### ISSUE TITLE
[NETSDKE2E]With NET9 preview 4 SDK installed, Reductant "build succeed" log displays during creating project in CLI.

### ISSUE THREAD

**Issue by vdanche** [dotnet/msbuild#10004]
### Issue Description

With NET9 preview 4 SDK installed, Reductant "build succeed" log displays during creating project in CLI.

### Steps to Reproduce

Affect build:
9.0.100-preview.4.24211.4 SDK from [dotnet/installer: .NET SDK Installer (github.com)](https://github.com/dotnet/installer)
Affected Product Language:

Steps to reproduce:

1.dotnet new console in CLI
2.Check log displaying during creating console.

### Expected Behavior

console can be created successfully, and log can be display well.

### Actual Behavior

Reductant "build succeed" log displays during creating project in CLI.
![image](https://github.com/dotnet/msbuild/assets/65637796/015b3112-52e7-4dc3-bf80-63776ab5bb5f)

refer net8.0 as below:
![image](https://github.com/dotnet/msbuild/assets/65637796/6f813f1c-4f2c-4c68-a699-b3208ea1b9b3)

**Comment by vdanche** [comment]
Reductant "build succeed" log also display during running dotnet add package Microsoft.EntityFrameworkCore.Design.
![image](https://github.com/dotnet/msbuild/assets/65637796/3fa989d2-01b6-457e-8ac5-45fea235b467)

Net 8.0 SDK(not repro):
![image](https://github.com/dotnet/msbuild/assets/65637796/3fbd61df-2a68-4ffb-bc46-79eea17cecee)

**Comment by ChenhuiYuan01** [comment]
This issue is also repro on Linux.
![con](https://github.com/dotnet/msbuild/assets/92560562/4abf9693-6468-4625-8dd4-17458f53d7db)
![ef](https://github.com/dotnet/msbuild/assets/92560562/dcada21c-e85a-4394-ab08-2531145b8723)

**Comment by v-xiaofchen** [comment]
This issue also repro on Mac.

**Comment by vdanche** [comment]
This issue has been fixed on 9.0.100-preview.5.24256.12 SDK
![image](https://github.com/dotnet/msbuild/assets/65637796/a5a49574-148b-4465-8009-86693d0c4228)
