### ISSUE TITLE
Improve Severities model

### ISSUE THREAD

**Issue by maridematte** [dotnet/msbuild#10097]
### Context

* https://github.com/dotnet/msbuild/pull/9853#discussion_r1539496108
* https://github.com/dotnet/msbuild/pull/9853#discussion_r1539480094

### Goals

 * Severities aligned with Roslyn - https://learn.microsoft.com/en-us/visualstudio/code-quality/use-roslyn-analyzers?view=vs-2022#configure-severity-levels, we can omit `silent`.
 * The `isEnabled`configuration is passed to Analyzer `Initialize` call - and is basically an evaluation of `Severity != BuildAnalyzerResultSeverity.None`
 * Logic properly reflected in the design doc

**Comment by f-alizada** [comment]
Taking this thing to work on since it is aligned with the linked issue.
