### ISSUE TITLE
[Feature Request]: Diagnostic log "Environment at start of build" should record whether long paths enabled

### ISSUE THREAD

**Issue by hickford** [dotnet/msbuild#10151]
### Summary

MSBuild's diagnostic logging `-v:diagnostic`  should record whether long paths are enabled.

### Background and Motivation

msbuild.exe supports long paths on Windows since 16.0 https://github.com/dotnet/msbuild/releases/tag/v16.0.461.62831

> MSBuild.exe now supports long paths on Windows

However Windows users have to *additionally* opt in by setting a registry key/ https://learn.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=registry#enable-long-paths-in-windows-10-version-1607-and-later

> Starting in Windows 10, version 1607, MAX_PATH limitations have been removed from common Win32 file and directory functions. However, you must opt-in to the new behavior. ... The registry key Computer\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\FileSystem\LongPathsEnabled (Type: REG_DWORD) must exist and be set to 1

### Proposed Feature

MSBuild's diagnostic logging `-v:diagnostic` includes an "environment at start of build section". This should record whether long paths are enabled in Windows.

**Comment by AR-May** [comment]
Team triage: This is absolutely a great idea. @hickford are you interested in contributing to MSBuild and picking this issue up?

**Comment by hickford** [comment]
I don't have the expertise.

**Comment by rainersigwald** [comment]
@hickford no problem--a great idea is helpful all on its own!
