### ISSUE TITLE
[Bug]: dotnet restore throws error NU1202 with dotnet sdk 8.0.300 for some centrally managed packages

### ISSUE THREAD

**Issue by tomasfabian** [dotnet/msbuild#10157]
### Issue Description

After upgrading to the latest .NET SDK 8.0.300, the build process fails when using **ManagePackageVersionsCentrally** in case of some packages such as `FluentAssertions`.

### Steps to Reproduce

Running the `dotnet restore` Demo.sln command with the configuration below fails to restore packages:

UnitTest.csproj:
```xml
<Project Sdk="MSTest.Sdk/3.3.1">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <PropertyGroup>
        <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="FluentAssertions" />
    </ItemGroup>

</Project>
```
Directory.Packages.props
```xml
<?xml version="1.0" encoding="utf-8"?>
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ItemGroup>
    <PackageVersion Include="FluentAssertions" Version="6.12.0" />
  </ItemGroup>
</Project>
```

This works as expected:
```xml
<Project Sdk="MSTest.Sdk/3.3.1">

  <PropertyGroup>
      <TargetFramework>net8.0</TargetFramework>
      <IsPackable>false</IsPackable>
  </PropertyGroup>

    <PropertyGroup>
        <ManagePackageVersionsCentrally>false</ManagePackageVersionsCentrally>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="FluentAssertions" Version="6.12.0" />
    </ItemGroup>
</Project>
```

### Expected Behavior

Running `dotnet restore` with .NET SDK 8.0.300 should work the same way as it does with .NET SDK 8.0.205.

### Actual Behavior

A much older version of the package is being used/reported instead of the referenced one:
_C:\UnitTests.csproj : error NU1202: Package FluentAssertions 1.3.0.1 is not compatible with net8.0 (.NETCoreApp,Version=v8.0). Package FluentAssertions 1.3.0.1 supports: [C:\Demo.sln]_

**Comment by AR-May** [comment]
Team triage: it seems like it is a NuGet issue, moving it to NuGet repository.

**Comment by AR-May** [comment]
This issue was moved to NuGet/Home#13453
