### ISSUE TITLE
[Bug]: Cannot use Microsoft.Build.Utilities.Core 17.10.4 NuGet package

### ISSUE THREAD

**Issue by avivanoff** [dotnet/msbuild#10167]
### Issue Description

Microsoft.Build.Utilities.Core 17.10.4 NuGet package cannot be used because of missing dependency Microsoft.Build.Framework >= 17.10.4. The latest available version of Microsoft.Build.Framework is 17.10.0-preview-24081-01.

### Steps to Reproduce

1. Create a project and reference Microsoft.Build.Utilities.Core 17.10.4 NuGet package.
2. Build the project.

### Expected Behavior

Project should build.

### Actual Behavior

Project does not build:

error NU1102: Unable to find package Microsoft.Build.Framework with version (>= 17.10.4)
error NU1102:   - Found 50 version(s) in nuget.org [ Nearest version: 17.10.0-preview-24081-01 ]

**Comment by rainersigwald** [comment]
Try again, please -- it should be there now https://www.nuget.org/packages/Microsoft.Build.Framework/17.10.4.

**Comment by avivanoff** [comment]
Now I am getting:

NU1603: Warning As Error: Microsoft.VSSDK.BuildTools 17.10.2179 depends on Microsoft.VisualStudio.SDK.Analyzers (>= 17.7.20) but Microsoft.VisualStudio.SDK.Analyzers 17.7.20 was not found. An approximate best match of Microsoft.VisualStudio.SDK.Analyzers 17.7.22 was resolved.

But I guess this is for the different package.

**Comment by pfusik** [comment]
> NU1603: Warning As Error: Microsoft.VSSDK.BuildTools 17.10.2179 depends on Microsoft.VisualStudio.SDK.Analyzers (>= 17.7.20) but Microsoft.VisualStudio.SDK.Analyzers 17.7.20 was not found. An approximate best match of Microsoft.VisualStudio.SDK.Analyzers 17.7.22 was resolved.

I get the same error on VS 2022 17.10.1. Why `17.7.22` is not `>= 17.7.20` ?

**Comment by AR-May** [comment]
@pfusik It is a warning, so you could suppress it. However, `Microsoft.VSSDK.BuildTools` is not part of this repo. Please file a VS feedback for this issue.
