### ISSUE TITLE
[Bug]: CI/CD pipeline broken after update from 17.9 to 17.10: no Appx packages generated

### ISSUE THREAD

**Issue by JochemPalmsens** [dotnet/msbuild#10182]
### Issue Description

We're running a Github action for our release branches that builds, signs and uploads our apps to the app center.
Yesterday we updated the build tools from 17.9 to 17.10 and now the pipeline is broken.

As a build step, the action issues the command:
```
msbuild [our app name].sln /t:Apps\[our app identifier] /p:Platform=x64 /p:Configuration=ReleaseDeployment /p:PackageVersion=1.2.0.203 /p:AppxBundlePlatforms=x64 /p:AppxBundle=Always /p:UapAppxPackageBuildMode=StoreUpload /p:AppxPackageSigningEnabled=False "/p:AppxPackageDir=E:\1\trunk\trunk/AppxPackages/" /m
```
this used to generate the artifacts in the directory `E:\1\trunk\trunk\AppxPackages\` with version 17.9, however, with version 17.10 the directory isn't generated at all. So the next steps fail as the files aren't found.

I've been looking around for a breaking change in 17.10, but found nothing. I've also tried to "fix" the inconsistent slashes in the path, but that didn't matter (and 17.9 worked fine). So I guess this is a bug?

### Steps to Reproduce

`msbuild [our app name].sln /t:Apps\[our app identifier] /p:Platform=x64 /p:Configuration=ReleaseDeployment /p:PackageVersion=1.2.0.203 /p:AppxBundlePlatforms=x64 /p:AppxBundle=Always /p:UapAppxPackageBuildMode=StoreUpload /p:AppxPackageSigningEnabled=False "/p:AppxPackageDir=E:\1\trunk\trunk/AppxPackages/" /m`

I cannot share the code, as it's IP. But if this is actually broken, more people should quickly discover this, right? Seems quite essential.

### Expected Behavior

msbuild generates the .msix file in the `E:\1\trunk\trunk/AppxPackages/` (sub) directories.

### Actual Behavior

The `E:\1\trunk\trunk/AppxPackages/` is not being generated _at all_.

### Versions & Configurations

MSBuild version 17.10.4+10fbfbf2e for .NET Framework
17.10.4.21802

**Comment by JochemPalmsens** [comment]
OK, small update here. I've taken the WinUI3 default template project and ran the same command. I got the following output:
![afbeelding](https://github.com/dotnet/msbuild/assets/106731455/51944675-acd2-40a8-b6a1-6641b2cf91ac)

Now back to my CI/CD pipeline: it seems that is no longer running these "_GenerateAppxPackageFile:" steps:
![afbeelding](https://github.com/dotnet/msbuild/assets/106731455/a65ed060-49ff-42b8-a5e5-5a2dfebed973)

It just stops after the `_CreateR2RImages:` step.

Was there a breaking change in a previous version that I missed, and for which the support was dropped?

**Comment by JochemPalmsens** [comment]
Never mind: this is probably not a bug (I was "blamed" for this by my colleagues, as I had updated the VS version on the build server.)

Turned out that it was caused by somebody adding MAUI components to out WinUI3 project and updating the csproj file.

`<Project Sdk="Microsoft.NET.Sdk">` was changed to `<Project Sdk="Microsoft.NET.Sdk.Razor">`
and these lines were added
```xml
	  <UseMaui>true</UseMaui>
	  <MauiEnablePlatformUsings>true</MauiEnablePlatformUsings>
	  <SingleProject>true</SingleProject>
	  <EnableDefaultCssItems>false</EnableDefaultCssItems>
```

one of these broke the CI/CD pipeline as the msix files aren't generated.
Still, the app runs fine... so why aren't the appx packages generated?

**Comment by surayya-MS** [comment]
@JochemPalmsens, I'm happy to hear that you managed to find the problem. Given that this not a MSBuild bug, closing this issue.

Note: changing the project sdk most likely is the problem a problem. I cannot tell for sure without seing the project file.
`Microsoft.NET.Sdk` fully supports WinUI3 projects, whereas `Microsoft.NET.Sdk.Razor` is not designed for desktop applications like WinUI3. The Razor SDK is meant for web applications and might cause build errors or unexpected behavior when used in a WinUI3 project.
