### ISSUE TITLE
Q: Verifying NuGet single multi targeting build assets importation

### ISSUE THREAD

**Issue by mwpowellhtx** [dotnet/msbuild#10197]
### Discussed in https://github.com/dotnet/msbuild/discussions/10192

<div type='discussions-op-text'>

<sup>Originally posted by **mwpowellhtx** May 30, 2024</sup>
Hello,

I am evaluating my [`BumpAssemblyVersions`](https://github.com/mwpowellhtx/BumpAssemblyVersions) project, whether I need to update and pull forward appropriate forwards/backwards compatible [`MSBuild`](https://github.com/dotnet/msbuild) dependencies. I am assuming I do since the last known [`Microsoft.Build`](https://nuget.org/packages/Microsoft.Build) dependency at `1.8.0` was something like `15.9.X` (specifically `15.9.20`). Also `Engine`, `Framework`, `Utilities.Core`, couple of other odd ones as well. Yeah I know it has been a minute since I had to look at this.

Best guess, I need to rebuild with the updated versions. 

Question when I do that, is it backwards compatible with the prior versions? `15+`, `16+`, `17+`? Or do I need specifically built projects around those?

Thanks...</div>

Could use some sort of acknowledgement, clarification around this. Two main questions, if you don't mind.

1. Do we in fact need to pull forward our `Microsoft.Build` suite dependencies to current `17.+` versions. The naive plausible impression is, probably yes, but I want to understand that better.
1.  Whether we do, do we also need to consider projects that focus on specific `VS` tiers, `2017`, `2019`, `2022+`, for example?

Alternatively, I am also open to considering current build technologies, if possible. The main goals of my project are to bump versions, in whatever forms they may be presented.

1. In `CSPROJ` form, as _Xml elements_.
1. In source form, i.e. as in `AssemblyInfo.cs` style `Attribute` instances.

Those are the main goals. Maybe there are better ways of doing that today.

**Comment by mwpowellhtx** [comment]
Okay, I ran build with a more detailed verbosity logging. I found this entry, which beggars the question, which targets are involved from one generation of VS to the next? And is there a way in which to gauge that within a `.PROPS` or `.TARGETS` file?

From a VS prompt:

```
L:\Source\...\xUnit.Fluently\master\src\xunit.fluently.assert>msbuild xunit.fluently.assert.csproj -t:Rebuild -fl -flp:logFile=msbuild.log;verbosity=detailed
```

With the following log output:

```
The target "DispatchToInnerBuilds" listed in a BeforeTargets attribute at "L:\Source\Ellumination Technologies\xUnit.Fluently\master\src\packages\bumpassemblyversions\1.8.0\build\BumpAssemblyVersions.targets (39,68)" does not exist in the project, and will be ignored.
```

From the [_BAV source_](https://github.com/mwpowellhtx/BumpAssemblyVersions/blob/602db74feee8d89c054177955efbed40f2dac52f/src/BumpAssemblyVersions/build/BumpAssemblyVersions.targets#L39). The idea there is, we want to be building in the outer most containing target, and not for every inner Build instance, i.e. when things such as multi-target `TargetFrameworks` are involved. i.e. _bump once per Build or Rebuild request only_.

So we need to know that from `15+`, `16+`, and `17+`, please. Which target(s) are most approproate.

After that, whether also we should be thinking about keeping up with the `Microsoft.Build` dependencies, and in what level of detail.

This is also curious, however, **_what?_** empty? I am confused.

```
Target "BumpAssemblyVersionsBeforeBuild" skipped, due to false condition; ('$(TargetFrameworks)' == '') was evaluated as ('netstandard2.0;netstandard2.1' == '').
```

It is definitely not empty.

```Xml
<TargetFrameworks>netstandard2.0;netstandard2.1</TargetFrameworks>
```

Those are the two main areas, `TargetFrameworks` empty, and changing `<Target/>` names from one generation `VS` to the next.

**Comment by mwpowellhtx** [comment]
When I unpack what this actually says, it makes no sense whatsoever. So, we cannot integrate our 3P targets assuming existence of internally provided targets? That makes no sense whatsoever. How do we add value to the build, bumping versions or whatever, when we cannot do that? _"Does not exist in the project, and will be ignored"_, **_but of course it does not exist in the project, which is precisely the point_**, we are trying to play nice integrating with msbuild targets!

```
The target "DispatchToInnerBuilds" listed in a BeforeTargets attribute at "L:\Source\Ellumination Technologies\xUnit.Fluently\master\src\packages\bumpassemblyversions\1.8.0\build\BumpAssemblyVersions.targets (39,68)" does not exist in the project, and will be ignored.
```

Just for grins, listing the targets, the target in question does exist, and would be encountered, apparently, so it is not that the target does not exist. Actually, a better listing, if possible, would be to not prune for uniqueness; I just want to see the dry run, i.e. _all the targets as they would normally be encountered, in the order in which they would be encountered_. I do not know if that option is available on the _msbuild_ CL.

```
L:\Source\...\xUnit.Fluently\master\src\xunit.fluently.assert>msbuild xunit.fluently.assert.csproj --targets
```

```
MSBuild version 17.10.4 for .NET Framework
AfterSdkPublish
PreBuild
PackableOnGeneratePackageOnBuild
_CheckForUnsupportedArtifactsPath
_GetRequiredWorkloads
ResolvePackageDependenciesDesignTime
CollectSDKReferencesDesignTime
CollectResolvedSDKReferencesDesignTime
ResolveFrameworkReferences
ResolveProjectReferencesDesignTime2
ResolveFrameworkReferencesDesignTime
CollectPackageReferences
CollectSuggestedWorkloads
_CheckCompileDesignTimePrerequisite
CollectAnalyzersDesignTime
CollectResolvedCompilationReferencesDesignTime
CollectUpToDateCheckInputDesignTime
CollectUpToDateCheckOutputDesignTime
CollectUpToDateCheckBuiltDesignTime
CollectBuildAccelerationIncompatiblePackageDesignTime
CollectCopyToOutputDirectoryItemDesignTime
_FixRazorEditorConfigFiles
CompileDesignTime
GetTargetFrameworks
_ComputeTargetFrameworkItems
GetTargetFrameworksWithPlatformFromInnerBuilds
InitializeSourceControlInformation
DispatchToInnerBuilds
Build
_SetBuildInnerTarget
Clean
Rebuild
Restore
GenerateRestoreGraphFile
CollectCentralPackageVersions
CollectPackageDownloads
CollectFrameworkReferences
_LoadRestoreGraphEntryPoints
_FilterRestoreGraphProjectInputItems
_GenerateRestoreGraph
_GenerateRestoreGraphProjectEntry
_GenerateRestoreSpecs
_GenerateDotnetCliToolReferenceSpecs
_GetProjectJsonPath
_GetRestoreProjectStyle
EnableIntermediateOutputPathMismatchWarning
_GetRestoreTargetFrameworksOutput
_GetRestoreTargetFrameworksAsItems
_GetRestoreSettings
_GetRestoreSettingsCurrentProject
_GetRestoreSettingsAllFrameworks
_GetRestoreSettingsPerFramework
_GenerateRestoreProjectSpec
_GenerateProjectRestoreGraph
_GenerateRestoreDependencies
_GenerateProjectRestoreGraphAllFrameworks
_GenerateProjectRestoreGraphCurrentProject
_GenerateProjectRestoreGraphPerFramework
_GenerateRestoreProjectPathItemsCurrentProject
_GenerateRestoreProjectPathItemsPerFramework
_GenerateRestoreProjectPathItems
_GenerateRestoreProjectPathItemsAllFrameworks
_GenerateRestoreProjectPathWalk
_GetAllRestoreProjectPathItems
_GetRestoreSettingsOverrides
_GetRestorePackagesPathOverride
_GetRestoreRepositoryPathOverride
_GetRestoreSourcesOverride
_GetRestoreFallbackFoldersOverride
_GetRestoreTargetFrameworkOverride
_GetTargetFrameworkOverrides
_IsProjectRestoreSupported
InitializeSourceControlInformationFromSourceControlManager
SetEmbeddedFilesFromSourceControlManagerUntrackedFiles
_SourceLinkHasSingleProvider
_InitializeSourceControlInformationFromSourceControlManager
SourceControlManagerPublishTranslatedUrls
_InitializeGitHubSourceLinkUrl
TranslateGitHubUrlsInSourceControlInformation
_InitializeGitLabSourceLinkUrl
TranslateGitLabUrlsInSourceControlInformation
_InitializeAzureReposGitSourceLinkUrl
TranslateAzureReposGitUrlsInSourceControlInformation
_InitializeBitbucketGitSourceLinkUrl
TranslateBitbucketGitUrlsInSourceControlInformation
Publish
GetAllRuntimeIdentifiers
GetPackagingOutputs
CollectApiCompatInputs
RunPackageValidation
GetReferencesForApiCompatValidatePackage
_GetReferencePathFromInnerProjects
_GetAbsoluteOutputPathsForPack
_GetOutputItemsFromPack
_GetTargetFrameworksOutput
_PackAsBuildAfterTarget
_CleanPackageFiles
_CalculateInputsOutputsForPack
Pack
_IntermediatePack
GenerateNuspec
_InitializeNuspecRepositoryInformationProperties
_LoadPackInputItems
_GetProjectReferenceVersions
_GetProjectVersion
_WalkEachTargetPerFramework
_GetFrameworksWithSuppressedDependencies
_GetFrameworkAssemblyReferences
_GetBuildOutputFilesWithTfm
_GetTfmSpecificContentForPackage
_GetDebugSymbolsWithTfm
_AddPriFileToPackBuildOutput
_GetPackageFiles
```

**Comment by mwpowellhtx** [comment]
As a thought experiment, I tried with both `VS2019` and `VS2022` shell command line build, with similar results. Neither of them are bumping versions like I expect.

```
...>msbuild xunit.fluently.assert.csproj -t:Rebuild -fl -flp:logFile=msbuild.log;verbosity=detailed
```

2019 build log attached:

[vs2019_msbuild.log](https://github.com/user-attachments/files/15526072/vs2019_msbuild.log)

2022 build log attached:

[vs2022_msbuild.log](https://github.com/user-attachments/files/15526080/vs2022_msbuild.log)

**Comment by mwpowellhtx** [comment]
As a thought experiment, I also tried also in a `VS2017` prompt, and does not support `netstandard2.0+`, apparently; unless maybe I can persuade a more up to date `Sdk` in that instance.

**Comment by mwpowellhtx** [comment]
As a clue, might possibly be related to a [recent NuGet single/multi-targeting strategy](https://learn.microsoft.com/en-us/visualstudio/msbuild/target-build-order). Definitely it is something we can investigate further.

**Comment by mwpowellhtx** [comment]
💡 I think we may have something here, the [_NuGet folder structures_](https://learn.microsoft.com/en-us/nuget/concepts/msbuild-props-and-targets#build-folders) have changed, definitely divergent from when I originally pursued the BAV solution. It's a bit tricky coordinating single/multi _"one and only one pass"_ strategies given that, probably redundant to a certain extent, but we'll investigate how we can orchestrate our build process in that area.

💡 another clue, we definitely need to be aware of, no need to do any direct inclusions of any `.targets` or `.props`, as it seems these would be [_automatically rolled into the build process_](https://learn.microsoft.com/en-us/nuget/concepts/msbuild-props-and-targets#build-folders).

We'll pursue both of these angles and see if we can persuade a more kosher _NuGet savvy_ process.

**Comment by mwpowellhtx** [comment]
So in summary thus far, I think I've [_identified perhaps 75% of the issue_](https://github.com/dotnet/msbuild/issues/10197#issuecomment-2144004384) and have a fairly strong grasp at how things have changed with regard to the latest nuget versions. If I understand things correctly, that should simplify much of my packaging and delivery, with the `build` and `buildMultiTargeting` there to receive my `.props` and `.targets`, and the `.g.` wiring _"just works"_; that'd be fantastic! Plus I can focus on just the appropriate `BeforeTargets` in either instance, since the outer <Import/> manages the `$(TargetFramework)` conditions for me, no muss no fuss.

The remaining part I need to clarify, pulling my `Microsoft.Build` packages forward to latest versions. Is that backwards compatible? And to what degree do I need to think about that aspect? Currently as stated have been in the `15.9+` range.

**Comment by AR-May** [comment]
Hello @mwpowellhtx! As for the remaining part: I believe I answered to that in the Discussions.
One more tip that might be useful for you when you figure out what is going during the build. I see that you use file logger. It is very beneficial to investigate what is happening with your builds using the binlog: https://github.com/dotnet/msbuild/blob/main/documentation/wiki/Binary-Log.md
You can check when the target was run/why it was skipped etc.

**Comment by mwpowellhtx** [comment]
> Hello @mwpowellhtx! As for the remaining part: I believe I answered to that in the Discussions.

Yes, thank you. For now, I may pin the idea of pulling `Microsoft.Build` dependencies forward, but we'll see. Remains to be seen at the moment.

> One more tip that might be useful for you when you figure out what is going during the build. I see that you use file logger. It is very beneficial to investigate what is happening with your builds using the binlog: https://github.com/dotnet/msbuild/blob/main/documentation/wiki/Binary-Log.md You can check when the target was run/why it was skipped etc.

> Hello @mwpowellhtx! As for the remaining part: I believe I answered to that in the Discussions. One more tip that might be useful for you when you figure out what is going during the build. I see that you use file logger. It is very beneficial to investigate what is happening with your builds using the binlog: https://github.com/dotnet/msbuild/blob/main/documentation/wiki/Binary-Log.md You can check when the target was run/why it was skipped etc.

Good to know. The messages I did receive were not making a lot of sense, at least in the textual format. That is, until I was clued in via discord channels as to the NuGet variable being factored in. This I was unwaware of, more than likely it is because of my targets not landing in an appropriate `build` or `buildMultiTargeting` directory, for instance. Given that assumption, the `MSBuild` messages start making a lot more sense.

In closing, will hang onto the discussion and issues for now. When I start to see positive results, will circle around and close out.

**Comment by mwpowellhtx** [comment]
Need some clarification, and getting some mixed feedback from discord. From _single-_ to _multi-targeting scenarios_, I want for my targets to evaluate exactly once and only once, regardless of the overarching `$(TargetFramework)` context. Which if we understand the `NuGet` variable, `build` is evaluating for each and every inner build, whereas, possibly, `buildMultiTargeting` is evaluating for the _multi- scenario_ for the outer build. This is pretty critical to coordinating my targets, so I need to understand that better, if possible.

**Comment by mwpowellhtx** [comment]
Okay, so initial single-targeting feedback, so far so good.

However, in the multi-targeting scenario, it is not working so good. I think the inner is getting confused from the outer. This is my build output. At least bumps are happening, but as you can see, multiple times. Presumably for outer, and each of the inners.

```
1>'MultiTargeting.ProjXml.Demo.csproj': Bumped 'Version' from '2024.158.1550.2' to '2024.158.1550.3'
1>'MultiTargeting.ProjXml.Demo.csproj': Bumped 'AssemblyVersion' from '2024.158.1550.2' to '2024.158.1550.3'
1>'MultiTargeting.ProjXml.Demo.csproj': Bumped 'FileVersion' from '2024.158.1550.2' to '2024.158.1550.3'
1>'MultiTargeting.ProjXml.Demo.csproj': Bumped 'InformationalVersion' from '2024.158.1550.2' to '2024.158.1550.3'
1>'MultiTargeting.ProjXml.Demo.csproj': Bumped 'PackageVersion' from '2024.158.1550.2' to '2024.158.1550.3'

1>'MultiTargeting.ProjXml.Demo.csproj': Bumped 'Version' from '2024.158.1550.3' to '2024.158.1550.4'
1>'MultiTargeting.ProjXml.Demo.csproj': Bumped 'AssemblyVersion' from '2024.158.1550.3' to '2024.158.1550.4'
1>'MultiTargeting.ProjXml.Demo.csproj': Bumped 'FileVersion' from '2024.158.1550.3' to '2024.158.1550.4'
1>'MultiTargeting.ProjXml.Demo.csproj': Bumped 'Version' from '2024.158.1550.3' to '2024.158.1550.4'
1>'MultiTargeting.ProjXml.Demo.csproj': Bumped 'InformationalVersion' from '2024.158.1550.3' to '2024.158.1550.4'
1>'MultiTargeting.ProjXml.Demo.csproj': Bumped 'AssemblyVersion' from '2024.158.1550.3' to '2024.158.1550.4'
1>'MultiTargeting.ProjXml.Demo.csproj': Bumped 'FileVersion' from '2024.158.1550.3' to '2024.158.1550.4'
1>'MultiTargeting.ProjXml.Demo.csproj': Bumped 'PackageVersion' from '2024.158.1550.3' to '2024.158.1550.4'
1>'MultiTargeting.ProjXml.Demo.csproj': Bumped 'InformationalVersion' from '2024.158.1550.3' to '2024.158.1550.4'
1>'MultiTargeting.ProjXml.Demo.csproj': Bumped 'PackageVersion' from '2024.158.1550.3' to '2024.158.1550.4'
```

One bump from at least `.2` to `.3`; then another from `.3` to `.4`. Spacing added for bit of clarity in the output.

However, I'm not sure also maybe specs are not also somehow being piled up incorrectly from inner to outer. Maybe we also need `$(TargetFramework)` comprehension conditioning those, who knows.

Might be interesting to also report the number of specifications we think are being processed.

Thoughts in the multi- scenario... would it be possible somehow to inject a key file or something on first run? All other iterations forward from that point would be ignored when the file exists? Afterwards delete it.

**Comment by mwpowellhtx** [comment]
So far the best thing I could come up with is to better condition the specs themselves. If there are better ideas, I am open to them.

```xml
<ItemGroup Condition="'$(TargetFramework)' == ''">
    <!--               ^^^^^^^^^^^^^^^^^^     -->
    <BumpVersionSpec Include="Version" DefaultVersion="0.0.0.0" CreateNew="true" UseUtc="true" MayReset="true" MajorProviderTemplate="YearVersion" MinorProviderTemplate="DayOfYear" PatchProviderTemplate="HourMinute" BuildProviderTemplate="Increment" />
    <BumpVersionSpec Include="AssemblyVersion" DefaultVersion="0.0.0.0" CreateNew="true" UseUtc="true" MayReset="true" MajorProviderTemplate="YearVersion" MinorProviderTemplate="DayOfYear" PatchProviderTemplate="HourMinute" BuildProviderTemplate="Increment" />
    <BumpVersionSpec Include="FileVersion" DefaultVersion="0.0.0.0" CreateNew="true" UseUtc="true" MayReset="true" MajorProviderTemplate="YearVersion" MinorProviderTemplate="DayOfYear" PatchProviderTemplate="HourMinute" BuildProviderTemplate="Increment" />
    <BumpVersionSpec Include="InformationalVersion" DefaultVersion="0.0.0.0" CreateNew="true" UseUtc="true" MayReset="true" MajorProviderTemplate="YearVersion" MinorProviderTemplate="DayOfYear" PatchProviderTemplate="HourMinute" BuildProviderTemplate="Increment" />
    <BumpVersionSpec Include="PackageVersion" DefaultVersion="0.0.0.0" CreateNew="true" UseUtc="true" MayReset="true" MajorProviderTemplate="YearVersion" MinorProviderTemplate="DayOfYear" PatchProviderTemplate="HourMinute" BuildProviderTemplate="Increment" />
</ItemGroup>
```

**Comment by mwpowellhtx** [comment]
@AR-May curious, any other suggestions than my recent learnings from it? If there's a better idea, I'm open to it, So far seems like better coordination with `TargetFramework` is the right approach, however.

**Comment by mwpowellhtx** [comment]
@AR-May Follow up, I went the next step, from _"raw"_ importation of sandboxed BAV assets, to local NuGet package sources.

However, we are having difficulty, it seems that only the `buildTransitive` assets are being imported. Whereas, I half expected, based on some other _.generated._ imports, that I would see both `build` and `buildMultiTargeting` assets also imported, under `TargetFramework` conditions. However, neither of these is happening. Either/both of these is critical, because we are making the assumption we should receive one or the other, and we make appropriate `.props` declarations, which our transitive (i.e. _"shared"_ ?) assets then utilize.

This is an example generated nuget props and targets. Trying to test integration of my `BumpAssemblyVersions` package from local sources. However, only the `buildTransitive` bits are being imported. What about the `build` and `buildMultiTargeting`, which are also there? It is critical that ALL of those get imported, regardless.

```xml
<ImportGroup Condition=" '$(ExcludeRestorePackageImports)' != 'true' ">
  <Import Project="$(NuGetPackageRoot)\bumpassemblyversions\1.9.0\buildTransitive\BumpAssemblyVersions.props" Condition="Exists('$(NuGetPackageRoot)\bumpassemblyversions\1.9.0\buildTransitive\BumpAssemblyVersions.props')" />
</ImportGroup>
```

```xml
<ImportGroup Condition=" '$(ExcludeRestorePackageImports)' != 'true' ">
  <Import Project="C:\Program Files\dotnet\sdk\NuGetFallbackFolder\netstandard.library\2.0.3\build\netstandard2.0\NETStandard.Library.targets" Condition="Exists('C:\Program Files\dotnet\sdk\NuGetFallbackFolder\netstandard.library\2.0.3\build\netstandard2.0\NETStandard.Library.targets')" />
  <Import Project="$(NuGetPackageRoot)\bumpassemblyversions\1.9.0\buildTransitive\BumpAssemblyVersions.targets" Condition="Exists('$(NuGetPackageRoot)\bumpassemblyversions\1.9.0\buildTransitive\BumpAssemblyVersions.targets')" />
</ImportGroup>
```

**Comment by mwpowellhtx** [comment]
For what we are trying to accomplish, I suppose it would not be the worst thing to just factor `build` (`buildMultiTargeting`) property declarations instead to `buildTransitive`, and do the conditioning within, i.e.

```xml
<PropertyGroup Condition="'$(TargetFramework)' != ''">
    <BavBeforeTargets>BeforeBuild</BavBeforeTargets>
</PropertyGroup>

<PropertyGroup Condition="'$(TargetFramework)' == ''">
    <BavBeforeTargets>DispatchToInnerBuilds</BavBeforeTargets>
</PropertyGroup>
```

Which we then use, i.e. `BeforeTargets="$(BavBeforeTargets)"`.

**Comment by AR-May** [comment]
> @AR-May curious, any other suggestions than my recent learnings from it? If there's a better idea, I'm open to it, So far seems like better coordination with `TargetFramework` is the right approach, however.

@mwpowellhtx yes, it seems as you need to know whether `TargetFramework` or `TargetFrameworks` were used in the build. Also, consider using property `IsCrossTargetingBuild` to coordinate that you run the target for the outer build only.

**Comment by mwpowellhtx** [comment]
> > @AR-May curious, any other suggestions than my recent learnings from it? If there's a better idea, I'm open to it, So far seems like better coordination with `TargetFramework` is the right approach, however.
> 
> @mwpowellhtx yes, it seems as you need to know whether `TargetFramework` or `TargetFrameworks` were used in the build. Also, consider using property `IsCrossTargetingBuild` to coordinate that you run the target for the outer build only.

To clarify, I do not need to know per se, whether a subscriber project is _single-_ or _multi-targeting_. But I do need to respond accordingly. I thought that `build` and `buildMultiTargeting` was the way to convey those assets for `MSBuild` consumption under those conditions? But apparently all we get are `buildTransitive`. Is that behavior feature documented somewhere? And is that a bug? Or is that intended? And is it documented?

To clarify further, `IsCrossTargetingBuild` would not work in the single-targeting instance. Again, the baseline requirement is that my target runs before the outer-most build, agnostic of whether single- or multi-targeting.

From a prior discussion, the best possible time to do that, we think, is before `BeforeBuild` targets for _single_; before `DispatchToInnerBuilds` targets for _multi_. Again, assuming appropriate `build[MultiTargeting]` importation; or sufficient workarounds.

**Comment by rainersigwald** [comment]
@mwpowellhtx can we take several steps back here? What are you trying to do? How are you trying to do it? Are you a NuGet package, or logic in a single repo?

**Comment by mwpowellhtx** [comment]
> @mwpowellhtx can we take several steps back here? What are you trying to do? How are you trying to do it? Are you a NuGet package, or logic in a single repo?

It is deployed as a NuGet package. So we bumped into the change in `build[MultiTargeting|Transitive]` semantics. Were previously deploying `build` assets; but we want to support mutli-target scenarios as well.

Current best estimates are, can do our own internal conditioning, assuming the assets will prefer `buildTransitive` only.

```xml
<PropertyGroup Condition="'$(TargetFramework)' != ''">
    <BavBeforeTargets>BeforeBuild</BavBeforeTargets>
</PropertyGroup>

<PropertyGroup Condition="'$(TargetFramework)' == ''">
    <BavBeforeTargets>DispatchToInnerBuilds</BavBeforeTargets>
</PropertyGroup>
```

[`Discord MSBuild`](https://discord.com/channels/732297728826277939/732310858776182866) discussion duly noted, BTW.

Notwithstanding a complete reconsideration of our approach.

**Comment by mwpowellhtx** [comment]
@rainersigwald Appreciate the effort and attention helping us sort through all this.

Bit of feedback trying to make `buildTransitive` work, for starters.

_"When"_ are _transitive properties/targets_ `.g.` importations happening? The timing feels different from `build[MultiTargeting]` scenarios. i.e. we are not seeing `$(TargetFramework)` having been defined at that moment. At which point any assumptions that were depending upon `$(TargetFramework)` for anything are invalid.

At least in our current packaging approach, the alternative may be that if we deployed one `build` path, and another `buildMultiTargeting`, how could we best consolidate properties, targets, without necessarily having to duplicate a bunch of assets. Seems very repetitive in nature.

**Comment by rainersigwald** [comment]
> _"When"_ are _transitive properties/targets_ `.g.` importations happening? The timing feels different from `build[MultiTargeting]` scenarios. i.e. we are not seeing `$(TargetFramework)` having been defined at that moment.

the same import order applies. The difference you're observing may be because inner builds get TargetFramework defined "early" as a global property, while single-targeted builds have it defined in the body of the project file.

> if we deployed one `build` path, and another `buildMultiTargeting`, how could we best consolidate properties, targets, without necessarily having to duplicate a bunch of assets. Seems very repetitive in nature.

You can `<Import` a common file from the various scenarios.

**Comment by mwpowellhtx** [comment]
> > _"When"_ are _transitive properties/targets_ `.g.` importations happening? The timing feels different from `build[MultiTargeting]` scenarios. i.e. we are not seeing `$(TargetFramework)` having been defined at that moment.
> 
> the same import order applies. The difference you're observing may be because inner builds get TargetFramework defined "early" as a global property, while single-targeted builds have it defined in the body of the project file.

Which makes sense, perfectly understandable.

> > if we deployed one `build` path, and another `buildMultiTargeting`, how could we best consolidate properties, targets, without necessarily having to duplicate a bunch of assets. Seems very repetitive in nature.
> 
> You can `<Import` a common file from the various scenarios.

I understand we _"can"_ in principle. But NuGet balks over that while packaging, apparently... which is one reason we are considering does `builtTransitive` fit the bill. However, at the moment, it seems probably not; so we'll think on how to coordinate `build` versus `buildMultiTargeting`.

The good news is that at least in early end to end sandbox integration testing, we appear to be seeing a positive application of the strategies, at least to begin with. We are now end to end testing in a fully packaged environment.

Also, to be fair, 💯 acknowledging the concerns, suggestions, etc, conveyed via discord. First, we want to try to reposition best we can in the current delivery modality. Then we may consider alternative measures, git, hooks, more of a CI/CD outlook.

Okay doke... I think I understand what I need to do next stitching it back together again.

Best 🍻

**Comment by rainersigwald** [comment]
> NuGet balks over that while packaging, apparently

Say more please, NuGet shouldn't have any problems with this pattern.

**Comment by mwpowellhtx** [comment]
> > NuGet balks over that while packaging, apparently
> 
> Say more please, NuGet shouldn't have any problems with this pattern.

I shall; pulling that together just now.

**Comment by mwpowellhtx** [comment]
Updated the title reflecting the root cause what was sorted out. Closing.
