### ISSUE TITLE
[Kitten] Fix binskim warnings in msbuild pipeline

### ISSUE THREAD

**Issue by AR-May** [dotnet/msbuild#10249]
https://dev.azure.com/devdiv/DevDiv/_workitems/edit/2087296/?view=edit

**Comment by rainersigwald** [comment]
for the errors coming from drop.app, can we exclude that directory? cc @f-alizada

**Comment by rainersigwald** [comment]
[internal] https://eng.ms/docs/cloud-ai-platform/devdiv/one-engineering-system-1es/1es-docs/1es-pipeline-templates/features/sdlanalysis/baselines#azure-devops-based-builds

**Comment by rainersigwald** [comment]
#10271 pushed the priority of this down but we should still look into excluding the whole `.packages` directory since we don't redistribute it.

**Comment by AR-May** [comment]
I see no more binskim warnings in Ci
