### ISSUE TITLE
Serialize build cancellation event to the binlog

### ISSUE THREAD

**Issue by MichalPavlik** [dotnet/msbuild#10244]
#10055 will add new event that informs about build cancellation. When the PR is merged, we should serialize `BuildCanceledEventArgs` to binlog and update binlog viewer to display this event.

**Comment by JanKrivanek** [comment]
Just suggestions:

Btw. we should as well add de/serialization of `BuildCheckTracingEventArgs` and `BuildSubmissionStartedEventArgs` (the latter need to be introduced as well) - tracked under https://github.com/dotnet/msbuild/issues/10145

We might want to bundle that work under single BinaryLogger version bump - to minimize the churn.

Also - as we'll be on it - we might want to document the process: https://github.com/dotnet/msbuild/issues/10146
