### ISSUE TITLE
[Bug]: Running a specific target which depends on ResolveReferences fails when TargetFrameworks is specified

### ISSUE THREAD

**Issue by wnorvelleadc** [dotnet/msbuild#10254]
### Issue Description

The error error `MSB4057: The target "ResolveReferences" does not exist in the project.` is thrown when specifically running a target that depends on `ResolveReferences` in a project file that uses `<TargetFrameworks>` with one or more TFMs. The error does not happen when just running the build target or when using `<TargetFramework>`, even though the "problematic" target is still run in both cases. Additionally, specifying both build and problematic targets still throws the error.

### Steps to Reproduce

A minimal reproduction of the problem (has a readme and script for demonstrating the issue): [ResolveReferencesDoesNotExistRepro.zip](https://github.com/user-attachments/files/15873881/ResolveReferencesDoesNotExistRepro.zip)

All that's needed is a project file specifying `<TargetFrameworks>`, a target that depends on `ResolveReferences`, and then running that target with msbuild like so: `msbuild.exe /t:DependsOnResolveReferences ClassLibrary.csproj`

None of the following fix the issue: adding `/restore`, additionally specifying the build target, or specifying a solution instead of the project file.

### Expected Behavior

`#### The target was run ####` should be printed in the build log

### Actual Behavior

Failed build with `error MSB4057: The target "ResolveReferences" does not exist in the project.`

### Versions & Configurations

```
$ MSBuild.exe --version
MSBuild version 17.10.4+10fbfbf2e for .NET Framework
17.10.4.21802
```

**Comment by rainersigwald** [comment]
What would you expect to have happened at the point that your target runs in this case?

The reason `ResolveReferences` isn't defined in the "outer build" is that it only really makes sense for one of the specific `TargetFramework`s defined in the list, not for the "overall/outer" build that runs all of them.

**Comment by wnorvelleadc** [comment]
AFAICT, `ResolveReferences` is normally run once per TFM, so I would expect a target dependent on it would also get run once per TFM.

Perhaps that's not how MSBuild is thinking about what targets to run? I'm certainly quite open to the possibility that we're just using it wrong.

**Comment by rainersigwald** [comment]
> AFAICT, `ResolveReferences` is normally run once per TFM, so I would expect a target dependent on it would also get run once per TFM.

That's correct.

> Perhaps that's not how MSBuild is thinking about what targets to run?

Yeah I think this is what's biting you. Multitargeted projects are fairly confusing with respect to supplemental targets.

What happens is that your target appears in _all three versions_ of the multitargeted project. In the two versions that have a TF set (the "inner" builds), it works just fine, as you can see if you add `-p:TargetFramework=net6.0` to your build command line.

But it also exists in the outer build--_un_like most of the build process. The outer build normally just calls `Build` on the inner builds. Your custom target will exist but not do anything in the outer build. But when you specify a target (and no TF property) on the command line, you're explicitly requesting it and by extension its `DependsOnTargets`--but then `ResolveReferences` wasn't imported, producing the error you saw.

This diagram may help? Or maybe not? I tried to make it clear in both the text and the diagram.

```mermaid
graph TD

subgraph Outer[Foo.csproj <i>no TF set</i>]
  BuildO[Build]
  DependsOnResolveReferencesO[DependsOnResolveReferences] --x|DependsOn| ResolveReferences[/<s>ResolveReferences</s>/]
end

subgraph TF1[Foo.csproj <i>TF=net6.0</i>]
  Build1[Build] --> BeforeBuild1[BeforeBuild]
  Build1 --> CoreBuild1[CoreBuild]
  CoreBuild1 --> RR1[ResolveReferences]
  Build1 --> AfterBuild1[AfterBuild]
  DependsOnResolveReferences1[DependsOnResolveReferences] -->|DependsOn| RR1
  DependsOnResolveReferences1 ==>|AfterTargets| RR1

end

subgraph TF2[Foo.csproj <i>TF=net6.0</i>]
  Build2[Build] --> BeforeBuild2[BeforeBuild]
  Build2 --> CoreBuild2[CoreBuild]
  CoreBuild2 --> RR2[ResolveReferences]
  Build2 --> AfterBuild2[AfterBuild]
  DependsOnResolveReferences2[DependsOnResolveReferences] -->|DependsOn| RR2
  DependsOnResolveReferences2 ==>|AfterTargets| RR2
end

BuildO --> Build1
BuildO --> Build2
```

**Comment by wnorvelleadc** [comment]
Ah, ok. That makes sense. Thank you very much for your help, it's been enlightening!
