### ISSUE TITLE
Is the double-checked locking pattern in BuildManager correct?

### ISSUE THREAD

**Issue by omajid** [dotnet/msbuild#10260]
https://github.com/dotnet/msbuild/blob/4a45d56330882a5e596e97d05ba568ec32e0603c/src/Build/BackEnd/BuildManager/BuildManager.cs#L3177-L3221

This doesn't quite match the double-checked locking pattern described at:

https://github.com/dotnet/runtime/blob/main/docs/design/specs/Memory-model.md#examples-and-common-patterns

It seems it might be possible to see a stale value of `_disposed` and then enter the lock and do the cleanup operations again. Is this safe to do because the cleanup operations are idempotent?

**Comment by JanKrivanek** [comment]
Team is currently overloaded - so postponing this.
Contributions are very welcome for this one.
