### ISSUE TITLE
[Bug]: CustomAnalyzerTest test fails in the CI pipeline

### ISSUE THREAD

**Issue by AR-May** [dotnet/msbuild#10277]
Links to the failure:
https://dev.azure.com/dnceng-public/public/_build/results?buildId=713198&view=results
https://dev.azure.com/dnceng-public/public/_build/results?buildId=714118&view=results

**Comment by AR-May** [comment]
I am disabling the test in vs17.11 and main branches. When fixed, please turn in on both vs17.11 and main.

**Comment by AR-May** [comment]
It seems like this test only fails on the version bump PRs:
https://github.com/dotnet/msbuild/pull/10268
https://github.com/dotnet/msbuild/pull/10270

We still need to fix it, but we can try to re-enable it meanwhile

**Comment by JanProvaznik** [comment]
Reenabled in https://github.com/dotnet/msbuild/pull/10307

https://github.com/dotnet/msbuild/blob/37ba950c4461abba607ba42e276e3892c5f61e59/src/BuildCheck.UnitTests/EndToEndTests.cs#L151
