### ISSUE TITLE
Duplicate item metadata present in generated editorconfig with CompilerVisibleItemMetadata

### ISSUE THREAD

**Issue by kzu** [dotnet/msbuild#10309]
### Issue Description

Suppose you have three totally independent packages that provide analyzers that leverage additional files to do some processing. Additionally, all packages consume the same file types (i.e. `.resx` files).

The first package might just add the files as `AdditionalFiles` and check for file extension inside the analyzer:

```xml
  <ItemGroup>
    <AdditionalFiles Include="@(EmbeddedResource)" />
  </ItemGroup>
```

The second package, however, might use an additional piece of metadata for the embedded resources to distinguish them, and thus has a slightly different version:

```xml
  <ItemGroup>
    <CompilerVisibleItemMetadata Include="AdditionalFiles" MetadataName="SourceItemType" />
    <!-- NOTE: added again, same identity, but with the additional metadata this time -->
    <AdditionalFiles Include="@(EmbeddedResource)" SourceItemType="EmbeddedResource" />
  </ItemGroup>
```

A third one might even use another totally different metadata annotation on the same items for its own purposes:

```xml
  <ItemGroup>
    <CompilerVisibleItemMetadata Include="AdditionalFiles" MetadataName="Foo" />
    <AdditionalFiles Include="@(EmbeddedResource)" Foo="Bar" />
  </ItemGroup>
```

The resulting editorconfig will currently now look like the following:

```editorconfig
[.../Resources.resx]
build_metadata.AdditionalFiles.SourceItemType = 
build_metadata.AdditionalFiles.SourceItemType = EmbeddedResource
build_metadata.AdditionalFiles.SourceItemType = 
build_metadata.AdditionalFiles.Foo = 
build_metadata.AdditionalFiles.Foo = 
build_metadata.AdditionalFiles.Foo = Bar
```

Regardless of the somewhat unintuitive behavior when retrieving this item's metadata from the analyzer using the `AnalyzerConfigOptionsProvider` for that file (will you get the empty value or `EmbeddedResource` when asking for `SourceItemType` with `.TryGetValue("build_metadata.AdditionalFiles.SourceItemType", out var value)`?), if you have many files and multiple packages leveraging compiler item metadata, this duplication can make the editorconfig unnecessarily large (and potentially impossible to get the right value, depending on whichever behavior Roslyn itself provides for such duplicated entries).

### Steps to Reproduce

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <!-- Some nuget package via .targets -->
  <ItemGroup>
    <AdditionalFiles Include="@(EmbeddedResource)" />
  </ItemGroup>

  <!-- Some other package via .targets -->
  <ItemGroup>
    <CompilerVisibleItemMetadata Include="AdditionalFiles" MetadataName="SourceItemType" />
    <!-- NOTE: added again, same identity, but with the additional metadata this time -->
    <AdditionalFiles Include="@(EmbeddedResource)" SourceItemType="EmbeddedResource" />
  </ItemGroup>

  <!-- A third package via .targets -->
  <ItemGroup>
    <CompilerVisibleItemMetadata Include="AdditionalFiles" MetadataName="Foo" />
    <!-- NOTE: added again, same identity, but with the additional metadata this time -->
    <AdditionalFiles Include="@(EmbeddedResource)" Foo="Bar" />
  </ItemGroup>

</Project>
```

### Expected Behavior

Emitted editorconfig similar to:

```editorconfig
[.../Resources.resx]
build_metadata.AdditionalFiles.SourceItemType = EmbeddedResource
build_metadata.AdditionalFiles.Foo = Bar
```

### Actual Behavior

Emitted editorconfig is actually similar to:

```editorconfig
[.../Resources.resx]
build_metadata.AdditionalFiles.SourceItemType = 
build_metadata.AdditionalFiles.SourceItemType = EmbeddedResource
build_metadata.AdditionalFiles.SourceItemType = 
build_metadata.AdditionalFiles.Foo = 
build_metadata.AdditionalFiles.Foo = 
build_metadata.AdditionalFiles.Foo = Bar
```

### Versions & Configurations

17.11.0.27902

**Comment by AR-May** [comment]
MSBuild team triage: Seems like it is the roslyn team that owns the corresponding target. Moving the issue to their repo.

**Comment by AR-May** [comment]
This issue was moved to dotnet/roslyn#74234
