### ISSUE TITLE
Rework the approach to bootstrap

### ISSUE THREAD

**Issue by YuliiaKovalova** [dotnet/msbuild#10300]
Introduce a simplified and transparent way for getting sdk bits and patching the changes to them using install-scripts.

**Comment by YuliiaKovalova** [comment]
Will resolve https://github.com/dotnet/msbuild/issues/10131

**Comment by JanKrivanek** [comment]
Is this expected to as well address https://github.com/dotnet/msbuild/issues/6566 and https://github.com/dotnet/msbuild/issues/7988?

**Comment by YuliiaKovalova** [comment]
> Is this expected to as well address #6566 and #7988?

yes, these two will be resolved.
