### ISSUE TITLE
Improve MSB4019 to include unevaluated path

### ISSUE THREAD

**Issue by danmoseley** [dotnet/msbuild#10333]
Example -- I got this
```
C:\git\aspire-samples\samples\AspireWithJavaScript\AspireJavaScript.Angular\node_modules\lmdb\dependencies\lz4\lib\dll\example\fullbench-dll.vcxproj(28,3): error MSB4019: The imported project "C:\Microsoft.Cpp.Default.pr
ops" was not found. Confirm that the expression in the Import declaration "\Microsoft.Cpp.Default.props" is correct, and that the file exists on disk.
```
this originates from this line in the .vcxproj:
```xml
<Import Project="$(VCTargetsPath)\Microsoft.Cpp.Default.props" />
```
It would be useful to know that `$(VCTargetsPath)` is evaluating to empty. It takes me a little closer to the problem. 

At the point that MSB4019 is emitted, can it access the unevaluated value of the attribute, and include that in the message?

**Comment by rainersigwald** [comment]
Yes we should definitely do this for the general case.

For your specific error (C++), we should extend the special-casing from https://github.com/dotnet/msbuild/issues/8967 to flag it.

**Comment by AR-May** [comment]
We soon should have a build-in analyzer for catching similar situations: #9883. But if we can improve the error here, that will also help.

**Comment by rainersigwald** [comment]
My proposed wording is:

```
Confirm that the expression in the Import declaration "$(VCTargetsPath)\Microsoft.Cpp.Default.props", which evaluated to "\Microsoft.Cpp.Default.props" is correct, and that the file exists on disk.
```

where the first one is the unevaluated value and the second one is the evaluated one we're currently logging.

**Comment by danmoseley** [comment]
> My proposed wording is:

Sounds good to me

**Comment by danmoseley** [comment]
do you label 'help wanted' to things like this?

**Comment by wpostma** [comment]
Random internet person wondering if this msbuild related task is going to hopefully make MSB4019 errors less confusing and misleading.

Currently I have a project which fails to build with this error:

Severity	Code	Description	Project	File	Line	Suppression State	Details
Error	MSB4019	The imported project "C:\cppdev\wordtsar-mercurial\QtMsBuild\Qt.props" was not found. Confirm that the expression in the Import declaration "C:\cppdev\wordtsar-mercurial\QtMsBuild\Qt.props" is correct, and that the file exists on disk.	wordtsar	C:\cppdev\wordtsar-mercurial\wordtsar.vcxproj	159		


The thing that annoys me is that QtMsBuild is not needed for this project to work, and QtMsBuild appears to get installed without my consent and not uninstalled by whatever THIRD PARTY vendor makes the QT Tools for Visual Studio.

I think that's a valid example case of where things are confusing when msbuild fails. I have no idea how to debug this issue, and am close to "format drive C and reinstall windows" as the only possible way to find and fix what's wrong with msbuild, or visual studio.

**Comment by jrdodds** [comment]
Please assign this issue to me. Thanks

**Comment by rainersigwald** [comment]
@jrdodds Done! Let us know if you hit any trouble.
