### ISSUE TITLE
Better error when UsingTask Reference Include is empty

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/msbuild#10343]
```xml
<Project>

    <UsingTask
      TaskName="WriteAttributes"
      TaskFactory="CodeTaskFactory"
      AssemblyFile="$(MSBuildToolsPath)\Microsoft.Build.Tasks.Core.dll">
    <Task>
      <Reference Include="$(CppCodeProvider)" />
      <Code Type="Class" Language="cs">
        <![CDATA[
public class WriteAttributes : Task
{
  public override bool Execute()
  {
    return true;
  }
}
      ]]>
      </Code>
    </Task>
  </UsingTask>

  <Target Name="Build">
    <WriteAttributes />
  </Target>

</Project>
```

The error isn't great here:

![image](https://github.com/dotnet/msbuild/assets/679326/fd4269ca-7c69-441b-b2cf-dd95b2f7e536)

**Comment by AR-May** [comment]
Team triage: Let's reword the message. Seems quite repetitive.

**Comment by GangWang01** [comment]
While looking into this issue, bug #10389 was found.

**Comment by GangWang01** [comment]
@baronfel would you like to suggest a better error message when UsingTask Reference Include is empty?

**Comment by baronfel** [comment]
The problem is that `Include` is required for the `Reference` element here, but it evaluated to empty? 

> `UsingTask`'s `Reference` cannot be empty, but was set to `$(CppCodeProvider)` which evaluated to empty.
