### ISSUE TITLE
[Testing][AR-May]: Testing effort of BuildCheck

### ISSUE THREAD

**Issue by f-alizada** [dotnet/msbuild#10377]
### Summary

Testing effort of BuildCheck item for team member
 
## Part 1
- [x] Inbox (built-in) analyzers that run during the build execution.
- [ ] Custom BuilcCheck
- [x] Configuration
- [ ] Tracing
- [x] Replay mode

## Part 2
Repository to be tested: 
- [x] [OrchardCore](https://github.com/OrchardCMS/OrchardCore)
- [ ] PerfStar

For more information on the effort please refer to the related issue #10372.

**Comment by AR-May** [comment]
Update: reproduced on the laptop as well.

**Comment by AR-May** [comment]
Found a weird behavior of analyzer: #10431

**Comment by AR-May** [comment]
I am having problems finding info for custom analyzers creation. Filed an issue to improve the experience: #10449
