### ISSUE TITLE
[Bug] Args type resolution in Expander

### ISSUE THREAD

**Issue by YuliiaKovalova** [dotnet/msbuild#10393]
The recent change in sdk unfolded a bug in 
https://github.com/dotnet/msbuild/blob/c2f9b76bb511c2ef4419abe468e81855781c40a1/src/Build/Evaluation/Expander.cs#L3597

On the attempt to invoke 
`<_MSBuildVersionMajorMinor>%24([System.Version]::Parse('%24(MSBuildVersion)').ToString(2))</_MSBuildVersionMajorMinor>`
the arg for `ToString` method is defined as string, that prevents the[ correct method](https://learn.microsoft.com/en-us/dotnet/api/system.version.tostring?view=net-8.0#system-version-tostring(system-int32)) resolution in runtime.

There might be a conventional wisdom behind this limitation, feel free to share what you know about that.

**Comment by rainersigwald** [comment]
We discussed this offline but for posterity: this isn't a _bug_; the evaluation eventually and transparently finds the right method, calls it, and gets the right answer. However, in doing so it throws (and catches) `MissingMethodException`, which was flagged by Visual Studio performance infrastructure.

This is the by-design way that MSBuild handles arbitrary method calls, but does have some performance cost, and the expander has a way to avoid the exceptions. They will go away for the specific case we see now with #10398.

**Comment by YuliiaKovalova** [comment]
close as dupe of https://github.com/dotnet/msbuild/issues/10398.
