### ISSUE TITLE
Catalogization of PerfStar service

### ISSUE THREAD

**Issue by JanKrivanek** [dotnet/msbuild#10459]
### Context

PerfStar doesn't seem to have it's dedicated s360 service record - and hence the PerfStar Azure resources are mapped to MSBuild s360 record.

### Goals
* [x] Dedicated s360 service for PerfStar - categorized under [.NET Tooling Prague Services tokapin](https://microsoftservicetree.com/organizations/95507f37-52a9-4246-939a-2c350ef60a72).
* [x] The PerfStar Azure resource [devdiv-dotnet-perfstar-vssps-SP - Microsoft Azure](https://ms.portal.azure.com/#view/Microsoft_AAD_RegisteredApps/ApplicationMenuBlade/~/Branding/appId/f291b063-bd8f-48a8-b38b-7d6f0f95ea31/isMSAApp~/false) is linked to the s360 service above (via 'Service management reference' record)
* [x] Audit that there are no other AZ resources belonging to PerfStar that' need above action
* [x] Set up our own Azure Subscription for SQL database

**Comment by AR-May** [comment]
Created and added all the resources to the entry,

**Comment by AR-May** [comment]
Reopened as we found one more point to execute
