### ISSUE TITLE
[Unhandled Exception]: double quote in path results in System.ArgumentException: Illegal characters in path

### ISSUE THREAD

**Issue by samedder** [dotnet/msbuild#10497]
### Issue Description

Attempting to use copy task to target a quote-surrounded path will cause MSBuild to crash with an unhandled exception.

### Steps to Reproduce

In any project, create an item such as:

```xml
  <ItemGroup>
    <FileCopy Include="mytestfile.ps1">
      <DestinationFolder>"$(Output)\bin"</DestinationFolder>
    </FileCopy>
  </ItemGroup>
```

Then run the following target
```xml
<Target Name="RunCopy" Inputs="@(FileCopy)" Outputs="@(FileCopy->'%(DestinationFolder)\%(Filename)%(Extension)')">
  <Copy SourceFiles="@(FileCopy)" DestinationFolder="%(DestinationFolder)\%(RecursiveDir)" />
</Target>
```

### Actual Behavior

> This is an unhandled exception in MSBuild -- PLEASE UPVOTE AN EXISTING ISSUE OR FILE A NEW ONE AT https://aka.ms/msbuild/unhandled
>     System.ArgumentException: Illegal characters in path.
>    at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
>    at System.IO.Path.Combine(String path1, String path2)
>    at Microsoft.Build.BackEnd.TargetUpToDateChecker.CompareLastWriteTimes(String path1, String path2, Boolean& path1DoesNotExist, Boolean& path2DoesNotExist)
>    at Microsoft.Build.BackEnd.TargetUpToDateChecker.IsOutOfDate(String input, String output, String inputItemName, String outputItemName)
>    at Microsoft.Build.BackEnd.TargetUpToDateChecker.PerformDependencyAnalysisIfCorrelatedInputsOutputs(Dictionary`2 itemVectorsInTargetInputs, Dictionary`2 itemVectorsInTargetOutputs, List`1 itemVectorsReferencedInBothTargetInputsAndOutputs, ItemDictionary`1& changedTargetInputs, ItemDictionary`1& upToDateTargetInputs)
>    at Microsoft.Build.BackEnd.TargetUpToDateChecker.PerformDependencyAnalysis(ItemBucket bucket, Boolean question, ItemDictionary`1& changedTargetInputs, ItemDictionary`1& upToDateTargetInputs)
>    at Microsoft.Build.BackEnd.TargetEntry.<ExecuteTarget>d__44.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at Microsoft.Build.BackEnd.TargetBuilder.<ProcessTargetStack>d__23.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.Build.BackEnd.TargetBuilder.<BuildTargets>d__10.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.Build.BackEnd.RequestBuilder.<BuildProject>d__68.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.Build.BackEnd.RequestBuilder.<BuildAndReport>d__59.MoveNext()

### Analysis

Bad string input but probably should not crash

### Versions & Configurations

MSBuild version 17.9.8+b34f75857 for .NET Framework

**Comment by JaynieBai** [comment]
Repro it with msbuild.exe , not with dotnet MSBuild
