### ISSUE TITLE
[Bug]: Microsoft.NET.StringTools 17.11.4 does not exist

### ISSUE THREAD

**Issue by reduckted** [dotnet/msbuild#10526]
### Issue Description

[`Microsoft.Build`](https://www.nuget.org/packages/Microsoft.Build#dependencies-body-tab) v17.11.4 depends on [`Microsoft.NET.StringTools`](https://www.nuget.org/packages/Microsoft.NET.StringTools/#versions-body-tab) v17.11.4 or greater, but the latest version of `Microsoft.NET.StringTools` is v17.11.2.

```
Installed Microsoft.Build 17.11.4 from <...snip...> to <...snip...> with content hash UMC7DfeFEHY2GGHHaghybUuUlLaByFHEFudR2PehMgDBuRuLAUePp1iaa4eFtVzepRzMtIbeSCVJCzzX3NV2Gg==.
NU1102: Unable to find package Microsoft.NET.StringTools with version (>= 17.11.4)
  - Found 15 version(s) in NuGet [ Nearest version: 17.11.2 ]
```

### Steps to Reproduce

Use NuGet to install `Microsoft.Build` v17.11.4.

### Expected Behavior

It installs successfully.

### Actual Behavior

It fails to install because the required version of `Microsoft.NET.StringTools` does not exist.

**Comment by baronfel** [comment]
@rbhanda I think we missed this package dependency when we asked for a push earlier today. Can you check and push this one as well?

**Comment by BobbyCannon** [comment]
![image](https://github.com/user-attachments/assets/9c0aea04-09c6-4c26-b618-c63128181b5e)

**Comment by MichalPavlik** [comment]
@reduckted, I'm sorry for inconvenience. We asked for publishing the missing package. I really hope it will be done today (US time).

**Comment by rainersigwald** [comment]
https://www.nuget.org/packages/Microsoft.NET.StringTools/17.11.4 is now present, though indexing is not yet complete.
