### ISSUE TITLE
[Bug]: Microsoft.Build.Utilities.Core 17.11.4 NuGet package is broken

### ISSUE THREAD

**Issue by avivanoff** [dotnet/msbuild#10532]
### Issue Description

Microsoft.Build.Utilities.Core 17.11.4 NuGet package depends on Microsoft.NET.StringTools 17.11.4 that does not exist.

### Steps to Reproduce

Create a project and add a reference to Microsoft.Build.Utilities.Core 17.11.4 NuGet package.

### Expected Behavior

Build should succeed.

### Actual Behavior

Build fails.

**Comment by baronfel** [comment]
duplicate of https://github.com/dotnet/msbuild/issues/10526
