### ISSUE TITLE
[Bug]: LNK2005 and LNK1169 Error one or more multiply defined symbols found

### ISSUE THREAD

**Issue by payn-git** [dotnet/msbuild#10546]
### Issue Description

when compiling our existing projects with msbuild 17.8 unexpected linker errors popup during compilation. This is not a case on msbuild 17.11. Our build machines are running mixture of 17.8 and 17.10 msbuild versions which cant be changed easily to 17.11 as we have many build machines cross various departments. Any help which can identify why this error happening on 17.8 -17.10 msbuild versions and how to avoid it will be appreciated. Also, it will be good to get some insights why this is not happening on 17.11 msbuild version as there doesn't seems to be anything in changelog which would indicate that such issues were fixed. binary log from compilation on 17.8 is attached. We will be not able to provide source projects\code because of IP.

[LNK2005Error.zip](https://github.com/user-attachments/files/16692915/LNK2005Error.zip)

### Steps to Reproduce

binary logs attached

### Expected Behavior

compilation will succeed without errors

### Actual Behavior

compilation faile

### Versions & Configurations

msbuild 17.8-17.10

**Comment by maridematte** [comment]
Team triage: 
We believe this is an issue with Visual Studio, not MSBuild. Can you [open a feedback ticket instead](https://docs.microsoft.com/visualstudio/ide/feedback-options)?

After it's created, that will open an internal bug which will be routed to the right team. If you post the link here we may be able to help that process go faster.

**Comment by payn-git** [comment]
Hi,

can you please elaborate bit more on your statement ? How compiling from command line while using msbuild is visual studio issue ?
