### ISSUE TITLE
Consider loosening `byte[]` rules in resx resources

### ISSUE THREAD

**Issue by rainersigwald** [dotnet/msbuild#10551]
originally by @ericstj at https://github.com/dotnet/project-system/issues/9526#issuecomment-2297743790

> it's being treated as a Activator type resource.
> 
> Here's the relevant code in MSBuild: https://github.com/dotnet/msbuild/blob/1a51dd82a24e26b6aac68e29414182fa56fbb573/src/Tasks/ResourceHandling/MSBuildResXReader.cs#L222-L280
> 
> MSbuild is registering as activator resource: https://github.com/dotnet/msbuild/blob/1a51dd82a24e26b6aac68e29414182fa56fbb573/src/Tasks/ResourceHandling/MSBuildResXReader.cs#L279C31-L279C49 https://github.com/dotnet/msbuild/blob/1a51dd82a24e26b6aac68e29414182fa56fbb573/src/Tasks/ResourceHandling/FileStreamResource.cs#L47
> 
> That's wrong, it should be treating as byte[], but MSBuild is only treating this as a byte array if it has both `System.Byte[]` and `mscorlib` https://github.com/dotnet/msbuild/blob/1a51dd82a24e26b6aac68e29414182fa56fbb573/src/Tasks/ResourceHandling/MSBuildResXReader.cs#L293
> 
> Here's what I see in the latest resx:
> 
> ```
>   <data name="ProgramSource" type="System.Resources.ResXFileRef, System.Windows.Forms">
>     <value>Program.cs;System.Byte[]</value>
>   </data>
> ```
> 
> Repro: [conRes.zip](https://github.com/user-attachments/files/16666930/conRes.zip)
> 
> So I can workaround this by adding `,mscorlib` to the resx.
> 
> ```diff
>   <data name="ProgramSource" type="System.Resources.ResXFileRef, System.Windows.Forms">
> -    <value>Program.cs;System.Byte[]</value>
> +    <value>Program.cs;System.Byte[],mscorlib</value>
>   </data>
> ```
> 
> Maybe MSBuild could broaden that check to consider this specific case of no core assembly name. @rainersigwald

**Comment by rainersigwald** [comment]
@melytc it looks like you changed the resource editor to put `,mscorlib` in there again; do you think we should change MSBuild as @ericstj suggested?

**Comment by melytc** [comment]
What @ericstj described, where we weren't saving the assembly information for the resource correctly, was a bug on our side. I don't think you need to change MSBuild, as our goal is to save the resource as we were doing before with the legacy resource editor. :)
