### ISSUE TITLE
Remove CoreCrossTargetingTargetsPath import when SDK provides them via package mechanism

### ISSUE THREAD

**Issue by nguerrera** [dotnet/msbuild#1062]
Microsoft.Commmon.CrossTargeting.targets imported $(CoreCrossTargetingTargetsPath) as a temporary bootstrapping mechanism before there was packaging extensibility available for cross-targeting builds. Once the SDK targets are successfully wired in via the packaging mechanism, remove this import.

**Comment by nguerrera** [comment]
@rainersigwald @AndyGerlicher  Please assign this to me. Any chance I could get permission to do that myself?

**Comment by rainersigwald** [comment]
@nguerrera I think you might have permissions now. Maybe.

**Comment by rainersigwald** [comment]
Do we still need this?

**Comment by nguerrera** [comment]
Technically, we could remove this:

https://github.com/microsoft/msbuild/blob/c70d6ded175c0a7da632018b856daff9f9cd392e/src/Tasks/Microsoft.Common.CrossTargeting.targets#L189-L191

But it is a breaking change if anyone besides dotnet/sdk started using it. I think we could also leave it and remove the TODO.

**Comment by dsplaisted** [comment]
Looks like this is probably not used, at least in public code: https://github.com/search?q=CoreCrossTargetingTargetsPath+-filename%3AMicrosoft.Common.CrossTargeting.targets&type=code

**Comment by rainersigwald** [comment]
We'll, now's the time then.

**Comment by Nirmal4G** [comment]
I already it in my patch. I'll separate this into a new PR!

**Comment by Nirmal4G** [comment]
I already have it in my patch. I'll separate this into a new PR!
