### ISSUE TITLE
Property check wording suggestion - use the MSBuild referencing syntax

### ISSUE THREAD

**Issue by JanKrivanek** [dotnet/msbuild#10630]
### Context

This is feedback by @RussKie:

> the warning messages - they look inconsistent - in the code a variable is declared as `$(Name)`, yet the message uses `Property [Name]...` or just `...variable: Name.`. Any reason not to output `Property '$(Name)'...`?
> 
![image](https://github.com/user-attachments/assets/29948c9e-3762-4cbb-9cb5-b2c3105504d4)
![image](https://github.com/user-attachments/assets/a8160d4d-4f1d-4981-9eb1-860d6c682184)
> With that, the messages would look like: `Property '$(Name)' was accessed...` and `Property '$(Name)' is derived from an env var`.

Since we are refering to references within MSBuild scripts - sticking to that syntaxt feels as a great improvement.
FYI @baronfel - do agree with the suggestion?

**Comment by baronfel** [comment]
Moving from square brackets to property usage syntax makes a ton of sense to me.

**Comment by rainersigwald** [comment]
People (including us!) definitely use `$(PropertyName)` a lot, but do we do it in other error messages or formal documentation? My inclination would be to put it in quotes instead (but I don't feel strongly and am very on board with changing the square brackets).

**Comment by RussKie** [comment]
I'm a strong believer of consistency, but these messages aren't in the docs but rather "right there with the developer" - near the code, so to speak.

Other than that, you know your domain and assets better than anyone else, so I trust you make the right call :)
