### ISSUE TITLE
Add BuildCheck basic telemetry

### ISSUE THREAD

**Issue by JanKrivanek** [dotnet/msbuild#10634]
### Context

Let's understand how our users are using BuildChecks.
Possible examples of usefull metrics:
 * Is BuildCheck enabled.
 * Built in rules that run as part of build.
 * Total ration of built-time vs buildcheck run.
 * Number of distinct custom checks enabled.
 * Number of distinct custom checks failed to load.

### Work to be done

Inspiration: https://github.com/dotnet/msbuild/issues/9063

* [x] Add and populate BuildCheck telemetry event
* [x] [Mount it properly in SDK](https://github.com/dotnet/sdk/blob/71ebd47cba756870c456081848b0d525eefb1732/src/Cli/dotnet/commands/dotnet-msbuild/MSBuildLogger.cs#L105-L154)
* [x] Emit initial telemetry (to be captured in gdpr inventory tool: https://gdpr.datasmart.ms/)
  * [x] once mounted in the SDK, run a build with the `DOTNET_CLI_TELEMETRY_OPTOUT=0` env var set to actually send the telemetry so the GDPR tool will flag it.
* [ ] Approve telemetry in GDPR inventory tool
* [ ] Update SDK telemetry docs in [dotnet/docs](https://github.com/dotnet/docs/issues/new?template=z-customer-feedback.yml&pageUrl=https%3A%2F%2Flearn.microsoft.com%2Fen-us%2Fdotnet%2Fcore%2Ftools%2Ftelemetry&pageQueryParams&contentSourceUrl=https%3A%2F%2Fgithub.com%2Fdotnet%2Fdocs%2Fblob%2Fmain%2Fdocs%2Fcore%2Ftools%2Ftelemetry.md&documentVersionIndependentId=50433ae5-4687-fe5f-75ab-a47e1a706777&feedback=%0A%0A%5BEnter+feedback+here%5D%0A&author=%40KathleenDollard&metadata=*+ID%3A+c136055b-bb04-17b6-19b2-42d4610c1a70+%0A*+Service%3A+**dotnet-fundamentals**)

FYI @baronfel

**Comment by baronfel** [comment]
Data that I want to be able to check (separately from your questions above).

* what % of builds are using buildchecks? We should be able to chart usage over time.
* What checks are being suppressed (turned down from their default warnings)? This is a signal that they are too painful/chatty.
* What checks are being elevated (turned up from their default warnings)? This is a signal they are valuable and should be considered for a severity increase in the next release.
* What checks are being run? General usage tracking to ensure that created checks are bringing value.
* What checks are actually flagging issues? General view of how correct a check is.

**Comment by baronfel** [comment]
This is the question I am least sure of how to answer :D If we track BuildChecks that do flag errors, we'd expect that number to trend down to zero over time as users either suppress or fix all reported errors for the BuildCheck. Maybe that's useful enough of a metric?

**Comment by JanKrivanek** [comment]
@baronfel - can you have a quick look if those: https://github.com/dotnet/msbuild/pull/10652/files#diff-b2558de61139ff21a10b8149c39fd972bce0477b76f4deb6ed238d5e1e0abe07R14-R93 seem like might meet the needs?

I'm still working on testing and polishing the code - so PR is not yet fully ready, but it already has the proposal of data.
Main questions:
* Will change of existing telemetry event (adding `BuildCheckEnabled` to `loggingConfiguration`) force a need for re-classification (I suppose so). Is there any other concern?
* Are event names with slashes supported? The final eventname is with slashes - e.g. 'dotnet/cli/msbuild/loggingconfiguration'. But I'm not sure if specifying the last part with slashes matters.
* Do the proposed data look as meeting your requirements?

**Comment by baronfel** [comment]
* Responded to this point in the PR, but I think there's a better event to put BuildCheckEnabled onto ("msbuild/build")
* event names with slashes are indeed supported, so feel free to use whatever namespaces you need
* yes! the data I see so far should be able to answer all of the questions above

**Comment by JanKrivanek** [comment]
So I run couple samples with `DOTNET_CLI_TELEMETRY_OPTOUT=0` through the local sdk with local patched msbuild (as well debugged through the sdk to confirm the events are coming in and data are populated). Yet I do not see the data yet in the classification tool:

https://gdpr.datasmart.ms/?q=ProductCode%20=%20%27ai.dotnetcli%27%20and%20DataClassification%20%3D%20%27Unclassified%27%20and%20EntityName%20like%20%27%25msbuild%25%27

Probably couple hours delay can be expected here?
