### ISSUE TITLE
Provide error recap/summary at the end of a large build in tl

### ISSUE THREAD

**Issue by rainersigwald** [dotnet/msbuild#10681]
In a very large build, errors may have scrolled well offscreen before the end of the build, leaving a terminal window with a sea of green "project succeeded" messages followed by an unhelpful "build failed with 8 errors".

We decided not to repeat every error because of noise, but we could consider a heuristic based on terminal height that could emit an error recap if errors were emitted but are now offscreen.

(I could swear we had this conversation several times but I can't find a bug tracking it)

**Comment by maridematte** [comment]
Team triage: @baronfel what is your opinion on the priority of this issue?

**Comment by baronfel** [comment]
It's not technically blocking but it is a major customer dissatisfaction as soon as you have builds with more than...say 10 projects or TFMs being built.  We should do it definitely for .NET 10, but ideally earlier - possibly for 9.0.200.
