### ISSUE TITLE
Reenable CustomCheck tests

### ISSUE THREAD

**Issue by maridematte** [dotnet/msbuild#10702]
The Custom Checks tests fail on version bump. We ran into this before: https://github.com/dotnet/msbuild/issues/10277. This issue is a reminder to reenable the tests once the version bumps are completed. 

This goes for main and VS17.12.

**Comment by JanKrivanek** [comment]
https://github.com/dotnet/msbuild/blob/5491064fe8d18c8f73d8b6048d277c3ec8b81d31/src/BuildCheck.UnitTests/EndToEndTests.cs#L442

https://github.com/dotnet/msbuild/blob/5491064fe8d18c8f73d8b6048d277c3ec8b81d31/src/BuildCheck.UnitTests/EndToEndTests.cs#L620
