### ISSUE TITLE
[Bug]: Deterministic builds in .NET8

### ISSUE THREAD

**Issue by dejvis** [dotnet/msbuild#10710]
### Issue Description

Hello
We have an issue with the deterministic build in .NET8.

We have a large project with many referenced libraries.

For simplification, lets have lib2 which is referenced by lib1.
For deployment reasons, if lib2 changes, we need lib1 to remain unchanged.

The current behavior in .NET8 is that if lib2 changes, lib1 changes as well.

For deployment build we use msbuild.

Is this a bug or an intended solution? Is there a solution to our requirements?

### Steps to Reproduce

[TestDeterministicBuildCoreConsole.zip](https://github.com/user-attachments/files/17159415/TestDeterministicBuildCoreConsole.zip)

### Expected Behavior

If lib2 changes, we need lib1 to remain unchanged.

### Actual Behavior

If lib2 changes, lib1 changes as well.

**Comment by dejvis** [comment]
If you mean this section in VS , than it is already turned on and still build generates different binaries. I expect msbuild takes this property from the project files.
![obrazek](https://github.com/user-attachments/assets/5877e7b1-6a4f-43ad-83f5-d54c3487b065)

**Comment by GangWang01** [comment]
@dejvis if the change to referenced project lib2 is public API change such as public member added/removed or name change, it's expected referencing project lib1 will be built and changed. If referenced project lib2 is changed in a way that doesn't alter its public API, referencing project lib1 will not be built and not change either. https://github.com/dotnet/project-system/blob/main/docs/up-to-date-check.md#reference-assemblies-and-mixed-sdk-stylenon-sdk-style-projects explains this.
