### ISSUE TITLE
[Bug]: Insufficient permissions on %SystemRoot%\TEMP results in nonspecific XamlTaskFactory error

### ISSUE THREAD

**Issue by esthermations** [dotnet/msbuild#10759]
### Issue Description

If permissions on `%SystemRoot%\Temp` are revoked, invoking a custom Xaml task declared via `UsingTask` causes MSBuild to log a nonspecific error implicating the (perfectly valid) command invocation file/line location as its cause.

### Steps to Reproduce

I'm locally seeing this using VS and CUDA. I think the important thing is having a project with a Build Customisation set to some external thing which declares custom tasks via `UsingTask`, and then actually using those tasks in the project. In this instance it's `CudaCompile`.

* In VS: File -> New -> Project -> CUDA 12.3 Runtime (or set up your test project with build customisation and task invocation)
* Build the example project. It works fine.
* Open cmd.exe as administrator and run `cacls C:\Windows\Temp /E /R everyone`
* Rebuild the project (or Clean then Build).
* Note the error described above.
* Run `cacls C:\Windows\Temp /E /G everyone:F` in the admin cmd.exe
* Rebuild again. Now it works again.

### Expected Behavior

If `%SystemRoot%\TEMP` doesn't have the requisite permissions, MSBuild should log an error saying so.

### Actual Behavior

MSBuild logs an error implicating an innocent task invocation.

### Analysis

Hi all, thought I'd report a bug I ran into which was tricky to solve. I have found a workaround, but I think the logging could have been much more helpful. I also hope that writing something here will help others who run into this in future.

As a bit of background, somehow the permissions on my `C:\Windows\TEMP` directory were revoked. Some cursory googling suggests this can happen in Windows updates. I think in my case it might have been in the process of installing VS 2022, but I'm not sure. This caused my project builds which include `CUDA 12.3.targets` to fail in a mysterious way:

```
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\BuildCustomizations\CUDA 12.3.targets(799,9): error MSB3686: Unable to create Xaml task.  Compilation failed.   [C:\Users\esther.okeefe\source\re
pos\MSBuildBug\MSBuildBug\MSBuildBug.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\BuildCustomizations\CUDA 12.3.targets(799,9): error MSB3686: Source file 'C:\Windows\TEMP\k5qvwvgi.0.cs' could not be found [C:\Users\esther.okee
fe\source\repos\MSBuildBug\MSBuildBug\MSBuildBug.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\BuildCustomizations\CUDA 12.3.targets(799,9): error MSB3686:  [C:\Users\esther.okeefe\source\repos\MSBuildBug\MSBuildBug\MSBuildBug.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\BuildCustomizations\CUDA 12.3.targets(799,9): error MSB4175: The task factory "XamlTaskFactory" could not be loaded from the assembly "Microsoft.
Build.Tasks.v4.0, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a". Object reference not set to an instance of an object. [C:\Users\esther.okeefe\source\repos\MSBuildBug\MSBuildBug\MSBuildBug.vcxproj]
```

The file/line number given is a red herring, as the error has nothing to do with the particular file. Changing the permissions on the system temp folder is not something anyone would think to do manually, so if this issue ever crops up the user isn't going to have any idea what's going on.

In VS the error looks like this, which doesn't mention C:\Windows\TEMP and draws even more attention to the (actually perfectly innocent) file/line number:
![image](https://github.com/user-attachments/assets/86c92c3b-5710-4548-9a3c-4de3858ad5d0)

Looking at the MSBuild code I saw that setting `MSBUILDWRITEXAMLTASK=1` would [take a different code path](https://github.com/dotnet/msbuild/blob/c4d51a11b84b4aabd9e5da1e3099f2c7c85024fe/src/Tasks/XamlTaskFactory/XamlTaskFactory.cs#L137-L151), and indeed doing so avoids the error because it doesn't access `%SystemRoot%\Temp`.

This led me to check the permissions on all my temp folders. Running `cacls C:\Windows\Temp /E /G everyone:F` from an administrator prompt resolved the issue, and running `cacls C:\Windows\Temp /E /R everyone` causes it to come back, whence the repro steps above.

### Versions & Configurations

Microsoft (R) Build Engine version 16.10.2+857e5a733 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

16.10.2.30804

**Comment by JanKrivanek** [comment]
Thank you for filing high quality bug!

It seems we are missing on opportunity to emit better error somewhere here: https://github.com/dotnet/msbuild/blob/d0a797e9ed0d218bcae30a986b9e14ed56339460/src/Tasks/XamlTaskFactory/XamlTaskFactory.cs#L186

**Comment by SimaTian** [comment]
Hello,

I couldn't reproduce the bug.
Could you please provide us with a sample project that reproduces the issue and .binlog with the error? I suspect I'm failing to set up the Build Customisation properly or something.
It would also help us to see if the bug still persist on the newer version of msbuild tool if that is possible for your case.

**Comment by SimaTian** [comment]
Update:
With a setup like this:
root task
```
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
    <UsingTask TaskName="SimpleTask.SimpleTask"
        AssemblyFile="testTask1.dll"/>

    <Target Name="MyTarget">
        <SimpleTask MyProperty="testcontent.txt"/>
    </Target>
</Project>
```
the .dll file is based on this project:

```
using System;
using Microsoft.Build.Framework;
using Microsoft.Build.Utilities;
using Microsoft.Build.Tasks;
using System.Collections.Generic;

namespace SimpleTask
{
    public class SimpleTask : Task
    {
        private string myProperty;
        private XamlTaskFactory myfactory;

        // The [Required] attribute indicates a required property.
        // If a project file invokes this task without passing a value
        // to this property, the build will fail immediately.
        [Required]
        public string MyProperty
        {
            get
            {
                return myProperty;
            }
            set
            {
                myProperty = value;
            }
        }

        public override bool Execute()
        {
            // Log a high-importance comment
            Log.LogMessage(MessageImportance.High,
                "The task was passed \"" + myProperty + "\".");
            myfactory = new XamlTaskFactory();
            var taskParameters = new Dictionary<String, TaskPropertyInfo>();
            myfactory.Initialize("mySampleTask", taskParameters, myProperty, BuildEngine);
            var myTask = myfactory.CreateTask(BuildEngine);
            myTask.BuildEngine = BuildEngine;
            myTask.Execute();
            return true;
        }
    }
}
```
some portions could be simplified away. However the gist of it is that this is a task that uses XamlTaskFactory to create a subtask, that it then executes.
When the .exe file is in an inaccessible folder, the error is:
```
 C:\Users\<username>\Documents\tests\customTask\test.mycsproj(6,9): error MSB6004: The specified task executable location "./test/mem.exe" is invalid.
However the build succeds. 
```

When the XAML task itself is in an inaccessible folder, the error becomes:
```error MSB4018: System.ArgumentException: Unable to create Xaml task.  File not found: C:/path_to_file```

When the file is accessible and throws an unhandled exception, the error becomes:
```
 Unhandled exception. System.AccessViolationException: you shall not pass
     at Program.<Main>$(String[] args) in C:\Users\<username>\source\repos\mem_fake\mem_fake\Program.cs:line 8
C:\Users\<username>\Documents\tests\customTask\test.mycsproj(6,9): error MSB3721: The command "" exited with code -532462766.
```


With the latest CUDA environment(12.6) + and its default project, the error didn't materialize even after manually deleting all permissions on the C:\temp folder. Maybe there is some step or setting that I'm missing.
