### ISSUE TITLE
[Bug]: Ouput path absolute only for OSX?

### ISSUE THREAD

**Issue by GustavEikaas** [dotnet/msbuild#10764]
## Description
I got an issue in my vim plugin for dotnet development saying that the output path was incorrect. After some digging we found out that seemingly only on OSX the `OutputPath` msbuild variable is absolute

## OSX
```
❯ dotnet msbuild ./ -getProperty:OutputPath -getProperty:TargetExt -getProperty:AssemblyName -getProperty:TargetFramework
{
  "Properties": {
    "OutputPath": "/Users/alex/GitHub/redacted/channel-notif-preferences/services/channel-notif-preferences/src/../bin/ChannelNotifPreferences/Debug/net8.0/",
    "TargetExt": ".dll",
    "AssemblyName": "ChannelNotifPreferences",
    "TargetFramework": "net8.0"
  }
}
```
## Windows
MSBuild version 17.11.3+0c8610977 for .NET
17.11.3.35201
```
❯ dotnet msbuild ./ -getProperty:OutputPath -getProperty:TargetExt -getProperty:AssemblyName -getProperty:TargetFramework
{
  "Properties": {
    "OutputPath": "bin\\Debug\\net8.0\\",
    "TargetExt": ".dll",
    "AssemblyName": "NeovimDebugProject.Api",
    "TargetFramework": "net8.0"
  }
}
```
## Ubuntu WSL
MSBuild version 17.8.5+b5265ef37 for .NET
17.8.5.5502
```
❯ dotnet msbuild ./ -getProperty:OutputPath -getProperty:TargetExt -getProperty:AssemblyName -getProperty:TargetFramework
{
  "Properties": {
    "OutputPath": "bin/Debug/net8.0/",
    "TargetExt": ".dll",
    "AssemblyName": "dotnet-api",
    "TargetFramework": "net8.0"
  }
}
```

I guess my question is if this is intentional or not. In my code im querying this variable to be able to construct a path to the final build dll. 

Link to issue:
https://github.com/GustavEikaas/easy-dotnet.nvim/issues/143

### Steps to Reproduce

Use a machine running OSX

1. Create a console app dotnet project
2. Run `dotnet msbuild ./ -getProperty:OutputPath -getProperty:TargetExt -getProperty:AssemblyName -getProperty:TargetFramework`
3. Inspect the `OutputPath` 

### Expected Behavior

I guess I would expect OSX to behave like this 
```
❯ dotnet msbuild ./ -getProperty:OutputPath -getProperty:TargetExt -getProperty:AssemblyName -getProperty:TargetFramework
{
  "Properties": {
    "OutputPath": "/bin/Debug/net8.0/",
    "TargetExt": ".dll",
    "AssemblyName": "ChannelNotifPreferences",
    "TargetFramework": "net8.0"
  }
}
```

### Actual Behavior

```
❯ dotnet msbuild ./ -getProperty:OutputPath -getProperty:TargetExt -getProperty:AssemblyName -getProperty:TargetFramework
{
  "Properties": {
    "OutputPath": "/Users/alex/GitHub/redacted/channel-notif-preferences/services/channel-notif-preferences/src/../bin/ChannelNotifPreferences/Debug/net8.0/",
    "TargetExt": ".dll",
    "AssemblyName": "ChannelNotifPreferences",
    "TargetFramework": "net8.0"
  }
}
```

**Comment by GustavEikaas** [comment]
Seems likely this is caused by user config or MSBuild variables, im currently investigating but its likely not a bug in msbuild. Sorry for the trouble

**Comment by JanKrivanek** [comment]
That being said - you can try to use [MSBuild Binary Log Viewer](https://msbuildlog.com/) to search for all reassignments of `OutputPath` property - that should reveal quickly if customisations are culprit.

**Comment by GustavEikaas** [comment]
Issue resolved it was user configuration messing up the path

**Comment by JanKrivanek** [comment]
Thank you for comming quickly back to us with the results!
