### ISSUE TITLE
[NETSDKE2E][Loc]With NET 9 RTM SDK installed in loc OS(Chinese), Unit of time in message is missing when building project in CLI.

### ISSUE THREAD

**Issue by v-ivyzuo** [dotnet/msbuild#10790]
1. Install 9.0.100-rtm.24509.30 in Loc OS(e.g Chinese OS)
2. Run "dotnet new console" and "dotnet build" in CLI.
3. Check Unit of time in message and if the messages are localized well.

Expected Result:
Unit of time is displayed in message and the messages are localized well.

Actual Result:
Unit of time in message is missing.

Chinese(Repro)
![Image](https://github.com/user-attachments/assets/7fb90119-a3a5-4336-9ff8-4f47b177ed0c)

EN:
![Image](https://github.com/user-attachments/assets/cd53ca3f-1ed7-4b60-bad2-e9af548ef659)

C:\Users\v-ivyzuo>dotnet --info
.NET SDK:
 Version:           9.0.100-rtm.24509.30
 Commit:            2d0b3f7934
 Workload version:  9.0.100-manifests.c5c38474
 MSBuild version:   17.12.3+4ae11fa8e

运行时环境:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\9.0.100-rtm.24509.30\

已安装 .NET 工作负载:
没有要显示的已安装工作负载。
配置为在安装新清单时使用 loose manifests。

Host:
  Version:      9.0.0-rtm.24503.8
  Architecture: x64
  Commit:       3429fee9ed

.NET SDKs installed:
  9.0.100-rtm.24509.30 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 9.0.0-rtm.24508.22 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 9.0.0-rtm.24503.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 9.0.0-rtm.24508.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

**Comment by marcpopMSFT** [comment]
I assume those strings are coming from MSBuild but holler if not.

**Comment by maridematte** [comment]
Team triage: We need to go through the strings we have and a note that the `s` in the message means seconds to avoid confusion.

**Comment by vdanche** [comment]
Currently still happens on 9.0.100 SDK
![Image](https://github.com/user-attachments/assets/f2220473-22dc-4529-bd1e-753ef71c9b4b)

**Comment by vdanche** [comment]
This issue has been resolved on 9.0.200-preview.0.24529.19 SDK
![Image](https://github.com/user-attachments/assets/f731da34-bab9-44d8-8d65-5ec0fbaf4475)
