### ISSUE TITLE
Regression in .NET 9 RC2: Compile produces warning MSB3277

### ISSUE THREAD

**Issue by bkoelman** [dotnet/msbuild#10856]
### Issue Description

After updating an existing codebase (multi-targeting .NET 6 and 8) that compiles without warnings, new warnings appear when building with .NET 9 RC2. The new warnings don't make sense to me.

See the thread at https://github.com/NuGet/Home/issues/13855#issuecomment-2415207763 for details.

### Steps to Reproduce

1. Clone https://github.com/json-api-dotnet/JsonApiDotNetCore
2. Run dotnet build

The above produces no compile warnings when .NET 6 and 8 are installed. Updating to .NET 9 RC2 shows MSB3277 three times.

### Expected Behavior

No compile warnings.

### Actual Behavior

warning MSB3277: Found conflicts between different versions...

**Comment by GangWang01** [comment]
@bkoelman I could not reproduce the issues using NET SDK 9.0.100-rc.2.24474.11. I've tried the branches master, test-against-dotnet9 mentioned in https://github.com/NuGet/Home/issues/13855#issuecomment-2415207763 with steps below. The warning MSB3277 didn't appear.
1. Clone https://github.com/json-api-dotnet/JsonApiDotNetCore and checkout the target branch.
2. Edit file test\SourceGeneratorTests\SourceGeneratorTests.csproj and comment out the line <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="$(EntityFrameworkCoreVersion)" />
3. Run dotnet build

Can you help to check if the issue can be reproduced on a new clean machine? If yes, can you [provide binary log](https://github.com/dotnet/msbuild/blob/main/documentation/wiki/Providing-Binary-Logs.md) for the investigation? Be aware that binary log might capture sensitive information before sharing.

**Comment by bkoelman** [comment]
Thanks for looking into this. If time permits, I can try that over the weekend. And I'll report my findings back here.

**Comment by bkoelman** [comment]
Good news! I tried on a fresh machine and installed VS 17.12.0 Preview 4.0 and I'm not getting these warnings anymore.
