### ISSUE TITLE
Backport Coversion deprecation message to older VS branches/versions

### ISSUE THREAD

**Issue by JanKrivanek** [dotnet/msbuild#10862]
### Motivation

In order to be able to remove Deprecated code in release branches - we'd need to announce the plan for some time via the dialog in the said VS versions - hence this work

Having a usage data would be helpful as well for justifying the removal.

This might be needed as we might need to soon perform more compliancy investments in non-main release branches - and being able to get rid of Deprecated code in thos branches there would then be very beneficial.

### Objectives

We want to backport https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/573846 to older (in-support) 17.* VS branches, and older VS versions (16, 15).

We want to as well backport the instrumentation change - https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/552729 - to observe the usages of the feature

**Note (10/15/2024):** We need as well https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/563147 in order to properly collect the telemetry

### Goals

- [x] Backport the PRs to 15.9, 16.11, 17.8 and 17.10 (17.6 to be skipped) - Kitten work
- [x] Backport the https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/552729 PR into same branches
- [x] Prepare QB bugs (template https://dev.azure.com/devdiv/DevDiv/_wiki/wikis/DevDiv.wiki/1969/Bug-Template-for-M2-and-QB-Modes?anchor=vs-ask-mode-template) for each of the backports (to be handled by @JanKrivanek)
- [x] Get the team, division and QB approval (to be handled by @JanKrivanek)

### Timeline 
let's target Nov patching Tuesday - so deadline around Oct/31st (https://devdiv.visualstudio.com/DevDiv/_wiki/wikis/DevDiv.wiki/27212/Dev15-16-17-Servicing-Schedule)

### Telemetry query

[Telemetry query to check the feature usage](https://dataexplorer.azure.com/clusters/ddtelvsraw/databases/VS?query=H4sIAAAAAAAAA13OSw6CQAwG4L2naFjpavQALCWyUIwmhO0IJYzOg7TDQ%2BPhnUDExK7a%2FOnXXuSw79F6zq%2BrN3j5QNhtpwrj0CAhTPlJGoQ4hihnkXNL7o6lF4XRrSRGEsUxrB5Qt6FP%2BTznidKY2kxXiSMjfQSO%2FrSeRb9o46KNJmjNrKlvXgdNWaeretbCg9wZI0m9EErXWb%2FewO35u%2FABoBKj7twAAAA%3D):

```
RawEventsVS
| take 1000000
| where EventName == "Vs/Vsproject/Xmlparser/XMakeHelper/IsProjectFileInOldFormat" or EventName == "vs/vsproject/xmlparser/xmakehelper/isprojectfileinoldformat"
| summarize count() by EventName
```

### Backport QB bugs

* 17.10: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/2284057
* 17.8: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/2287520
* 16.11: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/2287521
* 15.9: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/2287522

**Comment by JanKrivanek** [comment]
Verification needs to be done for each backported version - and copied to the appropriate ADO bug.
It needs to be done for the English and single non-English locale.
It should match the results that are outlined below as sample steps - those are for 17.12/17.13. The bug for 17.10 has the sample verification for 17.10. The 17.8, 16.11 and 15.9 needs to be tested and results added


**Backport verification steps:**
* Download sample old project file (additional files are not needed): https://devdiv.visualstudio.com/Personal/_git/matclark?path=%2Ftools%2FXmlSerializerPreCompiler%2FBackup%2FXmlSerializerPreCompiler%2FXmlSerializerPreCompiler.csproj&_a=contents&version=GBmain
* Open in VS and verify the new wording appears in the dialog:
![Image](https://github.com/user-attachments/assets/f16fa844-4e23-4be8-8883-d7825df95d6f)
* Verify the project is loaded after conversion:
![Image](https://github.com/user-attachments/assets/a5a9c270-7676-4386-b075-9ca3b5d2653b)
* Verify that the project was converted to MSBuild format:
![Image](https://github.com/user-attachments/assets/dcdac6e9-e8e5-4b64-b796-d46a6e6addd4)
* Verify that upgrade dialog has the new warning wording:
![Image](https://github.com/user-attachments/assets/6a476c2b-02c0-4f07-95ff-0fd32b0f9a65)




Alter localization:
* Run installer
* Add Lang pack and remove English
![Image](https://github.com/user-attachments/assets/6e74a60b-6e76-4346-af66-ca127fdfb363)
* Then open VS - it should be in the selected locale:
![Image](https://github.com/user-attachments/assets/257eb058-7fc7-4ee0-9904-14fde224c7a1)
* Run the 'Backport verification steps' above, with the current locale

**Comment by JanKrivanek** [comment]
So the 17.10 PR - https://devdiv.visualstudio.com/DevDiv/_git/a290117c-5a8a-40f7-bc2c-f14dbe3acf6d - was finally fully sorted out, tested and approved. We now need to backport+repeat for other 3 remaining PRs.

High level, what needs to be done (largely sourced from https://dev.azure.com/devdiv/DevDiv/_wiki/wikis/DevDiv.wiki/40758/Localization-Servicing-in-Dev-17):
 * Backport localization changes into Localize repo, from https://devdiv.visualstudio.com/DevDiv/_git/80eae3e6-fe98-458b-a2d4-5fa8f4d0e465/pullrequest/587046 - the branches naming need to folllow the naming scheme of the matching VS branches (plus the 'loc' suffix) - similarly as the sample PR into rel/d17.10loc
 * Add me and Cristiano as reviewers - ping us if needed for timely signoff and merge
 * Then the top of newly created branch need to be referenced from the VS PRs (all that's needed is to switch the branch in the local git where you have the PR checked out - ping me for details if needed. The VS wiki is bit confusing in this step)
 * Then backport or manually transfer all other remaining changes from the 17.10 PR (it should be basicaly just those `revision.txt` changes)
 * Once done, produce and install a build for the PR (https://dev.azure.com/devdiv/DevDiv/_wiki/wikis/DevDiv.wiki/29319/Install-a-VS-Build-from-a-PR) and verify that the localization changes were properly applied (as described in the previous comment on this bug)
 * Then ping me and we'll get through the approval paperwork

**Comment by JaynieBai** [comment]
17.8  https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/585699
16.11 https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/585698
15.9  https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/585692

They are merged
