### ISSUE TITLE
Solution doesn't respect WarningsNotAsErrors

### ISSUE THREAD

**Issue by rainersigwald** [dotnet/msbuild#10877]
The promotion of the "plain property" version of some warning-related settings:

https://github.com/dotnet/msbuild/blob/69b3e7a43fb2fb26812b20807333cf6ca62167f2/src/Tasks/Microsoft.Common.CurrentVersion.targets#L668-L672

Is in `Microsoft.Common.CurrentVersion.targets`, which is not imported into solution metaprojects. This means that any warnings raised in the solution itself (like in NuGet operations) may be promoted to error even if `$(WarningsNotAsErrors)` includes them.

This is very related to #10873 and we should consider fixing both by looking at the unprefixed versions in the engine (if the prefixed version is unset) rather than requiring XML logic to do it.

**Comment by ViktorHofer** [comment]
@SimaTian I assume this should get re-opened given that https://github.com/dotnet/msbuild/pull/10942 got reverted later?
