### ISSUE TITLE
Treat UseUtf8Encoding=true as "always"

### ISSUE THREAD

**Issue by rainersigwald** [dotnet/msbuild#10907]
In `ToolTask` and derived tasks like `Exec`:

> `UseUtf8Encoding="true"` is ignored; [valid values are are `Always`, `Never`, or `Detect`](https://learn.microsoft.com/en-us/visualstudio/msbuild/exec-task?view=vs-2022#:~:text=Valid%20values%20are%20Always%2C%20Never%2C%20or%20Detect.). We should probably treat `true` as `Always` though, since it isn't currently an error.

 _Originally posted by @rainersigwald in [#4870](https://github.com/dotnet/msbuild/issues/4870#issuecomment-2444584058)_

**Comment by rainersigwald** [comment]
All yours @jrdodds! As always please let us know if you have questions.

**Comment by jrdodds** [comment]
`ToolTask` class doesn't validate and doesn't interpret the value of `UseUtf8Encoding`. The value of `UseUtf8Encoding` is interpreted when passed to `EncodingUtilities.BatchFileEncoding()`. The `EncodingUtilities` class can be modified to add a const string member for "TRUE" and the `switch` statement in `BatchFileEncoding()` can be modified to use "TRUE".

My question is about the unit test and testing `Detect`. Adding a test method to the `EncodingUtilities_Tests` class that tests the `BatchFileEncoding()` method with `True`, `Always`, and `Never` is straight-forward. For `Detect`, the static `BatchFileEncoding()` method calls the static `CanEncodeString()` method. What's the standard or convention in the codebase for situations like this? I'm not finding examples and I don't want to introduce something new or unusual.

Thanks
