### ISSUE TITLE
Test BuildCheck packages redistribute `Microsoft.Build.dll`

### ISSUE THREAD

**Issue by rainersigwald** [dotnet/msbuild#10900]
I had occasion to look at the packages we produce, like `CustomCheck2`, and the contents have some problems:

```
S:\MSBUILD\ARTIFACTS\BIN\MICROSOFT.BUILD.BUILDCHECK.UNITTESTS\CUSTOMCHECKS\CUSTOMCHECK2.1.0.0
│   CustomCheck2.nuspec
│   MSBuild-NuGet-Icon.png
│   README.md
│   [Content_Types].xml
│
├───build
│       CustomCheck2.dll
│       CustomCheck2.props
│       Microsoft.Build.dll
│
├───content
│       README.md
│
├───contentFiles
│   └───any
│       └───netstandard2.0
│               README.md
│
├───notices
│       THIRDPARTYNOTICES.txt
│
├───package
│   └───services
│       └───metadata
│           └───core-properties
│                   eb8370b39a7d4e268cce01eea2db634b.psmdcp
│
└───_rels
        .rels
```

1. We shouldn't redistribute `Microsoft.Build.dll`
2. The package itself shouldn't have dependencies on MSBuild stuff (or anything in this case I believe).
3. Why is `README.md` in there several times, or as `content`?

**Comment by YuliiaKovalova** [comment]
Microsoft.Build.dll won't be included in the package after merging this change https://github.com/dotnet/msbuild/pull/10872/files#:~:text=%3C-,ProjectReference,-Include%3D%22..%5C..%5C..%5CBuild%5CMicrosoft.Build.csproj%22%20/%3E

for readme.md I will check separately
