### ISSUE TITLE
BuildXL nuget repo deletion breaks building older releases

### ISSUE THREAD

**Issue by omajid** [dotnet/msbuild#10917]
The BuildXL nuget repo was recently deleted. This broke source-build (eg https://github.com/dotnet/source-build/issues/4634) which was easily fixed. 

However, this also broke online builds of *older* versions of .NET, which all require fixing some way or the other.

For example:

- I wanted to rebuild 9.0 RC 1 with a custom fix to re-bootstrap 9.0 RC 2. But RC 1 is broken due to missing BuildXL repo and can't be fixed (due to being a point-in-time release)
- Someone on my team is trying to test an older commit of .NET 8 - 8.0 RC 1 specifically - to see if it reproduces a bug. But the 8.0 build is broken because BuildXL is removed.

I know that, in general, expecting older releases to build out of the box is not realistic. Many bugs, tooling support and compatibility fixes are missing in older releases. However, this change accidentally breaks *all* older releases.

**Comment by rainersigwald** [comment]
I don't think there's anything that we can do to fix this. Older builds will have to patch out that feed.

**Comment by YuliiaKovalova** [comment]
Hi @omajid , 

We have backported it to the older release branches. For other changes you would need to cherry pick this commit https://github.com/dotnet/msbuild/commit/d0a797e9ed0d218bcae30a986b9e14ed56339460 and use version from here https://github.com/dotnet/msbuild/commit/0a3683cf7bb7d635aa418dbc8afbc69f6aa3e2cb.

**Comment by omajid** [comment]
Thanks. I have a few workarounds for this now.

I want to raise awareness of how deleting a nuget repo can have a broader impact than just the new releases.
