### ISSUE TITLE
Better name for "Sdk"

### ISSUE THREAD

**Issue by atrauzzi** [dotnet/msbuild#10925]
### Summary

I was just having a look through the release notes for [Aspires 9.0 RC1](https://learn.microsoft.com/en-us/dotnet/aspire/whats-new/dotnet-aspire-9-release-candidate-1?tabs=unix&pivots=dotnet-cli) and was happy to see that workloads have been eliminated.

Thank goodness! 🥳 

...but then I was reading the migration instructions and I spotted something that - while I think I know what's going on - could easily become confusing due to the level of ambiguity in terminology:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <Sdk Name="Aspire.AppHost.Sdk" Version="9.0.0-rc.1.24511.1" />
```
😞

Don't get me wrong, this is neat as I feel it's akin to the gradle plugin system. 👏 

It's just... Couldn't you guys have picked a better name than `Sdk`?  Now we have `<Project Sdk=`, which is then followed by an element called `<Sdk`.  And then to make matters worse, the values for both are namespaced.

Mark my word, this will be a small - but evergreen! 🌲☄ - source of confusion!

### Background and Motivation

Quality of life with naming and structure, which MS has been known to struggle with. 😉 

I mean, even the fact that we've had to live with workloads for a period while the pains were worked out in public shows that these things warrant more consideration.

### Proposed Feature

What was wrong with `Plugin`?

**Comment by rainersigwald** [comment]
I'm a bit confused by what you're asking for. Both `<Project Sdk=` and `<Sdk` are the same concept, but it sounds like you're thinking they should have different names?
