### ISSUE TITLE
How to avoid package version dependency from project

### ISSUE THREAD

**Issue by Ajith-GS** [dotnet/msbuild#10941]
1.	**Background**
We have a requirement to avoid package version dependency from a WinUI3 CppWinRT project. In CSharp projects NuGet package for multiple projects can be accessed from a single location using NuGet's central package management (CPM) features. But in CppWinRT project this is not working as expected because package.config file is version dependent.
2.	**Issue**
In WinUI3 CppWinRT application we can only update package versions manually using Manage NuGet Packages. In CppWinRT projects, using Central Package Management version dependencies in project file can be removed but version dependency from package.config cannot be removed.
3.	**Method** **tried**
 Using Central Package Management
•	Package and its version information’s are present in project and package.config file. We tried Central Package Management to centrally manage package dependencies in project. Using Central Package Management version dependency from project file is removed but again issue occurred as version dependency from package.config cannot be removed.
•	Instead of removing versions from package.config we tried to copy updated packages.config to root folder in prebuild events but this also failed as NuGet restore operations occurs before prebuild events.
4.	**Query**
Is there a method to make package.config version independent or update the versions in package.config automatically.

5.	**Testing Environment**
•	Windows OS version	: 22H2
•	OS Build			: 19045.5011
•	Visual Studio Version	: VS 2022,17.4.4

Sample application is attached:
[SampleApp.zip](https://github.com/user-attachments/files/17659889/SampleApp.zip)

**Comment by maridematte** [comment]
This issue was moved to NuGet/Home#13935
