### ISSUE TITLE
Extra calls in Asm

### ISSUE THREAD

**Issue by 1zaboy** [dotnet/msbuild#10962]
### Issue Description

I have method
```
    public static void RecordError(Exception exception)
    {
    }
```

And I have code witch call RecordError
```
                try
                {
                     ...
                }
                catch (Exception ex)
                {
                    O.RecordError(ex);
                }
```

But when I build it and check Asm, I see call     [Test.O:RecordError(System.Exception)]

Since the method does not contain any code, its call could be removed.

I use .net 8 and Disasmo for see asm

### Steps to Reproduce

I have method
```
    public static void RecordError(Exception exception)
    {
    }
```

And I have code witch call RecordError
```
                try
                {
                     ...
                }
                catch (Exception ex)
                {
                    O.RecordError(ex);
                }
```

### Expected Behavior

Not call method

### Actual Behavior

call method

### Versions & Configurations

 .net 8

**Comment by baronfel** [comment]
Hi - this issue doesn't seem related to MSBuild. Are you asking a question about how the C# compiler compiles your code?

**Comment by 1zaboy** [comment]
@baronfel Hi, I think it's mistake of build of try catch block with Empty method. In asm Empty method should not to call.
Yea, maybe I write on wrong repo, but I don't shore who make final build.

**Comment by baronfel** [comment]
It's ok. This repo is for the build tools/engine, but your question does seem to be about the C# compiler (which is a tool that we end up calling). I'll transfer you to the Roslyn repo so they can see your question.

**Comment by baronfel** [comment]
Weird, I don't seem to have transfer permissions anymore. Can you recreate this at the dotnet/roslyn repo?
