### ISSUE TITLE
No types defined for elements in XSD schema

### ISSUE THREAD

**Issue by eZprava** [dotnet/msbuild#10983]
### Issue Description

In XSD there are many elements which should likely have type="xs:string", but they have no type at all, thus ur-type. Is it a bug, or a design choice?
E.g.: https://github.com/dotnet/msbuild/blob/6cd445d84e59a36c7fbb6f50b7a5a62767a6da51/src/MSBuild/MSBuild/Microsoft.Build.CommonTypes.xsd#L24
<xs:element name="Name"> // Friendly display name (optional)

### Steps to Reproduce

-

### Expected Behavior

-

### Actual Behavior

-

**Comment by eZprava** [comment]
So it could be type derived from string which allows any attribute? I don't understand why one would need child elements in e.g. Name.

**Comment by eZprava** [comment]
I don't know about VS - I used XSD to generate C# classes from Microsoft.Build.xsd and found out that Name is object instead of string. So I was curious if there's some deeper reason why one element has type="msb:boolean" while other has ur-type.

**Comment by eZprava** [comment]
Thanks, I'm not using XmlSerializer. I have my own library to generate C# classes and I used .NET Framework .csproj as test files, to see if it can be round-tripped using generated classes. I needed to add support for substitution groups, it's cleverly used in the schema, it was new to me. Now it works, I was just curious why the Name element has ur-type, that's all.

**Comment by maridematte** [comment]
Team Triage: @KalleOlaviNiemitalo answer is correct, the types are there to feed into intellisense and extra VS functions. Let us know if you have any more questions regarding this, but closing the issue for now.
