### ISSUE TITLE
$(MSBuildRuntimeType) mismatch when multi-target building

### ISSUE THREAD

**Issue by feast107** [dotnet/msbuild#11027]
### Issue Description

I read `$(MSBuildRuntimeType)` when running MSBuild Task and it is value as `Core` when I build .net-framework assembly

### Steps to Reproduce

> All the following is contained in new .csproj template style

when the framework is `<TargetFrameworks>net8.0</TargetFrameworks>`, `$(MSBuildRuntimeType)` is `Core` and correct.

![Image](https://github.com/user-attachments/assets/ceec79c5-9796-4eec-ae7c-d75316add08b)

> The log printed the value of MSBuildRuntimeType passed to the MSBuildTask

when the framework is `<TargetFrameworks>net462</TargetFrameworks>`, `$(MSBuildRuntimeType)` is `Full` and correct.

![Image](https://github.com/user-attachments/assets/8a8fbe12-2579-4a15-801c-e19bb98e6e7e)

But if framework is `<TargetFrameworks>net8.0;net462</TargetFrameworks>`, `$(MSBuildRuntimeType)` are both `Core`.

![Image](https://github.com/user-attachments/assets/488916df-7f99-421a-a2c5-6446a2e5fdf7)

which is obviously wrong.

The case also happens when it comes to `<TargetFrameworks>net462;net471</TargetFrameworks>`, the frameworks are both .net-framework. but `$(MSBuildRuntimeType)` are both still `Core`

![Image](https://github.com/user-attachments/assets/0c51cb0b-4c41-4ea1-b353-fd7e7ab91c52)

There were no other changes when I did the tests above.

### Expected Behavior

When `TargetFramework` is net-core or standard, it is `Core`. When `TargetFramework` is net-framework, it is `Full`.

### Actual Behavior

When `TargetFrameworks` contains multiple targets. It will always be `Core`.

### Analysis

Maybe forget to calculate for each target framework in a targeted manner when reading `TargetFrameworks`.

### Versions & Configurations

```
disk:\Users\One Developer> msbuild -version
适用于 .NET Framework MSBuild 版本 17.12.6+db5f6012c
17.12.6.51805
```

**Comment by Youssef1313** [comment]
You're probably looking for `TargetFrameworkIdentifier`

**Comment by feast107** [comment]
That make sense.
