### ISSUE TITLE
Option to avoid "fixing" `\` in `new TaskItem()`

### ISSUE THREAD

**Issue by rainersigwald** [dotnet/msbuild#11083]
### Summary

This code unconditionally calls `FixFilePath`:

https://github.com/dotnet/msbuild/blob/4c6a5a963ceb38f77af4e57d28669872b616a8dc/src/Utilities/TaskItem.cs#L80-L86

But while `TaskItem`s _usually_ represent files on disk, they don't _necessarily_ do so, and if they don't and also contain backslashes this will corrupt them. It should be configurable.

### Background and Motivation

See analysis by @JoeRobich in https://github.com/dotnet/roslyn/issues/72014#issuecomment-2505624518.

### Proposed Feature

```diff
        public TaskItem(
            string itemSpec
+           bool convertBackslashesToSlashes = true)
        {
            ErrorUtilities.VerifyThrowArgumentNull(itemSpec);

+           if (convertBackslashesToSlashes)
+           {
                _itemSpec = FileUtilities.FixFilePath(itemSpec);
+           }
        }

```

**Comment by jeffkl** [comment]
I suggest the name of the input parameter to be `bool treatAsFilePath = true` and document as such that MSBuild will by default treat it as a file path and potentially "fix" it up and/or create a full path from it.
