### ISSUE TITLE
Github checks sometimes randomly fail.

### ISSUE THREAD

**Issue by SimaTian** [dotnet/msbuild#11116]
### Issue Description

Once in a while, the github checks fail due to
`.dotnet\sdk\9.0.100\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(221,5): error : (NETCORE_ENGINEERING_TELEMETRY=Build) The process cannot access the file 'D:\a\1\s\artifacts\bin\Microsoft.Build.BuildCheck.UnitTests\CustomChecks\Microsoft.Build.Framework.17.13.0-ci-24609-01.nupkg' because it is being used by another process.`
Re-running the pipeline makes this go away most of the times.

### Steps to Reproduce

Create a PR for merging into `main` (could be other branches, but this one I notice most often).
Run checks.
Repeat until you see the failure.

### Expected Behavior

If there are no issues, the tests pass.

### Actual Behavior

Sometimes the tests randomly fail.

**Comment by YuliiaKovalova** [comment]
It's a dupe for https://github.com/dotnet/msbuild/issues/11090
and https://github.com/dotnet/msbuild/issues/11100
