### ISSUE TITLE
Globbing APIs: reduce memory pressure by storing less data

### ISSUE THREAD

**Issue by cdmihai** [dotnet/msbuild#1167]
- [ ] use a linked list to reduce GC events from growing the arraylist
- [ ] only item elements whose condition evaluated to true and which are under item groups with conditions or under choose elements. Then use this small list to recreate the bigger list from the list of all item elements (provided by ProjectRootElement). If a project has no conditions (like the large Chromium project), then this list will be empty. This works under the assumption that most item elements are not conditioned, and their parents are not conditioned, which appears the case for VS template csprojes

**Comment by ladipro** [comment]
[Perf triage]
@cdmihai, can you please help me understand this issue? Which ArrayList is problematic? "Globbing APIs" in the title doesn't refer to `namespace Microsoft.Build.Globbing`, does it?

**Comment by cdmihai** [comment]
@ladipro 

Well, this is a very bad example of an ambiguous task :)

I think it might refer to the `Project.GetAllGlobs` APIs, but I forget what it was about. It could be about [how the API stores its results](https://github.com/dotnet/msbuild/blob/9bcc06cbe19ae2482ab18eab90a82fd079b26897/src/Build/Definition/Project.cs#L2514) or about [how it computes the list of project item elements](https://github.com/dotnet/msbuild/blob/9bcc06cbe19ae2482ab18eab90a82fd079b26897/src/Build/Definition/Project.cs#L2666) it works off of which sometimes can trigger re-evaluations. Maybe best to just close the issue and let it resurface again in perf logs.

**Comment by ladipro** [comment]
Thank you, closing the issue then.
