### ISSUE TITLE
Print time taken in executing individual task

### ISSUE THREAD

**Issue by rathakur-msft** [dotnet/msbuild#1581]
Hello,

Is it possible to print the time taken in executing individual task in msbuild? I know there is /displaysummary option in msbuild but it prints the aggregate time of all invocation of tasks. What I am looking at is the time taken for executing 1 invocation of task. Below given are the kind of logs that where I want time taken to be printed.

Done executing task "CL". [I need something like **Done executing task "CL" in 15 seconds**.]
Done executing task "MSBuild".
Done executing task "AddToManifest".

This will be very helpful to us to investigate slow build issues.

Ravinder

**Comment by rainersigwald** [comment]
Not built in, but you can create a [custom logger](https://msdn.microsoft.com/en-us/library/ms171471.aspx) to collect that information. You'd have to preserve the timestamps from the `TaskStartedEventArgs` and `TaskFinishedEventArgs` events and subtract them.

**Comment by jeffkl** [comment]
@rathakur-msft: You can get a list of total time taken by a task for the build with the logger parameter `PerformanceSummary`.  It also displays project and target performance.

```
MSBuild.exe ConsoleApplication1.csproj /ConsoleLoggerParameters:PerformanceSummary

...

Task Performance Summary:
        0 ms  Message                                    3 calls
        0 ms  CallTarget                                 1 calls
        0 ms  FindAppConfigFile                          1 calls
        0 ms  AssignCulture                              1 calls
        0 ms  ConvertToAbsolutePath                      1 calls
        0 ms  Delete                                     2 calls
        0 ms  ResolveCodeAnalysisRuleSet                 1 calls
        0 ms  GetReferenceAssemblyPaths                  1 calls
        0 ms  Copy                                       3 calls
        0 ms  FindUnderPath                              5 calls
        0 ms  ReadLinesFromFile                          1 calls
        0 ms  WriteLinesToFile                           1 calls
        0 ms  AssignTargetPath                           6 calls
        0 ms  GetFrameworkPath                           1 calls
        0 ms  RemoveDuplicates                           2 calls
        0 ms  MakeDir                                    1 calls
       16 ms  ResolveAssemblyReference                   1 calls
      250 ms  Csc                                        1 calls
```

If I build an individual project, I can narrow down which task is taking the longest.  Is that what you're looking for?

**Comment by rathakur-msft** [comment]
@jeffkl I know about the PerformanceSummary option. However we are trying to optimize our full build and in that case a task like CSC is executed around 200+ time. Since the time above is aggregate, I am unable to find out that out of 100 calls of csc, which one took most time. If I want to find out project on my own, I have to manually compile all 100 projects individually and that is time consuming.

Since we have multiple tasks that need optimization, compiling individual projects become very time consuming.

In any case, I think it will add value to print the time when task completes since many people will be interested in fining out which invocation of task took most time.

**Comment by ladipro** [comment]
Perf triage: Closing an old issue.
@rathakur-msft, MSBuild now emits ETW events to help profile builds. See the attached [PR](https://github.com/dotnet/msbuild/pull/5004).

**Comment by KirillOsenkov** [comment]
Also this information is available from a binlog, see https://msbuildlog.com
