### ISSUE TITLE
publish to homebrew

### ISSUE THREAD

**Issue by ehartford** [dotnet/msbuild#1685]
I want to 'brew install msbuild' on my mac

http://docs.brew.sh/Formula-Cookbook.html

**Comment by cdmihai** [comment]
Until that happens, if you need to programatically get msbuild for vm setup and such, you could bring down [dotnet CLI ](https://github.com/dotnet/cli)which also packages msbuild. They have a script for it: https://github.com/dotnet/cli/blob/rel/1.0.0/scripts/obtain/dotnet-install.sh

Not ideal, but it is a one liner command line.

**Comment by rainersigwald** [comment]
We don't currently have any plans to do this. On non-Windows, you'll always need a runtime host (either `dotnet` CLI or Mono) to execute MSBuild, and both of those include MSBuild, so there's not much reason for us to go through the packaging effort. In addition, there are all the problems involved with getting the right set of SDKs, tools, targets, and tasks to be able to do something useful with MSBuild--which are solved by the CLI installer.

**Comment by cpitclaudel** [comment]
> both of those include MSBuild

Do they? I don't think the `mono` package on brew does.  It certainly doesn't on Ubuntu (it's in a separate package called `msbuild`, but I don't think there's an equivalent for that in homebrew)

**Comment by rainersigwald** [comment]
My understanding is that Mono carries MSBuild as of (some version number I don't know). @radical or @directhex, am I misunderstanding?

**Comment by cpitclaudel** [comment]
Mono-the-project does (starting in 5.0, IIRC). Mono-the-package doesn't, at least on Ubuntu and IIUC on brew, currently.

**Comment by directhex** [comment]
Mono for Mac bundles msbuild as part of the mono.pkg download. But there is a LOT in that package beyond what's in mono.git.

RE Linux: There are msbuild packages on download.mono-project.com, but msbuild as-is is not suitable for inclusion directly into Debian/Ubuntu.

**Comment by akoeplinger** [comment]
Also note that the mono that is on homebrew is not maintained by us (Xamarin/Mono team) but some third party. It's best to use the .pkg download from http://www.mono-project.com.

**Comment by haf** [comment]
@rainersigwald You're wrong, says @akoeplinger – you need msbuild to be installed for mono to work properly nowadays.

**Comment by mcclure** [comment]
Looks like homebrew now bundles msbuild with its distribution of mono https://github.com/Homebrew/homebrew-core/pull/29422
