### ISSUE TITLE
Diagnostic builds should log "global" properties

### ISSUE THREAD

**Issue by davkean** [dotnet/msbuild#1710]
Diagnostic builds log the current environment at the start of a build:

```
Environment at start of build:
ALLUSERSPROFILE                = C:\ProgramData
APPDATA                        = C:\Users\davkean\AppData\Roaming
CommonProgramFiles             = C:\Program Files (x86)\Common Files
CommonProgramFiles(x86)        = C:\Program Files (x86)\Common Files
CommonProgramW6432             = C:\Program Files\Common Files
COMPUTERNAME                   = DAVKEAN-DEV
[...]
```

To make it easier to diagnose builds, it would be really helpful if the set of global properties were also logged:
```
DesignTimeBuild                = true
Configuration                  = Debug
[...]
```

This would help diagnose both command-line and Visual Studio builds. As example, I'm trying to figure out https://github.com/dotnet/roslyn-project-system/issues/1554, and I have no idea where to start - is this a CPS bug? Or a MSBuild bug?

**Comment by rainersigwald** [comment]
Sounds entirely reasonable to me.

**Comment by KirillOsenkov** [comment]
Isn't this fixed now?

**Comment by rainersigwald** [comment]
Yeah this should be long, long done.
