### ISSUE TITLE
Transforming an item allows access to metadata value

### ISSUE THREAD

**Issue by rainersigwald** [dotnet/msbuild#1764]
See https://github.com/Microsoft/msbuild/blob/7a255b89c90c38520b5cc6869a5e2a2f1e66da20/src/Build.UnitTests/Evaluation/Evaluator_Tests.cs#L1410

```
<i Include=""@(h->'%(identity))"">
```

This is malformed, and therefore expands to a literal string rather than a transform of the `h` item. Because of that, the `Predecessor` value is null (and the test passes), and the `m` metadata is set to `2;` because the metadatum reference `%(m)` is replaced with the empty string.

But when adding the missing `'`, the test starts failing, because all of a sudden `%(m)` has a value.

The current real behavior makes sense to me but before fixing the test to expect it, I'd like to make sure we've investigated why the test expects different.

**Comment by rainersigwald** [comment]
Looking at this now, I think the test is just wrong and should be updated.

**Comment by vijaya-lakshmi-venkatraman** [comment]
Hi,
Is this issue still available?

**Comment by Forgind** [comment]
@vijaya-lakshmi-venkatraman, I think so.
