### ISSUE TITLE
GenerateTargetFrameworkMonikerAttribute is always out of date

### ISSUE THREAD

**Issue by davkean** [dotnet/msbuild#1770]
_From @davkean on February 27, 2017 9:47_

Saw this in a few builds logs in github.com/dotnet/roslyn-project-system, looks like GenerateTargetFrameworkMonikerAttribute always considers itself out-of-date but won't generate the file to make it up-to-date:

```
Building target "GenerateTargetFrameworkMonikerAttribute" completely.
Input file "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\bin\Microsoft.Common.targets" is newer than output file "C:\Users\davkean\AppData\Local\Temp\.NETStandard,Version=v1.0.AssemblyAttributes.cs".
Task "WriteLinesToFile" skipped, due to false condition; ('@(Compile)' != '' and '$(TargetFrameworkMonikerAssemblyAttributeText)' != '') was evaluated as ('' != '' and '
// <autogenerated />
using System;
using System.Reflection;
[assembly: global::System.Runtime.Versioning.TargetFrameworkAttribute(".NETStandard,Version=v1.0", FrameworkDisplayName = "")]
        ' != '').
Done building target "GenerateTargetFrameworkMonikerAttribute" in project "Composition.csproj".: (TargetId:1223)
```

_Copied from original issue: dotnet/sdk#919_

**Comment by davkean** [comment]
_From @rainersigwald on February 27, 2017 15:51_

Is your `@(Compile)` really empty? That seems unusual.

**Comment by davkean** [comment]
In this case, yes it is empty - that explains it. Perhaps GenerateTargetFrameworkMonikerAttribute should even be run in this case?

**Comment by davkean** [comment]
_From @nguerrera on March 1, 2017 3:49_

This isn't specific to SDK, right? Common targets would do this for any empty @(Compile) if I've understood correctly. I'm not sure it's worth optimizing for that case, but if you think it is, you should probably move this to the msbuild repo.

**Comment by davkean** [comment]
Yeah, thought there was something specific about .NET Standard - I didn't realize we were hitting this because of the empty Compile. I'll move it.

**Comment by ladipro** [comment]
Perf triage: Closing an old and low-pri issue.
