### ISSUE TITLE
Figure out plan for Mono flavors

### ISSUE THREAD

**Issue by rainersigwald** [dotnet/msbuild#1800]
We need to either teach the Sdk projects about Mono, or collapse the Mono differences into all run-time checks so there's no separate Mono binary (somewhat riskier).

**Comment by rainersigwald** [comment]
One possibility: introduce a new `net471` (or something) TFM that we "know" is Mono; that allows multitargeting without SDK friction at the cost of mental overhead (and we'd have to be careful about packaging it).

**Comment by marcpopMSFT** [comment]
Here is the plan going forward for Mono: https://github.com/dotnet/msbuild/issues/7034#issuecomment-967257469
