### ISSUE TITLE
string.Split behaves differently on Mono than it does on Windows .NET framework

### ISSUE THREAD

**Issue by agocke** [dotnet/msbuild#191]
When calling the following code on Mono I get a different result than on Windows:

https://github.com/Microsoft/msbuild/blob/xplat/src/XMakeTasks/Microsoft.Common.CurrentVersion.targets#L1134

Specifically, on Mono the resulting property has the value `System.String[]`, whereas on Windows it seems to have the same value as the string before the `.Split`.

**Comment by dsplaisted** [comment]
I think @ValMenn also ran into this.

**Comment by ValMenn** [comment]
I think the reason is that `System.String[]` does not support IEnumerable in Mono. When a function returns a value that does not support IEnumerable, MSBuild converts that value to a string (which in this case is "System.String[]"). I don't know why System.String[] does not support IEnumerable.

**Comment by akoeplinger** [comment]
@ValMenn that doesn't sound right to me, string[] definitely supports IEnumerable on Mono.

**Comment by dsplaisted** [comment]
How does MSBuild determine whether something "supports" IEnumerable?  Does it call `Type.IsAssignableFrom`, `Type.GetInterfaces`, or is it using something like `Convert.ChangeType`.  Maybe one of those has different behavior on Mono.

**Comment by ValMenn** [comment]
@akoeplinger it was just a guess. I did not spend much time debugging it. I assumed `ConvertToString` in Expander.cs was called at some point and I could only assume that `Split` returned `System.String[]`. But there may be other possibilities.

**Comment by SamB** [comment]
@ValMenn: There actually seem to be an awful lot of `Object.ToString` calls in there where I would expect `ConvertToString` to be used instead; `System.String[]` could easily be coming from one of those.
