### ISSUE TITLE
MsBuild with netstandard1.5 Task throws FileNotFoundException 'System.Runtime, Version=4.1.0.0'

### ISSUE THREAD

**Issue by lecaillon** [dotnet/msbuild#1940]
A custom task (which just logs a string) targeting the netstandard1.4 is well executed by MsBuild, while the same targeting netstandard1.5 fails with this error message: 

> error MSB4018: System.IO.FileNotFoundException: Could not load file or
> assembly 'System.Runtime, Version=4.1.0.0, Culture=neutral,
> PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The
> system cannot find the file specified.

Here is the .targets file:

```xml
<UsingTask TaskName="ClassLibrary1.Class1" AssemblyFile="$(MSBuildThisFileDirectory)ClassLibrary1.dll" />
<Target Name="Test" AfterTargets="Build">
  <Class1 />
</Target>
```

And the task class:

```c#
    using Microsoft.Build.Framework;
    using Microsoft.Build.Utilities;
    
    namespace ClassLibrary1
    {
        public class Class1 : Task
        {
            public override bool Execute()
            {
                Log.LogMessage(MessageImportance.High, "Bonjour !");
                return true;
            }
        }
    }
```

I use Visual Studio 2017 and build a netcoreapp 1.1 project.

**Comment by dsplaisted** [comment]
I'm not sure this is supposed to work.  If I'm remembering correctly, .NET Standard 1.5 is not supported by .NET 4.6.1.

**Comment by lecaillon** [comment]
I believe it should support it, if I understand well this blog?
https://github.com/dotnet/standard/blob/master/docs/versions.md

**Comment by AArnott** [comment]
This is making it difficult for me as well. I want to target netstandard1.5 rather than an earlier version because 1.5 is necessary to reference `System.Runtime.Loader`.

**Comment by lecaillon** [comment]
@AArnott I've got this problem for the exact same reason: I want to reference `System.Runtime.Loader`

**Comment by gulbanana** [comment]
System.Runtime.Loader won't work on .net framework. Its netstandard requirement is a bit of a mistake and it really only supports .net core.

**Comment by AArnott** [comment]
Wow. That needs to be *clearly* called out in documentation and a new version of the package should target only netcoreapp in that case.

**Comment by dasMulli** [comment]
The `System.Runtime.Loader` package has a `_._` file in its `lib/net462` folder to indicate it doesn't support .net framework.. this caused a discussion in https://github.com/dotnet/cli/issues/6019

**Comment by lecaillon** [comment]
In my case this means that a `Microsoft.Build.Framework.Task` that needs to load an assembly at runtime must be developed  in .NET (with AppDomain) when it is executed from MSBuild and .NET Core (with AssemblyLoadContext) when it is executed from dotnet build?
If true, will this evolve with the release of the .NET standard 2.0?

**Comment by AArnott** [comment]
> In my case this means that a Microsoft.Build.Framework.Task that needs to load an assembly at runtime must be developed in .NET (with AppDomain) when it is executed from MSBuild and .NET Core (with AssemblyLoadContext) when it is executed from dotnet build?

Ya. It's a major pain. So much so that I created a nuget package specifically to help developing msbuild tasks that require assembly load isolation. [The project](https://github.com/AArnott/Nerdbank.MSBuildExtension) multi-targets for netcoreapp1.0 and net45, including a netstandard1.5 facade so you can just derive your Task from [`ContextIsolatedTask`](https://github.com/AArnott/Nerdbank.MSBuildExtension/blob/master/src/Nerdbank.MSBuildExtension/ContextIsolatedTask.cs) and it can then run on either platform and it will get the right style of isolation for the version of msbuild that runs your task.

I have some tests for it that work already. But in my more complex use case for this where I'm hosting roslyn inside my Task, failures still occur that I still haven't figured out.

**Comment by lecaillon** [comment]
Thanks @AArnott, your MSBuild targets file [Nerdbank.GitVersioning.targets ](https://github.com/AArnott/Nerdbank.GitVersioning/blob/master/src/Nerdbank.GitVersioning.NuGet/build/Nerdbank.GitVersioning.targets) helped me a lot to select the correct Task depending of the build context:
```xml
<_NBGV_PlatformSuffix Condition=" '$(_NBGV_PlatformSuffix)' == '' and '$(MSBuildRuntimeType)' == 'Core' ">MSBuildCore/</_NBGV_PlatformSuffix>
<_NBGV_PlatformSuffix Condition=" '$(_NBGV_PlatformSuffix)' == '' ">MSBuildFull/</_NBGV_PlatformSuffix>
<NerdbankGitVersioningTasksPath Condition=" '$(NerdbankGitVersioningTasksPath)' == '' ">$(MSBuildThisFileDirectory)$(_NBGV_PlatformSuffix)</NerdbankGitVersioningTasksPath>
```

**Comment by Rabadash8820** [comment]
@lecaillon Is this issue still occurring with newer versions of .NET Standard (or .NET 6)? If not, might be worth closing this issue...
