### ISSUE TITLE
64bit projects depending on Microsoft.Build.Runtime cannot programmatically start out of proc builds

### ISSUE THREAD

**Issue by cdmihai** [dotnet/msbuild#1941]
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net46</TargetFramework>
  </PropertyGroup>

  <PropertyGroup>
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>
  
  <ItemGroup>
    <PackageReference Include="Microsoft.Build.Runtime" Version="15.1.548" />
  </ItemGroup>

</Project>
```

```c#
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using Microsoft.Build.Execution;

namespace ConsoleApp4
{
    class Program
    {
        static void Main(string[] args)
        {
            var projecContents = @"
<Project>
  <Target Name=""build"">  
    <Message Text=""Hello""/>
  </Target>
</Project>";

            var projectFile = Path.GetTempFileName();
            File.WriteAllText(projectFile, projecContents);

            var requestData = new BuildRequestData(projectFile, new Dictionary<string, string>(), null, new string[0], null);
            var buildParameters = new BuildParameters
            {
                MaxNodeCount = Environment.ProcessorCount,
                EnableNodeReuse = false,
                DisableInProcNode = true
            };

            var buildResults = new BuildManager().Build(buildParameters, requestData);

            Trace.Assert(buildResults.OverallResult == BuildResultCode.Success);
        }
    }
}
```

Fails with:
`Build was canceled. Failed to successfully launch or connect to a child MSBuild.exe process. Verify that the MSBuild.exe "C:\Users\micodoba\Documents\visual studio 2017\Projects\ConsoleApp4\ConsoleApp4\bin\Debug\net46\MSBuild.exe" launches successfully, and that it is loading the same microsoft.build.dll that the launching process loaded. If the location seems incorrect, try specifying the correct location in the BuildParameters object, or with the MSBUILD_EXE_PATH environment variable.`

This is because the starting process is 64bit but the spawned msbuild nodes are 32bit.

There are two action items for this issue:
- [ ] include x64 msbuild.exe in the nuget packages
- [ ] update `NodeProviderOutOfProcBase.GetNode` to search for x64 msbuild.exe if the invoking process is (not msbuild.exe) and x64.

**Comment by rainersigwald** [comment]
I don't think we'll add this support to the Runtime package--that's now entirely an implementation detail of the .NET SDK. Instead, use MSBuildLocator.
