### ISSUE TITLE
adding Retries, RetryDelayMilliseconds parameters to Delete task

### ISSUE THREAD

**Issue by chipitsine** [dotnet/msbuild#199]
Copy task already has such parameters.
it is good for situations when one asynchronously stops windows service (for example) and one need to make sure that files are not locked anymore

I'm not saying that situation itself is good. However, I like the approach of "Copy" task, it allows me to wait for some time and copy files again.

I would like to add such parameters to "Delete" task as well.

if nobody minds, I will make pull request

**Comment by rainersigwald** [comment]
I mind on general principle because retries are icky, but I'm convinced by your argument.

Team triage:  we would be amenable to accepting such a pull request.

**Comment by chipitsine** [comment]
I could not get solution compiled until I made some changes https://github.com/chipitsine/msbuild/commit/c09566ed91500d1aca1b7dbbcd36e14143279f91

can you please review those changes ? it might me either something with my environment or with solution itself.

after that review I will make pull request for "Delete" task

**Comment by chipitsine** [comment]
I tried to follow compilation guide as much as possible actually

**Comment by sandos** [comment]
We needed this today for a situation where a shutdown of an external ftp-client would release a file-lock, but we do not know exactly how long that takes. An excessive timeout is no fun in automatic tests, so a poll+retry is nice.

Just a +1
