### ISSUE TITLE
Microsoft.Build.Framework nupkg pulls in unnecessary dependencies when consumed from net46 project

### ISSUE THREAD

**Issue by nguerrera** [dotnet/msbuild#1992]
Spotted in sln explorer:
![image](https://cloud.githubusercontent.com/assets/75470/25158932/eb5bea10-2460-11e7-982e-78348dc42b1a.png)

And that causes extra System.* dll in my net46 build output:
![image](https://cloud.githubusercontent.com/assets/75470/25158957/164ae366-2461-11e7-8e5b-2cc94196990d.png)

However, the net46 version of Microsoft.Build.Framework.dll has only these references:
```
.assembly extern mscorlib
{
  .publickeytoken = (B7 7A 5C 56 19 34 E0 89)
  .ver 4:0:0:0
}
.assembly extern System.Xaml
{
  .publickeytoken = (B7 7A 5C 56 19 34 E0 89)
  .ver 4:0:0:0
}
.assembly extern System
{
  .publickeytoken = (B7 7A 5C 56 19 34 E0 89)
  .ver 4:0:0:0
}
```

I believe the issue is that there needs to be an empty dependency group for net46 in the .nuspec. Without it, the dependencies for netstandard1.3 seem to flow to net46.

**Comment by nguerrera** [comment]
@dsplaisted @livarcocc

**Comment by rainersigwald** [comment]
Dependencies are likely radically different now, so I'm going to close "hopefully fixed at some point in the last 5 years".
