### ISSUE TITLE
Microsoft.Build.Runtime: experience different behaviour depending on csproj style for net46

### ISSUE THREAD

**Issue by xgalaxy** [dotnet/msbuild#1995]
System:
```
Visual Studio Community 2017 (Version 15.1 - 26403.7 Release)
NuGet Package Manager 4.1.0
```

Setup A:

1. Create new Console App (.NET Framework) w/ .NET Framework 4.6
2. Install Microsoft.Build.Runtime v15.1.548
3. Note: Visual Studio and NuGet use the old Packages.config NuGet format for this project
4. Insert the following code in Program.cs
```
internal class Program
    {
        private static void Main(string[] args)
        {
            var solutionDirectory = "<path to your solution>";
            var projectFilePath = "<path to the csproj in the solution>";

            var globalProperties = new Dictionary<string, string> {
                { "DesignTimeBuild", "true" },
                { "BuildProjectReferences", "false" },
                { "_ResolveReferenceDependencies", "true" },
                { "SolutionDir", solutionDirectory + Path.DirectorySeparatorChar }
            };

            var collection = new ProjectCollection();
            Project project = collection.LoadProject(projectFilePath);
        }
    }
```
5. Run the program.

Result:
Everything seems to work properly. The project compiles fine. The program can load and evaluate a net46 project and it appears to be able to load and evaluate a net core project.

Setup B:

1. Create new Console App (.NET Framework) w/ .NET Framework 4.6
2. Modify the the created csproj file to use the new csproj file format [as demonstrated here](http://www.natemcmaster.com/blog/2017/03/09/vs2015-to-vs2017-upgrade/)
3. Install Microsoft.Build.Runtime v15.1.548
4. Note: Visual Studio and NuGet use the new PackageReference NuGet format for this project
5. Insert the same code for Program.cs as in Setup A.
6. Run the program.

Result:
The program throws an assembly not found exception: Cannot find `System.Threading.Tasks.Dataflow`. After manually installing the missing assembly from NuGet another exception is thrown: `Microsoft.Build.Exceptions.InvalidProjectFileException: 'The imported project "D:\Code\ConsoleApp1\ConsoleApp1\bin\Debug\net46\Sdks\Microsoft.NET.Sdk\Sdk\Sdk.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.'`

**Comment by AndyGerlicher** [comment]
If you use our runtime package (MSBuild.exe + content) it treats that as a distribution of MSBuild. This means it should not use anything from outside that instance of MSBuild. So you would have to package all dependencies, in this case the SDKs that .NET CLI/VS package.

If this is not what you want and you'd like to use an installed copy of MSBuild to load/parse/build, you can see my explanation in #1784 and the PR I sent to that dotnet-builder project with code to find MSBuild and not distribute MSBuild in your application.

**Comment by xgalaxy** [comment]
And what about on Mono? The linked ticket only explains how to find MSBuild in a Windows environment that uses Visual Studio.

**Comment by dasMulli** [comment]
> So you would have to package all dependencies, in this case the SDKs that .NET CLI/VS package

Related: https://github.com/dotnet/sdk/issues/300

omnisharp-roslyn [sets global properties](https://github.com/OmniSharp/omnisharp-roslyn/blob/0ad7681ea8dbd855dd838f608636c95921e327bd/src/OmniSharp.MSBuild/ProjectFile/ProjectFileInfo.cs#L205-L213) to be able to work with project files.

Assembling the proper directory layout so that everything works out of the box is tricky, but setting `MSBuildSDKsPath`, `MSBuildExtensionsPath` and `CscToolExe` to the locations of a known working installation (e.g. private copy of a .net core CLI) makes it work. (this also allows mono's msbuild to build SDK / .net core projects.. see [this gist](https://gist.github.com/dasMulli/29c7d68f321cc5ac4a68407a6fd76d19) for example)

**Comment by xgalaxy** [comment]
Unless I'm completely misunderstanding something, I think people are missing the heart of the issue:

**There is also no explanation as to why I'm seeing different behavior when using old csproj from new csproj even though both are targeting FULL Net Framework and not Core.**

**Comment by AndyGerlicher** [comment]
The target is a lot less relavent than what build SDK they use, and that's the difference you're seeing. If you look in an old C# file you'll see MSBuild importing build logic directly from `MSBuildExtensionsPath`:
```XML
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="14.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props" Condition="Exists('$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props')" />
...
  <Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets" />
</Project>
```

New style is:
```XML
<Project Sdk="Microsoft.NET.Sdk">
...
</Project>
```

The 2nd translate to an import into the MSBuild SDKs folder. The default location for is `Sdks` folder under the folder where MSBuild.exe is located. In your example it's looking for the `Microsoft.NET.SDK` under `D:\Code\ConsoleApp1\ConsoleApp1\bin\Debug\net46\Sdks\Microsoft.NET.Sdk\Sdk\Sdk.props`. It might be helpful to run `MSBuild.exe <project>.csproj /pp:out.proj` to see exactly what files MSBuild is importing.

Is that helpful?

**Comment by xgalaxy** [comment]
Yes thanks I think I understand now.

**Comment by Forgind** [comment]
It sounds like the problem was resolved or at least worked around? If not, let us know, and we can reopen this.
