### ISSUE TITLE
Wrong and weird build behavior after upgrading to VS 2017 

### ISSUE THREAD

**Issue by al1b** [dotnet/msbuild#2033]
I have a solution with many projects. Since I've upgraded to VS 2017 I've faced weird build behavior problems.

1. I cleaned up the solution
2. I **build** the solution, some of the dll assemblies were outdated! For example I build the solution today, but some assemblies modified-date were about a month ago. ( I'm 100% sure, source code of those assemblies were changed today ). I also used a dotnet reflector to decompile the assembly and I saw the code is outdated and that's not the code that I wrote today.
3. I **rebuild** the project, the msbuild result were about a couple of compile errors
3.1 Errors such as `CS1061	'xxx' does not contain a definition for 'yyy' and no extension method 'Move' accepting a first argument of type 'xxx' could be found (are you missing a using directive or an assembly reference?)`
3.2 The most weird thing is those `xxx` and `yyy` are do exist! and if I rebuild that project alone , that error won't show up!

**Some important notes:**

1. I have a `PowerShell` script to build my solution. 
2. The resutl from `PowerShell` script and build inside VS is the same, and the same weird behavior.
3. Everything were fine before VS 2017 and its msbuild.

**Comment by Forgind** [comment]
This hasn't received any attention for the past few years. If this is still an issue, let us know, and we can reopen it.
