### ISSUE TITLE
Investigate Log Task Inputs performance

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/msbuild#2200]
The amount of data passed to NuGet tasks is huge, but @nguerrera points out we do unnecessary string concatenation there. Let's investigate builds with `/v:diag` (that enable log task inputs).

See also:
https://github.com/Microsoft/msbuild/issues/2164
https://github.com/Microsoft/msbuild/issues/2168

**Comment by nguerrera** [comment]
I was asked for a brain dump on this. Here's all I have: Loggers are passed the each parameter as one string. If the parameters are items, then all the items and their metadata go together in one string. This can end up on the large object heap and cause perf problems. I would imagine a fix involving streaming the items to the log without concatenating them in to a string.

**Comment by KirillOsenkov** [comment]
See also:
http://source.dot.net/#Microsoft.Build/BackEnd/TaskExecutionHost/TaskExecutionHost.cs,1542

**Comment by KirillOsenkov** [comment]
This is now fixed by #6155.
