### ISSUE TITLE
MSBuild is boxing 25 MB worth of ImmutableList<T>/List<T> enumerators

### ISSUE THREAD

**Issue by davkean** [dotnet/msbuild#2265]
Looking at trace from @jainaashish, I noticed that MSBuild is boxing 25 MB (0.6% of the entire scenario - which was installing a bunch of NuGet pages) worth of enumerators:

![image](https://user-images.githubusercontent.com/1103906/27898972-b4b9588c-626b-11e7-80cb-460ee31594a8.png)

See: \\scratch2\scratch\asja\AddReference Perf ETL logs

These are struct enumerators - so they are probably being passed as `IEnumerable<string>` somewhere.

**Comment by ladipro** [comment]
- At least half of this was fixed in #2634.
- The traces are not available anymore.
- We have an effort to improve evaluation performance going on based on fresh traces (#6034).
