### ISSUE TITLE
Create project evaluation sessions to enable IO caching

### ISSUE THREAD

**Issue by cdmihai** [dotnet/msbuild#2306]
One way to improve perf is to cache IO operations during project evaluation. The lifespan of the cache should be per some user controlled evaluation session:

```c#
var session= new EvaluationSession();

var projects = projectPaths.Select(p => new Project(p, session));
```

IO operations to cache:
- file existence checks
- directory enumerations

**Comment by ladipro** [comment]
This appears to have been addressed with [EvaluationContext](https://github.com/dotnet/msbuild/blob/main/src/Build/Evaluation/Context/EvaluationContext.cs) and [CachingFileSystemWrapper](https://github.com/dotnet/msbuild/blob/main/src/Shared/FileSystem/CachingFileSystemWrapper.cs). @cdmihai please reopen if you disagree.
