### ISSUE TITLE
MSB1003 when *nix system has a /m file or directory

### ISSUE THREAD

**Issue by rainersigwald** [dotnet/msbuild#2351]
_From @svick on July 23, 2017 8:37_

I'm trying to use the portable Linux release of .Net Core SDK 2.0 Preview 2 on a Gentoo machine and I'm getting some strange behavior from msbuild, which means I can't run `dotnet restore`.

What I did:

```bash
~$ cat /etc/*-release
Gentoo Base System release 2.3
DISTRIB_ID="Gentoo"
NAME=Gentoo
ID=gentoo
PRETTY_NAME="Gentoo/Linux"
ANSI_COLOR="1;32"
HOME_URL="https://www.gentoo.org/"
SUPPORT_URL="https://www.gentoo.org/support/"
BUG_REPORT_URL="https://bugs.gentoo.org/"
~$ mkdir dotnet
~$ cd dotnet
~/dotnet$ curl -sSL -o dotnet.tar.gz https://aka.ms/dotnet-sdk-2.0.0-preview2-linux-x64-bin
~/dotnet$ tar xf dotnet.tar.gz
~/dotnet$ PATH=$PATH:$HOME/dotnet
~/dotnet$ cd ..
~$ mkdir hwapp
~$ cd hwapp
~/hwapp$ dotnet new console
The template "Console Application" was created successfully.

Processing post-creation actions...
Running 'dotnet restore' on /afs/ms.mff.cuni.cz/u/o/ondep7am/hwapp/hwapp.csproj...
MSBUILD : error MSB1008: Only one project can be specified.
Switch: /afs/ms.mff.cuni.cz/u/o/ondep7am/hwapp/hwapp.csproj

For switch syntax, type "MSBuild /help"


Restore failed.
Post action failed.
Description: Restore NuGet packages required by this project.
Manual instructions: Run 'dotnet restore'

~/hwapp$ ls
Program.cs  hwapp.csproj
~/hwapp$ dotnet restore
MSBUILD : error MSB1003: Specify a project or solution file. The current working directory does not contain a project or solution file.
~/hwapp$ dotnet restore hwapp.csproj
MSBUILD : error MSB1008: Only one project can be specified.
Switch: hwapp.csproj

For switch syntax, type "MSBuild /help"
```

If I follow the same steps on a brand new AWS Gentoo VM, it works fine. So it looks like an issue specific to that machine, not to Gentoo in general.

What can I do to analyze this issue further?

_Copied from original issue: dotnet/cli#7227_

**Comment by rainersigwald** [comment]
_From @livarcocc on July 23, 2017 22:39_

Can you do a dotnet restore /v:diag > log.txt and share the log.txt file?

cc @rainersigwald

**Comment by rainersigwald** [comment]
_From @svick on July 23, 2017 22:43_

@livarcocc That doesn't give any additional information:

```bash
~/hwapp$ dotnet restore /v:diag
MSBUILD : error MSB1003: Specify a project or solution file. The current working directory does not contain a project or solution file.
```

**Comment by rainersigwald** [comment]
_From @livarcocc on July 24, 2017 4:46_

@rainersigwald Any ideas how to debug this or what might be going on here?

**Comment by rainersigwald** [comment]
I haven't seen anything like this before, unfortunately. If I could reproduce it locally I'd probably try debugging or making private MSBuild bits that spewed more information. But since this is on Linux I bet we can use [wizardry](https://jvns.ca/zines/#strace-zine) instead.

@svick Could you share an `strace` of the failure? I think

```sh
strace -f -o missing_project_file dotnet restore
```

Should do the trick. Then zip and upload `missing_project_file*`, please.

**Comment by rainersigwald** [comment]
_From @svick on July 25, 2017 15:15_

@rainersigwald That command produced only one file: [missing_project_file.zip](https://github.com/dotnet/cli/files/1173834/missing_project_file.zip)

**Comment by rainersigwald** [comment]
Thanks!

I think line 14175 is the problem:

```
6713  stat("/m", {st_mode=S_IFDIR|0755, st_size=60, ...}) = 0
```

@svick do you have a directory at the root level named `m`? That is, does `/m` exist on this machine?

**Comment by rainersigwald** [comment]
_From @svick on July 25, 2017 15:43_

> @svick do you have a directory at the root level named m? That is, does /m exist on this machine?

Yes, `/m` does exist. It's a symlink to `/run/am`. It's not my machine, so I don't know what is the reason for that.

 Why would that be a problem?

**Comment by rainersigwald** [comment]
It's confusing the MSBuild command line parser into thinking that you're specifying `/m` as the project to build, rather than telling msbuild to build in multiprocess mode.

We should do better. I'm going to copy this bug over to MSBuild.

**Comment by rainersigwald** [comment]
The problem comes down to [this line](https://github.com/Microsoft/msbuild/blob/073abdb45a78365f310b4b5af13796d63d0cdd60/src/MSBuild/XMake.cs#L1428):

```c#
if (!unquotedCommandLineArg.StartsWith("-", StringComparison.Ordinal) && (!unquotedCommandLineArg.StartsWith("/", StringComparison.Ordinal) || FileUtilities.LooksLikeUnixFilePath(unquotedCommandLineArg)))
```

That decides that `/m` looks like a path so it must be a project argument.

We should special case `/m`. It would prevent building a project named `/m`, but that violates convention (doesn't match `*proj`) and should be very rare, compared to merely _having_ a `/m` directory or file.

**Comment by svick** [comment]
@rainersigwald I take it there are no other switches that could reasonably exist in `/`? For example, as far as I can tell, `/v:m` and `/NoLogo` also have this issue, but I wouldn't expect anyone to have files or directories with those names in `/`.

**Comment by rainersigwald** [comment]
It could happen with an arbitrary MSBuild switch.

@jeffkl proposed attempting to parse every argument as an MSBuild switch, then falling back to path specifications, which seems to make sense (but may be easier said than done).

`/m` and `/v:m` are special because they're [hardcoded into the CLI](https://github.com/dotnet/cli/blob/93a4ae7f351160ae93030e2446d32117c85f5515/src/Microsoft.DotNet.Cli.Utils/MSBuildForwardingAppWithoutLogging.cs#L32), so a user can't work around their existence with `-`-prefixed arguments.

**Comment by Imisnew2** [comment]
Just ran into this issue myself after pulling my hair out. It works on one machine, but not the other?! Can't get any information from /v:diag. Can't get any information from /fl:<whatever>. What the heck is going on? COREHOST_TRACE=1 (with 'dotnet build') to look at command line arguements -- seems sane. Finally, after digging through 'strace -f dotnet build' did I have the right keywords to land me at this bug report.

For what it's work, the machine I'm looking at has an /m directory. It is not my machine.

**Comment by Ka-Mau** [comment]
Here the same. Please fix this bug!!! Thank you.

**Comment by kasper3** [comment]
`mkdir /m`
`mkdir /restore`
`mkdir /v:m`
`mkdir /fl:whatever`
`mkdir /p:Configuration=Release`

all create directories at system root on Unix and can break msbuild thereafter. We probably don't want .NET Core docs telling the user to not have directories with those names because it will break msbuild.

Maybe have a breaking change and introduce Unix-y arguments, for full name: `--switch`, for alias: `-a`.

**Comment by dasMulli** [comment]
All of the switch-based arguments should work on *nix, maybe a more compatible change would be to move to `-m -v:m -flp:xyz -p:Foo=Bar` in at least the CLI and then maybe in documentation (docs for the c# compiler have changed to switches already)

**Comment by rainersigwald** [comment]
https://github.com/dotnet/cli/pull/8969 switched the CLI to use dash arguments everywhere, and if you're adding an argument explicitly, you can use the dash form, so I'm going to close this.
