### ISSUE TITLE
Builds are spending lots of time (~4.5%) of CPU just sleeping

### ISSUE THREAD

**Issue by davkean** [dotnet/msbuild#2391]
Trying to speed up design-time builds, and I can see that 4.5% of the CPU is just sleeping (is this spin waiting?):

![image](https://user-images.githubusercontent.com/1103906/28905684-91c81534-7855-11e7-8567-3878456afbae.png)

Could be related to: https://github.com/Microsoft/msbuild/pull/2384.

**Comment by davkean** [comment]
I can't tell if this is "real" CPU usage or if the thread was really sleeping when PerfView captured. I thought that PerfView sampled whatever the CPU was executing at the time, which lean to the former.

**Comment by davkean** [comment]
In this customer's process, 11% of the build is just calling Sleep: https://github.com/dotnet/project-system/issues/2712.

**Comment by onyxmaster** [comment]
Found this issue occasionally after a PerfView session of my own.
IIRC, this callstack means that thread pool is being hammered with lots of thread creation requests (QueueUserWorkItem, tasks, etc.) that arrive in a short time interval, so yes, #2384 is probably the real deal.

**Comment by ladipro** [comment]
These sleeps were eliminated in #6678.
