### ISSUE TITLE
IndexOfAny/ProbablyContains/InitializeProbabilisticMap is showing up on radar

### ISSUE THREAD

**Issue by davkean** [dotnet/msbuild#2411]
See: https://github.com/dotnet/corefx/issues/22771

I've looked at 3 large solutions where IndexOfAny usage is showing up on the radar. I initially thought that it maybe caused by Directory.GetFiles/GetDirectories usage (where they check for invalid chars) but looking at this trace: https://github.com/Microsoft/msbuild/issues/2348, I see it consuming *a lot* (25% of CPU) - but very little time spent in GetFiles/GetDirectories. 

Check usage of other Path APIs, such as GetExtension which also does a invalid char check - it may be caused by this.

I suspect we should just hand write IndexOfAny checks for known chars.

**Comment by davkean** [comment]
Feel free to assign this one to me.

**Comment by davkean** [comment]
I strongly suspect this has to do with http://index/?query=ExpandPropertiesLeaveTyped&rightProject=Microsoft.Build&file=Evaluation%5CExpander.cs&line=933:

``` C#
                // If there are no substitutions, then just return the string.
                propertyStartIndex = s_invariantCompareInfo.IndexOf(expression, "$(", CompareOptions.Ordinal);
                if (propertyStartIndex == -1)
                {
                    return expression;
                }

```

**Comment by davkean** [comment]
I believe these belong together (ProbablyContains/InitializeProbabilisticMap usage is always a broken stack so they aren't grouped):

![image](https://user-images.githubusercontent.com/1103906/30577494-f3b02ee6-9d51-11e7-938b-6fb53e07d77c.png)

**Comment by davkean** [comment]
I don't know what the cause of this is, I replaced all usage of IndexOfAny and LastIndexOfAny and it's still showing up on the radar.

**Comment by davkean** [comment]
Could be AppendEscapedString?

**Comment by davkean** [comment]
I have a strong suspicion that this is all EscapingUtilities.

**Comment by ladipro** [comment]
`clr!ProbablyContains`
`clr!InitializeProbabilisticMap`
`clr!COMString::IndexOfCharArray`

together amount to ~0.4% of evaluation time according to recent @arkalyanms's traces.

ProbablyContains and InitializeProbabilisticMap have broken stacks and IndexOfCharArray (~0.2% of eval time) has many callers with nothing standing out:

![image](https://user-images.githubusercontent.com/12206368/114545088-d0903200-9c5b-11eb-9d24-1fc1b7ed251a.png)

Based on this I'm inclined to close this unless @davkean remembers the scenario where the excessive cost was observed.

**Comment by davkean** [comment]
I have seen popup in a few traces recently as much as what caused me to file the original CoreFx but the traces are long gone. I will keep an eye out for it and reopen this if you close it if I see it again.
