### ISSUE TITLE
MSBuild has non-trivial overhead due to JIT'ing

### ISSUE THREAD

**Issue by davkean** [dotnet/msbuild#2419]
VisualStudio.15.IntPreview/15.3.0-pre.7.0+26730.0.d15rel

1. Enlist in Roslyn (assuming e:\Roslyn, otherwise change paths)
2. Restore.cmd
3. Run:

```
msbuild /nologo /m:1 /v:m /clp:Summary;PerformanceSummary /flp:v:d /t:ReportAssetsLogMessages /p:"SolutionFileName=Roslyn.sln;LangName=en-US;Configuration=Debug;LangID=1033;DesignTimeBuild=true;SolutionDir=E:\\roslyn\\;SolutionExt=.sln;BuildingInsideVisualStudio=true;DefineExplicitDefaults=true;Platform=AnyCPU;SolutionPath=E:\\roslyn\\Roslyn.sln;SolutionName=Roslyn;DevEnvDir=C:\Program Files (x86)\Microsoft Visual Studio\Enterprise\Common7\IDE;BuildingProject=false" E:\roslyn\src\Compilers\Core\CodeAnalysisTest\CodeAnalysisTest.csproj
```

```
Project Evaluation Performance Summary:
      149 ms  E:\roslyn\src\Compilers\Core\CodeAnalysisTest\CodeAnalysisTest.csproj   1 calls

Project Performance Summary:
      142 ms  E:\roslyn\src\Compilers\Core\CodeAnalysisTest\CodeAnalysisTest.csproj   1 calls
                142 ms  ReportAssetsLogMessages                    1 calls

Target Performance Summary:
      141 ms  ReportAssetsLogMessages                    1 calls

Task Performance Summary:
      134 ms  ReportAssetsLogMessages                    1 calls

Build succeeded.
    0 Warning(s)
    0 Error(s)
```

In the above, the following binaries are JIT'd consuming 150ms of CPU time, is this expected?

Name | JitTimemsec | Num Methods | IL Size | Native Size
-- | -- | -- | -- | --
TOTAL | 155.3 | 568 | 48,467 | 133,499
C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise\MSBuild\15.0\Bin\System.Collections.Immutable.dll | 22.7 | 23 | 888 | 2,038
C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise\MSBuild\15.0\Bin\Microsoft.Build.dll | 19.8 | 79 | 8,163 | 17,994
C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise\MSBuild\15.0\Bin\Microsoft.Build.Utilities.Core.dll | 1.0 | 2 | 343 | 728
C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise\MSBuild\15.0\bin\MSBuild.exe | 0.8 | 1 | 67 | 153
C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise\MSBuild\15.0\Bin\Microsoft.Build.Framework.dll | 0.5 | 5 | 169 | 335

**Comment by davkean** [comment]
When I tried to NGEN these binaries manually, it seems like they already had NGEN entries - are you passing MSBuild's config file to NGEN so that it generates images based on the binding policy?

**Comment by davkean** [comment]
Hmm, I tried manually passing a config or appbase to ngen and Immutable - it doesn't help, we still JIT it - perhaps it's just some of the generic methods that we can't produce native code up front for?

**Comment by davkean** [comment]
Use Advanced Group -> Jit Stats in PerfView to see what's being JIT'd.

**Comment by davkean** [comment]
I can see these NGEN images getting loaded:

![image](https://user-images.githubusercontent.com/1103906/29202853-522ea6e4-7eaf-11e7-9c15-9c47e856341a.png)
![image](https://user-images.githubusercontent.com/1103906/29202863-6fa849b4-7eaf-11e7-8945-fecc356f5805.png)
![image](https://user-images.githubusercontent.com/1103906/29202905-c14bc67e-7eaf-11e7-81e7-e91189e84467.png)
![image](https://user-images.githubusercontent.com/1103906/29202916-de0479aa-7eaf-11e7-8c80-04e91b45361f.png)

But it appears that are exhibiting patterns that cause them to be JIT'd.

**Comment by davkean** [comment]
Note, I filed https://github.com/Microsoft/msbuild/issues/2419 against CoreFx for the Immutable JIT which mostly is 1 method.

**Comment by rainersigwald** [comment]
We ngen through the VSIX:

https://github.com/Microsoft/msbuild/blob/2d8a4341875e532bdf25a14f208f62a7bb547774/setup/files.swr#L25

RPS has caught performance regressions when we accidentally didn't in the past, as well as when our binding redirect mismatched with VS's. So the "they're NGENed but still getting JITted" theory rings true to me.

**Comment by benaadams** [comment]
when trying to run command in summary getting error
```
roslyn\src\Compilers\Core\CodeAnalysisTest\CodeAnalysisTest.csproj : 
 error MSB4057: The target "ReportAssetsLogMessages" does not exist in the project.
```
e.g.
```
C:\GitHub\roslyn\src\Compilers\Core\CodeAnalysisTest\CodeAnalysisTest.csproj : error MSB4057: The target "ReportAssetsLogMessages" does not exist in the project.

Project Evaluation Performance Summary:
     6005 ms  C:\GitHub\roslyn\src\Compilers\Core\CodeAnalysisTest\CodeAnalysisTest.csproj   1 calls

Project Performance Summary:
      378 ms  C:\GitHub\roslyn\src\Compilers\Core\CodeAnalysisTest\CodeAnalysisTest.csproj   1 calls
                378 ms  ReportAssetsLogMessages                    1 calls

Build FAILED.

C:\GitHub\roslyn\src\Compilers\Core\CodeAnalysisTest\CodeAnalysisTest.csproj : error MSB4057: The target "ReportAssetsLogMessages" does not exist in the project.
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:08.60
```

**Comment by benaadams** [comment]
@davkean is there a roslyn branch that has `ReportAssetsLogMessages`? Can't find the jitted method

**Comment by davkean** [comment]
Need to be on 15.3 build.

**Comment by davkean** [comment]
Ah, sorry - I thought we back ported this to 1.1, I'm guessing we didn't? If so, install the latest 2.0 CLI to get this target.

**Comment by benaadams** [comment]
Ah am running with CoreRun.exe as have to target standalone and its not producing an exe; will rummage. Know where to look now :)

**Comment by davkean** [comment]
It comes from http://github.com/dotnet/sdk.

**Comment by benaadams** [comment]
Ah, copied all the stuff from `Microsoft Visual Studio\Preview\Enterprise\MSBuild` (Sdk/Microsoft/15) to the MSBuild directory, mostly seems to work - now getting an issue reading registry for CodeAnalysis
```
C:\GitHub\msbuild\bin\Release-NetCore\AnyCPU\Windows_NT\Windows_NT_Deployment>.\CoreRun.exe MSBuild.dll  /nologo /m:1 /v:m /clp:Summary;PerformanceSummary /flp:v:d /t:ReportAssetsLogMessages /p:"SolutionFileName=Roslyn.sln;LangName=en-US;Configuration=Debug;LangID=1033;DesignTimeBuild=true;SolutionDir=C:\\GitHub\\roslyn\\;SolutionExt=.sln;BuildingInsideVisualStudio=true;DefineExplicitDefaults=true;Platform=AnyCPU;SolutionPath=C:\\GitHub\\roslyn\\Roslyn.sln;SolutionName=Roslyn;DevEnvDir=C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise\Common7\IDE;BuildingProject=false" C:\GitHub\roslyn\src\Compilers\Core\CodeAnalysisTest\CodeAnalysisTest.csproj
C:\GitHub\msbuild\bin\Release-NetCore\AnyCPU\Windows_NT\Windows_NT_Deployment\Microsoft\VisualStudio\v15.0\CodeAnalysis\

Microsoft.CodeAnalysis.targets(26,5): error MSB4184: The expression 
"Registry:HKEY_LOCAL_MACHINE\Software\Microsoft\VisualStudio\15.0\Setup\EDev@StanDir" 
cannot be evaluated.  [C:\GitHub\roslyn\src\Compilers\Core\CodeAnalysisTest\CodeAnalysisTest.csproj]

Project Evaluation Performance Summary:
        0 ms  C:\GitHub\roslyn\src\Compilers\Core\CodeAnalysisTest\CodeAnalysisTest.csproj   1 calls

Project Performance Summary:
      126 ms  C:\GitHub\roslyn\src\Compilers\Core\CodeAnalysisTest\CodeAnalysisTest.csproj   1 calls
                126 ms  ReportAssetsLogMessages                    1 calls

Build FAILED.

C:\GitHub\msbuild\bin\Release-NetCore\AnyCPU\Windows_NT\Windows_NT_Deployment\Microsoft\VisualStudio\v15.0\CodeAnalysis\Microsoft.CodeAnalysis.targets(26,5): 
error MSB4184: The expression "Registry:HKEY_LOCAL_MACHINE\Software\Microsoft\VisualStudio\15.0\Setup\EDev@StanDir" 
cannot be evaluated.  [C:\GitHub\roslyn\src\Compilers\Core\CodeAnalysisTest\CodeAnalysisTest.csproj]
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:05.19
```
Can keep looking if you have any tips?

**Comment by rainersigwald** [comment]
@benaadams I suspect some of your bad time is mixing full framework world (installed to Program Files/VS) with coreclr msbuild.

Looks like you can safely delete `C:\GitHub\msbuild\bin\Release-NetCore\AnyCPU\Windows_NT\Windows_NT_Deployment\Microsoft\VisualStudio\v15.0\CodeAnalysis\Microsoft.CodeAnalysis.targets`; it's covered by an existence check:

https://github.com/Microsoft/msbuild/blob/2d8a4341875e532bdf25a14f208f62a7bb547774/src/Tasks/Microsoft.Common.CurrentVersion.targets#L5768-L5772

-------

The way I usually hack around with private bits of MSBuild in .NET Core scenarios is:

* Download and unzip an SDK from, say, https://dotnetcli.blob.core.windows.net/dotnet/Sdk/release/2.0.0/dotnet-sdk-latest-win-x64.zip
* Or just copy `C:\Program Files\dotnet\` to a folder of choice
* Make sure path points to it.
* Overwrite as desired. Interesting bits:
  * `{root}\sdk\2.0.0\` has the MSBuild assemblies and core MSBuild targets.
  * `sdk\2.0.0\MSBuild.deps.json` may interfere with loading private `System.*` assemblies and need to be altered.
  * SDKs in `sdk\2.0.0\Sdks\Microsoft.NET.Sdk` and parallel

You can do a similar thing with full framework MSBuild from the VS folder, but you have to search around for more bits.

We should have scripts to do that for you: #2425

**Comment by rainersigwald** [comment]
Oh wait, I don't think the SDK has all of the design-time targets. So if you really want to test on corefx, you'll probably have to do what you're doing and keep mangling things 'til they work :(

**Comment by davkean** [comment]
In a trace I did for this: https://github.com/dotnet/sdk/issues/1534, 56.3% of CPU time was just spent JITing. Node reuse doesn't help here because we don't reuse a node when there's only a single project.

**Comment by ladipro** [comment]
Reproduced with latest bits and the Build target (as ReportAssetsLogMessages no longer exists) and seeing >1.2 second of cummulative JIT time which is indeed excessive.

Simply running NGEN on MSBuild.exe reduced it by ~40%. Something is indeed off here.

**Comment by ladipro** [comment]
Doesn't look worth keeping around now that #6666 is in. There is still some JITting but it's caused by platform constraints - mainly generics - rather than a bug on our side. We're looking at tweaking our IBC optimization process in #6067.
