### ISSUE TITLE
Resolving Nuget dependencies and other 3rd party dependencies

### ISSUE THREAD

**Issue by Dirkster99** [dotnet/msbuild#2450]
I am currently trying to remove more and more components from my project and and am sticking them into a seperate GitHub project:

Main project:
https://github.com/Dirkster99/Edi

Control projects:
https://github.com/Dirkster99/NumericUpDownLib
https://github.com/Dirkster99/DropDownButtonLib
https://github.com/Dirkster99/MsgBox
https://github.com/Dirkster99/UnitComboLib

and I am wondering how I can best handle problems that I encounter with libraries that are referenced from one of the library projects but not from the main executable Edi project. So, far there are 2 'obvious' options that I encountered and have tried:

1 - reference all required ölibraries from the main project even if the main project does not dependent directly on them

2 - use build events to copy dependent files via COPY -f ... statement when library project has compiled succesfully

Either option seems to have drawbacks and I am almost certain that they will not work for nuget for sure. Is there a prefered way to track this dependency graph correctly via XML in MSBuild or this problem of building and sorting all required files outside of the MSBuild scope?

**Comment by rainersigwald** [comment]
For posterity: reference the packages in the library projects that need them; NuGet traverses ProjectReferences and will pull them into the executable transparently in most cases.
