### ISSUE TITLE
How can I apply a custom locale patch for dotnet cli?

### ISSUE THREAD

**Issue by yhshin217** [dotnet/msbuild#2483]
Look at issue https://github.com/Microsoft/msbuild/issues/2349, I can check that a patch for custom locale will be supported from MSBuild 15.5.
Until official release of 15.5, I need to build with this feature. So, I tried to do as below.

Firstly, I cloned the code(15.3.409.57025 version of MSBuild) in my local repository.
And, I added custom locales in ```src/Tasks/CultureInfoCache.cs```.

```
 #if !FEATURE_CULTUREINFO_GETCULTURES
         // copied from https://github.com/aspnet/Localization/blob/5e1fb16071affd15f15b9c732833f3ae2ac46e10/src/Microsoft.Framework.Globalization.CultureInfoCache/CultureInfoList.cs
         // removed the empty string from the list
         private static readonly HashSet<string> HardcodedCultureNames = new HashSet<string>(StringComparer.OrdinalIgnoreCase)
         {
             "af",
             "af-ZA",
             "am",
             "bhb-IN", // added
             "ckb-IQ", // added
```

Then, after building msbuild I overwrote ```Microsoft.Build.Tasks.Core.dll``` to my dotnet cli.
When checking the result of build, I can check above custom locales were added in resources. 
However, I have a couple of questions as below.

#### 1. File size of ```Microsoft.Build.Tasks.Core.dll```
    * dotnet cli 2.0.0 official version : 1.2MB
    * local build with Visual Studio 2017 : 1.2MB
    * local build with dotnet cli : 659KB
#### Question : ```CultureInfoCache.cs``` is a file of Build.Tasks project. If so, can I replace only ```Microsoft.Build.Tasks.Core.dll``` file based on dotnet cli 2.0.0 official version? Isn't there any unexpected compatibility issue?

Which way would be better for my case?

**Comment by yhshin217** [comment]
cc/ @lemmaa

**Comment by yhshin217** [comment]
@cdmihai Could you leave a comment?

**Comment by cdmihai** [comment]
> If I will use dotnet cli in linux, can I use this library which I built in dotnet cli of ubuntu? There is a difference in file size, though.

The dll is AnyCPU targetting netstandard1.3. Should be pretty portable. I am not quite sure what causes the difference in size though. 

> CultureInfoCache.cs is a file of Build.Tasks project. If so, can I replace only Microsoft.Build.Tasks.Core.dll file based on dotnet cli 2.0.0 official version? Isn't there any unexpected compatibility issue?

If your assembly is not signed, or its version does not match the version the other msbuild tasks depend upon, the CoreCLR might not load it and error out. You can experiment and see what works.
