### ISSUE TITLE
Restore first functionality does not clear the configuration cache

### ISSUE THREAD

**Issue by jeffkl** [dotnet/msbuild#2504]
When implementing https://github.com/Microsoft/msbuild/pull/2414, I was not able to find a way to clear the configuration cache between builds.  The result of this is that memory will not be freed between builds.  The loaded configurations will never be re-used because they contain a property that is a GUID.  When experimenting with clearing the configuration cache, MSBuild hangs after building the first project after restore.

**Comment by ladipro** [comment]
Perf triage: Closing old low-priority issues. Feel free to reopen if this has non-trivial impact despite being open for >3 years.
