### ISSUE TITLE
Projects are paying 3% of evaluation of a solution-wide design-time build importing targets they don't use

### ISSUE THREAD

**Issue by davkean** [dotnet/msbuild#2524]
See: https://github.com/dotnet/sdk/issues/1586

Note costs are slightly different than above due to a different run.

The following targets are not used by these projects yet they are paying the cost for them. While .NET Framework _can_ use these technologies, .NET Core/.NET Standard projects are paying for Xaml/Workflow and Service model targets even though they are never applicable.

Pass|File|Line #|Expression|Inc (ms)|Inc (%)|Exc (ms)|Exc (%)|#|Projects
---|---|---:|---|---:|---:|---:|---:|---:|---
Total Evaluation||||5718|100%|59|1%||
Properties (Pass 1)||||2916|51%|8|0.1%||
ItemDefinitionGroup (Pass 2)||||13|0.2%|1|0%||
Items (Pass 3)||||463|8.1%|16|0.3%||
Lazy Items (Pass 3.1)||||1902|33.3%|137|2.4%||
UsingTasks (Pass 4)||||61|1.1%|61|1.1%||
Targets (Pass 5)||||304|5.3%|163|2.9%||
Properties (Pass 1)|e:\msbuild\bin\Release\x86\Windows_NT\Output\Microsoft.NETFramework.CurrentVersion.targets|126|`<Import Project="$(MSBuildToolsPath)\Microsoft.WinFX.targets" Condition="'$(TargetFrameworkVersion)'...`|52|0.9%|3|0%|180| .NET Framework only
Properties (Pass 1)|e:\msbuild\bin\Release\x86\Windows_NT\Output\Microsoft.Common.CurrentVersion.targets|5788|`<Import Project="$(MSBuildToolsPath)\Microsoft.WorkflowBuildExtensions.targets" Condition="('$(Targe...`|46|0.8%|3|0.1%|223|  All
Properties (Pass 1)|e:\msbuild\bin\Release\x86\Windows_NT\Output\Microsoft.Common.CurrentVersion.targets|5784|`<Import Project="$(MSBuildToolsPath)\Microsoft.Xaml.targets" Condition="('$(ImportXamlTargets)' == '...`|35|0.6%|3|0%|223| All
Properties (Pass 1)|e:\msbuild\bin\Release\x86\Windows_NT\Output\Microsoft.NETFramework.CurrentVersion.targets|127|`<Import Project="$(MSBuildToolsPath)\Microsoft.Data.Entity.targets" Condition="'$(TargetFrameworkVer...`|23|0.4%|3|0%|180| .NET Framework only
Properties (Pass 1)|e:\msbuild\bin\Release\x86\Windows_NT\Output\Microsoft.CSharp.CurrentVersion.targets|332|`<Import Project="$(MSBuildToolsPath)\Microsoft.ServiceModel.targets" Condition="('$(TargetFrameworkV...`|17|0.3%|3|0%|223| All

**Comment by gulbanana** [comment]
fwiw, i've got a bunch of SDK projects which use xaml targets. happy to change them to opt in to something if it means improving perf for other projects, though

**Comment by davkean** [comment]
Yep, we would do this in a way that opts them out of .NET Core/.NET Standard.

**Comment by rokonec** [comment]
> Yep, we would do this in a way that opts them out of .NET Core/.NET Standard.
@davkean Has the above been done? Is this issue still valid?
