### ISSUE TITLE
Run custom target once per solution is very slow

### ISSUE THREAD

**Issue by shubham90** [dotnet/msbuild#2562]
We have a custom target that runs once per solution build. We achieved this by adding the target to a dummy project and made every other project dependent on dummy project. Now, in multiprocess scenario(/m) , the node that actually runs that target keeps every other project waiting until it is done with all it's work(builds other big project). So, the time taken increases a lot because of the contention in the node.

Is there any way to optimize that node since the target on which others are waiting has already completed? If not, any plans to add that feature in near future? Is there any other way possible today to achieve this in multiprocess environment?

**Comment by rainersigwald** [comment]
I know this issue is very old, but do you have a repro for the problem? The engine should be able to return the results for the dummy project quickly.
