### ISSUE TITLE
Replace short-lived string, collection, enumerator allocations with String Segment, Struct-based collection/enumerator

### ISSUE THREAD

**Issue by davkean** [dotnet/msbuild#2573]
MSBuild performs huge amount of short-lived string, collection and enumerator allocations. For large projects, this produces huge amount of memory pressure in the thousands of megabytes during evaluation. We should replace usage with smarter patterns such as a StringSegment + struct enumerator.

Using this bug to track the places that I see could benefit from this as I look through traces:

- [x] ExpressionShredder.SplitSemiColonSeparatedList and consumers of it, producing lots of string, List<string> and boxed Enumerator<string> instances. #2586
- [x] ProjectXmlElements.GetChildElements produces unneeded List<string> and a XmlChildEnumerator, just make a strongly typed enumerator (2%) - https://github.com/Microsoft/msbuild/pull/2577

**Comment by rokonec** [comment]
Closing: All reference issues are closed. If this is still valid and we shall do some further work, feel free to reopen and add repro steps.
