### ISSUE TITLE
Don't read comments when reading imports

### ISSUE THREAD

**Issue by davkean** [dotnet/msbuild#2576]
In a trace of an evaluation of a large solution from a major partner, 1% of allocations during the evaluation is spent reading comments (their GC time is 25%, so we need to reduce allocations). For project file persistence we want to make sure to roundtrip comments - but for targets do we need them? 

![image](https://user-images.githubusercontent.com/1103906/31064991-74377e1c-a78d-11e7-92d6-876347dfbb4e.png)

**Comment by davkean** [comment]
`XmlReaderSettings.IgnoreComments` controls this.

**Comment by davkean** [comment]
Interestingly enough, we already have this concept - see `_loadAsReadOnly` in `XmlDocumentWithLocation`, that avoids the XmlNode allocations but not the string allocations as above.

**Comment by davkean** [comment]
Hmm, looks like that's off by default, I'm also seeing XmlComment allocations:

![image](https://user-images.githubusercontent.com/1103906/31065522-a9712764-a791-11e7-88a6-d3e4f051b957.png)

**Comment by davkean** [comment]
@jeffkl Mentioned that we should take this even further and just turn on read-only mode across MSBuild process - we should never need read/write for that.

**Comment by tmeschter** [comment]
@davkean @jeffkl So [XMake.cs]() has this rather scary comment:

``` C#
// Indicate to the engine that it can toss extraneous file content
// when it loads microsoft.*.targets. We can't do this in the general case,
// because tasks in the build can (and occasionally do) load MSBuild format files
// with our OM and modify and save them. They'll never do this for Microsoft.*.targets, though,
// and those form the great majority of our unnecessary memory use.
Environment.SetEnvironmentVariable("MSBuildLoadMicrosoftTargetsReadOnly", "true");
```

If build tasks are loading and modifying MSBuild files during the build, doesn't that preclude us from using "read-only" mode in the general case? Hopefully I'm missing something here.

Even if it does we can update "read-only" mode to avoid allocating strings and nodes for XML comments and whitespace. That would at least help us in the case of loading Microsoft targets.

**Comment by davkean** [comment]
That does sound scary - maybe we can just expand the Microsoft.* targets check to include typically read-only locations; packages + program files, etc.

**Comment by davkean** [comment]
We should also factor in shared projects - I'm sure we open those targets as read/write.

**Comment by davkean** [comment]
Perhaps this bug can be split in 2; 

- apply the existing logic to the XML reading not just DOM
- extend the existing logic to apply to more situations

**Comment by rainersigwald** [comment]
Reactivating as #4213  will reintroduce this, because #3584 caused a behavior break (#4210).
