### ISSUE TITLE
LazyOperation.Apply can allocate 5% to 9% opening a solution

### ISSUE THREAD

**Issue by davkean** [dotnet/msbuild#2599]
Large solution containing a mix of .NET Framework/.NET Standard projects:
![image](https://user-images.githubusercontent.com/1103906/31270331-b3fea22e-aacf-11e7-815c-7f339ea3a1ff.png)

Huge solution from a major partner containing .NET Framework projects:
![image](https://user-images.githubusercontent.com/1103906/31270314-a0c2c0d2-aacf-11e7-92a3-e2da77a4108b.png)

**Comment by rokonec** [comment]
Closed: This seems has been addressed in referenced PRs.
