### ISSUE TITLE
ProduceReferenceAssembly with embedded resource

### ISSUE THREAD

**Issue by iskiselev** [dotnet/msbuild#2646]
Currently CSC task always called if project is compiled for projects that contains Embedded resources.
Output:
```
Target "CoreCompile" in file "C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin\Roslyn\Microsoft.CSharp.Core.targets":
  Building target "CoreCompile" completely.
  Input file "obj\Debug\net20\ConsoleApp2.Resource1.resources" is newer than output file "obj\Debug\net20\ConsoleApp2.exe".
```
It happens because GenerateResource task is called unconditionally, so even if API of referenced project has not been updated, CSC will still be called for all projects that contain embedded resources.

**Comment by jonathanpeppers** [comment]
For us, we looked into using `$(ProduceReferenceAssembly)` for Xamarin.Forms projects:
- User edits XAML in a NetStandard Xamarin.Forms project: an `EmbeddedResource`
- We *thought* the reference assembly would not change in this case--but it does.
- If the reference assembly didn't change, we could skip parts of the Xamarin.Android build. This would improve our incremental build times for Xamarin.Forms applications.

Any ideas on how to improve this behavior?

**Comment by rainersigwald** [comment]
@jaredpar @jcouv Is it expected that reference assemblies contain resources?

**Comment by jcouv** [comment]
Let me start with @iskiselev's scenario:

I don't know much about the `GenerateResource` task, but if it produces an updated output, then `CoreCompile` has no choice but to run.
From what I can tell from the [documentation](https://docs.microsoft.com/en-us/visualstudio/msbuild/generateresource-task?view=vs-2017), `GenerateResource` has logic to skip work when it should:

> Because .resx files may contain links to other resource files, it is not sufficient to simply compare .resx and .resources file timestamps to see if the outputs are up-to-date. Instead, the GenerateResource task follows the links in the .resx files and checks the timestamps of the linked files as well. 

The question is why is `GenerateResource` producing an updated output in your case? Did one of its inputs (or linked inputs) get updated? Or does it have a bug?

@rainersigwald Do you know who might be more knowledgeable about `GenerateResource`?

**Comment by rainersigwald** [comment]
It's me :) I agree with that assessment; having a repro might be nice.

I'd like your input on @jonathanpeppers scenario as well; I would also have assumed that changing the content of an embedded resource wouldn't result in an updated ref assembly.

**Comment by jcouv** [comment]
Regarding @jonathanpeppers's scenario:
I checked with Neal and our recollection is that when producing both a main assembly and a ref assembly, resources should only get embedded into the main assembly.
This means that when you update a resource file, we should produce an updated main assembly and an _identical_ ref assembly.
I will double check that behavior (ie. find a test that covers it).

**Comment by rainersigwald** [comment]
Closing since there was no repro of the always-generating-new-resources problem.

**Comment by jonathanpeppers** [comment]
I think this has been fixed for a while. Sometime in Dev16, I think.
