### ISSUE TITLE
Allow exclude filters on Import tag when globbing

### ISSUE THREAD

**Issue by bradphelan** [dotnet/msbuild#2651]
https://stackoverflow.com/questions/46786132/how-to-exclude-projects-from-import-when-using-wildcard-with-msbuild-import

I have a top level msbuildproj ``foo.csproj``. In this project I have the line

    <Import "**\*.props"/>

However this includes the ``bin`` directory which is at the same level as the project file. I have tried

    <Import Project="**\*.props" Exclude="obj;bin" />
    <Import Project="**\*.targets" Exclude="obj;bin" />

Is there a way to solve this

but I get

[![enter image description here][1]][1]

  [1]: https://i.stack.imgur.com/nM57E.png

**Comment by rainersigwald** [comment]
This is a reasonable idea but it looks like there isn't much demand for it, so I don't think we're going to get to it.
