### ISSUE TITLE
Microsoft.Build 15.3, 15.5 uses System.IO.Compression assembly instead of GAC

### ISSUE THREAD

**Issue by yaakov-h** [dotnet/msbuild#2681]
Microsoft.Build 15.3 (NuGet) and 15.5 (Preview, within Visual Studio's installation) both have references to:

> `System.IO.Compression, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b77a5c561934e089`

When using MSBuild in a .NET Framework project (or bunch of projects) that also uses System.IO.Compression, this causes assembly conflicts - i.e. strange build warnings and errors just by updating MSBuild to a newer release.

The version of System.IO.Compression that ships with .NET Framework is:

> `System.IO.Compression, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089`

Can we please change Microsoft.Build to use the GAC/Framework version when built for `net46`?

FWIW, Microsoft.Build 15.1 did not reference System.IO.Compression at all.

**Comment by rainersigwald** [comment]
The current solution to this is to use MSBuildLocator to find MSBuild + its references.
