### ISSUE TITLE
ExpandExpressionCaptureIntoStringBuilder is spending ~4.8 of allocations resizing the string builder

### ISSUE THREAD

**Issue by davkean** [dotnet/msbuild#2696]
This is in a large mixed solution with collection of .NET Core and ASP.NET Core projects. Looking into this, we're resizing the underlying StringBuilder because it's default size isn't large enough when expanding an expression like `@(Compile)` (not `@(Compile, '|')` because there's not a lot of those).

We should change this method to figure out the up-front cost before allocating the stringbuilder:
![image](https://user-images.githubusercontent.com/1103906/32363182-1749664a-c0c2-11e7-9748-b3cf8ee6534d.png)

**Comment by danmosemsft** [comment]
In the case of expanding `@(Compile)` it would be easy to start with # of entries in the item list multiplied by some factor like 10. Seems pretty unlikely to be over estimate.

**Comment by ladipro** [comment]
This was optimized by using `SpanBasedStringBuilder` instead of `ReuseableStringBuilder` in #6128.
