### ISSUE TITLE
ResolveAssemblyReference spends 2.3% of its time in LogReference, even on silent verbosities

### ISSUE THREAD

**Issue by cdmihai** [dotnet/msbuild#2700]
Measured this while building Roslyn with `/clp:PerformanceSummary;Summary /v:m`

![image](https://user-images.githubusercontent.com/2255729/32389056-ce4766f8-c086-11e7-8770-f3a0de0afcc5.png)

It would be nice if RAR had access to the highest verbosity requested by any logger, and skip this on low verbosities.

**Comment by cdmihai** [comment]
There's a flag to turn of LogReference, probably used for design time builds: https://github.com/Microsoft/msbuild/blob/75e5117ab8be40faad4601904600aceae6bf9ee1/src/Tasks/Microsoft.Common.CurrentVersion.targets#L2026-L2027

However, #2417 suggests that there may be a bug somewhere and `BuildingProject` gets to be true during CPS based design time builds

**Comment by rokonec** [comment]
PR #5924
