### ISSUE TITLE
Need clearer documentation on how to build msbuild for Mono

### ISSUE THREAD

**Issue by benmishkanian** [dotnet/msbuild#2718]
I have been trying to compile msbuild v15 targeting Mono for a couple days now and I could use some help. I am compiling on CentOS 7 and after struggling with various issues I have finally gotten `./cibuild.sh --target Mono` to complete (seemingly) successfully. But now I am stuck. The documentation is not clear what the output of this script is supposed to be. I am currently working on the assumption that it creates `bin/Debug-MONO/AnyCPU/Unix/Unix_Deployment/` but it's not clear what I should do with the contents of this directory. The msbuild.sh in there always fails with error `msbuild.sh: line 4: /scratch/bmishkania/msbuild-15.4.8.50001/bin/Debug-MONO/AnyCPU/Unix/Unix_Deployment/dotnetcli/dotnet: No such file or directory`. I also tried using the MSBuild.dll there as follows: `mono MSBuild.dll` and when trying to build my project it failed with error `The "*.tasks" files could not be successfully loaded from their expected location`.

Can someone please tell me what I am doing wrong here?

**Comment by radical** [comment]
@benmishkanian https://github.com/Microsoft/msbuild/wiki/Building-Testing-and-Debugging-on-Mono-MSBuild

**Comment by benmishkanian** [comment]
I am trying to compile on branch mono-2017-10 as directed by that document. `make` gave me this error:

```
  Restoring build tools...
  log  : Restoring packages for /scratch/bmishkania/msbuild-git/src/.nuget/project.json...
  log  : Lock file has not changed. Skipping lock file write. Path: /scratch/bmishkania/msbuild-git/src/.nuget/project.lock.json
  log  : Generating MSBuild file /scratch/bmishkania/msbuild-git/src/.nuget/.nuget.nuget.targets.
  log  : Generating MSBuild file /scratch/bmishkania/msbuild-git/src/.nuget/.nuget.nuget.props.
  log  : Restore completed in 284ms for /scratch/bmishkania/msbuild-git/src/.nuget/project.json.
  find: paths must precede expression: /!
  Usage: find [-H] [-L] [-P] [-Olevel] [-D help|tree|search|stat|rates|opt|exec] [path...] [expression]
  Building Project(s): build/dirs.proj : Configuration=Release-MONO, Platform=AnyCPU
  Building Project(s): src/dirs.proj : Configuration=Release-MONO, Platform=AnyCPU
  Building Project(s): Samples/dirs.proj : Configuration=Release-MONO, Platform=AnyCPU
  Building Project(s): mono/tasks/build.csproj : Configuration=Release-MONO, Platform=AnyCPU
  Microsoft.Build.Framework -> /scratch/bmishkania/msbuild-git/bin/Release-MONO/AnyCPU/Unix/Output/Microsoft.Build.Framework.dll
/scratch/bmishkania/msbuild-git/targets/DeployDependencies.proj(133,5): error : Your project.json doesn't list 'centos-x64' as a targeted runtime. You should add '"centos-x64": { }' inside your "runtimes" section in your project.json, and then re-run NuGet restore.
/scratch/bmishkania/msbuild-git/targets/DeployDependencies.proj(133,5): error : Your project.json doesn't list 'centos-x64' as a targeted runtime. You should add '"centos-x64": { }' inside your "runtimes" section in your project.json, and then re-run NuGet restore.
/scratch/bmishkania/msbuild-git/targets/DeployDependencies.proj(133,5): error : Your project.json doesn't list 'centos-x64' as a targeted runtime. You should add '"centos-x64": { }' inside your "runtimes" section in your project.json, and then re-run NuGet restore.
/scratch/bmishkania/msbuild-git/targets/DeployDependencies.proj(133,5): error : Your project.json doesn't list 'centos-x64' as a targeted runtime. You should add '"centos-x64": { }' inside your "runtimes" section in your project.json, and then re-run NuGet restore.
```
I don't see a project.json, so I'm not sure how to fix this. Also, it seems like it failed to run `find`?

**Comment by mletterle** [comment]
The documentation on building is in sore need of updating, especially wrt the current state of master.

And there is NO documentation on how to iterate during development, it took me a while to stumble on the fact that running from the `Debug/bootstrap` directory is the ideal place. As it was I had to replace the copy of Roslyn in that directory with the one from my local sdk install.

Admittedly, I'm attempting to use preview builds of dotnet-core 2.1, but still, the documentation as it stands today was no help whatsoever. 

Would be nice if the wiki had a repo of it's own for PRs...

**Comment by radical** [comment]
`master` needs a fix to support mono, which is WIP and I should have a PR for that shortly. I will update the wiki accordingly.
For use with mono though, using mono's fork might be more useful. See instructions here - https://github.com/Microsoft/msbuild/wiki/Building-Testing-and-Debugging-on-Mono-MSBuild .
