### ISSUE TITLE
ResolveProjectReferences performance has high variance on certain number of cores

### ISSUE THREAD

**Issue by mikeharder** [dotnet/msbuild#2735]
# Repro Steps
1. VM with clean Win10
2. Install .NET Core CLI 2.0.2
3. `git clone https://github.com/mikeharder/dotnet-cli-perf`
4. `git checkout 8d7493b`
5. `cd dotnet-cli-perf\scenarios\classlib\core`
6. `for /l %i in (1,1,10)   do dotnet build /clp:performancesummary | findstr /i resolveprojectreferences`

# Results
Cores|Iter 1|Iter 2|Iter 3|Iter 4|Iter 5|Iter 6 |Iter 7|Iter 8|Iter 9|Iter 10|AVERAGE|STDEV.S
-----|-----|-----|-----|-----|-----|-----|-----|-----|-----|-----|-----|-----
1|4|4|4|4|4|4|4|4|4|6|4.2|0.6
2|983|950|2,005|954|2,007|966|966|23|24|947|982.5|661.5
3|2,014|1,006|1,997|14|989|1,000|1,617|992|961|1,015|1,160.5|588.7
4|15|576|13|630|606|13|613|586|13|605|367|304.6
5|11|648|623|640|673|653|40|641|630|648|520.7|261.4
6|13|14|14|15|14|13|15|13|16|14|14.1|1.0
8|14|15|13|14|15|13|14|15|15|13|14.1|0.9

# Conclusions
For this particular solution (with 2 projects), the performance of ResolveProjectReferences (and the performance of the overall build) is highly variable on 2-5 cores.  It's consistent on 1 core, or >= 6 cores.

**Comment by AndyGerlicher** [comment]
Does this repro with full framework MSBuild? Or just on Core?

**Comment by mikeharder** [comment]
I don't know, but I can test it tomorrow.  Will need to test with and without node reuse for full framework.

**Comment by mikeharder** [comment]
It doesn't repro quite the same with framework msbuild.  If `/m` and `/nr` are both enabled, ResolveProjectReferences is much slower, but it doesn't have the variance like core msbuild.  Numbers below are from a 4-core Hyper-V VM with .NET Core 2.0.2 and MSBuild.exe 15.4.8.50001.

MsBuild|/m|/nr|Iter 1|Iter 2|Iter 3|Iter 4|Iter 5|Iter 6|Iter 7|Iter 8|Iter 9|Iter 10|AVERAGE|STDEV.S
-----|-----|-----|-----|-----|-----|-----|-----|-----|-----|-----|-----|-----|-----|-----
Desktop|false|false|16|16|16|31|31|16|16|31|16|16|20.5|7.245688373
Desktop|false|true|16|16|16|31|31|31|16|16|31|31|23.5|7.90569415
Desktop|true|false|31|31|31|47|68|47|47|47|31|31|41.1|12.35088841
Desktop|true|true|594|797|609|672|656|719|719|609|688|750|681.3|66.49653291
Core|N/A|N/A|976|856|24|878|925|938|944|15|25|962|654.3|438.2523499

**Comment by rokonec** [comment]
The system has undergone many changes since this issue was created.  Please reopen if it remains relevant.
