### ISSUE TITLE
Project Evaluation Performance is significantly slower when using "/m /nr:false" or Core MSBuild

### ISSUE THREAD

**Issue by mikeharder** [dotnet/msbuild#2755]
May be related to https://github.com/Microsoft/msbuild/issues/2735.

# Repro Steps
1. VM with clean Win10
2. Install .NET Core CLI 2.0.2 and Visual Studio Build Tools 2017 (with .NET Core Workload)
3. `git clone https://github.com/mikeharder/dotnet-cli-perf`
4. `git checkout 8d7493b`
5. `cd dotnet-cli-perf\scenarios\classlib\core`
6. `dotnet restore`
7. `msbuild /v:minimal /t:build /clp:performancesummary` and `dotnet build --no-restore /v:minimal /clp:performancesummary`

# Results
MsBuild|/m|/nr|Project Evaluation (ms)|Total (ms)
-----|-----|-----|-----|-----
Desktop|false|false|274|3,282
Desktop|false|true|263|3,333
Desktop|true|false|640|4,439
Desktop|true|true|262|3,086
Core|false|N/A|187|2,993
Core|true|N/A|373|3,537

**Comment by AndyGerlicher** [comment]
Just as a small note you can call `dotnet build /m:1` to turn off /m to get comparable results for Core. Just can't do /nr.

**Comment by mikeharder** [comment]
Updated table above with `dotnet build /m:1`.  I will also collect the total build times, to see if the increase in eval contributes to total time.  I suspect the root cause may be JIT time.  When `/m` is enabled but `/nr` is not, eval will be blocked during JIT in the new node.  If `/m` is disabled or if `/nr` is enabled, the JIT cost is only paid once (or never).

**Comment by mikeharder** [comment]
Added total time to the table above.  The increase in total time exceeds the increase in project evaluation, but they are correlated.

**Comment by rokonec** [comment]
The system has undergone many changes since this issue was created.  Please reopen if it remains relevant.
