### ISSUE TITLE
Consider using compiled regexes in globbing code

### ISSUE THREAD

**Issue by cdmihai** [dotnet/msbuild#2817]
Need experimentation to find how bad regex matching is during globbing and, whether to always have this on, or when, in the middle of globbing, to switch to compiled regexes.

**Comment by ladipro** [comment]
When running on .NET Core, the break-even point for the typical regex we use in globbing is ~8000 matches. In other words, it's better to compile the regex if we know we're going to use it at least 8000 times.

When running on .NET Framework, there is no such breaking point as matching against the compiled regex is actually ~30% slower (!!!).

I've used this regex for the test:
```
^(?<FIXEDDIR>)(?<WILDCARDDIR>((.*/)|(.*\\)|())\.[^/\\]*((/)|(\\)|(/.*/)|(/.*\\)|(\\.*\\)|(\\.*/)))(?<FILENAME>[^/\\]*)$
```

and matched it against strings like:
```
some_directory\some_file.txt
```

**Comment by cdmihai** [comment]
So it looks like it's not worth it right? We don't really know how many users experience more than 8000 matches, and the machinery to make it adaptive would make the code more complex for dubious benefits.
It would be awesome on the other hand if the Regex APIs had some ETW events to help us measure how many times a specific pattern is matched during a build and pipe into the VS / dotnet telemetry.

Feel free to close the issue if you agree.

**Comment by drewnoakes** [comment]
If `Regex` is appearing in traces, it may be worth trying different versions of the regular expression pattern, as each pattern will have different performance characteristics. Alternatively, write the algorithm by hand so that it's AOT compiled.

**Comment by ladipro** [comment]
As a small and impactful fix I am planning to actually stop compiling this kind of Regexes in the FX build of MSBuild, saving both memory and time.

https://github.com/dotnet/msbuild/blob/f0eebf2872d76ab0cd43fdc4153ba636232b222f/src/Build/Globbing/MSBuildGlob.cs#L218

I agree that making it adaptive on Core is not worth the complexity. And also agree with Drew that there's a better way if regex matching is still showing in traces.

**Comment by pakrym** [comment]
Regex matching definitely shows up on traces.

The following screenshot is collected by running 
```
dotnet restore eng/service.proj
```
in https://github.com/Azure/azure-sdk-for-net/


![image](https://user-images.githubusercontent.com/1697911/143285603-f09dc3e5-f54d-4499-b5fd-d3cc82f952fe.png)
