### ISSUE TITLE
The "GetDotNetHost" task could not be loaded from the assembly 

### ISSUE THREAD

**Issue by themust0** [dotnet/msbuild#2921]
the below issue appear when runing  docker-compose -f docker-compose.ci.build.yml -f docker-compose.yml -p Flowon run --rm -T ci-build  in cmd 

/root/.nuget/packages/microsoft.aspnetcore.mvc.razor.viewcompilation/2.0.2/build/netstandard2.0/Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.targets(45,5): 
error MSB4062: The "GetDotNetHost" task could not be loaded from the assembly 
/root/.nuget/packages/microsoft.aspnetcore.mvc.razor.viewcompilation/2.0.2/build/netstandard2.0/Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.Tasks.dll. 
Assembly with same name is already loaded Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available,
 and that the task contains a public class that implements Microsoft.Build.Framework.ITask.

**Comment by rainersigwald** [comment]
Do some of your projects reference different versions of `microsoft.aspnetcore.mvc.razor.viewcompilation`? Can you point them all to the same version?

**Comment by themust0** [comment]
I did, but same  issue appear.
I tried to create another MVC project this issue doesn't appear.

**Comment by mahpah** [comment]
I've faced this issue today, it's never happen before with the same code base. I've tried to walk around by adding this line to the csproj file and it built successfully. Don't ask me why, I don't know. 
 
```
<MvcRazorCompileOnPublish>false</MvcRazorCompileOnPublish>
```

**Comment by joeryw** [comment]
Hi,

Same problem here from yesterday in our CI builds. I Found this post, and apparently, this fixed it (post mahpah).

But strange that this is since yesterday. Nothing relevant changed in the code. Maybe something changed on the build servers of VSTS?

What is de root cause of this?

**Comment by JoelGallagher** [comment]
@mahpah Thanks for the MvcRazorCompileOnPublish tip, resolved my build issue
