### ISSUE TITLE
Add option for "warning as errors except ..."

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/msbuild#3062]
Follow up to https://github.com/Microsoft/msbuild/issues/68

I would like to have the ability to make all warnings by errors, but with some exclusions.
```
msbuild.exe -warnAsError -warnNotAsError MSB3277
```

This is not the same as `-nowarn` which would make the warning a low-importance message and hide the warning. I still want the warnings to appear as warnings so show the user there may be a problem, but I want to be able to specify which problems are non-fatal.

**My scenario:**
We would like to enable `-warnAsError` by default in the build system that produces ASP.NET Core, but we can't because there are a handful of warning that we can't always do anything about. We would like the warnings to appear, but to be non-fatal to a build passing.

For comparison, C# supports a  `WarningsNotAsErrors` properties which allows users to set `TreatWarningsAsErrors=true` which exclusions defined as `WarningsNotAsErrors`.

**Comment by kasper3** [comment]
Just sent a PR for inclusion in F# project system request as well Microsoft/visualfsharp#3395 😄

**Comment by MarkKharitonov** [comment]
I need that too.

**Comment by rainersigwald** [comment]
@MarkKharitonov That is already the case. This is a request to make some warnings produced as warnings _even when `-warnAsError` is set_.

```sh-session
$ type warnaserror.proj
<Project>
 <Target Name="Warn">
  <Warning Code="Code1" Text="Warning 1" />
  <Warning Code="Code2" Text="Warning 2" />
 </Target>
</Project>

$ msbuild warnaserror.proj -warnAsError
Microsoft (R) Build Engine version 15.9.20+g88f5fadfbe for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 11/19/2018 10:02:37 AM.
Project "s:\warnaserror.proj" on node 1 (default targets).
s:\warnaserror.proj(3,3): error Code1: Warning 1
s:\warnaserror.proj(4,3): error Code2: Warning 2
Done Building Project "s:\warnaserror.proj" (default targets).


Build FAILED.

"s:\warnaserror.proj" (default target) (1) ->
(Warn target) ->
  s:\warnaserror.proj(3,3): error Code1: Warning 1


"s:\warnaserror.proj" (default target) (1) ->
  s:\warnaserror.proj(4,3): error Code2: Warning 2

    0 Warning(s)
    2 Error(s)

Time Elapsed 00:00:00.10

$ msbuild warnaserror.proj -warnAsError -nowarn:Code1
Microsoft (R) Build Engine version 15.9.20+g88f5fadfbe for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 11/19/2018 10:02:47 AM.
Project "s:\warnaserror.proj" on node 1 (default targets).
s:\warnaserror.proj(4,3): error Code2: Warning 2
Done Building Project "s:\warnaserror.proj" (default targets).


Build FAILED.

"s:\warnaserror.proj" (default target) (1) ->
(Warn target) ->
  s:\warnaserror.proj(4,3): error Code2: Warning 2

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.12

$ msbuild warnaserror.proj -warnAsError -nowarn:Code1 -verbosity:detailed
Microsoft (R) Build Engine version 15.9.20+g88f5fadfbe for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 11/19/2018 10:03:03 AM.
Project "s:\warnaserror.proj" on node 1 (default targets).
Building with tools version "15.0".
Target "Warn" in project "s:\warnaserror.proj" (entry point):
Using "Warning" task from assembly "Microsoft.Build.Tasks.Core, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5
f7f11d50a3a".
Task "Warning"
s:\warnaserror.proj(3,3): message Code1: Warning 1
Done executing task "Warning".
Task "Warning"
s:\warnaserror.proj(4,3): error Code2: Warning 2
Done executing task "Warning".
Done building target "Warn" in project "warnaserror.proj".
Done Building Project "s:\warnaserror.proj" (default targets).


Build FAILED.

"s:\warnaserror.proj" (default target) (1) ->
(Warn target) ->
  s:\warnaserror.proj(4,3): error Code2: Warning 2

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.18
```

**Comment by MarkKharitonov** [comment]
Excellent, then we do not have a problem. So, I can pass **/err /nowarn:MSB3026** to treat all the warnings as errors except for MSB3026

**Comment by sandyarmstrong** [comment]
This would be very useful, so that build output still shows the warnings, but simply doesn't treat them as errors.

**Comment by BenVillalobos** [comment]
Is there still demand for a feature like this despite the workaround @rainersigwald suggested further up in this thread? `msbuild warnaserror.proj -warnAsError -nowarn:Code1`

**Comment by BenVillalobos** [comment]
Linking some relevant pull requests:

https://github.com/dotnet/msbuild/pull/6174

https://github.com/dotnet/msbuild/pull/6308

https://github.com/dotnet/msbuild/pull/5774

**Comment by leshy84** [comment]
We also bumped into the problem today in C# projects:
```
<PropertyGroup>
  <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  <WarningsNotAsErrors>NU1701</WarningsNotAsErrors>
</PropertyGroup>
```

We expected the warning to be displayed as warning, but it's displayed as error.
So had to replace WarningsNotAsErrors with NoWarn property to hide the warning completely.

**Comment by rseanhall** [comment]
Yes, I would still like this feature. So would the people commenting on https://github.com/dotnet/msbuild/issues/5053.

**Comment by BenVillalobos** [comment]
Will make sure we at least discuss this during our next planning meeting.

**Comment by rseanhall** [comment]
Thanks!

**Comment by baronfel** [comment]
Added the Documentation label to signal that we need a Docs addition for this feature.

**Comment by Forgind** [comment]
https://github.com/MicrosoftDocs/visualstudio-docs/pull/7585
https://github.com/MicrosoftDocs/visualstudio-docs/pull/7586
