### ISSUE TITLE
Consider expanding load-read-only heuristic to SDKs & NuGet packages

### ISSUE THREAD

**Issue by rainersigwald** [dotnet/msbuild#3134]
When loading an imported file, MSBuild has a heuristic to determine if the file can be loaded in a faster, more compact fashion:

https://github.com/Microsoft/msbuild/blob/d83a9eda20970d2bfa3ad96d47cbecf93343256b/src/Build/ElementLocation/XmlDocumentWithLocation.cs#L378-L400

This was designed during The Old Times; target files come from many other places now that might be reasonably assumed to be read-only. But it's not _necessarily_ true that things that come from NuGet packages are immutable, so I'm not entirely sure how to manage the risk of this.

(noticed when reviewing #3115)

**Comment by rokonec** [comment]
@rainersigwald Do you think this is still something we shall focus on in reasonable time ro shall we rather close this issue?

**Comment by rainersigwald** [comment]
Let's close for now; if it comes up in profiling I think opting into this behavior for SDK files should be pretty easy.
