### ISSUE TITLE
[Unix] MSBuild should escape/sanitize environment variables when logging them

### ISSUE THREAD

**Issue by grendello** [dotnet/msbuild#3233]
### Steps to reproduce

When running msbuild in a Unix terminal emulator with environment containing variables whose values contain ANSI color escapes, colors of the diagnostic
output are ruined because msbuild outputs the variables and their values verbatim to stdout. I have a number of variables in the environment which contain
such escapes, but it appears that this is the minimal set which triggers the behavior:

```
CLUTTER_IM_MODULE=xim
GIT_PROMPT_FETCH_REMOTE_STATUS=0
LD_LIBRARY_PATH=/home/grendel/devel/mono/mono-master/lib:
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:
LESSCLOSE=/usr/bin/lesspipe %s %s
ANDROID_HOST_PLATFORM=linux-x86_64
HISTCONTROL=ignoreboth
LESS=-R
COLORTERM=truecolor
XDG_VTNR=2
LESS_TERMCAP_so=
LESS_TERMCAP_se=
MANPAGER=less -s -M +Gg
LESS_TERMCAP_mb=
LESS_TERMCAP_md=
LESS_TERMCAP_me=
LESS_TERMCAP_mh=
LESS_TERMCAP_mr=
TERM=xterm-256color
VTE_VERSION=5201
SHELL=/bin/bash
SHLVL=1
LESS_TERMCAP_ue=
LESS_TERMCAP_us=
LESS_TERMCAP_ZW=
LESS_TERMCAP_ZV=
LESS_TERMCAP_ZO=
LESS_TERMCAP_ZN=
LESSOPEN=| /usr/bin/lesspipe %s

```

In particular, removing the following variable:

```
LESS_TERMCAP_us=$'\E[4m\E[1m\E[33m'
```

fixes `msbuild` output colors. MSBuild should escape the ANSI codes when logging to console to avoid this kind of side effect on the output. Screenshot below shows
the corrupted output (terminal is mate-terminal, based on GNOME VTE library)

![screenshot at 2018-04-25 23-21-39](https://user-images.githubusercontent.com/184788/39274314-ddf2d928-48e1-11e8-9ef1-6da20161ab03.png)

### Expected  behavior

Output colors should not be affected by contents of the environment variables.

### Actual behavior

Output colors are all replaced by underscored bright yellow color.

### Environment data
```
$ msbuild -version
Microsoft (R) Build Engine version 15.6.0.0 ( Fri Apr  6 15:55:10 UTC 2018) for Mono
Copyright (C) Microsoft Corporation. All rights reserved.
```

OS info:

Ubuntu Linux 18.04 64-bit (and earlier), also reproduced in Debian and Arch. The issue is independent on Linux distribution most probably

If applicable, version of the tool that invokes MSBuild (Visual Studio, dotnet CLI, etc):

CLI

**Comment by rainersigwald** [comment]
This seems entirely reasonable. It may also affect Windows, if we ever start setting [`ENABLE_VIRTUAL_TERMINAL_PROCESSING`](https://docs.microsoft.com/en-us/windows/console/console-virtual-terminal-sequences) there.

But I do note that `env` doesn't escape either:

![image](https://user-images.githubusercontent.com/3347530/39374392-4f6e5ee0-4a10-11e8-82d9-c566112d0b4d.png)

**Comment by rainersigwald** [comment]
Since this only affects console logging at high verbosities (don't do that, use a binlog :)) and we're not inconsistent with other tooling, I don't think we're likely to change it.
