### ISSUE TITLE
Assembly binding redirects ignored in website in sln

### ISSUE THREAD

**Issue by lt-gerjan** [dotnet/msbuild#3269]
I have a ASP.NET WebSite (so not a web application) and I am using the `msbuild` command line to build this website.
Since WebSites do not have a `csproj` file, I am forced to build the `sln` file, but thats fine. As long as its works like `csproj` :)
The problem is that I cannot get rid of the assembly binding warnings, despite that I have it configured in my `web.config`

The weird thing is: Visual Studio does not give these warnings
Another weird thing: It seems that `p:TreatWarningsAsErrors` does not work on msbuild + sln + website. On all the other projects (csproj based) this does work fine.

### Steps to reproduce

Command line
```
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\MSBuild.exe  Solution.sln /m   /v:q  /p:RestorePackages="False" /p:PreBuildEvent="" /p:PostBuildEvent="" /p:TreatWarningsAsErrors="true" /p:LangVersion="7" /p:Configuration="Release" /p:TargetFrameworkVersion="v4.6.1" /p:OutputDir="D:\Output"
```

web.config
```
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="Newtonsoft.Json" publicKeyToken="30ad4fe6b2a6aeed" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-11.0.0.0" newVersion="11.0.0.0" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
```

### Expected  behavior
No warnings

### Actual behavior
```
Solution.metaproj : warning MSB3247: Found conflicts between different versions of the same dependent assembly. In Visual Studio, double-click this warning (or select it and press Enter) to fix
the conflicts; otherwise, add the following binding redirects to the "runtime" node in the application configuration file: <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1"><dependentAssembly><assemblyIdentity name="Ne wtonsoft.Json" culture="neutral" publicKeyToken="30ad4fe6b2a6aeed" /><bindingRedirect oldVersion="0.0.0.0-11.0.0.0" newVersion="11.0.0.0" /></dependentAssembly></assemblyBinding>
```

### Environment data
`msbuild /version` output:

Microsoft (R) Build Engine version 15.6.85.37198 for .NET Framework

How can i fix these warnings? Or stated differently: how can I cause msbuild + sln + website to respect my assembly binding redirects?

**Comment by alexandrecavaco** [comment]
I also have this exact same problem.
Did anyone found a solution for this?

**Comment by alexandrecavaco** [comment]
@gerjandev I don't know if you still need this but I was able to run `msbuild` in a Web Site project and it read all assembly bindings from the `web.config` file.

What you need to do is to run the `msbuild` command inside your Web Site directory and remove the `Solution.sln` from your command, keeping all other parameters you might need.
