### ISSUE TITLE
GetReferenceAssemblyPaths should depend on _PrepareForReferenceResolution

### ISSUE THREAD

**Issue by akrieger** [dotnet/msbuild#3312]
### Steps to reproduce

We see a case where we cannot compile a single .cpp file in a native project in Visual Studio because of this missing target dependency. `_PrepareForReferenceResolution` normally unsets `TargetFrameworkMoniker` when the project is a native project. This then makes the task `GetReferenceAssemblyPaths` in the target `GetReferenceAssemblyPaths` be skipped. When compiling a single file, though, `_PrepareForReferenceResolution` is not run, but `GetReferenceAssemblyPaths` is still run, and the task fails with 

```
1>Target "GetReferenceAssemblyPaths" in file "C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets":
1>  Set Property: TargetFrameworkDirectory=
1>  Using "GetReferenceAssemblyPaths" task from assembly "Microsoft.Build.Tasks.Core, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a".
1>  Task "GetReferenceAssemblyPaths"
1>    Task Parameter:TargetFrameworkMoniker=.NETFramework,Version=v4.0
1>    Task Parameter:BypassFrameworkInstallChecks=True
1>    C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(1124,5): error MSB3644: The reference assemblies for framework ".NETFramework,Version=v4.0" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend.
```

A .NET SDK should not be required to be able to develop native applications. In this case, a workaround exists by always building the whole project at a time. However, for iteration speed when editing a common header on a resource constrained system, like a laptop, it is faster to repeatedly rebuild only the single file of interest and not every other file transitively affected by the changes.

### Expected  behavior

Compiling a single file in Visual Studio via right click -> compile should succeed.

### Actual behavior

On some systems, doing so fails due to a failure to resolve a .NET SDK.

### Environment data
`msbuild /version` output: 15.5.180.51428

OS info: Win 10

If applicable, version of the tool that invokes MSBuild (Visual Studio, dotnet CLI, etc): Visual Studio 15.5.6

**Comment by rainersigwald** [comment]
@yuehuang010, can you take a look at this? I don't know how single-file compilation from VS works.

**Comment by yuehuang010** [comment]
GetReferenceAssemblyPaths DependOnTarget $(GetReferenceAssemblyPathsDependsOn) which should contain "_PrepareForReferenceResolution".

Set in around Microsoft.CppBuild.targets :128
