### ISSUE TITLE
Investigate native IO operations during evaluation

### ISSUE THREAD

**Issue by cdmihai** [dotnet/msbuild#3404]
Once we replace all IO calls in evaluation with an interface, we need to experiment with an all native implementation and see how it compares to the managed one.

Prerequisites:
- have an IO abstraction. Will get introduced in #3396 
- propagate the abstraction everywhere in evaluation

**Comment by ladipro** [comment]
Team triage: Closing due to age and unclear relevance. Reimplementing I/O in native does not look like a promising direction, unlike switching to Microsoft.IO.Redist (#5468).
