### ISSUE TITLE
Keep track of which global properties/env variables were actually used

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/msbuild#3432]
Proposal: Every time we use an environment variable or a global property, we should mark it as used, so that we can log which variables were actually consumed during the build.

This would be very useful to determine the "closure" of the build where it depends on the environment. For example, people may inadvertently rely on the "Version" variable, and CI may set that, causing undesired side effects.

Several times now I've seen VSTS CI build breaks because the codebase assumed that Version is of a certain format, and CI was setting it to something else.

**Comment by rainersigwald** [comment]
I'm not sure I understand how the tracing would help with the problem you're describing. Can you elaborate?

**Comment by Nirmal4G** [comment]
I need this _bad_ but for a whole different reason!

**Comment by Nirmal4G** [comment]
Originally what I wanted for blacklisting sensitive variables from `.binlog` or the MSBuild itself from consuming those in a build.

**Comment by KirillOsenkov** [comment]
Yes, just include the environment variables that are actually used. 

Also eyeballing the list of consumed variables would indicate a hidden dependency on the environment. It's good to be mindful of places your build depends on implicit environment, and minimize/control those places. Good for deterministic/reproducible builds.

**Comment by cdmihai** [comment]
MSBuild reads the environment variables up front right now, and injects them as properties. We'd have to switch for a just in time fallback lookup mechanism which respects the property precedence (cmd line (aka global properties), environment, project).

This is a huge perf opportunity as well, as we could read only the env vars that are used. On the other hand, I don't remember if MSBuild guarantees an environment snapshot, in which case the perf benefit is not that large as we'd still have to read everything upfront. But at least we wouldn't convert them right away into properties.

**Comment by cdmihai** [comment]
Also, this could be a good step towards a potential strict execution mode.

**Comment by rainersigwald** [comment]
relevant snippets:

https://github.com/Microsoft/msbuild/blob/87f6fd25c6782b6bf90aefc00bf2598d99519576/src/Build/Evaluation/Evaluator.cs#L687-L695

https://github.com/Microsoft/msbuild/blob/87f6fd25c6782b6bf90aefc00bf2598d99519576/src/Build/Evaluation/Evaluator.cs#L1318-L1322

If we had scoped lookups and an Environment scope, it could potentially be shared among all projects in a build (I think; pretty sure new env isn't picked up if you set it in a project and then `<MSBuild>` another).

**Comment by maneely** [comment]
Currently investigating this.

**Comment by jeffkl** [comment]
Reopening since #4437 was reverted

**Comment by jeffkl** [comment]
I added a new feature that allows tasks to get global properties, so anything that needs to know what global properties were used should tie into that as well

https://github.com/microsoft/msbuild/pull/4939

**Comment by cdmihai** [comment]
> I added a new feature that allows tasks to get global properties, so anything that needs to know what global properties were used should tie into that as well
> 
> #4939

In hindsight, would it be better to reimplement #4939 such that the API only allows for getting a global property by name? Getting all of them makes tracking really hard.

**Comment by jeffkl** [comment]
I need all global properties, so I would have had to add an API that just returned the name of all of them and then got each one of their values.

**Comment by rainersigwald** [comment]
I hope that using the new API is so rare that it's ok to just pessimistically mark all global props as read if it's used.

**Comment by KirillOsenkov** [comment]
See also https://github.com/microsoft/msbuild/issues/5015

**Comment by baronfel** [comment]
Is this still necessary now that we separately track Environment Variables and only log those to the BinLog?

**Comment by rainersigwald** [comment]
We don't track global properties today, and they could _conceivably_ be useful--but I'm having a hard time articulating a concrete use case. I'd be ok with closing
