### ISSUE TITLE
msbuild given a folder path will ignore the pp argument

### ISSUE THREAD

**Issue by dsplaisted** [dotnet/msbuild#3462]
_From @maryamariyan on June 12, 2018 3:4_

Example:

`msbuild folder_containing_csproj\csproj_file.csproj /pp`

works as expected but:

`msbuild folder_containing_csproj\ /pp` 

doesn't pick up the `/pp` option.

_Copied from original issue: dotnet/buildtools#2064_

**Comment by dsplaisted** [comment]
_From @maririos on June 28, 2018 20:51_

@dsplaisted could you rout this to MsBuild please?

**Comment by rainersigwald** [comment]
@maryamariyan I don't repro this:

```
S:\repro\Microsoft\msbuild\issues\3462>msbuild folder_containing_csproj\ /pp
<?xml version="1.0" encoding="IBM437"?>
<!--
============================================================================================================================================
S:\repro\Microsoft\msbuild\issues\3462\folder_containing_csproj\folder_containing_csproj.csproj
============================================================================================================================================
-->
<Project DefaultTargets="Build">
...
```

I'm on internal 15.8, but I don't think we've changed anything related to this in 15.8. What version of MSBuild are you observing this with?

**Comment by BenVillalobos** [comment]
I don't repro this today with `msbuild` or `dotnet msbuild`, closing.
