### ISSUE TITLE
Emit clearer error for built-in tasks that don't work on .NET Core

### ISSUE THREAD

**Issue by rainersigwald** [dotnet/msbuild#3499]
Not all tasks in `Microsoft.Build.Tasks.Core.dll` are present in .NET Core MSBuild; some weren't ported because of API limitations at the time and some just aren't done yet.

It'd be nice if you got a clear error indicating this, rather than a mysterious one like

```
C:\Program Files\dotnet\sdk\2.1.301\Microsoft.Common.CurrentVersion.targets(2725,5): error MSB4062: The "Microsoft.Build.Tasks.ResolveComReference" task could not be loaded from the assembly Microsoft.Build.Tasks.Core, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a.  Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.
```

**Comment by rainersigwald** [comment]
This was done specifically for `ResolveComReference` in #3987. That model could be extended to all the tasks we don't build for Core.

Marking as up-for-grabs since we'd take contributions to build more stubs.

**Comment by santoshyadav198613** [comment]
Hi @rainersigwald, 

Will take this up.

**Comment by kendrahavens** [comment]
A user on an unrelated ticket mentioned using the workaround documented here: https://stackoverflow.com/questions/47062203/net-core-error-on-build-error-msb4062-microsoft-build-tasks-resolvecomreferenc.
Should we have official guidance on this?

**Comment by rainersigwald** [comment]
@kendrahavens for COM specifically? Do you have suggestions over https://docs.microsoft.com/en-us/visualstudio/msbuild/resolvecomreference-task?view=vs-2019#msb4803-error?

**Comment by jrdodds** [comment]
@rainersigwald Please assign this issue to me.

I will create stubs for the `AspNetCompiler`, `RegisterAssembly`, and `UnregisterAssembly` tasks based on how the `ResolveComReference` task was stubbed. I will check for other tasks that may need to be stubbed.

There are some supporting classes for the COM related tasks that appear to be unused in .NET Core MSBuild:
- `ResolveComReferenceCache` (referenced by `ResolveComReference`)
- `AppDomainIsolatedTaskExtension` (base class of `ResolveComReference`, `RegisterAssembly`, and `UnregisterAssembly`)
- `AppDomainIsolatedTask` (base class of `AppDomainIsolatedTaskExtension`)

Should these types be removed or stubbed out in the .NET Core MSBuild?

**Comment by jrdodds** [comment]
PR #3987 includes a change in `ref/` (specifically in `ref/Microsoft.Build.Tasks.Core/netstandard/Microsoft.Build.Tasks.Core.cs`) but `ref/` is not a part of the public dotnet/msbuild repo.

Has the `ref/` directory been replaced by dotnet/source-build-reference-packages (`src/referencePackages/src/microsoft.build.tasks.core/17.4.0/ref/netstandard2.0/Microsoft.Build.Tasks.Core.cs`)? It looks like there is an automated system for updating reference packages. How are changes made or propagated?

**Comment by rainersigwald** [comment]
> PR #3987 includes a change in `ref/` (specifically in `ref/Microsoft.Build.Tasks.Core/netstandard/Microsoft.Build.Tasks.Core.cs`) but `ref/` is not a part of the public dotnet/msbuild repo.
> 
> Has the `ref/` directory been replaced by dotnet/source-build-reference-packages (`src/referencePackages/src/microsoft.build.tasks.core/17.4.0/ref/netstandard2.0/Microsoft.Build.Tasks.Core.cs`)? It looks like there is an automated system for updating reference packages. How are changes made or propagated?

The `ref/` stuff has been replaced by .NET SDK-integrated [package validation](https://learn.microsoft.com/dotnet/fundamentals/package-validation/overview). For this specific change, the API surface should only increase (with the new-to-core types), which should not cause any errors. If you encounter errors highlight them in the PR and we can consider the best way forward (we can add exceptions if there's something that's technically breaking but reasonable to do).

**Comment by jrdodds** [comment]
The PR fails to build because base classes are different for the tasks.

**Comment by saichadu1702** [comment]
Hi guys,
COMReference in .Net 8.0 will work? if there is any other resolution please provide.
