### ISSUE TITLE
Find a way to embed project.assets.json in .binlog

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/msbuild#3529]
It would be helpful to include the `project.assets.json` file from the obj directory in the .binlog file archive. 

Not sure what's the best way to do it as it's not technically an MSBuild file.

**Comment by rainersigwald** [comment]
What scenarios aren't well-served by just looking at the results of the asset-file-reading task?

Maybe some kind of advisory API from within a task: "it'd be interesting to capture this file"?

```C#
IBuildEngine6.LogFileContents(string path)
```

(Someday we're going to get into double digits on that interface and it will be something to behold.)

We wouldn't want folks to abuse this for everything (if you need to debug contents of source files, build locally), but for build-graph-altering things like the assets file it could be handy.

**Comment by KirillOsenkov** [comment]
Here's an example where I needed the contents of project.assets.json:
https://github.com/NuGet/Home/issues/7132

**Comment by KirillOsenkov** [comment]
A naïve way to do that that works well is just add this to BinaryLogger.CollectImports():

```
                if (projectArgs.Items is IEnumerable items)
                {
                    foreach (DictionaryEntry item in items)
                    {
                        if (item.Key is string itemName && itemName == "IncludeInBinlog" && item.Value is ITaskItem taskItem)
                        {
                            projectImportsCollector.AddFile(taskItem.ItemSpec);
                        }
                    }
                }

                if (projectArgs.Properties is IEnumerable properties)
                {
                    foreach (DictionaryEntry property in properties)
                    {
                        if (property.Key is string name && name == "ProjectAssetsFile" && property.Value is string projectAssetsFile)
                        {
                            projectImportsCollector.AddFile(projectAssetsFile);
                        }
                    }
                }
```

**Comment by KirillOsenkov** [comment]
Suggestions welcome on how to name the item `IncludeInBinlog` that the binary logger will recognize as special.

Then you could just do 
```
<ItemGroup>
    <IncludeInBinlog Include="CustomFile.txt" />
</ItemGroup>
```

to embed the file in binlog.

Embedding all project.assets.json roughly doubles the size of the files archive, from 450K to 900K. Feels like it's worth it though because project.assets.json contain valuable information not available elsewhere, e.g. why was a certain file chosen to be CopyLocal.

**Comment by KirillOsenkov** [comment]
It's unclear when to embed the file. ProjectStarted or ProjectEvaluationFinished may be too early as the file may not exist yet. But I guess in the majority of cases when a project is being built the Restore already happened. 

TargetFinished for Restore target could be another location.

**Comment by KirillOsenkov** [comment]
I feel like I should first fix https://github.com/dotnet/msbuild/issues/5316 so we can better enumerate items after evaluation.
