### ISSUE TITLE
Support binary logs >2GB uncompressed

### ISSUE THREAD

**Issue by rainersigwald** [dotnet/msbuild#3534]
From an internal mail:

> It appears that StructuredLogger doesn’t support binlog whose decompressed content exceeds 2G. MemoryStream and byte[] only supports 2G even if the process has 64-bit address space.

relevant snippet:

https://github.com/Microsoft/msbuild/blob/f725b4e3e4136f8e693183e0c7b4b97453789f73/src/Build/Logging/BinaryLogger/BinaryLogReplayEventSource.cs#L31-L67

**Comment by KirillOsenkov** [comment]
I think this should be fixed by now.
