### ISSUE TITLE
Consider replacing the evaluator List<T> usage with block lists

### ISSUE THREAD

**Issue by cdmihai** [dotnet/msbuild#3582]
IEvaluatorData [implementors](https://github.com/Microsoft/msbuild/blob/68dbc04992370136a832e83f41471f8ccc97c586/src/Build/Definition/Project.cs#L3200-L3212), the [Evaluator](https://github.com/Microsoft/msbuild/blob/68dbc04992370136a832e83f41471f8ccc97c586/src/Build/Evaluation/Evaluator.cs#L107-L138) itself, and potentially other places in MSBuild use reasonably long lived instances of `List<T>` to collect data (up to tens of thousands of elements or more) which never / seldomly gets removed. Growing the `List<T>` in these cases is wasteful, and a `BlockList<T>` which links arrays together instead of throwing them away and regrowing would probably lower memory traffic.

**Comment by cdmihai** [comment]
One BlockList implementation is here: https://github.com/jamesqo/BlockList by @jamesqo

**Comment by cdmihai** [comment]
Not sure if pooling would help, as projects are usually long lived, and their element types are specialized evaluation types. But if there would be a use case where there's many short lived project objects then yes, pooling the linked arrays would help.

**Comment by ladipro** [comment]
I have replaced `List` with an instrumented version to measure the impact of resizing. The numbers are not convincing. When building a simple ASP.NET Core app, Ocelot, and Orchard Core, allocations thrown away when resizing were 0.06%, 0.3%, and 0.3% of all allocations during evaluation, respectively. I have used the instrumented data structure in all places suggested by this issue and also did a quick scan for other potential occurrences.

Even if the block list had zero overhead, we wouldn't be able to save more than 0.5% of evaluation allocations (plus some small CPU cost of moving items when resizing).

|                  | Evaluation allocations | List<T> resizing allocations |
|------------------|------------------------|------------------------------|
| ASP.NET Core app | 16,584,344             | 11,168 (0.06%)                       |
| Ocelot           | 110,587,064            | 341,888 (0.3%)                      |
| Orchard Core     | 1,978,160,400          | 6,749,600 (0.3%)                    |
