### ISSUE TITLE
Consider walking directories in up-to-date checks

### ISSUE THREAD

**Issue by rainersigwald** [dotnet/msbuild#3586]
@ccastanedaucf has observed (https://github.com/Microsoft/msbuild/pull/3547#issuecomment-410354029) significant time spent in up-to-date checks in https://github.com/Microsoft/msbuild/blob/680224d8ecf9a7da82c001d95db336fd9cfd12d8/src/Build/BackEnd/Components/RequestBuilder/TargetUpToDateChecker.cs#L937

Git for Windows got a big speedup by implementing some caching around checks for individual file timestamps (with the `core.fscache` setting). See https://github.com/git-for-windows/git/blob/master/compat/win32/fscache.c and its history.

The gist of the idea is that it's faster to enumerate all files in a directory and get every file's modification timestamp than it is to get the timestamps on an individual basis. Since there's probably a fairly high degree of overlap in the directories of files we're checking for timestamps, I suspect we could get some benefit from this technique too.

**Comment by AndyGerlicher** [comment]
@ccastanedaucf can you take a look at implementing this? Might help get Windows closer to Linux after #3547 is in.

**Comment by cdmihai** [comment]
Would be nice if you could implement it over the existing IFileSystem :)

Also, this might be a very good use case for the fast allocation free directory enumeration introduced by @JeremyKuhne  https://blogs.msdn.microsoft.com/jeremykuhne/2018/03/09/custom-directory-enumeration-in-net-core-2-1/

**Comment by 4creators** [comment]
The above problems are a huge burden in some dotnet repos see #2843

**Comment by rainersigwald** [comment]
@4creators This will probably help with that, but I'd be shocked if it was a very high percentage of the overall incremental build time in those repos.

**Comment by ccastanedaucf** [comment]
@cdmihai small bench comparing methods of getting last write time for 10 files on Windows. Right now we use the equivalent of ```File.GetLastWriteTimeUtc```.
```
                       Method |      Mean |     Error |    StdDev |
----------------------------- |----------:|----------:|----------:|
     File_GetLastWriteTimeUtc | 257.60 us | 0.7359 us | 0.5745 us |
 DirectoryInfo_EnumerateFiles |  53.60 us | 1.1738 us | 1.4416 us |
         FileSystemEnumerable |  30.44 us | 0.1749 us | 0.1550 us |
```

**Comment by JeremyKuhne** [comment]
> small bench comparing methods of getting last write time for 10 files on Windows

Allocations would be interesting to measure as well. Using DirectoryInfo requires allocating a FileSystemInfo around every result, which will also allocate strings to do so. With FileSystemEnumerable you can get zero allocations (outside of the enumerable itself).

**Comment by ccastanedaucf** [comment]
1000 files in same directory + memory allocations
```
                       Method |         Mean |       Error |      StdDev |   Gen 0 |  Gen 1 |  Gen 2 | Allocated |
----------------------------- |-------------:|------------:|------------:|--------:|-------:|-------:|----------:|
     File_GetLastWriteTimeUtc | 45,740.60 us | 666.3182 us | 590.6736 us |       - |      - |      - | 109.38 KB |
 DirectoryInfo_EnumerateFiles |  1,036.26 us |  19.6407 us |  18.3719 us | 56.6406 |      - |      - | 242.71 KB |
         FileSystemEnumerable |     31.05 us |   0.2048 us |   0.1916 us |  0.3052 | 0.1221 | 0.0305 |   1.71 KB |
```

**Comment by JeremyKuhne** [comment]
> 1000 files in same directory + memory allocations

Cool. Shows a pretty big difference. :)

I'm curious about the Allocated (1.71K) number. Is it measuring `GC.GetAllocatedBytesForCurrentThread` or `GetTotalmemory`? It is just a somewhat odd total for me to place.

**Comment by cdmihai** [comment]
Looks like it's ETW allocation events: https://github.com/dotnet/BenchmarkDotNet/blob/36bf7c4ee053134d0bfeaf5d757c12afa332f1c2/src/BenchmarkDotNet.Diagnostics.Windows/MemoryDiagnoser.cs#L74

**Comment by rainersigwald** [comment]
microsoft/msbuild#3608 is an implementation of this that should be revisited if we move forward with this bug.

**Comment by rainersigwald** [comment]
Another possible implementation to help with this: microsoft/msbuild#2848; it should also be looked at.

**Comment by mfkl** [comment]
Has there been more data to help with a design for a solution to this problem?

Looking at previous comments/PRS, native calls vs `DirectoryInfo_EnumerateFiles` vs `FileSystemEnumerable` are some of the possible options I guess.

**Comment by AR-May** [comment]
We are waiting for final measurements for PR #6974 from @rokonec. It is likely that this PR the issue with up-to-date checks would be mostly resolved and that further room for improvements would be too small.

**Comment by ladipro** [comment]
Closing, assuming that #6974 will be merged soon. Please reopen otherwise.
