### ISSUE TITLE
Delay formatting msbuild resources until they get consumed by a Stream

### ISSUE THREAD

**Issue by cdmihai** [dotnet/msbuild#3599]
Formatted msbuild resource strings eventually get sent to loggers, which eventually write them to some stream. Most StreamWriters have overloads (or will have) for formatting. Therefore it is pointless to convert formatted resources into strings, if they're final resting place is some buffer anyway.

An interesting experiment would be to put the resource and its arguments into some struct, and then propagate that struct all the way into loggers, which then can format them directly into their streams / string builders / etc.

Building WebLargeCore with minimal verbosity creates 74mb of formatted resources:

![image](https://user-images.githubusercontent.com/2255729/43931239-6c07f87a-9bf2-11e8-8263-a16630f16196.png)

And in a broader sense, we should look for cases where we strinbbuild or format strings just to then later put them in some buffer. Patterns that will help
- switch to using ReadOnlyMemory<char> instead of strings
- future corefx work will allow us to retrieve the buffers from stringbuilders
- use formatting overloads

**Comment by rokonec** [comment]
I believe most of this has been addressed by LazyFormattedBuildEventArgs. There was a bug related to minimal verbosity and improper usage of LazyFormattedBuildEventArgs - #5924

**Comment by rokonec** [comment]
Please reopen if it remains relevant.
