### ISSUE TITLE
Exception when using Microsoft.Build.Evaluation.Project on dotnet core sdk 2.1.400

### ISSUE THREAD

**Issue by MatthewLymer** [dotnet/msbuild#3740]
### Steps to reproduce
1. Open project in Visual Studio
1. Update paths in `Program.cs` to match environment
1. Run project

Working directory:
[BuildTools.zip](https://github.com/Microsoft/msbuild/files/2379481/BuildTools.zip)

Command line:  
n/a

### Expected  behavior
At least one `Passed` message

### Actual behavior
Three `Failed, ...` messages:

(without `MSBuildSDKsPath` defined)
Failed, The SDK 'Microsoft.NET.Sdk' specified could not be found.  C:\Projects\BuildTools\src\BuildTools\BuildTools.csproj

(with `MSBuildSDKsPath` defined to `C:\Program Files\dotnet\sdk\2.1.400\Sdks`)
Failed, The imported project "C:\Projects\BuildTools\src\BuildTools\bin\Debug\netcoreapp2.1\15.0\Microsoft.Common.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.  
C:\Program Files\dotnet\sdk\2.1.400\Sdks\Microsoft.NET.Sdk\Sdk\Sdk.props

### Environment data
`msbuild /version` output:
Not sure, whatever comes w/ Visual Studio 2017 Community 15.8.0

`dotnet --info` output:
.NET Core SDK (reflecting any global.json):
 Version:   2.1.400
 Commit:    8642e60a0f

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.400\

Host (useful for support):
  Version: 2.1.2
  Commit:  811c3ce6c0

.NET Core SDKs installed:
  2.1.101 [C:\Program Files\dotnet\sdk]
  2.1.104 [C:\Program Files\dotnet\sdk]
  2.1.200 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.300 [C:\Program Files\dotnet\sdk]
  2.1.400 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

OS info:
* Windows 10  
* Visual Studio 2017 Community  
* .NET Core 2.1.400 SDK

**Comment by MatthewLymer** [comment]
Is this the right place to report issues?

**Comment by baruchiro** [comment]
#3434
