### ISSUE TITLE
Issue a warning when a file is imported more than once

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/msbuild#3856]
Currently looks like MSBuild will silently import the same file more than once and in that case if nothing breaks it's because most of the things are idempotent.

**Comment by stan-sz** [comment]
Isn't this covered with [`MSB4011`](https://learn.microsoft.com/en-us/visualstudio/msbuild/errors/msb4011?view=vs-2022)?

**Comment by KirillOsenkov** [comment]
You're right, let me close this and I can reopen if I can remember what this was about, or have any more concrete details/information. Right now the bug is not actionable.
