### ISSUE TITLE
clp:ForceConsoleColor freezes wix setup build

### ISSUE THREAD

**Issue by MarioVolarevic** [dotnet/msbuild#3857]
### Steps to reproduce
Setup for our tool is built on teamcity using wix toolset with FAKE scripts for preparing the environment.
After updating FAKE in context of teamcity, Msbuild now gets this flag by default which didn't exist before: 
clp:ForceConsoleColor
And it seems that this freezes the wix build at one point.
When this flag is removed, setup is built successfully.

Additionally, when the flag is used, gibberish is shown in the console output.
It can be also reproduced if called from Command Prompt, teamcity doesn't have to be used.

This is an example of corrupted output.
```C
Build started 12.10.2018. 14:00:46.
[36;1mProject "D:\\<somefolder>\\MyBundle.sln" on node 1 (Rebuild target(s)).
[m[30;1m[36;1mValidateSolutionConfiguration:
[30;1m  Building solution configuration "Release|x64".
```

Command line
```
C:\Users\user>"C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\MSBuild.exe"  "D:\<somefolder>\MyBundle.sln" "/t:Rebuild" "/m:1" "/nodeReuse:False" "/v:n" "/clp:ForceConsoleColor" "/p:RestorePackages=False" "/p:Optimize=True" "/p:DebugSymbols=True" "/p:Configuration=Release" "/p:Platform=x64"
```
### Expected  behavior
New flags shouldn't break the build.

### Actual behavior
clp:ForceConsoleColor freezes the build and outputs broken text (check example above).
As soon as the flag is removed, build works again.

### Environment data
`msbuild /version` output:
Microsoft (R) Build Engine version 15.8.169+g1ccb72aefa for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

15.8.169.51996
OS info:
Windows 10 x64 b1709 16299.665
If applicable, version of the tool that invokes MSBuild (Visual Studio, dotnet CLI, etc):
Command Prompt

**Comment by rainersigwald** [comment]
The "broken" text is the documented behavior of that switch:

```
                        ForceConsoleColor--Use ANSI console colors even if
                            console does not support it
```

The Windows console doesn't use ANSI color codes (normally; this is changing with the latest win10 updates), so they just get passed through as gibberish.

I don't know why FAKE would opt into this mode by default. It looks like you filed that at https://github.com/fsharp/FAKE/issues/2146. It was added for UNIX-like environments that _do_ support colorization but are getting misdetected for whatever reason.

I'd also be fairly surprised if the console logging output was causing the build hang. Can you remove the `ForceConsoleColor` while keeping the updated everything else to isolate the cause there?

**Comment by MarioVolarevic** [comment]
In the original post I have added an example of command line which was taken from Teamcity build log.
As soon as I remove "/clp:ForceConsoleColor" build doesn't hang anymore.
That's why we were also surprised that this might cause incompatiblity with wix.
FAKE added this as default for Teamcity environment, otherwise it's not used. 
And colors are really displayed in TC build log, but unfortunately the build hangs.

Other types of builds, like C++ and C# projects are working without any problems.
Wix is the only problematic one. It seems that it get stuck on one of the candle steps.
On Monday I might give you more info when I get to work.
