### ISSUE TITLE
Redirect all redistributed dlls

### ISSUE THREAD

**Issue by cdmihai** [dotnet/msbuild#3896]
Redistributed dlls appear in the [swr ](https://github.com/rainersigwald/msbuild/blob/c71cbc0190e5366a91227d9fabb4cdb32e1ef58f/src/Package/MSBuild.VSSetup/files.swr#L161-L165 )and corext nuspec files.

We need to redirect them as per the comment in app.config: https://github.com/Microsoft/msbuild/blob/exp/net472/src/MSBuild/app.config#L43

**Comment by rainersigwald** [comment]
This is now enforced by #7153.
