### ISSUE TITLE
Possible unnecessary work in CompareAssemblyIdentity

### ISSUE THREAD

**Issue by rainersigwald** [dotnet/msbuild#3930]
I'm pretty sure there should be a return at the end of this block:

https://github.com/Microsoft/msbuild/blob/6fa296fcf692bf61e374d93826c30ca124c23479/src/Tasks/NativeMethods.cs#L1112-L1133

before cross-platform work, it was just the native call:

https://github.com/Microsoft/msbuild/blob/a939f1547a3f8b91512d0d2d270a8d0f0111e7e7/src/XMakeTasks/NativeMethods.cs#L976-L985

**Comment by livarcocc** [comment]
@rainersigwald any suggestions on when to tackle this? Dev16, beyond?

**Comment by rainersigwald** [comment]
I would expect it to be safe to take in a dot release, but I don't think there's any reason not to do it now (unless it unexpectedly breaks things, which would be surprising).
