### ISSUE TITLE
TargetFrameworkAttribute support in UWP/WPF

### ISSUE THREAD

**Issue by lutzroeder** [dotnet/msbuild#3941]
### Steps to reproduce
1. Create blank WPF project
2. Add `Newtonsoft.Json` NuGet reference and restore NuGet cache
3. Create blank UWP TPMinV<10.0.16299.0 project
4. Copy `<NuGetPath>\Newtonsoft.Json.11.0.2\lib\net45\Newtonsoft.Json.dll` to UWP project
5. Edit UWP .csproj to include:
```
    <Reference Include="Newtonsoft.Json.dll">
      <HintPath>Newtonsoft.Json.dll</HintPath>
    </Reference>
```
6. Reload project and build
### Expected  behavior
`Newtonsoft.Json.dll` is marked with `TargetFrameworkAttribute(".NETFramework, Version=v4.5")` and should not be a resolved reference. Applies for design-time builds and the reverse scenario (.NETCore reference in .NETFramework project) as well.
### Actual behavior
`Newtonsoft.Json.dll` is resolved and returned as a reference.

**Comment by davkean** [comment]
MSBuild already does TFM checks between versions (disallowing .NET Framework 4.6 project from referencing 4.7 library) this is an extension on this.

**Comment by rainersigwald** [comment]
> `Newtonsoft.Json.dll` is marked with `TargetFrameworkAttribute(".NETFramework, Version=v4.5")` and should not be a resolved reference.

Why? What rules need to be added to ResolveAssemblyReferences to satisfy the scenario?

**Comment by davkean** [comment]
Probably the sames rules that we apply to project-to-project rules @nguerrera @dsplaisted. Where is that logic stored?

**Comment by dsplaisted** [comment]
We've never applied TFM compatibility checks to DLL references.  Is this a request that we should now do so?  What's the motivation for this?

**Comment by davkean** [comment]
We do within the same "framework" @dsplaisted:

```
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2114,5): warning MSB3275: The primary reference "Microsoft.VisualStudio.ProjectSystem" could not be resolved because it has an indirect dependency on the assembly "Microsoft.Build.Framework, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" which was built against the ".NETFramework,Version=v4.7.2" framework. This is a higher version than the currently targeted framework ".NETFramework,Version=v4.6".
```

**Comment by dsplaisted** [comment]
We discussed this and are concerned that a change in build behavior where we no longer allow these references could break projects that depend on the fact that this is possible.

We think we could do the following:

- Add a warning when there is a DLL reference to a DLL compiled against an incompatible target framework
- Allow opting out of the warning per-reference (via metadata on the reference)
- Add telemetry to help us understand how frequently projects successfully reference DLLs from "incompatible" target frameworks
- Based on the telemetry, consider modifying the build behavior to by default not allowing the incompatible reference to be resolved
