### ISSUE TITLE
Communication between VS -> MSBuild is pushing 6% (100MB) of allocations onto the LOH

### ISSUE THREAD

**Issue by davkean** [dotnet/msbuild#3953]
We're attempting to quadruple the number of projects that the project system can open, while at same reducing solution load time. Reducing GC time is an important part of that.

In one trace where we are opening 780 projects, I'm seeing ~50 MB pushed on the large object heap (LOH) during the communication between VS and MSBuild.

It would reduce the amount of data we pushed on the LOH (and forced Gen2 collection) if we chunked this data up into arrays that were less than 85K.

GC Rollup By Generation
--
Gen | Count | MaxPause | MaxPeak MB | Max AllocMB/sec | TotalPause | TotalAlloc MB | Alloc MB/MSec GC | Survived MB/MSec GC | MeanPause | Induced
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
ALL | 426 | 741.5 | 4,106.9 | 1,112.349 | 9,601.4 | 2,118.8 | 0.2 | 0.269 | 22.5 | 7
0 | 282 | 35.3 | 2,087.1 | 1,112.349 | 3,548.3 | 1,389.3 | 1.7 | 0.029 | 12.6 | 0
1 | 138 | 63.7 | 4,106.9 | 396.323 | 2,764.4 | 709.1 | 1.3 | 0.025 | 20.0 | 1
2 | 6 | 741.5 | 2,070.8 | 10.006 | 3,288.7 | 20.3 | 1.6 | 0.369 | 548.1 | 6

![image](https://user-images.githubusercontent.com/1103906/48874311-c3820680-ee46-11e8-975c-fbf871545d96.png)

![image](https://user-images.githubusercontent.com/1103906/48874771-0d6bec00-ee49-11e8-9570-a79c1400ca3b.png)

**Comment by davkean** [comment]
Here's a trace for 520 projects (above is for 780), similar problem:

![image](https://user-images.githubusercontent.com/1103906/48929626-a29cdc80-ef3e-11e8-9017-4fe4cdaaf7f6.png)

**Comment by davkean** [comment]
Here's a trace that allocates 25% of all allocations during solution load on the LOH due to MSBuild:

![image](https://user-images.githubusercontent.com/1103906/51301053-faa91880-1a81-11e9-9c44-97e93dd312b6.png)

**Comment by rainersigwald** [comment]
@BenVillalobos can you check current relevance of this after the latest project system changes?

**Comment by danmosemsft** [comment]
Maybe the stream passed to BinaryWriter could be some custom (subclass of?) MemoryStream that allocated in sizes that are more friendly to the LOH (?)

**Comment by ladipro** [comment]
Code inspection:
- Buffers allocated in `NodeProviderOutOfProcBase` were optimized and short-lived LOH allocations eliminated in #6023.
- `InterningBinaryReader.ReadString` was optimized in #5663 (eliminated the StringBuilder), and #6556 and #6705 (implemented buffer pooling).

We should be much better off now. Let's measure.

**Comment by ladipro** [comment]
Confirmed by recording a trace opening a 1000 project solution in 17.1.0 Preview 2.0 [31915.365.main.
- ~2 MB worth of LOH `char[]` allocations coming from the `InterningBinaryReader`.
- No `byte[]` LOH allocations coming from MSBuild.

![image](https://user-images.githubusercontent.com/12206368/141999224-f77a2d88-d021-4fad-a959-b43beb01ef90.png)
