### ISSUE TITLE
InterningBinaryReader+Buffer allocates 16MB opening large solution

### ISSUE THREAD

**Issue by davkean** [dotnet/msbuild#3954]
We're attempting to quadruple the size of a solution we can load. Peak and stable memory influences this and we're reducing both heavily across the product. 

In a trace of opening a solution with 780 projects, these buffers allocate 16MB just in the VS process. This combined with other causes puts pressure on GC time, in particularly Gen0, which is entirely is responsible for 3.5 seconds of blocked time.

Gen | Count | MaxPause | MaxPeak MB | Max AllocMB/sec | TotalPause | TotalAlloc MB | Alloc MB/MSec GC | Survived MB/MSec GC | MeanPause | Induced
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
ALL | 426 | 741.5 | 4,106.9 | 1,112.349 | 9,601.4 | 2,118.8 | 0.2 | 0.269 | 22.5 | 7
0 | 282 | 35.3 | 2,087.1 | 1,112.349 | 3,548.3 | 1,389.3 | 1.7 | 0.029 | 12.6 | 0
1 | 138 | 63.7 | 4,106.9 | 396.323 | 2,764.4 | 709.1 | 1.3 | 0.025 | 20.0 | 1
2 | 6 | 741.5 | 2,070.8 | 10.006 | 3,288.7 | 20.3 | 1.6 | 0.369 | 548.1 | 6

![image](https://user-images.githubusercontent.com/1103906/48884953-92232e00-ee7a-11e8-85c4-20ce5e7b282f.png)

It looks like there already is an attempt to share these buffers somewhat, but probably needs improvement perhaps via a buffer pool.

**Comment by AR-May** [comment]
[perf triage] 
The system has undergone many changes since this issue was created.  Please reopen if it remains relevant.

**Comment by ladipro** [comment]
Reopening since we keep getting Watson reports with OOMs at this callstack and it's not hard to fix.
