### ISSUE TITLE
Add url to warning/error tasks and objects

### ISSUE THREAD

**Issue by sanderobdeijn** [dotnet/msbuild#4029]
I'm making a .props file that reads some properties in a .csproj and then sets other properties and loads some nugetpackages.
I want to add errors or warnings when the properties are empty. So I added a warning tag that looks for a empty property.

Also I would like to add a link to a support page in visual studio. Can an url be added to this attribute.

The 1 code becomes an url in visualstudio but now points to a MDN page.
If I add a HelpKeyword attribute with an url the link in visual studio changes but not to the value of the help keyword.

How does this tag work? Can I set this tag to a specific url in visual studio?

Here is my code:
```xml
<Project InitialTargets="ValidateProjectParameters">
    <Target Name="ValidateProjectParameters">
        <Warning Text="The property TestProperty is empty in the projectfile"
                 Condition="'$(TestProperty)' == ''"
                 Code="1"
                 HelpKeyword="http://google.com">
    </Target>
</Project>
```

**Comment by livarcocc** [comment]
This might be a better question to dotnet/project-system. I am not sure how VS leverages warnings coming from msbuild.

@davkean any idea?

**Comment by sanderobdeijn** [comment]
In #3858 I was asked to open a separate issue.
What is the helpkeyword used for? If I do an dotnet build it also isn't returned in the output

**Comment by jmezach** [comment]
This would be a really useful feature to have in order to document your own set of context specific warnings. Any plans to add this?

**Comment by davkean** [comment]
I don't believe this is scheduled, but I'm sure that MSBuild will welcome the contribution. After that I can schedule some time on the VS side to make sure this all plumbed through.

**Comment by davkean** [comment]
This has been merged in: https://github.com/dotnet/msbuild/pull/5488.
