### ISSUE TITLE
ExpandPropertiesLeaveTypedAndEscaped (incorrectly) makes the assumption that it's ReuseableStringBuilder won't be resized

### ISSUE THREAD

**Issue by davkean** [dotnet/msbuild#4084]
Opening a large 1000 project solution based on a solution with http://github.com/dotnet/project-system's project duplicated many times, I can see that 8.4% of all allocations during solution load (before we OOM) is ExpandPropertiesLeaveTypedAndEscaped expanding its ReuseableStringBuilder:

![image](https://user-images.githubusercontent.com/1103906/51368924-7fa93600-1b45-11e9-8832-79833c93bca2.png)

This seems to indicate that this is not required:

``` C#
                    // This method is called very often - of the order of 3,000 times per project.
                    // With the reuseable string builder, there's no particular need to initialize the length as it will already have grown.
                    using (var result = new ReuseableStringBuilder())
```

I suspect we're not caching the builder because it's grown too big so the comment will be incorrect. We should set a sensible initial size based on what we're going to put inside it.

**Comment by ladipro** [comment]
This was optimized by using `SpanBasedConcatenator` instead of `ReuseableStringBuilder` in #6128.
