### ISSUE TITLE
Reduce memory usage of ItemDictionary especially in immutable ProjectInstance

### ISSUE THREAD

**Issue by lifengl** [dotnet/msbuild#4197]
This data structure is designed to make Remove/Replace O(1), which made it very inefficient when it is used in an immutable ProjectInstance, also those operations do happen often in the normal project evaluation results.

Suggestion:
  1, to create the second dictionary ProjectItem->LinkedNode, only lazily when we need it.  In the majority case, this will not be created.  It doesn't cost more time to create the dictionary at that time than keeping it at the beginning.

2, consider using a different implementation in the immutable scenario.  Because the LinkedListNode uses extra memory (link points, additional 8 bytes per CLR object), using List<> will be much efficient in the immutable scenario.

**Comment by AR-May** [comment]
[perf triage]
Please can you share measurements on the influence of using ItemDictionary?
