### ISSUE TITLE
Should static graph respect MSBuild.SkipNonExistentProjects and MSBuild.SkipNonExistentTargets?

### ISSUE THREAD

**Issue by cdmihai** [dotnet/msbuild#4252]
In msbuild, one can call targets which do not exist by setting SkipNonexistentTargets on the MSBuild task.
The static graph target protocol does not support this and will call the nonexistent targets which results in a build failure.

A possible implementation would be to support  `<ProjectReferenceTargets Include='Build' Targets='GetTargetFrameworks' SkipNonexistentTargets='true'>` which would instruct the target propagation code to take out non existing targets.

**Comment by rainersigwald** [comment]
I'd say "no".

**Comment by cdmihai** [comment]
Unfortunately we encountered some repos depending on skipping nonexistent targets. A possible implementation was attempted in https://github.com/dotnet/msbuild/pull/5297, but the PR has to be revived.

**Comment by rainersigwald** [comment]
> I'd say "no".

I now think this was wrong, _especially_ while we don't have #6852.

**Comment by AArnott** [comment]
I would add that the parser should honor `SkipGetTargetFrameworkProperties=true` by no longer executing the `GetTargetFrameworks` target.

See https://github.com/dotnet/Nerdbank.GitVersioning/pull/648#discussion_r709561954 for context.
