### ISSUE TITLE
Warning wave: error when task logs an error but doesn't fail

### ISSUE THREAD

**Issue by rainersigwald** [dotnet/msbuild#4294]
This is basically the inverse of #2036: it's possible today to log an error from a task but not fail the task, so you get a "Build SUCCEEDED with 3 errors" at the end. That's extremely confusing.

I think this could go with a warning-wave toggle, even though it's introducing a build failure instead of a warning, because it's such bad behavior.

**Comment by aitch-hat** [comment]
I just wanted to register some interest in this ticket. I'm regularly experiencing this issue at my organisation. I saw it first in Azure DevOps where I've observed build tasks experience errors but register success. The whole build is then registered as a success, which is false. This means the success/failure reporting of an Azure DevOps pipeline is unreliable, which is a pretty major fault for any continuous integration platform.

I've reported this issue in the [Microsoft Developer Community](https://developercommunity.visualstudio.com/content/problem/544946/azure-devops-msbuild-task-succeeds-despite-errors.html?childToView=569231#comment-569231). I was referred here to report the issue, but am pleased to find I'm not the first to experience it.

**Comment by danmosemsft** [comment]
All tasks ought only to ever return thus: `return !Log.HasLoggedErrors;`. If we could rewind time, Execute would be a void method and this would be implicit.

**Comment by guillaume86** [comment]
Did anyone find a solution/workaround for this issue on azure pipelines?
I'm using the Microsoft.Build.Traversal SDK to build some projects and encounter the same issue. 

No one seem interested to help in any place this is reported:

https://developercommunity.visualstudio.com/content/problem/544946/azure-devops-msbuild-task-succeeds-despite-errors.html?childToView=569231#comment-569231

https://social.msdn.microsoft.com/Forums/vstudio/en-US/9c699f64-8d2a-49e7-9454-028a7beb5f4f/build-succeeds-despite-error-in-task?forum=msbuild
