### ISSUE TITLE
MSBuild detects wrong core count on multi-proc machines

### ISSUE THREAD

**Issue by rainersigwald** [dotnet/msbuild#435]
If you use `msbuild /m` on a machine with more than 32 cores, we will only launch up to 32 processes. This appears to be because we generally run as a 32-bit process, and 32-bit Windows had a 32-core limit. But we should be able to use as many processes as cores, so we need to call an API that gives us "the real truth" about `NUMBER_OF_PROCESSORS`.

**Comment by AndyGerlicher** [comment]
Team brainstorming: We would like to fix this, not entirely sure how. The only way we know to get this is WMI, which is terribly slow. One proposal is to check if Environment.ProcessorCount == 32 then use WMI to get processor count. This way at least we'd only take the ~1sec hit when >32 is likely.

**Comment by mloskot** [comment]
I can confirm the issue. On machine with `NUMBER_OF_PROCESSORS=48` and VS2015 Update 1 installed, MSBuild utilises only up to 32 cores.

**Comment by rainersigwald** [comment]
I didn't update with the workaround that people are using internally until we can get a good fix in: we will spawn the correct number of processes if passed a number higher than 32 on the command line. *Getting* that number from a 32-bit command prompt can be a bit tricky, but if you can bury it in a script this might be worthwhile (presuming you have a very parallel build).

@mloskot, on your machine you should be able to use `msbuild.exe /m:48` to use the full machine.

**Comment by mloskot** [comment]
@rainersigwald It works, thanks.

![msbuild-48-cores](https://cloud.githubusercontent.com/assets/80741/13151840/4bdc4342-d66c-11e5-9aab-04fb2ec05217.png)

[Trying parallel MSBuild](https://gist.github.com/mloskot/eb93fe8303f2338c1252) with largish solution.

**Comment by rainersigwald** [comment]
I think we might be able to P/Invoke to [GetLogicalProcessorInformationEx](https://msdn.microsoft.com/en-us/library/windows/desktop/dd405488(v=vs.85).aspx) to get the correct count quickly. Haven't looked at it deeply though.

**Comment by mloskot** [comment]
Would you have any update on that?

**Comment by rainersigwald** [comment]
No progress yet. We should consider scheduling this for the next big update.

(It's still up-for-grabs, if anyone outside the core team would like to contribute a fix.)

**Comment by missmah** [comment]
Worse than this, on a 72-thread machine, NUMBER_OF_PROCESSORS is for some reason only reporting 36, and apparently VS only builds with 32, so this really leaves the machine empty by default (without /m:72).

**Comment by japj** [comment]
Just checking, is there a proven way to get the correct core count from win32? Or is that still part of the investigating into this issue? By chance I discovered we ran into this too.

**Comment by japj** [comment]
On a side note, should this not be in dotnet api, so this can work correctly cross platform?
