### ISSUE TITLE
What is the reason that binding redirects can't be generated for web projects?

### ISSUE THREAD

**Issue by maxinfet** [dotnet/msbuild#4373]
I know that binding redirects for web projects are output as warnings and the user can double click on them to add a binding explicitly but I was wondering why auto generating binding redirects for web projects is not possible? I saw this [comment](https://github.com/Microsoft/msbuild/blob/master/src/Tasks/AssemblyDependency/ResolveAssemblyReference.cs#L1035) as well but I have not found the limiting factor that prevents it?

**Comment by rainersigwald** [comment]
The story I've heard is twofold:

1. The binding redirects for web projects don't live in `app.config` but in an IIS configuration file.
2. That configuration file is generally _checked into the project_, and is used in F5 debug builds from its checked-in location.

Item 1 is obviously something that could be changed. Item 2 gets into more philosophy: generally, people are resistant to change user source code as part of the build, because it's too easy to change things accidentally and then get them checked in forever.

**Comment by maxinfet** [comment]
I am using the GenerateBindingRedirects task to update our web.config files and I was wondering if there was something I was missing about this. It seems to be working for our needs so I was curious if I was missing a reason this wasn't done more generically. I will say that point 2 has been quite accurate. One more thing I ran into was that many of our developers have different MVC libraries installed on their machines based on when they started and that causes quite a bit of meaningless churn in the bindings section.

I am actually looking into pulling the runtime section out into its own configuration file that will not be checked into version control for that reason. I just wanted to make sure I wasn't missing some other limitation that would make this impossible. Thank you.

**Comment by maxinfet** [comment]
I am not sure if this is the correct place to ask this question so if there is a better repository to ask this on please point me there. Is there a means to specify a relative path when using the linkedConfiguration element for the assemblyBindings?

```
  <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
    <linkedConfiguration href="./runtime.config"/>
  </assemblyBinding>
```

I have tried quite a few different variations of paths for the href attribute but have been unable to get it to pull in my runtime.config without giving it a absolute path to the runtime.config file.

**Comment by arielsrv** [comment]
I have the same issue, i can't to specify relative path o current runtime directory,

**Comment by arielsrv** [comment]
It's only works if you specify absolute path.

**Comment by mikeblakeuk** [comment]
Any news on this?

**Comment by maxinfet** [comment]
I am closing this because I only had a follow up question and @rainersigwald already helped me with the initial question. @rainersigwald if you happen to know where I could ask my question from 2019 I would be happy to create issue with the question in another repo.
