### ISSUE TITLE
Minimize NuGet package sources

### ISSUE THREAD

**Issue by rainersigwald** [dotnet/msbuild#4426]
I think all of these are canonically found on a blob feed now:

https://github.com/microsoft/msbuild/blob/2b277c1383fd93ce665cac006fcd3e1bb8c2afdd/eng/Versions.props#L9-L12

The last three we may not need at all.

We should see which of these we can remove or replace with a more up to date source.

**Comment by rainersigwald** [comment]
@BenVillalobos can you put this on your to-do list? Not high pri, but good tidiness and maybe some build/restore perf improvements.

**Comment by BenVillalobos** [comment]
Will do, assigning this myself.

**Comment by BenVillalobos** [comment]
Closing this, [here's why](https://github.com/microsoft/msbuild/pull/4500#pullrequestreview-260386514)

**Comment by BenVillalobos** [comment]
No longer an issue.
