### ISSUE TITLE
Let's make ProjectItem.EvaluatedIncludeBeforeWildcardExpansion public

### ISSUE THREAD

**Issue by xtmq** [dotnet/msbuild#4509]
We are developing Rider IDE and for some features we would like to have access to the `EvaluatedIncludeBeforeWildcardExpansion` property in some way.

**Comment by livarcocc** [comment]
Can you expand on your scenario and why this is needed?

**Comment by xtmq** [comment]
Yes, I will do. We are developing Rider IDE. And Rider supports `link` metadata. So imagine we have the next project item: 
```
<Compile Include="A.cs" Link="B.cs" />
```
In that case, Rider correctly renders node B.cs (which links to A.cs) in the solution explorer. 

But let's take a bit more complicated case:
```
<Compile Include="src/*.cs" Link="Data/X.cs" />
<Content Include="img/A.png;img/B.png" Link="Data/X.png" />
<None Include="@(Compile)" Link="Data/X.cs" />
```
In that case Rider has to understand that `ProjectItem` which represents `A.cs` or `A.png` came from some wildcard pattern and we have to drop last linked part (`/X.cs` and `/X.png`) and use physical file names to build project model.

And here we have a problem. Rider has to understand "origin" of some `ProjectItem` but it has only `UnevaluatedInclude` public property. In case of `src/*.cs` everything is ok, we can easily tell the item was introduced from a pattern. 
But for `@(Compile)` and `img/A.png;img/B.png` it is almost impossible. We have no idea which were produced by wildcard and which by a normal strict include. 

So public access to the property `EvaluatedIncludeBeforeWildcardExpansion` can solve this problem and allow us answering the question fast without trying to repeat MsBuild evaluation logic. 

Thanks!

**Comment by maridematte** [comment]
Team triage: We unfortunately are not planning on doing this work due to low priority, and it being an edge case for feature request.
