### ISSUE TITLE
Binary logger should respect verbosity

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/msbuild#4543]
Currently the Binary Logger forces verbosity to diagnostic:
https://github.com/microsoft/msbuild/blob/bd233ed5dd20725c79b16d907634874237267d77/src/MSBuild/XMake.cs#L3043

This has side effects, such as forcing Log Task Inputs and DetailedSummary. We should probably respect the ambient verbosity if specified explicitly. Still default to diagnostic if `/bl` is specified and the verbosity isn't specified.

**Comment by rainersigwald** [comment]
Reopening because we're reverting #8805 to fix #8845.
