### ISSUE TITLE
Add more EventSource profiling locations

### ISSUE THREAD

**Issue by Forgind** [dotnet/msbuild#4725]
EventSource profiling has already been added in various places in the code (see #4724)

Some recommendations:
Evaluator.cs (search TrackPass, TrackElement, TrackCondition, and TrackFile). This seems to cover some or all of the info previously captured by CodeMarkers.
ProfilerLogger.cs, 290, GenerateProfilerReport, This is called only on shutdown as the profiler report is written to disk.

EvaluationFrame has a Dispose method. Searching for it naively returns a lot of results, but I'm suspicious that most of them are not actually referring to EvaluationFrames, just other IDisposables, so I think it better to look at what places actually make an EvaluationFrame (which is done above) and ignoring where they're disposed of and logging information is recorded.

ProfilerResult can also store some relevant info about...what our profiler logged...and it's used in BuildEventArgsReader.cs, ProfilerResult.cs, ProjectEvaluationFinishedEventArgs.cs (probably irrelevant), ProfilerResult.cs (which seems to be a struct, so it probably isn't relevant), some test files (probably irrelevant), ProfilerLogger.cs

MSBuild multiprocess builds involve sending messages over IPC pipes. It’d be nice to have correlatable events between:
•	Process A starts sending a message (before serializing the message itself and before pipe operations), and
•	Process B handles the message (after deserializing and routing the message but before doing whatever the message wanted done)

**Comment by rainersigwald** [comment]
I'd like to see eventing around serialization/deserialization for IPC (in and around `NodePacketTranslator`).

**Comment by livarcocc** [comment]
I agree. We should definitely add tracing around IPC.

**Comment by Forgind** [comment]
ctrl-t did not reveal a NodePacketTranslator. Were you thinking of the BinaryTranslator class? Also, doesn't that duplicate:
```
MSBuild multiprocess builds involve sending messages over IPC pipes. It’d be nice to have correlatable events between:
• Process A starts sending a message (before serializing the message itself and before pipe operations), and
• Process B handles the message (after deserializing and routing the message but before doing whatever the message wanted done)
```
?
