### ISSUE TITLE
Nodemode failure

### ISSUE THREAD

**Issue by Forgind** [dotnet/msbuild#4906]
There seems to be a problem with nodemode (an internal flag) without an argument.
I set MSBUILDDEBUGONSTART to 1 and built a project that referenced two other libraries using the command:
`<path to MSBuild.exe> <path to project file> /m /nodemode /nodereuse:false`

Expected behavior: useful error message about how nodemode works.
Actual behavior: unexpected bug with a message asking me to file a bug on GitHub.

This should not be an important issue because is has minimal customer impact, but it still might be nice to have a better error message.

**Comment by abc516** [comment]
Hi @Forgind I'm willing to take this on. Any tips on how to approach?

**Comment by Forgind** [comment]
Thanks @abc516!

It turns out this was resolved by https://github.com/dotnet/msbuild/pull/5569, but we didn't realize it until I tried to reproduce this issue just now. Let me know if there are any others you'd like to try!
