### ISSUE TITLE
Question: Task Output ItemGroup result as MetaData in ItemGroup?

### ISSUE THREAD

**Issue by japj** [dotnet/msbuild#4945]
I have an ItemGroup with files that need to be processed in a Target.
This processing takes several steps and I would like to store the progress along the way (e.g. for error reporting or further processing)

I find that I would like the Output keyword (for ItemName) to behave differently that it currently does.

Example:
```xml
        <ItemGroup>
              <SomeFile include="file1">
                   <Location>..\someplace\file1/Location>
               </SomeFile>
        </ItemGroup>
..
        <GetFileHash Files="%(SomeFile.Location)">
            <Output TaskParameter="Hash" PropertyName="SomeFile"/>
        </GetFileHash>

<!-- would like to have result-->
        <ItemGroup>
              <SomeFile include="file1">
                   <Location>..\someplace\file1/Location>
                   <Hash>abcdefhash</Hash>
               </SomeFile>
        </ItemGroup>
```

The actual result is that new items are appended to the ItemGroup with identity set to the Hash Value.

Is there a different way to get a similar result?
(e.g. if I can merge 2 ItemGroups (same length) without needing to have same identity)

**Comment by rainersigwald** [comment]
Best we've come up with on the team is a new (inline?) task that takes

1. A list of items to add the metadata to
1. A list of items where the include is the metadata to add (hashes in this case)
1. The name of the metadata to put that into

And emits the result as a new item which can be swapped back into the old item.

**Comment by japj** [comment]
going to close this item, since we managed to make the custom task as described above
