### ISSUE TITLE
DotNet Core 3.1 - Resources Files no longer being resolved.

### ISSUE THREAD

**Issue by owlyowl** [dotnet/msbuild#4962]
### Steps to reproduce
Please see https://github.com/dotnet/corefx/pull/42209#issuecomment-561538797

I've upgraded a DotNet Core 3.0 project to 3.1 and explicitly set build version in global.json and in the csproj files to make sure everything is built to the same target.

1. Open sln.
2. Clean & build
3. From cli dotnet run
4. Attach debugger and open site
5. Observe LocalisationController.cs line 67 -  resourceManager.GetResourceSet(CultureInfo.GetCultureInfo("en-US"), true, true) throws

Previously in 3.0 ResX files were being resolved correctly, now they're not able to be loaded in.
Here's the ILSpy:
![image](https://user-images.githubusercontent.com/1916426/70279225-1cca9700-180a-11ea-95ee-4adf59730fa6.png)

Referred to here by Eric StJohn,

Can someone please let me know what email address would be best to share a repo with?

**Comment by ericstj** [comment]
@owlyowl you can zip it up and drag/drop into a github comment, or if you prefer to keep it off github you can email me at ericstj at microsoft dot com and I will distill it to a minimal repro and share it.

**Comment by owlyowl** [comment]
Thanks Eric
Ill do that :)

I'll shoot off an email on Monday alas in the middle of moving house

**Comment by ericstj** [comment]
@owlyowl I didn't get anything in email, were you able to send it?

Also, if you're willing to share more broadly you should be able to attach the zip to the issue (simply drag-drop into comments).

**Comment by ericstj** [comment]
Just to add some context for MSBuild folks.  As shown in the ILSpy screenshot this assembly has no resources embedded.  The screenshot shared in the linked issue showed the project's resx files:
![image](https://user-images.githubusercontent.com/8918108/72929879-90b7f480-3d0f-11ea-8004-c30b37a6dc61.png)  microsoft/msbuild#4597 or microsoft/msbuild#4740

I thought this could be related to

**Comment by BenVillalobos** [comment]
Closing. We've done a lot of work on resources since this issue was filed. One of those changes may have covered this. If it hasn't, please reopen 😁
