### ISSUE TITLE
Investigation status for failing tests on OSX with netcore msbuild

### ISSUE THREAD

**Issue by cdmihai** [dotnet/msbuild#499]
Some tests are failing on OSX when run on netcore osx. This issue tracks the investigation status of those tests and why they are failing.

The tests that are failing on OSX with netcore msbuild have been marked with `[Trait("Category", "netcore-osx-failing")]`

**Comment by cdmihai** [comment]
@JunielKatarn

**Comment by JunielKatarn** [comment]
Hi. Is this something I should do something about?

**Comment by radical** [comment]
@JunielKatarn No. It should be fixed with PR #498 .

**Comment by cdmihai** [comment]
My original intention was to have this issue track the investigation status for the failing OSX tests on netcore.

**Comment by JunielKatarn** [comment]
@cdmihai Is there a way to only run a specific set of tests?
For instance, run only tests in `src/XMakeTasks/UnitTests/Move_Tests.cs`.
I'm trying to fix currently failing tests on OS X, but it's a pain to run all tests each time.

**Comment by rainersigwald** [comment]
@JunielKatarn The way I've generally done that in the past is to get the failing command line out of the MSBuild log and add filter operations to it. For your case, I think `-class Microsoft.Build.UnitTests.Move_Tests` would do the trick.

**Comment by cdmihai** [comment]
@JunielKatarn 
I also use the `-class` and even `-method` xunit params to run only the tests in a class or a specific test from a class.

Xunit also nicely formats the test results in xml files (one xml per test dll: `%(AssemblyUnderTest.FullPath)_core_TestResults.xml`).

To quickly get the fully qualified names I grep these xmls for the `result="[^ps]` regex. This quickly gives me the line containing the fully qualified names.
