### ISSUE TITLE
Long if-else statements

### ISSUE THREAD

**Issue by Forgind** [dotnet/msbuild#5019]
https://github.com/microsoft/msbuild/blob/master/src/Build/Logging/BinaryLogger/BuildEventArgsWriter.cs#L35-L86
is not pretty and can probably be made a lot cleaner using a visitor. Alternatively, if the relevant information to be written to the log can be passed in a form other than the type—a string for example—that might be a cleaner and more efficient solution.

There are probably other similar examples.

**Comment by szaliszali** [comment]
also related to the `BuildEventArgsWriter` mentioned in the issue by @Forgind :

`Microsoft.Build.Logging.EventArgsDispatcher.Dispatch` at https://github.com/dotnet/msbuild/blob/e70a3159d64f9ed6ec3b60253ef863fa883a99b1/src/Build/Logging/BinaryLogger/BuildEventArgsDispatcher.cs#L86-L142

additional very deeply nested if-else's:

`Microsoft.Build.Shared.FileUtilities.ItemSpecModifiers.GetItemSpecModifier` at https://github.com/dotnet/msbuild/blob/bf8629b4cd92c1bd05de8b1e124b4700eb0b7834/src/Shared/Modifiers.cs#L390-L616

`Microsoft.Build.Evaluation.Expander.Function.TryExecuteWellKnownFunction` at https://github.com/dotnet/msbuild/blob/df645299a158c787f9884fca2bcd8c295318193f/src/Build/Evaluation/Expander.cs#L3531-L4148

also, there are several cases where high complexity was introduced for performance optimization - one example: `Microsoft.Build.Shared.FileUtilities.ItemSpecModifiers.IsItemSpecModifier` at  https://github.com/dotnet/msbuild/blob/bf8629b4cd92c1bd05de8b1e124b4700eb0b7834/src/Shared/Modifiers.cs#L86-L253
this structure seems to be a frequently recurring pattern to reduce number of string comparisons, not sure if these are still worth with modern .Net versions of not

_[list above is not exhaustive, don't have good tools to discover all occurrences efficiently]_
