### ISSUE TITLE
Slow in-place build after upgrade to sdk build

### ISSUE THREAD

**Issue by michalsznajder** [dotnet/msbuild#5057]
I have Visual Studio 2019 version `16.4.1 `and MSBuild version `16.4.0+e901037fe for .NET Framework`.

I have a solution with around 250 projects (mix of `csproj` and `vcxproj`). All target `net4.8` or produces native images.  All projects are currently using "old" style `csproj` (`<Project DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003" ToolsVersion="4.0">`). `ToolsVersion` is `4.0` but I think it is not important to my case.

Recently I wanted to have a look on "new style" builds ("sdk") and I converted one small `csproj`  with excellent [CsprojToVs2017](https://github.com/hvanbakel/CsprojToVs2017). This went smooth and there is no problem (except I had to set `AppendTargetFrameworkToOutputPath` to `false` to adjust `OutputPath`). This `cspro`j has one direct dependency but more than 70 indirect ones.

My problem is that it takes too long for subsequent builds to complete. Even smallest change in my project takes around 8 seconds to build in Visual Studio (via `r-click-> Build` or `Ctrl+B`).  I installed [Project System Tools](https://marketplace.visualstudio.com/items?itemName=VisualStudioProductTeam.ProjectSystemTools) and by looking into resulting logs I see that biggest offender is  `_GetProjectReferenceTargetFrameworkProperties:`

```
       34 ms  FindReferenceAssembliesForReferences       1 calls
       59 ms  _CopyFilesMarkedCopyLocal                  1 calls
       88 ms  AssignTargetPaths                         81 calls
      148 ms  ResolveAssemblyReferences                  1 calls
      483 ms  GetCopyToOutputDirectoryItems             81 calls
     1227 ms  ResolveProjectReferences                   1 calls
     5699 ms  _GetProjectReferenceTargetFrameworkProperties  81 calls

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:08.60
```

Looking at definition for [`_GetProjectReferenceTargetFrameworkProperties`](https://github.com/microsoft/msbuild/blob/e812790eabece155f9ea7cbc13d57ce1ad7bff19/src/Tasks/Microsoft.Common.CurrentVersion.targets#L1581) I tried setting `SkipGetTargetFrameworkProperties` but it did not change situation

```
 <ProjectReference Include="..\project\project.csproj" SkipGetTargetFrameworkProperties="true" />
```

Do I hit some edge case or is it just "regular" RAR problem mentioned so often in issues here? Is there any workaround? I do not need multitargetting currently.

**Comment by rainersigwald** [comment]
> This `cspro`j has one direct dependency but more than 70 indirect ones.

Can you try setting `<DisableTransitiveProjectReferences>true</DisableTransitiveProjectReferences>` in the project with one direct dependency?

**Comment by AR-May** [comment]
[perf triage]
Is this still an issue? Does the setting DisableTransitiveProjectReferences helped?

**Comment by michalsznajder** [comment]
I cannot tell any longer as I am not working with this code (I left company). And I longer posses code that is so huge (it was i range of 2 MLOC in a single solution)

As for DisableTransitiveProjectReferences: I don't remember. I think it might have helped but I am not sure.

**Comment by AR-May** [comment]
Got it, thank you for your response!

**Comment by AR-May** [comment]
[Perf triage]
Closing this issue as outdated.
