### ISSUE TITLE
An experience to create "isolated" task

### ISSUE THREAD

**Issue by wli3** [dotnet/msbuild#5068]
Since we have task assembly load context checked in. We should be able to produce such Task easily and consume them with just a package reference.

The implementation code will probably be in SDK. And share a big chuck with PackAsTool=true

**Comment by wli3** [comment]
We should have a template and something like dotnet build /p:packAsTask=true

and one the consumer side just add a package reference. And you can use the target maybe even without <using....>

**Comment by Nirmal4G** [comment]
Do you mean this #4834?

**Comment by wli3** [comment]
I don't think that's the same

**Comment by Nirmal4G** [comment]
Ahhh... Similar to SDKs but only with `UsingTask` in the imports. I see now.

Projects like `MSBuild Extension Pack` and many others would benefit from this.

Having a project system to author, debug and test MSBuild packages would complement this.

**Comment by rainersigwald** [comment]
I think this could be rolled into #7548.
