### ISSUE TITLE
Lots of duplicated items inside List<ProjectItemDefinitionInstance> inside ProjectItemInstance

### ISSUE THREAD

**Issue by lifengl** [dotnet/msbuild#5092]
Do we need all the repeated items in this list?
![image](https://user-images.githubusercontent.com/11638466/73388495-3080ff80-4287-11ea-8e26-634de5825723.png)

Also similar items in the same ProjectInstance usually share the same ProjectItemDefinitionInstance. Can we reuse a CopyOnWriteList<> here, so we don't need create extra list for every item in the project?

**Comment by AR-May** [comment]
[Perf triage]
It does not seem to have a big impact in a memory footprint, so we decide to close this issue. Please feel free to reopen the issue if you feel otherwise.
