### ISSUE TITLE
Add an option to treat MSB3277 (Found conflicts between different versions...) as an error

### ISSUE THREAD

**Issue by n-voronkov** [dotnet/msbuild#5184]
VS/Nuget sometimes add duplicated entries in app.config which will lead to runtime errors while loading assemblies. Oftentimes it requires hitting specific codepath and having an option to treat this error as warning at build time would really benefit and save time.

**Comment by rainersigwald** [comment]
Team triage: This makes sense as a new, opt-in behavior. Marking up-for-grabs--if you'd like to contribute a fix, please let us know.

**Comment by Forgind** [comment]
This can be resolved with <MSBuildWarningsAsErrors>MSB3277</MSBuildWarningsAsErrors>.
