### ISSUE TITLE
Microsoft.Common.tasks cleanup

### ISSUE THREAD

**Issue by rainersigwald** [dotnet/msbuild#5190]
`Microsoft.Common.tasks` has every built-in MSBuild task duplicated between sections, one of which is

https://github.com/microsoft/msbuild/blob/3453beee039fb6f5ccc54ac783ebeced31fec472/src/Tasks/Microsoft.Common.tasks#L9-L14

I don't think we need to have back compat with dev11 any more, and `$(AssemblyVersion)` should never be empty with MSBuild as built from this repo.

I'm not 100% sure of the impact of just deleting all the 4.0 references; that needs to be considered.

We _cannot_ delete the 3.5 references like

https://github.com/microsoft/msbuild/blob/3453beee039fb6f5ccc54ac783ebeced31fec472/src/Tasks/Microsoft.Common.tasks#L39

They're needed for asset compat on old projects. But they should be conditioned out on .NET Core, which they currently are not.

**Comment by Nirmal4G** [comment]
If we have a Core SDK for the common targets, it might be safe to clean up all workarounds and back-compat till v15!

Can the following be removed too? As you said `$(MSBuildAssemblyVersion)` will not be empty. These code paths will never hit.

https://github.com/microsoft/msbuild/blob/ee1c9fd0c7e0e43174785a4e2ed177f14f5856a0/src/Tasks/Microsoft.Common.props#L93

https://github.com/microsoft/msbuild/blob/ee1c9fd0c7e0e43174785a4e2ed177f14f5856a0/src/Tasks/Microsoft.Common.props#L107-L112

https://github.com/microsoft/msbuild/blob/ee1c9fd0c7e0e43174785a4e2ed177f14f5856a0/src/Tasks/Microsoft.Common.props#L117

We could also remove xmlns as we already removed `$(MSBuildAllProjects)` (thus the min MSBuild version will be v16)!
