### ISSUE TITLE
Could not load file or assembly 'Microsoft.Build.Framework, Version=15.1.0.0

### ISSUE THREAD

**Issue by megactek** [dotnet/msbuild#5192]
Unhandled Exception: System.TypeInitializationException: The type initializer for 'Microsoft.Build.CommandLine.MSBuildApp' threw an exception. ---> System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Build.Framework, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
   at Microsoft.Build.CommandLine.MSBuildApp..cctor()
   --- End of inner exception stack trace ---
   at Microsoft.Build.CommandLine.MSBuildApp.Main()

**Comment by itrice** [comment]
Yes there have another issue, maybe the same issue. #5193

**Comment by megactek** [comment]
Every time i try to build a code and debug it keeps popping this error on the command-line and later will output build 0 - successful 1 - skipped
then microsoft visual studio will prompt error in build, run previous version?

**Comment by rainersigwald** [comment]
If you're encountering this problem (@megactek @itrice), can you please download and run https://github.com/microsoft/msbuild/blob/2d82e1a861d890fce68c8e2d42b569e5bbaf5687/scripts/EnumerateMSBuild.ps1 and share the results? You might have a Visual Studio installation problem, or you might have MSBuild assemblies in your Global Assembly Cache (GAC). If it's the latter, the instructions from [this feedback issue](https://developercommunity.visualstudio.com/solutions/219148/view.html) might help you.

**Comment by marakonec** [comment]
Hello I have the same problem. 

_Exception has been thrown by the target of an invocation.  The project file could not be loaded. Could not load file or assembly 'Microsoft.Build.Framework, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified._ 

The error occurs when I execute the nuget restore command. Nuget version 4.6.2. I have two ways to solve this problem. 
1. Use Nuget 4.8.2 and higher.
2. gacutil /i "C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin\Microsoft.Build.Framework.dll

**But I need a different solution.**


Enumerate MSBuild result attached. 
[msbuild_versions.txt](https://github.com/microsoft/msbuild/files/4460831/msbuild_versions.txt)

**Comment by newCoderNovice** [comment]
@rainersigwald  here is the result of the run:
[msbuild_versions.txt](https://github.com/dotnet/msbuild/files/5335579/msbuild_versions.txt)

**Comment by rainersigwald** [comment]
> The error occurs when I execute the nuget restore command. Nuget version 4.6.2.

@megactek This should be resolved by #5257 in Visual Studio 2019 16.5.5.

**Comment by rainersigwald** [comment]
@newCoderNovice can you describe what you're doing when this happens?
