### ISSUE TITLE
Default ProjectImports still creates a temporary zip

### ISSUE THREAD

**Issue by asklar** [dotnet/msbuild#5383]
https://github.com/microsoft/msbuild/blob/5cb677292e0fe6f9db973d416ea866332833c306/src/Build/Logging/BinaryLogger/BinaryLogger.cs#L187

The docs say that the default for /bl is ProjectImports=Embed. However msbuild creates a zipfile, writes to it, then reads from to embed it in the binlog and deletes the zip file.
This is causing file lock contention with some tools we have (Metro bundler, used in React Native). The bundler watches for new files and .zip is one of the file extensions it watches. The end result is that metro tries accessing the newly created file while msbuild is writing it.

See also https://github.com/MicrosoftDocs/visualstudio-docs/issues/5388

**Comment by KirillOsenkov** [comment]
We could add a flag to have this stream in memory and never write it to disk.

**Comment by asklar** [comment]
@KirillOsenkov @rainersigwald any idea when this might be addressed? This currently breaks Release builds of some React Native for Windows apps.
During the build we will call out to a tool that packs most files in the app's directory (js files, images, and unfortunately zip files too).
Because msbuild is holding this file open, the packing fails which breaks the build.

**Comment by KirillOsenkov** [comment]
Unfortunately my schedule looks really busy right now, so I honestly don't know when I'll be able to get to it. For now try outputting the .binlog into a different directory, the .zip file should get created next to it. 

`msbuild /bl:..\..\logs\msbuild.binlog`
