### ISSUE TITLE
Resolving metadata fails when referencing a c++/winrt project from a c# uwp project

### ISSUE THREAD

**Issue by matthew4850** [dotnet/msbuild#5412]
### Steps to reproduce
Download attached zip and run:
`msbuild test.sln /p:AppxBundlePlatforms="x86|x64|ARM" /p:AppxBundle=Always /p:UapAppxPackageBuildMode=StoreUpload /p:Configuration=Debug /p:Platform="x86"`
[test.zip](https://github.com/microsoft/msbuild/files/4740498/test.zip)

Directory contents:
```
/
- test.sln
- test.user
- App1/
     - App.xaml
     - App.xaml.cs
     - App1.csproj
     - MainPage.xaml
     - MainPage.xaml.cs
     - Package.appxmanifest
- RuntimeComponent1/
     - Class.cpp
     - Class.h
     - Class.idl
     - packages.config
     - pch.cpp
     - pch.h
     - PropertySheet.props
     - RuntimeComponent.def
     - RuntimeComponent.vcxproj
     - RuntimeComponent.vcxproj.filters
- packages/
     - Microsoft.Windows.CppWinRT.2.0.200316.3/
```

### Expected behavior
It builds successfully.

### Actual behavior
`CSC : error CS0006: Metadata file [path] could not be found`

### Environment data
`msbuild /version` output:
16.5.0.12403
OS info:
Windows 10 20h1

**Comment by jbrianceau** [comment]
I observe the same issue, which actually seems to be a **regression** introduced between versions `2.0.191018.6` and `2.0.191023.3`.

Here are the results using different release of CppWinRT nuget with the test project provided above by @matthew4850 :
| CppWinRT nuget release | Issue does repro? |
|:-:|:-:|
| Microsoft.Windows.CppWinRT.2.0.191018.6 | No |
| Microsoft.Windows.CppWinRT.2.0.191023.3 | Yes |
| Microsoft.Windows.CppWinRT.2.0.200316.3 | Yes |
| Microsoft.Windows.CppWinRT.2.0.201113.7<br/>(current latest release) | Yes |

**Comment by rainersigwald** [comment]
@jlaanstra is fixing this with https://github.com/microsoft/cppwinrt/pull/824. Thanks! We'll let it be tracked there.

**Comment by jbrianceau** [comment]
For the record, fix is available in the [Microsoft.Windows.CppWinRT.2.0.201217.4](https://github.com/microsoft/cppwinrt/releases/tag/2.0.201217.4) nuget release.
