### ISSUE TITLE
Prevent OutputPath from flowing to project references via a global property

### ISSUE THREAD

**Issue by dsplaisted** [dotnet/msbuild#5420]
The .NET CLI supports `--output` as a parameter to the build command, and [translates this](https://github.com/dotnet/sdk/blob/d30e9ba1fe915d99cd3455bda9b41cde42775fbe/src/Cli/dotnet/commands/dotnet-build/BuildCommandParser.cs#L23-L27) into a `-property:OutputPath` parameter to MSBuild.

Since this is a global property, it will flow to referenced projects and they will all build with the same output path.  This isn't safe.  We should add `OutputPath` to a list of properties which we remove when building project references.

**Comment by rainersigwald** [comment]
Today, we don't have any default value for 

https://github.com/microsoft/msbuild/blob/9eb5d09e6cd262375e37a15a779d56ab274167c8/src/Tasks/Microsoft.Common.CurrentVersion.targets#L1814

This would involve adding one or hardcoding it at the callsites; that could create problems.

Logically, I agree with you, but some people might depend on it (with `UseCommonOutputDirectory=true`?). I think we'd at least need an opt-out; maybe we should do an opt-in and opt in at the SDK layer?

**Comment by dsplaisted** [comment]
We might want to consider also stopping other OutputPath-like properties from flowing, such as `BaseIntermediateOutputPath`.
