### ISSUE TITLE
Sometimes ProjectStarted.ParentProjectBuildEventContext doesn't report the parent task

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/msbuild#5422]
Projects triggered by the MSBuild task should have the task ID reported in the ParentProjectBuildEventContext. This works fine for a simple P2P and the projects are nested under the MSBuild task correctly:

![image](https://user-images.githubusercontent.com/679326/84455160-7674a980-ac11-11ea-844f-8854c918cf2a.png)

However I am seeing cases in the wild where projects are nested directly under the parent project because their TaskId is set to -1:
https://github.com/KirillOsenkov/MSBuildStructuredLog/issues/358

We should investigate and always make sure that the TaskId is set properly.

This was implemented in https://github.com/microsoft/msbuild/pull/5013 but apparently doesn't cover all the cases?

**Comment by marcpopMSFT** [comment]
@KirillOsenkov Is this different than what you fixed in #5996?

**Comment by KirillOsenkov** [comment]
Nope, same issue, can close.
