### ISSUE TITLE
Consider disabling compression of target results

### ISSUE THREAD

**Issue by ladipro** [dotnet/msbuild#5443]
The code in `TargetResults.CompressItems()` and `TargetResults.DecompressItems()` may be hurting performance rather than helping. On the compression side we translate all task items into a `MemoryStream`, convert the stream to a `byte` array, then compress the `byte` array using a `DeflateStream`, then convert this stream to a `byte` array to finally subject it to the rest of the serialization logic to send it cross process. Similarly on the receiving side, we make a bunch of allocations and burn CPU to get to the original decompressed items. It's very likely that it would be faster and less memory intensive to simply send the uncompressed items.

We should:
- Measure the performance impact of compression with a microbenchmark.
- Remove it if it doesn't prove helpful.

**Comment by ladipro** [comment]
I have seen MSBuild fail with this exception a couple of times. It is possible that the code in question also has a bug, which would be another reason to get rid of it 😉 

![image](https://user-images.githubusercontent.com/12206368/84961767-67a46000-b105-11ea-95ca-451bba07a0b5.png)

**Comment by rainersigwald** [comment]
I've only ever seen that exception in internal scenarios that use the unsupported `DEVPATH` .NET runtime feature. Have you seen it outside of razzle/corext?

This is not an objection to deleting the code!

**Comment by ladipro** [comment]
It was indeed in razzle, apologies for blaming it on the code. Out of curiosity, is it understood how `DEVPATH` leads to this exception?

**Comment by ostorc** [comment]
I have tried to measure the impact of disabling of the compression. Benchmark was run 100 times for each group
```
COMPRESSION - 100 items
---------
AVG: 17.8602 ms

COMPRESSION - 1000 items
---------
AVG: 22.7986 ms

COMPRESSION - 10000 items
---------
AVG: 47.2003 ms

NO COMPRESSION - 100 items
---------
AVG: 15.6751 ms

NO COMPRESSION - 1000 items
---------
AVG: 19.1399 ms

NO COMPRESSION - 10000 items
---------
AVG: 51.6685 ms
```
My testing target was simple task which put on input all items from one folder.
As you can see, the compression starts to reduce time around 10k items, but I haven't seen any project which would have so many items on output to other process (although my experience in this is rather shallow). Most of the projects have only one or two items on output (I have tried for example OrchardCore). So I think it makes sense to remove the code. What do you think @rainersigwald?

**Comment by rainersigwald** [comment]
Those numbers look convincing to me. While there's nothing _preventing_ extremely large results I agree that the common case is tiny and much more interesting than the extreme. Let's do it!
