### ISSUE TITLE
Switch to use new Microsoft.IO.Redist (and Net Core Path library) to scan disk & handle file paths

### ISSUE THREAD

**Issue by lifengl** [dotnet/msbuild#5468]
The new library provides more efficient way to scan file system (with less GC pressure), and can make the globbing resolving code more efficient.

**Comment by rainersigwald** [comment]
Note previous failures to do this #3947. Nothing big, just may require care.

I'm also fairly concerned about compat with the existing code; we'll need to be careful about that.

**Comment by AR-May** [comment]
Closing as it is a duplicate for #6075.
