### ISSUE TITLE
VB.Net SDK Project fails to compile when two resx file exists with the same name in different namespaces

### ISSUE THREAD

**Issue by elachlan** [dotnet/msbuild#5469]
### Steps to reproduce
Have a VB.Net winforms project using SDK project type. The project should include two forms with the same name in separate namespaces. Each form should have its icon set, so that it creates a resource file.

This isn't an issue for C#.

**See Attached zip:**
VB: [TestApp2.zip](https://github.com/microsoft/msbuild/files/4843881/TestApp2.zip)
C#: [TestApp3.zip](https://github.com/microsoft/msbuild/files/4855050/TestApp3.zip)

**Error:**
```
MSB3577: Two output file names resolved to the same output path: "obj\Debug\net472\TestApp2.Edit.resources"

C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets
```

The code that the error points you to is line 3036 in Microsoft.Common.CurrentVersion.targets  which is situated in the CoreResGen section:
https://github.com/microsoft/msbuild/blob/e2a33003170b038bf0c2414df166b5409d4b9581/src/Tasks/Microsoft.Common.CurrentVersion.targets#L3035-L3064

I believe the error is raised from:
https://github.com/microsoft/msbuild/blob/86d9494e446de002ea6a4f08d6fbd111b1041059/src/Tasks/GenerateResource.cs#L1462-L1491

The issue stems from the fact that in VB.Net the OutputResources are added without their namespaces:
![image](https://user-images.githubusercontent.com/2433737/86191318-1460f180-bb8a-11ea-85cb-1095f9092aa4.png)

Where as the C# OutputResources are fully qualified:
![image](https://user-images.githubusercontent.com/2433737/86191418-59852380-bb8a-11ea-8b17-80a2768aa850.png)

The names are transformed here using the EmbeddedResources ManifestResourceName, which seems to be broken in VB.NET:
https://github.com/microsoft/msbuild/blob/e2a33003170b038bf0c2414df166b5409d4b9581/src/Tasks/Microsoft.Common.CurrentVersion.targets#L3050

**Comment by elachlan** [comment]
I wasn't sure where to raise it so i have also raised an issue in the dotnet/project-system:
https://github.com/dotnet/project-system/issues/6312

**Comment by elachlan** [comment]
I have a report class library that doesn't have any forms and it also displayed the same issue.

**Comment by elachlan** [comment]
@rainersigwald sorry to bother you with this. I am wondering if this is enough information to go off of?

**Comment by rainersigwald** [comment]
@BenVillalobos can you take a look at this?

**Comment by BenVillalobos** [comment]
@elachlan Thanks for such a detailed issue! There's a PR in the works now.

**Comment by elachlan** [comment]
@BenVillalobos Thanks for looking into it! Glad I was able to help :)

**Comment by KathleenDollard** [comment]
See https://github.com/microsoft/msbuild/pull/5477#pullrequestreview-450781160

**Comment by elachlan** [comment]
So essentially it can't be fixed/won't in msbuild?

Would the fix be in visual studio to have it add an entry to the project file with dependant upon for the form resource file?

Additionally might I suggest we add an explanation of the differences between C# and VB.net at the top of CreateVisualBasicManifestResourceName.cs?

**Comment by elachlan** [comment]
For the new SDK project format, would it not make sense for vb.net winforms projects to automatically include set dependant upon for its associated resource file (same name)? Visual Studio already recognises the resource file as a part of the form. 

That way the project file isn't polluted unnecessarily with boilerplate definitions, which is the intention of the new format.

@KathleenDollard that wouldn't be a breaking change would it? Since its inline with what currently happens in the old project system?

**Comment by BenVillalobos** [comment]
@elachlan unfortunately it doesn't seem obvious (at least to me) that there is a "fix" for this situation. Especially after discovering that vb.net doesn't account for subfolders _by design_. The way DependentUpon works at the moment is also _by design_, and this specific situation is an unfortunate side effect that we offer ways to get around (manually setting `LogicalName`, `ManifestResourceName` metadata, or changing the folder structure).

Though I do agree we should clarify the differences between the two files, as this info should be archived. If you'd like, please file an issue 🙂 otherwise I can do that in a day or two.

**Comment by elachlan** [comment]
I really appreciate all your help. I do not think the fix is in msbuild. But maybe in visual studio, to lighten the load of management.

I spent the last 4 days working to convert to an SDK project for two production winforms applications. I have to manually added entries for every form for the compile(vb/designer.vb) and embeddedresource tags(.resx) to get it to work.

Will visual studio be managing these entries in the project file in the future for VB.Net projects? 

some of the issues I have had:
- licx files (the release build didn't have a license for 3rd party component)
- version numbers not showing in users app data folder, but on the assembly.
- forms not showing as a form and being unable to be edited. (fix was manual entries, sometimes it wasn't needed, I can't work out what breaks it.)

It really does need someone to investigate the use case thoroughly to iron out issues with the sdk format.

Thank you all for your help. You have done a great job.

**Comment by BenVillalobos** [comment]
I'll have to defer to @KathleenDollard for your latest question.

Glad we got to a solution!
