### ISSUE TITLE
ToolTasks Can Log MSB4181 When Cancelled

### ISSUE THREAD

**Issue by danmoseley** [dotnet/msbuild#5508]
### Steps to reproduce

Assume there is a tool named "sleep" in the path. Build this project, then hit Ctrl-C.
```xml
<Project>

  <Target Name="t">
    <Exec Command="sleep 1000000"/>
  </Target>

</Project>
```

### Actual behavior
```
C:\proj>dotnet msbuild test.proj
Microsoft (R) Build Engine version 16.7.0-preview-20330-08+96403c598 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

Attempting to cancel the build...
C:\proj\test.proj(4,5): warning MSB5021: Terminating the task executable "cmd" and its child processes because the build was canceled.
C:\proj\test.proj(4,5): error MSB4181: The "Exec" task returned false but did not log an error.
```

### Expected behavior

If the task was canceled, suppress MSB4181.

MSB4181 is a grumble that the task does not follow the contract of "return false if an only if you logged an error". But in the case of cancelation, this error is useless for the user, who just hit Ctrl-C, and for the task author, who returned immediately exactly as the engine required them to. We don't want task authors to start logging bogus errors on cancelation. Just continue and fail the build with `MSB4188: Build was canceled`  in the normal way.

### Environment data
```
C:\proj>dotnet msbuild /version
Microsoft (R) Build Engine version 16.7.0-preview-20330-08+96403c598 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

16.7.0.33008
```

**Comment by rainersigwald** [comment]
Someone else brought this up with me but I can't find it now. I agree.

**Comment by jeffkl** [comment]
The `Copy` task does this as well when `ContineOnError` is set to `true`

```xml
<Project>
  <Target Name="Build">
    <ItemGroup>
      <SourceFiles Include="Foo" />
    </ItemGroup>
    <Copy SourceFiles="@(SourceFiles)"
          DestinationFolder="$(MSBuildBinPath)"
          ContinueOnError="true"
          Retries="0" />
  </Target>
</Project>
```

```
D:\>msbuild D:\Stuff\MSB4181.proj /clp:v=m;summary;forcenoalign
Microsoft (R) Build Engine version 16.8.0-preview-20411-05+9a32a8063 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

D:\Stuff\MSB4181.proj(6,5): warning MSB3021: Unable to copy file "Foo" to "C:\Program Files (x86)\Visual Studio 2019 Preview\MSBuild\Current\Bin\Foo". Access to the path 'C:\Program Files (x86)\Visual Studio 2019 Preview\MSBuild\Current\Bin\Foo' is denied.
D:\Stuff\MSB4181.proj(6,5): warning MSB4181: The "Copy" task returned false but did not log an error.

Build succeeded.

D:\Stuff\MSB4181.proj(6,5): warning MSB3021: Unable to copy file "Foo" to "C:\Program Files (x86)\Visual Studio 2019 Preview\MSBuild\Current\Bin\Foo". Access to the path 'C:\Program Files (x86)\Visual Studio 2019 Preview\MSBuild\Current\Bin\Foo' is denied.
D:\Stuff\MSB4181.proj(6,5): warning MSB4181: The "Copy" task returned false but did not log an error.
    2 Warning(s)
    0 Error(s)

Time Elapsed 00:00:00.38
```

When ContinueOnError is set, I wouldn't expect to get this warning as errors were technically mutated to a warning.  When I saw this, a user had suppressed `MSB3021` but now their build fails because of the new warning.

**Comment by BenVillalobos** [comment]
Poking at this a little bit with `msbuild msbuild.dev.slnf` and cancelling at random times, I hit the same thing with `Csc`. Whatever the fix is should work with any task that's cancelled.

MSB4188 is never emitted, right?

**Comment by BenVillalobos** [comment]
@danmoseley I don't repro this issue. This may have been fixed with our various taskhost HasLoggedErrors PR's. Closing this in favor of https://github.com/dotnet/msbuild/issues/5912 which I think is a larger issue with tooltasks.
