### ISSUE TITLE
dotnet build does not discover generated files

### ISSUE THREAD

**Issue by jamers99** [dotnet/msbuild#5524]
We have a project structure that generates C# code from json in a PostBuild event. It works in VS, but it does not from the `dotnet build` command.

Here is the (simplified) build order
1. Generator
2. Server
    - PostBuild: runs the Generator project which inserts cs files into the Model project below
3. Model (builds generated cs files)
4. Consumer (project uses code from Model project)

The problem is that the first time it's built it fails because Consumer can't find the classes generated in the Model project. But the build logs clearly show the Server project's build (and PostBuild) completing before the Model project's build, and the Model project's build completing before the Consumer build runs.

The second time the build is run, it works, indicating that either the Consumer is not seeing the new Model, or when the Model project is built, it's not building the generated files.

From Visual Studio it works every time the first time (running a repo git clean in-between to delete all generated files).

**Comment by jamers99** [comment]
I've verified that the Model project is building the generated files. The issue is that the Consumer project is not seeing the updates to the Model project.

**Comment by BenVillalobos** [comment]
We'll need more information to help you on this. Can you create a small example project that reproduces this behavior?

**Comment by BenVillalobos** [comment]
So the issue here is the order in which things happen.

I suspect that at the time Model expands it's wildcards, the files are not generated.

How are you including the files from step 2 in step 3?

> I've verified that the Model project is building the generated files. 

How have you verified this?
