### ISSUE TITLE
[RAR as Service] Serialization of request into queue

### ISSUE THREAD

**Issue by ostorc** [dotnet/msbuild#5557]
This issue tracks part of issue #3139 (RAR as service). Target of this issue to create simple serialization of request into queue. This is not optimal approach to consuming requests, but will be done in reasonable time and will provide us with option to prepare tests for the execution of RAR task in RAR node.

Expected time: ~14 days

**Comment by AR-May** [comment]
This issue is no longer valid. RAR as a Service has been redesigned: #6192
