### ISSUE TITLE
GetAssemblyIdentity Is unable to get version info form exe files.

### ISSUE THREAD

**Issue by dpeter99** [dotnet/msbuild#5608]
### Issue Description
GetAssemblyIdentity Is unable to get version info form exe files. I want to get the version of my uotput exe that is build witht he dingle file publishing under net core 3.1. But I get the following error when trying to do so: 
```error MSB3441: Cannot get assembly name for "<FilePath>". Could not load file or assembly '<File>' or one of its dependencies. The module was expected to contain an assembly manifest.```

### Steps to Reproduce
Try to use the ``<GetAssemblyIdentity />`` build task with any exe (I tried it with my net core publised exe and git.exe) 

### Expected Behavior
I would expect msbuild to be able to extract the file version form files metadata.

### Analysis
I don't know if this exact build task is the best place to implement general file version extraction. Maybe a ``<GetFileMetadata>`` or  a simpler ``<GetFileVersion>`` task would be more suitable.

### Versions & Configurations
Win 10 version 1909
Microsoft (R) Build Engine version 16.7.0-preview-20330-08+96403c598 for .NET
VS 2019 Version 16.6.5

**Comment by BenVillalobos** [comment]
Team Triage: We believe this is by design. Have you tried using this on a managed `exe`? `git.exe` is unmanaged and therefore this task wouldn't work on such a binary.

**Comment by dpeter99** [comment]
I did try to use it in my original use case with a single file deployment of my net core app. Didn't work with that exe either.
Is there any way to get the file version atribute still if it is not a mangged exe?

**Comment by BenVillalobos** [comment]
Team Triage: Not really. FileVersionAttribute is a managed concept. You might be able to extract related information from the PE Header of an unmanaged executable. This may be of some use: https://docs.microsoft.com/en-us/windows/win32/api/winver/nf-winver-getfileversioninfoa
