### ISSUE TITLE
Incorrect zh-Hans XML documentation expression for Resx.Designer file generated by StronglyTypedResourceBuilder

### ISSUE THREAD

**Issue by CXuesong** [dotnet/msbuild#5636]
### Issue Description

This issue is actually a translation suggestion, but is also a bug/regression because the translation is worse than before.

The `xxx.Designer.vb` file generated from `xxx.resx`.by `StronglyTypedResourceBuilder` is using incorrect zh-Hans localized XML documentation for `xxx.Culture` property. (Assume `xxx` is the name of Resx file.)

### Steps to Reproduce

* Create a new Visual Basic / C# .NET Core console project on in Visual Studio 2019 on Windows with zh-CN locale
* Add a new Resx file to the project
* Open the corresponding `.Designer.vb/cs` file and check generated code
* As comparison, create a console project on Visual Studio 2013/2015 with the same steps above.

### Expected Behavior

This is the generated code on VS 2013/2015
```cs
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
```

### Actual Behavior

This is the generated code on VS 2019. Note the first line of `<summary>` is incorrect and is the duplicate of the second line.
```cs
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
```

### Analysis

I found this issue when migrating some old projects authored in VS 2013/2015 and this documentation change generates noises for version control system.

The code snippet above is generated by
https://github.com/dotnet/msbuild/blob/e8c17c128ed847d4acd278b42a02df9621bd1652/src/Tasks/system.design/stronglytypedresourcebuilder.cs#L454-L455

and the corresponding value in neutral locale is
https://github.com/dotnet/msbuild/blob/e8c17c128ed847d4acd278b42a02df9621bd1652/src/Tasks/system.design/system.design.txt#L19-L20

I haven't found the file hosting localized resources, so I open the issue in hope that the value of `CulturePropertyComment1` in zh-Hans locale can be corrected.

### Versions & Configurations

```powershell
PS > dotnet msbuild -version
Microsoft (R) Build Engine version 16.8.0-preview-20371-01+e8338f5ad for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

16.8.0.37101
PS > dotnet --list-sdks
1.1.13 [C:\Program Files\dotnet\sdk]
2.1.800 [C:\Program Files\dotnet\sdk]
2.2.104 [C:\Program Files\dotnet\sdk]
3.1.102 [C:\Program Files\dotnet\sdk]
3.1.400 [C:\Program Files\dotnet\sdk]
5.0.100-rc.1.20374.4 [C:\Program Files\dotnet\sdk]
PS > dotnet --version
5.0.100-rc.1.20374.4
```

**Comment by Forgind** [comment]
This doesn't seem to be the case any more in 16.8.0.41105:
```
/// <summary>
///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
///   使用這個強類型資源類別的資源查閱。
/// </summary>
```

(I'm assuming that's right, since the two lines look different.)

I'm guessing that either it was resolved more recently (hard to imagine unless your command line MSBuild version and your VS MSBuild version are different) or you got a version from between when the string changed and when the localized versions were produced—it sometimes takes a little time to get localized strings. If it's the latter, sorry about that! Can you try updating VS to the latest version and seeing if it works?

**Comment by BenVillalobos** [comment]
Tracking duplicated translation text here: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1180327

**Comment by cristianosuzuki77** [comment]
I'm the loc pm. I am investingating this issue as well.

**Comment by BenVillalobos** [comment]
Team Triage: Closing due to fix in later version of VS.
