### ISSUE TITLE
Regression in msbuild between VS 16.7.0 & the last 16.7 preview

### ISSUE THREAD

**Issue by Ninds** [dotnet/msbuild#5637]
HI

### Issue Description
When building C++/CLI dll targeting .NET Core 3.1 with msbuild of VS 16.7 we have the following error \:
```
"C:\WorkSpace\Project1\Project1\Project1.vcxproj" (default target) (1) ->
(_GetIjwHostPaths target) ->
  C:\Program Files\dotnet\sdk\5.0.100-preview.7.20366.6\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(585,5)
: error NETSDK1114: Unable to find a .NET Core IJW host. The .NET Core IJW host is only available on .NET Core 3.1 or h
igher when targeting Windows. [C:\WorkSpace\Project1\Project1\Project1.vcxproj]

    0 Warning(s)
    1 Error(s)
```
This error did not occur in the last 16.7 preview.

#### Environment
```
$ dotnet --list-runtimes
Microsoft.AspNetCore.All 2.1.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
Microsoft.AspNetCore.App 2.1.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 5.0.0-preview.7.20365.19 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.NETCore.App 2.1.20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 5.0.0-preview.7.20364.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.WindowsDesktop.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 5.0.0-preview.7.20366.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```
```
$ dotnet --list-sdks
3.1.302 [C:\Program Files\dotnet\sdk]
3.1.400 [C:\Program Files\dotnet\sdk]
5.0.100-preview.7.20366.6 [C:\Program Files\dotnet\sdk]
```
```
C:\WorkSpace\Project1\Project1>msbuild -version
Microsoft (R) Build Engine version 16.7.0+b89cb5fde for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

16.7.0.37604
```
[Reproducing Project File](https://gist.github.com/Ninds/7db8f055d8127bf0ebf50631d3b1dda8)

Targeting .NET 4.7.2 is ok 
Targeting .NET 5      is ok
Targeting .NET Core 3.1  is **NOT** ok

**Comment by Ninds** [comment]
Even switching of __use of previews of the .NET Core SDK__  doesn't fix the problem.

![preview](https://user-images.githubusercontent.com/5892035/89827470-8cd6ad00-db4f-11ea-9e7b-93d2f5ac835e.jpg)


```
1>C:\Program Files\dotnet\sdk\5.0.100-preview.7.20366.6\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(585,5): error NETSDK1114: Unable to find a .NET Core IJW host. The .NET Core IJW host is only available on .NET Core 3.1 or higher when targeting Windows.
```

**Comment by stic** [comment]
Same here, unable to target netcoreapp3.1 with .net core 5.0 preview installed.
I've tried to do some investigation (i.e. figure out how .net core targets are resolved during build), but even verbose build log doesn't explain much - suggestion, whilst providing fix it might be worth to improve build logging too. Cleaned everything cached internally under .vs, build outputs etc. By the way it's with VS16.7.1 (haven't tried 16.8 behaviour yet)

Workaround for now - remove preview 🤕

**Comment by Forgind** [comment]
At face value, this sounds like a "we expected .NET Core __ but got .NET __" type problem, fixed by teaching it that it should work with .NET 5, too. I had some difficulty with reproducing the problem, though. Here's what I tried:
I created a new vcxproj and replaced its content with the project you provided.
I used MSBuild 16.7.0.37604 (full framework) to build the project, but that worked (not too surprising)
I used Core MSBuild 16.7.0.36003 to try to build the project and reset VCTargetsPath to point to the relevant folder, but it still failed for an unrelated reason—failing to find Platform.props. What did I do wrong?

Also, given that the error message is NETSDK1114, I have a feeling this is a dotnet/sdk problem. Is that correct, @wli3/@dsplaisted?

**Comment by dsplaisted** [comment]
It's probably an issue with dotnet/sdk, though it's hard to say.  A [binlog](https://aka.ms/binlog) would be helpful to investigate this.

**Comment by Ninds** [comment]
I suspected MSBuild only because all other things being equal under the last VS 16.7 preview everything worked.
Specifically, building for target .NET Core 3.1 with .NET 5 preview 7 installed.  If .NET preview 7 is not installed there is no issue observed.  
When VS 16.7 preview was being used and .NET Core 3.1 & .NET 5 preview were installed and everything was working, the only change that was then made was to upgrade VS to 16.7 Release for msbuild to exhibit the error.

The binlog file is attached.

[msbuild.binlog.zip](https://github.com/dotnet/msbuild/files/5067344/msbuild.binlog.zip)

Thanks

**Comment by Ninds** [comment]
Having uninstalled .NET 5 Preview 7 i attach also the msbuild binlog of a successful build  :
[msbuild.binlog.zip](https://github.com/dotnet/msbuild/files/5067400/msbuild.binlog.zip)

Is it still possible to download the the last VS 16.7 preview ?

**Comment by wli3** [comment]
Assign it to me. I'll look into it.

**Comment by wli3** [comment]
Issue moved to [dotnet/sdk #12911](https://github.com/dotnet/sdk/issues/12911) via [**ZenHub**](https://www.zenhub.com/)

**Comment by Ninds** [comment]
@stic 

@dsplaisted got to resolved the issue (at least for me) and the work around was to install .NET Core 3.1.2 (side by side if necessary to any later 3.1 installs). The explanation is here : dotnet/sdk#12911
