### ISSUE TITLE
Cannot find nuget package if run dll using .targets in .Net 5

### ISSUE THREAD

**Issue by QuantumDeveloper** [dotnet/msbuild#5638]
### Issue Description
  `System.TypeInitializationException: The type initializer for 'Effects.EffectData' threw an exception.
 System.IO.FileNotFoundException: Could not load file or assembly 'protobuf-net, Version=3.0.0.0, Culture=neutral, PublicKeyToken=257b51d87d2e4d67'. The system cannot find the file specified.
File name: 'protobuf-net, Version=3.0.0.0, Culture=neutral, PublicKeyToken=257b51d87d2e4d67'
   at Effects.EffectData..cctor()

### Steps to Reproduce
I created custom .targets file run it through .Net 5 msbuild. It starts app, but when it tries to find protobuf-net.dll, it fails with exception above, but at the same time I can run test with the same class and it will work as expected.
This effect is present only when run app with custom .targets file.

### Ask us questions
How this issue could be worked around? Its quite important for me, because It is blocking me from running the project

**Comment by QuantumDeveloper** [comment]
Actually I even run into another issue:
![image](https://user-images.githubusercontent.com/6085009/89893780-a7f1fd00-dbe1-11ea-9e5b-247b878a7919.png)
I will attach small demo project to show this behavior.
[TargetsTest.zip](https://github.com/dotnet/msbuild/files/5056736/TargetsTest.zip)

**Comment by marcpopMSFT** [comment]
@BenVillalobos Looking up similar issues, this may be Gac related

**Comment by Forgind** [comment]
I tried to build TargetsTest from the command line, and I got the same error QuantumDeveloper did, so it probably isn't GAC-related.

**Comment by QuantumDeveloper** [comment]
Rider can build this using .Net 5 msbuild. Seems Visual studio MSBuild cannot define which runtime to use here, which is quite strange, because there is .Net 5 in all projects

**Comment by Forgind** [comment]
The error here was very confusing, but I don't think it should work. The EngineCompileTarget target in TargetsTest.targets specifies that it runs the EffectCompilerTask with input parameter Files and Output TaskParameters ContentFiles and CompiledFiles. The EffectCompilerTask doesn't reference either of the latter two. I haven't yet figured out why it would come up with the error you noticed, but that at least explains why it might fail.

**Comment by sidristij** [comment]
Also got this error. Have msbuild task + nuget. msbuild cannot find this nuget.
![image](https://user-images.githubusercontent.com/1454688/102776813-77487e00-43a0-11eb-904e-2b61790e9e05.png)

**Comment by Forgind** [comment]
I've looked into this more carefully. There's a ProjectReference from the CompilerTask to Worker, and Worker has a PackageReference to protobuf-net. If I copy protobuf-net.dll and protobuf-net.Core.dll into the output directory of CompilerTask, it works. I think there's a CopyToOutputDirectory thing; I'll try to find it.

**Comment by Forgind** [comment]
Did the workaround I suggested work for you?

**Comment by QuantumDeveloper** [comment]
> Did the workaround I suggested work for you?

Yes, workaround is working, but exactly the same usecase is working without any workarounds in Rider. Could you fix this bug in Visual studio please?

**Comment by Forgind** [comment]
Team triage: Rider uses `dotnet build` to build; Visual Studio doesn't. Your tasks target .net5.0, which is .NET Core, so it can be used in a .NET Core build, i.e., `dotnet build`, but not from msbuild.exe, which is what Visual Studio uses. Can you try multitargeting your task to target both net5.0 and net472?
