### ISSUE TITLE
clean VS2010 project with SSDT we get MSB4019

### ISSUE THREAD

**Issue by trivalik** [dotnet/msbuild#5673]
### Issue Description
I found that if solution file is for Visual Studio 2010 with project which include use of "SQL Server Data Tools" (SSDT). We get error MSB4019 to path "C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin
\SqlServer.targets" if we use current msbuild version by command: C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin\msbuild" /t:Clean Test.sln

In this case the project file with SSDT is also ToolsVersion 4.0. Only resave solution, which changes from csproj to sqlproj in solution file fix the issue.

### Steps to Reproduce
* extract the append test.zip and execute the "clean.bat" to show error MSB4019
* open with VS2019 (need SSDT installed) press reload of the include project (seems incompatible), this changes only the solution file, press save and now the "clean.bat" will work

[test.zip](https://github.com/dotnet/msbuild/files/5117806/test.zip)

### Expected Behavior
clean without error
### Actual Behavior
MSB4019
### Analysis
Update solution would fix it, in case this is a wont fix this could help others to understand the issue.
### Versions & Configurations
Msbuild 16.7.0+b89cb5fde
I tested it now also with 16.8.0-dev-20425-01+79ab985eb, same behavior.

**Comment by BenVillalobos** [comment]
Team Triage: We believe this isn't a bug with MSBuild. Please head over to https://aka.ms/vs-feedback and direct it to SSDT. Feel free to link to this issue as you file it.

**Comment by trivalik** [comment]
I would to, but since feedbacks have to be provided in a browser opened by VS2019, I am unable to do it. I was in contact with developer for it, but got after a few mails no further response. My last contact was on 6 August 2020. I am not sure if I should post his/her name her.
