### ISSUE TITLE
Graph build causes NETSDK1004 when restoring

### ISSUE THREAD

**Issue by atniomn** [dotnet/msbuild#5690]
### Issue Description

A solution contains two projects:
- Project A is a .NET Framework v4.7.2 project
- Project B is a .NET Standard 2.0 project

Project A references Project B
Project B references a NuGet package

When building the solution with /graph:false, everything succeeds as expected.
When building the solution with /graph:true, NETSDK1004 is raised and the build fails.

### Steps to Reproduce

Zip below includes a solution which reproduces the issue.
test.ps1 script runs MSBuild and takes an argument to disable or enable graph build.
After it finishes building, it *DELETES* the bin and obj folders of the two projects in the solution.
It deletes these folders, so the script can be run again successfully.

Success case (no graph build):
```
PS SdkRestoreTest> .\test.ps1
```

Failure case (graph build):
```
PS SdkRestoreTest> .\test.ps1 -GraphBuild $true
```

[SdkRestoreTest.zip](https://github.com/dotnet/msbuild/files/5139751/SdkRestoreTest.zip)

### Expected Behavior

MSBuild succeeds in building the solution, regardless of whether or not graph build is enabled

### Actual Behavior

MSBuild fails to restore the solution, when graph build is enabled

### Versions & Configurations

```
Microsoft (R) Build Engine version 16.6.0+5ff7b0c9e for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

16.6.0.22303
```

pwsh v7.0.3

**Comment by atniomn** [comment]
Actually, this seems like more of a documentation issue, I accidentally shot myself in the foot: [here](https://docs.microsoft.com/en-us/nuget/reference/msbuild-targets)


I need to refrain from using the separate target:
![image](https://user-images.githubusercontent.com/29003333/91516457-283a8280-e8b1-11ea-8cb7-d353f4f66c30.png)


I got confused by this section:

![image](https://user-images.githubusercontent.com/29003333/91516504-46a07e00-e8b1-11ea-850a-f6de2cc550f7.png)


which seems to imply running the restore target is fine, as long as you use PackageReference everywhere, but you also have to watch out for when you're running multiple targets. which is the *ONLY* time I run restore

**Comment by BenVillalobos** [comment]
Team Triage: Thanks for the report. The doc issue is now being tracked here: https://github.com/NuGet/docs.microsoft.com-nuget/issues/2149
