### ISSUE TITLE
add ReferenceOutputAssembly with mixed old/new project file type

### ISSUE THREAD

**Issue by trivalik** [dotnet/msbuild#5691]
### Issue Description
I just want to add a hint reference in old style project (<Project ToolsVersion="15.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">) to a new style project of "Microsoft.NET.Sdk". This new style project does not contain any files for build, just a copy and clean task with reference BeforeTargets: BeforeBuild and BeforeCompile. I heard that "ReferenceOutputAssembly" could be used to get rid of the solution dependency, so I want to give it a try.

If I execute "dotnet clean oldstyle.csproj" on the old style project, the clean operation is done but with "msbuild oldstyle.csproj -target:Clean" not. Same for building it.

Is project type mixing old/new supported?

new style project content:
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
  </PropertyGroup>

  <Target Name="CopyDLL" BeforeTargets="BeforeBuild">
    <Copy SourceFiles="x.dll" DestinationFolder="..\..\..\..\x\" ContinueOnError="false" OverwriteReadOnlyFiles="true" />
  </Target>
  <Target Name="CleanDLL" BeforeTargets="BeforeClean">
    <Delete Files="..\..\..\..\x\x.dll" />
  </Target>
</Project>
```

### Expected Behavior
Clean/Build of old style project works, but both do not if reference from old to new project type is done.

### Actual Behavior
Clean and Build is skipped in old style project.

### Analysis
Add ReferenceOutputAssembly have here no influence.

### Versions & Configurations
msbuild Version 16.7.0+b89cb5fde
.NET Core SDK (5.0.100-preview.8.20417.9)

**Comment by BenVillalobos** [comment]
Team Triage: Can you include the new and old project as well as a script with what you're doing here?

**Comment by trivalik** [comment]
I am right now not sure about exact circumstance. I tried to reproduce and it looks like that the issue was related to that in solution file the GUID for project is {9A19103F-16F7-4668-BE54-9A1E7A4F7556}. After remove and readd the project a new GUID was created (FAE04EC0-301F-11D3-BF4B-00C04F79EFBC) and it was then possible to build. It looks like information is in the GUID coded. Here the log what VS2019 reported with the first GUID: 
[VsProjectFault_fd0ee92f-3543-4007-8c58-a047776bebba.failure.txt](https://github.com/dotnet/msbuild/files/5186393/VsProjectFault_fd0ee92f-3543-4007-8c58-a047776bebba.failure.txt)
