### ISSUE TITLE
missing MinimumRecommendedRules.ruleset because of double backslash

### ISSUE THREAD

**Issue by trivalik** [dotnet/msbuild#5692]
### Issue Description
It looks like that after upgrade to 16.7.2 the msbuild behaves different in calculate the ruleset path:
```
/ruleset:"C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\Team Tools\Static Analysis Tools\\Rule Sets\MinimumRecommendedRules.ruleset
```

**see analysis**

### Steps to Reproduce
build a project in VS2019 or with Msbuild which has enabled the
my settings:

```
    <CodeAnalysisIgnoreBuiltInRuleSets>true</CodeAnalysisIgnoreBuiltInRuleSets>
    <CodeAnalysisIgnoreBuiltInRules>false</CodeAnalysisIgnoreBuiltInRules>
    <CodeAnalysisFailOnMissingRules>true</CodeAnalysisFailOnMissingRules>
```

### Expected Behavior
no warning

### Actual Behavior
warning MSB3884
### Analysis
seems to appear after upgrade to 16.7.2 of VS2019
**seems already in fixed in 16.8.0 Preview 2.0 or earlier preview**

### Attach a binlog

**Comment by Forgind** [comment]
I tried this with MSBuild 16.7.2 and 16.8.0 Preview 2.0, and I saw a warning for both. Can you clarify how you found that 16.8.0p2 works as expected? What version (before 16.7.2) also worked?

(Knowing this will help me find which change may have induced this problem.)

**Comment by trivalik** [comment]
Here is the test project which have warning with 16.7.0+b89cb5fde, but no warning with 16.8.0-preview-20411-05+9a32a8063
I would say the 16.7.1 version did not had this issue.
[TestWarning.zip](https://github.com/dotnet/msbuild/files/5186219/TestWarning.zip)

**Comment by Forgind** [comment]
I'm still having trouble seeing what you see. Building that project with 16.8 p2 (a slightly later version than yours still gave a warning:
![image](https://user-images.githubusercontent.com/12969783/92505604-2fb73100-f1b9-11ea-9a58-f7067cb6a49b.png)

On the other hand, if I explicitly specified the path to the ruleset by adding:
```
<CodeAnalysisRuleSet>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Team Tools\Static Analysis Tools\\Rule Sets\MinimumRecommendedRules.ruleset</CodeAnalysisRuleSet>
```

It was able to build with no warning despite the extra slash.
![image](https://user-images.githubusercontent.com/12969783/92505469-faaade80-f1b8-11ea-8cfd-9116a4eace4e.png)

Does that workaround work for you? I'm sorry this has been causing you trouble, but the file that tries to find the rule set (ResolveCodeAnalysisRuleSet.cs) hasn't been changed in the past few years, and I didn't see any change in behavior between versions when I tried the repro locally.

**Comment by trivalik** [comment]
The thing is that our CI server has the same issue. 16.8.0 Preview.3.0 still works.

Adding this workaround works, but I don't want:
```
  <PropertyGroup>
	<CodeAnalysisRuleSet>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\Team Tools\Static Analysis Tools\Rule Sets\MinimumRecommendedRules.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>
```


The output with -v:diag of 16.7.3

```
...
ResolveCodeAnalysisRuleSet-Aufgabe (Aufgaben-ID: 21)
  Aufgabenparameter:CodeAnalysisRuleSet=MinimumRecommendedRules.ruleset (Aufgaben-ID: 21)
  Aufgabenparameter:MSBuildProjectDirectory=D:\TestWarning (Aufgaben-ID: 21)
C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin\Microsoft.CSharp.CurrentVersion.targets(135,9): warning MSB3884: Regelsatzdatei "MinimumRecommendedRules.ruleset" konnte nicht gefunden werden. [D:\TestWarning\TestWarning.csproj]
Ausführen der ResolveCodeAnalysisRuleSet-Aufgabe beendet. (Aufgaben-ID: 21)
```

but in preview version is the ResolveCodeAnalysisRuleSet ignored:
```
Das Ziel "ResolveCodeAnalysisRuleSet" wurde übersprungen, da die Bedingung "false" war . ('$(CodeAnalysisRuleSet)' != '') wurde als ('' != '') ausgewertet.
```

Means "CodeAnalysisRuleSet" is in preview empty.

**Comment by Forgind** [comment]
I did some more digging, and here's what I found:
1. There isn't a default version defined in MSBuild or the SDK.
2. Roslyn explicitly specifies a location for the CodeAnalysisRuleSet.
3. ResolveCodeAnalysisRuleSet (in MSBuild) hasn't been touched for 6+ years, as I noted earlier, and its condition specifies that it won't run unless there is some value defined for $(CodeAnalysisRuleSet). See https://github.com/dotnet/msbuild/blob/0220c5eaeac8dd1770a597a7ba4306651c421bf4/src/Tasks/Microsoft.CSharp.CurrentVersion.targets#L132

Perhaps you used to have a custom .props or .targets file that gave you a default value?

**Comment by trivalik** [comment]
After searching I found that Microsoft.CodeAnalysis.Targets seems to set this variable.

Since in  -v:diag of 16.7.3

```
CleanFile = TestWarning.csproj.FileListAbsolute.txt
CmdUIContextGuid = {FAE04EC1-301F-11d3-BF4B-00C04F79EFBC}
CodeAnalysisApplyLogFileXsl = false
CodeAnalysisFailOnMissingRules = true
CodeAnalysisForceOutput = true
CodeAnalysisGenerateSuccessFile = true
CodeAnalysisIgnoreBuiltInRules = false
CodeAnalysisIgnoreBuiltInRuleSets = true
CodeAnalysisIgnoreGeneratedCode = true
CodeAnalysisIgnoreInvalidTargets = true
CodeAnalysisIgnoreMissingIndirectReferences = false
CodeAnalysisInputAssembly = Bin\Debug\TestWarning.dll
CodeAnalysisLogFile = Bin\Debug\TestWarning.dll.CodeAnalysisLog.xml
CodeAnalysisModuleSuppressionsFile = GlobalSuppressions.cs
CodeAnalysisOutputToConsole = false
CodeAnalysisOverrideRuleVisibilities = false
CodeAnalysisPath = C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\Team Tools\Static Analysis Tools\FxCop\
CodeAnalysisQuiet = false
CodeAnalysisRuleDirectories = ;C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\Team Tools\Static Analysis Tools\FxCop\\Rules
CodeAnalysisRuleSet = MinimumRecommendedRules.ruleset
CodeAnalysisSaveMessagesToReport = Active
CodeAnalysisSearchGlobalAssemblyCache = true
CodeAnalysisStaticAnalysisDirectory = C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\Team Tools\Static Analysis Tools\
CodeAnalysisSucceededFile = Bin\Debug\TestWarning.dll.lastcodeanalysissucceeded
CodeAnalysisSummary = false
CodeAnalysisTargets = C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Microsoft\VisualStudio\v16.0\CodeAnalysis\Microsoft.CodeAnalysis.targets
CodeAnalysisTimeout = 120
CodeAnalysisTreatWarningsAsErrors = false
CodeAnalysisUpdateProject = false
CodeAnalysisUseTypeNameInSuppression = true
CodeAnalysisVerbose = false
```

but in preview output is just the `CodeAnalysisRuleSet` assignment missing:

```
CleanFile = TestWarning.csproj.FileListAbsolute.txt
CmdUIContextGuid = {FAE04EC1-301F-11d3-BF4B-00C04F79EFBC}
CodeAnalysisApplyLogFileXsl = false
CodeAnalysisFailOnMissingRules = true
CodeAnalysisForceOutput = true
CodeAnalysisGenerateSuccessFile = true
CodeAnalysisIgnoreBuiltInRules = false
CodeAnalysisIgnoreBuiltInRuleSets = true
CodeAnalysisIgnoreGeneratedCode = true
CodeAnalysisIgnoreInvalidTargets = true
CodeAnalysisIgnoreMissingIndirectReferences = false
CodeAnalysisInputAssembly = Bin\Debug\TestWarning.dll
CodeAnalysisLogFile = Bin\Debug\TestWarning.dll.CodeAnalysisLog.xml
CodeAnalysisModuleSuppressionsFile = GlobalSuppressions.cs
CodeAnalysisOutputToConsole = false
CodeAnalysisOverrideRuleVisibilities = false
CodeAnalysisPath = C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\Team Tools\Static Analysis Tools\FxCop\
CodeAnalysisQuiet = false
CodeAnalysisRuleDirectories = ;C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\Team Tools\Static Analysis Tools\FxCop\\Rules
CodeAnalysisSaveMessagesToReport = Active
CodeAnalysisSearchGlobalAssemblyCache = true
CodeAnalysisStaticAnalysisDirectory = C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\Team Tools\Static Analysis Tools\
CodeAnalysisSucceededFile = Bin\Debug\TestWarning.dll.lastcodeanalysissucceeded
CodeAnalysisSummary = false
CodeAnalysisTargets = C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Microsoft\VisualStudio\v16.0\CodeAnalysis\Microsoft.CodeAnalysis.targets
CodeAnalysisTimeout = 120
CodeAnalysisTreatWarningsAsErrors = true
CodeAnalysisUpdateProject = false
CodeAnalysisUseTypeNameInSuppression = true
CodeAnalysisVerbose = false
```

but  I cannot see evalutation of condition in this Microsoft.CodeAnalysis.targets file:

```
<When Condition="!Exists('$(CodeAnalysisRuleSet)') and ('$(CodeAnalysisVSSku)'=='Express' or ('$(CodeAnalysisRules)'=='' and '$(CodeAnalysisRuleAssemblies)'=='' and '$(CodeAnalysisRuleSet)'==''))">
```

**Comment by trivalik** [comment]
I found the difference!!! 

In preview MSBuild\Microsoft\VisualStudio\v16.0\CodeAnalysis\Microsoft.CodeAnalysis.Targets is this *missing*:
```
          <Otherwise>
              <PropertyGroup>
                <CodeAnalysisRuleSet>MinimumRecommendedRules.ruleset</CodeAnalysisRuleSet>
              </PropertyGroup>
          </Otherwise>
```

**Comment by Forgind** [comment]
Ah, this actually explains a lot! I was very confused because changing the version of _MSBuild_ didn't affect anything because we don't own that. With some digging, I found the commit that removed it, but its message wasn't terribly illuminating. I can message the dev who wrote that and see what his rationale was, though. Nice digging!

**Comment by mavasani** [comment]
The rulesets shipping in VS along with FxCop are legacy, and will be completely removed from VS in next major release. Are you still running the deprecated binary/legacy FxCop for your analysis? If so, you should consider migrating to analyzers instead: https://docs.microsoft.com/visualstudio/code-quality/migrate-from-legacy-analysis-to-fxcop-analyzers?view=vs-2019. Also see https://docs.microsoft.com/visualstudio/code-quality/configure-fxcop-analyzers?view=vs-2019

**Comment by trivalik** [comment]
We do not use it at all. It was just found the behavior changed. Seems that few older projects have set this random.
