### ISSUE TITLE
Docker msbuild fails when target is Metrics under docker

### ISSUE THREAD

**Issue by SeshagiriSriram** [dotnet/msbuild#5693]
### Issue Description
Calling the following 
`dotnet msbuild /t:Metrics`
in a docker image based on : mcr.microsoft.com/dotnet/core/sdk:3.1 
fails with following error: 

![image](https://user-images.githubusercontent.com/3693855/91577397-40200e00-e966-11ea-822f-a0dd02eab6fc.png)

### Steps to Reproduce
Attached CSPROJ file is shown below: 
```
  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <Platforms>AnyCPU;x64</Platforms>
    <CodeAnalysisRuleSet>TestCICD.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.FxCopAnalyzers" Version="3.3.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.CodeAnalysis.Metrics" Version="3.3.0" >
    <PackageReference Include="Microsoft.CodeQuality.Analyzers" Version="3.3.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
</Project>
```
Code is invoked as 

`dotnet msbuild /t:Metrics`
`
### Expected Behavior
Metrics.xml file should be generated. 

### Actual Behavior
It works on Windows 10/Linux (non Docker). When this is part of a docker script e.g. 

`RUN dotnet msbuild /t:Metrics`

it fails with the error listed in 1st section. 

### Ask us questions
There is a generated Metrics.exe file found here: 
![image](https://user-images.githubusercontent.com/3693855/91578087-5084b880-e967-11ea-800c-2430f63bfbae.png)

It does nothing - no error - no file generated. Note that this is an issue only on docker - standalone machines do not seem to have this issue. 

- Is the issue related to the docker image and if yes, what image really works? 
- Is there a an alternative to generate code metrics for C# code as part of CI/CD?

**Comment by BenVillalobos** [comment]
Team Triage: It looks like that's a windows executable. Moving this where the package is defined.

**Comment by rainersigwald** [comment]
This issue was moved to dotnet/roslyn-analyzers#4118
