### ISSUE TITLE
Published output contains xml doc files from referenced packages

### ISSUE THREAD

**Issue by njannink** [dotnet/msbuild#5696]
**Issue**
My published output (aspnetcore web project) contains the xml documentation files of referenced packages. I have the `<GenerateDocumentationFile>true</GenerateDocumentationFile>`, because I need the xml documentation files of my own projects for the Swagger OpenAPI documentation. What I don't need is for example the 3MB documentation file from `System.Reactive`.

Is there any way to exclude the documentation files of referenced packages? Otherwise it might be good to extend the `ExcludeAssets` list with an option for xml documentation files,

`<PackageReference Include="System.Reactive" Version="4.4.1" ExludeAssets="xmldoc" />`

**Comment by BenVillalobos** [comment]
@nkolev92 Is there a way to selectively generate documentation files on packagereferences? Or to exclude the documentation from specific packagereferences?

**Comment by dsplaisted** [comment]
Can you share a repro project or a [binlog](https://aka.ms/binlog) of a build where this happens?
