### ISSUE TITLE
TargetPlatformIdentifier is not inferred for .NET Core C++/CLI Projects - prevents successful builds

### ISSUE THREAD

**Issue by vatsan-madhavan** [dotnet/msbuild#5709]
`TargetPlatformIdentifier` is not inferred in .NET Core C++/CLI projects correctly. This affects (a) restore of C++/CLI .vcxproj and (b) creation of a new .NET Core C++/CLI .vcxproj in Visual Studio. 

In both instances, the problem looks like this: 

Restore log: 
> C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(93,5): error MSB4184: The expression "[Microsoft.Build.Utilities.ToolLocationHelper]::GetPlatformSDKLocation('', 10.0.19041.0)" cannot be evaluated. Parameter "targetPlatformIdentifier" cannot have zero length. [D:\src\repos\wpf\src\Microsoft.DotNet.Wpf\src\System.Printing\System.Printing.vcxproj]

New Project creation failure: 

![HMF6WMg0ke](https://user-images.githubusercontent.com/20246435/92186731-87961680-ee0c-11ea-8cba-0099fe2a234a.gif)

The project actually gets created - it just *seems* like a failure. It's possible to open the project in Visual Studio. Trying to **build** the project leads to failure again - 

>Build started...
1>------ Build started: Project: CppCliClassLibrary3, Configuration: Debug Win32 ------
1>The expression "[Microsoft.Build.Utilities.ToolLocationHelper]::GetPlatformSDKLocation('', 10.0.19041.0)" cannot be evaluated. Parameter "targetPlatformIdentifier" cannot have zero length.  C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets
1>Error: The expression "[Microsoft.Build.Utilities.ToolLocationHelper]::GetPlatformSDKLocation('', 10.0.19041.0)" cannot be evaluated. Parameter "targetPlatformIdentifier" cannot have zero length.  C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

==

I believe this is a regression introduced by #5624 (/cc @sfoslund). 

In addition to generically blocking C++/CLI scenarios from working well with .NET 5, I also predict that this will impede [dotnet/wpf](https://github.com/dotnet/wpf)'s ability to update its repo-wide `global.json` to point to a newer version of the .NET 5 SDK. 

/cc @ryalanms, @dsplaisted, @richaverma1

**Comment by wli3** [comment]
Why targetplatformversion need to get set for c++/CLI? Only thing it does is to get cswinrt, which is c# projection.

**Comment by wli3** [comment]
Weird. A created project can build. But not in new project.

**Comment by wli3** [comment]
@vatsan-madhavan this is rc1 build?

**Comment by vatsan-madhavan** [comment]
> Weird. A created project can build. But not in new project.

I suspect that a **restored** project can build.

**Comment by wli3** [comment]
No repro for the latest val build. This bug does exist in older version.
![cppcli](https://user-images.githubusercontent.com/6993335/92201406-524fef80-ee31-11ea-8696-cd231d0be79c.gif)

**Comment by vatsan-madhavan** [comment]
What about it makes it a no-repro? I mean, where is the TargetPlatformIdentifier being set ?

**Comment by vatsan-madhavan** [comment]
So #5624 changed the logic and added an extra check for `$(_EnableDefaultWindowsPlatform) != false`

https://github.com/dotnet/msbuild/blob/c7790e1ed37c2e6cb4fc38e76c06ed1fb15d3148/src/Tasks/Microsoft.Common.CurrentVersion.targets#L89


In [Microsoft.NET.TargetFrameworkInference.targets@L161-L165](https://github.com/dotnet/sdk/blob/fa41a211d36cf5c7cf918113d6d0397ba718f08a/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.TargetFrameworkInference.targets#L161-L165), I see this **at present**: 

```xml
  <!--C++/CLI has its own logic of determine TargetPlatformIdentifier and TargetPlatformVersion-->
  <PropertyGroup Condition="'$(TargetFrameworkIdentifier)' == '.NETCoreApp' and $([MSBuild]::VersionGreaterThanOrEquals($(TargetFrameworkVersion), 5.0)) and '$(Language)' != 'C++'">
    <_EnableDefaultWindowsPlatform>false</_EnableDefaultWindowsPlatform>
    <UseOSWinMdReferences>false</UseOSWinMdReferences>
  </PropertyGroup>
```

In the version of the SDK where I encountered the bug, this is what I saw though:

```xml
  <PropertyGroup  Condition="'$(TargetFrameworkIdentifier)' == '.NETCoreApp' and $([MSBuild]::VersionGreaterThanOrEquals($(TargetFrameworkVersion), 5.0))">
    <_EnableDefaultWindowsPlatform>false</_EnableDefaultWindowsPlatform>
    <UseOSWinMdReferences>false</UseOSWinMdReferences>
  </PropertyGroup>
```

That probably explains the fact that the bug is fixed - the current version of the SDK has a condition that looks for `$(Language) != 'C++'` before settings `_EnableDefaultWindowsPlatform=false`. This didn't happen in older SDK's - thus the bug.

**Comment by dsplaisted** [comment]
This should be fixed in RC1.  #13111 is the PR that fixed it.
