### ISSUE TITLE
Pack - Only packs UWP target when OutputPath is specified

### ISSUE THREAD

**Issue by PieterjanDeClippel** [dotnet/msbuild#5721]
### Issue Description
I'm trying to build a Multi-target NuGet package for Xamarin.Forms.

When running the following command:

    C:\path\to\source\repos\Company.Xamarin.Alert>msbuild /t:Pack /p:Configuration=Debug Library/Company.Xamarin.Alert/Company.Xamarin.Alert.csproj

The produced nupkg can be installed in each project of a Xamarin.Forms application, and platform-specific code can be called.

However, when running the same command with the `p:OutputPath` parameter specified:

     C:\path\to\source\repos\Company.Xamarin.Alert>msbuild /t:Pack /p:Configuration=Debug /p:OutputPath=../.. Library/MintPlayer.Xamarin.Alert/MintPlayer.Xamarin.Alert.csproj

The resulting `nupkg` only contains the definitions for the UWP target.

### Steps to Reproduce

    git clone https://github.com/MintPlayer/MintPlayer.Xamarin.Alert
    cd MintPlayer.Xamarin.Alert
    msbuild /t:Restore
    msbuild /t:Pack /p:Configuration=Debug /p:PackageVersion=1.0.0 Library/MintPlayer.Xamarin.Alert/MintPlayer.Xamarin.Alert.csproj
    msbuild /t:Pack /p:Configuration=Debug /p:OutputPath=../.. /p:PackageVersion=1.0.1 Library/MintPlayer.Xamarin.Alert/MintPlayer.Xamarin.Alert.csproj
    copy Library\MintPlayer.Xamarin.Alert\bin\Debug\MintPlayer.Xamarin.Alert.1.0.0.nupkg .
    dotnet nuget add source %cd% --name TestPackages

Now you can install version 1.0.0 (the one built with outputpath) or version 1.0.1 (the one built without outputpath) in a xamarin.forms project.

All targets for version 1.0.0 only contain the UWP declarations, The targets for version 1.0.1 contain the declarations for the dedicate target.

### Expected Behavior
Specifying the outputpath should also pack all target dll's in the nuget package.

### Actual Behavior
Installing the nuget package in Android, iOS and UWP projects only makes the UWP declarations available for all platforms.

**Comment by BenVillalobos** [comment]
Team Triage: It looks like you're setting `OutputPath` as a global property. As a result, it will apply to every project, including the different target frameworks for your library. In general, It's not safe to pass `OutputPath` on the command line. You might want to specify `OutputPath` within a `Directory.Build.targets` file based on a new property that you define and specify that on the command line.
