### ISSUE TITLE
.NET Core project doesn't work inside a file path with '%20' characters.

### ISSUE THREAD

**Issue by lifengl** [dotnet/msbuild#5727]
There are some msbuild logic unescapes strings incorrectly, and when a NET Core project is put inside a folder with '%20' in the name, several things are broken down:

1, globbing doesn't seem to work, files inside the project cone are no longer picked up

2, properties like ProjectAssetsFile is computed with a wrong path (where %20 has been expanded to a space character).

**Comment by lifengl** [comment]
It is coming from feedback like this one: https://developercommunity.visualstudio.com/content/problem/1156262/folder-name-with-20-causes-references-in-project-t.html

**Comment by rainersigwald** [comment]
Duplicate of #2178
