### ISSUE TITLE
MSBuild's Publish Target does not see AdditionalFile added to project through a NuGet package's target file.

### ISSUE THREAD

**Issue by Delpire** [dotnet/msbuild#5733]
### Issue Description
I have some code analysis in a NuGet package that gets added to my project. Part of that NuGet package is a targets file that has some properties that point to the location of a dictionary for acceptable spellings.

During `dotnet publish` (which I assume does an MSBuild Publish target), the dictionary cannot be found, and my build fails because I treat warnings as errors.

Everything works correctly using Build, its only the Publish task that fails.

### Steps to Reproduce
1. NuGet package that pulls in a target file, that includes a property pointing to the dictionary. It looks something like this:
```
<PropertyGroup>
    <MyDictionary>$(SolutionDir)\CodeAnalysisDictionary.xml</MyDictionary>
</PropertyGroup>

<ItemGroup>
    <AdditionalFiles Include="$(MyDictionary)" Condition="Exists('$(MyDictionary)')"/>
</ItemGroup>
```
2. Include NuGet package as PackageReference to my project.
3. Run the following dotnet publish command:
```
dotnet publish -r win-x64 -c "Release" --output "C:\Users\chris\source\repos\MyRepo\src\UI\obj\desktop\--win\bin" /p:PublishReadyToRun=true --self-contained
```

### Expected Behavior
Publish occurs without warnings.

### Actual Behavior
My build fails because I treat warnings as errors for Release, and I get warnings related to things being misspelled, which my AdditionalFiles dictionary should fix.

### Analysis
I have tried explicitly putting the AdditionalFiles property in my csproj and using the copy to publish directory, but that shouldn't make a difference. It should see the property from the NuGet file, and resolve the SolutionDirectory.

I have other AdditionalFiles in that target file that appear to be working. The only difference is they reference directories within the NuGet package, **not the SolutionDirectory**. I feel like its possible the SolutionDirectory property does not work with dotnet publish.

### Versions & Configurations
VS2019
Microsoft (R) Build Engine version 16.6.0+5ff7b0c9e for .NET Framework
dotnet version 3.1.300
Windows 10

**Comment by Delpire** [comment]
Okay so I tried replacing $(SolutionDir) with a hardcoded path, and everything worked. So I believe MSBuild Publish does not know about the $(SolutionDir).

**Comment by BenVillalobos** [comment]
Team Triage: Because you're building an individual project and not a solution, the `$(SolutionDir)` property won't be defined. If you own this NuGet package, try avoiding use of `$(SolutionDir)`, as you won't know what context it will be used in.

Here are some options:
1. Require your users to define a property such as `$(RepoRoot)`, and use that in the package. Error if not set.
2. Package the dictionary in the NuGet package.
3. Depending on your use case, do you need a NuGet package for this? Can you accomplish your goals with `Directory.Build.props` in your repo?

**Comment by Delpire** [comment]
@BenVillalobos thank you for the response. Option 1 seems like our best bet. 

It makes sense that `$(SolutionDir)` would not be populated. I think it is safe to close this issue.
