### ISSUE TITLE
The <PackageReference /> is incorrect when building for multi-target platform

### ISSUE THREAD

**Issue by DingpingZhang** [dotnet/msbuild#5735]
### Issue Description

I want to build a WPF project separately for X64 and x86, and they will refer to different packages, *.csproj file like below:

```xml
  <Platforms>x64;x86</Platforms>

  <ItemGroup Condition="'$(Platform)'=='x64'">
    <ProjectReference Include="..\ClassLibrary.x64\ClassLibrary.x64.csproj" />
    <PackageReference Include="DotNetBrowser64" Version="1.21.5" />
  </ItemGroup>
  <ItemGroup Condition="'$(Platform)'=='x86'">
    <ProjectReference Include="..\ClassLibrary.x86\ClassLibrary.x86.csproj" />
    <PackageReference Include="DotNetBrowser32" Version="1.21.5" />
  </ItemGroup>
```

If I build with Visual Studio 2019, and output files will be exactly correct. But when I use the following command in `Developer PowerShell for VS 2019`, it will references `DotNetBrowser64` package for the x86 project: (On my other machine,  it will reference `DotNetBrowser32` package for the x64 project)

```cmd
// In *.sln file dir
> msbuild -p:Configuration='Release' -p:Platform='x86' -t:Rebuild

// Version Info
> msbuild -version
< Microsoft (R) Build Engine version 16.7.0+b89cb5fde for .NET Framework
< Copyright (C) Microsoft Corporation. All rights reserved.
```

`<ProjectReference />` (`ClassLibrary.x86.dll`) is correct, but `<PackageReference />` (`DotNetBrowser64.dll`) is incorrect:

![image](https://user-images.githubusercontent.com/8541016/92986050-a66e6a00-f4ea-11ea-823b-9bb890ebc4da.png)

### Steps to Reproduce

1. New WPF project in VS2019, and migrate to sdk-style *.csproj by [CsprojToVs2017](https://github.com/hvanbakel/CsprojToVs2017).
2. Modify the *csproj file to import some package, see attachment for detail.
3. Build by VS2019 and `msbuild` commands respectively.

### Expected Behavior

When built with MSBuild in cmd, powershell or cake script, it can output the same results as the VS2019 GUI build.

### Versions & Configurations

- VS: Microsoft Visual Studio Enterprise 2019 Version 16.7.3
- MSBuild: Microsoft (R) Build Engine version 16.7.0+b89cb5fde for .NET Framework

![image](https://user-images.githubusercontent.com/8541016/92986366-b6874900-f4ec-11ea-8f69-2fff5e1f6e05.png)

### Attach

Mini reproduction demo: [MultiTargetErrorMiniDemo.zip](https://github.com/dotnet/msbuild/files/5212139/MultiTargetErrorMiniDemo.zip)

**Comment by BenVillalobos** [comment]
Team Triage: Nuget doesn't support conditional references on anything other than `TargetFramework`. Try adding `-restore` to the msbuild command line.

**Comment by DingpingZhang** [comment]
> Try adding -restore to the msbuild command line.

@BenVillalobos Thanks for your suggestion! it works for me.
