### ISSUE TITLE
Cant build after updating my NETFramework Version

### ISSUE THREAD

**Issue by TheRod1990** [dotnet/msbuild#5747]
### Issue Description

Hey there, i actually cant rebuild my program, which is compiled with MSBuild. 
Right now im getting this errormessage: 

Microsoft.Bcl.Build.targets(243, 5): Could not locate C:\Users\Daniel.Beller\projects\Enerlisa\Energieportal.DataAccess\packages.config.  Ensure that this project has Microsoft.Bcl.Build installed and packages.config is located next to the project file.

This happened after i renewed my NETFramework Version.
I'll be glad for help.

Thank you.

### Steps to Reproduce

Intellij Rider Log: 

"C:\Users\Daniel.Beller\projects\Enerlisa\Energieportal.DataAccess\Energieportal.DataAccess.csproj" (GetTargetPath target) (3:2) ->
       (BclBuildValidateNugetPackageReferences target) -> 
         C:\Users\Daniel.Beller\.nuget\packages\microsoft.bcl.build\1.0.21\build\Microsoft.Bcl.Build.targets(243,5): error : Could not locate C:\Users\Daniel.Beller\projects\Enerlisa\Energieportal.DataAccess\packages.config.  Ensure that this project has Microsoft.Bcl.Build installed and packages.config is located next to the project file.

### Expected Behavior

This Error should be skipped or ignored in order to build correctly.

### Actual Behavior

This Error Message appears and my program cant be build

### Ask us questions

Can you help me with figuring out on how to fix that behavior?

**Comment by BenVillalobos** [comment]
Team Triage: 
1. What exactly does it mean to update your `NETFramework` here? 
1. Does this only happen in Rider?
1. Does this happen on the command line with msbuild.exe?
1. Can you [provide a binlog](https://github.com/dotnet/msbuild/blob/master/documentation/wiki/Providing-Binary-Logs.md)?

**Comment by rainersigwald** [comment]
Team triage: closing due to lack of response. If you're still seeing this please let us know.
