### ISSUE TITLE
Move StreamJsonRpc and dependencies to a folder under MSBuild\bin

### ISSUE THREAD

**Issue by rainersigwald** [dotnet/msbuild#5752]
It came up internally that because the MSBuild bin folder is added to the default `{AssemblyFoldersEx}` reference location in Visual Studio, assemblies from MSBuild can collide with VS assemblies when referenced by simple name.

We can instead move the assemblies to a folder and add entries for them in our app.config to locate them at runtime.

**Comment by mgoertz-msft** [comment]
@rainersigwald Any update on when this will get fixed in 16.8?

**Comment by Forgind** [comment]
We currently expect it to be fixed with https://github.com/dotnet/msbuild/pull/5758, so as soon as we've added the tactics template and seen what they say + a couple days.

**Comment by mgoertz-msft** [comment]
Thank you @Forgind!
