### ISSUE TITLE
GetTargetPlatformIdentifier Returning  empty values for netcoreapp3.1-Windows & netcoreapp3.1-Unix

### ISSUE THREAD

**Issue by Anipik** [dotnet/msbuild#5769]
### Issue Description

GetTargetPlatformIdentifier is returning empty values for input ``` netcoreapp3.1-Windows & netcoreapp3.1-Unix```
It returns the correct values for net5.0-Windows & net5.0-Unix

### Steps to Reproduce
 ```xml
  <Target Name="TestParsing">
    <PropertyGroup>
      <TestStringNet50Windows>$([MSBuild]::GetTargetPlatformIdentifier('net5.0-Windows'))</TestStringNet50Windows>
      <TestStringNet50Unix>$([MSBuild]::GetTargetPlatformIdentifier('net5.0-Unix'))</TestStringNet50Unix>
      <TestStringNet31Windows>$([MSBuild]::GetTargetPlatformIdentifier('netcoreapp3.1-Windows'))</TestStringNet31Windows>
      <TestStringNet31Unix>$([MSBuild]::GetTargetPlatformIdentifier('netcoreapp3.1-Unix'))</TestStringNet31Unix>
    </PropertyGroup>
    <Message Importance="High" Text="net5.0-Windows $(TestStringNet50Windows)"/>
    <Message Importance="High" Text="net5.0-unix $(TestStringNet50Unix)"/>
    <Message Importance="High" Text="netcoreapp3.1-Windows $(TestStringNet31Windows)"/>
    <Message Importance="High" Text="netcoreapp3.1-Unix $(TestStringNet31Unix)"/> 
  </Target>
```

### Expected Behavior
  net5.0-Windows Windows
  net5.0-unix Unix
  netcoreapp3.1-Windows Windows
  netcoreapp3.1-Unix Unix

### Actual Behavior
```
  net5.0-Windows Windows
  net5.0-unix Unix
  netcoreapp3.1-Windows
  netcoreapp3.1-Unix
```

cc @ericstj @ViktorHofer @safern

**Comment by safern** [comment]
cc: @rainersigwald

**Comment by safern** [comment]
I guess this is by design, as tfms earlier than net5.0 didn't support TargetPlatformIdentifiers, the tfms were always `netcoreappX` without a platform and then you published for the RID you wanted, but in 5.0 we added support for platforms like, `net5.0-windows` (WPF/Winforms app), or `net6.0-android`.

**Comment by rainersigwald** [comment]
@sfoslund @zkat can y'all confirm or deny that theory?

**Comment by sfoslund** [comment]
Yes, that's right, netcoreapp3.1-{ platform } is not a valid target framework.
