### ISSUE TITLE
Invalid Child Element at wrong level

### ISSUE THREAD

**Issue by Forgind** [dotnet/msbuild#5773]
### Issue Description
Putting an property inside a target without a property group gives a confusing error.

### Steps to Reproduce

Put a property inside a target without an enclosing PropertyGroup and build.

### Expected Behavior

Error informing me that `<propertyName>` is an invalid child element of `<Target>`.

### Actual Behavior

`Microsoft.Build.Exceptions.InvalidProjectFileException : The element <#text> beneath element <propertyName> is unrecognized.`

**Comment by JaynieBai** [comment]
In my view, the difficulties on the issues are how to distinguish property and task under the target.
