### ISSUE TITLE
Performance problems with large winforms project -- with repro

### ISSUE THREAD

**Issue by msneijders** [dotnet/msbuild#5776]
**Visual Studio Version**:
16.8.0 Preview 3.2

**Summary**:
In a "large" winforms project (500+ forms/usercontrols) the project becomes not workable because of performance problems. I added a generated project with a large amount of (empty) forms to show the problem.

Commands like "Add new class" in this project takes on my machine about 19 seconds to complete. "Deleting" this class file takes 36 seconds.

These timings seem to be linearly dependent on the amount of forms/usercontrols in the project. In my actual large LOB winforms project, which contains about half of the forms/usercontrols, these commands take resp. 9 and 17 seconds.

[LargeWinforms.zip](https://github.com/dotnet/project-system/files/5323385/LargeWinforms.zip)

I added a class "Form.cs" to the root of this project, this class subtypes System.Windows.Forms.Form and marks it with DesignerCategory("code").

If you include this Form.cs in the project, and wait for the background process to complete. Now the performance problems are gone: adding the new class is fast. You can visibly see the difference in the file 'PerformanceProblem1.csproj.user' -- it will have no more <SubType> entries for each Form.

**Steps to Reproduce**:

1. Open the uploaded solution.

2. Add new class to the root folder.

3. Delete this new file from the root folder.

**Expected Behavior**:
I expect simple commands like "Add new class" to take at most 2 seconds. My LOB project is migrated from an "old-style" project using NET471 -- in this project it takes less than 2 seconds for adding and deleting (tested with the same Visual Studio version).

**Actual Behavior**:
Adding a new class takes, depending on the amount of forms, 19 seconds. And deleting it twice as long.

**User Impact**:
This winforms project is unusable for my team -- I will not be able to convince any of my team to migrate to .NET5.0.

**Comment by Forgind** [comment]
Added untriaged label to make sure we pick it up in the bug triage meeting.
