### ISSUE TITLE
[loc][query] Assistance with translation

### ISSUE THREAD

**Issue by cristianosuzuki77** [dotnet/msbuild#5779]
String Resource ID | 0; "GenerateLauncher.EmptyEntryPoint"
-- | --
Source String | MSB3966: EntryPoint input parameter cannot be empty in the GenerateLauncher task.
Subtenant | OSS_MSBuild
Source Control Link |  
Filename | Tasks\Resources\xlf\Strings.xlf
Question | According to the instruction - Dev={StrBegin="MSB3965: "}, the string should start with MSB3965. But there is a string starting with MSB3965 as below. MSB3965: No output path specified in build settings. So we assume that this DevComment is outdated. We translated it as source for now. Please check it.

**Comment by rainersigwald** [comment]
cc @sujitnayak. I think we removed that string so it doesn't really matter, but I agree that translating as source sounds good.

**Comment by cristianosuzuki77** [comment]
Thank you.
