### ISSUE TITLE
[loc][query] Assistance with translation.

### ISSUE THREAD

**Issue by cristianosuzuki77** [dotnet/msbuild#5785]
String Resource ID | 0; "ChangeWave_InvalidFormat"
-- | --
Source String | Environment variable MSBUILDDISABLEFEATURESFROMVERSION is set to an invalid format. Enabling all change wave versions. Entered value: {0}.
Subtenant | OSS_MSBuild
Source Control Link |  
Filename | Build\Resources\xlf\Strings.xlf
Question | Please clarify change wave. Translated as change flow for the time being

**Comment by cristianosuzuki77** [comment]
VCQ 318318

**Comment by BenVillalobos** [comment]
Taken from the docs [here](https://github.com/dotnet/msbuild/blob/master/documentation/wiki/ChangeWaves.md)
> A Change Wave is a set of risky features developed under the same opt-out flag. This flag happens to be the version of MSBuild that the features were developed for. The purpose of this is to warn developers of risky changes that will become standard functionality down the line.

Is this what you need?
