### ISSUE TITLE
msbuild Xamarin.Forms apk corrupts and reduces size

### ISSUE THREAD

**Issue by sergey19941201** [dotnet/msbuild#5794]
We use GA for CI/CD in Xamarin.Forms solution to deliver Android apks. It was restoring/building release apk 37MB size up to 25st of August 2020. Everything was working perfect at least at 21st of August. But starting from 25st of August size of built apk was 24.8MB and this apk became corrupted. The problem is still actual at the moment. We changed nothing that can result size reducing and apk corruption.

```
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.0
    - uses: nuget/setup-nuget@v1
 
    - name: Droid nuget restore and build
      run: |
        nuget restore
        cd MySolution
        cd MySolution.Droid
        msbuild MySolution.Droid.csproj /verbosity:normal /t:SignAndroidPackage /p:Configuration=Release 
```

If I execute exactly the same command from a command line on my local Windows machine, apk builds correctly and has 37MB size. So currently I have no idea how to fix this issue.

**Comment by BenVillalobos** [comment]
Team Triage: This seems like more of a xamarin issue than an msbuild issue, please file your issue here: https://github.com/xamarin/xamarin-android/issues
