### ISSUE TITLE
 The "GetReferenceNearestTargetFrameworkTask" task was not found

### ISSUE THREAD

**Issue by kAvItHa-cL** [dotnet/msbuild#5801]
I am trying to add netstandard2.0 project reference to netcoreapp3.1 project and build but getting error like this.

Project:

<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <Folder Include="Controllers\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BusinessLayer\BusinessLayer.csproj" />
    <ProjectReference Include="..\Entity\Entity.csproj"/>
     </ItemGroup>
</Project>

C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(1655,5): error MSB4036: The "GetReferenceNearestTargetFrameworkTask" task was not found. Check the following: 1.) The name of the task in the project file is the same as the name of the task class. 2.) The task class is "public" and implements the Microsoft.Build.Framework.ITask interface. 3.) The task is correctly declared with <UsingTask> in the project file, or in the *.tasks files located in the "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin" directory

**Comment by rainersigwald** [comment]
Can you share your projects or a standalone repro of this problem? Can you build other projects? What workloads do you have installed in that Visual Studio Community?

**Comment by Forgind** [comment]
Closing for lack of response.
