### ISSUE TITLE
MSB3644 says .NETFramework version 5

### ISSUE THREAD

**Issue by timheuer** [dotnet/msbuild#5807]
### Issue Description
When attempting to use `dotnet build` on a .NET 5 project when the SDK is not present it shows a weird error message with terminology that isn't branding correct:

```
error MSB3644: The reference assemblies for .NETFramework,Version=v5.0 were not found.
```
Observe `.NETFramework,Version=v5.0`

I would not expect this to say '.NETFramework'

**Comment by rainersigwald** [comment]
We started working on this issue as #5826 before we saw this one, sorry.

**Comment by rainersigwald** [comment]
Duplicate of #5826
