### ISSUE TITLE
Project builds for a 3rd party VS language integration (Synergy DBL) don't occur in parallel (cross post)

### ISSUE THREAD

**Issue by trolfu** [dotnet/msbuild#5813]
### Issue Description
Cross post from [here](https://developercommunity.visualstudio.com/content/problem/1226188/project-builds-for-3rd-party-language-wont-occur-i.html) in case this ends up being the better spot for it.

### Data
Our project system is implemented using MPF so there's a bit of custom implementation. Combing through commits in a couple of repos (including F#) suggest that the only thing that needs to be implemented on the VS side is  `ProjectConfig.GetBuildCfgProperty` and setting the out var to true if the property being passed in is `VSBLDCFGPROPID_SupportsMTBuild`/`-16000`. Inspecting the VS diagnostic build output from our implementation indicates the projects still aren't building in parallel. Building the solution from the command line with msbuild and the `-m` flag does build the projects in parallel (visable in structured log viewer).

### Analysis
With project builds occurring in parallel from the command line, I'd rule out our custom target and task implementations as a failure point. I did break in one of our tasks and `BuildInParallel` was set to true on the task's build engine. As far as I can tell at this point, either there's an implementation detail wrong/missing in our project system or VS isn't interfacing with msbuild correctly to start parallel project builds for us. A test build in F# shows parallel builds occurring in VS diagnostic output. I've attached a VS log, msbuild binary log, and the VS setting showing multiple projects are allowed to build concurrently.

**Comment by BenVillalobos** [comment]
Thanks for filing this, because it's happening in VS this isn't our issue. We routed your feedback ticket to the correct internal team, please follow that.

**Comment by trolfu** [comment]
I appreciate it. Thank you!
