### ISSUE TITLE
build.cmd modifies the selected font of console

### ISSUE THREAD

**Issue by BartoszKlonowski** [dotnet/msbuild#5828]
### Issue Description
When launching the `build.cmd` (no matter if in *cmd.exe* or *PowerShell*) the font used for the console is changed to default used by *powershell* script.
As an example, having *consolas* font with size 14 selected:
![obraz](https://user-images.githubusercontent.com/70535775/96899117-cfdac800-1490-11eb-9072-9232da245269.png)
it's changed to:
![obraz](https://user-images.githubusercontent.com/70535775/96898615-37dcde80-1490-11eb-8af4-a86298876851.png)

**NOTE:** due to Polish language selected by *build.cmd* I also have some errors in displaying words containing special characters (notice for example "*okre lanie*" and "*przywrócenia*"). Some are displayed incorrectly, some are just avoided.

### Steps to Reproduce
* Configure your console with custom font family and font size settings
* Go to MSBuild project repository directory
* Launch the *build.cmd* and observe the change

### Expected Behavior
Console settings and font's style is kept and any output from *build.cmd* is printed with the customized settings and font.

### Actual Behavior
Settings are changed and stay changed even after *build.cmd* exits.

### Analysis
It looks like a problem with encoding, as [this answer](https://superuser.com/a/1548564) says.
The solution given in the mentioned answered solves the problem, but also forces the language to be english - it doesn't bother me, but if we want to keep the ability of *build.cmd* script to be displayed in various languages, then it's still needed to figure out better solution.

**Comment by rainersigwald** [comment]
Our `build.cmd` doesn't specify a codepage though; it's ANSI. This looks like an issue with PowerShell and the console host when the current codepage isn't ANSI. So I'm not sure there's anything we can do to implement a fix.

Does the same thing happen if you use the new [Windows Terminal](https://www.microsoft.com/en-us/p/windows-terminal/9n0dx20hk701)?

Does the same thing happen if you `chcp 65001` instead of `437`? That should allow Polish output.

**Comment by BartoszKlonowski** [comment]
@rainersigwald Thank you!
Answering both questions:

> Does the same thing happen if you use the new Windows Terminal?

No, when using Windows Terminal everything works well - translation is OK and settings are kept

> Does the same thing happen if you chcp 65001 instead of 437?

`chcp 65001` gives the same issue as with original *build.cmd* script - translation has missing/incorrect characters and settings are lost.

**Comment by BenVillalobos** [comment]
This issue might be related: https://github.com/microsoft/terminal/issues/280

**Comment by BenVillalobos** [comment]
Team Triage: If anyone knows what we can do to fix this in our repo, we'd love to hear about it 🙂

**Comment by BartoszKlonowski** [comment]
There are no comment for a few months now, and this is really a minor issue - I'll close this.
We can reopen this if anyone else will see this as worth spending the time.
