### ISSUE TITLE
Getting different result when running "/t:Restore" vs "/Restore"

### ISSUE THREAD

**Issue by AlexanderRydberg** [dotnet/msbuild#5841]
### Issue Description
`/t:Restore` gives me a different result than `/restore`

If we are building a csproj where we have included the nuget package "MSTest.TestAdapter" it will not include that packages dlls in the projects bin folder. If we have once before built the project without clearing the obj folder the result differs and all the dlls are there.

When we then try to run our tests it wont find any since the adapter is not present.
Tho if we have a csproj that includes another csproj that has "MSTest.TestAdapter" as a nuget package it will work as expected every build. Also if building the sln it works as expected.

### Steps to Reproduce
https://github.com/AlexanderRydberg/adapterTest
building from ps with msbuild:

```
$msbuild = "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe"
$collectionOfArgs = @("C:\GitHub\adapterTest\Tickster.Core.Tests.csproj", 
     "/t:Restore;Rebuild", "/p:Configuration=Release")
& $msbuild $collectionOfArgs
```
Check /bin/Release/ and it wont contain the mstestadapter dlls
Run the same ps script again without clearing /obj/ and /bin/Release/ will contain all the files

### Expected Behavior
These files should be copied to /bin/Release:
Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.dll
Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.dll
Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.Interface.dll
Microsoft.VisualStudio.TestPlatform.TestFramework.dll
Microsoft.VisualStudio.TestPlatform.TestFramework.Extensions.dll
Tickster.Core.Tests.dll
Tickster.Core.Tests.pdb

### Actual Behavior
Only these end up in /bin/Release unless it has been built before and /obj/ is not cleared. Meaning if you run the build twice, the dlls are all there (but thats a bit ineffective).
Microsoft.VisualStudio.TestPlatform.TestFramework.dll
Microsoft.VisualStudio.TestPlatform.TestFramework.Extensions.dll
Tickster.Core.Tests.dll
Tickster.Core.Tests.pdb

### Analysis
If I instead run:
```
$msbuild = "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe"
$collectionOfArgs = @("C:\GitHub\adapterTest\Tickster.Core.Tests.csproj", 
     "/t:Rebuild", "/p:Configuration=Release", "/restore")
& $msbuild $collectionOfArgs
```
it works as expected. But why?

### Versions & Configurations
MSBuild version: 16.7.0.37604
Windows 10

**Comment by teo-tsirpanis** [comment]
I suppose that `/restore` first runs your project with the `Restore` target, and then it runs it again with the targets you specified, while adding `/t:Restore` to your targets restores and builds the project at the same invocation.

The results differ because MSBuild will evaluate a restored project differently. For example, a restored project might import target files from the `build` directory of one of its dependencies.

**Comment by BenVillalobos** [comment]
Team Triage: This issue is why the `/Restore` exists now. Doing `/t:Restore;Rebuild` has the `Rebuild` target discover only what existed at the time `Restore` also ran, without finding what `Restore` generated.
