### ISSUE TITLE
Update to latest dotnet/runtime package versions

### ISSUE THREAD

**Issue by rainersigwald** [dotnet/msbuild#5852]
When the .NET 5.0 packages are out, we should update to the latest and greatest packages:

https://github.com/dotnet/msbuild/blob/47e6ac1bcff02d4cfbf2ff8ea0c957c072f697cc/eng/Packages.props#L27-L51

**Comment by ViktorHofer** [comment]
nit around naming: Those packages are now "runtime" packages, not "corefx" ones anymore :) Unsure how much Arcade logic you use, but if you have a Versions.props file, you can just create a subscription from runtime -> msbuild and auto update the packages.

**Comment by rainersigwald** [comment]
> you can just create a subscription from runtime -> msbuild and auto update the packages

We generally depend on GA packages and don't want to create problems with coherency, so I don't think we need a live subscription. Unless they've added a channel for "latest GA"? That would be kinda awesome for us.

**Comment by ViktorHofer** [comment]
@mmitche that would be the ".NET 5" channel, right? And when net6 is out we would then just update the channel to ".NET 6". Would that make sense?

**Comment by mmitche** [comment]
,NET 5 would be latest, but I wouldn't use it for that...because depending on the current build state it could be a mix-match of packages.

Instead the right thing to do is to probably update to the BAR build id of the RTM build: 68362

**Comment by rainersigwald** [comment]
WIP branch for this: https://github.com/rainersigwald/msbuild/tree/update-packages.

I'm thinking wait until 6.0 GA then do this, including VS fallout.

**Comment by rainersigwald** [comment]
Let's call this done, with the 7.0 packages in #8347.
