### ISSUE TITLE
The project dependencies in project.assets.json are named in an inconsistent manner

### ISSUE THREAD

**Issue by MarkKharitonov** [dotnet/msbuild#5860]
### Issue Description
We are talking about .Net Framework projects using **ProjectReference**.

Some project entries in project.assets.json are named after the project name and some are named after the respective assembly name. The logic behind selecting one or another is unclear and makes it hard to write custom processing of this file. For example, to deal with the binding redirect hell.

### Steps to Reproduce
https://github.com/MarkKharitonov/PackageAssetsJsonAnomaly#the-anomaly - this repository contains 3 tiny projects and describes the repro steps in README.

### Expected Behavior
The names of project entries follow a consistent scheme - either project or assembly names, but not mixed.

### Actual Behavior
On a sample solution with 3 tiny projects, the project.assets.json file names one project dependency after the project name and another - after the assembly name.

### Analysis
I do not have an idea, but I am afraid it is related to https://stackoverflow.com/questions/64576860/why-does-console-build-generate-radically-different-project-assets-json-than-tha

### Versions & Configurations
https://github.com/MarkKharitonov/PackageAssetsJsonAnomaly#the-anomaly

### Attach a binlog
https://github.com/MarkKharitonov/PackageAssetsJsonAnomaly/blob/master/msbuild.binlog

**Comment by rainersigwald** [comment]
This file is written by NuGet restore, so moving this issue to NuGet.

**Comment by rainersigwald** [comment]
This issue was moved to NuGet/Home#10255
