### ISSUE TITLE
.NET 6: error MSB4259: Unexpected space at position N Did you forget to remove a space?

### ISSUE THREAD

**Issue by jonathanpeppers** [dotnet/msbuild#5863]
### Issue Description

I'm guessing this was introduced in: https://github.com/dotnet/msbuild/pull/5672

Our build fails with:

```
error MSB4259: Unexpected space at position "47" of condition "$(RestoreTaskAssemblyFile.EndsWith('NuGet.exe', StringComparison.InvariantCultureIgnoreCase))". Did you forget to remove a space?
```

The property in question, I can fix by doing:

```diff
-<_IsRunningNuGetRestore Condition="$(RestoreTaskAssemblyFile.EndsWith('NuGet.exe', StringComparison.InvariantCultureIgnoreCase))">True</_IsRunningNuGetRestore>
+<_IsRunningNuGetRestore Condition="$(RestoreTaskAssemblyFile.EndsWith('NuGet.exe',StringComparison.InvariantCultureIgnoreCase))">True</_IsRunningNuGetRestore>
```

But then I just hit the next location:

```diff
-<AndroidSupportedHostJitAbisForConditionalChecks Condition=" !$(AndroidSupportedHostJitAbisForConditionalChecks.EndsWith (':')) "   >$(AndroidSupportedHostJitAbisForConditionalChecks):</AndroidSupportedHostJitAbisForConditionalChecks>
+<AndroidSupportedHostJitAbisForConditionalChecks Condition=" !$(AndroidSupportedHostJitAbisForConditionalChecks.EndsWith(':')) "   >$(AndroidSupportedHostJitAbisForConditionalChecks):</AndroidSupportedHostJitAbisForConditionalChecks>
```

I'm thinking these should be valid, as lots of our existing MSBuild targets would probably break.

### Steps to Reproduce

1. Use: https://dotnetcli.azureedge.net/dotnet/Sdk/6.0.100-alpha.1.20554.10/dotnet-sdk-6.0.100-alpha.1.20554.10-win-x64.exe
2. `dotnet build` this `foo.proj` file:

```xml
<Project>
  <PropertyGroup>
    <Foo>ABCD</Foo>
  </PropertyGroup>
  <ItemGroup Condition="$(Foo.StartsWith ('A'))">
    <Bar Include="True" />
  </ItemGroup>
  <Target Name="Build">
    <Message Importance="High" Text="Foo: $(Foo) Bar: @(Bar)" />
  </Target>
</Project>
```

### Expected Behavior

Build succeeds.

### Actual Behavior

Build fails with:

```
foo.proj(5,14): error MSB4259: Unexpected space at position "16" of condition "$(Foo.StartsWith ('A'))". Did you forget to remove a space?
```

### Analysis

Only guess is something in: https://github.com/dotnet/msbuild/pull/5672

### Versions & Configurations

```
> dotnet --version
6.0.100-alpha.1.20554.10
```

### Attach a binlog

[msbuild.zip](https://github.com/dotnet/msbuild/files/5497384/msbuild.zip)

**Comment by BenVillalobos** [comment]
This feature is behind [Change Wave 16.10](https://github.com/dotnet/msbuild/blob/master/documentation/wiki/ChangeWaves.md#1610). If you want to opt out of this feature, set environment variable `MSBuildDisableFeaturesFromVersion` to `16.10`.
