### ISSUE TITLE
As a customer, I want implicitly reduced launched processes so that MSBUILD is faster & consumes less resources

### ISSUE THREAD

**Issue by donJoseLuis** [dotnet/msbuild#5866]
### _*Reduction of launched processes*_

Explore reducing resource consumption and impact on latency by reducing the numbers of launched processes.  

### Issues:
- Eliminate extra dotnet process by loading MSBuild directly into CLI (like TE)
  - [x] [Make sure that MSBuild.dll is hostable](https://github.com/dotnet/msbuild/issues/6254)
  - [x] [Eliminate process hop in dotnet build by hosting MSBuild.dll in the CLI process](https://github.com/dotnet/sdk/issues/16362)
- ~~Work towards making MSBuild multi-threaded so `/m:N` uses N threads and not N processes~~ (out of scope for 6.0)

**Comment by donJoseLuis** [comment]
This work should be based in the learnings from #3139

**Comment by ladipro** [comment]
This can be closed now as we're not aware of further opportunities to eliminate processes launched as part of build. General build perf improvements should be parented by #5873.
