### ISSUE TITLE
As a customer, I want MSBUILD to start faster so that I wait negligible time to do my work

### ISSUE THREAD

**Issue by donJoseLuis** [dotnet/msbuild#5873]
### _*Start-time optimizations*_

Benchmark MSBUILD start times in targeted scenarios & investigate to identify optimization candidates.

### Issues:
- [x] [BinaryFormatter serialization of on-disk RAR cache is slow](https://github.com/dotnet/msbuild/issues/6057)
- [x] [Ignore comments and whitespace when parsing read-only XML files](https://github.com/dotnet/msbuild/pull/6232)
- [x] [Move importance/verbosity check earlier in logging](https://github.com/dotnet/msbuild/issues/5992)
- [ ] [MSBuild service](https://github.com/dotnet/msbuild/issues/6392)
- Start MSBuild nodes speculatively before they are needed

**Comment by ladipro** [comment]
All child issues have been closed.
