### ISSUE TITLE
Building custom MSBuild tasks extending TrackedVCToolTask

### ISSUE THREAD

**Issue by werat** [dotnet/msbuild#5882]
I have a few custom MSBuild tasks, that extend `Microsoft.Build.CPPTasks.TrackedVCToolTask` from `Microsoft.Build.CPPTasks.Common.dll`. Nothing fancy, just override some logic and add new properties.

I need my tasks to work in both Visual Studio 2017 and Visual Studio 2019. Ideally I would like to build just one version of DLL, that can be loaded and used in both editions of Visual Studio.

The problem is that `Microsoft.Build.CPPTasks.Common.dll` is shipped with Visual Studio and different editions have different versions. Visual Studio 2017 has version `15.0.0.0`, while Visual Studio 2019 -- `16.*` (e.g. `16.8.0.0`).

MSBuild in Visual Studio 2019 has a binding redirect for `Microsoft.Build.CPPTasks.Common.dll`, but only for `16.*` -- https://github.com/dotnet/msbuild/blob/master/src/MSBuild/app.config#L55-L59.

Visual Studio 2017 doesn't even have a binding redirect, so the `Microsoft.Build.CPPTasks.Common.dll` in Visual Studio must always match the one I used for building my custom tasks library.

So currently I have to build two versions of `MyCustomTasks.dll`:
* One referencing `CPPTasks 15.0.0.0` (for Visual Studio 2017)
* One referencing `CPPTasks 16.0.0.0` (for Visual Studio 2019)

Questions:

* Is it somehow possible to build just one version that can work with both versions of Visual Studio?

* What is the recommended way of writing custom tasks that depend on `Microsoft.Build.CPPTasks.Common.dll`? It seems that this library is not even available in Nuget, so I have to build against the one in my Visual Studio, which also doesn't seem ideal.

* Can I ship a specific version `Microsoft.Build.CPPTasks.Common.dll` along with my `MyCustomTasks.dll`? I can imagine there might be conflicts if MSBuild tried to load two different versions. Also I'm not sure if it's allowed from licensing perspective.

Thanks!

**Comment by werat** [comment]
Kind reminder :)

**Comment by yuehuang010** [comment]
Hi, @werat, officially you will need a different DLL for 15.0 and 16.0.  It don't guarantee any backwards compatibility on any of the API in the DLL.  That said, Miscrosoft.Build.CPPTask.Common.dll is a fairly mature DLL and very little changes between versions.  Your DLL could be referenced by name but might have issues during binding or runtime.  You will need to test thoroughly.  

Felix Huang from Visual Studio C++.

**Comment by yuehuang010** [comment]
> What is the recommended way of writing custom tasks that depend on Microsoft.Build.CPPTasks.Common.dll? It seems that this library is not even available in Nuget, so I have to build against the one in my Visual Studio, which also doesn't seem ideal.
The dll is not in a Nuget, you will have to reference the Dll directly from the Visual Studio folder.

> Can I ship a specific version Microsoft.Build.CPPTasks.Common.dll along with my MyCustomTasks.dll? I can imagine there might be conflicts if MSBuild tried to load two different versions. Also I'm not sure if it's allowed from licensing perspective.
It is untested and I would guess it would lead to many more problems.

Try this path. 1) Try shipping one DLL referring the 15.0.  This should load in 16.0.  If there are breaking changings, then 2) ship two DLL, then use <Using> in the .targets to switch between the versions.

Thanks
Felix

**Comment by Forgind** [comment]
Seems resolved, right?
