### ISSUE TITLE
Framework References incorrectly added implicitly via nuspec when older versions have that reference

### ISSUE THREAD

**Issue by dotMorten** [dotnet/msbuild#5896]
### Issue Description

If I build a project for one target framework has a framework dependency, but a newer target framework dependency doesn't, the generated nuspec will cause the dependency to be added to both.

### Steps to Reproduce
- Create a new SDK style project.
- Make the project file look like this:
```xml
<Project Sdk="MSBuild.Sdk.Extras/2.1.2">

  <PropertyGroup>
    <TargetFrameworks>netcoreapp3.1;net5.0-windows</TargetFrameworks>
    <UseWpf Condition="'$(TargetFramework)'=='netcoreapp3.1'">true</UseWpf>
  </PropertyGroup>

</Project>
```

This will cause WPF to be a dependency for the .NET Core 3.1 target, but not for the .NET5-Windows build.
However the generated nuspec will look like this:

```xml
<?xml version="1.0" encoding="utf-8"?>
<package xmlns="http://schemas.microsoft.com/packaging/2012/06/nuspec.xsd">
  <metadata>
    <id>FrameworkRepro</id>
    <version>1.0.0</version>
    <authors>FrameworkRepro</authors>
    <requireLicenseAcceptance>false</requireLicenseAcceptance>
    <description>Package Description</description>
    <dependencies>
      <group targetFramework=".NETCoreApp3.1" />
      <group targetFramework="net5.0-windows7.0" />
    </dependencies>
    <frameworkReferences>
      <group targetFramework=".NETCoreApp3.1">
        <frameworkReference name="Microsoft.WindowsDesktop.App.WPF" />
      </group>
    </frameworkReferences>
  </metadata>
</package>
```
The problem is when referencing this package, because `.NETCoreApp3.1` < `net5.0-windows7.0`, the `Microsoft.WindowsDesktop.App.WPF` reference will get added to .NET 5 projects as well.
The generated nuspec framework references should have looked like this to avoid that:

```xml
    <frameworkReferences>
      <group targetFramework=".NETCoreApp3.1">
        <frameworkReference name="Microsoft.WindowsDesktop.App.WPF" />
      </group>
      <group targetFramework="net5.0-windows7.0" />
    </frameworkReferences>
```

### Expected Behavior
`<group targetFramework="net5.0-windows7.0" />` included in nuspec.

### Actual Behavior
WPF dependency added to .NET5 project that uses the generated package.

### Versions & Configurations
Microsoft (R) Build Engine version 16.8.1+bd2ea1e3c for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.
16.8.1.52902

### Attach a binlog

[msbuild.zip](https://github.com/dotnet/msbuild/files/5563323/msbuild.zip)

**Comment by nkolev92** [comment]
Dup of https://github.com/NuGet/Home/issues/10218.

**Comment by dotMorten** [comment]
Thanks. Closing in favor of that one.
