### ISSUE TITLE
msbuild restore doesn't import all packages

### ISSUE THREAD

**Issue by zdavidsen** [dotnet/msbuild#5908]
### Issue Description

(Posting on behalf of a coworker, since I'm the designated build script maintainer)

We have a common msbuild script/project that we use in a number of repositories which requires a couple of Nuget packages (an internal package and MSBuild Community Tasks).  Recently, one of my coworkers has started having problems with the project, where it will restore correctly but won't import MSBuild Community tasks (it does import the internal package).  The fun part is that the exact same project will build on any of our other machines and our build server; it only fails on coworker's machine.

Any ideas what could be causing this?

Here's a slightly stripped down copy of the common build script, and the generated .props and .targets files from both my machine and the coworker's.
[MSBuildFiles.zip](https://github.com/dotnet/msbuild/files/5591156/MSBuildFiles.zip)

**Comment by BenVillalobos** [comment]
Team Triage:  Does this still happen if your coworker flushes their nuget cache? `nuget locals all -clear`. This will delete _all_ nuget packages on their machine and the restore will redownload them.

**Comment by zdavidsen** [comment]
Yes to both of those questions.  He tried clearing the nuget cache (probably through visual studio), and I know the package exists locally because manually importing the targets file allows the build to proceed.
(`<Import Project="$(PkgMSBuildTasks)\build\MSBuildTasks.targets" />`)

**Comment by BenVillalobos** [comment]
Team Triage: When your coworker imports using `<Import Project="$(PkgMSBuildTasks)\build\MSBuildTasks.targets" />`, what does `PkgMSBuildTasks` expand to? Is it the same on your machine?

**Comment by zdavidsen** [comment]
It's expanding to the same path on both computers: `C:\Users\<user>\.nuget\packages\msbuildtasks\1.5.0.235`

**Comment by BenVillalobos** [comment]
This issue was moved to NuGet/Home#10347
