### ISSUE TITLE
InvalidProjectFileException in ProjectCollection.LoadProject()

### ISSUE THREAD

**Issue by yevgeni-zolotko** [dotnet/msbuild#5913]
### Issue Description

I am trying to load .csproj file with msbuild 14 API, and on a machine with both VS2019 **16.8.2** and VS2019 **16.8.0 Preview 4.0** installed, I get
_Microsoft.Build.Exceptions.InvalidProjectFileException: 'The tools version "14.0" is unrecognized. Available tools versions are "2.0", "3.5", "4.0"_
in the following code:
```
new ProjectCollection().LoadProject("HelloWorld.csproj");
```
where _HelloWorld.csproj_ looks like 

```
<Project ToolsVersion="14.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
...
</Project>
```
This error goes away whan I install _Build tools for VS2015_ on my machine.
**However**, this code works fine on a clean Windows 10 VM with no additional software/SDKs installed.
Could we get a clear guidance on how to use msbuild API/NuGet packages for project file manipulation on machines with no VS/build tools installed?

Here are the packages I am using:

```
    <PackageReference Include="System.Threading.Tasks.Dataflow" Version="4.5.24" Condition="$(DefineConstants.Contains(';NETFRAMEWORK'))" />
    <PackageReference Include="Microsoft.Build" Version="14.3.0" />
    <PackageReference Include="Microsoft.Build.Utilities.Core" Version="14.3.0" />
```

### Steps to Reproduce

- Download the following project: [ToolsVersionTest.zip](https://github.com/dotnet/msbuild/files/5598432/ToolsVersionTest.zip)
- Open it in VS, compile and run it

### Expected Behavior
The program exits with no exception.

### Actual Behavior
An exception _Microsoft.Build.Exceptions.InvalidProjectFileException: 'The tools version "14.0" is unrecognized. Available tools versions are "2.0", "3.5", "4.0"_ is thrown.

### Versions & Configurations
Microsoft (R) Build Engine version 16.8.2+25e4d540b for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

16.8.2.56705

Both VS2019 **16.8.2** and VS2019 **16.8.0 Preview 4.0** are installed

**Comment by BenVillalobos** [comment]
Team Triage: Can you provide more context on what you want to do and why? Ideally you want to load a project like visual studio would. This link might help: https://docs.microsoft.com/visualstudio/msbuild/updating-an-existing-application

**Comment by yevgeni-zolotko** [comment]
@BenVillalobos 

> Can you provide more context on what you want to do and why?

We make application scripting components for .NET developers. For our script projects we use the .csproj format. In our demo application, we allow users to change the script projects (i.e. add references, files, etc). Then user can save the modified project into a .csproj file. To implement saving the project, we are using msbuild libraries, namely the aforementioned APIs.

**Comment by BenVillalobos** [comment]
Team Triage: Because you're referencing MSBuild 14.3, that requires having VS Build Tools version 14, 2015 installed. Can you try using MSBuildLocator? https://github.com/Microsoft/MSBuildLocator

**Comment by yevgeni-zolotko** [comment]
@BenVillalobos Thank you for the advise on using MSBuildLocator.
But what really of interest to us is (quoting the original question, added emphasis):
> Could we get a clear guidance on how to use msbuild API/NuGet packages for project file manipulation on machines with __no VS/build tools installed?__

Could you please confirm it is currently impossible to use msbuild programmatically with no VS Build Tools installed, or otherwise? Would it help if we upgraded to an msbuild version newer than 14.3?

**Comment by Forgind** [comment]
Team triage: MSBuild is more complicated than many other assemblies. It's essentially a programming language API plus an implementation of that API plus common targets that run in build. The MSBuild engine handles actually executing tasks and targets, but it doesn't have visibility into a lot of other parts of the build. It also includes a set of common targets that run for each build, and sets of targets that often run but don't run every time. If you load a project that you want to load or manipulate, we need to be able to import everything it imports. That includes .targets and .props that aren't necessarily findable or open-source. Missing those means that although you could call MSBuild, it wouldn't do what you would expect.

As a result, it's impossible to use arbitrary parts of MSBuild's API without getting the whole package from VS, build tools, or the .NET SDK. MSBuildLocator can help find and load MSBuild if it's downloaded, though the finding part doesn't work as well with VS < 15.0. You can still register MSBuild using RegisterMSBuildPath.

**Comment by yevgeni-zolotko** [comment]
@Forgind Thank you for your reply.
