### ISSUE TITLE
GenerateResource Task: Missing resources

### ISSUE THREAD

**Issue by markusroessler** [dotnet/msbuild#5919]
### Issue Description
When generating a StronglyTypedClass from a resx file in Visual Studio (Language: German), the comments within the generated class are german as expected.
When using the msbuild task GenerateResource from the command line, the comments are english.

### Steps to Reproduce
* Open Visual Studio and set the language to German
* Create a .NET Standard project
* add a resx file 
* configure the csproj file to generate a StronglyTypedClass from the resx:
````
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Update="Resources\AppResources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>AppResources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Resources\AppResources.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>AppResources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>
</Project>
````

* open the generated AppResources.Designer.cs. The output looks like this:
 ```
/// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
  ...
    public class AppResources {
 ...
```

* regenerate the class using "msbuild -t:ResGen". The output looks like this:
```
/// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
   ...
    public class AppResources {
...

```
### Expected Behavior
The comments in a generated StronglyTypedClass are in the same language as msbuild's CultureInfo.CurrentCulture

### Actual Behavior
The generated comments are always english.

### Analysis
The visual studio resources are located in this satellite assembly: 
C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\Common7\IDE\PrivateAssemblies\de\System.Design.Resources.dll > System.Design.de.resources

These resources (System.Design.de.resources) are missing in msbuild's satellite assembly: 
C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin\de\Microsoft.Build.Tasks.Core.resources.dll

### Versions & Configurations
Windows 10 x64
Visual Studio 2019
msbuild 16.7.0.37604

**Comment by BenVillalobos** [comment]
Note to self: Set up a VM in german, install VS and set language to german and repro it.

**Comment by BenVillalobos** [comment]
Sorry this fell through the cracks! Is this still an issue?

**Comment by markusroessler** [comment]
I'm not sure if this still occurs but for me it isn't a problem anymore - we removed those generated classes from version control. So we don't see those "pseudo changes" when committing resource changes. Will close for now.
