### ISSUE TITLE
Update GenApi to use nuget compat functions

### ISSUE THREAD

**Issue by benvillalobos** [dotnet/msbuild#5947]
Refer to @rainersigwald , related item: `GenAPIShortFrameworkIdentifier` in src/Directory.Build.targets

**Comment by rainersigwald** [comment]
Yeah, here:

https://github.com/dotnet/msbuild/blob/1ff34e830630ff7c4b6cb008e85ece4f263ace52/src/Directory.Build.targets#L80-L82

Use [IsTargetFrameworkCompatible](https://docs.microsoft.com/visualstudio/msbuild/property-functions?view=vs-2019#msbuild-targetframework-and-targetplatform-functions) instead.

**Comment by GangWang01** [comment]
#5799 has already updated them with another function `GetTargetFrameworkIdentifier`.

Over time they became the properties below.
https://github.com/dotnet/msbuild/blob/3847162365a20626dbef16f2b1153dada9c26965/src/Directory.Build.targets#L80-L85
But these properties have became unused any more currently. I think we could remove them to make the code clean.

https://github.com/dotnet/msbuild/commit/90ae0e4d88cdff845c957e5e94d235c29f594fd5#diff-4da790e243fabc7a08eef8f04f251cff1a708fd1aa498a6508da5ecb2bce1564 dropped the reference to `GenAPIFolderPath`.
https://github.com/dotnet/msbuild/pull/8116/files#diff-4da790e243fabc7a08eef8f04f251cff1a708fd1aa498a6508da5ecb2bce1564 dropped the reference to `PublicApiTfm`.

**Comment by rainersigwald** [comment]
Yeah, we don't need this any more at all after #8116. Closing.
