### ISSUE TITLE
ProjectInSolution.AbsolutePath should return a normalized full path

### ISSUE THREAD

**Issue by jeffkl** [dotnet/msbuild#5949]
### Issue Description
`ProjectInSolution.AbsolutePath` currently returns the result of `Path.Combine()` which leaves in relative path segments like `..\`.  When parsing a solution and getting the paths to projects, this places the burden on the caller to normalize the path.

https://github.com/dotnet/msbuild/blob/1ff34e830630ff7c4b6cb008e85ece4f263ace52/src/Build/Construction/Solution/ProjectInSolution.cs#L165

### Steps to Reproduce
Create a solution with relative paths containing `..\` 
Parse the solution with the `SolutionFile` API
Call the `AbsolutePath` property on one of the `ProjectInSolution` objects.

### Expected Behavior
`AbsolutePath` property returns a normalized full path.

### Actual Behavior
`AbsolutePath` property returns a path containing `..\` segments.

### Versions & Configurations
All versions of MSBuild

This manifested into this bug: https://github.com/NuGet/Home/issues/10307

And its worked around in MSBuild's own codebase:
https://github.com/dotnet/msbuild/blob/1ff34e830630ff7c4b6cb008e85ece4f263ace52/src/Build/Graph/GraphBuilder.cs#L293-L298

**Comment by aolszowka** [comment]
Wonder if these are related?

https://github.com/dotnet/msbuild/issues/5915

Also https://github.com/dotnet/msbuild/issues/5898
