### ISSUE TITLE
Add ARM64 as a supported architecture 

### ISSUE THREAD

**Issue by tommcdon** [dotnet/msbuild#5951]
**Visual Studio Version**: 16.8

**Summary**: .NET 5 is adding support for Windows ARM64. Visual Studio .NET Core projects should allow you target ARM64 in addition to x86/x64/arm32.

**Steps to Reproduce**:

1. Create a .NET Core Console / Unit Test / ASP.NET Core  project

2. Under Project properties, Build, you should be able to select "ARM64" as a target architecture

**Comment by predavid** [comment]
@dotnet/sdk - when will the ARM64 option be made available in the Platform Target drop-down?

**Comment by tommcdon** [comment]
@tmeschter

**Comment by marcpopMSFT** [comment]
@BenVillalobos check with Daniel on what are the risks of us updating the AvailablePlatforms in common targets.  @tommcdon , are there any restrictions on when to show ARM64 and ARM32? I think the risk here is that MSBuild may not be aware of projects that don't support those targets.

**Comment by tommcdon** [comment]
> @tommcdon , are there any restrictions on when to show ARM64 and ARM32? I think the risk here is that MSBuild may not be aware of projects that don't support those targets.

| Version | Windows | Linux | macOS
| --- | --- | --- | ---
| [.NET Core 2.1](https://github.com/dotnet/core/blob/master/release-notes/2.1/2.1-supported-os.md) | x86, x64 | x86, x64, arm32 | x64
| [.NET Core 3.1](https://github.com/dotnet/core/blob/master/release-notes/3.1/3.1-supported-os.md) | x86, x64, arm32 | x86, x64, arm32, arm64 | x64
| [.NET 5](https://github.com/dotnet/core/blob/master/release-notes/5.0/5.0-supported-os.md) | x86, x64, arm64 (console only) | x86, x64, arm32, arm64 | x64

**Comment by marcpopMSFT** [comment]
@BenVillalobos I went ahead and put this in 16.10 as I think we have what we need from Tom.

**Comment by BenVillalobos** [comment]
@dsplaisted how do we go about checking if we're specifically a console app?

The only reference to a console app check I've found is line 5647 on Microsoft.Common.CurrentVersion.Targets:
`<Error Condition="'$(OutputType)'!='winexe' and '$(OutputType)'!='exe' and '$(OutputType)'!='appcontainerexe'" Text="Publish is only valid for 'Windows Application' or 'Console Application' project types."/>`

**Comment by BenVillalobos** [comment]
I'm not seeing any changes adding ARM64 to AvailablePlatforms: 
![image](https://user-images.githubusercontent.com/4691428/113363232-321fda80-9305-11eb-96f1-8de910eec761.png)

**Comment by davkean** [comment]
@drewnoakes How are you populating above?

**Comment by dsplaisted** [comment]
> @dsplaisted how do we go about checking if we're specifically a console app?
> 
> The only reference to a console app check I've found is line 5647 on Microsoft.Common.CurrentVersion.Targets:
> `<Error Condition="'$(OutputType)'!='winexe' and '$(OutputType)'!='exe' and '$(OutputType)'!='appcontainerexe'" Text="Publish is only valid for 'Windows Application' or 'Console Application' project types."/>`

Non-console apps would have a FrameworkReference to the WindowsDesktop or AspNetCore framework.  There wouldn't be a RuntimePack for the ARM RuntimeIdentifiers that aren't supported, so you'd get an error building a self-contained app targeting ARM.  I don't think we have a block that would prevent you from building a shared framework app using an ARM RuntimeIdentifier.

**Comment by drewnoakes** [comment]
Those options are currently hard coded here:

https://github.com/dotnet/project-system/blob/20d7f46f0f492dfabcd61b7462e532b8229ca005/src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/BuildPropertyPage.xaml#L39-L50

If they can be sourced from somewhere, we can add a dynamic enum value provider that surfaces them.

**Comment by davkean** [comment]
They are provided by the `<AvailablePlatforms>` property.

**Comment by tmeschter** [comment]
Surfacing it in the new property pages is now tracked via https://github.com/dotnet/project-system/issues/7081. The current plan is to read the allowable values from `<AvailablePlatforms>` and we will depend on the SDK to populate that correctly.

**Comment by davkean** [comment]
Note that the property pages have always read it (indirectly) from AvailablePlatforms. This was a regression from the prior pages.

**Comment by austinkinross** [comment]
Until this is fixed, what's the best way (if any) to make MSBuild pass /platform:ARM64 to CSC?

**Comment by BenVillalobos** [comment]
@austinkinross At first glance, it looks like MSBuild calls csc and includes the platform like so: `Platform="$(PlatformTarget)"`. Setting platformtarget affects `PlatformTargetAsMSBuildArchitecture` and `ProcessorArchitecture` properties, which will likely have adverse side effects.
