### ISSUE TITLE
ResolveComReference task does not respect EmbedInteropTypes in .NET Core 3.1 app

### ISSUE THREAD

**Issue by tmeschter** [dotnet/msbuild#5959]
### Issue Description

When building a .NET Core 3.1 project with a `COMReference` item with `<EmbedInteropTypes>true</EmbedInteropTypes>` metadata, the metadata will be correctly embedded but the PIA will still be copied to the output _and_ will be listed as a dependency in the .deps.json file.

### Steps to Reproduce

1. On a system with the Office COM libraries installed, create a project with the following content:
``` xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <!-- This is just an example; I believe any COMReference with EmbedInteropTypes=true will reproduce. -->
    <COMReference Include="Microsoft.Office.Interop.Excel">
      <WrapperTool>tlbimp</WrapperTool>
      <VersionMinor>9</VersionMinor>
      <VersionMajor>1</VersionMajor>
      <Guid>00020813-0000-0000-c000-000000000046</Guid>
      <Lcid>0</Lcid>
      <Isolated>false</Isolated>
      <EmbedInteropTypes>true</EmbedInteropTypes>
    </COMReference>
  </ItemGroup>
</Project>
```
2. Replace Program.cs with the following:
``` csharp
using System;
using Excel = Microsoft.Office.Interop.Excel;

namespace NETCoreApp31
{
    class Program
    {
        static void Main(string[] args)
        {
            // The point here is to use COM types so the compiler will embed them in the output assembly.
            var excelApplication = new Excel.Application();
            var workbooks = excelApplication.Workbooks;
            var sampleWorkbook = workbooks.Add();
            Excel.Worksheet sampleWorksheet = (Excel.Worksheet)sampleWorkbook.Worksheets[1];
            Excel.Range samplecell = sampleWorksheet.Range["A1"];
            samplecell.Value = "New Value";
            sampleWorkbook.SaveAs2(Filename: @"C:\Users\tomescht\Downloads\Output.xlsx");
            sampleWorkbook.Close();
            excelApplication.Quit();
        }
    }
}
```
3. Build the project.

### Expected Behavior

- The COM types used in Program.cs **are** copied into the output assembly (can be verified with ilspy or ildasm).
- The Interop.Microsoft.Office.Interop.Excel.dll PIA **is not** copied to the output directory.
- The Interop.Microsoft.Office.Interop.Excel.dll PIA **is not** listed as a dependency in the .deps.json.

### Actual Behavior

- The COM types used in Program.cs are copied into the output assembly, as expected.
- The Interop.Microsoft.Office.Interop.Excel.dll PIA **is** copied to the output directory.
- The Interop.Microsoft.Office.Interop.Excel.dll PIA **is** listed as a dependency in the .deps.json.

### Analysis

It looks like the issue is this code in SetCopyLocalToFalseOnGacOrNoPIAAssemblies:

https://github.com/dotnet/msbuild/blob/1ff34e830630ff7c4b6cb008e85ece4f263ace52/src/Tasks/ResolveComReference.cs#L1619-L1628

I suspect that the version check causes us to entirely (and improperly) skip the body of the `if` block when targeting .NET Core 3.1.

Also, this scenario works as expected when targeting .NET 5, lending support this theory.

### Versions & Configurations

```
Microsoft (R) Build Engine version 16.9.0-preview-20603-10+d39f2e4f5 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

16.9.0.60310
```

### Attach a binlog

[msbuild.binlog.zip](https://github.com/dotnet/msbuild/files/5676267/msbuild.binlog.zip)

**Comment by tmeschter** [comment]
This was discovered while investigating dotnet/project-system#5735. I suspect that since the project system wasn't adding the EmbedInteropTypes metadata to begin with (which is being fixed) we didn't notice that it wasn't being fully respected.

**Comment by rainersigwald** [comment]
@AaronRobinsonMSFT do you have thoughts on the best path forward here?

**Comment by AaronRobinsonMSFT** [comment]
>Also, this scenario works as expected when targeting .NET 5, lending support this theory.
>do you have thoughts on the best path forward here?

@rainersigwald So much boo here. I am inclined to say we should fix this for .NET Core 3.1, but don't understand what that would mean. The code snippet referenced by @tmeschter seems to indicate a simple updated predicated would suffice but I don't know how servicing MSBuild works here.

Let's go down the path of "yes, this should be fixed to support someone building with .NET Core 3.1" - how would we approach that?

**Comment by rainersigwald** [comment]
> Let's go down the path of "yes, this should be fixed to support someone building with .NET Core 3.1" - how would we approach that?

Since we only support COMReference items in desktop/full framework MSBuild, this is a bit easier. We have two options:

1. Fix it in our current development branch which will flow into VS 16.9.
1. Service MSBuild in the oldest VS that supports targeting .NET 3.1 and is still in support (16.4) + merge the fix forward to other supported branches (16.8, 16.9).

The bar for option 2 is pretty high and I don't think this would meet it without high-pri customer reports. So I'd say "just fix it for 16.9", which is pretty straightforward.

**Comment by Forgind** [comment]
We haven't had any high-priority customer reports, and .NET 3.1 will be out of support in a few months. Should we just close this as won't-fix?

**Comment by marcpopMSFT** [comment]
Since Tom says this was working in 5.0 and 3.1 is nearly out of support, closing.
