### ISSUE TITLE
Building Xamarin.Forms iOS project with msbuild fails because of missing dll

### ISSUE THREAD

**Issue by xamadev** [dotnet/msbuild#5963]
### Issue Description
I'm trying to build a Xamarin.Forms iOS project via command line for CI/CD purposes directly on macOS. Please have a look at [this StackOverflow post](https://stackoverflow.com/questions/65197810/building-xamarin-forms-ios-project-from-command-line-with-msbuild).

### Steps to Reproduce

- Create a fresh Xamarin.Forms project in Visual Studio for Mac named test
- run `dotnet build test/test.csproj --configuration Release --no-dependencies`
- run  `msbuild test.iOS/test.iOS.csproj /restore /p:Platform=iPhone /p:ArchiveOnBuild=true /p:Configuration="Release" /p:BuildProjectReferences="false"`

Error message:
```
CSC : error CS0006: Metadata file '/Users/c4s/Projects/test/test/bin/iPhone/Release/netstandard2.0/ref/test.dll' could not be found [/Users/c4s/Projects/test/test.iOS/test.iOS.csproj]
Die Erstellung des Projekts "/Users/c4s/Projects/test/test.iOS/test.iOS.csproj" ist abgeschlossen (Standardziele) -- FEHLER.

Fehler beim Buildvorgang.

"/Users/c4s/Projects/test/test.iOS/test.iOS.csproj" (Standardziel) (1:7) ->
(CoreCompile Ziel) -> 
  CSC : error CS0006: Metadata file '/Users/c4s/Projects/test/test/bin/iPhone/Release/netstandard2.0/ref/test.dll' could not be found [/Users/c4s/Projects/test/test.iOS/test.iOS.csproj]
```
### Software Versions
=== Visual Studio Community 2019 for Mac ===

Version 8.8.3 (build 16)
Installation UUID: 529e58c4-5244-46ca-87c6-c920436d9e08
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 612000107

=== Mono Framework MDK ===

Runtime:
	Mono 6.12.0.107 (2020-02/a22ed3f094e) (64-bit)
	Package version: 612000107

=== Roslyn (Language Service) ===

3.8.0-5.20519.18+4c195c3ac1974edcefa76774d7a59a2350ec55fa

=== NuGet ===

Version: 5.8.0.6860

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/5.0.100/Sdks
SDK Versions:
	5.0.100
	3.1.404
	3.1.402
MSBuild SDKs: /Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	5.0.0
	3.1.10
	3.1.8
	2.1.23
	2.1.22

=== .NET Core 3.1 SDK ===

SDK: 3.1.404

=== Xamarin.Profiler ===

Version: 1.6.15.68
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Xamarin Designer ===

Version: 16.8.0.507
Hash: e87b24884
Branch: remotes/origin/d16-8
Build date: 2020-10-29 00:31:38 UTC

=== Apple Developer Tools ===

Xcode 12.1 (17222)
Build 12B45b

=== Xamarin.Android ===

Not Installed

=== Microsoft OpenJDK for Mobile ===

Java SDK: Not Found

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.8.0.32
Hash: 01a7774
Branch: remotes/origin/d16-8
Build date: 2020-10-13 23:32:30 UTC

=== Android Device Manager ===

Version: 16.8.0.45
Hash: fc0af5f
Branch: remotes/origin/d16-8
Build date: 2020-10-13 23:32:54 UTC

=== Xamarin.Mac ===

Xamarin.Mac not installed. Can't find /Library/Frameworks/Xamarin.Mac.framework/Versions/Current/Version.

=== Xamarin.iOS ===

Version: 14.4.1.3 (Visual Studio Community)
Hash: e30c41de3
Branch: d16-8
Build date: 2020-10-20 22:18:50-0400

=== Build Information ===

Release ID: 808030016
Git revision: cc6375d2fdcc1b42532e551e24ce650eaca1ae45
Build date: 2020-11-25 13:16:20-05
Build branch: release-8.8
Xamarin extensions: cc6375d2fdcc1b42532e551e24ce650eaca1ae45

=== Operating System ===

Mac OS X 10.15.7
Darwin 19.6.0 Darwin Kernel Version 19.6.0
    Mon Aug 31 22:12:52 PDT 2020
    root:xnu-6153.141.2~1/RELEASE_X86_64 x86_64

**Comment by Forgind** [comment]
This issue was moved to xamarin/xamarin-macios#10308
