### ISSUE TITLE
MSBuild Does Not Attempt to Retry a Copy of Output Assembly In Some Scenarios

### ISSUE THREAD

**Issue by aolszowka** [dotnet/msbuild#5964]
### Issue Description
In a scenario not yet fully understood MSBuild will fail to attempt a retry at a copy on these lines:

https://github.com/dotnet/msbuild/blob/54bda1ba66d46f8a11f1710d6d0e7bceac7110ac/src/Tasks/Microsoft.Common.CurrentVersion.targets#L4555-L4566

Here is the redacted output of a build

```
"S:\bamboo\TSG-TTI1030-CG\Dotnet\Source\Framework\Interop\Project\XXX.Interop.sln" (Build target) (1:2) ->
        "S:\bamboo\TSG-TTI1030-CG\Fusion\Server\PlatformServices\CashService\XXX.CashServiceContracts\XXX.CashPlatformServiceContracts.csproj" (default target) (42:7) ->
        (_CopyFilesMarkedCopyLocal target) ->
           C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(4559,5): warning MSB3026: Could not copy "S:\bamboo\TSG-TTI1030-CG\Bin\Shared\XXX.Models.pdb" to "..\..\..\..\..\Bin\Server\XXX.Models.pdb". Beginning retry 1 in 1000ms. The process cannot access the file '..\..\..\..\..\Bin\Server\XXX.Models.pdb' because it is being used by another process. [S:\bamboo\TSG-TTI1030-CG\Fusion\Server\PlatformServices\CashService\XXX.CashServiceContracts\XXX.CashPlatformServiceContracts.csproj]
"S:\bamboo\TSG-TTI1030-CG\Dotnet\Source\Framework\Interop\Project\XXX.Interop.sln" (Build target) (1:2) ->
        "S:\bamboo\TSG-TTI1030-CG\Fusion\Server\PublishedServices\Private.CollectionsInquiryService\XXX.CollectionsInquiryPrivatePublished.Contracts\XXX.PrivatePublished.CollectionsInquiry.Contracts.csproj" (default target) (53:8) ->
        (_CopyFilesMarkedCopyLocal target) ->
           C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(4559,5): error MSB3021: Unable to copy file "S:\bamboo\TSG-TTI1030-CG\Bin\Shared\XXX.iFX.Core.dll" to "..\..\..\..\..\Bin\Server\XXX.iFX.Core.dll". Access to the path '..\..\..\..\..\Bin\Server\XXX.iFX.Core.dll' is denied. [S:\bamboo\TSG-TTI1030-CG\Fusion\Server\PublishedServices\Private.CollectionsInquiryService\XXX.CollectionsInquiryPrivatePublished.Contracts\XXX.PrivatePublished.CollectionsInquiry.Contracts.csproj]
      65 Warning(s)
     1 Error(s)
  Time Elapsed 00:00:25.68
```

The interesting part is that we see several attempts (that is what most of the warnings are) at this same line to reattempt a copy which end up being successful. But for some reason other places will fail.

The root cause is not yet known.

### Expected Behavior
This should attempt to retry this copy.

### Actual Behavior
There is never an attempt to recopy.

### Analysis
The Solution being ran is incredibly complex (~3500 projects in the Solution). The suspicion is that at some point the `$(CopyRetryCount)` is dropped.

We are going to attempt setting this as a Window Level Environment Variable (dirty hack) to see if we can survive for now.

### Versions & Configurations
Windows Server 2019

`msbuild -version`
```
Microsoft (R) Build Engine version 16.8.1+bd2ea1e3c for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

16.8.1.52902
```

**Comment by Forgind** [comment]
Team triage: Can you get a binlog or diagnostic build log to see if CopyRetryCount is being passed to the failing task, and if so, whether its value is valid?

**Comment by aolszowka** [comment]
@Forgind Is there a non-public way I can give you this binlog? I'll try to get you a smaller one than the 21.5GB Monster https://github.com/KirillOsenkov/MSBuildStructuredLog/issues/397#issuecomment-699088101

**Comment by aolszowka** [comment]
Sorry to double post, but to add more detail here:

* We have proven that setting this variable explicitly (as a Windows Level Environment Variable) does work around the issue.
* We believe we know why we encounter the condition, unfortunately it is a race condition.

Our system, being a large monolith, utilizes several shared libraries, these shared libraries will get copied to several output locations (For example `/bin/Client`, `/bin/Server`, `/bin/Test`, `/bin/Shared`) when the system (~3,500 Projects) in run in a massively parallel build server (64 Cores/128GB RAM/64GB RAM Drive) the probability that you will encounter a scenario like the following approaches 1:

![image](https://user-images.githubusercontent.com/2592881/102383374-af0e8a80-3f88-11eb-870a-dd98331b3366.png)

Where A Outputs to `/bin/Shared`
Where B and C Output to `/bin/Client`

If you attempt to build B and C at the same time and they attempt to perform their copy at the same time, because the `retry` is being dropped you win "the game" and encounter a copy conflict.

**Comment by KirillOsenkov** [comment]
@aolszowka you can email the binlog to me and I'll forward.

Have you searched the binlog:
 1. search the tree for `Property reassignment CopyRetryCount`
 2. search Find in Files for `CopyRetryCount` and see if you have non-standard usages that don't come from standard targets

**Comment by rainersigwald** [comment]
You can also always file VS feedback at https://developercommunity.visualstudio.com/ which has a private-upload feature. Then link it here and we can short-circuit the routing process.

**Comment by aolszowka** [comment]
Hi All,

Thanks for the responses, I tried @KirillOsenkov 's suggestion but was unable to see any property reassignment in the log. For now we'll just to an explicitly add the property.

This was my last day with this firm, I have attempted to pass off this issue, but will mark this as closed unless my replacement reopens it.

Thank you!
