### ISSUE TITLE
VS and dotnet build behaves diffrent on missing projects in solutions

### ISSUE THREAD

**Issue by lippinio** [dotnet/msbuild#5976]
### Issue Description
If you have multiple Solutions on the same projects. Some only contains subsets of all projects and one with all Projects. If someone add in project A a reference to a project B in the full solution it can happen, that other solutions that not contains B break. The problem is that VS and dotnet cli behaves different. With dotnet cli everything can be build. But in VS it fails. Because in dotnet build everything is fine it can pass CI gates and developers later have to fix the subsolutions because VS cant handle this.

### Steps to Reproduce
Use the following structure to reproduce the issue or download the zip file.
[AB.zip](https://github.com/dotnet/msbuild/files/5715990/AB.zip)

C:.
│   A.sln
│   AB.sln
│
├───A
│       A.cs
│       A.csproj
│
└───B
        B.cs
        B.csproj

AB.sln
```
Microsoft Visual Studio Solution File, Format Version 12.00
Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "B", "B\B.csproj", "{3C50BE2E-9F33-4B3A-AB0E-17E8B5DDE678}"
EndProject
Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "A", "A\A.csproj", "{4897A731-C11F-4F0D-8D54-131CD74D27B5}"
EndProject
Global
	GlobalSection(SolutionConfigurationPlatforms) = preSolution
		Debug|Any CPU = Debug|Any CPU
		Release|Any CPU = Release|Any CPU
	EndGlobalSection
	GlobalSection(ProjectConfigurationPlatforms) = postSolution
		{3C50BE2E-9F33-4B3A-AB0E-17E8B5DDE678}.Debug|Any CPU.ActiveCfg = Debug|Any CPU
		{3C50BE2E-9F33-4B3A-AB0E-17E8B5DDE678}.Debug|Any CPU.Build.0 = Debug|Any CPU
		{3C50BE2E-9F33-4B3A-AB0E-17E8B5DDE678}.Release|Any CPU.ActiveCfg = Release|Any CPU
		{3C50BE2E-9F33-4B3A-AB0E-17E8B5DDE678}.Release|Any CPU.Build.0 = Release|Any CPU
		{4897A731-C11F-4F0D-8D54-131CD74D27B5}.Debug|Any CPU.ActiveCfg = Debug|Any CPU
		{4897A731-C11F-4F0D-8D54-131CD74D27B5}.Debug|Any CPU.Build.0 = Debug|Any CPU
		{4897A731-C11F-4F0D-8D54-131CD74D27B5}.Release|Any CPU.ActiveCfg = Release|Any CPU
		{4897A731-C11F-4F0D-8D54-131CD74D27B5}.Release|Any CPU.Build.0 = Release|Any CPU
	EndGlobalSection
EndGlobal
```

A.sln
```
Microsoft Visual Studio Solution File, Format Version 12.00
Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "A", ".\A\A.csproj", "{E00D4674-C975-4774-BA72-CB15A30A657E}"
EndProject
Global
	GlobalSection(SolutionConfigurationPlatforms) = preSolution
		Debug|Any CPU = Debug|Any CPU
		Release|Any CPU = Release|Any CPU
	EndGlobalSection
	GlobalSection(ProjectConfigurationPlatforms) = postSolution
		{E00D4674-C975-4774-BA72-CB15A30A657E}.Debug|Any CPU.ActiveCfg = Debug|Any CPU
		{E00D4674-C975-4774-BA72-CB15A30A657E}.Debug|Any CPU.Build.0 = Debug|Any CPU
		{E00D4674-C975-4774-BA72-CB15A30A657E}.Release|Any CPU.ActiveCfg = Release|Any CPU
		{E00D4674-C975-4774-BA72-CB15A30A657E}.Release|Any CPU.Build.0 = Release|Any CPU
	EndGlobalSection
EndGlobal
```

A.csproj
```xml
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net5.0</TargetFramework>
    </PropertyGroup>
    <ItemGroup>
      <ProjectReference Include="..\B\B.csproj" />
    </ItemGroup>
</Project>
```

B.csproj
```xml
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net5.0</TargetFramework>
    </PropertyGroup>
</Project>
```
A.cs
```c#
namespace A
{
    public class A {B.B b = new B.B(); }
}
```

B.cs

```c#
namespace B
{
    public class B   { }
}
```

### Expected Behavior
VS and dotnet build behave the same.

### Actual Behavior
dotnet build builds A.sln and VS doesn't

### Versions & Configurations
dotnet version 5.0.100
visual studio version 16.8.1

**Comment by BenVillalobos** [comment]
Team Triage: A [solution filter](https://docs.microsoft.com/visualstudio/msbuild/solution-filters) would fix the issue you're having here. If you really care about VS building a solution like this, you can open VS on the cmd line using `devenv /build`, though it's not an ideal experience.

When building in VS, projects are built without building their references. A solution here is to manually build the project that lives outside of the solution first.

**Comment by BenVillalobos** [comment]
Team Triage: Closing after a week due to a solution being provided. Feel free to re-open if this doesn't fix your issue.

**Comment by robsonj** [comment]
the above is not a fix
