### ISSUE TITLE
Cannot find reference assemblies for .NET 3.5 using .NET 5.0 SDK

### ISSUE THREAD

**Issue by ganeshnj** [dotnet/msbuild#5985]
### Issue Description
Failed to build .NET Framework 3.5 targeted class library using .NET 5.0 SDK.

### Steps to Reproduce
```
git clone https://github.com/ganeshnj/DotNet5ReferenceAssemblies
cd DotNet5ReferenceAssemblies
dotnet build
```
Output
```
C:\Program Files\dotnet\sdk\5.0.101\Microsoft.Common.CurrentVersion.targets(1180,5): error MSB3644: The reference assemblies for .NETFramework,Version=v3.5 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks [C:\source\repos\DotNet5ReferenceAssemblies\DotNet5ReferenceAssemblies.csproj]
```

### Expected Behavior
This issues existed previously also which was mitigated using [this](https://github.com/dotnet/msbuild/issues/1333#issuecomment-296346352) workaround.

### Actual Behavior
`dotnet build` should build the project.

### Analysis
I suspect .NET 5 CLI introduces some breaking changes that causes this behavior. If I force 3.1 version of .NET Core SDK, build succeeds.

Branch [fix-35-reference-assemblies](https://github.com/ganeshnj/DotNet5ReferenceAssemblies/tree/fix-35-reference-assemblies)

**global.json**
```
{
  "sdk": {
    "version": "3.1.101",
    "rollForward": "latestFeature"
  }
}
```

### Versions & Configurations
```
❯ dotnet --list-sdks
3.1.301 [C:\Program Files\dotnet\sdk]
5.0.101 [C:\Program Files\dotnet\sdk]
```
```
❯ [System.Environment]::OSVersion
Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.18363.0 Microsoft Windows NT 10.0.18363.0
```
### Attach a binlog

[msbuild.zip](https://github.com/dotnet/msbuild/files/5726647/msbuild.zip)

**Comment by alexey-gusarov** [comment]
VS uses msbuild for building and it's works as expected
Rider also have errors on build SDK-style projects with net35 targets

**Comment by alexey-gusarov** [comment]
I found deferent behaviors:

failed build:
![image](https://user-images.githubusercontent.com/2213498/103329945-43d8b400-4a70-11eb-9e32-5e0fbc8cabaa.png)

success build:
![image](https://user-images.githubusercontent.com/2213498/103329980-7bdff700-4a70-11eb-90fe-276a28f465eb.png)

**Comment by alexey-gusarov** [comment]
I've found workaroud

set properties 
```` msbuild
    <FrameworkPathOverride Condition="'$(TargetFramework)' == 'net35'">$(MSBuildProgramFiles32)\Reference Assemblies\Microsoft\Framework\.NETFramework\v3.5\Profile\Client</FrameworkPathOverride>
    <AutomaticallyUseReferenceAssemblyPackages Condition=" '$(TargetFramework)' == 'net35' ">false</AutomaticallyUseReferenceAssemblyPackages>

````

**Comment by Forgind** [comment]
It looks like that means $(MSBuildFrameworkToolsRoot) was evaluated to ''. That's normally set in Microsoft.NetFramework.CurrentVersion.props, but that wasn't imported because `exists('$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.NETFramework.props\ImportBefore')` (`C:\Users\jangirg\AppData\Local\Microsoft\MSBuild\Current\Microsoft.NETFramework.props\ImportBefore`) evaluated to false. Not sure if that's supposed to exist or if one of those properties is set to the wrong value.

**Comment by BenVillalobos** [comment]
@Forgind Try to get a repro going. See what happens if we target netcoreapp3.1
