### ISSUE TITLE
Move importance/verbosity check earlier in logging

### ISSUE THREAD

**Issue by Forgind** [dotnet/msbuild#5992]
Currently, it seems the importance check waits until it reaches the BuildEngine. Might it make more sense to check that a lot earlier, say, in TaskLoggingHelper instead? It would be a little less centralized, and we'd have to expose it, but then we wouldn't have to create strings that we're never going to log, and we can perform some other little optimizations along the way if getting the information that we're not going to log would take a lot of time.

**Comment by BenVillalobos** [comment]
Team Triage: We should have some performance profiling on this to justify the amount of work that would need to happen to get this to work.

**Comment by rokonec** [comment]
@ladipro This might be related to your current log level propagation optimization.
