### ISSUE TITLE
Address issues with ETW traces in Evaluator

### ISSUE THREAD

**Issue by Forgind** [dotnet/msbuild#6039]
Address https://github.com/dotnet/msbuild/pull/5978#discussion_r546126805

**Comment by arkalyanms** [comment]
Yes the count needs to be fixed if this profiling is to be left in there - trying to understand if there is value in this given https://github.com/dotnet/msbuild/blob/master/documentation/evaluation-profiling.md. 

I am the only consumer of this data at the moment. You can keep it parked on me for the moment and I'll fix it or revert it once I get things rolling on #6034.

**Comment by Forgind** [comment]
@arkalyanms, do you have a timeline on when you're planning to tackle this?

**Comment by Forgind** [comment]
Bump @arkalyanms.

Note that while you may be the only consumer, everyone uses evaluate, and #5978 worsened evaluate's perf.
