### ISSUE TITLE
Mono msbuild has broken NuGet.Config

### ISSUE THREAD

**Issue by mfilippov** [dotnet/msbuild#6041]
### Issue Description
I try to build msbuild for mono in Homebrew and I found broken feeds in the latest release version of MSBuild.
### Steps to Reproduce
Checkout repo: https://github.com/mono/msbuild/ on tag: mono/mono-2019-12 
run: ./eng/cibuild_bootstrapped_msbuild.sh --host_type mono --configuration Release --skip_tests

### Expected Behavior
Build is finished without errors.

### Actual Behavior
Restore fail.

### Analysis
I found broken feeds in: https://github.com/mono/msbuild/blob/xplat-master/NuGet.config
https://dotnet.myget.org/F/aspnetcore-release/api/v3/index.json
https://dotnet.myget.org/F/msbuild/api/v3/index.json
https://dotnet.myget.org/F/roslyn/api/v3/index.json
https://dotnet.myget.org/F/nuget-build/api/v3/index.json
https://dotnet.myget.org/F/roslyn-tools/api/v3/index.json

### Versions & Configurations
macOS Big Sur

### Attach a binlog
[build-output-log.txt](https://github.com/dotnet/msbuild/files/5819425/build-output-log.txt)

**Comment by akoeplinger** [comment]
Thanks, I pushed a fix: https://github.com/mono/msbuild/commit/e2e4dfee543269ccb0a459263985b1c993feacec
