### ISSUE TITLE
BinaryFormater serialization of on-disk RAR cache is slow

### ISSUE THREAD

**Issue by rokonec** [dotnet/msbuild#6057]
### Issue Description
BinaryFormater serialization of on-disk RAR cache is slow.
Optimizing deserialization time will likely be synergic with RAR pre-caching goals.

### Steps to Reproduce
Incremental rebuild or Roslyn repo.

### Data
For Roslyn incremental build reading and parsing the RAR cache took almost 40% of RAR wall-clock time.
![image](https://user-images.githubusercontent.com/25249058/105399102-761aa300-5c23-11eb-8ae6-fdec17987a3f.png)

### Analysis
When looking for optimal solution benchmark was create to measure serialization and deserialization of  real project RAR cached data.
![SerializationBenchmarks](https://user-images.githubusercontent.com/25249058/105398521-c2191800-5c22-11eb-903e-aadd8920aea0.png)

After evaluating pros and cons decision has been made to implement serialization as custom binary format, hand written code.

During this decision following was considered:
- CPU performance
- memory performance
- on-disk size
- maintainability
- security
- estimated effort

### Versions & Configurations
Measured at latest production dotnet 5.0.102 SDK.

**Comment by marcpopMSFT** [comment]
@rokonec #6094 is in so closing this out.  Reactivate if you were using this to track any additional changes.
