### ISSUE TITLE
Microsoft.Build.Internal.EngineFileUtilities.GetFileListEscaped is 3x slower for netcore projects

### ISSUE THREAD

**Issue by arkalyanms** [dotnet/msbuild#6061]
Child of #6034. Traces at "\\SLNATSCALE002\CoreVsFramework\Traces\Core_400.etl.zip"

For 400 projects it takes 960ms(netcore) vs 320ms(netframework) and the delta increases with project.

**Comment by ladipro** [comment]
Likely addressed with #6151, will confirm.

**Comment by ladipro** [comment]
Acceptance criteria: The cost of GetFileListEscaped is reduced by at least 20%.
