### ISSUE TITLE
DecorateItemsWithMetadata is 3x slower for netcore projects

### ISSUE THREAD

**Issue by arkalyanms** [dotnet/msbuild#6062]
Child of #6034. Traces at "\\\\SLNATSCALE002\CoreVsFramework\Traces\Core_400.etl.zip"

For 400 projects: 600ms vs 200ms and increases with projects.

**Comment by AR-May** [comment]
I believe that the reason of this function to be 3 times slower is 3 times more metadata in case of netcore projects. (30,340 vs 11,944 items). I can not see how it could be helped here.  We might ask if it is possible to simplify the sdk in this sense. 

There are couple of possible minor improvements for this function, I will make a PR for them shortly.
