### ISSUE TITLE
ProcessMetadataElements 5x slower for netcore projects

### ISSUE THREAD

**Issue by arkalyanms** [dotnet/msbuild#6064]
Child of #6034. Traces at "\SLNATSCALE002\CoreVsFramework\Traces\Core_400.etl.zip"

For 400 projects: 500ms(netcore) vs 110ms(netframework).

**Comment by AR-May** [comment]
Investigation: We have ~3 times more metadata to process, as we found out in #6062. And the epic itself shows 3 times difference. This huge multiplicity factor (5x) seems as a fluke to me. I performed additional measurements for this function and on my dev machine got 2142 msec (netcore) and 651 msec (netframework) in average. Which gives us multiplicity factor ~3.2. 
Code changes: Similar to issue #6062, there were some minor changes that we can do to this function. We have already done them (together with changes for #6062) in PR #6529.
