### ISSUE TITLE
LogProjectEvaluationStarted is expensive for netcore and increases with projects

### ISSUE THREAD

**Issue by arkalyanms** [dotnet/msbuild#6065]
Child of #6034. Traces at "\SLNATSCALE002\CoreVsFramework\Traces\Core_400.etl.zip"

For 400 projects it takes about 120ms.

**Comment by ladipro** [comment]
Acceptance criteria: The cost of LogProjectEvaluationStarted is reduced by at least 20%.

**Comment by ladipro** [comment]
@arkalyanms, >95% of the time is spent in the logger on VS side. Same as #6066, assigning to you to take a look. 

![image](https://user-images.githubusercontent.com/12206368/110937201-530e9480-8332-11eb-9595-48a4f06df006.png)

**Comment by arkalyanms** [comment]
Moved to CPS in https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1303828.
