### ISSUE TITLE
LoggingContext.LogBuildEvent is slow but has a static cost

### ISSUE THREAD

**Issue by arkalyanms** [dotnet/msbuild#6066]
Child of #6034. Traces at "\SLNATSCALE002\CoreVsFramework\Traces\Core_400.etl.zip"

Static cost, still a log build event taking 50ms

**Comment by drewnoakes** [comment]
What do you mean by "static cost"?

**Comment by arkalyanms** [comment]
It doesn’t increase with the increase in projects in the solution.

**Comment by ladipro** [comment]
Acceptance criteria: The cost of LogBuildEvent is reduced by at least 20%.

**Comment by ladipro** [comment]
@arkalyanms most of the cost actually comes from `MultithreadedProjectCollectionHost+ProjectCollectionLogger` in Microsoft.VisualStudio.ProjectSystem.Implementation. There's also some lock contention but ~20 ms doesn't look like something worth pursuing, and would naturally go down if the logger gets faster.

![image](https://user-images.githubusercontent.com/12206368/110771794-32274000-825b-11eb-8b59-7062308a8953.png)

**Comment by arkalyanms** [comment]
Moved to CPS in https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1303828
