### ISSUE TITLE
Expand the MSBuild optprof scenarios to have more representative dotnet/project-system + CPS scenarios

### ISSUE THREAD

**Issue by arkalyanms** [dotnet/msbuild#6067]
Child of #6034. Traces at "\SLNATSCALE002\CoreVsFramework\Traces\Core_400.etl.zip"

100ms each:
- ~JITutil_MonReliableContention and JIT_MonReliableEnter~
- Few cold ngens showing up as new jit entries that all contribute >50ms. Example: microsoft.build.ni![COLD]

**Comment by ladipro** [comment]
Note: Understand how optprof works with full NGEN.
