### ISSUE TITLE
Glob pattern matching improvements for netcore/CPS (~1s during solution load of 400 projects)

### ISSUE THREAD

**Issue by arkalyanms** [dotnet/msbuild#6069]
Child of #6034.

Globs were not a hot path before with netframework, but with CPS using globs, the pattern matching can be optimized, say for example by extension first before groveling through disk. 

Below is the default set of blobs from CPS/netcore that comes with every project:

glob | excludedPatterns
-- | --
`**/*.cs` | `**/*.vssscc`, `obj\/**`, `**/*.sln`, `**/*.*proj`, `**/*.user`, `**/.*/**`, `bin\/**`, `bin\Debug\/**`, `obj\Debug\/**`
`**/*.resx` | `**/*.vssscc`, `obj\/**`, `**/*.sln`, `**/*.*proj`, `**/*.user`, `**/.*/**`, `bin\/**`, `bin\Debug\/**`, `obj\Debug\/**`
`**/*` | `**/*.vssscc`, `obj\/**`, `**/*.sln`, `**/*.*proj`, `**/*.user`, `**/.*/**`, `**/*.resx`, `bin\/**`, `bin\Debug\/**`, `**/*.cs`, `obj\Debug\/**`

**Comment by ladipro** [comment]
Observation: We are evaluating globs even if the corresponding item type is not used. The `None` items declared in the SDK are a good example.

**Comment by drewnoakes** [comment]
@ladipro `None` items are used by the Project System. Removing a text file from `None` causes it to disappear in Solution Explorer, for example.

**Comment by ladipro** [comment]
@drewnoakes thank you, that makes sense. Although I still wonder if we can avoid doing this work when building on the command line with `dotnet build`.
