### ISSUE TITLE
ApplyChangeWaves reads Environment every time

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/msbuild#6077]
I'm seeing ApplyChangeWave showing up in profiles:

https://github.com/dotnet/msbuild/blob/f98579d50f8b08c4efe13ca07327e3e5222b50f8/src/Framework/ChangeWaves.cs#L113

Shouldn't it cache the environment read?

![image](https://user-images.githubusercontent.com/679326/105649435-262b1e80-5e65-11eb-8ac9-66cd78eb0170.png)

**Comment by BenVillalobos** [comment]
I believe it did cache previously, but had to be switched. I can't seem to remember why. I'll dig into the commit history.
