### ISSUE TITLE
Could not find SDK "Foo, Version=1.0" error when Win10 SDK installed to custom path

### ISSUE THREAD

**Issue by MSLukeWest** [dotnet/msbuild#6090]
### Issue Description
Microsoft.Common.CurrentVersion.targets sets SDKExtensionDirectoryRoot paths in a way that doesn't properly handle non-default Win10 SDK install locations

### Steps to Reproduce
1. Install the Win10 SDK to a non-default directory (for example on the d: drive).
2. Create a UWP project (repros for both C# and C++)
3. Add the following to the project file (Note: update 18362 to a different SDK version based on what you have installed)

  ```
<ItemGroup>
    <SDKReference Include="WindowsMobile, Version=10.0.18362.0" />
  </ItemGroup>
```

4. Build

A more practical repro using Unity is described in this Visual Studio feedback item: https://developercommunity2.visualstudio.com/t/HoloLens-2-build-fails-if-Windows-sdk-is/1313568

### Expected Behavior
Build succeeds, SDK is found correctly

### Actual Behavior
Error: Could not find SDK "WindowsMobile, Version=10.0.18362.0".

### Analysis
See here: https://github.com/dotnet/msbuild/blob/ec6ed832e6a4adf94a2e6ff7e2f34d8e2da1cc05/src/Tasks/Microsoft.Common.CurrentVersion.targets#L2348

It's always looking for the Win10 SDK root under program files ($(MSBuildProgramFiles32)\Windows Kits\10).  It should instead get the root from the registry value "HKLM\SOFTWARE\Microsoft\Windows Kits\Installed Roots" @KitsRoot10

### Versions & Configurations
16.8

**Comment by Forgind** [comment]
Team triage:
It sounds like a solution might be to update the default behavior on https://github.com/dotnet/msbuild/blob/ec6ed832e6a4adf94a2e6ff7e2f34d8e2da1cc05/src/Tasks/Microsoft.Common.CurrentVersion.targets#L2348

Alternatively, you could work around this by setting SDKExtensionDirectoryRoot yourself before building.

**Comment by CaptainBaxter** [comment]
Hi all, thanks for your support. I am also receiving this error, is this on the agenda for a fix? Having to remove the broken reference every build adds a lot to development time and makes the whole process quite jarring.
