### ISSUE TITLE
"Confidential" notice in Shared Code.doc

### ISSUE THREAD

**Issue by omajid** [dotnet/msbuild#6095]
### Issue Description

msbuild's code is open source under the MIT license. This allows anyone to examine, modify and distribute the sources (among other things). However, the source code repository includes a documentation file that has a "Microsoft Confidential" notice: 

https://github.com/dotnet/msbuild/blob/master/src/Shared/Shared%20Code.doc

I suspect this is a mistake since there is a lot of documentation in `.md` files in this repository; those files do not carry such a notice.

I am not sure what that means, legally speaking: is this file under a non-free license?

As an aside, perhaps that document should be converted to markdown like all other documentation files in this repo? There are no other `.doc` files in this repo.

### Steps to Reproduce

Try and read https://github.com/dotnet/msbuild/blob/master/src/Shared/Shared%20Code.doc

### Expected Behavior

This is all open source and publicly usable

### Actual Behavior

There's a "Microsoft Confidential" notice.

**Comment by omajid** [comment]
cc @tmds @leecow @dleeapho

**Comment by leecow** [comment]
@marcpopMSFT @KathleenDollard to triage and determine what to do with this.

**Comment by marcpopMSFT** [comment]
That looks like a really old document that likely came over from the pre-open source days. I have no concerns just removing the confidential notice since everything in the repo is already covered by a license.

**Comment by omajid** [comment]
FWIW, it's still referred to by developers: https://github.com/dotnet/msbuild/pull/6053#pullrequestreview-576485077

**Comment by kit-repo-depot** [comment]
If this still needs converted I'd like to do that!
