### ISSUE TITLE
SignFile task referenced, but not provided, in Microsoft.Build.Tasks.Core

### ISSUE THREAD

**Issue by Zastai** [dotnet/msbuild#6098]
When using `dotnet build`, attempting to sign assemblies results in

```
error MSB4062: The "Microsoft.Build.Tasks.SignFile" task could not be loaded from the assembly Microsoft.Build.Tasks.Core, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a.
Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.
```

It is declared in Microsoft.Common.tasks:

```xml
    <UsingTask TaskName="Microsoft.Build.Tasks.SignFile"                              AssemblyName="Microsoft.Build.Tasks.Core, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" Condition="'$(MSBuildAssemblyVersion)' != ''" />
```

It looks like the task is only present in the .NET Framework version of the assembly, not in the standard/core version.

Oddly, the backend signing methods ARE present in the core assembly (`SecurityUtilities.SignFile()`), so there does not seem to be any reason to omit the task.

The task should be added to the standard/core assembly too; on non-Windows it can fail with PNSE, but on Windows it should work with `dotnet build` the same way it does with `msbuild`.

If that is not possible, it should still be added so that it can give a useful error rather than MSB4062, because that suggests user/configuration error.

**Comment by j5aenz** [comment]
I am currently having this issues as well. I have tried to publish using other methods and this is the most descriptive message. so far. It does look like a compatibility issue between net5 and msbuild. i am targeting net5-windows10.0.19041.0.

**Comment by BenVillalobos** [comment]
@sujitnayak is it reasonable to enable this task on .NET Core on Windows?

**Comment by sujitnayak** [comment]
Yes it should be reasonable to support this during build. For ClickOnce publish that also call SignFile, we don't support the dotnet CLI yet.

**Comment by BenVillalobos** [comment]
Team Triage: Since there are some scenarios that won't be supported, we can enable SignFile. We're open to taking a PR as this isn't high priority for us
