### ISSUE TITLE
Circular dependency with DependsOnTargets/AfterTargets combination

### ISSUE THREAD

**Issue by iskiselev** [dotnet/msbuild#6111]
MSBuild can't solve target dependencies order and show MSB4006 error in some specific case

### Steps to Reproduce
1. Use next msbuild file:
```xml
<Project>
  <Target Name="Primary" >
    <Message Text="Primary" Importance="high"/>
  </Target>
  
  <Target Name="Dependend" DependsOnTargets="Primary">
    <Message Text="Dependend" Importance="high"/>
  </Target>

  <Target Name="AddOn" DependsOnTargets="Dependend" AfterTargets="Primary">
    <Message Text="AddOn" Importance="high"/>
  </Target>
</Project>
```
2. Run: `msbuild /t:Dependend`

### Expected Behavior
MSBuild will run all three targets in next order: Primary, Dependend, AddOn.

### Actual Behavior
MSbuild fails with:
```
"C:\appd\agent-java-dotnet\dotnet_agent\AzureSiteExtensions\test\test.csproj" (Dependend target) (1) ->
  C:\appd\agent-java-dotnet\dotnet_agent\AzureSiteExtensions\test\test.csproj(10,24): error MSB4006: There is a circula
r dependency in the target dependency graph involving target "Dependend".
```

### Analysis
The project has target `AddOn` that should be if `AddOn` target was executed, but after `Dependend` execution. If either AddOn or Primary will be initial target - build will complete successfully (with execution of all target in same order). The problem can be workaround, if `AddOn` AfterTarget will have both `Primary;Dependend`

**Comment by BenVillalobos** [comment]
Team Triage: I think the confusion here might be with `AfterTargets`. `AfterTargets`specifies that `AddOn` must run before `Primary`. In this project you're saying `Addon` must run before depended, and after primary, which creates the circular dependency.

This is working as intended. Feel free to reopen for discussion.

**Comment by iskiselev** [comment]
@BenVillalobos , `AfterTargets` specifies that `AddOn` must run **after** `Primary` , not before - so there is no real cycle,

**Comment by ladipro** [comment]
Apologies for jumping the gun @iskiselev, it is largely my fault. I am reopening the ticket.

**Comment by Forgind** [comment]
@haiyuzhu, since you wrote this recently, do you want to take a stab at fixing it? If not, I can.

**Comment by Forgind** [comment]
Team triage:
In MSBuild, Target dependencies do not form a graph. They are defined [here](https://docs.microsoft.com/visualstudio/msbuild/target-build-order#determine-the-target-build-order). If we were to change how this works, that would be a breaking change even if it would be easier to understand.
