### ISSUE TITLE
How to make a ProjectReference TargetFramework-agnostic?

### ISSUE THREAD

**Issue by Zastai** [dotnet/msbuild#6134]
### Issue Description
- I have a solution with
   1. A project that builds an MSBuild build task (which instruments a built assembly)
      This targets `net472` and `netcoreapp2.1` (for use with `MSBuild.exe` and `dotnet build`, respectively)
   2. Several projects that use that build task:
      - these target `net472`, `netcoreapp2.1` and `netcoreapp3.1`
      - they have a `ProjectReference` pointing to it, with `ReferenceOutputAssembly="False"` on it
      - they import a .targets file to use it
        - this is hooked as `AfterTargets="CopyFilesToOutputDirectory"` so that it can operate on a clean assembly under `bin`
- Solution-level build ordering is _not_ used (it is a goal that all projects build correctly even without the solution present)

This all builds perfectly fine under normal circumstances.

There are two issues:
- despite the `ReferenceOutputAssembly="False"`, there are warnings issued if the referenced project does not target a compatible framework (e.g. if the build task project only targets `net472`, the referencing projects complain because of their netcoreapp targets)
- when building using `msbuild -m`, it may happen that applying the build task fails because it has not been built yet
  - msbuild in use, so the net472 assembly of the build task will be used
  - build task gets built for netcoreapp2.1
  - referencing project gets built for netcoreapp3.1 <-- _too early! need net472 build of build task_
  - so: there seems to be an assumption that, even with `ReferenceOutputAssembly="False"`, the build scheduling can treat the project reference as target-framework specific

### Expected Behavior
1. no diagnostics about target frameworks of a project referenced with `ReferenceOutputAssembly="False"`
2. build scheduling waits for full build of referenced project before building a referencing project

### Actual Behavior
1. diagnostics issued
2. build scheduling may build a referencing project too early

### Ask us questions
Is there a way to ensure build order at the project level instead of at the project+target level?

**Comment by BenVillalobos** [comment]
Team Triage: Can you provide a minimal project that reproduces this behavior?

**Comment by Zastai** [comment]
I'll have a look - it should not be too hard to contrive an small scale case.

**Comment by Zastai** [comment]
I have created https://github.com/Zastai/msbuild-6134/ as a test case.

While this reproduces the spurious warning about mismatched framework, I have so far been unable to reproduce the build scheduling issue. Will try again tomorrow or over the weekend.

**Comment by Zastai** [comment]
Looks like the `Exec` I used to make the build task project take some time was causing "correct" scheduling as a side-effect.
After adding ` YieldDuringToolExecution="true"` to it, the issue is now entirely reproducible.

Simply running

```powershell
rm -r */bin, */obj; dotnet build -m
```

reproduces the issue.
You see the build task building its `net472` target, then the consumer for the `net472` target - but because `dotnet build` was used, the build targets want to use the build task's `netcoreapp2.1` output.

**Comment by ladipro** [comment]
@Zastai thank you for the repro. I was able to make your scenario work by adding the `SetTargetFramework` metadatum to the `ProjectReference` item to explicitly specify which target of build-task it's depending on. I wouldn't say the framework mismatch warning is spurious. On the contrary, it's very relevant because it's explaining why the task has not been built when you need it.

Here's how I modified the `ProjectReference`. Also note I replaced `ReferenceBuildOutput` with `ReferenceOutputAssembly` as the former is not a well-known metadatum and would have no effect.

```xml
    <ProjectReference
        Include="..\build-task\build-task.csproj"
        ReferenceOutputAssembly="False"
        SetTargetFramework="TargetFramework=netcoreapp2.1" />  
```

Let me know if this resolves your issue.

**Comment by Zastai** [comment]
Yes, the `ReferenceOutputAssembly` was my mistake when setting up the test repo; my real-world case uses it correctly.

Looks like I managed to miss the documentation for `SetTargetFramework`; it's slightly odd that it needs to include the `TargetFramework=` part, but 🤷.

So in order to handle both core and desktop, I would need
```xml
<ProjectReference Include="..\build-task\build-task.csproj" ReferenceOutputAssembly="False">
  <SetTargetFramework Condition=" '$(MSBuildRuntimeType)' == 'Full' ">TargetFramework=net472</SetTargetFramework>
  <SetTargetFramework Condition=" '$(MSBuildRuntimeType)' != 'Full' ">TargetFramework=netcoreapp2.1</SetTargetFramework>
</ProjectReference>
```
While it's a bit more verbose than I would like, it does work.
And I suppose I could put it in the .targets file to avoid repeating it.

Thanks for the assistance.
