### ISSUE TITLE
Linux compilation works from Visual Studio 2019, but does not from command line on the linux machine

### ISSUE THREAD

**Issue by tigranmt** [dotnet/msbuild#6144]
### Issue Description
The sample project is possible to build from Visual Studio 2019 targeting WSL2, but once moved compilation to the WSL2  from command line, there is a linkage error. The project uses linked external library delivered by vcpckg. 

### Steps to Reproduce
Sample code as  

```
#include <iostream>
#include "arrow/array/array_primitive.h"
#include "arrow/array/array_base.h"
#include "arrow/io/file.h"
#include "arrow/type_fwd.h"

int main() {
	auto* ptr = arrow::default_memory_pool();
	std::cout << "Hello \n";
}
```
Provided vcpkg exists on the target linux machine, in this case it is WSL2 , Ubuntu 20.04.1 LTS, what I do is 

1) Copy vcxproj file into the source folder of the Linux machine  
2) sudo apt-get install -y dos2unix
3) sudo dotnet new -i GCC.Build.Template
4) sudo dotnet new gccbuild --allow-scripts=yes
5) set VCTargetsPath env variable to "./"

dotnet build -p:Configuration=Release -p:Platform=x64 

### Expected Behavior
Compilation has to be successful as it happens when it's launched from the VS 2019

### Actual Behavior
Compilation on linkage to the external library (apache arrow in this case) , fails when invoked form cmdline.
The error I get is: "undefined reference to arrow::default_memory_pool()" on linkage. There is no such error when it's compiled from VS 2019, on the same WSL2, which means same, "machine" and same code layout, in my understanding.
### Ask us questions

Should something else to be done, before invoking cmdline MsBuild compilation, in order to make it work ?

**Comment by BenVillalobos** [comment]
Team Triage: What is the exact issue you're seeing? Does running `msbuild -p:Configuration=release -p:Platform=x64` have the same result?

**Comment by tigranmt** [comment]
the error I get is:  "undefined reference to arrow::default_memory_pool()" on linkage. There is no such error when it's compiled from VS 2019, with _on the same WSL2_, which means same, "machine" and same code layout.

**Comment by tigranmt** [comment]
This turned to be a path issue, once adjusted properly, on this sample, it compiles as it was expected.
