### ISSUE TITLE
Unable to publish Blazor app because path length

### ISSUE THREAD

**Issue by astrowalker** [dotnet/msbuild#6149]
This is repost of report against Blazor: https://github.com/dotnet/aspnetcore/issues/30067

### Describe the bug

I have Blazor web client project which I can run OK both from Visual Studio 2019 (16.8.4) and from command line. Now I would like to publish this project into local folder (I used the defaults -- "bin\Release\net5.0\browser-wasm\publish\"). When I hit Publish I got this output:

> C:\Program Files\dotnet\sdk\5.0.103\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Publish.targets(237,5): Warning MSB3026: Could not copy "C:\Users\macias\.nuget\packages\microsoft.aspnetcore.components.webassembly.authentication\5.0.3\staticwebassets\AuthenticationService.js" to "D:\temp\Xxxxxxx\Aaa-AAA\PpppppppppppOooooo\Xxxxxxx.Yyyyyy.Zzzzzzzzzzzzzzzzzz\Xxxxxxx.Yyyyyy.Zzzzzzzzzzzzzzzzzz.WebBlazor\Client\obj\Release\net5.0\browser-wasm\PubTmp\Out\wwwroot\_content\Microsoft.AspNetCore.Components.WebAssembly.Authentication\AuthenticationService.js". Beginning retry 1 in 1000ms. Could not find a part of the path 'D:\temp\Xxxxxxx\Aaa-AAA\PpppppppppppOooooo\Xxxxxxx.Yyyyyy.Zzzzzzzzzzzzzzzzzz\Xxxxxxx.Yyyyyy.Zzzzzzzzzzzzzzzzzz.WebBlazor\Client\obj\Release\net5.0\browser-wasm\PubTmp\Out\wwwroot\_content\Microsoft.AspNetCore.Components.WebAssembly.Authentication\AuthenticationService.js'. 

The source file exists, the destination directory exists. I can copy the file manually, no problem. 

When I copy the file myself first, and then try to publish I got extra error first stating

> C:\Program Files\dotnet\sdk\5.0.103\Sdks\Microsoft.NET.Sdk.Publish\targets\CopyTargets\Microsoft.NET.Sdk.Publish.CopyFiles.targets(50,5): Warning MSB3231: Unable to remove directory "D:\temp\Xxxxxxx\Aaa-AAA\PpppppppppppOooooo\Xxxxxxx.Yyyyyy.Zzzzzzzzzzzzzzzzzz\Xxxxxxx.Yyyyyy.Zzzzzzzzzzzzzzzzzz.WebBlazor\Client\obj\Release\net5.0\browser-wasm\PubTmp\Out\". Could not find a part of the path 'AuthenticationService.js'.

### To Reproduce

Create example Blazor app located in flat/short directory, like d:\test. This will work.

Create example Blazor app located in somewhat longer path (as above). This will work initially, but then just install nuget package to web client project "Microsoft.AspNetCore.Components.WebAssembly.Authentication" and this will tip over the path limit -- this won't work (i.e. you will not be able to publish web client).

#### Issues found

I see here several issues which I think should be addressed:

* the error messages are misleading, "cannot copy" is maybe accurate internally, but should be spelled out as "path is too long"
* more serious one -- since total length path in Windows is limited to 260 characters, it is good to take user part and "infrastructure" part into consideration. The latter is this sequence "\obj\Release\net5.0\browser-wasm\PubTmp\Out\wwwroot\_content\Microsoft.AspNetCore.Components.WebAssembly.Authentication\AuthenticationService.js" (it is 145 characters long). It means the user controls only 115 characters. It might seem like a lot but after you move from naming your project "BlazorApp1" you can quickly exceed the limit. Besides common sense tells that taking majoriy of space from the user is kind of unfair :-)
* maybe minor thing, but still, it is kind of "surprise" effect when you can build you app, run it (path length is not exceeded), and yet you cannot publish just because of the way publish internally works (I can change the publish target folder, but the error is about "obj" not target)

### Further technical details
ASP.NET 5.0

PM> dotnet --info
.NET SDK (reflecting any global.json):
 Version:   5.0.102
 Commit:    71365b4d42

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.102\

Host (useful for support):
  Version: 5.0.2
  Commit:  cb5f173b96

.NET SDKs installed:
  2.1.104 [C:\Program Files\dotnet\sdk]
  2.1.201 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.402 [C:\Program Files\dotnet\sdk]
  2.1.403 [C:\Program Files\dotnet\sdk]
  2.1.504 [C:\Program Files\dotnet\sdk]
  2.1.509 [C:\Program Files\dotnet\sdk]
  2.1.513 [C:\Program Files\dotnet\sdk]
  2.1.602 [C:\Program Files\dotnet\sdk]
  2.2.104 [C:\Program Files\dotnet\sdk]
  5.0.101 [C:\Program Files\dotnet\sdk]
  5.0.102 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.24 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.24 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.24 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by Forgind** [comment]
https://github.com/dotnet/msbuild/issues/53#issuecomment-459062618

It isn't perfect, but I think that's the best we can offer. MSBuild supports long paths, but not all the tools around it do.

**Comment by astrowalker** [comment]
@Forgind , "the best"? The prefix of the path is "\obj\Release\net5.0\browser-wasm\PubTmp\Out", from top of my head "\obj\Release\net5.0\wasm\" -- here, it is shorter making more space for the user.

Secondly, the message is really also "the best"? I would say "Cannot use path XYZ because it exceeds the limit of ABC characters" is way more useful.

**Comment by Forgind** [comment]
Closing this was probably premature. We can improve the error experience (possibly just adding a catch in Copy.cs, though I would've thought [this](https://github.com/dotnet/msbuild/blob/6819f7ab06c3f43e83ff4059d417395e0af06c01/src/Tasks/Copy.cs#L749) would do it) here, but I don't think we can change the path.

**Comment by djthegr8** [comment]
I think that along with MSBuild, this is a fundamental problem in (probably) .NET or maybe `System.IO`, as I'm *frequently* getting `System.IO.FileNotFoundException` in cases where the exception should've ideally been PathTooLong, for example in the screenshot attached. 
![image](https://user-images.githubusercontent.com/44142719/118684116-92200100-b81f-11eb-8ae1-5659451f89cb.png)
Maybe this is a bug upstream?

**Comment by MikkelChristensen3Shape** [comment]
> Closing this was probably premature. We can improve the error experience (possibly just adding a catch in Copy.cs, though I would've thought [this](https://github.com/dotnet/msbuild/blob/6819f7ab06c3f43e83ff4059d417395e0af06c01/src/Tasks/Copy.cs#L749) would do it) here, but I don't think we can change the path.

Who can change the path?  dotnet/aspnetcore refused to do anything about this and redirected the OP to you.
