### ISSUE TITLE
Debugging fails when using PathMap in dotnet5 csproj

### ISSUE THREAD

**Issue by lonix1** [dotnet/msbuild#6167]
I'm not sure which repo this belongs in, sorry.

### Issue Description
I want to conceal the original paths from my assembly and from its stack traces. So I use this in my `.csproj` ([source1](https://www.codementor.io/@rowlandbanks/cleaner-stacktraces-13q3hbv2s7)) ([source2](https://stackoverflow.com/a/66221592/9971404)):
````xml
<PropertyGroup>
  <PathMap>$([System.IO.Path]::GetFullPath('$(MSBuildThisFileDirectory)'))=./</PathMap>
</PropertyGroup>
````
This works when building and running. It does not work when debugging in vscode.

When I set any breakpoint, it fails. For example any breakpoint I set in `Program.cs` gives this error when the debug session starts:
> Could not load source './Program.cs': Incorrect format of 'source' message..

I also tried:
````xml
<PropertyGroup Condition="'$(Configuration)' != 'Debug'">
````

### Steps to Reproduce
- `dotnet new webapp`
- generate default `tasks.json` and `launch.json`
- add above code to `MyProject.csproj`
- add breakpoint in any `.cs` file
- start debugging

### Versions & Configurations
linux ubuntu latest
vscode latest - 1.53.2
omnisharp plugin latest - 1.23.9
dotnet sdk latest - 5.0.103

**Comment by ladipro** [comment]
@lonix1 MSBuild just passes the `PathMap` property to compilers, unlikely to be the culprit here. Can you please open an issue in the [microsoft/vscode](https://github.com/microsoft/vscode) repo? It's a different organization so I can't simply move this issue there.

**Comment by lonix1** [comment]
Thanks. I'm unsure whether the problem is vscode itself, so I moved it to the omnisharp extension's repo.
