### ISSUE TITLE
Building WPF project fails intermittently

### ISSUE THREAD

**Issue by swesonga** [dotnet/msbuild#6170]
### Issue Description
Building the project system solution works when I'm making changes in VS but after some time the build starts failing with the error below:

```
2>C:\WINDOWS\Microsoft.NET\Framework\v4.0.30319\Microsoft.WinFx.targets(712,5): error BG1002: File 'D:\dev\repos\project-system\artifacts\Debug\obj\Microsoft.VisualStudio.ProjectSystem.Managed.VS\ProjectSystem\VS\UI\DontShowAgainMessageBox.baml' cannot be found.
2>Done building project "Microsoft.VisualStudio.ProjectSystem.Managed.VS.csproj" -- FAILED.
```

Switching to a command line build still results in the same error so it is not unique to Visual Studio.

### Steps to Reproduce

1. Clone https://github.com/dotnet/project-system
2. Run `build.cmd /diagnostic`

### Versions & Configurations
Microsoft (R) Build Engine version 16.10.0-preview-21105-01+13de7ba2b for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

16.10.0.10501

### Binlog
[wesonga-build.zip](https://github.com/dotnet/msbuild/files/5999192/wesonga-build.zip)

**Comment by BenVillalobos** [comment]
Notes from my debug session on 2/16:

When I saw it repro, I saw `DontShowAgainMessageBox.baml` get deleted and created multiple times during a single `build.cmd` call. The problem is, somehow my machine stopped reproducing it after the 1st or 2nd try, and I couldn't save the binlog.

Currently still thinking it's a race condition of some kind.

**Comment by swesonga** [comment]
@BenVillalobos  I think the attached binlogs should be similar to the ones you would get from your repro.

**Comment by rainersigwald** [comment]
@swesonga are you still seeing this? Can you get a [procmon](https://docs.microsoft.com/en-us/sysinternals/downloads/procmon) trace of filesystem activity for one of the builds? From the log, `MarkupCompilePass1` appears to create the file, and nothing in the log mentions deleting it. That makes me suspect an external process.

**Comment by marner2** [comment]
I'm seeing the same thing, although it is exclusively from the command line and not VS. Any explanation?
