### ISSUE TITLE
Replace CopyOnReadEnumerable with immutable collections

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/msbuild#6176]
The whole machinery around ProjectPropertyInstanceEnumeratorProxy, ProjectItemInstanceEnumeratorProxy, ItemDictionary<T> and CopyOnReadEnumerable could really benefit from immutable collections. 

A lot of unnecessary work and allocations are happening to enumerate properties and items.

**Comment by KirillOsenkov** [comment]
I pulled on the string some more and ended up in ProjectInstance, where `_items` is set in several places, including Translator. It might make sense to just use a lighterweight read-only collection in situations where items are deserialized such that we don't have to clone and use CopyOnWrite. Maybe seal the items themselves somehow (like use TaskItemData) to avoid wrapping each item in ProjectItemInstance.TaskItem.

**Comment by KirillOsenkov** [comment]
Russian Dolls:
![image](https://user-images.githubusercontent.com/679326/108614685-94ee8f80-73b1-11eb-8eec-5e851ab9837a.png)

**Comment by ladipro** [comment]
@KirillOsenkov I have eliminated redundant deep cloning in the attached PR. I don't think it's worth optimizing further as this work/allocations are relatively minor. When building a medium sized solution with `/v:diag` we spend ~80 ms and allocate ~1.2 MB in `BaseConsoleLogger.ExtractItemList` and `BaseConsoleLogger.ExtractPropertyList` combined. For both metrics this is about 0.1% of total.

**Comment by KirillOsenkov** [comment]
@ladipro nice, thanks!

I've also found https://source.dot.net/#Microsoft.Build/BackEnd/Components/Logging/TargetLoggingContext.cs,d99a8dbf081f1a4d,references

Should we do the same thing for target items too? Shall we file a separate issue?

**Comment by KirillOsenkov** [comment]
Also see related:
https://github.com/dotnet/msbuild/issues/6704

Since items aren't truly immutable, we have a bug where we capture the live data structure for logging instead of capturing an immutable snapshot. If the core data structures are truly immutable, we can give an immutable snapshot to loggers without any copying whatsoever, this will also avoid allocations.

**Comment by KirillOsenkov** [comment]
Specifically, see this comment:
https://github.com/dotnet/msbuild/blob/a59d7a533c9154e8aa99b823625e7eff199ddf1a/src/Build/Logging/BinaryLogger/BuildEventArgsWriter.cs#L744-L753

**Comment by ladipro** [comment]
> Should we do the same thing for target items too? Shall we file a separate issue?

Yes to both! If you file an issue, may I ask you to include a high-level description of the MSBuild logging infra? How log events flow today and the shortcomings / inefficiencies you are aware of.

**Comment by KirillOsenkov** [comment]
OK here you go: https://github.com/dotnet/msbuild/issues/7142
