### ISSUE TITLE
Microsoft.Build.Utilities.v4.0.dll is loaded from the GAC

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/msbuild#6179]
NuGet.Build.Tasks.dll (C:\msbuild\artifacts\bin\bootstrap\net472\Common7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.Build.Tasks.dll) references v4.0.dll and it gets loaded from the GAC

**Comment by KirillOsenkov** [comment]
Add this code to the Main() method in XMake.cs to catch MSBuild assemblies loaded from the GAC:

```
            AppDomain.CurrentDomain.AssemblyLoad += (s, e) =>
            {
                if (e.LoadedAssembly is Assembly loaded)
                {
                    if (loaded.FullName.Contains("Build") &&
                        loaded.Location is string location &&
                        location.StartsWith(Environment.GetFolderPath(Environment.SpecialFolder.Windows), StringComparison.OrdinalIgnoreCase))
                    {
                    }
                }
            };
```

We should perhaps even capture the callstack using `new StackTrace().ToString()` and log warnings for each MSBuild assembly loaded from the GAC including the callstack that loaded it.

**Comment by sharwell** [comment]
> log warnings for each MSBuild assembly loaded from the GAC including the callstack that loaded it.

This will be followed by loads of sadness.

**Comment by KirillOsenkov** [comment]
Sure we can log a message if verbosity is diag

**Comment by Forgind** [comment]
Team triage: @KirillOsenkov, can you clarify what is wrong with loading M.B.Utilities.v4.0.dll from the GAC? I thought that was expected behavior.

**Comment by KirillOsenkov** [comment]
I thought having MSBuild .dlls in the GAC is bad? Or is the v4.0.dll in the GAC fine? I thought we had tooling to detect and UnGAC .dlls? If it's benign then I suppose we can close this issue.

But also why is NuGet.Build.Tasks.dll even referencing the v4.0.dll?

**Comment by Forgind** [comment]
Ah, yes. Having MSBuild version 15.1.0.0 .dlls in the GAC is bad because then that overrides our normal assembly loading, but that only applies if it's the same version as the one we're trying to ship. v4.0.0 won't affect that, whether it's in the GAC or not. I don't remember exactly why 4.0.0 should be in the GAC—something related to TaskHost maybe?—but it is supposed to be there.

**Comment by KirillOsenkov** [comment]
How does it work when we copy bootstrap MSBuild to a machine where MSBuild is mot installed? Does 4.0 ship in the GAC as part of .NET Framework or will a local copy be loaded in that case?

**Comment by Forgind** [comment]
@rainersigwald can correct me if I'm wrong, but I believe it's installed as part of the framework. When I've installed VS on a clean machine, it seems to be put in the GAC, and for that sort of thing, I don't choose too many workloads, so either it comes with the framework or it's automatically in the GAC as part of Windows.

**Comment by rainersigwald** [comment]
Yeah, MSBuild 4.0 was part of .NET framework, so that assembly is always available if we can run. I suspect NuGet has just linked against it for a bajillion years and it has continued to work. I hope it's not because they're still supporting dev11!
