### ISSUE TITLE
CopyOnWriteDictionary in Microsoft.Build.Utilities.v4.0.dll doesn't work with List`1.AddRange

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/msbuild#6180]
If Microsoft.Build.Utilities.v4.0.dll is loaded from the GAC during the build (e.g. by NuGet.Build.Tasks.dll) and CopyOnWriteDictionary<K,V> is used in `List<T>.AddRange()` to enumerate, you will get a malformed list back full of null elements.

This is because AddRange has a special case for `ICollection<T>` that COWDictionary wasn't designed for:
https://referencesource.microsoft.com/#mscorlib/system/collections/generic/list.cs,712

**Comment by rainersigwald** [comment]
I don't think there's any way this will meet the bar for servicing .NET Framework 4.8. Is there any way for us to work around in current code, or do we just have to live with this? How did you notice it in the first place?

**Comment by KirillOsenkov** [comment]
I tried AddRange here and it just added all nulls:
https://github.com/dotnet/msbuild/blob/18a8ddcb5bdfa16357ae2350b09cafcbc3550f13/src/Build/Logging/BinaryLogger/BuildEventArgsWriter.cs#L901-L908

**Comment by KirillOsenkov** [comment]
As far as I can tell, there's nothing wrong in the Framework here, it's just our COW needs to properly implement CopyTo (I think)

This is certainly very low pri.

**Comment by KirillOsenkov** [comment]
Oh, and I think this bug is not actionable at all because we can't change Microsoft.Build.Utilities.v4.0.dll at all.

The best thing to do is move desktop WPF targets out of C:\Windows and into the MSBuild toolset, and avoid loading anything from the GAC (by XAML markup tooling).
