### ISSUE TITLE
Allow IBuildEngine Extension Point

### ISSUE THREAD

**Issue by BenVillalobos** [dotnet/msbuild#6183]
Issue tracking discussion that started here: https://github.com/dotnet/msbuild/pull/6174#issuecomment-782423719

### Issue Description
Adding new information the task can access from the build engine is cumbersome. Current process:
1. Create IBuildEngineX
2. Add one property
3. Modify TaskHost and OOPTaskHost to implement the interface.

### Potential Path Forward
1. Create an IBuildEngineX that contains a `Dictionary<string, object>` where object is serializable.
2. Mihai suggested an IBE with an abstract class called `EngineServices`.

**Comment by Forgind** [comment]
@marcpopMSFT suggested we should put this off until mid-April at the earliest.

**Comment by rainersigwald** [comment]
@ladipro you're basically doing this in one of your outstanding PRs right?

**Comment by ladipro** [comment]
Affirmative. I wasn't aware of this one, I like the suggested name `EngineServices`.
