### ISSUE TITLE
Check for unused files from the repo

### ISSUE THREAD

**Issue by Nirmal4G** [dotnet/msbuild#6190]
### Unused files

- [x] Remove `netci.groovy` file.
- [x] Remove `RunApiPort.bat` file.
- [x] Remove `runApiCompat.bat` file.
- [x] Remove `CompatBaseline.txt` file.
- [x] Remove `src\Tasks\DefaultTasks.bat` file.
- [x] Remove `src\Tasks.UnitTests2` project.

##### Notes
Do update the list if there are any other redundant files in the repo.

**Comment by Forgind** [comment]
Speaking only for myself, I'm happy taking PRs that remove files we don't use. Do you have any others in mind?

(Note that I do think the Tasks.UnitTests2 PR you made will be merged, but we've been fighting with a lot of insertion difficulties recently, which has made it hard to actually merge things.)

**Comment by Nirmal4G** [comment]
> Do you have any others in mind?

Yes, what about these...?

- [/RunApiPort.bat](/dotnet/msbuild/blob/master/RunApiPort.bat)
- [/runApiCompat.bat](/dotnet/msbuild/blob/master/runApiCompat.bat)
- [/src/Tasks/DefaultTasks.bat](/dotnet/msbuild/blob/master/src/Tasks/DefaultTasks.bat)

> ...we've been fighting with a lot of insertion difficulties...

I see. That's why, a lot of PRs are pending merge. Is it because of a broken PR (_I do see some reverts_)?

**Comment by Nirmal4G** [comment]
@Forgind

**Comment by Forgind** [comment]
I think the last two should be removable. I don't know about the first three—@BenVillalobos, can we look at these in triage this week to see if we can remove them?

> I see. That's why, a lot of PRs are pending merge. Is it because of a broken PR (I do see some reverts)?

That's part of it. We've also struggled with random outages and various other difficulties. I'm hoping it will be resolved soon.

**Comment by BenVillalobos** [comment]
/cc the folks who last modified these files:
@cdmihai for netci.groovy, CompatBaseline.txt
@dsplaisted for RunApiPort.bat and RunApiCompat.bat

DefaultTasks.bat looks like an old cleanup file? 

A quick grep doesn't make it seem like there are any references to these files. We can take a bit to grep through other repos. to be safe we should `exp/` branch scripts in case they get picked up at other stages.

**Comment by dsplaisted** [comment]
I think the ApiCompat files were from when I was porting MSBuild to .NET Core, and aren't needed anymore.

**Comment by cdmihai** [comment]
> @cdmihai for netci.groovy, CompatBaseline.txt

You can remove them.

**Comment by Nirmal4G** [comment]
I have updated the PR with all the files mentioned here. Instead of multiple PRs, I committed the deletions in the current PR branch. Let me know if you want to put them into separate PRs.

**Comment by Nirmal4G** [comment]
The PRs #7278 and #7279 further removes the unused files from the Repo!
