### ISSUE TITLE
ResolveAssemblyReference throws InvalidOperationException on invalid PE files

### ISSUE THREAD

**Issue by FiniteReality** [dotnet/msbuild#6200]
### Issue Description
I have a project which produces native binaries (on linux, so ELF format) and when I use ProjectReference to indicate project dependencies, ResolveAssemblyReference tries to read the metadata of these files and throws InvalidOperationException because the dependencies don't use the PE format, or have metadata.

### Steps to Reproduce
Reproducing this is pretty hard in my experience, since *most* ELF files make the PEReader throw a BadImageFormatException. I've opened a related issue in the .NET runtime because of this: https://github.com/dotnet/runtime/issues/48419

The summary is, though:
1. Create a MSBuild project which produces a non-PE format file (e.g. by writing a large text file to `$(IntermediateOutputPath)$(TargetName)$(TargetExt)`)
2. Try to reference that project from another using `ProjectReference`
3. Build the project in step 2

### Expected Behavior
ResolveAssemblyReference skips the project because it doesn't have any metadata

### Actual Behavior
ResolveAssemblyReference throws an InvalidOperationException from PEReader.GetMetadataBlock()

### Analysis
Doing some digging, this appears to be caused by [AssemblyInformation.CorePopulateMetadata](https://github.com/dotnet/msbuild/blob/ca44138662e3aa90eb9305dd31d906ef02e962cb/src/Tasks/AssemblyDependency/AssemblyInformation.cs#L362) not checking whether the created PEReader has any metadata. This appears to be checked everywhere else a PEReader is used:
- https://github.com/dotnet/msbuild/blob/ca44138662e3aa90eb9305dd31d906ef02e962cb/src/Tasks/ManifestUtil/MetadataReader.cs#L35-L42
- https://github.com/dotnet/msbuild/blob/6819f7ab06c3f43e83ff4059d417395e0af06c01/src/Shared/AssemblyNameExtension.cs#L214-L220

### Versions & Configurations
```
$ dotnet --info
.NET SDK (reflecting any global.json):
 Version:   5.0.103
 Commit:    9effbc8ad5

Runtime Environment:
 OS Name:     debian
 OS Version:  
 OS Platform: Linux
 RID:         debian-x64
 Base Path:   /usr/share/dotnet/sdk/5.0.103/

Host (useful for support):
  Version: 5.0.3
  Commit:  eae88cc11b

.NET SDKs installed:
  3.1.406 [/usr/share/dotnet/sdk]
  5.0.103 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.12 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.3 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.12 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.3 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
$ dotnet msbuild -version
Microsoft (R) Build Engine version 16.8.3+39993bd9d for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

16.8.3.61104
```

### Attach a binlog
[This binlog](https://github.com/dotnet/msbuild/files/6052440/msbuild.binlog.zip) reproduces the issue, and I've been unable to reproduce it using smaller projects. I think this may be because smaller projects produce smaller binaries, which PEReader ends up rejecting. The source for the `ClangLink` and `ClangCompile` tasks can be found [here](https://github.com/finitereality/finite.cpp.sdk).

**Comment by cdmihai** [comment]
I think the story with non-managed assemblies is that you have to add the `ReferenceOutputAssembly="False"` metadata to your ProjectReference. Can you please check whether this works for you?

**Comment by FiniteReality** [comment]
> I think the story with non-managed assemblies is that you have to add the `ReferenceOutputAssembly="False" OutputItemType="Content"` metadata to your ProjectReference item ([docs](https://docs.microsoft.com/en-us/visualstudio/msbuild/common-msbuild-project-items?view=vs-2019#projectreference)). Can you please check whether this works for you?

I'm currently building an MSBuild SDK to allow building of native projects (which is probably outside of the supported use case, which I'm fine with), so I'd rather not have to do that in each project - if there's an alternative place I can specify this (like `GetTargetPath`) then I might be able to build my own infrastructure for this. However, as it stands currently, I'm stuck relying on ResolveAssemblyReference working correctly, since it's an incredibly complex task which does a lot of things.
