### ISSUE TITLE
Support restricting /warnaserror to msbuild specific warnings only

### ISSUE THREAD

**Issue by bearmate** [dotnet/msbuild#6202]
At the moment the ``/warnaserror`` command line switch for ``msbuild`` seems to make all warnings to errors, even compiler warnings. If for example in a .vcxproj file the ``TreatWarningAsError`` property is set to ``false``, this will be ignored by ``msbuild /warnaserror`` leading to failing builds despite having explicitly disabled this behaviour for certain projects or files.

As far as I can see this is intended behaviour and it is possible to disable it for specific warnings with ``/nowarn``, however this will also override all local configuration, ignoring warnings where they shouldn't be ignored.

It would be nice to be able to restrict ``/warnaserror`` to only ``msbuild`` specific warnings or alternatively to honor local configuration instead of ignoring it.

**Comment by rainersigwald** [comment]
This is already possible. From the help:

```
  -warnAsError[:code[;code2]]                                                        
                     List of warning codes to treats as errors.  Use a semicolon     
                     or a comma to separate multiple warning codes. To treat all     
                     warnings as errors use the switch with no values.               
                     (Short form: -err[:c;[c2]])                                     
                                                                                     
                     Example:                                                        
                       -warnAsError:MSB4130                                          
                                                                                     
                     When a warning is treated as an error the target will           
                     continue to execute as if it was a warning but the overall      
                     build will fail.                                                
```

You can also use the project-level properties `MSBuildWarningsAsMessages` to demote individual warnings (this overrides a "treat all warnings as errors" setting since it's more specific).

**Comment by confusedsushi** [comment]
I don't think the desired use-case is possible.

Here the problem is, that in an external dependency a compiler warning is throw. This external dependency cannot be modified. When you now add this dependency as reference to a project in which `/warnaserror` is set, The whole build fails even if in the dependency `TreatWarningAsError` is set to `false`. While the parent project should still fail to build if any warning occurs, the dependency should build successfully since there the compiler warning is already configured to be not an error.
