### ISSUE TITLE
Unable to produce framework-less nuget using msbuild sdk project

### ISSUE THREAD

**Issue by aaronla-ms** [dotnet/msbuild#6210]
### Issue Description

I'm attempting to use the new sdk targets to build a frameworkless nuget package. This package contains no .net code, so should have no framework dependencies. However, when I create an SDK style project (either using notargets, or the C# sdk), I get build errors.

Note, we do have a workaround for this bug to (a) set the framework to some dummy value, and (b) disable dependencies. However this is pretty fragile, and would prefer to align with supported msbuild features if possible.

### Steps to Reproduce

1. Create a new C# project
2. Change the SDK to Microsoft.Build.NoTargets/2.0.1
3. Remove the <TargetFramework> and <TargetFrameworks> lists
4. Add at least one <None Pack="true"... > item to the project
5. `dotnet pack`

I tested on both dotnetsdk3.1 and net6.0 preview.

### Expected Behavior
A nuget package is produced. That project has 

### Actual Behavior
on dotnetsdk3.1:

```
C:\Program Files\dotnet\sdk\3.1.406\NuGet.targets(128,5): error : Value cannot be null. (Parameter 'folderName') [C:\scratch\examplenuget\examplenuget.csproj]
```

on net60sdk:

```
C:\Program Files\dotnet\sdk\6.0.100-preview.1.21103.13\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.TargetFrameworkInference.targets(92,5): error NETSDK1013: The TargetFramework value '' was not recognized. It may be misspelled. If not, then the TargetFrameworkIdentifier and/or TargetFrameworkVersion properties must be specified explicitly. [C:\scratch\examplenuget\examplenuget.csproj]
```

### Analysis
Looking at nuget.targets, it seems like this machinery really doesn't expect frameworkless code. We know msbuild in the past had very poor support for non-framework project types, but were hoping that it had improved with the new sdks.

Adding `<TargetFramework>netstandard2.0</TargetFramework>` silences the build errors, but the produces a bad nuspec -- specifically, it has an unnecessary and undesirable netstandard2.0 entry:

```
<dependencies>
  <group targetFramework=".NETStandard2.0" />
</dependencies>
```

Previous versions of our nuget using proprietary project types did not include this dependency. While we'd like to get off of using proprietary tools to build nuget files, we also need to not regress our dependencies list.

### Versions & Configurations
- Windows 10 and,
- dotnetsdk 3.1.406 or
- net60sdk 6.0.100-preview.1.21103.13

### Attach a binlog
n/a

**Comment by BenVillalobos** [comment]
Team Triage: @nkolev92 is this supported / does this seem like a nuget or msbuild issue?

**Comment by nkolev92** [comment]
NuGet and the SDK both require a target framework to restore, build & pack.

> Note, we do have a workaround for this bug to (a) set the framework to some dummy value, and (b) disable dependencies. However this is pretty fragile, and would prefer to align with supported msbuild features if possible.

That's the recommended way. There are pack switches that allow granular control over what gets packed.

**Comment by Forgind** [comment]
Sounds like you started with the best way, so closing this.

**Comment by aaronla-ms** [comment]
@Forgind - how would I go about filing a feature request for this in future releases? This is really a pain to workaround and educate developers on.

**Comment by Forgind** [comment]
That would depend on where the feature would have to be built. From `NuGet and the SDK both require a target framework`, I would assume filing an issue very similar to this one in one or both of those repos would be appropriate.
https://github.com/dotnet/sdk
and
https://github.com/NuGet/NuGet.Client
are the right repos, I believe.
