### ISSUE TITLE
MSBuild lack of support for --LongOptionName, is not consistent with other DotNet CLI commands.

### ISSUE THREAD

**Issue by jwdonahue** [dotnet/msbuild#6211]
### Issue Description
MSBuild lack of support for --LongOptionName, is not consistent with other DotNet CLI commands.

### Steps to Reproduce
> dotnet msbuild --help
### Expected Behavior
Expected to behave like other dotnet commands and provide the same output as `dotnet msbuild -h`.

### Actual Behavior
Microsoft (R) Build Engine version 16.8.3+39993bd9d for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

MSBUILD : error MSB1001: Unknown switch.
Switch: --help

For switch syntax, type "MSBuild -help"

### Versions & Configurations
> msbuild -version
Microsoft (R) Build Engine version 16.8.3+39993bd9d for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

**Comment by BenVillalobos** [comment]
Team Triage: This has been fixed in 16.9+ versions of MSBuild.
