### ISSUE TITLE
Conditions vs DependsOnTargets vs AfterTargets

### ISSUE THREAD

**Issue by Nikita-T86** [dotnet/msbuild#6216]
My goal is to create target that will be executed only if another target was finished successfully. And that another target is conditional one itself.

So I created the following csproj: 

    <Project Sdk="Microsoft.NET.Sdk">
    
      <PropertyGroup>
        <TargetFrameworks>netstandard2.0;net472</TargetFrameworks>
      </PropertyGroup>
    
	    <Target Name="PostBuildNet472" AfterTargets="PostBuildEvent" Condition="'$(TargetFramework)'=='net472'">
		    <Message Text="Post build event message for net472" Importance="high"/>
	    </Target>
    
	    <Target Name="PostBuildNetStandard" AfterTargets="PostBuildEvent" Condition="'$(TargetFramework)'=='netstandard2.0'">
		    <Message Text="Post build event message for netstandard2.0" Importance="high"/>
	    </Target>
    
	    <Target Name="DisplayMessage" DependsOnTargets="PostBuildNetStandard">
		    <Message Text="Post build event for .Net Standard target was executed successfully" Importance="high"/>
	    </Target>
	    
    </Project>

I expect that target "DisplayMessage" will be executed after target "PostBuildNetStandard", but that doesn't happen. 

Build output:
1>------ Rebuild All started: Project: TestLibrary, Configuration: Release Any CPU ------
1>TestLibrary -> C:\Framework_NetStandard\TestLibrary\bin\Release\net472\TestLibrary.dll
1>Post build event message for net472
1>TestLibrary -> C:\Framework_NetStandard\TestLibrary\bin\Release\netstandard2.0\TestLibrary.dll
1>Post build event message for netstandard2.0
========== Rebuild All: 1 succeeded, 0 failed, 0 skipped ==========

Why DisplayMessage target is not executed even though it depends on successfully executed target?

Now consider modified version of same project where I experience opposite behavior when using AfterTargets - target is executed even if previous one is failed.

    <Project Sdk="Microsoft.NET.Sdk">
    
      <PropertyGroup>
        <TargetFrameworks>netstandard2.0;net472</TargetFrameworks>
      </PropertyGroup>
    
	    <Target Name="PostBuildNet472" AfterTargets="PostBuildEvent" Condition="'$(TargetFramework)'=='net472'">
		    <Message Text="Post build event message for net472" Importance="high"/>
	    </Target>
    
	    <Target Name="PostBuildNetStandard" AfterTargets="PostBuildEvent" Condition="'$(TargetFramework)'=='netstandard2.0'">
		    <Error Text="Error"/>
	    </Target>
    
	    <Target Name="DisplayMessage" AfterTargets="PostBuildNetStandard">
		    <Message Text="Post build event for .Net Standard target was executed successfully" Importance="high"/>
	    </Target>
	    
    </Project>

The build is failed, but I still see the message from DisplayMessage target even though PostBuildNetStandard target is failed.
Build output:

  1>------ Rebuild All started: Project: TestLibrary, Configuration: Release Any CPU ------
  1>TestLibrary -> C:\Framework_NetStandard\TestLibrary\bin\Release\net472\TestLibrary.dll
  1>Post build event message for net472
  1>**Post build event for .Net Standard target was executed successfully**
  1>TestLibrary -> C:\Framework_NetStandard\TestLibrary\bin\Release\netstandard2.0\TestLibrary.dll
  1>C:\Framework_NetStandard\TestLibrary\TestLibrary.csproj(12,3): error : Error
  1>Done building project "TestLibrary.csproj" -- FAILED.
  ========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========

MsBuild version 15.9.21.664

**Comment by BenVillalobos** [comment]
Team Triage: Try setting `AfterTargets=PostBuildEvent;DisplayMessage` for `PostBuildNetStandard`. Feel free to reopen if that didn't work.
