### ISSUE TITLE
Using build tasks with multitarget solutions

### ISSUE THREAD

**Issue by replaysMike** [dotnet/msbuild#6229]
I'm not sure if this is the right place for this report, but I've found I can no longer use build tasks with multitargeted projects. It was working fine some time in the last 6 months, then suddenly I can't build any of my dozen or so nuget packages that rely on it.

A reproducable example:

```csharp
public class MyTask : Microsoft.Build.Utilities.Task
{
  public override bool Execute()
  {
    Log.LogMessage("Hey I ran!");
    return true;
  }
}
```

Works fine if I target a single framework:
```
<PropertyGroup>
  <TargetFramework>net48</TargetFramework>
</PropertyGroup>
<UsingTask TaskName="MyTask" AssemblyFile="bin\Debug\net48\MyAssembly.dll" />
<Target Name="SomeTask" AfterTargets="Build>
  <MyTask />
</Target>
```
Does not work anymore when I change to `<TargetFrameworks>netstandard2.0;net48</TargetFrameworks>` with any of the following:

```
<UsingTask TaskName="MyTask" AssemblyFile="bin\Debug\$(TargetFramework)\MyAssembly.dll" />
<UsingTask TaskName="MyTask" AssemblyFile="bin\Debug\$(TargetFramework)\MyAssembly.dll" Condition="'$(TargetFramework)' != ''" />
<UsingTask TaskName="MyTask" AssemblyFile="bin\Debug\net48\MyAssembly.dll" Condition="'$(TargetFramework)' == 'net48'" />
<UsingTask TaskName="MyTask" AssemblyFile="bin\Debug\netstandard2.0\MyAssembly.dll" Condition="'$(TargetFramework)' == 'netstandard2.0'" />
// or ommitting UsingTask and just declaring MyTask
```

I've tried every combination of configuration I could think of, but it always either tries to resolve an empty TargetFramework path:

> MyProject.csproj(71,3): error MSB4036: The "MyTask" task was not found. Check the following: 1.) The name of the task in the project file is the same as the name of the task class. 2.) The task class is "public" and implements the Microsoft.Build.Framework.ITask interface. 3.) The task is correctly declared with in the project file, or in the *.tasks files located in the "C:\Program Files\dotnet\sdk\5.0.200" directory.

or when the path is correct it gives a different error about MyTask not existing:

> MyProject.csproj(70,3): error MSB4062: The "MyTask" task could not be loaded from the assembly B:..\bin\Release\MyAssembly.dll. Could not load file or assembly 'B:..bin\Release\MyAssembly.dll'. The system cannot find the file specified. Confirm that the declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.

The weird thing is this was working before. I didn't even need to declare a UsingTask, it just worked. I was using it to execute ILRepack on nuget packages I was publishing, but I'll either have to abandon tasks and write build scripts or figure out some kind of workaround to make it work.

VS2019 (16.9.0)

**Comment by BenVillalobos** [comment]
Hey! I can't reproduce the issue you're having here. A few things that may be an issue:
1. Try including the namespace in the `TaskName` of your `UsingTask`.
2. Try using `$(MSBuildThisFileDirectory)\bin\...` in your assemblyfile path

Does this happen only on the command line, or just VS, or both?

To help us figure out what's going on in your build, could you provide some more info such as:

1. [A binlog](aka.ms/msbuild/binlog) of your build
2. Provide the repro project you're building. (if there's any more to it than what was posted)
3. Post the output of `msbuild --version`
