### ISSUE TITLE
msbuild restores delisted NuGet package versions when PackageReferenve.Version ends with * to denote the latest version

### ISSUE THREAD

**Issue by MarkKharitonov** [dotnet/msbuild#6233]
### Issue Description
We have changed the versioning scheme of an internal NuGet package. The new scheme places the new versions below the old ones, so the latter were unlisted from the NuGet repository (we use Azure Artifacts).

The NuGet package is referenced in code using a *, like this - **61.***:
```
    <PackageReference Include="Company.Payroll.Engine.DB">
      <Version>61.*</Version>
    </PackageReference>
```

We run msbuild with the **RestoreForce = true** and msbuild restores the latest old version, which is unlisted.

Note that running nuget.exe list command returns the correct new version, i.e. it does ignore the unlisted versions unlike msbuild.

### Steps to Reproduce

1. Create a NuGet package and publish it to anywhere. I think the server side technology does not matter as long as it supports the NuGet API.
2. Create an msbuild project and reference the NuGet package using *
3. Have 2 versions of the NuGet package
4. Unlist the newest version
5. run msbuild /t:Restore /p:RestoreForce=true

### Expected Behavior
The unlisted package is ignored - the previous package version should be restored instead.

### Actual Behavior
The unlisted package is restored. Cleaning the nuget cache does not help.

### Analysis
I checked with Fiddler and nuget uses a different API than msbuild. Nuget uses some kind of XML API, whereas msbuild uses JSON API, specifically https://docs.microsoft.com/en-us/nuget/api/package-base-address-resource which I believe is wrong, because it returns both listed and unlisted versions (as documented in the article), without indicating what is unlisted. As such it is not suitable to resolve the * versions. Or any range versions in general.

### Versions & Configurations

- NuGet Version: 5.2.0.6090
- Microsoft (R) Build Engine version 16.8.3+39993bd9d for .NET Framework

### Attach a binlog
[msbuild.zip](https://github.com/dotnet/msbuild/files/6109565/msbuild.zip)

**Comment by BenVillalobos** [comment]
Team Triage: @nkolev92 is this a NuGet issue?

**Comment by nkolev92** [comment]
That's by design. 
Listedness does not affect resolution, only user discoverability (searching for packages on nuget.org, PM UI).

**Comment by MarkKharitonov** [comment]
I was afraid you would say so. So **nuget.exe list** would not return delisted versions, but **msbuild /restore** would happily restore it.
Now I may understand it when the version is provided exactly. But when it is given as a range - don't you do discovery first? No matter how you call it - the discovery phase is there. You are calling NuGet API to discover the available versions. And if it is by design, then how come the discovery API you use returns delisted versions? By your own words - it should not.

**Comment by nkolev92** [comment]
> Now I may understand it when the version is provided exactly. But when it is given as a range - don't you do discovery first? 

Exact version is preferred. You'd get a warning if anything else was resolved.

**Comment by MarkKharitonov** [comment]
I would also prefer an exact version. But we use * versions for some of our internal NuGet packages.

So, back to my question. Given a range of versions - don't you do version discovery? And if so, shouldn't delisted versions be excluded from this discovery?

**Comment by nkolev92** [comment]
All available versions are considered when using floating versions. 
Once a package has been installed, the notion of a package being listed is lost.

**Comment by MarkKharitonov** [comment]
I am sorry. I still do not understand. We use **RestoreForce=true** during the restore. That means the version restored an hour ago may not be the version restored now, because the flag forces **discovery** of the new versions. That discovery happens before the resolution. My point - the discovery should not include delisted versions.

**Comment by nkolev92** [comment]
> My point - the discovery should not include delisted versions.

Floating versions by design considers listed and unlisted versions.

**Comment by MarkKharitonov** [comment]
Is it documented anywhere?

**Comment by nkolev92** [comment]
Docs available here: https://docs.microsoft.com/en-us/nuget/nuget-org/policies/deleting-packages

I couldn't find the client side one, I created an issue for that to be added there as well, https://github.com/NuGet/docs.microsoft.com-nuget/issues/2349.

**Comment by MarkKharitonov** [comment]
Now that I know it is by design I question - why do we need package delisting at all? Seems like actually deleting the package is the only way to affect the floating versions algorithm.

I think this design is flawed.

**Comment by rainersigwald** [comment]
This issue was moved to NuGet/Home#10931
