### ISSUE TITLE
Broken build for solutions with web site projects

### ISSUE THREAD

**Issue by donovan-ecargo** [dotnet/msbuild#6236]
### Issue Description
Web site projects in the solution will break the build. Note, by web site project, I mean web site projects(WSP), not web application projects (WAP).

The last working version of MSBuild: packaged with the 16.8.6 version of Visual Studio 2019.

Known broken versions:
`Microsoft (R) Build Engine version 16.9.0+57a23d249 for .NET Framework`, with Visual Studio 16.9.1. 
The version packaged with Visual Studio 16.9.0.

### Steps to Reproduce
1. Install 16.9.1 version of Visual studio.
2. Create a console project
3. Add an existing website from the local IIS installation.
4. Run msbuild via commandline, something like `msbuild /m -t:"clean;build" .\WebsiteBugIssueRepro.sln`
5. Error in build should appear.

### Expected Behavior
The build should successfully complete.

### Actual Behavior
An error is thrown during the build.

**Comment by donovan-ecargo** [comment]
Based on some ad-hoc guess debugging, one of our developers believed the source of the issue was

> 
> The new MSBuild adds a property group for every project referenced in the solution, it does this by retrieving the absolute path on the disk for the project in the solution file will be written out in the property group in memory as full path of the project by the method `AddPropertyGroupForSolutionConfiguration`. The `AbsolutePath` property of the `ProjectInSolution` class is implemented here and gets the path of the project in the solution file and combine it with the solution file directory:
> 
> 1. Solution file path
> 2. Relative path of a project, you can see this by examining the solution file.
> 3. Combining 1 and 2 and you get the absolute path.
> 
> The error according to the stack trace comes from here, following this method leads to a `NotSupportedException` which barfs when the function `PathInternal.HasInvalidVolumeSeparator(fullPath))` returns true, the source (and name) indicates somehow a bad character got into the absolute path retrieved above.
> 
> The web site project has entries in the solution file, like so:
> Project("{E24C65DC-7377-472B-9ABA-BC803B73C61A}") = "DummyEndpoints", "http://localhost:86/DummyEndpoints"
> The first string is the project name, the second is the relative path so the generated absolute file is:
> <projectAbsoluteFilePath>\http://localhost:86/DummyEndpoints
> 
> Which naturally generates an error.

**Comment by BenVillalobos** [comment]
Team Triage: @jeffkl is this related to https://github.com/dotnet/msbuild/pull/5950?

**Comment by donovan-ecargo** [comment]
Would you be able to give confirmation as to what version the fix should be released with?

**Comment by BenVillalobos** [comment]
@donovan-ecargo Thanks for the ping on this. It should land in 16.9.3

**Comment by donovan-ecargo** [comment]
Thanks, and thanks for the quick response to the bug!

**Comment by jeffkl** [comment]
The fix for this is now out in Visual Studio 2019 16.9.3.

https://docs.microsoft.com/en-us/visualstudio/releases/2019/history#release-dates-and-build-numbers

https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes#--visual-studio-2019-version-1693-
