### ISSUE TITLE
UsingTask with specific AssemblyFile fails with FileNotFoundException, despite the file existing

### ISSUE THREAD

**Issue by belkiss** [dotnet/msbuild#6248]
### Issue Description
Hello!

I have a .targets file that tries to load a task from an Assembly DLL with UsingTask like this:
```
<UsingTask TaskName="SetEnv" AssemblyFile="$(MSBuildThisFileDirectory)Microsoft.Build.CppTasks.Common.dll"/>
```

And I'm getting this error, despite the file existing:
```
Could not load file or assembly 'Microsoft.Build.CPPTasks.Common.dll(...)' or one of its dependencies. The system cannot find the file specified.
```

The .targets file where that's being done is "tools\MSBuild\Microsoft\VC\v160\Microsoft.Cpp.Current.targets" and is located within the local vs2019_buildtools installation, version 16.8.4. I just import it in my .vcxproj.

### Analysis
I've retrieved latest MSBuild source code from the master branch (a13e20027d528310364bc40cbe2e079408ad82fe), compiled it, and managed to repro the issue. It seems the root of the problem lies in the "MSBuild" project, when it calls Assembly.UnsafeLoadFrom with the proper DLL as a path, throwing the FileNotFoundException with the message `Could not load file or assembly 'Microsoft.Build.CPPTasks.Common, Version=16.10.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.`

A sample project freshly created from vs wizard doesn't have the problem, and manages to load the DLL just fine with `UnsafeLoadFrom`, so I suspect one of the dependencies of MSBuild to trigger the issue. I don't know which one though.

Also note that this seems to only occur with MSBuild built for .net framework 4.7.2, the .net5 version seems to be doing the right thing.

### Steps to Reproduce

* Get the Microsoft.Build.CppTasks.Common.dll from a vs2019 16.8 build tools installation.
* Change the Main entry point of MSBuild in the file `XMake.cs` like this (adapting the path):

```csharp
        [MTAThread]
        public static int Main(
#if !FEATURE_GET_COMMANDLINE
            string [] args
#endif
            )
        {
            // the below line will throw 
            var assembly = Assembly.UnsafeLoadFrom(@"d:\vs2019_buildtools.16.8.4\MSBuild\Microsoft\VC\v160\Microsoft.Build.CppTasks.Common.dll");

            return 0;
        }
```
* Notice the exception when starting MSBuild

### Expected Behavior
No exception

### Actual Behavior
Throws a FileNotFoundException.

### Versions & Configurations
* 16.9.0.11203, but latest in master branch (a13e20027d528310364bc40cbe2e079408ad82fe) has the same problem

Thanks!

**Comment by BenVillalobos** [comment]
Team Triage: cpp tasks are designed to always use the latest version of the task. There is an entry in our app.config that ensures that behavior. Since you are using a newer MSBuild and an older Microsoft.Build.CppTasks.Common.dll, the version msbuild wants doesn't match the version that you're providing.

The cpp team has relaxed this requirement for 17.0, but for now you must have the cpp workload installed in the visual studio instance that you're running msbuild from.

/cc: @olgaark
