### ISSUE TITLE
Re-triaging MSBuild performance backlog.

### ISSUE THREAD

**Issue by AR-May** [dotnet/msbuild#6256]
MSBuild performance squad needs to re-triage all old performance issues.
Current task for each assignee: re-triage 30 old performance items.

**Comment by ladipro** [comment]
I have re-triaged 30 issues with the following outcome:
- 10 closed, 2 were already closed.
- 8 marked with needs-investigation.
- 9 moved to backlog.
- 1 already parented by a user story.

**Comment by ladipro** [comment]
@AR-May can this one be closed?

**Comment by AR-May** [comment]
done
