### ISSUE TITLE
KeyNotFoundException in GetWarningsToBeLoggedAsErrorsByProject

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/msbuild#6264]
https://github.com/dotnet/msbuild/blob/80b7f2dcb622333934826ebd008c61a1a2b7320b/src/Build/BackEnd/Components/Logging/LoggingService.cs#L544

the field has a single entry with a different key.

This is during a pretty regular multi-proc build

**Comment by BenVillalobos** [comment]
This will be closed by https://github.com/dotnet/msbuild/issues/6264
