### ISSUE TITLE
ProcessExtensions_Tests.KillTree() test failure

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/msbuild#6265]
This test fails on Windows:
https://github.com/dotnet/msbuild/blob/13522d2466ae1634177e2a6a40fefaedff95139c/src/Utilities.UnitTests/ProcessExtensions_Tests.cs#L18

Because "sleep" process is not found. Should we switch it to use notepad on Windows?

@tmds let us know if you're interested in fixing this, but if not, the team will pick it up

**Comment by KirillOsenkov** [comment]
I have no idea how it passes on Windows in CI? Does it find some "sleep" exe?

**Comment by BenVillalobos** [comment]
This passes almost every time I run `eng\cibuild_bootstrapped_msbuild.cmd`.

**Comment by KirillOsenkov** [comment]
We should find out whether:
1. the test runs at all during `eng\cibuild_bootstrapped_msbuild.cmd`
2. if yes, what process is being started and why does it not fail

**Comment by KirillOsenkov** [comment]
Hahaha, on CI it happens to find `C:\Program Files\Git\usr\bin\sleep.exe`

We need to think on how to make this pass on any machine with Windows, even if the above sleep.exe is not present or not on the PATH.

**Comment by KirillOsenkov** [comment]
Maybe just probe if the .exe is there, but not on the path. Most Windows users will have Git installed.
