### ISSUE TITLE
dotnet pack not working with the net5.0-windows10.0.19041.0 TFM

### ISSUE THREAD

**Issue by PureWeen** [dotnet/msbuild#6279]
### Issue Description

When I run `dotnet pack` against `net6.0-windows10.0.19041.0` or `net5.0-windows10.0.19041.0` I get the following exception

```
C:\Program Files\dotnet\sdk\5.0.201\Microsoft.Common.CurrentVersion.targets(2505,6): error MSB4062: The "Microsoft.Build.Tasks.FindInvalidProjectReferences" task could not be loaded from the assembly Microsoft.Build.Tasks.Core, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a.  Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask. [C:\Users\shane\Source\Repos\ANugetTest\ClassLibrary1\ClassLibrary1.csproj]
```

### Steps to Reproduce
[ANugetTest.zip](https://github.com/dotnet/msbuild/files/6172057/ANugetTest.zip)

I've included a sln here that has a net6 and a net5 target.

```cmd
C:\ANugetTest\Net6Target>dotnet pack
```

### Expected Behavior
A nuget package is created

### Actual Behavior

The following exception is thrown

```
C:\Program Files\dotnet\sdk\5.0.201\Microsoft.Common.CurrentVersion.targets(2505,6): error MSB4062: The "Microsoft.Build.Tasks.FindInvalidProjectReferences" task could not be loaded from the assembly Microsoft.Build.Tasks.Core, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a.  Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask. [C:\Users\shane\Source\Repos\ANugetTest\ClassLibrary1\ClassLibrary1.csproj]
```

### Analysis
I tried setting
`<FindInvalidProjectReferences>false</FindInvalidProjectReferences>`

But it didn't help

`msbuild /t:pack` works

Some additional context
https://microsoft.visualstudio.com/OS/_workitems/edit/32211926

It looks like 
`dotnet build` doesn't work and fails with the same exception

### Versions & Configurations
`msbuild -version`
16.10.0.11801

`dotnet --version`
6.0.100-preview.2.21155.3

### Attach a binlog

[msbuild (2).zip](https://github.com/dotnet/msbuild/files/6172101/msbuild.2.zip)

**Comment by BenVillalobos** [comment]
First pass investigation notes:

Can repro this bug. Doing a little bit of digging:

The FindInvalidProjectReferences task is imported like so in `Microsoft.Common.tasks`:
```
<UsingTask TaskName="Microsoft.Build.Tasks.FindInvalidProjectReferences"          AssemblyName="Microsoft.Build.Tasks.Core, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" Condition="'$(MSBuildAssemblyVersion)' != ''" />
```

In the `Microsoft.Build.Tasks.Core` assembly under my installed `C:\Program Files\dotnet\sdk\6.0.100-preview.2.21155.3` folder, I don't see `FindInvalidProjectReferences`.

![image](https://user-images.githubusercontent.com/4691428/112349866-538a2200-8c86-11eb-97a7-7a589a681065.png)


on `16.10.0.12417` msbuild and running `msbuild /t:pack` I get this error:
```
"C:\Users\bevillal\Downloads\ANugetTest\Net6Target\Net6Target.csproj" (pack target) (1) ->
(_GetSdkToolsPathsFromSdk target) ->
  C:\Users\bevillal\.nuget\packages\microsoft.projectreunion.foundation\0.5.0-prerelease\build\Microsoft.ApplicationMod
el.Resources.PriGen.targets(833,5): error MSB4062: The "Microsoft.Build.AppxPackage.GetSdkFileFullPath" task could not
be loaded from the assembly C:\Program Files (x86)\Microsoft Visual Studio\2019\Dogfood\MSBuild\Microsoft\VisualStudio\
v16.0\AppxPackage\Microsoft.Build.AppxPackage.dll. Could not load file or assembly 'file:///C:\Program Files (x86)\Micr
osoft Visual Studio\2019\Dogfood\MSBuild\Microsoft\VisualStudio\v16.0\AppxPackage\Microsoft.Build.AppxPackage.dll' or o
ne of its dependencies. The system cannot find the file specified. Confirm that the <UsingTask> declaration is correct,
 that the assembly and all its dependencies are available, and that the task contains a public class that implements Mi
crosoft.Build.Framework.ITask. [C:\Users\bevillal\Downloads\ANugetTest\Net6Target\Net6Target.csproj]
```

**Comment by BenVillalobos** [comment]
Team Triage: It looks like `FindInvalidProjectReferences` is explicitly excluded at the project level for netcore apps.

**Comment by rainersigwald** [comment]
In standard .NET SDK projects, nothing opts into `FindInvalidProjectReferences` and the missing task is irrelevant. `Microsoft.UI.Xaml.Markup.Compiler.interop.targets` explicitly opts into it in some cases:

```xml
    <!--
      Enable warning when referenced projects have higher version than the current project
      for Windows Store projects
    -->
    <PropertyGroup>
        <FindInvalidProjectReferences Condition="'$(TargetPlatformIdentifier)' == 'Windows' and
                                              '$(TargetPlatformVersion)' &gt;= '8.0'">true</FindInvalidProjectReferences>
    </PropertyGroup>
```

Explicitly forcing it to off gets past this error:

```
dotnet build -p:FindInvalidProjectReferences=false 
```

@PureWeen, is that something you can change or get the Windows folks to change? We can also look at enabling this task.
