### ISSUE TITLE
Solution with web site project no longer compiles after updating msbuild.

### ISSUE THREAD

**Issue by CzBuCHi** [dotnet/msbuild#6280]
### Issue Description
Solution with web site project no longer compiles after updating msbuild.

### Steps to Reproduce
1) extract zip [Test.zip](https://github.com/dotnet/msbuild/files/6172998/Test.zip)
2) run script.txt on command line as batch file
3) run 'msbuild web.sln'

### Expected Behavior
successful compilation - see success.log from test.zip

### Actual Behavior
"The build stopped unexpectedly because of an internal failure." - see error.log from test.zip

### Versions & Configurations
succesfull build:
windows: server 2019 Version 1809 (build 17763.1790)
msbuild: 16.8.3+39993bd9d for .NET Framework

failed build:
windows: server 2019 Version 1809 (build 17763.1817)
msbuild: 16.9.0+57a23d249 for .NET Framework

**Comment by jeffkl** [comment]
Thank you for reporting this issue, fortunately this was reported already in #6236 and has been fixed in https://github.com/dotnet/msbuild/pull/6238.  This should be out in the next release of Visual Studio 2019, 16.9.3.

**Comment by CzBuCHi** [comment]
Great news! I really need to learnt how to search for existing issues tho ...
