### ISSUE TITLE
TargetResult.TranslateItems is not pooling read buffers

### ISSUE THREAD

**Issue by sharwell** [dotnet/msbuild#6291]
This method explicitly passes `null` for the pool, which results in significant numbers of buffer allocations during VS solution load scenarios (7.5% of total solution load allocations for the solution I was testing at the time).

https://github.com/dotnet/msbuild/blob/13522d2466ae1634177e2a6a40fefaedff95139c/src/Build/BackEnd/Shared/TargetResult.cs#L323

**Comment by BenVillalobos** [comment]
Leaving this open for the perf related bug triage. /cc: @arkalyanms / @jackcartman

**Comment by ladipro** [comment]
This was fixed in #6556 by making **null** mean "use a global shared buffer".
