### ISSUE TITLE
MSBuild creates a faulty .net global tool package

### ISSUE THREAD

**Issue by JarLob** [dotnet/msbuild#6292]
### Issue Description

.NET Global tool built with msbuild creates a faulty nuget packages that gives `An assembly specified in the application dependencies manifest (security-scan.deps.json) was not found` on startup.

### Steps to Reproduce

I build on windows, test in docker.

1. git clone https://github.com/security-code-scan/security-code-scan.git
2. cd security-code-scan
2. git checkout 675161673b3d6f3c72b7f8bd63e2fa43ae1e493b
3. nuget restore SecurityCodeScan.sln
4. msbuild SecurityCodeScan.sln /t:Build /p:Configuration=Release
5. docker run -ti --rm --volume "<INSERT_YOUR_DIR>SecurityCodeScan.Tool\\.NET Core\bin":/tmp/app -w /tmp/app mcr.microsoft.com/dotnet/sdk:5.0
6. dotnet tool install --global --add-source Release security-scan
7. export PATH="$PATH:/root/.dotnet/tools"
8. security-scan

### Expected Behavior

Successful run

### Actual Behavior

Error:
  An assembly specified in the application dependencies manifest (security-scan.deps.json) was not found:
    package: 'System.Globalization.Extensions', version: '4.3.0'
    path: 'runtimes/unix/lib/netstandard1.3/System.Globalization.Extensions.dll'

### Analysis

a. If I build the same solution in Visual Studio it produces correct nuget package.
b. If I build the project (and its dependencies) with dotnet: `dotnet build "SecurityCodeScan.Tool/.NET Core/security-scan.csproj" --configuration Release` it also produces valid package. (To make it build with dotnet.exe please slightly edit config files, attaching [diff.txt](https://github.com/dotnet/msbuild/files/6192092/diff.txt))

### Versions & Configurations

msbuild 16.9.0.11203
dotnet 5.0.201

**Comment by BenVillalobos** [comment]
I had to run `dotnet restore` instead of nuget restore on your solution to get a successful restore. My run of `msbuild SecurityCodeScan.sln /t:Build /p:Configuration=Release` fails with:
```
"C:\src\git\_customerProjects\security-code-scan\SecurityCodeScan.Vsix\SecurityCodeScan.Vsix.csproj" (default target) (
4) ->
  C:\src\git\_customerProjects\security-code-scan\SecurityCodeScan.Vsix\SecurityCodeScan.Vsix.csproj(92,11): error MSB4
226: The imported project "C:\Program Files (x86)\Microsoft Visual Studio\2019\Dogfood\MSBuild\Microsoft\VisualStudio\v
16.0\VSSDK\Microsoft.VsSDK.targets" was not found. Also, tried to find "VSSDK\Microsoft.VsSDK.targets" in the fallback
search path(s) for $(VSToolsPath) - "C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v16.0" . These search paths
are defined in "C:\Program Files (x86)\Microsoft Visual Studio\2019\Dogfood\MSBuild\Current\Bin\msbuild.exe.Config". Co
nfirm that the path in the <Import> declaration is correct, and that the file exists on disk in one of the search paths
```
Could you provide a link to the dependency I'm missing?

**Comment by JarLob** [comment]
It must be "Visual Studio extension development"

![image](https://user-images.githubusercontent.com/26652396/116926579-2fe1d080-ac63-11eb-853e-3b3b34d1fd6c.png)

**Comment by BenVillalobos** [comment]
I can't seem to get this to repro.  The msbuild call results in a successful build with some compiler warnings,

dotnet --version (in the container) 5.0.203
msbuild --version 16.10.0-preview-21253

could you provide the full output of msbuild --version? This includes the hash.

**Comment by JarLob** [comment]
Did it succeed at step 9.? I didn't write that it fails to build :/

**Comment by BenVillalobos** [comment]
@JarLob I did get a splash screen from running `security-scan`

**Comment by BenVillalobos** [comment]
Coming back to this, I still can't repro. Had issues once in docker but that was because of a partially malformed path in the repro steps. Even then, running the tool works just fine.

Is this still an issue on your end?

**Comment by BenVillalobos** [comment]
> Does this work on a newer version of MSBuild? 16.9.0.11203 is fairly old.

Doing some due dilligence: That version of msbuild is probably what your version of the sdk is using, which is fine. But running `msbuild ...` will likely produce different results from `dotnet msbuild ...` because `msbuild ...` would point to your VS installation instead of your sdk install. 

Could you post the output of `msbuild --version`?

**Comment by JarLob** [comment]
Hi @BenVillalobos, just tried running Developer Command Prompt for VS 2019. The VS is up to the date, msbuild version is `16.10.2.30804` and cannot reproduce it anymore.

**Comment by JarLob** [comment]
Hit this one again :( Basically reproducible with the latest version, so just skip step 3.
msbuild 16.10.2.30804
dotnet 5.0.301

**Comment by JarLob** [comment]
Is there any feedback I didn't respond?

**Comment by JarLob** [comment]
I tried to repro it with GitHub actions: created a CI build runner at https://github.com/JarLob/security-code-scan/blob/vs2019/.github/workflows/build.yml that built the dotnet tool https://github.com/JarLob/security-code-scan/suites/3631189184/artifacts/87889576 When I downloaded it and installed with `dotnet tool install --global --add-source {mypath} security-scan` it worked correctly. The build log is [logs_5.zip](https://github.com/dotnet/msbuild/files/7083541/logs_5.zip)

However if I download a build artefact from the other CI - https://ci.appveyor.com/api/buildjobs/53p9buj8kejd1taw/artifacts/SecurityCodeScan.Tool%2F.NET%20Core%2Fbin%2FRelease%2Fsecurity-scan.5.2.3.nupkg it fails to run. Attaching the full log here:
[log.txt](https://github.com/dotnet/msbuild/files/7083540/log.txt)

I see I have a workaround - migrate to GH Actions. Not sure if these logs are useful for you to find what is the cause of the faulty build.

**Comment by v-zhiyul** [comment]
@JarLob We tried to reproduce you provided Repro_Steps without Step 3, but unfortunately we didn’t reproduce it on VS 16.11(MSbuild:16.11.0.30205). So could you help to confirm whether your problem also reproduces after updating to the latest VS(16.11)?

**Comment by JarLob** [comment]
Whatever
