### ISSUE TITLE
Do not log task inputs/outputs when LogTaskInputs is set

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/msbuild#6305]
RAR attempts to avoid logging task inputs and outputs when LogTaskInputs is set:
https://github.com/dotnet/msbuild/blob/38da84d453b14008b148c7eea28df24ab4443bb7/src/Tasks/AssemblyDependency/ResolveAssemblyReference.cs#L1317

However I've just realized this may not properly propagate to node processes. We need a way to reliably extract this information from a task.

**Comment by KirillOsenkov** [comment]
See a prototype here:
https://github.com/dotnet/msbuild/commit/1011f1771ff1460bfebb74210de8469339cfca35
It seems to be working fine.

Caveat: figure out the story for MSBuildTaskHost net35 and whether we care about it.

The design decision to make is how to expose this to tasks. Adding stuff to IBuildEngine seems natural.
Let's wait for Rainer to decide on the approach.

Additional approach would be to introduce an internal interface with `bool LogTaskInputs {get; set;}` and have `Task` or `TaskExtension` implement that, then in `TaskExecutionHost` after instantiating the task check for that interface and set `LogTaskInputs` if present.

**Comment by ladipro** [comment]
@KirillOsenkov #6381 is now merged so we can add the new property to the `EngineServices` class. Please remind me of the intended logic here. We want to expose `LogTaskInputs` as specified in `BuildParameters` to tasks, is that correct? In the commit linked above the flag is hardcoded to true but I guess that's only for testing, it should come from `TaskExecutionHost.LogTaskInputs`.

**Comment by KirillOsenkov** [comment]
Yes, exactly. It shouldn't matter which node the task is running in, tasks should be getting correct LogTaskInputs and be able to act based on the value, like here:

https://github.com/dotnet/msbuild/blob/38da84d453b14008b148c7eea28df24ab4443bb7/src/Tasks/AssemblyDependency/ResolveAssemblyReference.cs#L1317

RAR I'm worried about the most because now we log everything twice, and RAR is by far the biggest source of logging. RAR and a few other tasks (mostly NuGet) should then update to turn off custom logging of parameters when LogTaskInputs is true.
