### ISSUE TITLE
FormatUrl doesn't work on .NET Core

### ISSUE THREAD

**Issue by twsouthwick** [dotnet/msbuild#6313]
### Issue Description
If a WinForm project sets `<GenerateManifests>true<GenerateManifests>` it ends up failing with 

```
error : MSB4803: The task "FormatUrl" is not supported on the .NET Core version of MSBuild. Please use the .NET Framework version of MSBuild. See https://aka.ms/msbuild/MSB4803 for further details
```

I'm not certain if this is expected to succeed since ClickOnce is now supported, but building works fine with .NET Framework msbuild.

### Steps to Reproduce
See project here: https://github.com/twsouthwick/babysmash/pull/new/converted

**Comment by BenVillalobos** [comment]
Team Triage: It certainly looks like we could support this.

```c#

        public override bool Execute()
        {
#if RUNTIME_TYPE_NETCORE
            Log.LogErrorFromResources("TaskRequiresFrameworkFailure", nameof(FormatUrl));
            return false;
#else
            OutputUrl = InputUrl != null ? PathUtil.Format(InputUrl) : String.Empty;
            return true;
#endif
        }
```

@NikolaMilosavljevic @sujitnayak is there a specific reason we wouldn't want to do this?

**Comment by twsouthwick** [comment]
I'd be happy to provide the PR if this can be enabled.

**Comment by BenVillalobos** [comment]
We'd be happy to take a fix, as it seems like a fairly straightforward one.

Double checking with @NikolaMilosavljevic or @sujitnayak if there a specific reason why we don't want to do this on framework.

**Comment by BenVillalobos** [comment]
We're discussing this internally and have a few questions. Could you give us some context around what you're trying to do? It's possible if you're trying to build/publish the Forms project using dotnet CLI that it could fail downstream.

**Comment by sujitnayak** [comment]
@twsouthwick are you trying to build/publish winforms project with the dotnet CLI? If so, ClickOnce publish does not support that. You should be able to build/publish from VS or with the msbuild CLI without having to update FormatUrl for .NET Core.

**Comment by jrdodds** [comment]
Hi @rainersigwald, @marcpopMSFT,
I'd like to take this issue. Seems like the task should be made to work on .NET Core as a general task (regardless of any use by ClickOnce). Is that correct? Thanks

**Comment by BenVillalobos** [comment]
@jrdodds hold off just a bit before diving in to fixing this one. This Thursday, we're going to audit our `up-for-grabs` issues to make sure they're all still relevant today/have enough impact. We'll get back to you then!

**Comment by jrdodds** [comment]
Thanks @BenVillalobos. I'll wait to hear.

I assume it is best to always ask the team before working on any issue. But is there a ranking of the issues within a milestone or tag?

**Comment by BenVillalobos** [comment]
> I assume it is best to always ask the team before working on any issue.

Definitely! The last thing we want is to waste any contributors time.

> But is there a ranking of the issues within a milestone or tag?

Interesting question. We don't rank issues in any particular order, is there a use case you'd have for seeing issues ranked in some way? I assume the preference would be toward higher impact issues?

**Comment by jrdodds** [comment]
The ranking can be arbitrary but, yes, ranking from high to low impact or value would be reasonable.

I was thinking of Azure DevOps and other products that support ranked backlogs. I checked and GitHub doesn't have that feature. Backlogs can be represented by grouping issues by milestone but the issues are not ranked within the milestone.

That said, given two issues that I'm equally comfortable and equipped to tackle, some indicator of which issue is more important to address might be helpful. I assume an `up-for-grabs` issue in a `VS ##.#` milestone is more important than an `up-for-grabs` issue that either has no milestone or is in the `Backlog` milestone.

Thanks

**Comment by hasansachdev** [comment]
looks like this is still an active issue. was there a fix released  for this?

**Comment by rainersigwald** [comment]
No, this hasn't been fixed yet. @hasansachdev, what's your use case?

Regardless of that, I don't see any reason to avoid making this task available on .NET 6--@jrdodds (or someone else) feel free to work on it. Just comment here to let us know and we'll assign it to you.

**Comment by jrdodds** [comment]
@rainersigwald I will take the issue. You can assign it to me. Thanks

**Comment by rainersigwald** [comment]
@jrdodds Awesome. Please let us know if you run into any trouble.
