### ISSUE TITLE
Allow trailing commas in solution filters

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/msbuild#6317]
Have a slnf with trailing comma and try to restore, you get the following error:

```
Solution file error MSB5025: Json in solution filter file "path\to\filter.slnf" is incorrectly formatted.
```

See https://github.com/dotnet/aspnetcore/pull/31438

**Comment by BenVillalobos** [comment]
Where does an issue like this originate? Where did the comma come from?

**Comment by Youssef1313** [comment]
@BenVillalobos For aspnetcore repository, it should have been added manually.

**Comment by rainersigwald** [comment]
We should match the VS behavior here: if it allows trailing commas so should MSBuild.

cc @Forgind
