### ISSUE TITLE
Source Generators fail in WinUI 3 projects because Csc is invoked with AnalyzerConfigFiles

### ISSUE THREAD

**Issue by AArnott** [dotnet/msbuild#6323]
**Describe the bug**

A project reunion project fails to build when it contains code that relies on a Source Generator in any of the XAML code-behind files.

**Steps to reproduce the bug**

(based on @dotMorten's report https://github.com/microsoft/CsWin32/issues/219#issuecomment-811272354)

**[Minimal repro solution](https://github.com/microsoft/CsWin32/files/6238327/App39.zip)**

Or manual steps: 

1. Install Project Reunion Project Templates: https://marketplace.visualstudio.com/items?itemName=ProjectReunion.MicrosoftProjectReunion
2. Create a new Blank App, Packaged (WinUI 3 in Desktop) project.
3. Install the Microsoft.Windows.CsWin32 nuget package (0.1.422-beta)
4. Add NativeMethods.txt and some interop methods to it.
5. Open MainWindow.xaml.cs, and in the constructor add a pinvoke method call.
6. Compile
7. Observe errors in the error list
![error list](https://user-images.githubusercontent.com/1378165/113185548-6e6f1000-920b-11eb-8c76-c237fc8e9bb5.png)

Using VS16.10.p1

**Expected behavior**

The build is successful.

**Analysis**

Examining the build log I've found the problem: 
The `XamlPreCompile` target as defined in `MSBuild\Current\Bin\Microsoft.CSharp.CurrentVersion.targets` invokes the `Csc` task but omits AnalyzerConfigFiles that is normally passed in. As a result, the CsWin32 source generator is not getting the info it needs to generate the APIs referenced in the XAML code-behind.

As the faulty target is defined in `Microsoft.CSharp.CurrentVersion.targets`, this repo seemed the most appropriate place to file the issue.

**Screenshots**

The `CoreCompile` target's invocation of Csc:
![image](https://user-images.githubusercontent.com/3548/113191774-2d7ef780-921b-11eb-98a6-6beacbb2eb7d.png)

XamlPreCompile target's invocation of Csc:
![image](https://user-images.githubusercontent.com/3548/113191681-13ddb000-921b-11eb-8f68-b22a17482b10.png)

**Comment by rainersigwald** [comment]
@jmarolf Since we have this (extremely unfortunate) dependency in core targets, can we get someone from Roslyn to port the changes to CoreCompile to the `XamlPreCompile` task? And I guess add the updating to the to-do list for changing that target?

https://github.com/dotnet/msbuild/blob/1cfebe4dd3b1bb26bbf76128ff5f9270b6c090bb/src/Tasks/Microsoft.CSharp.CurrentVersion.targets#L163-169

**Comment by rainersigwald** [comment]
cc @chsienki -- looks like you did this semi-recently in #6096.

**Comment by chsienki** [comment]
@rainersigwald Yeah, I can port the fix. We should probably do an audit of all the CSC tasks across the dotnet org and make sure we a) know about them all and b) they match.

Now that we have arcade is there anyway we can ship a single 'include' proj file that each dependent repo uses to perform the actual invocation?

**Comment by BenVillalobos** [comment]
team triage: right now we don't have an easy way to have a single source of truth. We don't think arcade helps with that unfortunately

**Comment by riverar** [comment]
Any news on which deliverable will contain this fix? Seems to still be broken in Visual Studio 16.10p3 / latest .NET 5 SDK.

**Comment by riverar** [comment]
Not sure if the commit @rainersigwald made was to fix this issue or is prep work, but I made those changes locally and it didn't resolve the error. (Goes back into cave.)

**Comment by rainersigwald** [comment]
@riverar It should be fixed in VS 16.10 preview 4.

> I made those changes locally and it didn't resolve the error.

Which changes, exactly? @chsienki was able to build a project after applying #6438, I believe.

**Comment by riverar** [comment]
@rainersigwald Same changes you referenced. But I made the changes to my `Microsoft.CSharp.CurrentVersion.targets` delivered per the dotnet SDK not Visual Studio. After making the Visual Studio targets change (`Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\Microsoft.CSharp.CurrentVersion.targets`), I was able to validate the fix 👍

**Comment by rainersigwald** [comment]
🎉 Thanks for following up!
