### ISSUE TITLE
How deploy webapp to Azure from command line

### ISSUE THREAD

**Issue by ProGesss** [dotnet/msbuild#6333]
I have a project https://github.com/microsoftgraph/microsoft-graph-comms-samples/tree/master/Samples
which is deployed to Azure via Visual Studio 2019
How can I strip it through the command line?
when i executing this command
"C: \ Program Files (x86) \ Microsoft Visual Studio \ 2019 \ Community \ MSBuild \ Current \ Bin \ amd64 \ MSBuild.
exe "PolicyRecordingBot.sln / t: Publish / p: DeployOnBuild = true / p: Configuration = Release
build passes and I get
"Publishing process has completed.
Build succeeded."
Deployment to Azure fails, .azurePubxml file is ignored

**Comment by BenVillalobos** [comment]
Team Triage: This is a question for the Azure SDK team, which owns the publication process. From a quick look at their docs, they don't have integration with msbuild but you can build it in the command line. See https://docs.microsoft.com/visualstudio/azure/vs-azure-tools-publishing-using-powershell-scripts
