### ISSUE TITLE
Build events create batch files in temp directory which are then blocked by AppLocker

### ISSUE THREAD

**Issue by Balkoth** [dotnet/msbuild#6340]
### Issue Description
If AppLocker is active on the system you are using and you try to run a post build event in Visual Studio, e.g. to sign the binary you are developing to be accepted by AppLocker, MSBUILD creates a batch file in %TEMP% with the contents of the post build event. The execution of this batch file is in response then blocked by AppLocker.

### Steps to Reproduce

- Enable AppLocker on the machine used for developing
- Run Visual Studio with a normal user account (WITHOUT administrative rights)
- Configure a directory where your projects can be run without restrictions
- Create one of the aforementioned projects in that directory
- Add a post build event to that project

### Expected Behavior
The project builds and runs without issue.

### Actual Behavior
The projects builds, but the post build event fails.

### Analysis
https://developercommunity.visualstudio.com/t/Build-events-create-batch-files-in-temp/1339881#T-N1387549-N1391588

Comment from Benjamin Villalobos [MSFT]:
As I suspected, the inherent problem here is that MSBuild creates a batch file to run commands via exec, and that batch file is created in temp. If changing %TEMP% or relaxing applocker aren’t options, your best bet is to file an issue with MSBuild or to create a custom task that will take your script and create a process directly out of it.

### Versions & Configurations

Windows 10 2004 (Build 19041.804)
Visual Studio 2019 16.9.3

MSBUILD:
Microsoft (R)-Build-Engine, Version 16.9.0+5e4b48a27 für .NET Framework
Copyright (C) Microsoft Corporation. Alle Rechte vorbehalten.

16.9.0.16703

**Comment by BenVillalobos** [comment]
Thanks for filing the issue in our repo!

Exec creates the batch file and runs it because of DOS semantics. Is there a particular reason you can't change your %TEMP% environment variable to something like your project's `obj/` folder? Maybe have a script you run before/after you launch VS?

**Comment by Balkoth** [comment]
I think this can only be a temporary solution until VisualStudio and MSBUILD let you configure where those batch files are written and executed.

Running VisualStudio from a batch file defeats the whole windows integration. For example you get no jumplists. If you want to load specific projects, you have to create shortcuts for each project.

So imho and as AppLocker and VisualStudio/MSBUILD are Microsoft products, there has to be a better solution.

**Comment by BenVillalobos** [comment]
Looks like we have an existing issue for this [here](https://github.com/dotnet/msbuild/issues/399), as this issue is essentially asking to allow exec to run without creating that temp file.
