### ISSUE TITLE
Add Binary Compat Checker to CI

### ISSUE THREAD

**Issue by benvillalobos** [dotnet/msbuild#6356]
Mentioned in PR review today. @KirillOsenkov [created a tool](https://github.com/KirillOsenkov/MetadataTools/tree/main/src/BinaryCompatChecker) that can check binary compat based on an app.config and a directory that contains dll's.

We should consider adding it somewhere as automation so we don't get a surprise breakage.

**Comment by JanKrivanek** [comment]
Is this still valid?
[.NET Package Validateion](https://learn.microsoft.com/en-us/dotnet/fundamentals/package-validation/overview) seems to fullfill the needs (we're opting in via `EnablePackageValidation`).

@KirillOsenkov - was the tool able to achive some checks not achievable via API Compatability checking?

**Comment by rainersigwald** [comment]
At a glance, I agree this can be closed.
