### ISSUE TITLE
MSBuild Exec task with ToolPath broken

### ISSUE THREAD

**Issue by bombless** [dotnet/msbuild#6362]
# Repro steps

-  On a non-Windows OS
-   Run `dotnet msbuild` with the following project
```xml
<Project>
    <Target Name="Build">
        <Exec ToolPath="." Command="echo Hello World" />
    </Target>
</Project>
```
# Expected
Build succeeds

# Actual
Build fails with the following:
```sh
Microsoft (R) Build Engine version 16.9.0+57a23d249 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

/Users/yuekexiang/t(3,9): error MSB6004: The specified task executable location "./sh" is invalid.
```

# Version
I'm using installation from `https://download.visualstudio.microsoft.com/download/pr/749775e4-7b6f-4367-bb7a-9cb63a818dae/c2614b34e234fa03dc65320a8a954570/dotnet-sdk-5.0.202-osx-x64.pkg`
`dotnet msbuild -ver` shows `16.9.0.11203`

**Comment by BenVillalobos** [comment]
Team Triage: It doesn't make sense to specify ToolPath for the Exec task. The exec task will always use a shell to run its commands. Additionally, our repo requires being `git clone`'d. A tarball of our repo is not buildable by itself.

Please let us know if you have any further problems building MSBuild
