### ISSUE TITLE
MSBuild not signing UWP Application correctly from command line

### ISSUE THREAD

**Issue by luEbe** [dotnet/msbuild#6364]
### Issue Description
We are using MSBuild to build and sign a UWP Application from the command line using a pfx file that was signed by our own root authority. 

This used to work up until a few weeks ago (the exact point in time is unclear, somewhere between 25. February and 31. March).

The problem is, that the application is not signed using the provided pfx file from the MSBuild Arguments, but rather with a disposable one created at build time by the Task "GenerateDisposableSigningCertificate".

### Steps to Reproduce
Using a UWP Application with `<UseDotNetNativeToolchain>true</UseDotNetNativeToolchain>` set in the csproj file and the following command line invocation:
```
msbuild *.sln /p:AppxBundlePlatforms="x64" /p:AppxPackageDir="C:\Users\<user>\Desktop\\" /p:AppxBundle=Always /p:UapAppxPackageBuildMode=StoreUpload /p:AppxPackageSigningEnabled=true /p:PackageCertificateThumbprint="insert-thumbrpint" /p:PackageCertificateKeyFile="C:\Users\user\SomeCertificate.pfx" /p:PackageCertificatePassword="**************" /p:platform="x64" /p:configuration="Release"
```
Setting the dotnet native toolchain to false fixes the issue, but is not an acceptable solution to us.

### Analysis
After removing the argument `/p:UapAppxPackageBuildMode=StoreUpload`, the supplied pfx file is used to sign the application.
It seems that setting the above mentioned parameter also causes `/p:BuildAppxUploadPackageForUap=true` to be set, which in turn causes a Disposable Certificate to be used for signing.

As previously mentioned, this did not use to be like that in earlier versions of MSBuild as it always worked just fine. What could have been introduced, that causes a store uploadable application to be signed with a disposable certificate by default?

I already opened an issue on a different repo, as I initially expected the bug to be somewhere else. (see https://github.com/actions/virtual-environments/issues/3183)

### Versions & Configurations
MSBuild Version: 16.9.0.16703
Visual Studio Version: 16.9.4

**Comment by glsorre** [comment]
I definitively have the same problem.

**Comment by xpetrik** [comment]
Same in our company. Our build process is broken after update to 16.9.4

**Comment by BenVillalobos** [comment]
Team Triage: @SvetBonev do you know what's going on here? If so, could you help route this?

**Comment by SvetBonev** [comment]
@japarson

**Comment by japarson** [comment]
Hi everyone, sorry for the trouble. Updating to 16.9.5 should fix this problem.
