### ISSUE TITLE
Allow trailing comma in .slnf Json files to match VS

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/msbuild#6371]
VS is able to open .slnf files if the Json has a trailing comma.

MSBuild shows an error: 

```
Solution file error MSB5025: Json in solution filter file "C:\AspNetCore\src\Razor\razor.slnf" is incorrectly formatted.
```

See https://github.com/dotnet/aspnetcore/pull/32141 for an example

**Comment by rainersigwald** [comment]
Duplicate of #6317
