### ISSUE TITLE
MSBuild 16.9.0+5e4b48a27 seems unstable/spuriously dies/ TypeLoadException

### ISSUE THREAD

**Issue by jzabroski** [dotnet/msbuild#6404]
### Issue Description
When running an MSBuild task (most likely Build as a pre-target to another target), MSBuild dies.

### Steps to Reproduce
Run MSBuild either from within latest VS2019 or from command line:

Here is a powershell program:

```powershell
$target = "build"
& "C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin\MsBuild.exe" build.targets /v:minimal /m /t:$target
```

### Expected Behavior
Build program successfully.

### Actual Behavior
When running MSBuild.exe, I get the following error:

```
Application: MSBuild.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.TypeLoadException
   at Microsoft.Build.CommandLine.MSBuildApp.Execute(System.String)
   at Microsoft.Build.CommandLine.MSBuildApp.Main()
```

### Analysis
MSBuild seems to be trying to load some type, and fails.  It would be helpful if MSBuild would specifically catch TypeLoadException in places it dynamically loads types.

### Versions & Configurations
MSBuild 16.9.0+5e4b48a27
Visual Studio 2019 16.9.4
.NET Framework 4.8.03761
OS: Microsoft Windows Server 2016 Datacenter 10.0.14393 w/ 14393 hotfix (retrieved from `get-ComputerInfo`)

### Attach a binlog
I have downloaded the Project System Tools extension and should be able to capture a binlog the next time msbuild crashes.

https://docs.microsoft.com/en-us/visualstudio/ide/msbuild-logs?view=vs-2019#create-a-binary-msbuild-log-by-using-the-project-system-tools-extension

**Comment by jzabroski** [comment]
Hmm... I am experiencing a lot of quality issues with VS 2019 16.9.4 . My Resharper test runner component just died.

I have generally not had MSBuild or Resharper quality issues since Visual Studio 2017 beta releases.

**Comment by jzabroski** [comment]
See also: https://github.com/microsoft/MSBuildLocator/issues/126

**Comment by BenVillalobos** [comment]
Team Triage: is that the full output of running msbuild.exe?

**Comment by jzabroski** [comment]
Yes, that is the full output.

I have not tried running repair - but what problem would that solve given Event Viewer dumps the associated stack trace?  It's not like this stack trace was just magically created.

I also see 16.9.5 is now available, and was going to upgrade to that.

**Comment by BenVillalobos** [comment]
Team Triage: Is there any additional output if you remove `/v:minimal`? Can you download & run https://github.com/dotnet/msbuild/blob/main/scripts/EnumerateMSBuild.ps1 and send the output?

**Comment by jzabroski** [comment]
Hmm... that is odd.. the @VisualStudio twitter account mentions 16.9.5 is available but when I "Check for updates", 16.9.4 is all I see and my Visual Studio is pronounced up to date.

![image](https://user-images.githubusercontent.com/447485/117168305-06759180-ad96-11eb-9243-4a7f55ddb72a.png)

**Comment by jzabroski** [comment]
> Team Triage: Is there any additional output if you remove `/v:minimal`?

I removed this - didn't even see that. Ha - apologies.  May take a few runs before I can reproduce the issue, as it doesn't happen on every run.  Seems to mostly happen when the project is modified.



> Can you download & run https://github.com/dotnet/msbuild/blob/main/scripts/EnumerateMSBuild.ps1 and send the output?

I got an error running that script:

```powershell
PS D:\Users\John.Zabroski\source> .\EnumerateMSBuild.ps1
Using vswhere from C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe
Found VS Instance: VisualStudio/16.9.4+31205.134
Get-ChildItem: D:\Users\John.Zabroski\source\EnumerateMSBuild.ps1:38
Line |
  38 |      ls -File -Recurse -Include ('*.dll', '*.exe') -Path "$instancePat …
     |      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot find path 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\15.0\Bin'
     | because it does not exist.


Looking for legacy MSBuild versions: C:\Program Files (x86)\MSBuild\

Looking for MSBuild in the GAC: C:\Windows\Microsoft.NET\assembly

Looking for MSBuild in the GAC: C:\Windows\assembly

Output saved to D:\Users\John.Zabroski\source\msbuild_versions.txt
```
Attached is the generated file.
[msbuild_versions.txt](https://github.com/dotnet/msbuild/files/6428365/msbuild_versions.txt)

**Comment by jzabroski** [comment]
I'm not sure if this is related, but, got this today:

```
Microsoft (R) Build Engine version 16.9.0+5e4b48a27 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

MSBUILD : error MSB1025: An internal failure occurred while running MSBuild.
System.BadImageFormatException: Bad binary signature. (Exception from HRESULT: 0x80131192)
   at Microsoft.Build.CommandLine.MSBuildApp.BuildProject(String projectFile, String[] targets, String toolsVersion, Dictionary`2 globalProperties, Dictionary`2 restoreProperties, ILogger[] loggers, LoggerVerbosity verbosity, DistributedLoggerRecord[] distributedLoggerRecords, Boolean needToValidateProject, String schemaFile, Int32 cpuCount, Boolean enableNodeReuse, TextWriter preprocessWriter, TextWriter targetsWriter, Boolean detailedSummary, ISet`1 warningsAsErrors, ISet`1 warningsAsMessages, Boolean enableRestore, ProfilerLogger profilerLogger, Boolean enableProfiler, Boolean interactive, Boolean isolateProjects, Boolean graphBuild, Boolean lowPriority, String[] inputResultsCaches, String outputResultsCache)
   at Microsoft.Build.CommandLine.MSBuildApp.Execute(String commandLine)

Unhandled Exception: System.BadImageFormatException: Bad binary signature. (Exception from HRESULT: 0x80131192)
   at Microsoft.Build.CommandLine.MSBuildApp.BuildProject(String projectFile, String[] targets, String toolsVersion, Dictionary`2 globalProperties, Dictionary`2 restoreProperties, ILogger[] loggers, LoggerVerbosity verbosity, DistributedLoggerRecord[] distributedLoggerRecords, Boolean needToValidateProject, String schemaFile, Int32 cpuCount, Boolean enableNodeReuse, TextWriter preprocessWriter, TextWriter targetsWriter, Boolean detailedSummary, ISet`1 warningsAsErrors, ISet`1 warningsAsMessages, Boolean enableRestore, ProfilerLogger profilerLogger, Boolean enableProfiler, Boolean interactive, Boolean isolateProjects, Boolean graphBuild, Boolean lowPriority, String[] inputResultsCaches, String outputResultsCache)
   at Microsoft.Build.CommandLine.MSBuildApp.Execute(String commandLine)
   at Microsoft.Build.CommandLine.MSBuildApp.Main()
```

**Comment by jzabroski** [comment]
Repro'd on 16.9.5.

```
Faulting application name: MSBuild.exe, version: 16.9.0.16703, time stamp: 0xda545832
Faulting module name: KERNELBASE.dll, version: 10.0.14393.4350, time stamp: 0x606eb12a
Exception code: 0xe0434352
Fault offset: 0x000dc602
Faulting process id: 0x445c
Faulting application start time: 0x01d74789d81db307
Faulting application path: C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin\MSBuild.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: 81a79060-e2fd-4c90-9370-33119f8d830c
Faulting package full name: 
Faulting package-relative application ID: 
```

**Comment by BenVillalobos** [comment]
> Unhandled Exception: System.BadImageFormatException: Bad binary signature. (Exception from HRESULT: 0x80131192)

Did you run VS repair? Updating may not have changed your msbuild binaries.

**Comment by jzabroski** [comment]
Hi Ben,

I didn't. I thought upgrading was sufficient but see that repair is likely necessary and sufficient to troubleshoot further. 

I have not had this issue since last repro.

**Comment by BenVillalobos** [comment]
Glad it's no longer an issue! 🎉

Feel free to reopen if you see this again.

**Comment by jzabroski** [comment]
Issue happened again.  This time it happened when I took latest from version control.  It seems as if there was a passive MSBuild.exe hanging around.

@BenVillalobos  Re-open button isn't available - I can only comment.

```
Application: MSBuild.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.TypeLoadException
   at Microsoft.Build.CommandLine.MSBuildApp.Execute(System.String)
   at Microsoft.Build.CommandLine.MSBuildApp.Main()
```
```
Faulting application name: MSBuild.exe, version: 16.9.0.16703, time stamp: 0xda545832
Faulting module name: KERNELBASE.dll, version: 10.0.14393.4350, time stamp: 0x606eb12a
Exception code: 0xe0434352
Fault offset: 0x000dc602
Faulting process id: 0x70c
Faulting application start time: 0x01d76db5d660d64d
Faulting application path: C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin\MSBuild.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: bf0dcd00-ca0d-42a9-80fb-68349b2e777a
Faulting package full name: 
Faulting package-relative application ID: 
```
