### ISSUE TITLE
Object Reference Exception When Removing a Database Reference

### ISSUE THREAD

**Issue by BenVillalobos** [dotnet/msbuild#6420]
See https://github.com/dotnet/msbuild/pull/6212 for more context.

### Issue Description
In a SQL Server DB project, you hit a "Object Reference not set to instance of object" dialog when removing a database reference.

### Steps to Reproduce
Create a SQL Server Database project - You may need to install "Data storage and processing" workload in VS
Right click on References and select ‘Add Database Reference…’
Choose System database and select ‘master’ and click ‘OK’
Build the project and Check the .sqlproj file, it should have
```xml
      <ItemGroup>
  <ArtifactReference Include="$(DacPacRootPath)\Extensions\Microsoft\SQLDB\Extensions\SqlServer\130\SqlSchemas\master.dacpac">
    <HintPath>$(DacPacRootPath)\Extensions\Microsoft\SQLDB\Extensions\SqlServer\130\SqlSchemas\master.dacpac</HintPath>
    <SuppressMissingDependenciesErrors>False</SuppressMissingDependenciesErrors>
    <DatabaseVariableLiteralValue>master</DatabaseVariableLiteralValue>
  </ArtifactReference>
</ItemGroup>
```
Right click on ‘master’ reference on Solution Explorer and select Remove
It will throw ‘Object reference not set to an instance of an object’ and removes from UI
Check the .sqlproj and you can see it still has the reference as is.
Right click on References and select ‘Add Database Reference…’ and Choose System database and select ‘msdb’ and click ‘OK’
Build the project and Check the .sqlproj file. It would have something like:
```xml
      <ItemGroup>
  <ArtifactReference Include="C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\Common7\IDE\Extensions\Microsoft\SQLDB\Extensions\SqlServer\130\SqlSchemas\master.dacpac">
    <HintPath>C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\Common7\IDE\Extensions\Microsoft\SQLDB\Extensions\SqlServer\130\SqlSchemas\master.dacpac</HintPath>
    <SuppressMissingDependenciesErrors>False</SuppressMissingDependenciesErrors>
    <DatabaseVariableLiteralValue>master</DatabaseVariableLiteralValue>
  </ArtifactReference>
  <ArtifactReference Include="$(DacPacRootPath)\Extensions\Microsoft\SQLDB\Extensions\SqlServer\130\SqlSchemas\msdb.dacpac">
    <HintPath>$(DacPacRootPath)\Extensions\Microsoft\SQLDB\Extensions\SqlServer\130\SqlSchemas\msdb.dacpac</HintPath>
    <SuppressMissingDependenciesErrors>False</SuppressMissingDependenciesErrors>
    <DatabaseVariableLiteralValue>msdb</DatabaseVariableLiteralValue>
  </ArtifactReference>
</ItemGroup>
```
For master.dacpac, $(DacPacRootPath) is changed C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\Common7\IDE instead of removing the ArtifactReference.

### Expected Behavior
No dialog comes up.

### Actual Behavior
Object reference not set to... dialog box appears.

### Analysis
See the PR that's linked at the top of this issue.

**Comment by rainersigwald** [comment]
If you get back to this, I'd love to first know what the call stack of the exception is.

**Comment by rainersigwald** [comment]
Talked to @BenVillalobos offline--we don't have a repro or a stack so this isn't very actionable.

**Comment by Andy-INX** [comment]
If anyone is still interested I just came across this.
We added a MSDB & MASTER DB reference to a SQL Database Project in VS2019.
In a 2nd SQL Database Project we added a MSDB & MASTER DB reference as well as a reference to the 1st project.
Then kept getting "duplicate reference" when building it in Azure DevOps.
Turns out VS added a double-reference to the 1st project - one relative and one absolute! (but not the 2nd - and I would have expected this to happen to the 2nd because it references the 1st?!).
```xml
  <ItemGroup>
    <ArtifactReference Include="C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\Common7\IDE\Extensions\Microsoft\SQLDB\Extensions\SqlServer\130\SqlSchemas\master.dacpac">
      <HintPath>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\Common7\IDE\Extensions\Microsoft\SQLDB\Extensions\SqlServer\130\SqlSchemas\master.dacpac</HintPath>
      <SuppressMissingDependenciesErrors>False</SuppressMissingDependenciesErrors>
      <DatabaseVariableLiteralValue>master</DatabaseVariableLiteralValue>
    </ArtifactReference>
    <ArtifactReference Include="C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\Common7\IDE\Extensions\Microsoft\SQLDB\Extensions\SqlServer\130\SqlSchemas\msdb.dacpac">
      <HintPath>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\Common7\IDE\Extensions\Microsoft\SQLDB\Extensions\SqlServer\130\SqlSchemas\msdb.dacpac</HintPath>
      <SuppressMissingDependenciesErrors>False</SuppressMissingDependenciesErrors>
      <DatabaseVariableLiteralValue>msdb</DatabaseVariableLiteralValue>
    </ArtifactReference>
    <ArtifactReference Include="$(DacPacRootPath)\Extensions\Microsoft\SQLDB\Extensions\SqlServer\130\SqlSchemas\master.dacpac">
      <HintPath>$(DacPacRootPath)\Extensions\Microsoft\SQLDB\Extensions\SqlServer\130\SqlSchemas\master.dacpac</HintPath>
      <SuppressMissingDependenciesErrors>True</SuppressMissingDependenciesErrors>
      <DatabaseVariableLiteralValue>master</DatabaseVariableLiteralValue>
    </ArtifactReference>
    <ArtifactReference Include="$(DacPacRootPath)\Extensions\Microsoft\SQLDB\Extensions\SqlServer\130\SqlSchemas\msdb.dacpac">
      <HintPath>$(DacPacRootPath)\Extensions\Microsoft\SQLDB\Extensions\SqlServer\130\SqlSchemas\msdb.dacpac</HintPath>
      <SuppressMissingDependenciesErrors>True</SuppressMissingDependenciesErrors>
      <DatabaseVariableLiteralValue>msdb</DatabaseVariableLiteralValue>
    </ArtifactReference>
  </ItemGroup>
```
