### ISSUE TITLE
AssemblySearchPaths lacks $(OutDir) when building SDK style

### ISSUE THREAD

**Issue by MarkKharitonov** [dotnet/msbuild#6441]
### Issue Description
We use shared bin directory for local and CI builds.
Before migrating to SDK style we could reference assemblies from previously built solutions like this:
```
<Reference Include="SomeAssembly" />
```
After migration to SDK style this reference is no longer recognized. It is silently ignored, the build breaks.

### Steps to Reproduce
1. Take a legacy project, put some assembly into its OutDir and reference as shown above. The build should pass
2. Migrate the project to SDK and build - the build should fail.

### Analysis
C:\Program Files\dotnet\sdk\5.0.202\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.props defines **AssemblySearchPaths** like this:
```
    <AssemblySearchPaths Condition=" '$(AssemblySearchPaths)' == '' ">{CandidateAssemblyFiles};{HintPathFromItem};{TargetFrameworkDirectory};{RawFileName}</AssemblySearchPaths>
```
It omits `$(OutDir)`. Then C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets is imported and it contains the following code:
```
    <AssemblySearchPaths Condition=" '$(AssemblySearchPaths)' == ''">
      {CandidateAssemblyFiles};
      $(ReferencePath);
      {HintPathFromItem};
      {TargetFrameworkDirectory};
      $(AssemblyFoldersConfigFileSearchPath)
      {Registry:$(FrameworkRegistryBase),$(TargetFrameworkVersion),$(AssemblyFoldersSuffix)$(AssemblyFoldersExConditions)};
      {AssemblyFolders};
      {GAC};
      {RawFileName};
      $(OutDir)
    </AssemblySearchPaths>
```
However, **AssemblySearchPaths** has already been set and nothing happens here.

In the legacy projects this is the only definition of **AssemblySearchPaths** and thus it has `$(OutDir)`.

The workaround is to add the following code to Directory.Build.targets:
```
<AssemblySearchPaths>$(AssemblySearchPaths);$(OutDir)</AssemblySearchPaths>
```
### Versions & Configurations

- Windows 10
- VS 16.9.4
- msbuild 16.9.0.16703

### Attach a binlog
My solution contains too many projects. I did not come up with minimal repro, but it should be trivial. Let me know if you insist on the binary log.

**Comment by BenVillalobos** [comment]
Team Triage: This is intentionally left out of the sdk, see: 

https://github.com/dotnet/sdk/blob/6945e3694c918eea4c8c4fb6217e1485b179994b/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.props#L92-L93

Here's the PR that introduced it: https://github.com/dotnet/sdk/pull/176

Your change is the way to go if you want to opt into this in your projects.

**Comment by MarkKharitonov** [comment]
I understand why GAC and registry were removed. But removing output directory is a mistake, in my opinion.
Imagine migrating code from legacy to SDK style in the presence of a shared bin directory and multiple solutions. Not a far fetched scenario. You do all by the book, but your references now stop working. Go figure why.

Can you provide the rationale behind the removal of `$(OutDir)` from that list ?

**Comment by jhudler** [comment]
I agree with @MarkKharitonov . I'm my case, I'm also missing $(ReferencePath) in this list, which removal seems to have broken the VB.NET the Project "Reference Path" tab in Visual Studio. If $(ReferencePath) is emtpy, what implications would it have in performance? Why not have it?

**Comment by BenVillalobos** [comment]
Team Triage: This is by design now, but if you feel strongly about this please open up an issue over in dotnet/sdk.
