### ISSUE TITLE
MSBuild fails to build project with long path.

### ISSUE THREAD

**Issue by VirusQuartirus** [dotnet/msbuild#6455]
### Issue Description
When project has a long path name (longer that MAX_PATH) MSBuild fails to build C# project that targets netcoreapp3.0 and higher

### Steps to Reproduce
PS commands:
1. Create long path dir:
`md -Path \\?\D:\VeryVeryVeryVeryVeryVeryVeryVery\VeryVeryVeryVeryVeryVeryVeryVery\VeryVeryVeryVeryVeryVeryVeryVery\VeryVeryVeryVeryVeryVeryVeryVery\VeryVeryVeryVeryVeryVeryVeryVery\VeryVeryVeryVeryVeryVeryVeryVery\VeryVeryVeryVeryVeryVeryVeryVery\VeryVeryVeryVeryVeryVeryVeryVery\LongPath`
2. Create console app:
`dotnet new console -o D:\VeryVeryVeryVeryVeryVeryVeryVery\VeryVeryVeryVeryVeryVeryVeryVery\VeryVeryVeryVeryVeryVeryVeryVery\VeryVeryVeryVeryVeryVeryVeryVery\VeryVeryVeryVeryVeryVeryVeryVery\VeryVeryVeryVeryVeryVeryVeryVery\VeryVeryVeryVeryVeryVeryVeryVery\VeryVeryVeryVeryVeryVeryVeryVery\LongPath\ConsoleApp10`
3. Run build:
`dotnet build D:\VeryVeryVeryVeryVeryVeryVeryVery\VeryVeryVeryVeryVeryVeryVeryVery\VeryVeryVeryVeryVeryVeryVeryVery\VeryVeryVeryVeryVeryVeryVeryVery\VeryVeryVeryVeryVeryVeryVeryVery\VeryVeryVeryVeryVeryVeryVeryVery\VeryVeryVeryVeryVeryVeryVeryVery\VeryVeryVeryVeryVeryVeryVeryVery\LongPath\ConsoleApp10\ConsoleApp10.csproj`

### Expected Behavior
Build should run successfuly.

### Actual Behavior
Build failed with message:

```
C:\Program Files\dotnet\sdk\5.0.203\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(508,5): error MSB4018: The "CreateAppHost" task failed unexpectedly. [D:\Very...Very\LongPath\ConsoleApp10\ConsoleApp10.csproj]
C:\Program Files\dotnet\sdk\5.0.203\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(508,5): error MSB4018: Microsoft.NET.HostModel.HResultException: 8007007A [D:\Very...Very\LongPath\ConsoleApp10\ConsoleApp10.csproj]
C:\Program Files\dotnet\sdk\5.0.203\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(508,5): error MSB4018:    at Microsoft.NET.HostModel.ResourceUpdater.ThrowExceptionForLastWin32Error() [D:\Very...Very\LongPath\ConsoleApp10\ConsoleApp10.csproj]
C:\Program Files\dotnet\sdk\5.0.203\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(508,5): error MSB4018:    at Microsoft.NET.HostModel.ResourceUpdater.Update() [D:\Very...Very\LongPath\ConsoleApp10\ConsoleApp10.csproj]
C:\Program Files\dotnet\sdk\5.0.203\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(508,5): error MSB4018:    at Microsoft.NET.HostModel.RetryUtil.RetryOnWin32Error(Action func) [D:\Very...Very\LongPath\ConsoleApp10\ConsoleApp10.csproj]
C:\Program Files\dotnet\sdk\5.0.203\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(508,5): error MSB4018:    at Microsoft.NET.HostModel.AppHost.HostWriter.CreateAppHost(String appHostSourceFilePath, String appHostDestinationFilePath, String appBinaryFilePath, Boolean windowsGraphicalUserInterface, String assemblyToCopyResorcesFrom) [D:\Very...Very\LongPath\ConsoleApp10\ConsoleApp10.csproj]
C:\Program Files\dotnet\sdk\5.0.203\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(508,5): error MSB4018:    at Microsoft.NET.Build.Tasks.CreateAppHost.ExecuteCore() [D:\Very...Very\LongPath\ConsoleApp10\ConsoleApp10.csproj]
C:\Program Files\dotnet\sdk\5.0.203\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(508,5): error MSB4018:    at Microsoft.NET.Build.Tasks.TaskBase.Execute() [D:\Very...Very\LongPath\ConsoleApp10\ConsoleApp10.csproj]
C:\Program Files\dotnet\sdk\5.0.203\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(508,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute() [D:\Very...Very\LongPath\ConsoleApp10\ConsoleApp10.csproj]
C:\Program Files\dotnet\sdk\5.0.203\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(508,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask) [D:\Very...Very\LongPath\ConsoleApp10\ConsoleApp10.csproj]
    0 Warning(s)
    1 Error(s)
```

### Versions & Configurations
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.19041 N/A Build 19041

dotnet --version
5.0.203

dotnet msbuild --version
Microsoft (R) Build Engine version 16.9.0+57a23d249 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.
16.9.0.11203

**Comment by VirusQuartirus** [comment]
When change <TargetFramework>net5.0</TargetFramework> to <TargetFramework>netcoreapp2.1</TargetFramework> build runs OK.

**Comment by rainersigwald** [comment]
Thanks for the report. This task lives in another repo, where there seems to be a bug for this already, so I'm going to close this.

**Comment by rainersigwald** [comment]
Duplicate of https://github.com/dotnet/runtime/issues/39211
