### ISSUE TITLE
Consider Server GC

### ISSUE THREAD

**Issue by rainersigwald** [dotnet/msbuild#6462]
Many processes have noticeable performance improvements from opting into Server GC. We should see if MSBuild is one of those. Note that VS has its own switch so this would apply only to command line builds/worker nodes.

**Comment by jeffkl** [comment]
For static graph restore I had to implement an entire console app just to get server GC when running a task: https://github.com/NuGet/NuGet.Client/tree/dev/src/NuGet.Core/NuGet.Build.Tasks.Console

If MSBuild either used server GC or we added the ability for a task to run in an out of proc node that used server GC, then static graph restore could be simplified quite a bit.

**Comment by rainersigwald** [comment]
From [internal discussion](https://teams.microsoft.com/l/message/19:3212bf033f4c4b5198643a04fa1048fa@thread.skype/1621369012855?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=4ba7372f-2799-4677-89f0-7a1aaea3706c&parentMessageId=1621350887907&teamName=.NET%20Developer%20Experience&channelName=MSBuild&createdTime=1621369012855), it sounds like this is likely a bad idea, right? Should we just close it out?

**Comment by AR-May** [comment]
Let's close it then.

**Comment by safesparrow** [comment]
Server GC makes a massive difference in design-time build in Rider for larger solutions, as the main bottleneck is the "coordinator" msbuild node that delegates lots of work to multiple subprocesses.
Rider changed the defaults in recent versions to use it.

Is there any public info on why this was dismissed for commandline msbuild?

Can it still be enabled by the enduser through dotnet environment variables? 

Are there any test results showing the impact?
