### ISSUE TITLE
Could not locate packages.config

### ISSUE THREAD

**Issue by RhomGit** [dotnet/msbuild#6464]
Hi, firstly please excuse my ignorance regarding msbuild.

A few months ago I migrated all of my of the projects in our solution away from packages.config. Some projects were automatic, some had to be done manually.

Now I have the following error when I build.
Note: building a SECOND time straight away allows me to run the (WPF) app.
![image](https://user-images.githubusercontent.com/25700833/118742354-d5f82200-b882-11eb-915a-da10b679194a.png)

`Could not locate C:\B2iGit\RhomGit\AE-Dev\B2i.Ext.ADO\packages.config.  Ensure that this project has Microsoft.Bcl.Build installed and packages.config is located next to the project file.	B2i.Desktop	C:\Users\rhom\.nuget\packages\microsoft.bcl.build\1.0.21\build\Microsoft.Bcl.Build.targets	243	`

![image](https://user-images.githubusercontent.com/25700833/118742424-f1fbc380-b882-11eb-92c9-f02847ac000e.png)

If my project files are using PackageReferences, why is it looking for packages.config?
At the top of my project file I have this:   
`<Import Project="$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props" Condition="Exists('$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props')" />`

At the bottom of my project file I have this:   
`<Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets" />`

.NET Framework 4.6.1 using Visual Studio 2019 16.9.5

Thanks

**Comment by rainersigwald** [comment]
Looks like that package predates `PackageReference`, so it's probably just wrong. If you can't remove the reference, I see that there's a way to disable this check: set the property `SkipValidatePackageReferences` to `true`.

**Comment by RhomGit** [comment]
Thanks for pointing me in the right direction.
I set the property as you suggested in the .csproj file in my main project and it has stopped complaining/built correctly. So simple.

ref: https://stackoverflow.com/questions/17180268/warning-all-projects-referencing-myproject-csproj-must-install-nuget-package-m
