### ISSUE TITLE
MSBuild Server v1

### ISSUE THREAD

**Issue by rokonec** [dotnet/msbuild#6494]
To improve inner loop experience of building small project fast in scenarios:
- dotnet new console
- dotnet build/run

We force MSBuild to always use external reusable nodes/processes to build projects.

Measured improvement: https://github.com/dotnet/msbuild/issues/6467

Implementation:
- Modify SDK to set MSBUILDNOINPROCNODE = 1
- Implement escape hatches DOTNET_DO_NOT_USE_MSBUILDNOINPROCNODE = 1

--------------------------------------- PARKED ------------------------------------

TODO: bellov

During dogfooding we have identified few issues with current solution. All off below has to be somehow addressed for MSBuild V1 to be turned on by default:
- [ ] Not logging some properties -  https://github.com/dotnet/msbuild/issues/6609
- [ ] Static graph restore can cause subsequent builds to fail - https://github.com/dotnet/msbuild/issues/6602
- [ ] Dogfooding in Arcade was failing on linux builds - installer repo on branch `origin/updateStage0` sha `a6e9cdf432fc3f403886dea7fa80b1ea7471eba3` was failing with `./build.sh /v:detailed` on linux with error `The project file could not be loaded. Data at the root level is invalid`
- [ ] Missing log messages - when extension erroneously using Console.WriteLine as oppose to Logger.LogMessage - such messages will not make it out of ANY out-of-proc node

**Comment by rokonec** [comment]
There are couple of known issues:
- when building SLN by arcade in linux
- when extension using Console.WriteLine as oppose to Logger.LogMessage.

**Comment by ladipro** [comment]
Closing for now as we don't have resources to work through the issues.
