### ISSUE TITLE
ResolveAssemblyReferences: Canonicalize output paths

### ISSUE THREAD

**Issue by rainersigwald** [dotnet/msbuild#6501]
There's an internal bug caused by a RAR output that is

```
C:\Program Files (x86)\Common Files\Microsoft Shared\MSEnv\\PublicAssemblies\EnvDTE.dll
```

(note the `\\` there). That's a mostly-valid path but if compared as a string it won't be equivalent to the canonicalized version, which causes some downstream problem. RAR should consider using `FileUtilities.NormalizePath()` on its outputs (or maybe all of its input directories?).

**Comment by KirillOsenkov** [comment]
I just noticed today that if you look at the PATH set by the Developer Command Prompt, two of the paths have \\ in them (both under Visual Studio). I was too lazy to file anything but perhaps we should.

I noticed that NuGet restore restores some projects twice if a project is listed twice, once with \\. If you accidentally have a \\ in a ProjectReference, then it won't get deduplicated and NuGet will build the target twice in the same project.
