### ISSUE TITLE
Regression: Building a project in a sln file using target stopped working in 16.10

### ISSUE THREAD

**Issue by xt1** [dotnet/msbuild#6515]
### Issue Description
* have a solution file with lots of CPP vcxproj files, some in solution folders. 
* msbuild ConsoleApp2.sln /t:Folder\ClassLibrary2 
* Worked in MSBuild 16.9
* Produces target missing errors in 16.10

    error MSB4057: The target " Folder\ClassLibrary2" does not exist in the project.

### Steps to Reproduce
* MSBuildRepro.zip attached
* msbuild ConsoleApp2.sln /t:Folder\ClassLibrary2 

### Expected Behavior

Build compiles ClassLibrary2 + ClassLibrary1 without errors

### Actual Behavior

    error MSB4057: The target " Folder\ClassLibrary2" does not exist in the project.

### Versions & Configurations

16.10.0+4242f381a on windows 10 - does not work.

[MsBuildRepro.zip](https://github.com/dotnet/msbuild/files/6590956/MsBuildRepro.zip)

**Comment by joshuasmartin** [comment]
I noticed this same bug on Azure DevOps. The Pipeline was working fine until two days ago and all of a sudden we're seeing these errors. No changes. Output just shows a successful build at 1.183.0 and the failed builds at 1.187.0

**Comment by rainersigwald** [comment]
Duplicate of #6373

**Comment by rainersigwald** [comment]
The fix will be released with Visual Studio 16.10.1.

**Comment by rainersigwald** [comment]
VS 16.10.1 is now released.
