### ISSUE TITLE
Could not load file or assembly Microsoft.Build, Version=15.1.0.0 or one of its dependencies

### ISSUE THREAD

**Issue by tattan** [dotnet/msbuild#6570]
While building my project I see:

_The "ResolveComReference" task could not be instantiated from "Microsoft.Build.Tasks.Core, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a". Could not load file or assembly 'Microsoft.Build, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified._

I just updated from Version 16.11.0 Preview 1.0 to Preview 2.0, everything was working fine before. I just installed Version 16.10.2 and that allows me to build with no issues.

This seems similar in nature to #5192, but am unsure if its the same or not. 

Versions:
```
Microsoft (R) Build Engine version 16.11.0-preview-21302-05+5e37cc992 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

16.11.0.30205
```

[msbuild_versions.txt](https://github.com/dotnet/msbuild/files/6664692/msbuild_versions.txt)

running `gacutil -l | Select-String "Microsoft.Build" | Select-String "15.1.0.0"` in a developer powershell, shows nothing

**Comment by rainersigwald** [comment]
How are you building? On the command line with `msbuild.exe`, in Visual Studio, some other way?

Can you share a fusion log trace of an attempted build? You can do it with [`fuslogvw.exe`](https://docs.microsoft.com/dotnet/framework/tools/fuslogvw-exe-assembly-binding-log-viewer), though lately I've been using [Fusion](https://github.com/awaescher/Fusion) which has a nicer UI. That should hopefully have some more information about exactly what is going wrong.

**Comment by tattan** [comment]
@rainersigwald is there a way I can provide Fusion logs to you and the MS team privately?

To answer your other question, I was building from within Visual Studio when using both versions of VS.

**Comment by tattan** [comment]
I've simply been avoiding the Preview version of VS as everything seems to be working in the normal 2019 line. I'm still hitting this issue though and would like to provide information / logs directly if possible.

**Comment by rainersigwald** [comment]
If you [open a feedback ticket](https://docs.microsoft.com/visualstudio/ide/feedback-options), that system will provide a confidential-to-Microsoft upload. Please link it here so we can quickly route it.

**Comment by tattan** [comment]
@rainersigwald Done thanks, https://developercommunity.visualstudio.com/t/ResolveComReference-task-could-not-be-in/1517306

I hit a separate issue of not having all the majority of references load in some projects but there were enough projects in the solution that built and some did trigger this error.

**Comment by rainersigwald** [comment]
Unfortunately, those logs don't contain the information I was hoping for. They don't have logging for either `MSBuild.exe` or `devenv.exe` (the main Visual Studio process). Can you please try

1. Close all instances of Visual Studio.
2. run `taskkill /f /im msbuild.exe` to clean up any lingering MSBuilds (this should return something like `ERROR: The process "msbuild.exe" not found.`)
3. Start fusion logging with `Log all binds to disk`
4. Run your scenario again
5. Turn off fusion logging
6. upload the new set of logs (they should have an `MSBuild.exe` folder with many assembly load logs within it)

?

**Comment by tattan** [comment]
@rainersigwald I uploaded new logs that include msbuild.exe let me know if it's still not what you're looking for.

**Comment by rainersigwald** [comment]
@tattan Thanks, that does look more complete. Unfortunately, I don't see any _failed_ loads of `Microsoft.Build, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL`. There are three successful loads within the logs, but nothing that looks like it should produce that error. Did you see the same error during that build?

**Comment by tattan** [comment]
@rainersigwald I did see errors that looked to be the same root cause. If that's not the case my mistake. 

_The "UnregisterAssembly" task could not be instantiated from "Microsoft.Build.Tasks.Core, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a". Could not load file or assembly 'Microsoft.Build, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified._

**Comment by tattan** [comment]
I uninstalled and reinstalled VS and am now unable to install 2019 Preview so I won't be able to provide any further information for this issue sorry.

**Comment by rainersigwald** [comment]
I'm glad you were able to resolve it. Please let us know if you see it again. Since uninstall/reinstall fixed it, it must have been a missing or corrupted file within your VS installation but I don't know what would cause such a thing. Hopefully if anyone else sees it we can track it down.

Thanks for sharing your logs and things with us.
