### ISSUE TITLE
What is _WebToolingArtifacts?

### ISSUE THREAD

**Issue by Deilan** [dotnet/msbuild#6593]
Recently I have found `_WebToolingArtifacts` item in `.csproj` file, which looks like this:

```xml
<ItemGroup>
  <_WebToolingArtifacts Remove="Properties\PublishProfiles\FolderProfile.pubxml" />
</ItemGroup>
```

I tried to find any info about it on Google, but there's no info.

Can you please explain what is it, what is it used for, is there any documentation about it?

**Comment by rainersigwald** [comment]
@vijayrkn, can you help or route?
