### ISSUE TITLE
Workload resolver errors attributed to NuGet resolver

### ISSUE THREAD

**Issue by rainersigwald** [dotnet/msbuild#6594]
See https://developercommunity.visualstudio.com/t/ASPNET-Core-project-does-not-load-in-Vi/1453652

![image](https://user-images.githubusercontent.com/3347530/122592216-9f502b80-d029-11eb-9f78-20eda1409646.png)

That error message is clearly from the workload resolver, but we're attributing it to NuGet.

Looks like the first clause here is too broad:

https://github.com/dotnet/msbuild/blob/4945f056cbb8ced1410511962c5b4c34f92023f6/src/Build/BackEnd/Components/SdkResolution/SdkResolverService.cs#L120-L127

**Comment by BenVillalobos** [comment]
Note to self repro steps:

- install 2022 preview 1
- sdk 6.0.100-preview.5.21302.13
- run `dotnet tool install -g redth.net.maui.check`
- run `maui-check`
- create dummy `microsoft.net.workload.test` in `C:\Program Files\dotnet\sdk-manifests\6.0.100`
- finally, `dotnet build`
