### ISSUE TITLE
CombineTargetFrameworkInfoProperties fails on `portable` framework names

### ISSUE THREAD

**Issue by ericstj** [dotnet/msbuild#6603]
### Issue Description
When referencing a project that uses TargetFramework values containing `+` `CombineTargetFrameworkInfoProperties` fails with 

```
C:\src\dotnet\wcf\.dotnet\sdk\6.0.100-preview.4.21255.9\Microsoft.Common.CurrentVersion.targets(1809,5): error MSB4018: The "CombineTargetFrameworkInfoProperties" task failed unexpectedly.
System.Xml.XmlException: The '+' character, hexadecimal value 0x2B, cannot be included in a name.
   at System.Xml.XmlConvert.VerifyNCName(String name, ExceptionType exceptionType) in System.Private.Xml.dll:token 0x6000b7b+0x25
   at System.Xml.XmlConvert.VerifyNCName(String name) in System.Private.Xml.dll:token 0x6000b7a+0x0
   at System.Xml.Linq.XName..ctor(XNamespace ns, String localName) in System.Private.Xml.Linq.dll:token 0x600029a+0xd
   at System.Xml.Linq.XNamespace.GetName(String localName, Int32 index, Int32 count) in System.Private.Xml.Linq.dll:token 0x60002b6+0x28
   at Microsoft.Build.Tasks.CombineTargetFrameworkInfoProperties.Execute() in Microsoft.Build.Tasks.Core.dll:token 0x6000100+0x0
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute() in Microsoft.Build.dll:token 0x60015da+0x3e
   at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask) in Microsoft.Build.dll:token 0x600145a+0x2b5 [C:\src\dotnet\wcf\src\System.ServiceModel.Primitives\src\System.ServiceModel.Primitives.Facade.csproj]
```

This is a regression from 5.0.  cc @mconnew @ViktorHofer 

### Steps to Reproduce
Build attached repro. 
[repro.zip](https://github.com/dotnet/msbuild/files/6689937/repro.zip)

### Expected Behavior
Build successfully and don't throw when TargetFramework contains a `+`

### Actual Behavior
Exception is thrown

### Analysis
Regression was introduced by https://github.com/dotnet/msbuild/commit/83cd7d4e36b71d5b2cefd02cb9a5a58d27dd6a75

### Versions & Configurations
```
.NET SDK (reflecting any global.json):
 Version:   6.0.100-preview.5.21278.7
 Commit:    1961425fbd

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100-preview.5.21278.7\

Host (useful for support):
  Version: 6.0.0-preview.5.21277.4
  Commit:  d73fb996ce

.NET SDKs installed:
  5.0.202 [C:\Program Files\dotnet\sdk]
  5.0.300-preview.21258.4 [C:\Program Files\dotnet\sdk]
  6.0.100-preview.5.21278.7 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-preview.5.21277.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-preview.5.21277.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0-preview.5.21277.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

### Attach a binlog
[msbuild.zip](https://github.com/dotnet/msbuild/files/6689943/msbuild.zip)

**Comment by rainersigwald** [comment]
@dsplaisted, can you take a look at this? Looks like we have to change how the TF is represented.

**Comment by dsplaisted** [comment]
The issue is that we pass TargetFramework values back as XML with the updates to the project reference protocol, and we don't properly escape them when they contain a `+` character.

I'm not sure when I'll be able to look at fixing this though.

**Comment by chauncat** [comment]
@Forgind It looks like this was fixed but for the life of me I cannot figure out how to change my csproj file should be change to be able to support '+' in TargetFrameworks.  Can you provide an example?

**Comment by Forgind** [comment]
repro.zip has an example above.

What version of MSBuild are you using?

**Comment by chauncat** [comment]
Using MSBuild 16.11.2.50704.
We have a test pcl with following TargetFrameworks.
`<TargetFrameworks>netstandard2.0;portable-net45+win8+wp8</TargetFrameworks>`

This different come we have a Xamarin Android project references the test pcl.  That project will not compile with the same error is this bug.

**Comment by Forgind** [comment]
Ah. This made it into 17.0, if I remember correctly, so 16.11 doesn't actually have the fix. Can you try updating to 17.0 to see if you still see it?

**Comment by chauncat** [comment]
So VS2019 will never have this fix?

**Comment by Forgind** [comment]
I believe that is correct, but @dsplaisted would know for sure.

**Comment by chauncat** [comment]
That is super frustrating.  Thanks.  @dsplaisted let me know if it might show up in vs2019 since the bug appeared after I updated.

**Comment by dsplaisted** [comment]
We don't have any plans to fix this in VS 2019.

To clarify, the bug here was introduced (I believe) in the .NET 6.0 SDK.  If you're using VS 2019, I would generally recommend trying to use the version of the .NET SDK that aligns with that VS version (for example 5.0.4xx of the .NET SDK along with VS 16.11).  I believe that if you do so you will not hit this issue.
