### ISSUE TITLE
MSBuild has a grudge against $(VSToolsPath)

### ISSUE THREAD

**Issue by jimmylewis** [dotnet/msbuild#6607]
### Issue Description
Imports using `$(VSToolsPath)` are ignored by MSBuild.  The preprocess step silently comments them out instead of importing the file.

Workaround: use an equivalent value (`$(MSBuildExtensionsPath)\Microsoft\VisualStudio\v$(VisualStudioVersion)` works).

### Steps to Reproduce
```
<Project>
  <Import Project="SDK.props" Sdk="Microsoft.NET.Sdk" />
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>
  <Import Project="SDK.targets" Sdk="Microsoft.NET.Sdk" />
  <Import Project="$(VSToolsPath)\TextTemplating\Microsoft.TextTemplating.targets" />
</Project>
```

### Expected Behavior

I expect Microsoft.TextTemplating.targets to be imported.

### Actual Behavior

Output from msbuild /pp:

```...
  <!--
============================================================================================================================================
  </Import>
C:\Users\jamlew\source\repos\T4Setup\T4Setup\T4Setup.csproj
============================================================================================================================================
-->
  <!--<Import Project="$(VSToolsPath)\TextTemplating\Microsoft.TextTemplating.targets" />-->
</Project>
```

### Analysis

Per teams chat:
>[8:39 AM] Rainer Sigwald
    I have no idea what's going wrong here; please file a bug. I repro but don't know what would cause a silent ignore
​[8:40 AM] Rainer Sigwald
    changing $(VSToolsPath) to a constant makes it error, as I would expect
​[8:40 AM] Rainer Sigwald
    ah, there's a clue
​[8:40 AM] Rainer Sigwald
    we have a fallback from the early Willow days for certain folders
​[8:41 AM] Rainer Sigwald
>    
> Search paths being used for $(VSToolsPath) are ;$(MSBuildProgramFiles32)\MSBuild\Microsoft\VisualStudio\v$(VisualStudioVersion)
>
>​[8:43 AM] Rainer Sigwald
    ah, it's because there's no definition for VSToolsPath by default, but we have it in projectImportSearchPaths
​[8:43 AM] Rainer Sigwald
    we should still error, though, if the fallback doesn't work
​[8:43 AM] Rainer Sigwald
    so that's a bug

### Versions & Configurations

>C:\Program Files\Microsoft Visual Studio\2022\Preview>msbuild -version
Microsoft (R) Build Engine version 17.0.0-preview-21317-11+c579afe9c for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.
>
>17.0.0.31711

**Comment by rainersigwald** [comment]
Expounding on my IM stuff: 

https://github.com/dotnet/msbuild/blob/bbeb7013630a129f3ec84bf4a1173c25974733d0/src/MSBuild/app.config#L166

this should be firing but is not (condition wrong?):

https://github.com/dotnet/msbuild/blob/bbeb7013630a129f3ec84bf4a1173c25974733d0/src/Build/Evaluation/Evaluator.cs#L1656-L1664

**Comment by rainersigwald** [comment]
AHA! State is leaking from NuGet setting this for restore:

https://github.com/NuGet/NuGet.Client/blob/b83566ec2369c4e9fd07e6f95d734dfe370a1e66/src/NuGet.Core/NuGet.Build.Tasks.Console/MSBuildFeatureFlags.cs#L76

https://github.com/NuGet/NuGet.Client/blob/b83566ec2369c4e9fd07e6f95d734dfe370a1e66/src/NuGet.Core/NuGet.Build.Tasks.Console/MSBuildFeatureFlags.cs#L16

cc @jeffkl, @nkolev92

I think this may be new behavior related to dotnet/sdk#18263 (cc @rokonec): before, NuGet's limit of 1 worker node would have been in-proc; now it's forced out by `MSBUILDNOINPROCNODE`.

https://github.com/NuGet/NuGet.Client/blob/b83566ec2369c4e9fd07e6f95d734dfe370a1e66/src/NuGet.Core/NuGet.Build.Tasks.Console/MSBuildStaticGraphRestore.cs#L872-L874

Long term, I think we should teach NuGet to unset `MSBUILDNOINPROCNODE` or at least set `EnableNodeReuse=false`.

This suggests a workaround: set the environment variable `DOTNET_CLI_DO_NOT_USE_MSBUILDNOINPROCNODE=true`, _kill all dotnet.exe processes_, and it should work ok.
