### ISSUE TITLE
Project includes do not handle soft symlinks on linux, instead copy entire linked directory

### ISSUE THREAD

**Issue by levihb** [dotnet/msbuild#6620]
If I have something like the following in my project file:

```csproj
<None Include="fixtures\**" CopyToOutputDirectory="PreserveNewest" LinkBase="fixtures\" />
```

And then inside of fixtures I have a symlinked folder I created using `ln -s [source] [link]`. But the problem is when I build the project dotnet removes the symlink and instead just copies everything over. This doesn't work as when running in debug I need the folder to be elsewhere on the system, both because of access and because it's very large.

Is there a workaround for this?

I put linux in the title, although I have not tested it on any other operating system.

**Comment by rainersigwald** [comment]
No, it doesn't look like `Copy` has a `CopySymlinksAsSymlinks` option. That would be difficult to implement, as the inputs to `Copy` are a list of _files_, which are discovered by the `**` pattern you're specifying, so we don't even have an entry for your symlink--we just thought of it as a directory to traverse.

I think your best bet is to exclude the symlink directory from the pattern and explicitly set up the symlink using `<Exec Command="ln -s ..." />` in a custom target.
