### ISSUE TITLE
Add Solution Configuration name to variables/macros

### ISSUE THREAD

**Issue by Saibamen** [dotnet/msbuild#6623]
### Issue Description
There is no Solution Configuration name variable to be used during pre-build event.

![image](https://user-images.githubusercontent.com/905878/123325559-73a4d800-d538-11eb-9381-f0706c046703.png)

```
The command "xcopy /Y "C:\xxx\config\App.Debug.config" "C:\xxx\App.config"" exited with code 2.
```

This should copy `App.Dev.config`, not `App.Debug.config`

Related: https://stackoverflow.com/questions/68121300/get-active-solution-configuration-name-for-pre-build-event-command-line-in-visua

**Comment by rainersigwald** [comment]
Solution Configuration is not available inside a project, by design. Do you have that solution configuration set up to have a configuration of the same name for that project?

**Comment by Saibamen** [comment]
>Do you have that solution configuration set up to have a configuration of the same name for that project?

Now I have it
