### ISSUE TITLE
Build hangs on parallel dotnet publish calls

### ISSUE THREAD

**Issue by matkoch** [dotnet/msbuild#6657]
### Issue Description
Some time ago I discovered that I could improve my build time by invoking `dotnet publish` with different frameworks simultaneously. Seemingly since upgrading to .NET 5, my builds occasionally hang on the build server.

### Steps to Reproduce
Trimming my invocations to the most important parts:
```
> /usr/bin/dotnet publish /mnt/agent/work/63014a48ec1fbe46/source/Nuke.MSBuildTasks/Nuke.MSBuildTasks.csproj --configuration Release --framework net472 --no-build --verbosity Minimal --nologo 
> /usr/bin/dotnet publish /mnt/agent/work/63014a48ec1fbe46/source/Nuke.GlobalTool/Nuke.GlobalTool.csproj --configuration Release --framework netcoreapp2.1 --no-build --verbosity Minimal --nologo
> /usr/bin/dotnet publish /mnt/agent/work/63014a48ec1fbe46/source/Nuke.GlobalTool/Nuke.GlobalTool.csproj --configuration Release --framework netcoreapp3.1 --no-build --verbosity Minimal --nologo
> /usr/bin/dotnet publish /mnt/agent/work/63014a48ec1fbe46/source/Nuke.GlobalTool/Nuke.GlobalTool.csproj --configuration Release --framework net5.0 --no-build --verbosity Minimal --nologo
> /usr/bin/dotnet publish /mnt/agent/work/63014a48ec1fbe46/source/Nuke.MSBuildTasks/Nuke.MSBuildTasks.csproj --configuration Release --framework netcoreapp2.1 --no-build --verbosity Minimal --nologo
```

### Expected Behavior
Build should not hang, and at least give some kind of error output.

### Actual Behavior
Build hangs. See one of my [GitHubActions run](https://github.com/nuke-build/nuke/actions/runs/985502119) where Windows and Linux succeed, while MacOS hangs.

### Ask us questions
The parallel `dotnet publish` never made any issues before, but maybe it wasn't a good idea after all ?

**Comment by rainersigwald** [comment]
I suspect this is a known issue in SDK 5.0.3xx that should be fixed by #6538 in 5.0.400 and 6.0.100 (when they're released). You can likely work around the issue by setting the environment variable `MSBUILDDISABLENODEREUSE=1` in your Actions job.

**Comment by Forgind** [comment]
Team triage: Did you get a change to look at rainersigwald's comment?

**Comment by matkoch** [comment]
bump: seems like response is still missing

**Comment by Forgind** [comment]
#6538 was merged a couple months ago; have you tried downloading a recent preview and seeing if it resolves this problem? If not, have you tried the workaround?

**Comment by matkoch** [comment]
Can confirm it works. Thanks for your help!
