### ISSUE TITLE
Timeboxed perf investigation of always-run SDK targets

### ISSUE THREAD

**Issue by rainersigwald** [dotnet/msbuild#6660]
* https://github.com/dotnet/sdk/issues/19282
* ResolvePackageFileConflicts
  * Cache assembly info directly?
  * Share assembly info cache with RAR somehow?
  * Cache overall results?

**Comment by Forgind** [comment]
To clarify what you intended with this, I would understand it as looking at targets that always run (i.e., no inputs/outputs) to see if we can make them faster. Is that correct, or were you specifically looking at their up-to-date checks or something else?

**Comment by rainersigwald** [comment]
> looking at targets that always run (i.e., no inputs/outputs) to see if we can make them faster.

Yup.
