### ISSUE TITLE
Deploy-MSBuild.ps1 does not include 64-bit MSBuild.exe

### ISSUE THREAD

**Issue by rainersigwald** [dotnet/msbuild#6682]
I just tried to apply privates to my dev17 instance but failed because I was (secretly) using the pre-update MSBuild.exe, because dev17 now defaults to the `bin/amd64/msbuild.exe` location, which isn't updated today.

**Comment by BenVillalobos** [comment]
When working on setplatform I noticed common.tasks wasn't included and had to manually copy them over. We should add that as well (for the not uncommon case where we want to test new tasks)
