### ISSUE TITLE
Build multi target does not work with miscellaneous solution

### ISSUE THREAD

**Issue by enricobenedos** [dotnet/msbuild#6701]
### Issue Description

We have a miscellaneous solution that include WPF,WCF, Class Library and Blazor WASM project. On our CI we use MSBuild to compile all project starting from the solution.

`.\MSBuild.exe /t:Clean,Restore,Build /p:Configuration=ReleaseStandard C:\Users\supervisor\Desktop\my-app\ -v:Quiet`

The problem is that the Blazor WASM project generated an exception during build with no sense:
```
C:\Program Files\dotnet\sdk\5.0.302\Sdks\Microsoft.NET.Sdk.BlazorWebAssembly\targets\Microsoft.NET.Sdk.BlazorWebAssembly.Current.targets(234,5): error RAZORSDK1007: Unable to find BlazorWebAssembly JS files. This usually indicates a pac
kaging error. [C:\Users\supervisor\Desktop\my-app\WebGui\MySupervisorWebGui\MySupervisorWebGui.csproj]
```
**We have all the necessary frameworks and build tools installed on our build server.**

The problem can be fixed simply targeting only one operation per time, here an example of not working build with `/t:Clean,Restore,Build` and then a working one with separated targets:

```
PS C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin> .\MSBuild.exe /t:Clean,Restore,Build /p:Configuration=ReleaseStandard C:\Users\supervisor\Desktop\my-app\ -v:Quiet
Microsoft (R) Build Engine versione 16.10.2+857e5a733 per .NET Framework
Copyright (C) Microsoft Corporation. Tutti i diritti sono riservati.

C:\Users\supervisor\Desktop\my-app\Gui\MySupervisorGUI\Utility\ToolsPresetting.cs(289,30): warning CS0168: La variabile 'ex' è dichiarata, ma non viene mai usata [C:\Users\supervisor\Desktop\my-app\Gui\MySupervisorGUI\MySupervisorG
UI_z51umdjl_wpftmp.csproj]
C:\Users\supervisor\Desktop\my-app\Gui\MySupervisorGUI\Utility\ToolsPresetting.cs(289,30): warning CS0168: La variabile 'ex' è dichiarata, ma non viene mai usata [C:\Users\supervisor\Desktop\my-app\Gui\MySupervisorGUI\MySupervisorG
UI.csproj]
C:\Program Files\dotnet\sdk\5.0.302\Sdks\Microsoft.NET.Sdk.BlazorWebAssembly\targets\Microsoft.NET.Sdk.BlazorWebAssembly.Current.targets(234,5): error RAZORSDK1007: Unable to find BlazorWebAssembly JS files. This usually indicates a pac
kaging error. [C:\Users\supervisor\Desktop\my-app\WebGui\MySupervisorWebGui\MySupervisorWebGui.csproj]
PS C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin> .\MSBuild.exe /t:Clean /p:Configuration=ReleaseStandard C:\Users\supervisor\Desktop\my-app\ -v:Quiet
Microsoft (R) Build Engine versione 16.10.2+857e5a733 per .NET Framework
Copyright (C) Microsoft Corporation. Tutti i diritti sono riservati.

PS C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin> .\MSBuild.exe /t:Restore /p:Configuration=ReleaseStandard C:\Users\supervisor\Desktop\my-app\ -v:Quiet
Microsoft (R) Build Engine versione 16.10.2+857e5a733 per .NET Framework
Copyright (C) Microsoft Corporation. Tutti i diritti sono riservati.

PS C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin> .\MSBuild.exe /t:Build /p:Configuration=ReleaseStandard C:\Users\supervisor\Desktop\my-app\ -v:Quiet
Microsoft (R) Build Engine versione 16.10.2+857e5a733 per .NET Framework
Copyright (C) Microsoft Corporation. Tutti i diritti sono riservati.

C:\Users\supervisor\Desktop\my-app\Gui\MySupervisorGUI\Utility\ToolsPresetting.cs(289,30): warning CS0168: La variabile 'ex' è dichiarata, ma non viene mai usata [C:\Users\supervisor\Desktop\my-app\Gui\MySupervisorGUI\MySupervisorG
UI_z4rdfrei_wpftmp.csproj]
C:\Users\supervisor\Desktop\my-app\Gui\MySupervisorGUI\Utility\ToolsPresetting.cs(289,30): warning CS0168: La variabile 'ex' è dichiarata, ma non viene mai usata [C:\Users\supervisor\Desktop\my-app\Gui\MySupervisorGUI\MySupervisorG
UI.csproj]
```
### Expected Behavior

We expect that also multitargeting build works.

### Actual Behavior

Not working multitargeting build.

### Versions & Configurations

**MSBuild version:**
```
 .\MSBuild.exe --version
Microsoft (R) Build Engine versione 16.10.2+857e5a733 per .NET Framework
Copyright (C) Microsoft Corporation. Tutti i diritti sono riservati.

16.10.2.30804
```
**dotnet version:**
```
PS C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin> dotnet --version
5.0.302
```

**OS:** Microsoft Windows Server 2019 (build 17763.737)

**Comment by dasMulli** [comment]
Is this from a clean state or was a restore executed before? the `Restore` target is not meant to be run alongisde other targets.. use `msbuild -restore -t:Clean,Build` instead (restore will generate some msbuild xml files and projects need to be reevaluated separately. the `-restore`  argument does that). Though running this command may not solve the blazor wasm problem

**Comment by enricobenedos** [comment]
Hello @dasMulli,

your suggestion works perfectly.

Consider for both commands to start from a clean cloned repo,

**working:** `.\MSBuild.exe -restore /t:Clean,Build /p:Configuration=ReleaseStandard C:\Users\supervisor\Desktop\my-app\ -v:Quiet`

**not working:** `.\MSBuild.exe /t:Clean,Restore,Build /p:Configuration=ReleaseStandard C:\Users\supervisor\Desktop\my-app\ -v:Quiet`

> C:\Program Files\dotnet\sdk\5.0.302\Sdks\Microsoft.NET.Sdk.BlazorWebAssembly\targets\Microsoft.NET.Sdk.BlazorWebAssembly.Current.targets(234,5): error RAZORSDK1007: Unable to find BlazorWebAssembly JS files. This usually indicates a packaging error. [C:\Users\supervisor
\Desktop\my-app\WebGui\MySupervisorWebGui\MySupervisorWebGui.csproj]

Is it an expected behaviour? Is it reported on Microsoft docs?

**Comment by BenVillalobos** [comment]
> Is it an expected behaviour? Is it reported on Microsoft docs?

[It is](https://docs.microsoft.com/en-us/nuget/reference/msbuild-targets#restoring-and-building-with-one-msbuild-command). Closing out the issue, thanks @dasMulli for helping out here!
