### ISSUE TITLE
Include globs that look like \subdir** do not include files without extensions

### ISSUE THREAD

**Issue by ahmedalejo** [dotnet/msbuild#6708]
### Issue Description
A regression introduced in `Microsoft (R) Build Engine version 16.10.2+857e5a733 for .NET`.
Related to @ForNeVeR in dotnet/sdk#17976. and @ladipro in #6502

### Steps to Reproduce

Add a `.well-known\apple-app-site-association` file to the `wwwroot` folder of an aspnetcore project. Then run `dotnet publish.`

### Expected Behavior
- The `.well-known\apple-app-site-association` file should be published to the `wwwroot` folder.

### Actual Behavior
- The `.well-known\apple-app-site-association` file is not published to the `wwwroot` folder.

### Analysis
This seems to be related to files without an extension like `apple-app-site-association` rendering the `.weel-known` folder to be considered empty and therefore not published.
This worked previously with `Microsoft (R) Build Engine version 16.10.1+2fd48ab73`.

Works when the following is added
```csharp
<Content Include="wwwroot\.well-known\**" CopyToPublishDirectory="Always" />
```
but not
```csharp
<Content Include="wwwroot\.well-known\**" />
```
Note that none of the above was required in the previous version (`Microsoft (R) Build Engine version 16.10.1+2fd48ab73`)

### Versions & Configurations
on Azure DevOps agent.
- ✔`Microsoft (R) Build Engine version 16.10.1+2fd48ab73 for .NET` publish includes `wwwroot/.well-known` folder
- ❌`Microsoft (R) Build Engine version 16.10.2+857e5a733 for .NET` publish **does not** includes `wwwroot/.well-known` folder

**Comment by ladipro** [comment]
The previous behavior where the file was included in `Content` was unfortunately a bug. `Content` by default excludes everything from directories with a leading `.` (dot). Directories with such names are considered internal / hidden, take `.git` as an example.

#6531 is the fix that got us back to the correct behavior.

**Comment by BenVillalobos** [comment]
Team Triage: Closing this out since there is a fix out. Feel free to comment & reopen if, after updating, you're still seeing the issue.
