### ISSUE TITLE
Research built efficiency based on rate of MSBuild nodes vs CPU logical cores

### ISSUE THREAD

**Issue by rokonec** [dotnet/msbuild#6719]
Verify built efficiency on accessible common build machine for:
- [x] OrchardCode
- [x] MSBuild
- [x] OrchardCore on non 'hyperthreading' machine

If efficiency of current defaults is far from optimal, create another issue to investigate further and implement better default.

**Comment by rokonec** [comment]
## Conclusion
Do not invest further into this opportunity:

## Reasoning
We have hypothesis that when number of nodes equals to number of CPU logical processors system might be under-subscribed because there always be some level of blocking on IO. However that hypothesis has not been confirmed with following reasoning:
- When measured on CPU with CPU Cores < logical processors (Hyper-threading, simultaneous multi-threading) the system is naturally over-subscribed and increasing number of nodes further does not bring consistent performance gain.
- When measured on CPU with hyper-threading disabled (Orchard @4 in attached Excel) increasing nodes > CPU count only matters for rebuilds as incremental build is not as disk IO heavy => less DISK blocking.
- Gain from better CPU utilization is partially consumed by process initialization and by lesser cache-hit ratio.
- Data shows high noise. Most probably caused by 'randomness' of nodes scheduling and actual execution critical path.
- Event if it is obvious that optimal number of nodes is highly depending on project/solution, in measured scenarios the default has not been far from optimal value.
- No simple equation for optimal number of nodes have been devised yet. `nodes = logical processors * 1.5` looks like a good candidate but to verify this, extensive testing on various systems would have to be done, especially on "big iron" machines (> 64 core).
- Once Disk IO becomes perf bottleneck, increasing parallelism further do not help. Unfortunately Disk IO bandwidth differs a lot based on given Disk type (network share, SAN, rotational disk, SSD, RAM disk, ...).


I believe that given the complexity of MSBuild only way how to improve scheduling performance by optimal degree of parallelism is by introducing system metric feedback loop. Scheduler would receive main system metrics (memory usage, CPU usage, DISK usage) and dynamically control degree of parallelism to achieve optimal computer usage.

### Ryzen 5 3600, 6 Cores, 12 Logical processors, SSD
![image](https://user-images.githubusercontent.com/25249058/128362023-91faec15-04af-4b82-9e38-3895f5478985.png)

### Surface Book 2, i7-865oU, 4 Cores, hyper threading off, SSD
![image](https://user-images.githubusercontent.com/25249058/128362630-8622b528-8613-447b-8c3e-aff350faf216.png)

**Comment by rokonec** [comment]
[NodesCountPerf.xlsx](https://github.com/dotnet/msbuild/files/6939251/NodesCountPerf.xlsx)

**Comment by rokonec** [comment]
@ladipro please review

**Comment by ladipro** [comment]
Looks good, thank you for the detailed analysis. Curious, are the data points presented in the charts an average of multiple builds? If so, how many?

**Comment by ladipro** [comment]
Thank you! Feel free to close the issue.
