### ISSUE TITLE
Idea: Enhance MsBuild to use Usn Journal Records for fast up to date checks of files (ala BuildXL)?

### ISSUE THREAD

**Issue by bgianfo** [dotnet/msbuild#6727]
As folks working on MsBuild know, there was an optimization done by the [BuildXL](https://github.com/microsoft/BuildXL) team to use the journal metadata available in file systems to quickly know if the contents of a file changed or not. In the Build XL case [they were able](https://github.com/microsoft/BuildXL/blob/d1d0b430961e56a5bd006783ab8bb5c3d563bb60/Public/Src/Utilities/Storage/ChangeTracking/ChangedFileIdInfo.cs) to use the  [FSCTL_READ_USN_JOURNAL, etc ](https://docs.microsoft.com/en-us/windows/win32/api/winioctl/ni-winioctl-fsctl_read_file_usn_data) IOCTL to read [USN_RECORDs](https://docs.microsoft.com/en-us/windows/win32/api/winioctl/ns-winioctl-usn_record_v3) to achieve this.

Would it be possible to use such an optimization to enhance the MsBuild up to date check?
Just thought I would throw it out there 😄.

**Comment by rainersigwald** [comment]
Did they ever get it working without a service running with elevated permissions? That would be a blocker for us.

**Comment by bgianfo** [comment]
> Did they ever get it working without a service running with elevated permissions?

From browsing [the code](https://github.com/microsoft/BuildXL/blob/e3d1674c2f4d0b0ed9429c93f1e635d2c61f9c1d/Public/Src/Utilities/Native/IO/Windows/FileSystem.Win.cs#L1253-L1294) it appears they can use a different FSCTL depending on when the journal is "privileged" or not.
I didn't read all the code, or claim to fully understand the code I did read though, so perhaps there is more to the story. 😃 

Snippet: 

```csharp
        /// <inheritdoc />
        public unsafe ReadUsnJournalResult TryReadUsnJournal(
            SafeFileHandle volumeHandle,
            byte[] buffer,
            ulong journalId,
            Usn startUsn = default(Usn),
            bool forceJournalVersion2 = false,
            bool isJournalUnprivileged = false)
        {
            Contract.Requires(volumeHandle != null);
            Contract.Requires(buffer != null && buffer.Length > 0);
            Contract.Ensures(Contract.Result<ReadUsnJournalResult>() != null);

            var readOptions = new ReadUsnJournalData
                              {
                                  MinMajorVersion = 2,
                                  MaxMajorVersion = forceJournalVersion2 ? (ushort) 2 : (ushort) 3,
                                  StartUsn = startUsn,
                                  Timeout = 0,
                                  BytesToWaitFor = 0,
                                  ReasonMask = uint.MaxValue, // TODO: Filter this!
                                  ReturnOnlyOnClose = 0,
                                  UsnJournalID = journalId,
                              };

            int bytesReturned;
            bool ioctlSuccess;
            int error;

            fixed (byte* pRecordBuffer = buffer)
            {
                ioctlSuccess = DeviceIoControl(
                    volumeHandle,
                    ioControlCode: isJournalUnprivileged ? NativeIOConstants.FsctlReadUnprivilegedUsnJournal : NativeIOConstants.FsctlReadUsnJournal,
                    inputBuffer: (IntPtr) (&readOptions),
                    inputBufferSize: ReadUsnJournalData.Size,
                    outputBuffer: (IntPtr) pRecordBuffer,
                    outputBufferSize: buffer.Length,
                    bytesReturned: out bytesReturned,
                    overlapped: IntPtr.Zero);
                error = Marshal.GetLastWin32Error();
            }
```
