### ISSUE TITLE
SecurityUtilities chooses sha1 when signing using certificate signed with sha384

### ISSUE THREAD

**Issue by johan-e** [dotnet/msbuild#6732]
### Issue Description
When using a certificate signed with sha384 to sign a file using the ManifestUtilities.SecurityUtilities class, it will choose the sha1 algorithm, which is considered deprecated in most contexts. 

We encountered this issue when making a clickonce release package. The issue is also present when using mage.exe

As of june 1, most or all certificate authorities have started issuing certificates with a larger key size, and signed using sha384.

### Steps to Reproduce

You need:
1. A certificate signed using the sha384 algorithm installed in your personal certificate store
2. a file to be signed. in our case a clickonce manifest and application.

Use the SecurityUtilities class to sign the file, something like below:
```
using Microsoft.Build.Tasks.Deployment.ManifestUtilities;
using System;

namespace NovaSoftware.NsFrameworkTools.ClickOnceSigner
{
    class Program
    {
        static void Main(string[] args)
        {
            SecurityUtilities.SignFile("thumbprint of certificate", new Uri("Uri to timestamp server"), "path to file", "4.7.2");
        }
    }
}
```
And then run the program.

### Expected Behavior
SecurityUtilities signs the file with at least sha256

### Actual Behavior
The file is signed using sha1

### Analysis
The SecurityUtilities class only chooses sha256 if the certificate used is signed with sha256, otherwise it defaults to sha1. Our understanding of how certificates work is that the algorithm used to signed the certificate should not affect the available signing algorithms when using the certificate.

### Versions & Configurations
The issue is present in MSBuild main. We have investigated this in the v16.10 version.

**Comment by BenVillalobos** [comment]
Team Triage: The check for which sha hash to use is located here:

https://github.com/dotnet/msbuild/blob/4f8d57b40d49ab6b65f79a5963c1df26d3dcb68e/src/Tasks/ManifestUtil/SecurityUtil.cs#L610

It is reasonable to update this to, at the very least, not default to sha1.

**Comment by BenVillalobos** [comment]
> It is reasonable to update this to, at the very least, not default to sha1.

@sujitnayak does this sound reasonable?

**Comment by sujitnayak** [comment]
The current behavior is we default to SHA2 if the target framework supports it (.NE& FX > 4.5) and the certificate signature algorithm is SHA256RSA. If not, we default to SHA1.

To make the desired change to default to the signature algorithm from the cert, we need to use a signtool.exe from Windows SDK 20236 or higher as described here: https://docs.microsoft.com/en-us/dotnet/framework/tools/signtool-exe.

We should consider making this change.

**Comment by sujitnayak** [comment]
The SecurityUtilities.SignFile is also used by ClickOnce to sign it's XML manifest file. We will need to determine if the ClickOnce runtime can handle manifest files that are signed with sha384/sha512 certs across all down-level OS's we support.

**Comment by He-Man321** [comment]
I just want to add, in case it helps anyone else, this does not seem to be completely fixed, certainly not when using mage.exe; I suspect something else is causing mage to fall back to SHA1, as no matter which version I tried, it always added the signature with SHA1 (and this could be verified by opening the .application file in Notepad and checking the DigestMethod). In the end, I found dotnet-mage.exe and switched to that, and hey-presto, everything now works, and I can sign my .application files with a SHA384 certificate and timeserver, and the Windows ClickOnce installer recognises the certificate and shows a valid publisher, even after the certificate expiry date. In case it helps, the command I used is below, but it is using dotnet-mage that solved it:
dotnet-mage -Update MyApp.application -CertFile MyCert.pfx -Password PASSWORD -TimestampUri http://timestamp.comodoca.com -ProviderUrl https://MyURL.com/MyApp.application -appmanifest MyApp.exe.manifest -MinVersion 2.0 -Name MyApp -Algorithm sha256RSA
