### ISSUE TITLE
[Suggestion] `dotnet build` support piping

### ISSUE THREAD

**Issue by leonardochaia** [dotnet/msbuild#6733]
Hello all.
I've tried searching for a similar issue but could not find one.

Would it be possible for `dotnet build` to support piping for an MSBuild project instead of receiving it as an argument?

```bash
cat some.csproj | dotnet build
```

When `some.csproj` is a valid MSBuild project file, I would expect `cat some.csproj | dotnet build` to generate the same output as `dotnet build some.csproj`.

This would allow piping with other tools that generate MSBuild projects like [`SlnGen`](https://github.com/microsoft/slngen/) and [`dotnet-affected`](https://github.com/leonardochaia/dotnet-affected).

Some examples:

```bash
dotnet slngen | dotnet build
```
```bash
dotnet affected | dotnet build
```

Thank you all the work you've put into .NET

Regards,
Leo.

**Comment by BenVillalobos** [comment]
Team Triage: Since this hasn't attracted a lot of attention and has the caveats mentioned above, we don't plan to implement it at this time.
