### ISSUE TITLE
dotnet run on exec task exited with code 134

### ISSUE THREAD

**Issue by doniyorniyozov** [dotnet/msbuild#6739]
I have dotnet5 projA project which has [Exec](https://docs.microsoft.com/en-us/visualstudio/msbuild/exec-task?view=vs-2019) task which does "dotnet run ProjectB(dotnet5 project) /some arguments". But when I do dotnet build on ProjectA on WSL2 I'm getting "The command "dotnet run --project ProjectB" exited with code 134". However, it builds fine on Windows. I  only get this error when I do dotnet build ProjectA on WSL2. 

This is my exec command: 

<Exec Command="dotnet run --project ProjectB.csproj -c Debug /treatwarningaserrors /OP=$(TargetDir) /argument1=$(ProjectDir) /argument2=test />

**Comment by BenVillalobos** [comment]
Team Triage: We can't reproduce this issue, could you provide a minimal project that reproduces this behavior?

**Comment by doniyorniyozov** [comment]
@BenVillalobos I couldn't reproduce this with the test project either, I think this might be specific to my project.
