### ISSUE TITLE
msbuild process does not terminate after Xamarin.iOS build (version 16.11.0.36601)

### ISSUE THREAD

**Issue by binesh1991** [dotnet/msbuild#6748]
### Issue Description
When using Jenkins and PowerShell scripts to automatically build a Xamarin.iOS app, the msbuild process does not terminate automatically after the build is complete. This prevents us the Jenkins job from checking the exit code and moving on to the next step.

We have an exit code check like below, which had to be commented out and msbuild must be terminated via Task Manager every time the build is complete. This is affecting the automated nature of the whole build process.
`if ($LastExitCode -ne 0) { Exit $LastExitCode }`

### Steps to Reproduce
The msbuild command is executed as follows:
`msbuild $solutionFile /t:Rebuild "/p:Configuration=Ad-Hoc" "/p:Platform=iPhone" /p:ServerAddress=$macIp p:ServerUser=$macUsername /p:ServerPassword=$macPassword /nr:false /v:m /p:RestorePackages=false /p:IpaPackageDir=$deliverablesDir`

Note that we are using `/nr:false` also.

To recreate,
- Build a Xamarin.iOS project with the above command, replacing values as necessary
- Configuration "Ad-Hoc" is a custom config we have added. "Release" can be used instead.
- Replace $solutionFile with path to solution
- Replace $macIp, $macUsername and $macPassword with the values relevant to the Mac build host
- $deliverablesDir might not be necessary, but it's the IPA output path

### Expected Behavior
msbuild must exit automatically after the build has completed and return an appropriate exit code (must return 0 for success).

### Actual Behavior
msbuild does not terminate automatically. We must terminate it manually and does not return an exit code.

### Analysis
Error could be in the Xamarin.iOS targets files.

### Versions & Configurations
msbuild version 16.11.0.36601
Visual Studio 16.11

**Comment by BenVillalobos** [comment]
Team Triage: Could you provide us with a memory dump of the msbuild process when this happens? You can safely upload it as a feedback ticket. You can file feedback at [Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html) and include confidential-to-Microsoft attachments. Please link the issue here so I can expedite routing it to our team.

**Comment by binesh1991** [comment]
Hi, I have created a ticket on the [Developer Community](https://developercommunity.visualstudio.com/t/msbuild-process-does-not-terminate-after/1503232).
Thank you.

**Comment by binesh1991** [comment]
Setting the environment variable in PowerShell like `$env:MSBUILDDISABLENODEREUSE = 1;` seems to have worked, but I will need to run a few more builds to see whether it was a random incident or not. Our builds take over an hour usually so I will respond back if the solution looks consistent.

**Comment by binesh1991** [comment]
With the environment variable set, and running msbuild with the /m flag can be used as a workaround for this problem in our case. Verified by running 3 consecutive builds.

**Comment by BenVillalobos** [comment]
Closing in favor of the workaround.
