### ISSUE TITLE
IsImported seems to be false, when I expect it to be true

### ISSUE THREAD

**Issue by totollygeek** [dotnet/msbuild#6749]
Hi folks,

I am using the `Microsoft.Build.Evaluation` classes in order to parse and manipulate some `Version` strings for `PackageVersion` and for `Version` attribute of `PackageReferences`. 

When I have a `PackageVersion` property, that looks like this: 
```xml
<PackageVersion>$(MyPackageVersion)</PackageVersion>
```

and then I have `Directory.Build.props` file with the following:
```xml
<PropertyGroup>
	<MyPackageVersion>10.5.1</MyPackageVersion>
</PropertyGroup>
```
then the `PackageVersion` property has `IsImported` set to `true` and I can use the `ContainingProject` to change it in the source file (`Directory.Build.props`).

But if I have the following:
```xml
<PackageReference Include="MyFancyPackage" Version="$(MyPackageVersion)" />
```

then the `ProjectMetadata` item for `Version` has `IsImported` set to `false` and the `ContainingProject` is the `.csproj` itself, instead of the `Directory.Build.props`. Despite that, the `EvaluatedValue` is correct - `10.5.1`.

My questions are:
Is that intended behavior? If that is the case, how should I then proceed to do that change?
If this is not the behavior, then is it a bug?

**Comment by BenVillalobos** [comment]
Team Triage: Can you provide an example project that reproduces this?

It looks like what you're describing makes sense here, because `PackageReference` is defined in the project file it is not imported while `PackageVersion` is imported.

**Comment by totollygeek** [comment]
Now that I have created a [showcase project](https://github.com/totollygeek/showcase/tree/main/src/msbuild-6749.tests), I have validated that you are totally correct and I have interpreted the code wrong. The **value** of the property is coming from an imported property, not the property itself. 

My bad. I will close that issue now. Still the showcase will be there to serve as an example.
