### ISSUE TITLE
Unreliable equality comparisons in SdkResultItem

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [dotnet/msbuild#6750]
### Issue Description

Found some problems when reviewing the SdkResultItem.Equals and SdkResultItem.GetHashCode implementations from <https://github.com/dotnet/msbuild/pull/5269>. I don't know whether these methods can actually be called at all in normal use of the SDK.

### Equals can throw KeyNotFoundException

<https://github.com/dotnet/msbuild/blob/0538acc04cc2c953f220f9ec3f3764db1769defe/src/Framework/Sdk/SdkResultItem.cs#L33-L53>

If this.Metadata.Count == item.Metadata.Count, but the keys are not the same, then `item.Metadata[kvp.Key]` throws System.Collections.Generic.KeyNotFoundException.

If the method is actually used, this could be fixed by using TryGetValue.

#### PowerShell demo

```
PS C:\> Add-Type -Path "C:\Program Files\dotnet\sdk\6.0.100-preview.6.21355.2\Microsoft.Build.Framework.dll"
PS C:\> $a = [Microsoft.Build.Framework.SdkResultItem]::new()
PS C:\> $a.ItemSpec = "abc"
PS C:\> $a.Metadata.Add("Def", "42")
PS C:\> $b = [Microsoft.Build.Framework.SdkResultItem]::new()
PS C:\> $b.ItemSpec = "abc"
PS C:\> $b.Metadata.Add("Ghi", "42")
PS C:\> $a.Equals($b)
MethodInvocationException: Exception calling "Equals" with "1" argument(s): "The given key 'Def' was not present in the dictionary."
```

### GetHashCode depends on Dictionary order

<https://github.com/dotnet/msbuild/blob/0538acc04cc2c953f220f9ec3f3764db1769defe/src/Framework/Sdk/SdkResultItem.cs#L62-L66>

The resulting hash code depends on the order in which Dictionary\<string, string>.GetEnumerator() returns the key-value pairs. This order can differ even if the two metadata dictionaries contain the same keys and the same values.  Thus, GetHashCode() can return a different hash code even if Equals(object) return true.

If the method is actually used, this could be fixed by computing a hash code for each KeyValuePair individually and combining them with `^` or `+` so that the result is the same regardless of order.  Alternatively, omit the metadata from the hash code altogether; I imagine any hash tables where SdkResultItem instances are used as keys would be unlikely to have multiple instances for the same item spec.

#### PowerShell demo

I'm not sure it will happen every time.

```
PS C:\> $a = [Microsoft.Build.Framework.SdkResultItem]::new()
PS C:\> $b = [Microsoft.Build.Framework.SdkResultItem]::new()
PS C:\> $a.Metadata.Add("1", "")
PS C:\> $a.Metadata.Add("2", "")
PS C:\> $a.Metadata.Add("3", "")
PS C:\> $a.Metadata.Add("4", "")
PS C:\> $a.Metadata.Remove("2")
True
PS C:\> $a.Metadata.Remove("3")
True
PS C:\> $b.Metadata.Add("1", "")
PS C:\> $b.Metadata.Add("4", "")
PS C:\> $a.GetHashCode()
-641818147
PS C:\> $b.GetHashCode()
-641818147
PS C:\> $a.Metadata.Add("5", "")
PS C:\> $b.Metadata.Add("5", "")
PS C:\> $a.GetHashCode()
1124618266
PS C:\> $b.GetHashCode()
1418271594
PS C:\> $a.Equals($b)
True
```

### Unnecessary null checks

SdkResultItem.Metadata is a read-only property and assigned non-null in the constructor, so the null checks `Metadata?.Count` and `if (Metadata != null)` are not needed.

### Inconsistent case sensitivity for metadata keys

Described in [this comment](https://github.com/dotnet/msbuild/issues/6750#issuecomment-898233796).

**Comment by BenVillalobos** [comment]
Team Triage: Thanks for filing the issue! We've marked it as up for grabs, would you like to try fixing it?

**Comment by KalleOlaviNiemitalo** [comment]
No, I don't think I will be fixing this.

**Comment by KalleOlaviNiemitalo** [comment]
Found another problem. `kvp.Key.GetHashCode()` used by SdkResultItem.GetHashCode is case-sensitive but the `item.Metadata[kvp.Key]` lookups in SdkResultItem.Equals use `StringComparer.OrdinalIgnoreCase` because the dictionary was constructed with that.

**Comment by eriawan** [comment]
@BenVillalobos 

I think I will take this partially, on these two suggestions first: "Equals can throw KeyNotFoundException" and "Unnecessary null check" because my internal team depends on this.

After that, I will try to fix the equality comparison for granular unordered key-value

Please assign this to me.

**Comment by BenVillalobos** [comment]
@eriawan Sounds good, thanks for picking this up!

**Comment by eriawan** [comment]
@BenVillalobos 

thanks! I'm starting to work on this 🙂
