### ISSUE TITLE
Aggressively cache data on system/immutable files

### ISSUE THREAD

**Issue by ladipro** [dotnet/msbuild#6761]
### Issue Description

Files in directories that are considered "system" are treated the same way as files in regular project directories when it comes to metadata checks such as existence and time of last modification. We should take advantage of the fact that these files are not to be modified and cache their metadata.

### Sub-issues
- [x] [Investigate the impact.](https://github.com/dotnet/msbuild/issues/6822)

### Steps to Reproduce

Open a multi-project solution in VS and build it. Witness many files from the NuGet cache and the SDK directories checked repeatedly.

### Analysis

The files may be mutated on system-wide events like VS upgrade but MSBuild processes are terminated so there should be no issue keeping the data cached in memory.

### Versions & Configurations

17.0.0-preview-21377-02+38eec6f7a

### Regression?

No.

**Comment by ladipro** [comment]
@AR-May would you be interested in taking this? Maybe create a separate sub-issue to track the investigation (size <= 3). We'd like to know what percentage of [GetLastWriteFileUtcTime](https://github.com/dotnet/msbuild/blob/e923c2b80f00ec373b1f35108d4aaa45b280aa8c/src/Shared/NativeMethodsShared.cs#L1080) calls would be eliminated from an incremental build if we cached the result for SDK files and for files from the NuGet cache:
1. From first build (cache is empty).
2. From second build (cache in build nodes is populated from first build).

Let's put aside the problem of reliably detecting if a given file path falls into this bucket, i.e. feel free to hard-code it for now. Use larger solutions such as MSBuild and OrchardCore.

**Comment by drewnoakes** [comment]
For the Visual Studio fast up-to-date check, one of the biggest wins came from excluding the contents of reference assembly packs.

On my machine for example, `C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\5.0.0\ref\net5.0` contains 152 DLL files. `Microsoft.AspNetCore.App.Ref\5.0.0` adds a further 131.

We use the following class to classify files for this and other purposes. The implementation may be a useful reference.

https://github.com/dotnet/project-system/blob/6dcc31fa39ad6c922bfd73af553e37e7cdfd8b80/src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/ProjectFileClassifier.cs

**Comment by AR-May** [comment]
@ladipro Sure, I will take a look.
