### ISSUE TITLE
Fail fast when MSBuild SDK resolver throws an exception

### ISSUE THREAD

**Issue by dsplaisted** [dotnet/msbuild#6762]
Currently, it appears that if an SDK resolver throws an exception, MSBuild will print out the error, but continue to try to evaluate using other resolvers.  If an SDK import then fails, you will get a failure saying the specified SDK can't be found:

> C:\Program Files\dotnet\sdk\6.0.100-preview.7.21358.10\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.ImportWorkloads.props(14,3): warning MSB4242: The SDK resolver "Microsoft.DotNet.MSBuildWorkloadSdkResolver" failed to run. An item with the same key has already been added. Key: Microsoft.NET.Runtime.Emscripten.Node
C:\Program Files\dotnet\sdk\6.0.100-preview.7.21358.10\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.ImportWorkloads.props(14,38): error MSB4236: The SDK 'Microsoft.NET.SDK.WorkloadAutoImportPropsLocator' specified could not be found. [C:\Development\DesignerTestHarness\WindowsFormsApp472\NetFx472.csproj]

This obscures the real cause of the problem, especially in Visual Studio.

Resolvers should not be throwing exceptions, so I believe we should change this so that if they do we fail fast with the exception rather than ignoring it and trying to continue.

@BenVillalobos Can you try to fix this for Preview 4?

Related: https://github.com/dotnet/sdk/issues/17461

**Comment by mhutch** [comment]
Maybe something like this?

`error MSBxxxx: The SDK resolver "{resolver}" failed while attempting to resolve the SDK "{sdk_id)": {resolver_message}`
