### ISSUE TITLE
MSBuild_Logs directories created in source tree under normal operations

### ISSUE THREAD

**Issue by ManickaP** [dotnet/msbuild#6772]
Recently when building specific test project (e.g. System.Net.Http.FunctionalTests) in https://github.com/dotnet/runtime, non-ignored MSBuild directories appear in my repository:
```
Common/tests/TestUtilities/MSBuild_Logs/
System.Net.Http/tests/FunctionalTests/MSBuild_Logs/
```

They contain files like:
```
MSBuild_pid-198959_a4f6509bcc1f4974a892834d2fe157c3.failure.txt
```

And the file content is:
```
UNHANDLED EXCEPTIONS FROM PROCESS 198959:
=====================
8/17/2021 8:40:20 PM
System.IO.IOException: Pipe is broken.
   at System.IO.Pipes.NamedPipeServerStream.CheckConnectOperationsServer()
   at System.IO.Pipes.NamedPipeServerStream.WaitForConnectionAsync(CancellationToken cancellationToken)
   at System.IO.Pipes.NamedPipeServerStream.WaitForConnectionAsync()
   at Microsoft.Build.BackEnd.NodeEndpointOutOfProcBase.PacketPumpProc()
===================
```

I do not have set any msbuild env vars in my environment, including `MSBUILDDEBUGENGINE`.

Might be related to #6639

OS: Linux x64

**Comment by ViktorHofer** [comment]
Happening for me as well locally.

**Comment by cdmihai** [comment]
@ViktorHofer, can you please describe your repro, and what OS it's on?

**Comment by ViktorHofer** [comment]
It happens randomly when building projects in dotnet/runtime with the dotnet.cmd wrapper script (which uses the RC1 repo local SDK instead of a globally installed one) on Windows.

Unfortunately don't have any more specific repro steps.

**Comment by rainersigwald** [comment]
My guess is these (benign?) crashes were happening all along, but the location changed. I think the location changing is bad and should be reverted (for the case where the user didn't opt into the `MSBUILDDEBUGENGINE` world).

**Comment by ViktorHofer** [comment]
That these crashes happened all along is my guess as well...
