### ISSUE TITLE
BinaryLogger doesn't embed file contents for symbolic links

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/msbuild#6773]
If a file is a file system link pointing to another file, FileInfo.Length will be 0 and the file text won't be included.

We should think about a way of detecting links, following them, and grabbing the content from the target file (maybe also add some metadata about the link's source and destination).

**Comment by KirillOsenkov** [comment]
This is the `FileInfo.Length` check I was talking about:
https://github.com/dotnet/msbuild/blob/c88325c7859bcd282ff1fae14ed95936e051e1c3/src/Build/Logging/BinaryLogger/ProjectImportsCollector.cs#L132

Need to do some research how to do this robustly in a cross-plat way so it works on Windows, Mac and Linux.

**Comment by JanKrivanek** [comment]
Review the current implementation - can we simplify (and get rid of the majority of P/Invokes in the implementation)?
