### ISSUE TITLE
ProjectRootElement.Open throws due to missing 

### ISSUE THREAD

**Issue by erdembayar** [dotnet/msbuild#6799]
### Issue Description
When [try to open](https://github.com/NuGet/NuGet.Client/blob/dbedfa17a76b132c231deb3d8c684bf129932941/src/NuGet.Core/NuGet.CommandLine.XPlat/Utility/MSBuildAPIUtility.cs#L627) csproj project file with ProjectRootElement.Open from namespace Microsoft.Build.Construction then it throws following exception. I couldn't find `4.0.4.1` version anywhere, and my attempt to solve with bindingRedirect didn't work, it's blocking my work for another P1 issue.
`error: Could not load file or assembly 'System.Runtime.CompilerServices.Unsafe, Version=4.0.4.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
trace: System.AggregateException: One or more errors occurred. ---> System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime.CompilerServices.Unsafe, Version=4.0.4.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
trace:    at System.MemoryExtensions.AsSpan(String text)
trace:    at Microsoft.Build.Evaluation.Expander`2.Function`1.ExtractPropertyFunction(String expressionFunction, IElementLocation elementLocation, Object propertyValue, UsedUninitializedProperties usedUnInitializedProperties, IFileSystem fileSystem)`

### Steps to Reproduce
Currently I have project pointing private Azure repository, please contact me if you need repo project.

**Comment by BenVillalobos** [comment]
Team Triage: Are you using [MSBuildLocator](https://docs.microsoft.com/visualstudio/msbuild/updating-an-existing-application?view=vs-2019#use-microsoftbuildlocator)?

**Comment by erdembayar** [comment]
> Team Triage: Are you using [MSBuildLocator](https://docs.microsoft.com/visualstudio/msbuild/updating-an-existing-application?view=vs-2019#use-microsoftbuildlocator)?

@BenVillalobos 
I don't, I'm just using VS to debug nuget client code.

**Comment by jeffkl** [comment]
@erdembayar ping me tomorrow and I can help get this working.

**Comment by erdembayar** [comment]
@jeffkl 
Thank you. It happens to be MSBuildLocator version is old.
