### ISSUE TITLE
SDK Resolver assemblies leak AssemblyLoadContexts

### ISSUE THREAD

**Issue by rainersigwald** [dotnet/msbuild#6842]
The SDK resolver loader should cache by assembly path much like the task loader does, and evidently does not today:

_Originally posted by @marcin-krystianc in https://github.com/dotnet/msbuild/issues/5037#issuecomment-917981250_

> New ALC are created because SdkResolvers need to be loaded for each evaluated project.
> There is a cache for them called `CachingSdkResolverService` (in the `EvaluationContext`) so they are loaded only once per each instance of that cache. If it was possible to use single `EvaluationContext` for the whole lifetime of our long running service that would fix the leak from ALCs, unfortunately it is not possible as it creates other memory leaks (e.g. from the [EngineFileUtilities](https://github.com/dotnet/msbuild/blob/8f208e60995dce87ecd5f0edd313b23ef1d67bb8/src/Build/Evaluation/Context/EvaluationContext.cs#L66)).

**Comment by marcin-krystianc** [comment]
One possible fix would be to make the `CoreClrAssemblyLoader` in the `SdkResolverLoader`  to be a static field (https://github.com/dotnet/msbuild/blob/main/src/Build/BackEnd/Components/SdkResolution/SdkResolverLoader.cs#L20). Is it what you have in mind ?

**Comment by rainersigwald** [comment]
@marcin-krystianc Yes, I think that would do the trick. It looks like the other uses are in statics:

https://github.com/dotnet/msbuild/blob/f566ba17aa02768d9cce29e8caf6679a3d1537dd/src/Shared/TypeLoader.cs#L24

https://github.com/dotnet/msbuild/blob/f566ba17aa02768d9cce29e8caf6679a3d1537dd/src/Build/BackEnd/Components/ProjectCache/ProjectCacheService.cs#L216

Are you interested in sending a PR to fix this?

**Comment by marcin-krystianc** [comment]
> Are you interested in sending a PR to fix this?

Done in https://github.com/dotnet/msbuild/pull/6864

**Comment by rainersigwald** [comment]
Awesome, thank you!
