### ISSUE TITLE
RAR cracks open system files in empty incremental build

### ISSUE THREAD

**Issue by ladipro** [dotnet/msbuild#6844]
### Issue Description

The RAR on-disk cache appears to be missed for some subset of system dependencies. Even if the solution is built incrementally with no changes since the last successful build, I'm seeing a large number of calls to `AssemblyName.GetAssemblyName` for files like:

```
C:\Users\laprosek.EUROPE\.nuget\packages\microsoft.identitymodel.protocols.openidconnect\5.6.0\lib\netstandard2.0\Microsoft.IdentityModel.Protocols.OpenIdConnect.dll
C:\Users\laprosek.EUROPE\.nuget\packages\microsoft.identitymodel.tokens\5.6.0\lib\netstandard2.0\Microsoft.IdentityModel.Tokens.dll
C:\Users\laprosek.EUROPE\.nuget\packages\system.identitymodel.tokens.jwt\5.6.0\lib\netstandard2.0\System.IdentityModel.Tokens.Jwt.dll
C:\Users\laprosek.EUROPE\.nuget\packages\cachemanager.core\2.0.0-beta-1629\lib\netstandard2.0\CacheManager.Core.dll
C:\Users\laprosek.EUROPE\.nuget\packages\cachemanager.microsoft.extensions.configuration\2.0.0-beta-
C:\Users\laprosek.EUROPE\.nuget\packages\cachemanager.microsoft.extensions.logging\2.0.0-beta-1629\lib\netstandard2.0\CacheManager.Microsoft.Extensions.Logging.dll
C:\Users\laprosek.EUROPE\.nuget\packages\system.configuration.configurationmanager\4.5.0\ref\netstandard2.0\System.Configuration.ConfigurationManager.dll
...
```

### Steps to Reproduce

Clone the [Ocelot repo](https://github.com/ThreeMammals/Ocelot/) and build it. Notice that this code is executed for many assemblies, suggesting that the cache does not work well:

https://github.com/dotnet/msbuild/blob/ea1d6d99a376ac582216bba06b75f6bd9f3c7c64/src/Tasks/SystemState.cs#L449

### Data

~340 cache misses when building Ocelot, costing us ~2.5% of incremental build time.

### Analysis

Nothing obvious. The cache entry is updated with the assembly name and the cache is marked dirty so it should be written to the cache file and read back in subsequent builds.

### Versions & Configurations

Microsoft (R) Build Engine version 17.0.0-dev-21464-01+c82d55e9b for .NET Framework

### Regression?

N/A

### Attach a binlog

N/A

**Comment by rokonec** [comment]
It might be related to way RAR optimized amount of data stored in RAR on-disk-cache.
The current implementation of this https://github.com/dotnet/msbuild/blob/c8d4b38e7a913601c8e13e39b614462383afb65d/src/Tasks/SystemState.cs#L366-L379
is, IMHO, wrong (indeterministic, sub-optimal).
Maybe with recent optimization of RAR on-disk-cache size and serialization perf, we can now afford to store all project dependencies, and allow cross-project redundancy.

**Comment by Forgind** [comment]
That was actually a problem I'd mentioned in my [RAR precaching document](https://microsoft-my.sharepoint.com/:w:/p/nmytelka/EfJOiPG6XPJMsDQ12Nk5-HIBm957qVk2DPB0R5XSpRx1RA?e=6bVaU6) but never followed up on. Wish I had!
