### ISSUE TITLE
WithMetadataValue Returns All Items With Matching Identity

### ISSUE THREAD

**Issue by BenVillalobos** [dotnet/msbuild#6880]
### Issue Description
Calling @(Foo->WithMetadataValue('bar', 'baz')) should return `Foo` items that only have the value `baz` for the metadata `bar`.

But if there are multiple `Foo` items that have the same identity, every one of them is returned.

### Steps to Reproduce
Build the following project and see that there are two `Foo` items. Notice that BOTH of these items have `SomeNewMetadata`

```xml
<Project Sdk="Microsoft.Build.NoTargets/3.1.0">

    <PropertyGroup>
        <TargetFramework>net472</TargetFramework>
    </PropertyGroup>
    
    <ItemGroup>
        <TestItem Include="Foo">
            <TestMetadata>Hello</TestMetadata>
            <TestMetadata2>Hello!</TestMetadata2>
        </TestItem>
        <TestItem Include="Bar">
            <TestMetadata>NotHello</TestMetadata>
        </TestItem>
        <TestItem Include="Foo">
            <TestMetadata>Hello!</TestMetadata>
            <TestMetadata2>Hello</TestMetadata2>
        </TestItem>
    </ItemGroup>

    <ItemGroup>
        <TestItem Update="@(TestItem->WithMetadataValue('TestMetadata', 'Hello'))">
            <SomeNewMetadata>woo!</SomeNewMetadata>
        </TestItem>
    </ItemGroup>

</Project>
```

### Expected Behavior
Only the first `Foo` item is modified to include `SomeNewMetadata`

### Actual Behavior
![image](https://user-images.githubusercontent.com/4691428/134398100-aa744580-8ec3-4ad0-87a6-8ea144a6c3f8.png)
Both items have `SomeNewMetadata` despite the second `Foo` item not matching `TestMetadata` value `Hello`.

### Versions & Configurations
This happens as far back as 16.8.0+126527ff1

**Comment by Forgind** [comment]
The WithMetadataValue function is [here](https://github.com/dotnet/msbuild/blob/2f1e9cad51097aec5d7268a4afdf7ad9bc6864b9/src/Build/Evaluation/Expander.cs#L2757).

It looks like if we find an item that works, we construct a _new_ pair [here](https://github.com/dotnet/msbuild/blob/2f1e9cad51097aec5d7268a4afdf7ad9bc6864b9/src/Build/Evaluation/Expander.cs#L2784) that just happens to have the same key and value. Maybe start by yield returning `item` instead?

**Comment by BenVillalobos** [comment]
> Maybe start by yield returning item instead?

Unfortunately that doesn't solve it. It looks like a deeper issue than simply returning the right thing. WithMetadataValue properly returns the "Foo" item that's got the metadata we're looking for, but higher up in the stack it looks like it still only compares itemspec. 

By the time we hit https://github.com/dotnet/msbuild/blob/2f1e9cad51097aec5d7268a4afdf7ad9bc6864b9/src/Build/Evaluation/LazyItemEvaluator.UpdateOperation.cs#L65 `_itemsToUpdate` contains both `Foo` items.

**Comment by Forgind** [comment]
Talked with @rainersigwald, and he said this is actually as intended. A match is traditionally defined as a match _on EvaluatedInclude_, that is, not including metadata. If you want behavior similar to what you expected, he proposed batching with %(Foo.Metadata) == 'value' in a target.
