### ISSUE TITLE
MSBuild doesn't execute .targets file from NuGet package

### ISSUE THREAD

**Issue by melanchall** [dotnet/msbuild#6885]
### Issue Description
Original problem: https://developercommunity.visualstudio.com/t/vsbuildmsbuild-task-doesnt-add-targets-file-from-n/1461398.

I'm trying to build .NET Framework solution within Azure Pipeline. Solution has reference on some NuGet package containing .targets file and binary files in _build_ folder inside the package. The problem is .targets file doesn't get executed and thus binary files are not copied to output directory.

The problem occurs on MS hosted agents only running Azure Pipelines. Locally everything fine with the same MSBuild version.

### Steps to Reproduce
I have the pipeline to demonstrate the problem: https://dev.azure.com/Melanchall/DryWetMIDI/_build/results?buildId=18632&view=logs&s=96ac2280-8cb4-5df5-99de-dd2da759617d.

As you can see logs from **Build test program** step:

```
MSBuild auto-detection: using msbuild version '4.0' from 'C:\Windows\Microsoft.NET\Framework\v4.0.30319'.
All packages listed in packages.config are already installed.
"C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\amd64\msbuild.exe" "D:\a\1\s\Solution\DwmNetFrameworkConsoleApp.sln" /nologo /nr:false /dl:CentralLogger,"D:\a\_tasks\VSBuild_71a9a2d3-a98a-4caa-96ab-affca411ecda\1.192.3\ps_modules\MSBuildHelpers\Microsoft.TeamFoundation.DistributedTask.MSBuild.Logger.dll";"RootDetailId=43d01d4c-415c-4a10-85ba-1c68491ba4f7|SolutionDir=D:\a\1\s\Solution"*ForwardingLogger,"D:\a\_tasks\VSBuild_71a9a2d3-a98a-4caa-96ab-affca411ecda\1.192.3\ps_modules\MSBuildHelpers\Microsoft.TeamFoundation.DistributedTask.MSBuild.Logger.dll" -bl:D:\a\1\msbuild.binlog /p:platform="Any CPU" /p:configuration="Release" /p:VisualStudioVersion="16.0" /p:_MSDeployUserAgent="VSTS_da86e53e-02d0-42a7-ad86-d86986ae81da_build_53_0"
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\amd64\msbuild.exe /nologo -bl:D:\a\1\msbuild.binlog /dl:CentralLogger,D:\a\_tasks\VSBuild_71a9a2d3-a98a-4caa-96ab-affca411ecda\1.192.3\ps_modules\MSBuildHelpers\Microsoft.TeamFoundation.DistributedTask.MSBuild.Logger.dll;RootDetailId=43d01d4c-415c-4a10-85ba-1c68491ba4f7|SolutionDir=D:\a\1\s\Solution*ForwardingLogger,D:\a\_tasks\VSBuild_71a9a2d3-a98a-4caa-96ab-affca411ecda\1.192.3\ps_modules\MSBuildHelpers\Microsoft.TeamFoundation.DistributedTask.MSBuild.Logger.dll /nr:false /p:platform=Any CPU /p:configuration=Release /p:VisualStudioVersion=16.0 /p:_MSDeployUserAgent=VSTS_da86e53e-02d0-42a7-ad86-d86986ae81da_build_53_0 D:\a\1\s\Solution\DwmNetFrameworkConsoleApp.sln
```

You can find exact steps here: https://developercommunity.visualstudio.com/t/vsbuildmsbuild-task-doesnt-add-targets-file-from-n/1461398#T-N1470782-N1515049. There you can see links to solution and package artifacts. If you want them here:
* [solution](https://artprodsu6weu.artifacts.visualstudio.com/Ada86e53e-02d0-42a7-ad86-d86986ae81da/d286d31e-d5f6-443f-b126-d81074c91872/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL01lbGFuY2hhbGwvcHJvamVjdElkL2QyODZkMzFlLWQ1ZjYtNDQzZi1iMTI2LWQ4MTA3NGM5MTg3Mi9idWlsZElkLzE3ODc1L2FydGlmYWN0TmFtZS9Tb2x1dGlvbg2/content?format=zip)
* [package](https://artprodsu6weu.artifacts.visualstudio.com/Ada86e53e-02d0-42a7-ad86-d86986ae81da/d286d31e-d5f6-443f-b126-d81074c91872/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL01lbGFuY2hhbGwvcHJvamVjdElkL2QyODZkMzFlLWQ1ZjYtNDQzZi1iMTI2LWQ4MTA3NGM5MTg3Mi9idWlsZElkLzE3ODc1L2FydGlmYWN0TmFtZS9OdUdldFBhY2thZ2U1/content?format=zip)

As you can see the package has .tarhets file inside along with other files that should be copied to output directory by that .targets file. Please take a look at logs of last step of the pipeline:

```
    Directory: D:\a\1\s\Solution\DwmNetFrameworkConsoleApp\bin\Release


Mode                LastWriteTime         Length Name                                                                  
----                -------------         ------ ----                                                                  
-a----        9/24/2021   1:55 PM           7168 DwmNetFrameworkConsoleApp.exe                                         
-a----        9/24/2021   1:54 PM            187 DwmNetFrameworkConsoleApp.exe.config                                  
-a----        9/24/2021   1:55 PM          22016 DwmNetFrameworkConsoleApp.pdb                                         
-a----        8/25/2021   1:15 PM         642560 Melanchall.DryWetMidi.dll                                             
-a----        8/25/2021   1:15 PM        1987901 Melanchall.DryWetMidi.xml       
```

So .targets file not executed. But if I run MSBuild locally:

```
.\amd64\MSBuild.exe "DwmNetFrameworkConsoleApp\DwmNetFrameworkConsoleApp.sln" /nologo /nr:false /p:configuration="Release" /p:platform="Any CPU"  /p:VisualStudioVersion="16.0"
```

I got proper output directory content:

![image](https://user-images.githubusercontent.com/26361185/134693205-ad3e123d-0fc6-48a8-866f-c3775924b96a.png)

### Expected Behavior
.targets file inside a NuGet package is executed.

### Actual Behavior
.targets file inside a NuGet package is **not** executed.

Can you please say why MSBuild on MS-hosted agents didn't execute .targets file?

Thanks

**Comment by melanchall** [comment]
Can someone investigate the problem please?

**Comment by BenVillalobos** [comment]
MSBuild Team Triage: Looking at your project, it doesn't reference the .targets file in your nupkg. This is usually done automatically when installing the package via VS or nuget. 

You'll need something like this in your project:
```xml
  <Import Project="..\packages\Melanchall.DryWetMidi.6.0.0\build\Melanchall.DryWetMidi.targets" Condition="Exists('..\packages\Melanchall.DryWetMidi.6.0.0\build\Melanchall.DryWetMidi.targets')" />
  <Target Name="EnsureNuGetPackageBuildImports" BeforeTargets="PrepareForBuild">
    <PropertyGroup>
      <ErrorText>This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is {0}.</ErrorText>
    </PropertyGroup>
    <Error Condition="!Exists('..\packages\Melanchall.DryWetMidi.6.0.0\build\Melanchall.DryWetMidi.targets')" Text="$([System.String]::Format('$(ErrorText)', '..\packages\Melanchall.DryWetMidi.6.0.0\build\Melanchall.DryWetMidi.targets'))" />
  </Target>
```

**Comment by melanchall** [comment]
@BenVillalobos Thanks!

I've searched on the web after your answer and found that it's possible to specify .targets file as proeprty for MSBuild command:

```
msbuild.exe /p:CustomBeforeMicrosoftCSharpTargets=c:\mytargets\custom.targets
```

So it's possible to specify .targets file from a NuGet package and all works.
