### ISSUE TITLE
Getting 'Duplicate 'System.ReflectionAssembly...Attribute' attribute' build error when leveraging BaseIntermediateOutputPath and MSBuildProjectExtensionsPath

### ISSUE THREAD

**Issue by wouterroos** [dotnet/msbuild#6899]
Hi,

I have a project that uses the following MSBuild properties defined in a root-level `Directory.Build.props` file:

```
<PropertyGroup>
    <MSBuildProjectExtensionsPath>obj\$(PlatformName)</MSBuildProjectExtensionsPath>
    <BaseIntermediateOutputPath>obj\$(PlatformName)</BaseIntermediateOutputPath>    
    <BaseOutputPath>bin\$(PlatformName)</BaseOutputPath>              
  </PropertyGroup>
```

The `PlatformName` property is set either as an argument on `msbuild.exe` or derived by the name of the Visual Studio solution containing the project (we have a solution per platform and multiple projects per solution. A project can be contained in multiple solutions). The `PlatformName` property is also used to drive certain conditional MSBuild properties, conditional project/package references, etc.

We build the first platform using: 

`msbuild MyProject.csproj /p:PlatformName=Platform1` /restore

This will result in a successful build, populating the project's `obj` folder like:
```
obj\Platform1\.. //note: Contains project.assets.json etc.
obj\Platform1\Debug\..
obj\Platform1\Debug\netcoreapp3.1\..
```

Note: We can keep (re)building the project using the same command without any issue.

After the first successful build we build the second platform after the first one using:

`msbuild MyProject.csproj /p:PlatformName=Platform2` /restore

This will result in a failed build with a bunch of errors similar to the following:

```
error CS0579: Duplicate 'System.Reflection.AssemblyDescriptionAttribute' attribute
error CS0579: Duplicate 'System.Reflection.AssemblyVersionAttribute'
error CS0579: Duplicate 'System.Reflection.AssemblyTitleAttribute'
error CS0579: Duplicate 'System.Reflection.AssemblyProductAttribute'
...
```

The project's `obj` folder structure now looks like this:

```
obj\Platform1\..
obj\Platform1\Debug\..
obj\Platform1\Debug\netcoreapp3.1\..
obj\Platform1\Debug\netstandard2.0\..
obj\Platform2\..
obj\Platform2\Debug\..
obj\Platform2\Debug\netcoreapp3.1\.. 
obj\Platform2\Debug\netstandard2.0\.. 
```

Note: If we now build the first project again it will fail with similar errors.

The folder structure looks as I would expect when reading [the documentation](https://docs.microsoft.com/en-us/visualstudio/msbuild/common-msbuild-project-properties?view=vs-2019) on `MSBuildProjectExtensionsPath` and `BaseIntermediateOutputPath` and I can't think of a reason why this scenario could not be supported. It looks like MSBuild finds both `<ProjectName>.AssemblyInfo.cs` files located in the two `obj\$(PlatformName)\$(Configuration)\$(TargetFramework)\` folders instead of just looking at the folder specified by `MSBuildProjectExtensionsPath` and/or `BaseIntermediateOutputPath`. 

Am I missing something? Is there another MSBuild property that needs to be set to get this to work?

Any help/insights would be greatly appreciated!

Regards,

Wouter

**Comment by BenVillalobos** [comment]
Team Triage: Does your project use the `Microsoft.NET.SDK`?

**Comment by wouterroos** [comment]
@BenVillalobos thanks for getting back to me so quickly. Yes the project does use the `Microsoft.NET.SDK`.

**Comment by BenVillalobos** [comment]
We think this might be an sdk issue where it's automatically excluding certain files based on the intermediateoutputpath, and because yours is customized it might miss some necessary excludes. @dsplaisted might have more info on this process, I'm only aware at a high level.

**Comment by dsplaisted** [comment]
Try adding something like this to your project Directory.Build.targets:

```xml
    <DefaultItemExcludes>$(DefaultItemExcludes);obj/**</DefaultItemExcludes>
```

**Comment by wouterroos** [comment]
@dsplaisted That seems to solve the issue, thanks! I'm curious though on why this is needed.

**Comment by dsplaisted** [comment]
@wouterroos It's needed because by default all `.cs` files in your project folder (and in subfolders) are automatically included in the compilation.  The base output and intermediate output paths (by default `bin` and `obj`) are excluded from this.  However, since the intermediate output path depends on the platform, the generated files in the intermediate output from a different platform won't be excluded by default.  For example, when building for `Platform2`, it knows to exclude the files in `obj\Platform2`, but not `obj\Platform1`.

The `DefaultItemExcludes` property lets you add additional folders that should be ignored from the default includes.
