### ISSUE TITLE
MSBuild glob expansion API

### ISSUE THREAD

**Issue by AArnott** [dotnet/msbuild#6927]
I need to be able to exactly reproduce MSBuild glob expansion outside the context of msbuild project evaluation.

The scenario is that the glob _may_ originally come from an msbuild project, and the expanded result capture after project evaluation. Later, *without* loading the project, we want to see if values cached from msbuild are still valid by scanning all the input files and re-expanding globs to see if the msbuild project's inputs are effectively the same, which would allow us to skip msbuild project load.

The process that will do the glob expansion runs a service that targets netstandard2.0, so it would be great if the msbuild glob API was in a netstandard2.0 compliant assembly (i.e. _not_ microsoft.build.dll). Besides, bringing in the whole engine for something like glob parsing/expansion feels a bit heavy IMO.

**Comment by ladipro** [comment]
Correct, #6694 is different. Adding the API is going to be fairly easy. The requirement to have it exposed from a separate netstandard2.0 compliant assembly makes it a bit more complex. We probably wouldn't want to refactor MSBuild into multiple assemblies to avoid impacting mainline scenarios. That leaves us with double-compiling the relevant code, which may be OK.

There's one more wrinkle: @AArnott, our globbing implementation has been adopting new `System.IO` API that's not available in netstandard2.0. How hard of a requirement is it to target 2.0? Would netstandard2.1 work as well?

**Comment by AArnott** [comment]
`netstandard2.0` support is a nice-to-have. `net472` *might* not be necessary either, but I would be surprised if we didn't end up needing that. So dual-targeting `net472` and `netstandard2.1` should be fine. In fact if you held my feet to the fire, at this point `net472` and `net5.0` support would probably be ok as well.

**Comment by AArnott** [comment]
The overall effort that led to this requirement has been canceled. I don't need this any more.
