### ISSUE TITLE
Question: How does one debug custom SDKs with NuGet resolver?

### ISSUE THREAD

**Issue by ivanpovazan** [dotnet/msbuild#6934]
### Description

I am creating a custom SDK which includes custom build tasks I would like to debug.

The SDK is referenced in the project file with:
`<Project Sdk="My.Sdk/1.0.0">`
and can be built properly with either `dotnet build`  `msbuild -t:Build` or `VisualStudio 2019`

For debugging the custom tasks of `My.Sdk` I have tried to pack the SDK by specifying in the project file:
`    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>`
but also 
`
	  <DebugType>embedded</DebugType>
`
to include debug symbols in the nuget package. 
After which, I published the primary and symbol packages to my local source.

In order to debug the build process, I configured the VS debugger to start `dotnet.exe` as an external executable and passed the:
- `build` and 
- project file which references the custom SDK

as parameters, hoping that the debugger would load necessary symbols and stop at the breakpoint. 
However, it fails to do so. 
It builds the project correctly, but does not enter the debug session.

### Question

1. What is the proper way of debugging custom SDKs with the NuGet resolver?
2. Is there a step in my process I am doing wrong, or am I missing something?

### Workaround

The only way I have managed to debug my custom build tasks was to insert 
`System.Diagnostics.Debugger.Launch();` in the source code of the build tasks, which did not really seem to me as a proper way to do it.

**Comment by BenVillalobos** [comment]
> What is the proper way of debugging custom SDKs

To be clear, do you mean debugging specific tasks in an SDK? Or do you mean displaying information as the targets/tasks in the SDK are running?

@dsplaisted might know more, does this issue belong in the sdk?

**Comment by dsplaisted** [comment]
There may be some process hops from the original `dotnet.exe` to the one that ends up running MSBuild.  Try setting `MSBUILDDEBUGONSTART=1` in your environment variables, then you should get a just in time debugger prompt when MSBuild starts up.

See https://github.com/dotnet/msbuild/blob/main/documentation/wiki/MSBuild-Tips-&-Tricks.md

**Comment by ivanpovazan** [comment]
@dsplaisted Thank you very much env variable did the trick!
