### ISSUE TITLE
Remove prebuilt dependency on `jnm2.ReferenceAssemblies.net35`, now handled by `Microsoft.NETFramework.ReferenceAssemblies`

### ISSUE THREAD

**Issue by dagood** [dotnet/msbuild#6935]
* For: https://github.com/dotnet/source-build/issues/2417

The `jnm2.ReferenceAssemblies.net35` `1.0.1` package is a prebuilt dependency for source-build 6.0:

https://github.com/dotnet/msbuild/blob/bbb9655b007be6d079985f3a7ec14f5d82a18f64/src/StringTools/StringTools.csproj#L32

https://github.com/dotnet/msbuild/blob/bbb9655b007be6d079985f3a7ec14f5d82a18f64/eng/Packages.props#L8

The package is deprecated: https://www.nuget.org/packages/jnm2.ReferenceAssemblies.net35/1.0.1

> ![image](https://user-images.githubusercontent.com/12819531/136856450-04e10d77-3337-464a-b801-53054c4c5c99.png)

I think it can be removed without adding anything else back in, because the SDK will automatically use the official reference package to build the net35 target framework.

Maybe this also needs to be removed to prevent downgrade (or maybe it needs an update to the new version that supports net35):

https://github.com/dotnet/msbuild/blob/bbb9655b007be6d079985f3a7ec14f5d82a18f64/eng/Packages.props#L46-L48

---

This usage doesn't show up in the prebuilt report--I suppose due to `MSBuild.SourceBuild.slnf`:

https://github.com/dotnet/msbuild/blob/bbb9655b007be6d079985f3a7ec14f5d82a18f64/src/MSBuildTaskHost/MSBuildTaskHost.csproj#L211

---

I'm trying out a targeted removal of the reference in `src/StringTools/StringTools.csproj` for source-build 6.0, but maybe something broader could be done here.

**Comment by rainersigwald** [comment]
Reopening because it was removed only for source-build scenarios.
