### ISSUE TITLE
Microsoft.Build.Exceptions.InvalidProjectFileException: 'The "WroteAtLeastOneFile" parameter is not supported by the "Copy" task

### ISSUE THREAD

**Issue by Suplanus** [dotnet/msbuild#6969]
### Issue Description
All builds via Microsoft.Build.BuildManager failing after update to Visual Studio 16.11.5.

### Steps to Reproduce
I use this code to build projects via a C# application:

```csharp

var defaultToolsVersion = "Current"; // Needed for .Net Version
var pc = new ProjectCollection();
pc.DefaultToolsVersion = defaultToolsVersion;

var parameters = new BuildParameters(pc);
parameters.OnlyLogCriticalEvents = true;
parameters.DetailedSummary = false;
parameters.DefaultToolsVersion = defaultToolsVersion;

var globalProperty = new Dictionary<string, string>();
globalProperty.Add("Configuration", configuration);
globalProperty.Add("Platform", "x64");

var buildRequest =
  new BuildRequestData(projectFile, globalProperty, defaultToolsVersion, new[] { "Build" }, null);

var result = BuildManager.DefaultBuildManager.Build(parameters, buildRequest);
```

### Expected Behavior
Project will be build.

### Actual Behavior
Project not builded and I am getting this exception:
```
Microsoft.Build.Exceptions.InvalidProjectFileException: 'The "WroteAtLeastOneFile" parameter is not supported by the "Copy" task. Verify the parameter exists on the task, and it is a gettable public instance property.  C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets'
```

### Analysis
I saw changes in [this commit](https://github.com/dotnet/msbuild/commit/02a3a62dfc5f40c1e50a094da2f4419d11754f95#diff-b9e7e69d1865669b01c7d4230138b5ab642eeda009a16bc58358289a19675f9fR211) which perhaps make the problem.

### Versions & Configurations
16.11.1.47101

**Comment by Suplanus** [comment]
I found a workaround:
Installing the old [MsBuildTools 16.10.4](https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes-v16.10) fixed the problem.

**Comment by xEsteem** [comment]
I am also seeing this issue on Visual Studio 2019 16.11.5.
I'm using the MsBuildLocator to register the visual studio instance.

**Comment by Suplanus** [comment]
I haven't time to look into it. Please keep open. I give a feedback.

**Comment by Suplanus** [comment]
Thanks for reply. I had not a lot of time. Only tested with current Xamarin release. The problem is still there. I will post the build log in the upcoming weeks.

**Comment by Suplanus** [comment]
Tested with Microsoft.Build `17.2.0` -> Problem is not there anymore.

**Comment by icnocop** [comment]
This seems to be an issue in Visual Studio 2019 v16.11.27

```C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(4693,7): error MSB4131: The "WroteAtLeastOneFile" parameter is not supported by the "Copy" task. Verify the parameter exists on the task, and it is a gettable public instance property.```

**Comment by danmoseley** [comment]
Reopening per comment above

**Comment by rainersigwald** [comment]
@icnocop are you using MSBuildLocator? Can you share a binary log of the build that fails? Can you share a `fuslogvw` trace of assembly loads during that build?

**Comment by icnocop** [comment]
Yes, I'm also using
```
    <PackageReference Include="Microsoft.Build.Locator">
      <Version>1.2.15-ge4e3fc36c9</Version>
    </PackageReference>
```
I just noticed I'm using an older version of this package and I'm not sure if using a newer version will resolve the issue.

I'll try to collect a binary log and fuslogvw trace for the build soon.

Thank you.

**Comment by icnocop** [comment]
I can't seem to reproduce with a simplified project; how can I share the binary and fuslogvw log files privately?

Thank you.

**Comment by rainersigwald** [comment]
Can you [open a VS feedback ticket](https://docs.microsoft.com/visualstudio/ide/feedback-options)? You can restrict visibility on those to Microsoft folks.

Post the link here and we can skip the triage process and claim it directly.

**Comment by icnocop** [comment]
Thank you.

I think it may have been caused by trying to use code which was built using versions of the referenced `Microsoft.Build.*` assembly files from `$(DevEnvDir)` before Visual Studio 2019 was updated.

I added binary logging to the `BuildManager`'s `Logger` `BuildParameters`, rebuilt the code, and ran the same command which was previously failing, but I was not able to reproduce the error, probably because Visual Studio 2019 had already been updated and so now the `Microsoft.Build.*` assembly references in the output directory match those in `$(DevEnvDir)`.

I have kept the code which generates a binary log file to help troubleshoot the issue if it happens again in the future.

I'm not actually sure if this is a supported scenario, and I think I should actually be referencing `Microsoft.Build.*` assemblies from NuGet packages instead, and so this issue can be closed for now.

If it does happen again, I can open a VS feedback ticket, with a binary log attached, and post a link here.

Thank you.

**Comment by rainersigwald** [comment]
> I'm not actually sure if this is a supported scenario, and I think I should actually be referencing `Microsoft.Build.*` assemblies from NuGet packages instead

That is strongly preferred, for exactly this reason. And it's required in 2022+ IIRC.

> If it does happen again, I can open a VS feedback ticket, with a binary log attached, and post a link here.

Perfect, thank you and good luck!
