### ISSUE TITLE
MSBuild.exe spuriously dies with BadImageFormatException on BuildEnvironmentHelper.get_Instance()

### ISSUE THREAD

**Issue by jzabroski** [dotnet/msbuild#6970]
### Issue Description
I periodically get MSBuild failures.  I previously reported a separate issue that was closed due to lack of reproducibility.  However, this time, the Windows Event Log dump seems more helpful than previously. See Actual Behavior below.

### Steps to Reproduce
I have no idea.  Feeling a bit like Steve Martin in THE JERK right now just opening this ticket, but it needs fixing.

### Expected Behavior
No Crashes

### Actual Behavior
MSBuild.exe crashes. Windows Event Log has the following error messages:

```
Error	10/18/2021 7:28:28 PM	Application Error	1000	(100)
Faulting application name: MSBuild.exe, version: 16.10.2.30804, time stamp: 0xe420bb9d
Faulting module name: KERNELBASE.dll, version: 10.0.14393.4350, time stamp: 0x606eb12a
Exception code: 0xe0434352
Fault offset: 0x000dc602
Faulting process id: 0x4f18
Faulting application start time: 0x01d7c477dac329c3
Faulting application path: C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin\MSBuild.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: e3f0efcd-1087-488f-a7be-497ecb67a096
Faulting package full name: 
Faulting package-relative application ID: 
```

```
Error	10/18/2021 7:28:28 PM	.NET Runtime	1026	None
Application: MSBuild.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.BadImageFormatException
   at Microsoft.Build.Shared.BuildEnvironmentHelper.get_Instance()
   at Microsoft.Build.Utilities.Traits.get_Instance()
   at Microsoft.Build.CommandLine.MSBuildApp.Execute(System.String)
   at Microsoft.Build.CommandLine.MSBuildApp.Main()
```

```
Error	10/18/2021 7:27:58 PM	Application Error	1000	(100)
Faulting application name: MSBuild.exe, version: 16.10.2.30804, time stamp: 0xe420bb9d
Faulting module name: KERNELBASE.dll, version: 10.0.14393.4350, time stamp: 0x606eb12a
Exception code: 0xe0434352
Fault offset: 0x000dc602
Faulting process id: 0x3e60
Faulting application start time: 0x01d7c477c8e27647
Faulting application path: C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin\MSBuild.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: 89447d74-5d51-4095-8f31-0aeae7ea35ae
Faulting package full name: 
Faulting package-relative application ID: 
```

```
Error	10/18/2021 7:27:58 PM	.NET Runtime	1026	None
Application: MSBuild.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.BadImageFormatException
   at Microsoft.Build.Shared.BuildEnvironmentHelper.get_Instance()
   at Microsoft.Build.Utilities.Traits.get_Instance()
   at Microsoft.Build.CommandLine.MSBuildApp.Execute(System.String)
   at Microsoft.Build.CommandLine.MSBuildApp.Main()
```

### Analysis
It might be inside BuildEnvironmentHelper.Instance property. There are 5 places inside MSBuildApp that call this helper Instance property, see https://github.com/dotnet/msbuild/blob/bbb9655b007be6d079985f3a7ec14f5d82a18f64/src/MSBuild/XMake.cs

### Versions & Configurations
MSBuild.exe, version: 16.10.2.30804

### Attach a binlog
How do I attach a binlog if most often the process that crashes is a background process created by VS Tools? https://docs.microsoft.com/en-us/visualstudio/msbuild/obtaining-build-logs-with-msbuild?view=vs-2019 is actually not at all helpful in this regard.

**Comment by jzabroski** [comment]
@Forgind I thought about your proposal a bit more, and I suspect that re-writing it that way won't solve the issue, but it may change the windows event log exception that is logged into something more actionable.  It would also make the code more readable.

That said, if it were me, I would seek to write this code in such a way that de-coupled candidate paths from side effects.  One possible solution would be to write the beginning of the method this way:

```c#
        private static BuildEnvironment Initialize()
        {
            // See https://github.com/Microsoft/msbuild/issues/1461 for specification of ordering and details.
            var env = TryFromEnvironmentVariable() ??
                           TryFromVisualStudioProcess() ??
                           TryFromMSBuildProcess() ??
                           TryFromDevConsole() ??
                           TryFromSetupApi() ??
                           TryFromAppContextBaseDirectory();

            if (env != null)
                 return env;

            // If we can't find a suitable environment, continue in the 'None' mode. If not running tests,
            // we will use the current running process for the CurrentMSBuildExePath value.  This is likely
            // wrong, but many things use the CurrentMSBuildToolsDirectory value which must be set for basic
            // functionality to work.
            //
            // If we are running tests, then the current running process may be a test runner located in the
            // NuGet packages folder.  So in that case, we use the location of the current assembly, which
            // will be in the output path of the test project, which is what we want.

            string msbuildExePath;
            if (s_runningTests())
            {
                msbuildExePath = typeof(BuildEnvironmentHelper).Assembly.Location;
            }
```

Separately, the following is a bit of duplicate code compared to other parts of code in the same file:

https://github.com/dotnet/msbuild/blob/bbb9655b007be6d079985f3a7ec14f5d82a18f64/src/Shared/BuildEnvironmentHelper.cs#L181-L183

https://github.com/dotnet/msbuild/blob/bbb9655b007be6d079985f3a7ec14f5d82a18f64/src/Shared/BuildEnvironmentHelper.cs#L295-L298

Although, I must say, it's strange that on lines 295-298, the method is saying it's searching for MSBuild.exe, but it's actually searching for *both* MSBuild.exe and MSBuild.dll.  I don't know - this code is Gone Wild.

What do you think?  CC @rainersigwald 

As you can see in #6404 I have been having this problem quite a bit, dating back to at least May 3rd, 2021.

**Comment by jzabroski** [comment]
I also think that these lines should be their own method, so that the Initialize thing can be made even clearer/simpler:

https://github.com/dotnet/msbuild/blob/bbb9655b007be6d079985f3a7ec14f5d82a18f64/src/Shared/BuildEnvironmentHelper.cs#L95-L119

```c#
        private static BuildEnvironment TryFromNoneMode()
        {
            // If we can't find a suitable environment, continue in the 'None' mode. If not running tests,
            // we will use the current running process for the CurrentMSBuildExePath value.  This is likely
            // wrong, but many things use the CurrentMSBuildToolsDirectory value which must be set for basic
            // functionality to work.
            //
            // If we are running tests, then the current running process may be a test runner located in the
            // NuGet packages folder.  So in that case, we use the location of the current assembly, which
            // will be in the output path of the test project, which is what we want.

            string msbuildExePath;
            if (s_runningTests())
            {
                msbuildExePath = typeof(BuildEnvironmentHelper).Assembly.Location;
            }
            else
            {
                msbuildExePath = s_getProcessFromRunningProcess();
            }

            return new BuildEnvironment(
                BuildEnvironmentMode.None,
                msbuildExePath,
                runningTests: s_runningTests(),
                runningInVisualStudio: false,
                visualStudioPath: null);
        }
```

which would then make your initialization code read like this:

```c#
        private static BuildEnvironment Initialize()
        {
            // See https://github.com/Microsoft/msbuild/issues/1461 for specification of ordering and details.
            return TryFromEnvironmentVariable() ??
                           TryFromVisualStudioProcess() ??
                           TryFromMSBuildProcess() ??
                           TryFromDevConsole() ??
                           TryFromSetupApi() ??
                           TryFromAppContextBaseDirectory() ??
                           TryFromNoneMode();
        }
```

**Comment by jzabroski** [comment]
Separately, I do think it's a bit weird 'running tests' is not an environment mode, and is assigned to the wonky state of None, but whatever.

**Comment by Forgind** [comment]
Those refactorings look good to me. As you said, they wouldn't resolve the problem, but they should make it a good bit easier to figure out what exactly the problem is.

This code, like most code, was written piecemeal, so I'm sure there are places where comments don't quite line up or where we do duplicate work. I'd be a little careful around duplicate work just because I seem to remember there was some "duplicate work" I found recently that we stopped doing. It promptly broke, so we started doing it again. That said, I'm always happy to not do unnecessary work.

I am wondering about the "TryFromNoneMode" name...I'm not sure what a better name would be, but it doesn't feel quite right, since you're not trying to use None mode the same way you're looking in an environment variable, MSBuild process, etc. "TryConstructInDefaultMode"?

**Comment by jzabroski** [comment]
None Mode is very much just as magical as all this other stuff.

**Comment by jzabroski** [comment]
`TryFromNoneMode` could be named `ContinueInNoneMode`, as that is what the original comments suggest:

> If we can't find a suitable environment, continue in the 'None' mode.

**Comment by Forgind** [comment]
I'm not too worried about the name. If you just use it to help with debugging, it doesn't really matter what it is; if you submit it as a PR, I'm sure someone else will have an opinion 🙂

**Comment by jzabroski** [comment]
Happened again with the latest Visual Studio. 

Windows Event Log entries were:

```
Application: MSBuild.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.BadImageFormatException
   at Microsoft.Build.Shared.BuildEnvironmentHelper.get_Instance()
   at Microsoft.Build.Utilities.Traits.get_Instance()
   at Microsoft.Build.CommandLine.MSBuildApp.Execute(System.String)
   at Microsoft.Build.CommandLine.MSBuildApp.Main()
```

```
Faulting application name: MSBuild.exe, version: 16.11.1.47101, time stamp: 0xa5031179
Faulting module name: KERNELBASE.dll, version: 10.0.14393.4350, time stamp: 0x606eb12a
Exception code: 0xe0434352
Fault offset: 0x000dc602
Faulting process id: 0x51f0
Faulting application start time: 0x01d7d0e715245d9f
Faulting application path: C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin\MSBuild.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: 7f2151a4-1fc9-43ce-9957-88c51a965c22
Faulting package full name: 
Faulting package-relative application ID: 
```

**Comment by rainersigwald** [comment]
The callstack is not very helpful here. Can you try getting a memory dump of the crash (perhaps with [`procdump.exe` as a postmortem debugger](https://docs.microsoft.com/windows-hardware/drivers/debugger/enabling-postmortem-debugging#window-sysinternals-procdump)?
