### ISSUE TITLE
Enable building net472 (FullFrameworkTFM) during source-build

### ISSUE THREAD

**Issue by dagood** [dotnet/msbuild#6979]
In source-build 5.0, there's a patch to remove the middle line here:

https://github.com/dotnet/msbuild/blob/aac64bbabfcea279aa34875563848003887e8c84/src/Directory.Build.props#L29-L31

We need to build net472 in 6.0, too, so we have this patch:

https://github.com/dotnet/installer/blob/9326af28148706e3e89ef2d61ebb6fc1adde21d9/src/SourceBuild/tarball/patches/msbuild/0003-Restore-building-all-TFMs-for-source-build.patch
(Added in https://github.com/dotnet/installer/pull/12472)

This is needed for downstream repos to target net472 in source-build so Omnisharp will work:

* https://github.com/dotnet/source-build/issues/2548
* https://github.com/dotnet/source-build/issues/2478

I looked into the history a bit and it seems that this patch wasn't included in 6.0 ArPow onboarding simply because of a timing issue, not for any larger reason:

* MSBuild 6.0 ArPow onboarding (https://github.com/dotnet/msbuild/pull/6387) was submitted 2021-04-29
* The 5.0 patch to add net472 (https://github.com/dotnet/source-build/pull/2178) was merged 2021-06-14

/cc @dotnet/source-build-internal @rainersigwald @eerhardt

**Comment by MichaelSimons** [comment]
This isssue can be closed.  Source-build now excludes all Full Fx TFMs.
