### ISSUE TITLE
Consider  whether time stamp checks can be parallelized

### ISSUE THREAD

**Issue by rokonec** [dotnet/msbuild#7011]
MSBuild do lots of up-to-date checks, by getting LastWriteUtcTime for many files and compare it.

We would like to understand if simple parallelization of related File.IO operation would improve performance not only for MSBuild but also in general.

**Comment by rokonec** [comment]
I have build dotnebenchmark for related and measured on couple different storage devices.

During measurements I found out, it is very dependent on how spread files are. I therefore measured in two main scenarios:
1. sequential files -> ``` filesSample = Directory.EnumerateFiles(ScanFolder, "*", SearchOption.AllDirectories).Took(CountOfFiles)```
1. random files-> ``` filesSample = Directory.EnumerateFiles(ScanFolder, "*", SearchOption.AllDirectories).OrderBy(fn => fn.GetHashCode).Took(CountOfFiles)```

I have measured data on various runtimes, Core 3.1, net5, net6, net 4.7.2 but all runtimes shows about same behavior, which is understandable, as my benchmark was simulating MSBuild up-to-date check implementation i.e. P-Invoke to kernel `GetFileAttributesEx`. For brevity sake I will present here only 4.7.2 runtime data.

All charts will be presented as % difference from non parallelized version  i.e. its DOP (degree of paralelism) = 1.

I have measured it at thee storage devices. 
1. SSD - Samsung 980 PRO NVMe™ M.2 SSD 1 TB
1. Western Digital WD20EZRX-00DC0B0 - 2TB 7.2K RPM 64MB Cache
1. Azure VM Cloud  - Standard_D8as_v4 - Standard SSD

**Comment by rokonec** [comment]
Storage 1: SSD - Samsung 980 PRO NVMe™ M.2 SSD 1 TB

Sequential:
![image](https://user-images.githubusercontent.com/25249058/140046689-f026ac15-a5c2-4982-bca7-1984325e2b17.png)

Random:
![image](https://user-images.githubusercontent.com/25249058/140046754-d3db4dba-cbf5-4b41-ac69-3b48a9ceca9b.png)

**Comment by rokonec** [comment]
Storage 2: Western Digital WD20EZRX-00DC0B0 - 2TB 7.2K RPM 64MB Cache

Sequential:
![image](https://user-images.githubusercontent.com/25249058/140048168-f07cf2c9-ec14-4b6f-926c-936f8c1c9af5.png)

Random:
![image](https://user-images.githubusercontent.com/25249058/140048378-5138591c-a8a6-4423-b80a-de255e3c6089.png)

**Comment by rokonec** [comment]
Storage 2: Azure Cloud - Standard_D8as_v4 - Standard SSD

Sequential:
![image](https://user-images.githubusercontent.com/25249058/140048621-5866fd91-76b2-4fa5-9709-1c8cffaccc01.png)

Random:
![image](https://user-images.githubusercontent.com/25249058/140048750-6c314e6e-691d-40e6-b036-ac3e19b2a577.png)

**Comment by rokonec** [comment]
## Conclusion

Fragmentation of file location on file system have huge correlation to measured performance difference. It seems that parallelization can HARM performance in cases when it cause file system cache invalidation.
On the other hand optimal DOP for non fragmented file locations can saves up to 70% of time. 

** Data hints that parallelization can help in use cases when we have enough confidence (50% +) that files are collocated in the file system dictionary. **

However, for MSBuild I do not recommend such optimization because after merging #6974 the time spend in up-to-date checks was measured as only about 1s from overall 125s time spend on other stuff. After looking at code we cloud optimize about half of that second by about half i.e. 250ms from 125s = 0.2%. **I do not consider worth it.**

**Comment by rokonec** [comment]
@danmoseley @ladipro @rainersigwald @drewnoakes @jaredpar  I think you might find data from this 'white paper' interesting. Feel free to ping me for details.

**Comment by drewnoakes** [comment]
Thank you for sharing this.

Given the difference between random and sequential order, I wonder if there's value in ordering the items we check even without parallelism. Perhaps these checks would be faster if we ordered items by full path before scanning the file system. That may make better use of file system caches.

**Comment by rokonec** [comment]
@drewnoakes I agree. Even if we run this non concurrently sorted files would most probably better leverage file system caches. However, in SDK based project during globing we get list by enumerating file system in order which I believe is optimal for sequential 'GetFileAttributes' calls. Sorting this would probably make it slightly worse.
