### ISSUE TITLE
The binary output of MSBuild is missing entries

### ISSUE THREAD

**Issue by FrankHeimes** [dotnet/msbuild#7032]
### Issue Description
Several instances of warning C4599 appeared in the clear text output but were not included in the binary log file of msbuild.

### Steps to Reproduce
MSBuild was started in a TFS build step using this command line:
```
"C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\msbuild.exe" "D:\TF\7\s\Main\Setups.sln" /nologo /nr:false /dl:CentralLogger,"D:\TF\_tasks\MSBuild_c6c4c611-aa2e-4a33-b606-5eaba2196824\1.120.0\ps_modules\MSBuildHelpers\Microsoft.TeamFoundation.DistributedTask.MSBuild.Logger.dll";"RootDetailId=d485c9fc-0b58-47e8-9ea7-11f7e150c618|SolutionDir=D:\TF\7\s\Main"*ForwardingLogger,"D:\TF\_tasks\MSBuild_c6c4c611-aa2e-4a33-b606-5eaba2196824\1.120.0\ps_modules\MSBuildHelpers\Microsoft.TeamFoundation.DistributedTask.MSBuild.Logger.dll" /Restore /tv:Current /clp:Verbosity=normal /m:2 "/p:PackageCertificatePassword=***" "/bl:D:\TF\7\b\Setups.21-11-09.5-Release-Any32-Build.binlog" /p:platform="Any32" /p:configuration="Release" /p:_MSDeployUserAgent="TFS_69b85aa0-3019-41b5-b93c-68f2e28b8f0a_build_325_53020"
```

The build output in the TFS build log later contained the following warnings:
```
22>ClCompile:
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30133\bin\HostX64\x86\CL.exe /c /I. /Iobj\Release32\ /IInclude /I.. /I..\.. /ID:\TF\7\s\Main\Shared\Common\Include /I"D:\TF\7\s\Main\Shared\Libs\vcpkg\scripts\buildsystems\msbuild\..\..\..\installed\x86-windows\include" /ifcSearchDir D:\TF\7\s\Main\bin\Release32 /reference MyModule=MyFile.ixx.ifc /Zi /nologo /Wall /WX- /diagnostics:column /sdl /MP8 /O2 /Oi /Oy- /D NDEBUG /D SAL_NO_ATTRIBUTE_DECLARATIONS /D PLATFORM_TOOLSET_VERSION=142 /D PLATFORM_TOOLSET=v142 /D MS_CPP_UNITTESTFRAMEWORK /D TF_BUILD /D VCTOOLSVERSION=14.29.30133 /D WIN32=1 /D _UNICODE /D UNICODE /Gm- /EHs /MD /GS /Gy /fp:precise /permissive- /Zc:wchar_t /Zc:forScope /Zc:inline /std:c++latest /experimental:module /stdIfcDir "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30133\ifc\x86" /Yu"stdafx.h" /Fp"obj\Release32\FooBar.pch" /Fo"obj\Release32\\" /Fd"obj\Release32\vc142.pdb" /external:W0 /Gd /TP /wd4005 /wd4464 /wd4467 /wd4536 /wd4574 /wd4668 /wd4710 /wd4820 /wd26090 /wd28251 /wd28252 /wd28253 /wd4464 /wd4467 /wd4536 /wd4710 /wd4820 /wd26090 /wd28251 /wd28252 /wd28253 /analyze- /FC /errorReport:queue /await /bigobj /FS Main.cpp FooBar.cpp SimulatorFactory.cpp
##[warning]MyDir\Main.cpp(1,1): Warning C4599: '/IC:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\cppwinrt': command line argument number 61 does not match precompiled header
22>D:\TF\7\s\MyDir\Main.cpp(1,1): warning C4599: '/IC:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\cppwinrt': command line argument number 61 does not match precompiled header [D:\TF\7\s\MyDir\FooBar.vcxproj]
##[warning]MyDir\FooBar.cpp(1,1): Warning C4599: '/IC:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\cppwinrt': command line argument number 61 does not match precompiled header
22>D:\TF\7\s\MyDir\FooBar.cpp(1,1): warning C4599: '/IC:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\cppwinrt': command line argument number 61 does not match precompiled header [D:\TF\7\s\MyDir\FooBar.vcxproj]
##[warning]MyDir\SimulatorFactory.cpp(1,1): Warning C4599: '/IC:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\cppwinrt': command line argument number 61 does not match precompiled header
22>D:\TF\7\s\MyDir\SimulatorFactory.cpp(1,1): warning C4599: '/IC:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\cppwinrt': command line argument number 61 does not match precompiled header [D:\TF\7\s\MyDir\FooBar.vcxproj]
```
I examined the binary log file `D:\TF\7\b\Setups.21-11-09.5-Release-Any32-Build.binlog` using MSBuild Structured Log Viewer 2.1.561.
I also saved the binlog file as XML and searched that for the warning text.

### Expected Behavior
- Three entries in the analysis of MSBuild Structured Log Viewer for Warning C4599.
- A summary that states "3 Warning(s)" and "0 Error(s)".

### Actual Behavior
- No traces of Warning C4599 in the binary log file.
- Build summary stating 0 warnings:
```
Build succeeded.
     0 Warning(s)
     0 Error(s)
```

### Versions & Configurations
Windows 10 (1809)
MSBuild version:
Microsoft (R) Build Engine version 16.11.2+f32259642 for .NET Framework,
16.11.2.50704

### Attach a binlog
The binlog file is 17MB and I cannot rule out that it contains sensitive data.

**Comment by BenVillalobos** [comment]
Team Triage: could you provide a minimal project that reproduces this?

@KirillOsenkov are you aware of this?

**Comment by KirillOsenkov** [comment]
@FrankHeimes if you’re comfortable emailing me the binlog privately to my first name dot last name at ms, I can take a look. I will treat it as confidential of course.

**Comment by KirillOsenkov** [comment]
@FrankHeimes alternatively, if you could try to narrow down the repro to a standalone solution that we could test ourselves it would help too. 

Without a repro I’m afraid I have no idea how to even approach this.

**Comment by FrankHeimes** [comment]
[KirillOsenkov](https://github.com/KirillOsenkov) Thank you for your support. Unfortunately, I'm not allowed to forward the binlog file as it contains sensitive information and I was unable to create a sample project that reliably reproduces the problem.

However, I'd like to let you now that the problem was most likely caused by the fact that the source code is located in a subfolder named `Detail`, but the include statement and project setting still read `#include "StdAfx.h"` and `<PrecompiledHeaderFile>Stdafx.h</PrecompiledHeaderFile>`, resp.
After changing those to  `#include "Detail/StdAfx.h"` and `<PrecompiledHeaderFile>Detail/Stdafx.h</PrecompiledHeaderFile>`, resp., the problem disappeared.

**Comment by KirillOsenkov** [comment]
Hmm, thanks for giving this a try. If you ever find more details that could help us, we'll be happy to take another look. Certainly would want to make sure we're not randomly dropping valuable warnings on the floor!

**Comment by Scottj1s** [comment]
See also for reliable repro:
https://github.com/dotnet/msbuild/issues/8019
