### ISSUE TITLE
Question: Mono version of MSBuild 17.0

### ISSUE THREAD

**Issue by borgdylan** [dotnet/msbuild#7034]
When will the mono fork be updated to version 17.0? We already have .NET 5.0 support working, and it would be nice to get .NET 6.0 working as well.

**Comment by baronfel** [comment]
At this point the Mono team doesn't plan on porting the 17.0 changes to their [fork of msbuild](https://github.com/mono/msbuild). Users that require the Mono can explicitly opt in to using that runtime in their SDK-style projects by setting the `UseMonoRuntime` project property to `true`. You can verify that the mono runtime is being used in this scenario by 

* running `dotnet publish -r <your desired runtime identifier> -bl`
* viewing the resulting binlog in the [msbuild structured log viewer](https://github.com/dotnet/msbuild/blob/main/documentation/wiki/Providing-Binary-Logs.md),
* looking for uses of the `Microsoft.NETCore.App.Runtime.Mono.win-x64` runtime pack.

You should see something very much like this:

![image](https://user-images.githubusercontent.com/573979/141502601-7a729fcb-67bc-448c-aa21-9b8c55034eea.png)

and so on demonstrating that the actual implementation assemblies are in fact coming from the mono build of the runtime.

This setup should allow users to stay up to date with the SDK, while also using the runtime that suits them best. Hope this helps!

**Comment by borgdylan** [comment]
My reason was that I depended on msbuild targets that did not run on the dotnet CLI version of MSBuild. It was not about running the compiled output on mono but running MSBuild itself on mono.

That has now been resolved and it does not matter anymore. Thanks anyways.
