### ISSUE TITLE
MSBuild IsOsPlatform  is not work

### ISSUE THREAD

**Issue by YongChingShieh** [dotnet/msbuild#7044]
### Issue Description
 
 The project doesn't know how to publish the profile
 

### Steps to Reproduce
Create new project
```
dotnet new console -n TestProjectX
```
Edit  csproj 
```
 <ItemGroup>
	  <PackageReference Include="IBM.Data.DB2.Core-lnx" Version="3.1.0.500" Condition="$([MSBuild]::IsOsPlatform('Linux'))" />
  
	  <PackageReference Include="IBM.Data.DB2.Core" Version="3.1.0.500" Condition="$([MSBuild]::IsOsPlatform('Windows'))" />
  
  </ItemGroup>
```
publish project
```
dotnet publish -c Release -r linux-x64
```
### Expected Behavior
the IBM.Data.DB2.Core-lnx publish to Release folder

### Actual Behavior
the IBM.Data.DB2.Core publish to Release folder

### Versions & Configurations
 `msbuild -version`
Microsoft (R) Build Engine version 17.0.0+c9eb9dd64 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

17.0.0.52104
`dotnet info`
.NET SDK (reflecting any global.json):
 Version:   6.0.100
 Commit:    9e8b04bbff

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100\

Host (useful for support):
  Version: 6.0.0
  Commit:  4822e3c3aa

.NET SDKs installed:
  5.0.301 [C:\Program Files\dotnet\sdk]
  6.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
 
config
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
 <ItemGroup>
	  <PackageReference Include="IBM.Data.DB2.Core-lnx" Version="3.1.0.500" Condition="$([MSBuild]::IsOsPlatform('Linux'))" />
  
	  <PackageReference Include="IBM.Data.DB2.Core" Version="3.1.0.500" Condition="$([MSBuild]::IsOsPlatform('Windows'))" />
  
  </ItemGroup>
</Project>

```

### Attach a binlog
Release folder
![QQ截图20211118133230](https://user-images.githubusercontent.com/24885976/142358003-2b9014dd-6571-4fb0-a470-b9ec6c83135f.png)

IBM.Data.DB2.Core-lnx  driver folder
![QQ截图20211118133322](https://user-images.githubusercontent.com/24885976/142358027-52df33ae-cddf-4b01-8f99-da44a20913a5.png)

**Comment by Forgind** [comment]
IsOSPlatform returns the platform the current app (i.e., MSBuild) is running on, not the platform it's building for. Since you're running this on a windows machine, it finds the Windows version as expected. I think there should be a property for what you're looking for, but I couldn't find it quickly.

**Comment by YongChingShieh** [comment]
> IsOSPlatform returns the platform the current app (i.e., MSBuild) is running on, not the platform it's building for. Since you're running this on a windows machine, it finds the Windows version as expected. I think there should be a property for what you're looking for, but I couldn't find it quickly.

but   MSBuild is normal, before  update 6.0

**Comment by Forgind** [comment]
What do you mean that MSBuild is normal? That IsOSPlatform returned the platform it was building for?

**Comment by YongChingShieh** [comment]
> What do you mean that MSBuild is normal? That IsOSPlatform returned the platform it was building for?

yes ,if I use visual studio 2017 + net core 5.0 ,
when  run command "dotnet publish -c Release -r linux-x64"  the IBM.Data.DB2.Core-lnx will be copy to publish folder 
when run command "dotnet publish -c Release -r win-x64" the  IBM.Data.DB2.Core will be copy to publish folder

**Comment by Forgind** [comment]
I tried doing that with the 5.0.203 SDK (which had MSBuild 16.9) and IBM.Data.DB2.Core was copied even when I specified -r linux-x64.

I also looked at the IsOsPlatform method, and it hasn't been changed in the last 5 years, so if there's a bug here, I'm fairly confident it's a runtime bug and not MSBuild.

**Comment by AraHaan** [comment]
The proper fix for what the opener is asking for is to check ``$(RuntimeIdentifier.StartsWith('linux-'))``.

**Comment by blogcraft** [comment]
> The proper fix for what the opener is asking for is to check `$(RuntimeIdentifier.StartsWith('linux-'))`.

Not good if using WSL2 and an ubuntu distro.
RuntimeIdentifier returns `"ubuntu ..."`
