### ISSUE TITLE
Use of NuGet static-graph restore introduces prebuilts in source-build

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/msbuild#7058]
This is related to the use of the `RestoreUseStaticGraphEvaluation` option which was added in https://github.com/dotnet/msbuild/pull/6905.  This option does not appear to work well with the [`MSBuild.SourceBuild.slnf`](https://github.com/dotnet/msbuild/blob/main/MSBuild.SourceBuild.slnf).  All of the projects in the main solution appear to get restored instead of only the ones in the filter.  Therefore msbuild has numerous prebuilts coming from various projects that are intended to be excluded from source-build.

[source-build msbuild binlog](https://github.com/dotnet/msbuild/files/7582838/2.xx.sourcebuild.zip)

Related to https://github.com/dotnet/source-build/issues/2626

**Comment by MichaelSimons** [comment]
cc: @rainersigwald

**Comment by rainersigwald** [comment]
@Forgind can you investigate this? Is it a bug with the solution filter itself, or with NuGet's handling?

**Comment by rainersigwald** [comment]
@MichaelSimons I'd be fine disabling that for sourcebuild scenarios while we figure it out. We're using it primarily for dogfooding/finding this kind of issue; it's not critical for perf for our repo.

**Comment by MichaelSimons** [comment]
> I'd be fine disabling that for sourcebuild scenarios while we figure it out.

Thanks, I'll get a PR created to disabled this for source-build.

**Comment by Forgind** [comment]
Just to simplify the repo a bit, these seems to be true with any graph build—you can build a slnf fine, but it really just builds the whole solution.
