### ISSUE TITLE
System.NullReferenceException from AL task in Microsoft.Build.Tasks.Core

### ISSUE THREAD

**Issue by huizhonglong** [dotnet/msbuild#7101]
### Issue Description
We're hitting this build error from some projects in VS 2022 **Int Preview** (both inside VS and from command line)
    MSB4018: The "AL" task failed unexpectedly with System.NullReferenceException

The same projects build well in VS 2022 **Current** 
### Steps to Reproduce
You can repro it by building [Platform.retail.sln ](https://dev.azure.com/devdiv/devdiv/_git/VS?path=/src/Platform/Platform.retail.sln)

or build this project e.g. [Microsoft.VisualStudio.Utilities.csproj](https://dev.azure.com/devdiv/devdiv/_git/VS?path=/src/Platform/Utilities/Impl/Microsoft.VisualStudio.Utilities.csproj)

### Analysis
It looks like some regression on MSBuild, since the same projects build well in VS 2022 **Current** (the shipped version).

Below is from the binlog
C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(3870,5): error MSB4018: The "AL" task failed unexpectedly.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Build.Tasks.AL.GenerateFullPathToTool()
   at Microsoft.Build.Utilities.ToolTask.ComputePathToTool()
   at Microsoft.Build.Utilities.ToolTask.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext() [D:\DD\VS-MSB\src\Platform\Utilities\Impl\Microsoft.VisualStudio.Utilities.csproj]

### Attach a binlog
Here's the [msbuild.binlog](https://microsoft-my.sharepoint.com/:u:/p/hlong/EVIk3mZnzppHtSFiAD9Mm0wBg9jzha3GqEJ0mZttFL85GA?e=aGNnXx)

**Comment by rainersigwald** [comment]
Likely a regression from https://github.com/dotnet/msbuild/pull/7051

**Comment by Forgind** [comment]
Yes; looks like Platform is optional:
https://github.com/dotnet/msbuild/pull/7051/files#diff-29d2091d6dfbd4f7444a2104b3ba9ddd71bd15c640b8edfdaeeb45a79def232fR309
https://docs.microsoft.com/visualstudio/msbuild/al-assembly-linker-task?view=vs-2022
