### ISSUE TITLE
CodeTaskFactory can cause later task failures by loading a redundant copy of Microsoft.Build.Framework

### ISSUE THREAD

**Issue by rainersigwald** [dotnet/msbuild#7108]
This was reported and investigated (thanks!) offline by @KevinRansom.

The F# build failed when built with 64-bit MSBuild, with a failure like this:

```
error MSB4018: The "GetPackOutputItemsTask" task failed unexpectedly. [S:\fsharp\src\fsharp\FSharp.Core\FSharp.Core.fsproj]
error MSB4018: System.ArrayTypeMismatchException: Attempted to access an element as a type incompatible with the array. [S:\fsharp\src\fsharp\FSharp.Core\FSharp.Core.fsproj]
error MSB4018:    at System.Collections.Generic.List`1.Add(T item) [S:\fsharp\src\fsharp\FSharp.Core\FSharp.Core.fsproj]
error MSB4018:    at NuGet.Build.Tasks.Pack.GetPackOutputItemsTask.Execute() [S:\fsharp\src\fsharp\FSharp.Core\FSharp.Core.fsproj]
error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute() [S:\fsharp\src\fsharp\FSharp.Core\FSharp.Core.fsproj]
error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext() [S:\fsharp\src\fsharp\FSharp.Core\FSharp.Core.fsproj]
```

Debugging revealed that multiple copies of `Microsoft.Build.Framework.dll` were loaded--one from the `MSBuild\bin` directory, and one from `MSBuild\bin\amd64`.

The former makes sense because of the codebase we specify

https://github.com/dotnet/msbuild/blob/01e6196d5df534dec8c16a1417ff04638330c790/src/MSBuild/app.amd64.config#L19-L23

But the latter did not.

After some more debugging we found that the assembly was being loaded here

https://github.com/dotnet/msbuild/blob/01e6196d5df534dec8c16a1417ff04638330c790/src/Tasks/CodeTaskFactory.cs#L680-L686

As a result of entries in a `CodeTaskFactory` task definition:

```xml
      <Reference Include="$(MSBuildToolsPath)\Microsoft.Build.Framework.dll"/>
      <Reference Include="$(MSBuildToolsPath)\Microsoft.Build.Utilities.Core.dll"/>
```

In 64-bit MSBuild, `$(MSBuildToolsPath)` resolves to the `amd64` folder, passing that copy of `Microsoft.Build.Framework.dll` to `UnsafeLoadFrom`.

We then ignore the reference because it's provided by default

https://github.com/dotnet/msbuild/blob/01e6196d5df534dec8c16a1417ff04638330c790/src/Tasks/CodeTaskFactory.cs#L689-L696

But having already loaded it, it becomes possible to get incompatible definitions of `ITaskItem`, which is what happened to the ([perfectly reasonably authored](https://github.com/NuGet/NuGet.Client/blob/e0edb52d2ee204ab1117c9a592addc705cc76471/src/NuGet.Core/NuGet.Build.Tasks.Pack/GetPackOutputItemsTask.cs#L57-L59)) NuGet task.

```c#
            var outputs = new List<ITaskItem>();
            outputs.Add(new TaskItem(Path.Combine(PackageOutputPath, nupkgFileName)));
            outputs.Add(new TaskItem(Path.Combine(NuspecOutputPath, nuspecFileName)));
```

**Comment by rainersigwald** [comment]
## Workarounds

This can be worked around by changing the `CodeTaskFactory` task definition to remove the Framework and Utilities.Core references--we provide them by default and don't require that they be specified.

**Comment by drewnoakes** [comment]
I'm in the throes of moving the .NET Project System build to VS2022. We hit this issue today, packing a VB project:

https://dev.azure.com/dnceng/public/_build/results?buildId=1492964&view=logs&j=908bce63-940e-59f8-7204-204b1f5ead0b&t=2c2fdffc-ec6b-5664-5bad-2d9431cb9fe3&l=10563

**Comment by rainersigwald** [comment]
@drewnoakes you may wish to use a 32-bit MSBuild until the fix is deployed in your environment.
