### ISSUE TITLE
Package not found after switching to PackageReference

### ISSUE THREAD

**Issue by Regenhardt** [dotnet/msbuild#7134]
### Issue Description

We have a solution with around 10 projects. One Web API, several libraries used by it, and test projects for all those.

After upgrading from net461 to net472, there were several complications with packages, so we switched from Reference to PackageReference.  
Unfortunately, this seems to interfere with msbuild somehow:

One of the libraries, let's call it "OtherTeamAdapter", uses an internal package provided by a different team, let's call it "InternalLibY", version 2.67.something.

Restore seems to have to problems finding the package, as it is not in the nuget package cache waiting to be used.  
Visual Studio and msbuild however keep on telling us the package does in fact not exist. 

Basically I changed this

    <Reference Include="InternalLibY, Version=2.67, Culture=neutral, processorArchitecture=MSIL">
      <HintPath>..\..\packages\InternalLibY.2.67\lib\net40\datenanlage_lib.dll</HintPath>
    </Reference>

to this

    <PackageReference Include="InternalLibY">
      <Version>2.67</Version>
    </PackageReference>

Before this there seemed to be a problem with the nuget restore, so I opened an issue with nuget first: https://github.com/NuGet/Home/issues/11417

There is a description of the msbuild binlog output there, and a paste of the verbose build log with changed internal names.

The package does not appear in the project's "references"-list at all.

### Steps to Reproduce

Unfortunately I have no idea what's wrong or how to reproduce it outside this very specific case.

### Expected Behavior

The package should be recognised by Visual Studio and msbuild.

### Actual Behavior

Visual Studio says "The name InternalLibY does not exist in the current context" where we try to use that namespace. The build fails because the lack of that package.

### Technical information

Visual Studio version: 16.11.7  
MsBuild: `Microsoft (R) Build Engine version 16.11.2+f32259642 for .NET Framework`

**Comment by rainersigwald** [comment]
@Regenhardt can you help me understand why you think this might be an MSBuild issue? It sounds like a NuGet configuration problem to me at first glance.

**Comment by Regenhardt** [comment]
Well by now the biggest reason is probably that the nuget team sent me here :)

But also because in the binlog from building the OtherTeamAdapter with -bl option the restore task seems to have no problems  finding the package, but then in what I think is part of the build process under `Target ResolveAssemblyReferences > Task ResolveAssemblyReferences` it says "Could not resolve this reference". 

To quote myself from the other issue:  

> Below that are several searchpaths that were considered, but none of these points to the actual package directory. There are however several searchpaths pointing to other referenced libraries that themselves reference InternalLibY. Which might make sense if the dependency was only transitive, but it's a direct reference and should therefore have been restored and resolved normally.
> 
> So it seems to restore InternalLibY but then can't find it when trying to build.

**Comment by Forgind** [comment]
In the other ticket, you said the ResolveAssemblyReference task was looking in the wrong places. What happens if you add the path to your assembly to the property $(AssemblySearchPaths)? Note that it has a default set [here](https://github.com/dotnet/msbuild/blob/a70ee3087277b8d5c908d911ffca0e5deb19ecd5/src/Tasks/Microsoft.Common.CurrentVersion.targets#L612-L638), so you'd also have to include those if you want them.

**Comment by Regenhardt** [comment]
Can I somehow tell it to take the config from NuGet? NuGet puts all packages to %USERPROFILE%\.nuget\packages, but I'm not entirely sure I can add it and it would work in the pipeline too. I will however try to find out where NuGet puts the packages on the build server.

**Comment by Forgind** [comment]
I'm not sure if this is the recommended way to do things, but another option is to set the "HintPath" metadatum for each item passed into RAR to the NuGet path. You can get that quickly by setting GeneratePathProperty=true, in which case HintPath would be something like $(PkgMy_Assembly)\net472\lib\My.Assembly.dll (might have that slightly wrong).

**Comment by rainersigwald** [comment]
> I'm not sure if this is the recommended way to do things, but another option is to set the "HintPath" metadatum for each item passed into RAR to the NuGet path.

This is definitely not the recommended way to do things; PackageReference was introduced in large part to avoid having to do this.

> Well by now the biggest reason is probably that the nuget team sent me here

I think there is some missing information but that this would be best pursued there. I'm following that issue and will chime in on MSBuild-y stuff.
