### ISSUE TITLE
Cancelation gave `MSB4166: Child node "2" exited prematurely. `

### ISSUE THREAD

**Issue by danmoseley** [dotnet/msbuild#7145]
After hitting Ctrl-C to cancel a build, MSBuild announced that a child terminated unexpectedly. This is always a bug - cancelation should not produce a message.

I went to investigate but MSBuild had not written such a file. There was a zero byte file named MSB2509 but by the timestamp I suspect it was unrelated.

```
^CAttempting to cancel the build...
MSBUILD : error MSB4166: Child node "2" exited prematurely. Shutting down. Diagnostic information may be found in files in "/tmp/" and will be named MSBuild_*.failure.txt. This location can be changed by setting the MSBUILDDEBUGPATH environment variable to a different directory.
^C^C^C/mnt/c/git/installer/.dotnet/sdk/6.0.100-preview.5.21228.9/NuGet.targets(131,5): error MSB4220: Waiting for the currently executing task "RestoreTask" to cancel.
^Z
[1]+  Stopped                 ./build.sh /p:ArcadeBuildTarball=true /p:TarballDir=~/allsrc
dan@danmoseL:/mnt/c/git/installer$ pushd /tmp
/tmp /mnt/c/git/installer
dan@danmoseL:/tmp$ find . -name "MSB*"
find: ‘./tmp4zi7cux5’: Permission denied
find: ‘./tmprq93fg3o’: Permission denied
./MSBuild2509
dan@danmoseL:/tmp$ ll MSBuild2509
srwxr-xr-x 1 dan dan 0 Dec 12 15:42 MSBuild2509=
dan@danmoseL:/tmp$ echo $MSBUILDDEBUGPATH

dan@danmoseL:

dan@danmoseL:/tmp$ date
Sun Dec 12 15:54:43 MST 2021
```

info
```
dan@danmoseL:/tmp$ dotnet --info
.NET SDK (reflecting any global.json):
 Version:   5.0.202
 Commit:    db7cc87d51

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  20.04
 OS Platform: Linux
 RID:         ubuntu.20.04-x64
 Base Path:   /usr/share/dotnet/sdk/5.0.202/

Host (useful for support):
  Version: 5.0.5
  Commit:  2f740adc14

.NET SDKs installed:
  5.0.202 [/usr/share/dotnet/sdk]
```

As it is this but isn't actionable, but just an FYI that it's producing this message when it shouldn't and also not writing a file.

**Comment by danmoseley** [comment]
I don't know why it didn't write a file, but it could simply have been a SEGFAULT. Before emitting this message, the code attempts to look for an exception file. If it fails, it should not tell the user there may be an exceptoin file. Probably it should have a special message for when there is no such file:

https://github.com/dotnet/msbuild/blob/96a618ca59610908eddc92bfd0198746c34f0ed5/src/Build/BackEnd/BuildManager/BuildManager.cs#L2483-L2492

Of course that wouldn't have helped me diagnose this.

**Comment by Forgind** [comment]
I currently think this is a Nuget problem. The RestoreTask tries to account for a cancellation token, but in its catch for it, it checks for a TaskCanceledException instead of an OperationCanceledException.

**Comment by danmoseley** [comment]
@Forgind impressive -- how did you figure that out without any callstack?

**Comment by danmoseley** [comment]
Oh, I see it at least says what task was running. Still - nice.

**Comment by danmoseley** [comment]
https://github.com/NuGet/NuGet.Client/blob/f24bad0668193ce21a1db8cabd1ce95ba509c7f0/src/NuGet.Core/NuGet.Build.Tasks/RestoreTask.cs#L102
should catch OperationCanceledException, not TaskCanceledException, as cancelationToken.ThrowIfCancelRequested() throws the former, not the latter.

Moving to nuget for this one liner fix.
