### ISSUE TITLE
MSB4057: The target "BuildOnlySettings" does not exist in the project.

### ISSUE THREAD

**Issue by ashishmg-gds** [dotnet/msbuild#7167]
### Issue Description

* I went ahead and created Database project for my synapse DB in Azure Data Studio using SQL Database Projects Extension. Hooked this repo to Github actions and used below msbuild github action to build the same. Im receiving following error on build :

`C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VisualStudio\v16.0\SSDT\Microsoft.Data.Tools.Schema.SqlTasks.targets(1205,24): error MSB4057: The target "BuildOnlySettings" does not exist in the project.`

### Steps to Reproduce

* Create Database project in Azure Data Studio using SQL Database Projects extension
* use github action as below : 
`- id: dotnet-build
      name: Build Database project
      shell: bash
      run: |
          msbuild.exe ${{ inputs.solution }} -p:OutDir=${{ inputs.outputpath }} -p:Configuration=${{ inputs.configuration }}`

Example Project structure :
https://github.com/santiagxf/synapse-cicd

**Comment by Nirmal4G** [comment]
Does the same error occur locally?

**Comment by Forgind** [comment]
It looks like you already got a response:
https://github.com/santiagxf/synapse-cicd/issues/3#issuecomment-999783350

Did that answer your question, or did it not help?
