### ISSUE TITLE
MsBuild refuses to compile our custom projects (with custom language) in parallel

### ISSUE THREAD

**Issue by RobertvanderHulst** [dotnet/msbuild#7170]
We have our own custom .Net language (X#). We have created MsBuild support for that, based on what the C# build system does.
We have included the `<BuildInParallel Condition="'$(BuildInParallel)' == ''">true</BuildInParallel>  `
in our default properties file but this does not seem to work.
Building 2 independent projects in VS happens sequential. 2 independent C# assemblies are build in parallel.

Is MsBuild checking for something else as well ?

Our build task can be found here:
https://github.com/X-Sharp/XSharpDev/tree/main/XSharp/src/Compiler/XSharpBuildTask

**Comment by Forgind** [comment]
Does MSBuild build your projects in parallel from the command line? I'm wondering if, within VS, some internal code reevaluates whether two projects can be built in parallel.

I don't know the answer to your question, but if it doesn't build them in parallel, you can try building them in parallel from the command line with an attached debugger. It looks like MSBuild only cares about BuildInParallel via the MSBuild task, so you can break in there and see if it decides at some point that it can't use BuildInParallel or if it's just failing for some reason.
