### ISSUE TITLE
CA1050: Declare types in namespaces

### ISSUE THREAD

**Issue by elachlan** [dotnet/msbuild#7195]
Issue is with TestAssemblyInfo.cs. The file doesn't have a namespace. It gets included in each of the Microsoft.Build unit test projects. Does this mean a namespace is incorrect? 
https://github.com/dotnet/msbuild/blob/b827bf58c21f7a38770d786848c76f771d995a94/src/Shared/UnitTests/TestAssemblyInfo.cs#L1-L148

**Comment by Forgind** [comment]
Team triage: Probably can just add a namespace like Microsoft.Build.UnitTests. Hopefully nothing breaks.
