### ISSUE TITLE
ItemDictionary<T>.Enumerator has an unnecessary finalizer

### ISSUE THREAD

**Issue by sharwell** [dotnet/msbuild#7208]
This finalizer increases the cost of the object, but does not provide any value:

https://github.com/dotnet/msbuild/blob/b827bf58c21f7a38770d786848c76f771d995a94/src/Build/Collections/ItemDictionary.cs#L408-L414

Both the finalizer and the `Dispose(bool)` method should be eliminated from this type.

**Comment by elachlan** [comment]
Is IDisposable needed on the Enumerator type?

**Comment by sharwell** [comment]
`IEnumerator<T>` implements `IDisposable`, so it's likely to implement both interfaces even if you only explicitly list one.

* The finalizer is not needed because the type does not directly own any unmanaged resources, and including it adds an undesirable performance hit
* The `Dispose(bool)` method is not needed because the type is sealed, and including it adds unnecessary complexity
