### ISSUE TITLE
MSB1008: Only one project can be specified when Directory.Build.rsp contains undefined environment variable

### ISSUE THREAD

**Issue by CarlHeinrichs** [dotnet/msbuild#7210]
### Issue Description

I ran into an issue where MSBuild generates a misleading error message. I was trying to run MSBuild in a repo with a custom build environment which requires environment variables to be set (CoreXT). Since CoreXT was not needed for this particular project, I was trying to run MSBuild without initializing CoreXT. I am wondering if the experience here can be improved.

### Steps to Reproduce
1. Commit a Directory.Build.rsp file with an environment variable (Example)

# Add command-line for Microsoft.Build.Telemetry logger.
%MSBUILDTELCMD%

2. Run msbuild without that environment variable defined.

Example command line generated by the MSBuild ADO task.

"c:\.vs\msbuild\17.0\MSBuild\Current\Bin\amd64\MSBuild.exe" "C:\__w\1\s\EngSys-Pipelines\templates\msbuild\CodeSign\CodeSignUntrustedFiles.proj" /nologo /nr:false /t:"Clean" /dl:CentralLogger,"C:\__w\_tasks\MSBuild_c6c4c611-aa2e-4a33-b606-5eaba2196824\1.192.2\ps_modules\MSBuildHelpers\Microsoft.TeamFoundation.DistributedTask.MSBuild.Logger.dll";"RootDetailId=772cb217-9388-4362-a2c5-2822e9a3e0a2|SolutionDir=C:\__w\1\s\EngSys-Pipelines\templates\msbuild\CodeSign"*ForwardingLogger,"C:\__w\_tasks\MSBuild_c6c4c611-aa2e-4a33-b606-5eaba2196824\1.192.2\ps_modules\MSBuildHelpers\Microsoft.TeamFoundation.DistributedTask.MSBuild.Logger.dll" /t:Restore /m /p:_MSDeployUserAgent="VSTS_41bf5486-7392-4b7a-a7e3-a735c767e3b3_build_251213_0"

### Expected Behavior

MSBuild should run the project I specified on the 

### Actual Behavior
MSBUILD : error MSB1008: Only one project can be specified.
Switch: <Some project path>

Example:

MSBUILD : error MSB1008: Only one project can be specified.
Switch: C:\__w\1\s\EngSys-Pipelines\templates\msbuild\CodeSign\CodeSignUntrustedFiles.proj

### Analysis
This issue is confusing because the exact same command line will work in one repo but not another. 

### Versions & Configurations

MSBuild 17 or older.
Windows

**Comment by rainersigwald** [comment]
@CarlHeinrichs instead of just `%MSBUILDTELCMD%`, you can use the functionality from dotnet/msbuild#4612 for exactly this case.

**Comment by Forgind** [comment]
Closing from:

> @CarlHeinrichs instead of just `%MSBUILDTELCMD%`, you can use the functionality from #4612 for exactly this case.
