### ISSUE TITLE
Log a message for every response file used and embed in binlog

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/msbuild#7214]
We should log a message at the beginning of the build when we're using a response file, and embed each response file used into the binlog.

**Comment by edvilme** [comment]
Just working on this. What would be a good message to log? Was thinking someting like 
```
Using response file: /path/to/response-file.rsp
```

Also should this be for standalone msbuild or also for running within dotnet?

**Comment by edvilme** [comment]
Should message be logged even if errors are detected? 
![image](https://user-images.githubusercontent.com/5952839/200411612-b7e69f8a-11b8-4926-9f0a-260f54c98cbc.png)

**Comment by KirillOsenkov** [comment]
Yup, your message looks good, use it for all MSBuilds and also log when errors are detected.

**Comment by edvilme** [comment]
Great, thanks! Also, should the message be high importance (I feel normal should do it to avoid adding more verbosity)?

**Comment by KirillOsenkov** [comment]
Yes, normal should be fine.

In general, when in doubt, and no one has responded yet, just go with the option that makes most sense to you and we can always tweak later :) Just so you're not blocked if we're not around.
