### ISSUE TITLE
TypeInitializerException in DebugUtils

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/msbuild#7241]
### Issue Description

In [this feedback ticket](https://developercommunity.visualstudio.com/t/visual-studio-gets-confused-when-i-run-msbuild/1589332) I advised a customer to set the `MSBuildDebugEngine` environment variable to `1`. When they did so they received...

> error : The type initializer for ‘Microsoft.Build.Shared.Debugging.DebugUtils’ threw an exception.

...for each of the three non-SDK-style .csproj projects in their solution.

### Steps to Reproduce

As above. This is customer reported and I don't have much information at this point.

Feel free to engage the customer via the feedback ticket directly.

### Expected Behavior

No exception.

### Actual Behavior

Exception.

### Analysis

There is quite a bit of type initializer logic in: https://github.com/dotnet/msbuild/blob/518c041f4511a6bc23eb40703b69a94ea46c65fd/src/Shared/Debugging/DebugUtils.cs

I've asked if they have more information in the Event Viewer.

Feel free to engage the customer via the feedback ticket directly.

### Versions & Configurations

Visual Studio 2022 version 17.0.4

### Attach a binlog

This exception means we are blocked on getting build logs.

**Comment by drewnoakes** [comment]
I can repro this locally. The cause is, perhaps, unsurprising:

> UnauthorizedAccessException: Access to the path 'C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild_Logs' is denied.

The workaround then is to set `MSBuild_Logs` to a writeable path.

Regardless, I believe the situation could be improved for the end user who stumbles into this. Either by unwrapping the `TypeInitializerException` when reporting in VS, and perhaps by including a better exception message that explains use of the `MSBuild_Logs` environment variable.

**Comment by rainersigwald** [comment]
Looks like #6792 didn't fix this enough. I think we should default to `TEMP` rather than CWD, maybe after probing for writability.

**Comment by Forgind** [comment]
This isn't in line with our other environment variables, but it would be interesting to have MSBuildDebugEngine be set to a _path_ rather than just 1 and automatically set MSBUILDDEBUGPATH to that if it isn't set. That would presumably erase some of the confusion around setting that properly.

**Comment by Forgind** [comment]
I would be in favor of probe first, default to temp after. Other logs (like binlog, diagnostic log) are written to the cwd by default, so writing somewhere else by default is unexpected from that perspective.
