### ISSUE TITLE
'KillTree' test leaves Windows Terminal window opened

### ISSUE THREAD

**Issue by MichalPavlik** [dotnet/msbuild#7255]
This is very minor thing, but if you have Windows 11 and Windows Terminal is the default terminal, then even when the test successfully terminates powershell process, the Windows Terminal window is still opened. Sometimes the test kills the process fast enough to have WT window without any tab. In that case the window can't be closed without manually create new tab.
It's a bit annoying when running tests locally. I propose to use `new ProcessStartInfo("rundll32", "kernel32.dll, Sleep")` to start test process on Windows. I believe it makes the test also a little bit faster :)

**Comment by rainersigwald** [comment]
😲 I've been slowly trying to narrow down what has been causing this with the WT team but haven't beem able to narrow it down. Amazing, thank you! They're interested in fixing this part

> Sometimes the test kills the process fast enough to have WT window without any tab. In that case the window can't be closed without manually create new tab.

But needed a good repro--which maybe now we can give them!

**Comment by MichalPavlik** [comment]
Great, I'm glad I could help. I found the root cause of "unclosable" WT window by accident. When I was debugging the test, the WT window had one tab with message that the PS process was terminated with exit code. Increasing `Task.Delay` interval in the test has same effect, so I believe the reason is that the process is terminated before WT is fully initialized.
Anyway, I think that create a windowless process for this test is better. When WT team fixes this issue, we would have to manually close the WT window anyway, because it belongs to different process.

**Comment by rainersigwald** [comment]
> I think that create a windowless process for this test is better.

Yes, I fully support this. Want to put up a PR?

**Comment by MichalPavlik** [comment]
Yes, it's simple :)
