### ISSUE TITLE
Release MSBuild 17.1

### ISSUE THREAD

**Issue by rainersigwald** [dotnet/msbuild#7285]
- [x] Create darc channel for `VS 17.2` if it doesn't already exist \
`darc add-channel --name "VS 17.2"`
- [x] Associate the next release branch with the next release channel \
`darc add-default-channel  --channel "VS 17.2" --branch vs17.2 --repo https://github.com/dotnet/msbuild`
- [x] Remove the `main` to old release channel default channel \
`darc delete-default-channel --repo https://github.com/dotnet/msbuild --branch main --channel "VS 17.1"`
- [x] Associate the `main` branch with the next release channel \
`darc add-default-channel  --channel "VS 17.2" --branch main --repo https://github.com/dotnet/msbuild`
- [x] Check subscriptions for the current channel `VS 17.1` and update as necessary (for instance, SDK's `main` branch should usually be updated \
`darc get-subscriptions --exact --source-repo https://github.com/dotnet/msbuild --channel "VS 17.1"`
- [x] Ensure that the current release channel is associated with the correct release branch\
`darc get-default-channels --source-repo https://github.com/dotnet/msbuild --branch vs17.1`
- [x] Fast-forward merge the correct commit to the `vs17.1` branch \
`git push upstream 797fd829a374a880f63fd4eea4ea6990404c48f4:refs/heads/vs17.1`
- [x] Prepare final branding PR for `vs17.1` but ⚠️ DO NOT CHECK IN YET ⚠️ #7225 
- [x] Promote `unshipped` public API to `shipped` in `main`
      1. `Get-ChildItem -r src/PublicAPI.*.txt | Clear-Content`
      2. Open MSBuild.sln in Visual Studio, let it settle
      3. Find a green squiggle for the analyzer and fix all in solution
      4. `Get-ChildItem -r PublicAPI.Unshipped.txt | % { Move-Item -Force -Path $_ (Join-Path $_.Directory.FullName "PublicAPI.Shipped.txt") && New-Item $_ }`
- [x] Create 17.2 branding PR, including public API change #7224
- [x] Merge 17.2 branding PR
- [x] Prepare QB-mode bug for final branding insertion in internal VS repo
- [x] Update [internal "create VS PR for insertion"](https://dev.azure.com/devdiv/DevDiv/_releaseDefinition?definitionId=2153&_a=definition-variables) release to point to the new VS release branch by default
- [x] Merge final branding to `vs17.1` branch
- [x] Get QB approval
- [x] Merge to VS
- [x] ASAP after release, push packages to nuget.org (not currently automated, contact dnceng)
- [x] Update `main` subscriptions to the new channel (this can be done after release) \
`darc get-subscriptions --exact --target-repo https://github.com/dotnet/msbuild --target-branch main`

**Comment by Forgind** [comment]
Do we also need to update our subscriptions?
```
https://github.com/nuget/nuget.client (VS 17.1) ==> 'https://github.com/dotnet/msbuild' ('main')
```
for example

**Comment by Forgind** [comment]
How do we promote unshipped public API to shipped? Not sure I've done that before. Manual cut-paste?

**Comment by rainersigwald** [comment]
> Do we also need to update our subscriptions?
> 
> ```
> https://github.com/nuget/nuget.client (VS 17.1) ==> 'https://github.com/dotnet/msbuild' ('main')
> ```
> 
> for example

Yes! Added.

**Comment by rainersigwald** [comment]
> How do we promote unshipped public API to shipped? Not sure I've done that before. Manual cut-paste?

Looks like copy/paste is indeed the way: dotnet/roslyn-analyzers#3448.

**Comment by rainersigwald** [comment]
Got better instructions on the final API and put them in the OP and the linked issue. Also added that change to #7225.

**Comment by Forgind** [comment]
So it sounds like we should also add "update things subscribed to us"? I would've thought that was their job?

**Comment by KirillOsenkov** [comment]
don't forget publish to nuget.org

**Comment by ladipro** [comment]
cc @rokonec as 17.1 may GA during his kitten.

**Comment by marcpopMSFT** [comment]
@dotnet/kitten can you update the darc subscriptions so we can close this out? They are still on 17.1.

**Comment by KirillOsenkov** [comment]
Don't forget to publish to nuget.org 😛

**Comment by abatishchev** [comment]
Don't forget to [publish a release](https://github.com/dotnet/msbuild/releases?q=msbuild&expanded=true) too :)

**Comment by rainersigwald** [comment]
@abatishchev added that to #7459 for 17.2. https://github.com/dotnet/msbuild/releases/tag/v17.1.0
