### ISSUE TITLE
MSBUILD Multi-Threading

### ISSUE THREAD

**Issue by donJoseLuis** [dotnet/msbuild#7314]
# Background
Epic parent of user stories that aim to deliver multi-threading in MSBUILD.

## User Stories
- [x] #7315 
- [x] #7316 
- [ ] #7317
- [ ] #7318

## Justification
- Customer impact - With modern processors, MSBuild initializes many processes during the build. Multi-threaded approach reduces unnecessary process initialization, complexity and increases build performance.
- Needle moving (perf) - We estimate shaving >1 second off a non-trivial cold build even on the beefiest build machine due to the reduction of processes that have to be started, and ~5-10% of wall clock time savings in all builds.

**Comment by rokonec** [comment]
Canceled
