### ISSUE TITLE
When Copy fails to copy a file, report which process is locking the file on .NET Core's msbuild

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/msbuild#7327]
https://github.com/dotnet/msbuild/pull/2301 enabled printing which process locks a file but apparently this doesn't work on .NET Core's msbuild: https://github.com/dotnet/msbuild/blob/main/src/Tasks/Copy.cs#L902.

Any chance this could be enabled by making the logic work cross-platform? cc @KirillOsenkov @rainersigwald

**Comment by rainersigwald** [comment]
It should definitely be made to work on .NET 6 on Windows.

I don't know of a cross-platform option though. @ViktorHofer do you know of one? I suppose we could attempt to shell out to `lsof` . . .

**Comment by ViktorHofer** [comment]
I don't know of any but I'm not an expert on that area. @tmds or @akoeplinger might know (?)

**Comment by akoeplinger** [comment]
We could start by enabling it on netcore MSBuild on Windows at least.

**Comment by tmds** [comment]
>I don't know of a cross-platform option though. @ViktorHofer do you know of one? I suppose we could attempt to shell out to lsof . . .

There is no syscall for this. `lsof` looks at the files in `/proc/<pid>/<fd>`, which are symbolic links, and finds which ones link to the target.
