### ISSUE TITLE
Schema has incorrect PublicKey metadata for InternalsVisibleTo items

### ISSUE THREAD

**Issue by mhutch** [dotnet/msbuild#7336]
The schema currently offers completion for `PublicKey` metadata on `InternalsVisibleTo` items. This was added in https://github.com/dotnet/msbuild/pull/6778.

However, this is incorrect as the metadata for setting the public key is named `Key` (https://github.com/dotnet/sdk/pull/3439).

It may be better to leave the schema as-is and have the item respect `PublicKey` metadata for consistency with the `PublicKey` property, as suggested in https://github.com/dotnet/sdk/issues/13289#issuecomment-713355359.

**Comment by rainersigwald** [comment]
@marcpopMSFT got a preference here?

**Comment by marcpopMSFT** [comment]
So it was supposed to be `PublicKey` originally but was done as `Key` instead and the question is whether to update the Schema to point at `Key` or supported `PublicKey`? I think adding support for `PublicKey` makes slightly more sense to me as it may be what folks expect.
