### ISSUE TITLE
Creating UWP AppxBundle from project target works in VS Wizard but fails in MSBuild

### ISSUE THREAD

**Issue by zkacso-dev** [dotnet/msbuild#7337]
We are developing a UWP app for ARM64 and x64 platforms.
When we create the multi-platform package from the Visual Studio wizard it builds only the necessary projects for the target.

**The problem is when we execute it with msbuild.exe on our CI machines (or locally) it only limits the build to the target for the first platform it builds, and not for any consequent platforms.** This costs us a lot of time, while we wait for the whole solution to build, when we only needed a single project and its dependencies.

From looking at the build log I found `GetSolutionConfigurationContents` target appearing, which looked odd.
![image](https://user-images.githubusercontent.com/60542138/151150195-e730aacf-b24c-451b-815b-f74060aa855c.png)

**Created a minimal repro for this problem**: https://1drv.ms/u/s!AmtpQxAm1CzgggSWIRyyOcMeneDU?e=sQWx9M
1. Build it from VS, so nuget packages are downloaded properly.
2. run `build.ps1` (it expects VS2019)
3. It builds the faulty project as well even though we specified `/t:App`

if you package it from VS wizard it builds properly.

As a workaround we created a separate `.sln` file, that only contains the necessary projects, but needs extra maintenance, so not a solution that we want to keep forever.

**Comment by v-codyguan** [comment]
Hi @BenVillalobos , we've reproduced this issue according to zkacso-dev's repro step, after running build.ps1 and checking the _App_'s bin folder, nothing generated about x64 platform. Could you help to take a look?

**Comment by BenVillalobos** [comment]
@v-codyguan thanks!

I can't seem to get a successful build. Am I missing some dependency?

```
C:\Users\bevillal\Downloads\msbuild-min-repo\App>pwsh build.ps1
Building the projects in this solution one at a time. To enable parallel build, please add the "-m" switch.
Build started 2/3/2022 9:53:14 AM.
Project "C:\Users\bevillal\Downloads\msbuild-min-repo\App\TheApp.sln" on node 1 (App target(s)).
ValidateSolutionConfiguration:
  Building solution configuration "Release|ARM64".
Project "C:\Users\bevillal\Downloads\msbuild-min-repo\App\TheApp.sln" (1) is building "C:\Users\bevillal\Downloads\msbu
ild-min-repo\App\App\App.csproj" (2) on node 1 (default targets).
PrepareForBuild:
  Creating directory "bin\ARM64\Release\".
  Creating directory "obj\ARM64\Release\".
MarkupCompilePass1:
  Creating directory "obj\ARM64\Release\intermediatexaml\".
C:\Program Files (x86)\Windows Kits\10\bin\10.0.19041.0\XamlCompiler\Microsoft.Windows.UI.Xaml.Common.targets(312,5): X
aml Internal Error error WMC9999: Cannot find type System.Enum in module CommonLanguageRuntimeLibrary. [C:\Users\bevill
al\Downloads\msbuild-min-repo\App\App\App.csproj]
Done Building Project "C:\Users\bevillal\Downloads\msbuild-min-repo\App\App\App.csproj" (default targets) -- FAILED.

Done Building Project "C:\Users\bevillal\Downloads\msbuild-min-repo\App\TheApp.sln" (App target(s)) -- FAILED.
```

What is the version of VS 2019 you're using?

**Comment by v-codyguan** [comment]
@BenVillalobos Hi, we changed the MSBuild path （Note: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\msbuild.exe） to our VS msbuild path in build.ps1 file, and the version of VS 2019 is 16.11.9. And if you need repro machine, please feel free to contract us.

**Comment by zkacso-dev** [comment]
@BenVillalobos I think nuget initialization is missing. I wrote that I didn't add that to the powershell script.

**Comment by BenVillalobos** [comment]
> I think nuget initialization is missing.

Sorry, what nuget initialization is required? I tried running `dotnet restore` on the project and building again in a 2019 cmd prompt via `pwsh build.ps1`. And restoring nuget packages via VS 2019

**Comment by denyonce317** [comment]
Hello, I have experienced the same issue. 
Found this : https://issuetracker.unity3d.com/issues/uwp-building-multi-platform-appxbundle-via-msbuild-fails-with-il2cpp-scripting-backend
It solved my issue. Might be a help.
