### ISSUE TITLE
Can't build the repo locally: swc.exe exited with code -532462766

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/msbuild#7352]
```
C:\Users\kiril\.nuget\packages\microbuild.plugins.swixbuild\1.0.672\build\OutOfProcSwix.targets(36,5): error MSB6006: "
swc.exe" exited with code -532462766. [C:\Users\kiril\.nuget\packages\microsoft.dotnet.arcade.sdk\6.0.0-beta.22076.8\to
ols\VisualStudio.SetupPackage.swixproj]
```

**Comment by KirillOsenkov** [comment]
Ping me for full binlog if needed

**Comment by KirillOsenkov** [comment]
Oh, this is because I have ungaced Microsoft.Build.Framework.dll 4.0.0.0:

```
Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Build.Framework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
```

I just found out that after I ungaced all MSBuild dlls, nuget.exe stopped working too.

**Comment by rainersigwald** [comment]
Thanks for following up! Since that assembly is part of .NET Framework, it's probably fairly destructive to unGAC it, so I don't think we need to try to fix anything here (though it should be fixed anyway when the SWIXbuild stuff gets ported  to .NET 6, which I believe is planned).

**Comment by KirillOsenkov** [comment]
So when we tell customers to UnGAC MSBuild dlls, do we keep the framework ones? If we tell them to UnGAC everything it will put them in the state where lots of tools break.

**Comment by rainersigwald** [comment]
Yes, people should unGAC only the 15.1.0.0 versions, and that's what we've always suggested (and #5626 has been successful at making it so people don't have to do it manually any more).
