### ISSUE TITLE
ProduceReferenceAssembly true no longer creates bin/framework/ref directory - .NET 6.0.200 SDK

### ISSUE THREAD

**Issue by mrward** [dotnet/msbuild#7355]
### Issue Description

 - .NET 6.0.200 SDK no longer produces ref assemblies in the bin directory when ProduceReferenceAssembly is set to true.
 - .NET 6.0.101 SDK works as expected.

### Steps to Reproduce

 - Install .NET 6.0.200 SDK (took latest build from dotnet/installer). dotnet --info ` Version:  6.0.200 Commit:  e950d07146`
 - dotnet new classlib -o RefAssemblyTest
 - cd RefAssemblyTest
 - Open RefAssemblyTest.csproj and add `<ProduceReferenceAssembly>True</ProduceReferenceAssembly>` to the main property group.
 - dotnet build

### Expected Behavior

 - bin/Debug/net6.0/ref directory exists with reference assembly.

### Actual Behavior

 - No bin/Debug/net6.0/ref directory.
 - The obj/Debug/net6.0/ directory has a ref and a refint directory.
 - Works with .NET 6.0.101 sdk.

### Analysis

Microsoft.Common.CurrentVersion.targets uses 'refint' instead of 'ref' which I think is causing the problem. Typo?.

https://github.com/dotnet/msbuild/blob/91c64cef6ae8a45dbc7387ef78f298708ce92fca/src/Tasks/Microsoft.Common.CurrentVersion.targets#L397
   <IntermediateRefAssembly Include="$(IntermediateOutputPath)refint\$(TargetName)$(TargetExt)" Condition="'@(IntermediateRefAssembly)' == ''" />

.NET 6.0.101 sdk does not create a refint directory anywhere.

### Versions & Configurations

dotnet --info
Version:  6.0.200
Commit:  e950d07146

**Comment by rainersigwald** [comment]
This is an intentional change (see dotnet/msbuild#6543)--can you describe what you were doing with the ref assembly before? There may be a better way to reference it that is robust to path changes.

We got many complaints about the `bin/ref/` folder after its introduction and the build speedups can work fine without it. If you would like to control the path, you can set the property `TargetRefPath` to a path of your choosing.

@baronfel we probably need an SEO'ed document on this change.

**Comment by baronfel** [comment]
@rainersigwald in the [.NET 6 breaking changes docs](https://docs.microsoft.com/en-us/dotnet/core/compatibility/6.0)? That seems easy enough to do.

**Comment by mrward** [comment]
I was investigating an internal devdiv bug 1464647 filed against VS Mac. A classic Xamarin.iOS project is referencing a netstandard project that generates a reference assembly using ProduceReferenceAssembly. The build here seems to fail with an error:

error CS0006: Metadata file 'FormsRefAssemblyRepro/FormsRefAssemblyRepro/FormsRefAssemblyRepro/bin/Debug/netstandard2.0/ref/FormsRefAssemblyRepro.dll' could not be found

If not coping to the bin/framework/ref directory is by design then I suspect this may be a problem on the VS Mac side since it is not possible to build a classic Xamarin.iOS project with dotnet's msbuild, so we have two different msbuild's being used in the same solution. The non-dotnet msbuild I suspect is assuming the old behaviour and failing.

**Comment by rainersigwald** [comment]
Thanks @mrward. Made a comment there (trying `ProduceReferenceAssemblyInOutDir`) and happy to continue investigating with you.

**Comment by mrward** [comment]
Closing this since it is by design.
