### ISSUE TITLE
Is there a build start property?

### ISSUE THREAD

**Issue by stan-sz** [dotnet/msbuild#7357]
Per https://stackoverflow.com/questions/54278833/msbuild-build-start-property - we have a need to have the same (down to a second) build start property, that will be used as a label in all projects built in a traversal. Declaring a property as

```xml
<Now Condition="'$(Now)'==''">$([System.DateTime]::Now.ToString('yyyyMMddHHmmss'))</Now>
```

can have different value for different projects.

**Comment by Forgind** [comment]
What do you want to use it for? Can you use our [ETW traces](https://github.com/dotnet/msbuild/blob/main/documentation/specs/event-source.md)? There's one for Build, BuildProject, and MSBuildExe, which sound like different sides of what you're looking for. They come with stop events as well and extra information if that would be of value to you.

**Comment by stan-sz** [comment]
I'm looking for a way to pass the same piece of information (tag/label) that can be visible to all projects in a traversal.
In technical terms, expose https://github.com/dotnet/msbuild/blob/09bdfae164eac3b5c9027d803ffa513efaf91095/src/Build/Logging/SerialConsoleLogger.cs#L108 as MSBuild well-known property in a parseable form (so in projects we can use property functions to re-format the start time string).
Ideally we'd get two new well-known properties:
* `MSBuildStartTime` - the start of `msbuild.exe`
* `MSBuildProjectStartTime` - the start of building current project

**Comment by jrdodds** [comment]
@stan-sz Is the purpose of the timestamp to identify the build?

Are you using a tool or service to build like Azure DevOps Pipelines? In AzDO Pipelines there is a set of environment variables passed to the build. The environment variables include `$(Build_BuildNumber)` which should be unique per build (and which can be custom configured to be a timestamp down to the second.) If you are not using Azure DevOps, I'm sure other similar tools have similar capabilities.

If you are not using a build tool and are invoking MSBuild against the .sln file, you can extend the solution with a [before.{solutionname}.sln.targets](https://docs.microsoft.com/en-us/visualstudio/msbuild/customize-your-build?view=vs-2022#customize-the-solution-build) file. Note that the before|after.{solutionname}.sln.targets files are not honored by Visual Studio.

Hope that helps.

**Comment by stan-sz** [comment]
@jrdodds yes, this is needed to identify the build, however, the purpose of this property would be to fall back to date/time in case the build is not executed in Azure DevOps (e.g. local builds).

**Comment by jrdodds** [comment]
In many shops, local builds either are not given an identifier or are given a generic identifier like 'dev' or 'local'. This is because local builds are not considered 'official' and can't be used for releases. Local builds won't have the documented 'provenance' of a build linked to work items/issues, version control history, and test management.

You may know all of this already and you may have constraints that don't allow for identifying local builds differently and that is understandable. I'm only providing some context for why this is an unmet need.

**Comment by jrdodds** [comment]
@stan-sz Values for properties passed on the command line are not evaluated for property references. I did a quick test to confirm. In your example `_BuildStartTime` will be set to the string "$([System.DateTime]::Now.ToString('yyyyMMdd-HHmmss'))" and not the current date/time.

**Comment by stan-sz** [comment]
Is it a reasonable feature request to have the command line args of `/p` be evaluated?

**Comment by jrdodds** [comment]
I think that changing the behavior of `/p` would be a breaking change but a request to add a new switch might be reasonable.

However, I think you are just trying to define the `_BuildStartTime` property early and you don't need any new features for that.

At the root of your repo you can add a [Directory.Build.props](https://learn.microsoft.com/en-us/visualstudio/msbuild/customize-your-build?view=vs-2022#directorybuildprops-and-directorybuildtargets) file with a property definition for `_BuildStartTime`:

```XML
<Project>
  <!-- Chain this file with files of the same name -->
  <Import Project="$([MSBuild]::GetPathOfFileAbove('$(MSBuildThisFile)', '$(MSBuildThisFileDirectory)../'))" />

  <PropertyGroup>
    <_BuildStartTime Condition="'$(_BuildStartTime)' == ''">$([System.DateTime]::Now.ToString('yyyyMMdd-HHmmss'))</_BuildStartTime>
  </PropertyGroup>
</Project>
```

Defining a property doesn't mean that it needs to be used. `_BuildStartTime` can be left unused when the build is not local.

**Comment by rainersigwald** [comment]
@jrdodds that wouldn't be the _build_ start time, though--it'd be the _evaluation time of each project_, since properties are evaluated in each project.

**Comment by jrdodds** [comment]
Yes. That's true. My understanding is that would still work for @stan-sz but I could be wrong about that.

**Comment by stan-sz** [comment]
I am looking for a unique and same-for-all-projects date time value.

**Comment by stan-sz** [comment]
Is there a file that msbuild creates at the start of the build that we could take the last write time of as an equivalent of build start time property?

**Comment by rainersigwald** [comment]
> Is there a file that msbuild creates at the start of the build that we could take the last write time of as an equivalent of build start time property?

No. There's no particular location that would make sense for such a file, since a build can be customized within projects to have different `OutDir` and other output folders, so we can't know when the build starts what would be a reasonable place to put it. There's also no reason for such a file currently.
