### ISSUE TITLE
Community feedback survey

### ISSUE THREAD

**Issue by marcpopMSFT** [dotnet/msbuild#7358]
We’d like to hear from you the members of the community in this repo to learn how we were doing as maintainers.

Whether you've been involved for some time or you're relatively new please tell us about your experience participating and contributing to the project. It should only take a few minutes, and you can answer for up to 3 repos:

https://www.surveymonkey.com/r/8QTQTGJ?Source=msbuild

**Comment by danmoseley** [comment]
Survey is now closed - thanks for everyone that responded. We'll look through the feedback now.
