### ISSUE TITLE
[MSBuild Server] Introduce a client-side activation/communication library

### ISSUE THREAD

**Issue by ladipro** [dotnet/msbuild#7373]
Measure the client startup cost of these approaches:
1. Use `Microsoft.Build` as the client library. Based on the premise that most of the assembly will not be used when communicating with the server.
1. Introduce a new assembly solely for the purpose of talking to the server.
1. Distribute the client in the form of source code.

Depending on the outcome of the above, add a project in the MSBuild repo with a new client library. The library exposes a public API through which it accepts build requests. The API can be left unimplemented for now.

Acceptance criteria: Regardless of the approach chosen the library publishes out of the MSBuild repo for both .NET Framework and .NET 6/7 targets. It exposes a modern async API.

**Comment by AR-May** [comment]
We measured rebuild of the same project for all three options and did not see much of difference performace-wise.
Here are the results.
Option|First Run|SecondRun
---|---|---
1|1967.6 ms|275 ms
2|1985 ms|265 ms
3|2036 ms|295 ms

Hence, we decided we will implement it in `Microsoft.Build` assembly.
