### ISSUE TITLE
VS2019 debug output filled with crappy messages

### ISSUE THREAD

**Issue by sancilla** [dotnet/msbuild#7380]
Created the environment.txt that contains:
MONO_LOG_LEVEL=error
MONO_LOG_MASK=gc
Set the build action to Android Environment

AND STILL CAN NOT GET RID OF THESE ANNOYING LINES:
[monodroid-assembly]     ZIP: local header offset: 35499804; data offset: 35499912; file size: 1683384
 [monodroid-assembly] /data/app/Mono.Android.DebugRuntime-kjbSvJffIh6KuLyEXW4fQQ==/base.apk entry: assemblies/netstandard.dll
 [monodroid-assembly]     ZIP: local header offset: 37183296; data offset: 37183408; file size: 90624
 [monodroid-assembly] /data/app/Mono.Android.DebugRuntime-kjbSvJffIh6KuLyEXW4fQQ==/base.apk entry: typemap.jm
 [monodroid-assembly]     ZIP: local header offset: 37274032; data offset: 37274128; file size: 1304780
 [monodroid-assembly] /data/app/Mono.Android.DebugRuntime-kjbSvJffIh6KuLyEXW4fQQ==/base.apk entry: typemap.mj

Completely messing up the debug output, filling with unnecessary crap.

IS THERE A SOLUTION FOR THIS WELL-KNOWN BUG????????

**Comment by Forgind** [comment]
Team Triage: We believe this is an issue with Visual Studio, not MSBuild. Can you [open a feedback ticket instead](https://docs.microsoft.com/visualstudio/ide/feedback-options)?
