### ISSUE TITLE
command for msbuild

### ISSUE THREAD

**Issue by alicera** [dotnet/msbuild#7396]
There is a project sample.
```
../sample/
├── build
├── CMakeLists.txt
├── main.cpp
└── release
```

I build it with the command
```
cd sample
cmake -G "Visual Studio 16 2019" ^
		-S .\ ^
		-B .\build ^
		-DCMAKE_BUILD_TYPE=Release ^
cmake --build build --config Release
cmake --install build --config Release --prefix .\release
```

How can I command with `MSBuild` to get the library in release?

**Comment by Forgind** [comment]
Team triage:
Can you clarify what you're trying to accomplish? Also, your commands use cmake rather than MSBuild. Did you intend to file an issue with cmake?
