### ISSUE TITLE
CS2015 error on version 17.1.0

### ISSUE THREAD

**Issue by robga** [dotnet/msbuild#7400]
### Issue Description

After upgrading VS2022 to 17.1.0, my project failed to build. The compiler tried to compile many files in the "None" property in the target file and hit CS2015 error. I posted the details on the internal stackoverflow. 
https://stackoverflow.microsoft.com/questions/294670

### Versions & Configurations

This issue is only on 17.1.0. I repro the issue on two PCs with 17.1.0 for the same project. I didn't see this issue before. I also tried on 17.0.6 for the same code on the third PC which works fine.

**Comment by rainersigwald** [comment]
Can you share a binary log of the failing build? https://aka.ms/msbuild/binlog has instructions and warnings--if you want to share only internally let me know where you put it.

**Comment by rainersigwald** [comment]
@robga shared a log offline and this looks like an instance of https://developercommunity.visualstudio.com/t/Visual-Studio-2022-Preview-171-emits-/1645825.
