### ISSUE TITLE
Platform negotiation breaks transitive P2P references

### ISSUE THREAD

**Issue by AArnott** [dotnet/msbuild#7402]
### Issue Description

P2P references tend to be transitive, in that an indirectly referenced C# project will still be passed to the compiler. But this no longer works once platform negotiation is turned on.

### Steps to Reproduce

Use this repro sln, or follow these instructions.
[repromsbuild.zip](https://github.com/dotnet/msbuild/files/8101090/repromsbuild.zip)

```
dotnet new classlib -o head
dotnet new classlib -o middle
dotnet new classlib -o tail
dotnet add middle reference head
dotnet add tail reference middle
```

Then add this to the `tail/Class1.cs` file's class declaration:

```cs
    void Test()
    {
        head.Class1 h;
    }
```

```
dotnet build tail
```

The build succeeds.

Now add a `Directory.Build.props` file with this content (as directed by [the docs](https://github.com/dotnet/msbuild/blob/main/documentation/ProjectReference-Protocol.md#how-to-opt-in)):

```xml
<Project>
    <PropertyGroup>
        <EnableDynamicPlatformResolution>true</EnableDynamicPlatformResolution>
        <DisableTransitiveProjectReferences>true</DisableTransitiveProjectReferences>
    </PropertyGroup>
</Project>
```

And build again:

```
dotnet build tail
```

### Expected Behavior

The build succeeds both before and after enabling platform negotiation.

### Actual Behavior

The build fails after enable platform negotiation due to the compiler being unable to bind to a type from the transitive project reference.

> C:\temp\repromsbuild\tail\Class1.cs(6,9): error CS0246: The type or namespace name 'head' could not be found (are you missing a using directive or an assembly reference?) [C:\temp\repromsbuild\tail\tail.csproj]

### Versions & Configurations

I am using the .NET 6.0.100 SDK, with VS 2022 IntPreview installed.

CC: @BenVillalobos

**Comment by AArnott** [comment]
Ok, so I'm a total idiot. The steps include setting `DisableTransitiveProjectReferences` to `true`. I just copied and pasted this from [the docs on how to turn on platform negotiation](https://github.com/dotnet/msbuild/blob/main/documentation/ProjectReference-Protocol.md#how-to-opt-in) without reading them.

Why must transitive P2Ps be turned off for platform negotiation to work?

**Comment by BenVillalobos** [comment]
> Why must transitive P2Ps be turned off for platform negotiation to work?

To be completely honest, I don't remember why that flag had to be disabled. My best guess would be that transitive projectreferences bubbled up and followed the SetPlatform flow as a result.

This target in the SDK is probably the culprit behind the decision.

```
  <Target Name="IncludeTransitiveProjectReferences"
          DependsOnTargets="ResolvePackageAssets"
          Condition="'$(DisableTransitiveProjectReferences)' != 'true'">
    <ItemGroup>
      <ProjectReference Include="@(_TransitiveProjectReferences)" />
    </ItemGroup>
  </Target>
```

Checking out a binlog of the build with/without the flag set, It looks like enabling transitive references bubbles up all projectreferences to the level of the current project.

See how Tail tries to build Middle and Head here:

![image](https://user-images.githubusercontent.com/4691428/155192413-9e631764-5539-457f-a210-60a9571193a5.png)

In Tail (x86) -> Middle (anycpu) -> Head (x86, anycpu), Tail would attempt to build Head as x86 (because they match), which wouldn't be the most compatible platform. 

I can see this being fine for most scenarios since you'd still end up with less project builds because we still determine most compatible and stick with that.

Thoughts?

**Comment by AArnott** [comment]
> In Tail (x86) -> Middle (anycpu) -> Head (x86, anycpu), Tail would attempt to build Head as x86 (because they match), which wouldn't be the most compatible platform.

I'm puzzled by this analysis. If the 'app' (or Tail in this case) builds in x86, then ultimately we want to deploy x86 binaries with the app, I would think. At least this is how .NET and nuget work today, where regardless of the AnyCPU-ness of a nuget package's reference assemblies, when it comes time to deploying binaries (copylocal behavior), if a nuget package contains binaries under the `runtimes/*` folder, those are copied instead of the ref assemblies. These runtime folders typically carry architecture-specific binaries, so ultimately the app being published will pick the architecture-specific binaries from all its transitive dependencies.

In this case, if Tail is building for x86 and it wants transitive dependencies such that head acts as if a direct P2P existed, then yes I would expect Head to build as x86 since a more specific match (x86-x86) is preferred over (x86->anycpu). 
I guess this means that Head builds twice (AnyCPU to satisfy Middle, and x86 to satisfy Tail), but as that would be the same behavior if I added a direct P2P from both projects to Head, why shouldn't the implicit transitive dependency behavior be the same?

**Comment by BenVillalobos** [comment]
My example should have been written as Head->Middle->Tail (oops). I recall there being some specific scenario that caused the change. It was likely related to VS but I can't remember off the top of my head (maybe @rainersigwald remembers?) 

> In this case, if Tail is building for x86 and it wants transitive dependencies such that head acts as if a direct P2P existed, then yes I would expect Head to build as x86 since a more specific match (x86-x86) is preferred over (x86->anycpu)

If this should be the normal case, then `DisableTransitiveProjectReferences=true` doesn't need to be a requirement.

**Comment by BenVillalobos** [comment]
Fixed by https://github.com/dotnet/msbuild/pull/8114
