### ISSUE TITLE
Conditional Project Reference in subproject not resolved or compiled

### ISSUE THREAD

**Issue by Arlodotexe** [dotnet/msbuild#7438]
### Issue Description

When a project contains a reference to another project with conditional dependencies, such as

```xml

<ItemGroup>
	<PackageReference Condition="'$(WinUITarget)' == '2.x'" Include="Uno.UI" Version="4.0.13"/>
	<PackageReference Condition="'$(WinUITarget)' == '3.x'" Include="Uno.WinUI" Version="4.0.13"/>
</ItemGroup>

```

Investigating the binlog, the package reference is picked up by some Targets (`ResolvePackageAssets`, `CollectPackageReferences`, etc), but not other Targets (`ResolveAssemblyReferences`, `CoreCompile`), causing the final build to fail due to namespaces from those packages not resolving.

### Steps to Reproduce

A fully, minimal repro will be available here until this issue is closed
https://github.com/Arlodotexe/ConditionalPackageReferenceTest

Otherwise, a backup of the repository and the binlogs are attached:
[ConditionalPackageReferenceTest.zip](https://github.com/dotnet/msbuild/files/8188985/ConditionalPackageReferenceTest.zip)
[ConditionalPackageReferenceTest.binlogs.zip](https://github.com/dotnet/msbuild/files/8188986/ConditionalPackageReferenceTest.binlogs.zip)

### Expected Behavior

Build should succeed when package references are conditional.

### Actual Behavior

Innermost project fails to build due to the assembly in the conditional package reference not being passed to the `CoreCompile` task.

**Comment by BenVillalobos** [comment]
Pinging @nkolev92  _just in case_ it's something obvious from the nuget side of things

**Comment by nkolev92** [comment]
AdditionalProperties, UndefineProperties and the likes just won't work through ProjectReference. 

https://github.com/NuGet/Home/issues/7286 Feel free to upvote that issue for the NuGet side of it all. 
I think there might be more on the SDK/MSBuild side, but I just haven't done enough digging on that end to know what that may look like.

**Comment by michael-hawker** [comment]
Thanks @nkolev92, I think we're hitting this limitation mentioned in the docs page [here](https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files#adding-a-packagereference-condition):

> You can use a condition to control whether a package is included, where conditions can use any MSBuild variable or a variable defined in the targets or props file. _However, at presently, only the TargetFramework variable is supported.

Is that the issue you linked to or would it be a different one?

**Comment by BenVillalobos** [comment]
Team Triage: Do you see this issue when using `Microsoft.NET.Sdk` as your SDK instead of `MSBuild.Sdk.Extras`?

**Comment by michael-hawker** [comment]
@Arlodotexe looks like there was a question for you about the SDK type from end of March.

**Comment by Arlodotexe** [comment]
> @Arlodotexe looks like there was a question for you about the SDK type from end of March.

Thanks @michael-hawker, I wasn't sure that this was directed at me.

Coming back to this, it looks like the repro I provided only works from the command line using `msbuild /r /bl`, not in Visual Studio. You'll notice errors such as `The type or namespace name 'Windows' could not be found`, caused by the Uno nuget package not being selected.

We've temporarily worked around this in our project by effectively not using this approach, and instead switching between these 2 packages (WinUI 2 and 3) when under netstandard2.0 by running a PowerShell script before opening the solution.

---

>  Team Triage: Do you see this issue when using Microsoft.NET.Sdk as your SDK instead of MSBuild.Sdk.Extras?

Switching either/both library and wasm head to use `Microsoft.NET.Sdk` doesn't have any effect.

**Comment by Nirmal4G** [comment]
> switch between these 2 packages (WinUI 2 and 3) when under `netstandard2.0` by running a PowerShell script before opening the solution.

A better solution would be to use `Platforms`/`Platform` similar to what MSBuild repo uses.

**Comment by Nirmal4G** [comment]
@Arlodotexe

**Comment by michael-hawker** [comment]
@BenVillalobos is this enough info from Arlo or are you looking for more?

**Comment by Arlodotexe** [comment]
After months of using our current workaround and organizing projects around it, I've realized that conditionally imported props files with PackageReferences don't have this issue.

Which means we might have a workaround. Put the package references in a props file, add your condition to the prop import, and it should work even in a library project / subproject.

```xml
<Project Import="File.props" Condition="'$(Variable)' == 'true'"/>
```

**Comment by Nirmal4G** [comment]
@Arlodotexe

There will be differences when using `TargetFrameworks` vs `TargetFramework` since multi-build comes into play. The outer build will be based on an empty `TargetFramework` and the inner build will have that property populated. And some MSBuild task invocations (_based on how they are implemented_) remove some global properties when dispatching an inner build. So, you could use a differently named property like `LibraryFramework` and `LibraryFrameworks` that would not go into global property removals.

That's why you're seeing these differences. But these two do concern me!

> `$(TargetFramework)` doesn't have a value when used on an `<Import Project="$(TargetFramework)">`.
`$(TargetFramework)` does have a value when used on an `<Import>` Condition.

They should behave the same unless they are in different places like before/after .NET `Sdk.targets`!

As I previously mentioned here in this <https://github.com/dotnet/msbuild/issues/7438#issuecomment-1150419199>, this could be a potential solution.

**Comment by Arlodotexe** [comment]
After more testing and gathering information, it seems that in non-SDK style projects, `TargetFramework` just isn't consistently available during certain steps in the build process.

For now, I've worked around this by avoiding using `TargetFramework` to switch between packages in our project heads, opting instead to add them to the csproj or a props file referenced by it, with no conditions anywhere.

For our library projects, since they're all SDK style, they don't have this issue.
Thanks to that, I was able to create a props file like this for our library projects:

```xml
<Project>
    <!-- WinUI 2 / UWP -->
    <ItemGroup Condition="'$(IsUwp)' == 'true'">
        <PackageReference Include="Microsoft.Toolkit.Uwp.UI.Controls.Primitives" Version="7.1.2"/>
    </ItemGroup>

    <!-- WinUI 2 / Uno -->
    <ItemGroup Condition="'$(IsUno)' == 'true' AND '$(WinUIMajorVersion)' == '2'">
        <PackageReference Include="Uno.Microsoft.Toolkit.Uwp.UI.Controls.Primitives" Version="7.1.11"/>
    </ItemGroup>

    <!-- WinUI 3 / WinAppSdk -->
    <ItemGroup Condition="'$(IsWinAppSdk)' == 'true'">
        <PackageReference Include="CommunityToolkit.WinUI.UI.Controls.Primitives" Version="7.1.2"/>
    </ItemGroup>
    
    <!-- WinUI 3 / Uno -->
    <ItemGroup Condition="'$(IsUno)' == 'true' AND '$(WinUIMajorVersion)' == '3'">
        <PackageReference Include="Uno.CommunityToolkit.WinUI.UI.Controls.Primitives" Version="7.1.100-dev.15.g12261e2626"/>
    </ItemGroup>
</Project>
```

We've got a full workaround for now, but our setup no longer looks like that provided in the issue description. That means we haven't actually fixed the filed issue (despite this issue being closed).
