### ISSUE TITLE
Consider placing ref equivalents in lib of MSBuild's nuget package

### ISSUE THREAD

**Issue by benvillalobos** [dotnet/msbuild#7458]
### Issue Description
During https://github.com/dotnet/msbuild/pull/6148 we created a `ref/` folder in MSBuild's nuget package. This caused an issue with either the sdk or nuget explained here: https://github.com/dotnet/sdk/pull/24258#issuecomment-1064342073

Let's consider placing the equivalent ref assemblies into lib.

**Comment by Nirmal4G** [comment]
Even with the ref Assembly, as long as lib runtime version is found, it should use it. This may be an issue with NuGet than the package itself. If we place ref within the lib, I suspect it'll break a lot of dependent projects where it'll copy Assets into some arbitrary folder for testing. Especially in cases where a flat globbing could resolve in overwriting of dlls from ref.

**Comment by rainersigwald** [comment]
I don't think we're doing this so I'm going to close it.
