### ISSUE TITLE
_CleanPackageFiles target fails sporadically when (re)building

### ISSUE THREAD

**Issue by wouterroos** [dotnet/msbuild#7465]
### Issue Description

When rebuilding our 80+ project solutions we sporadically get the following error on the `_CleanPackageFiles` target:

`MSB3061 Unable to delete file "C:\Projects\MyProject\src\MyProject\obj\MyPlatform\Debug\MyProject.MyPlatform.3.0.0-debug.nuspec". Access to the path 'C:\Projects\MyProject\src\MyProject\obj\MyPlatform\Debug\MyProject.MyPlatform.3.0.0-debug.nuspec' is denied.`

This issue happens for seemingly random projects in our solution.

### Steps to Reproduce

Execute the following MSBuild command until the issue presents itself (Build runs with `Configuration` set to `Debug` and `Platform` set to `any cpu` by default):

`msbuild MySolution.MyPlatform.sln /bl -t:Rebuild -m --restore`

The impacted projects have `IsPackable` and `GeneratePackageOnBuild` set to true and `PackageOutputPath` set to `$(RepositoryRootDirectory)nuget\nupkg\$(Configuration)\`. Furthermore, the projects have `TargetFrameworks` set to `net48;netcoreapp3.1;net6.0`.

The issue can also be reproduced by opening the solution in Visual Studio and rebuilding the solution. This yields more consistent results.

Additional information:

We have multiple solutions targeting the same projects but for a different platform so we use a `Directory.Build.props` file that modifies the following MSBuild variables to allow for everything to compile to a separate output folder (`BuildForPlatform` is set per project or in a nested Directory.Build.props file based on requirements and `MySolutionPlatform` is determined by the solution name):

```
<!-- BEGIN Sets project output paths for platform-specific projects -->
  <PropertyGroup Condition="'$(BuildForPlatform)'=='true'">
    <MSBuildProjectExtensionsPath>obj\$(MySolutionPlatform)</MSBuildProjectExtensionsPath>
    <BaseIntermediateOutputPath>obj\$(MySolutionPlatform)\</BaseIntermediateOutputPath>
    <BaseOutputPath>bin\$(MySolutionPlatform)</BaseOutputPath>
    <DefaultItemExcludes>$(DefaultItemExcludes);bin/**;obj/**</DefaultItemExcludes>
    <PackageId>$(MSBuildProjectName).$(MySolutionPlatform)</PackageId>
  </PropertyGroup>
  <!-- END -->
```

We build our solutions in parallel using the `-m` MSBuild switch or by setting `maximum number of parallel project builds` in Visual Studio.

### Expected Behavior

As happens sometimes, the solution will be rebuilt and all NuGet packages are generated as expected.

### Actual Behavior

Rebuilding one of the projects fails with the error mentioned above, causing a cascading failure for all projects depending on the project causing the issue. We've verified this behavior using both Visual Studio and the MSBuild command line. The issue happens more often when building using Visual Studio but we've also seen occurrences when using MSBuild, especially when building on our build server. 

### Analysis

I generated a `.binlog` file and did some analysis and the issue might be caused by the `_CleanPackageFiles` target running for each target framework during the inner build, which are built in parallel. This seems weird as the `Pack` is only executed once (after all inner builds are completed, which makes sense). I've submitted the binlog as a Visual Studio issue (see: https://developercommunity.visualstudio.com/t/Binlog-for-https:githubcomdotnetmsb/1691529?entry=myfeedback)

### Versions & Configurations

MSBuild version: `17.1.0.7609`
OS: `Windows 10 Enterprise 21H2`

**Comment by BenVillalobos** [comment]
MSBuild Team Triage: We believe this is an issue with NuGet. Your inner builds of Copper.Discovery.Interface are all trying to delete the nupkg and nuspec files.

The first one deletes the files
The second one gives the error
The third one doesn't see the files because they got deleted.

To the NuGet team: It sounds like these targets should clean these files in the outer build. That, or setting `TreatErrorsAsWarnings` to true when calling the delete task for this clean up operation.

**Comment by BenVillalobos** [comment]
This issue was moved to NuGet/Home#11710
