### ISSUE TITLE
MSBuild hangs and eventually times out for OOP builds queued from .NET 6 process running in VS apphost

### ISSUE THREAD

**Issue by AArnott** [dotnet/msbuild#7466]
### Issue Description

I have a .NET console app that uses the MSBuildLocator and executes out-of-proc builds using the MSBuild `BuildManager`. 
When my console app is executed or debugged from VS, this build hangs before it begins. About 2 minutes later the build fails with an exception about a failure to spawn and communicate with the child process.

The MSBUILDDEBUGCOMM log is here: [MSBuild_CommTrace_PID_115004.txt](https://github.com/dotnet/msbuild/files/8246257/MSBuild_CommTrace_PID_115004.txt)

@rainersigwald looked at this and gave me a workaround, which is to set the `UseAppHost` msbuild property to `false` in my project file.

**Comment by AArnott** [comment]
The workaround of setting `UseAppHost` is ineffective when the project builds as a dotnet CLI tool, since the `dotnet tool install` command creates a new apphost .exe.
So to solve that, I'm adding this to my Main method:

```cs
// HACKHACK: https://github.com/dotnet/msbuild/issues/7466 requires us to have dotnet.exe as our process name.
// Although we set UseAppHost in the project file, the "dotnet tool" installer creates an .exe stub for us,
// so we have to escape that by spawning dotnet.exe with our own managed assembly as an argument.
if (!string.Equals("dotnet", Path.GetFileNameWithoutExtension(Environment.ProcessPath)))
{
    Console.WriteLine("Redirecting to dotnet.exe...");
    ProcessStartInfo psi = new ProcessStartInfo("dotnet");
    psi.ArgumentList.Add(Assembly.GetExecutingAssembly().Location);
    foreach (string arg in args)
    {
        psi.ArgumentList.Add(arg);
    }

    Process? p = Process.Start(psi);
    Assumes.NotNull(p);
    await p.WaitForExitAsync();
    return p.ExitCode;
}

```

**Comment by Nirmal4G** [comment]
You can do what the `dotnet` and `AppHost` does internally using the `C` APIs from `hostfxr` lib but that may be overkill.

This calls for a `.NETLocator` similar to `MSBuildLocator`!
