### ISSUE TITLE
Command `dotnet publish ... returned a non-zero code: 1` without explanation

### ISSUE THREAD

**Issue by stdedos** [dotnet/msbuild#7514]
### Description

Command `dotnet publish ... returned a non-zero code: 1` without explanation

### Reproduction Steps

```
Step 16/16 : RUN dotnet publish -c release -o /app --no-restore -p:PublishReadyToRun=true -p:p:PublishTrimmed=true --runtime linux-x64 --self-contained
 ---> Running in 38a6ddde6bf1
Microsoft (R) Build Engine version 17.1.0+ae57d105c for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

The command '/bin/sh -c dotnet publish -c release -o /app --no-restore -p:PublishReadyToRun=true -p:p:PublishTrimmed=true --runtime linux-x64 --self-contained' returned a non-zero code: 1
```

### Expected behavior

Explain to me what's wrong _i.e. argument `-p:p:...` is perhaps a typo, did you mean `-p:...`?_

### Actual behavior

_See above_

**Comment by danmoseley** [comment]
MSBuild should error on /p:p:foo=bar because p:foo is an invalid property name.

The second bug is that dotnet.exe does not show parsing errors:
https://github.com/dotnet/sdk/issues/14499

**Comment by Forgind** [comment]
> @Forgind does your property logging PR address the invalid property name error?

Which property logging PR? Do you mean the environment-derived properties change? That doesn't have anything to do with this.

**Comment by baronfel** [comment]
I did, thank you for confirming :) I thought I remembered something related to parsing logging in there, but couldn't remember 100%.

**Comment by Forgind** [comment]
I tested out a slightly simplified form of this in the MSBuild repo:
```
dotnet publish -p:p:PublishTrimmed-true MSBuild.sln
Microsoft (R) Build Engine version 17.2.0-preview-22126-01+40f49cd8d for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

MSBUILD : error MSB1006: Property is not valid.
Switch: p:PublishTrimmed-true

For switch syntax, type "MSBuild -help"
```

That sounds to me like something is suppressing the output—MSBuild is producing a useful message, but something else rejects it. Is this an SDK issue @dsplaisted? Or maybe something docker-specific?

**Comment by danmoseley** [comment]
That's https://github.com/dotnet/sdk/issues/14499 right? It needs investigation but it's already logged

**Comment by Forgind** [comment]
Great, thanks for finding that!
