### ISSUE TITLE
Multiple Copy into statements in script cause sql project to fail building

### ISSUE THREAD

**Issue by Arentir** [dotnet/msbuild#7519]
### Issue Description
A SQL project fails to build if they are two "copy into" statements in a given script. The issue is seems to stem from the fact it cannot handle the WITH arguments if they are repeated. In this example, it will be FILE_TYPE.

### Steps to Reproduce
Open the sql project zipped here and try to build. 
[bugtest.zip](https://github.com/dotnet/msbuild/files/8419894/bugtest.zip)

To reproduce from scratch, create a SQL project with targetplatform Microsoft Azure SQL Datewarehouse (copy into is a synapse analytics feature) and add a new script with the following code
[sp_MultipleCopyinto.txt](https://github.com/dotnet/msbuild/files/8419907/sp_MultipleCopyinto.txt)

### Expected Behavior
To build successfully

### Actual Behavior
Failing with one error
"error MSB4018: The "SqlBuildTask" task failed unexpectedly."
"Error MSB4018: System.ArgumentException: An item with the same key has already been added. Key: File_Type"

### Analysis
Everything points to the inability of MSBuild to handle the with arguments. In the provided example FILE_TYPE is declared in the two copy into statement, leading to the error message above
I would get the same error if I try to have defined FILE_FORMAT, CREDENTIAL, etc.. 
If I only declare an argument once - example FILE_FORMAT in first copy into and CREDENTIAL in second copy into - then the issue disappears

### Versions & Configurations
Tried with both Visual Studio (msbuild version 16.10.2+857e5a733) and Azure data studio with same result.

**Comment by Forgind** [comment]
When a "task failed unexpectedly," that's an issue with the task, not with MSBuild. Can you file an issue [like this](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) and mention that it's an issue with sql (Microsoft.Data.Tools.Schema.Tasks.Sql)?
