### ISSUE TITLE
Official build continues to product Microsoft.NET.StringTools v1.0.0

### ISSUE THREAD

**Issue by mmitche** [dotnet/msbuild#7562]
The msbuild official build continues to build and report Microsoft.NET.StringTools v1.0.0, even though it was shipped to nuget.org back in May 2021.

- This confuses .NET's publishing infrastructure 
- This leads to the potential for msbuild to accidentally internally rely on changes to a NuGet package that can never be shipped.

The build should stop building this, and instead restore it from the shipped location.

**Comment by rainersigwald** [comment]
We should probably just bump its version number. IIRC Ladi had a reason to keep it at 1.0.0 but I don't remember it--do you, by chance, @rokonec?

**Comment by mmitche** [comment]
> We should probably just bump its version number. IIRC Ladi had a reason to keep it at 1.0.0 but I don't remember it--do you, by chance, @rokonec?

I'd version same as the rest of your binaries then, since otherwise you'll end up with multiple bands producing the same version.

**Comment by BenVillalobos** [comment]
> I'd version same as the rest of your binaries then, since otherwise you'll end up with multiple bands producing the same version.

Team Triage: We're leaning toward this decision.

**Comment by rokonec** [comment]
@rainersigwald I do not recall why Ladi preferred version 1.0.0
Maybe he plan to be used outside of internal .NET build as it is generic tool.
