### ISSUE TITLE
Passing an empty string to `RemoveDir` results in wiping the `C:\` drive contents

### ISSUE THREAD

**Issue by gotmachine** [dotnet/msbuild#7563]
Executing the following : 
```xml
<PropertyGroup>
  <MyPath></MyPath>
</PropertyGroup>
<RemoveDir Directories="$(MyPath)" />
```
on windows results in MSBuild happily wiping the contents of the `C:\` drive, with all the consequences you can imagine.

After experiencing this, I'm now gating all `RemoveDir` calls behind a `Condition="'$(MyPath)' != ''"`, but I feel this is something that should somehow be done by default...

Maybe abort and log an error if `string.IsNullOrWhiteSpace(directory.ItemSpec)` before calling https://github.com/dotnet/msbuild/blob/518c041f4511a6bc23eb40703b69a94ea46c65fd/src/Tasks/RemoveDir.cs#L107

**Comment by Nirmal4G** [comment]
This is bad. I always do this instinctively but not everyone does. I agree that this should be gated.

Also, MSBuild should always take relative or root to the volume as relative to project directory or a concept of an executing/current/working directory. There are taks and features that could benefit MSBuild having more constrained location.

**Comment by rainersigwald** [comment]
> Maybe abort and log an error if `string.IsNullOrWhiteSpace(directory.ItemSpec)` before calling
> 
> https://github.com/dotnet/msbuild/blob/518c041f4511a6bc23eb40703b69a94ea46c65fd/src/Tasks/RemoveDir.cs#L107

Yes, `RemoveDir` should absolutely do that.

**Comment by Nirmal4G** [comment]
Only null check might not be enough! Also, Is whitespace a valid path? If so, we should use `string.IsNullOrEmpty(directory.ItemSpec)` but before we do that.

On that note, can we add some untouchable directories (_like `C:\`, `%SystemRoot%\Windows\`, etc..._) to some sort of a blocklist and check against it and provide an error and abort. If we want to proceed deleting the blocked directories, an option (_like `Force` or "I know what I'm doing"_) could be provided!

OR even simpler solution is run MSBuild as ***restricted*** process to have these directories blocked by ACLs!? (_I don't even know if this is possible_)

I know this could be overkill but I've seen so many of these complaints in my lifetime as a developer that could at least warrant a discussion. 😇

**Comment by BenVillalobos** [comment]
I think the easiest solution is a null or empty check for now. Let's go with that and handle any future scenarios as they come 👍
