### ISSUE TITLE
Compile Warning(18744): File access preemption

### ISSUE THREAD

**Issue by kelicto** [dotnet/msbuild#7581]
**Version Used**: 

Visual Studio 2022(17.1.5)

**Steps to Reproduce**:

Screenshots should be clear.

**Expected Behavior**:

Happened.

**Actual Behavior**:

Shouldn't happen.

**Warning Screenshot**:

![Warning](https://user-images.githubusercontent.com/23723575/165211179-8eb0a779-ec42-4be4-8a6e-cd4818b2a138.png)

**Comment by kelicto** [comment]
Cleaning up the solution is one way to solve the problem, and if it can be improved, please consider optimizing it.

**Comment by BenVillalobos** [comment]
Can you provide a minimal project that reproduces this behavior? That would help us improve this scenario.
