### ISSUE TITLE
Custom serialization after BinaryFormatter Removal

### ISSUE THREAD

**Issue by Forgind** [dotnet/msbuild#7583]
Per the [BinaryFormatter deprecation schedule](https://github.com/dotnet/designs/blob/main/accepted/2020/better-obsoletion/binaryformatter-obsoletion.md#net-7-nov-2022), the use of BinaryFormatter in all first-party Microsoft code is deprecated in .NET 7, so we are planning for its eventual removal. MSBuild currently uses it for serializing custom `BuildEventArgs` and `ITaskItem`s. If you use that functionality, we want to know! Head over to https://github.com/dotnet/msbuild/discussions/7582 and let us know how you use it and why.

**Comment by baronfel** [comment]
I've locked this to encourage discussion on the linked discussion, where threads are supported, instead of on this announcement issue.

**Comment by Forgind** [comment]
This has probably been open long enough
