### ISSUE TITLE
`TargetFrameworkMonikerAssemblyAttributesPath` starts with a `.` and is a hidden file on Unix

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/msbuild#7603]
Here we define `TargetFrameworkMonikerAssemblyAttributesPath` to be something like:
`obj/Debug/.NETCoreApp,Version=v6.0.AssemblyAttributes.cs` on Mac

https://github.com/dotnet/msbuild/blob/e049bfe3dddb84270dec5fc1aaedc9664f77eb98/src/Tasks/Microsoft.Common.CurrentVersion.targets#L3513

~~since it starts with a dot it's a hidden file and I think existence check fails on it, so incrementality breaks and the target runs every time?~~

I think the file name should start with a regular letter than than a `.`, e.g. `Target.NetStandard...`

**Comment by jrdodds** [comment]
I did a quick test of Exists() on macOS with the following project file. I'm using zsh and I have a .zshrc file.
```
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
    <Target Name="Test">
        <Message Text="Found!" Condition="Exists('$(HOME)/.zshrc')"/>
    </Target>
</Project>
```
The message 'Found!' is displayed. It would appear that being hidden doesn't change the existence check.

**Comment by KirillOsenkov** [comment]
My apologies, I got terribly confused yesterday and it turned out that indeed incrementality and exists checks are not the problem :| It was PEBKAC. Sorry for the confusion.

The only real remaining issue is the fact that it's a hidden file, but as far as I can see this should be benign.

Feel free to close this bug if you feel the hidden file is not worth fixing.

**Comment by rainersigwald** [comment]
I wouldn't be opposed to rewiring it to `AssemblyAttributes.*.cs` instead of `*.AssemblyAttributes.cs`. But I don't know if it's worth much to do so.

**Comment by KirillOsenkov** [comment]
I'd say when in doubt use the "bigger fish to fry" argument
