### ISSUE TITLE
Build doesn't fail if you reference a .NET Framework library inside a .NET 6 library

### ISSUE THREAD

**Issue by adcloeshelle** [dotnet/msbuild#7637]
### Issue Description
The build succeeds if you add a .NET Framework project as a dependency of a .NET 6 library. I would have expected that should be forbidden.

### Steps to Reproduce
See the attached solution below. If you build the .NET 6 or .NET Standard library, the build still succeeds.

[TestImports.zip](https://github.com/dotnet/msbuild/files/8723183/TestImports.zip)

### Expected Behavior
The Build should fail and say you should not reference a .NET Framework library from a .NET 6 library

### Actual Behavior
The Build succeeds.

### Versions & Configurations
VS 2022 - 17.0.2

**Comment by lextm** [comment]
"Reference .NET Framework libraries from .NET Standard", a feature back in 2017, https://devblogs.microsoft.com/dotnet/announcing-net-core-2-0/

**Comment by Forgind** [comment]
Thanks for finding that @lextm. From that blog post, ".NET Core and .NET Standard projects can reference .NET Framework NuGet packages and projects." That sounds like this is expected. @adcloeshelle, why did you expect something different?

**Comment by adcloeshelle** [comment]
For example, if I add CryptSharpOfficial 2.1.0 to ClassLibraryStandard from my Sample Project above, I get the following warning:

ClassLibraryStandard.csproj : warning NU1701: Package 'CryptSharpOfficial 2.1.0' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETStandard,Version=v2.0'. This package may not be fully compatible with your project.

**Comment by Forgind** [comment]
Little tricky, but it's perfectly fine to reference a .NET Framework library from a .NET 6 library. We don't guarantee that it will work 100% of the time, hence the warning you saw, but it should work for most cases, so it would just hurt people to make it fully illegal. Thanks for proactively reaching out!

**Comment by adcloeshelle** [comment]
Any reason for showing a warning for NuGet packages but no warning for normal project references? I'd love a warning that we could turn into an error for project references for our solution.
