### ISSUE TITLE
Running dotnet/performance benchmark script with arm architecture fails for preview4.

### ISSUE THREAD

**Issue by dakersnar** [dotnet/msbuild#7643]
### Describe the bug
Running the benchmarks_monthly.py script for .NET preview 4 on an `arm64` machine with an `arm` configuration crashes.

### To Reproduce
> git clone https://github.com/dotnet/performance.git
> cd performance
> py .\scripts\benchmarks_monthly.py net7.0-preview4 --architecture arm

### Exceptions (if any)

`error MSB4061: The "GenerateResource" task could not be instantiated from "Microsoft.Build.Tasks.Core, Version=15.1.0.0, Culture=neutral, PublicKeyToken=...". Arm is not a supported architecture. [...\performance\src\benchmarks\micro\MicroBenchmarks.csproj]
[2022/05/11 11:15:59][INFO] ...\performance\tools\dotnet\arm\sdk\7.0.100-preview.4.22227.3\Microsoft.Common.CurrentVersion.targets(3257,5): error MSB4060: The "GenerateResource" task has been declared or used incorrectly, or failed during construction. Check the spelling of the task name and the assembly name. [...\performance\src\benchmarks\micro\MicroBenchmarks.csproj]`

### Further technical details
- The script installs the relevant .NET SDK upon running. In my run, it installed it into `performance\tools\dotnet\arm\sdk\7.0.100-preview.4.22227.3`.
- This bug has been reproduced on @adamsitnik's arm machine.

**Comment by gcerik** [comment]
I can confirm the issue with preview 4 - I was able to build without issues on preview 3

**Comment by rainersigwald** [comment]
@BenVillalobos can you take a look? Might be dotnet/msbuild#1293.

**Comment by dakersnar** [comment]
Update: this issue persists in preview5, specifically '7.0.100-preview.5.22276.3'.

**Comment by BenVillalobos** [comment]
I tried the repro and see `OSError: [WinError 216] This version of %1 is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher`.  Using `--architecture arm64` works fine.

What version of windows are you on as you run this? 

Other notes:

It installed the `-Version 7.0.100-preview.4.22227.3` sdk.

Windows version of my machine: 
<img width="265" alt="image" src="https://user-images.githubusercontent.com/4691428/173119125-3773ec29-6cd3-47a9-9aeb-b9b211b6d502.png">

**Comment by gcerik** [comment]
@BenVillalobos I had this issue on a Raspberry PI - with Raspberry OS 32 bit installed with the 64 bit kernel

**Comment by dakersnar** [comment]
@BenVillalobos Sorry for the delay. I'm using Windows 11 Enterprise, OS build: 22000.795.

**Comment by adamsitnik** [comment]
I can reproduce the issue with Preview5, but not with Preview7. I hope that it's gone for good ;)
