### ISSUE TITLE
ARM64 As A Valid PlatformTarget When Targeting not-net481

### ISSUE THREAD

**Issue by BenVillalobos** [dotnet/msbuild#7648]
Referenced comment in previous thread at https://github.com/dotnet/winforms-designer/pull/4303

```
// No target framework version restriction for buildPlatform x86 and amd64 as server process will run in
// emulation mode.
// But an arm64 .NET Framework process can only load version 4.8.1.
```
> On one hand I agree that this is true; logically you must target `net481` in order to validly have `<PlatformTarget>ARM64</PlatformTarget>`. On the other hand though MSBuild / .NET SDK will successfully build binaries when you target `net472`. Evidence being here: https://github.com/dotnet/roslyn/blob/main/src/Compilers/CSharp/csc-arm64/csc-arm64.csproj#L8-L11
@rainersigwald  FYI, not sure if this is something we should consider warning on or highlighting. It's a subtle mistake I made and didn't even realize it.
_Originally posted by @jaredpar in https://github.com/dotnet/winforms-designer/pull/4303#discussion_r876328399_

**Comment by jaredpar** [comment]
One issue though is that it's hard to build `net481`  compared to `net472`. As an example took a project currently building against `net472`, flipped it to `net481` and ended up with the following: 

> C:\Program Files\dotnet\sdk\7.0.100-preview.4.22252.9\Microsoft.Common.CurrentVersion.targets(1221,5): error MSB3644: The reference assemblies for .NETFramework,Ver   
sion=v4.8.1 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can downlo   
ad .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks [C:\Users\jaredpar\code\roslyn\src\Compilers\CSharp\csc-arm64\csc-arm64.csproj]

Think we'd likely want to correct that before implementing the warning.

**Comment by BenVillalobos** [comment]
> Think we'd likely want to correct that before implementing the warning.

Right, this is blocked on 481 availability.

**Comment by jaredpar** [comment]
Do we have an issue tracking that? I'm not even sure where that part of the stack ends up coming from.

**Comment by BenVillalobos** [comment]
@jaredpar oh interesting, I figured this was a generic `<Error` task in common.currentversion targets. Turns out it's coming from `GetReferenceAssemblyPaths`, which we own.

**Comment by BenVillalobos** [comment]
Decided internally to close this.
