### ISSUE TITLE
TreatAsLocalProperty doesn't work for SDK-style projects

### ISSUE THREAD

**Issue by ghogen** [dotnet/msbuild#7656]
Copied from doc issue https://github.com/MicrosoftDocs/visualstudio-docs/issues/6274 entered by @stpatrick2016:

When running msbuild from the command line and specifying property with -p, it overrides project properties. It is possible to cancel such behavior by setting TreatAsLocalProperty. It works correctly with the old csproj format but seems has no effect on projects with the new SDK format.

Tried that with VS2017 and property OutDir

**Comment by Forgind** [comment]
No surprise, but this is more specific than just SDK-style/not SDK-style:
```
C:\Users\forgind\Desktop\Archives\Bug-specific\7656>dotnet build 7656.csproj /t:ToPrint /p:Thing=other
Microsoft (R) Build Engine version 17.3.0-preview-22226-04+f15ed2652 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  All projects are up-to-date for restore.
  Thing is hello

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:00.57

C:\Users\forgind\Desktop\Archives\Bug-specific\7656>dotnet build 7656.csproj /t:ToPrint /p:Thing=other
Microsoft (R) Build Engine version 17.3.0-preview-22226-04+f15ed2652 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  All projects are up-to-date for restore.
  Thing is other

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:00.57
```

when the project is:
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net7.0</TargetFramework>
    <RootNamespace>_7656</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Thing>hello</Thing>
  </PropertyGroup>

  <Target Name="ToPrint">
    <Message Text="Thing is $(Thing)" Importance="high" />
  </Target>

</Project>
```

(With it having TreatAsLocalProperty="Thing" for the first case.)

**Comment by Forgind** [comment]
@stpatrick2016,
Can you provide a more detailed repro for this? Does it work in a recent version of MSBuild or only 2017? Were you setting OutDir in the entrypoint project? Were you importing it? Where did you check if its value had been overridden properly? I'm assuming you were building with VS, correct? Does it also repro for you from the command line?

**Comment by baronfel** [comment]
@nagilson Check this out! Looks like there's an MSBuild property that is related to the GlobalProperties situation we discovered on Friday's call.

**Comment by nagilson** [comment]
I have a consistent repro in this in the .NET SDK repo. I can confirm it's not any SDK-style project, but it definitely affects the SDK.

**Comment by nagilson** [comment]
nvm I'm bad and ez
