### ISSUE TITLE
MsBuild 17.2.1.25201 - ProduceReferenceAssembly not actually producing reference assembly

### ISSUE THREAD

**Issue by DoctorVanGogh** [dotnet/msbuild#7657]
### Issue Description
msbuild 17.2.1+ seems to no longer output reference assemblies into `refs`

### Steps to Reproduce
1. Have a minimal project (C# console project will do fine)
2. Add `<ProduceReferenceAssembly>true</ProduceReferenceAssembly>` to project
3. Invoke msbuild (either via command line or from visual studio)

Sample project:
[RefAssemblyDemo.zip](https://github.com/dotnet/msbuild/files/8793710/RefAssemblyDemo.zip)
Command line :
```
msbuild -t:restore -p:RestorePackagesConfig=true
msbuild
```

### Expected Behavior
Reference assemblies output to the "refs/" subdirectory in target directory. This *did* happen with previous msbuild versions.
The same command line on the same project will *work* as expected with msbuild  `16.11.1.47101` (from VS 2019), and *did* work with previous versions of  msbuild 17.(?) (whatever version that shipped with VS 2022 17.0 was fine, VS 17.2.x exhibits the issue).

### Actual Behavior
No reference assemblies in `refs`. 

### Analysis
Looking at the command line output, something subtle seems to have changed:
*working* (from msbuild 16.11.1.47101):
```
PrepareForBuild:
  Creating directory "bin\Debug\net472\".
  Creating directory "obj\Debug\net472\".
  Creating directory "***\RefAssemblyDemo\obj\Debug\net472\ref\".
  Creating directory "bin\Debug\net472\ref".
```
***not** working* (from msbuild 17.2.1.25201):
```
PrepareForBuild:
  Creating directory "bin\Debug\net472\".
  Creating directory "obj\Debug\net472\".
  Creating directory "***\RefAssemblyDemo\obj\Debug\net472\refint\".
  Creating directory "obj\Debug\net472\ref".
```

### Versions & Configurations
```
Microsoft (R) Build Engine version 17.2.1+52cd2da31 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

17.2.1.25201
```

**Comment by baronfel** [comment]
It sounds like you're hitting this [breaking change](https://docs.microsoft.com/en-us/dotnet/core/compatibility/sdk/6.0/write-reference-assemblies-to-obj) that we documented for .NET SDK 6.0.200 (which I believe maps to MSBuild 17.1). Can you take a look at that documentation and see if that fixes it for you?

**Comment by DoctorVanGogh** [comment]
Using `ProduceReferenceAssemblyInOutDir` as described in https://docs.microsoft.com/en-us/dotnet/core/project-sdk/msbuild-props#producereferenceassemblyinoutdir indeed restores the expected (old) behaviour.

It also maintains backwards compatibility with older msbuild (or Visual Studio) versions.

Thank you for that blazingly quick triage.
