### ISSUE TITLE
Task XslTransformation: How to specify XmlSpace.Preserve?

### ISSUE THREAD

**Issue by NMertsch** [dotnet/msbuild#7671]
### Issue Description
The MSBuild Task XslTransformation ([docs](https://docs.microsoft.com/en-us/visualstudio/msbuild/xsltransformation-task?view=vs-2022), [source](https://github.com/dotnet/msbuild/blob/main/src/Tasks/XslTransformation.cs)) always loads the provided XSLT file with `XmlSpace.Default`. I would like to use `XmlSpace.Preserve` instead.

### Steps to Reproduce
See [this project](https://github.com/NMertsch/msbuild-xsltransformation-issue). It contains an XSL stylesheet, an input XML file, and a dotnet project that generates two output files: one with the XslTransformation task, one in `Program.cs`. It also contains both output files so you can see the difference in GitHub.

You can clone the repo, delete the generated files, and run `dotnet run` to re-generate them.

### Expected Behavior
Both files have the same content.

### Actual Behavior
The MSBuild Task does not preserve whitespace and offers no way to change this behavior (at least none that I was able to find).

### Analysis
The desired behavior can be achieved by changing `new XPathDocument(reader)` to `new XPathDocument(reader, XmlSpace.Preserve)` in [this line](https://github.com/dotnet/msbuild/blob/bfd80ab1692721767c3fa8c0d4bcd35254489086/src/Tasks/XslTransformation.cs#L446).

I'm happy that `XmlSpace.Default` is the default. But I'd like to have an option to use `XmlSpace.Preserve` instead, e.g. via `<XslTransformation PreserveWhitespace="true" ... />`.

### Versions & Configurations
To reproduce this, I use the dotnet CLI without IDE.
- `dotnet --version`: 6.0.300
- OS: Windows 10 Pro (Version 10.0.19044 Build 19044)

**Comment by rainersigwald** [comment]
Team triage: Nice analysis! We would accept a new argument to the task that passes a bool down to that call.

**Comment by shadyalfred** [comment]
Are the parameters specified in the `.csproj` file automatically mapped to the `XslTransformation` class? Because I couldn't find how they're read, except in the test files where the properties of `XslTransformation` are manually assigned. Am I correct in guessing that only adding a boolean property (which changes the behavior of `XPathDocument`) to `XslTransformation` is enough? However, adding a new property to the `XslTransformation` class gives an error
> error RS0016: Symbol 'PreserveWhitespace.get' is not part of the declared API

**Comment by rainersigwald** [comment]
> Are the parameters specified in the `.csproj` file automatically mapped to the `XslTransformation` class? Because I couldn't find how they're read, except in the test files where the properties of `XslTransformation` are manually assigned. Am I correct in guessing that only adding a boolean property (which changes the behavior of `XPathDocument`) to `XslTransformation` is enough? 

That's correct; there is some [documentation on task invocation](https://docs.microsoft.com/visualstudio/msbuild/task-writing?view=vs-2022#how-msbuild-invokes-a-task) and if you want the details you might be interested in [`TaskExecutionHost.SetTaskParameters`](https://github.com/dotnet/msbuild/blob/3db83fdeb160404917b6bd3f4dd9e62338539a48/src/Build/BackEnd/TaskExecutionHost/TaskExecutionHost.cs#L325).

> However, adding a new property to the `XslTransformation` class gives an error
> 
> > error RS0016: Symbol 'PreserveWhitespace.get' is not part of the declared API
> 
> Update: fixed it by modifying the public API files

That was almost perfect; I'm making a suggestion in your PR.
