### ISSUE TITLE
How can we clear the caches of last build

### ISSUE THREAD

**Issue by jianyexi** [dotnet/msbuild#7676]
I have a custom msbuild target which can generate some cs files  from `.cadl` files and the generated files will be added to the compiler so that it can be compiled.  But every time, the code generation will clear the last generated files, due to the compiler caches , if some generated files in last build were renamed or deleted in current build, the compiler will report "some files not found", how can we solve this issue ?
I try to exclude the generated file before compiling , like `<Compile Remove="**/generated/**/*.cs" />`, but seems does not work

here is my custom build target : https://github.com/jianyexi/adl/blob/f74e9be533bf08a36b0fd221f755343cccd64a36/packages/cadl-msbuild-target/build/Microsoft.Cadl.MSBuild.targets#L63

**Comment by jianyexi** [comment]
In addition, we are using '<Project Sdk="Microsoft.NET.Sdk.Web">' and custom build target

**Comment by BenVillalobos** [comment]
> I try to exclude the generated file before compiling , like <Compile Remove="**/generated/**/*.cs" />

What target (if any) are you hooking this Remove into?

Also, the link to your custom build target doesn't work.

**Comment by jianyexi** [comment]
> > I try to exclude the generated file before compiling , like
> 
> What target (if any) are you hooking this Remove into?
> 
> Also, the link to your custom build target doesn't work.

the target is before 'CoreCompile'
I put it here:
```
<Target Name="CadlCompileCore">
    <ItemGroup>
      <CadlCompile Remove="@(CadlCompile)" Condition=" '%(CadlCompile.Compile)' != 'true' " />
    </ItemGroup>

    <CadlCompiler Condition=" '$(Language)' == 'C#' and '@(CadlCompile)' != '' "
                  Imports="%(CadlCompile.Imports)"
                  CadlInputPaths="@(CadlCompile)"
                  CadlCompilerPath="%(CadlCompile.CadlCompilerPath)"
                  ToolPath="%(CadlCompile.CommandPath)"
                  OutputDir="%(CadlCompile.OutputDir)"
                  OS="$(OS)"
                  Options="%(CadlCompile.Options)"
                  Emitters="%(CadlCompile.Emitters)" >
      <Output TaskParameter="GeneratedFiles" ItemName="_Cadl_GeneratedFiles"/>
    </CadlCompiler>
    
    <Message Text="cadl gernerated @(_Cadl_GeneratedFiles)" Importance="high"/>
    <ItemGroup>
      <Compile Remove="generated/**/*.cs" />
      <Compile Remove="@(_Cadl_GeneratedFiles)" MatchOnMetadata="Identity" MatchOnMetadataOptions="PathLike" />
      <Compile Include="@(_Cadl_GeneratedFiles)"  Watch="false" />
    </ItemGroup>
  </Target>

  <!-- Do cadl compilation by default in a C# project. In other types, the user invoke
       CadlCompile directly where required. -->
  <Target Name="_CadlCompile_BeforeCsCompile" BeforeTargets="CoreCompile" DependsOnTargets="CadlCompileCore" Condition=" '$(Language)' == 'C#' " />
```

**Comment by rainersigwald** [comment]
@jianyexi I think several of the problems you're encountering could be resolved by generating the files into a folder in the `obj` (`$(IntermediateOutputPath)`) directory, instead of next to the checked-in source. That is the standard approach for generated files.

What's happening now is that at evaluation time, before your target runs, the SDK globs all `**/*.cs` files that exist on disk, including the ones from the last run. Then you generate more, but the `<Compile Remove` in your target globs only the ones that exist on disk _at that time_, so any generated files that you deleted in your code generator would not be on the list to be removed.

**Comment by jianyexi** [comment]
Thanks for the response, is there any way to just skip or change the step of 'including the ones from the last run' when evaluating

**Comment by rainersigwald** [comment]
@jianyexi yes, via SDK properties you can change the files that are automatically discovered under the project; see [`DefaultItemExcludes`](https://docs.microsoft.com/dotnet/core/project-sdk/msbuild-props#defaultitemexcludes) for example.
