### ISSUE TITLE
CopyToOutputDirectory does not copy generated file

### ISSUE THREAD

**Issue by novelhawk** [dotnet/msbuild#7678]
### Issue Description

I have some configuration files set as `CopyToOutputDirectory = PreserveNewest`, I also have a target ("CopyDefaultConfiguration") that should run before the CopyToOutputDirectory  as it verifies that the file exists and otherwise it copies `filename.default` into `filename`.

I'm having problems generating the file before the copy is executed. I've found that if I set "Taget:BeforeTargets" to `Restore` it works as expected but I would like to execute it before build step as I'm not sure `Restore` is and will run everytime a build is initiated.

On the other hand if I set the BeforeTargets to any of those the file is not copied:
- BeforeBuild
- PrepareForBuild
- GetCopyToOutputDirectoryItems

I believe MSBuild checks if the file exists before those targets and although it exists before the files are copied its skipped because MSBuild thinks it does not exists.

Is there a target I can run before so that I can copy the default file or am I forced to copy to the output directory with `Copy`?

### Steps to Reproduce
```xml
<ItemGroup>
  <None Update=".runsettings" CopyToOutputDirectory="PreserveNewest" />
</ItemGroup>

<Target Name="CopyDefaultConfiguration" BeforeTargets="BeforeBuild">
  <ItemGroup>
    <DefaultRunSettings Include="$(ProjectDir)/.runsettings.default" />
  </ItemGroup>
  <Copy SourceFiles="@(DefaultRunSettings)" DestinationFiles="@(DefaultRunSettings-&gt;Replace('.default', ''))" Condition="!Exists('$(ProjectDir)/.runsettings')" />
  <!-- <Copy SourceFiles="$(ProjectDir)/.runsettings" DestinationFolder="$(OutDir)" />This works -->
</Target>
```

1. Create a project and add a `.runsettings.default` file.
2. Include the lines above in the `.csproj` file
3. Verify that `.runsettings` does not exist
4. Execute `dotnet build`

### Expected Behavior
The file `.runsettings` gets copied to the output directory.

### Actual Behavior
The file is not copied to the output directory

### Analysis
https://github.com/dotnet/msbuild/blob/a2df02e6af1ed33882f36932ac2111cc98591dff/src/Tasks/Microsoft.Common.CurrentVersion.targets#L5088-L5112

https://github.com/dotnet/msbuild/blob/a2df02e6af1ed33882f36932ac2111cc98591dff/src/Tasks/Microsoft.Common.CurrentVersion.targets#L5035

I believe `_SourceItemsToCopyToOutputDirectory` does not contain `.runsettings`

### Versions & Configurations

```
$ msbuild -version
Microsoft (R) Build Engine versione 17.1.0+ae57d105c per .NET Framework
Copyright (C) Microsoft Corporation. Tutti i diritti sono riservati.

17.1.0.7609
```
```
$ dotnet --version
6.0.300
```

**Comment by BenVillalobos** [comment]
Hey! I did a quick writeup on why this is happening, and a solution for this scenario. Let me know if this helps, and if anything could be clearer.

https://gist.github.com/BenVillalobos/c671baa1e32127f4ab582a5abd66b005

**Comment by novelhawk** [comment]
I see. Thanks.
