### ISSUE TITLE
exit code -1 thrown when got "error" or "warning" word in the end of the test title.

### ISSUE THREAD

**Issue by Imperfectwow** [dotnet/msbuild#7682]
### Issue Description
We run our test in CI using msbuld.exe and PowerShell script that triggers the UITest we use the Playwright test framework.
we found an issue when the word "error" or "warning" was present at the end of the test title. we exit with error code -1 which is failing our job in Gitlab CI.

### Steps to Reproduce

in order to reproduce the issue attached two files.
1. run command ` .\MSBuild.exe -target:RunAutomationPlaywrightTests D:\projects\sro4\testSRO.xml`  from ps within the the folder that contains msbuild.exe. (screenshot of results attached)
1.1 in this way we run our test in CI, basically we trigger our test through MSBuild.exe testSRO.xml inside has a target of _RunAutomationPlaywrightTests_ that points to ps script.

2. To verify that issue is related specifically to MSBuild I run tests only with the ps script, without using MSBuild.exe. (screenshot attached)
3. running tests with MSBuild - https://share.getcloudapp.com/E0uyE6Zr
4.  running tests only with ps script without MSBuild - https://share.getcloudapp.com/Koujem1K
5. example of test title that causes the error.
img -https://share.getcloudapp.com/8Lu0w4Dv

### Expected Behavior

* the error code 1 will be thrown when the test ended with error, and 0 when the test passed 

### Actual Behavior

*  when the word "error" is present at the end of the test title, the exec command is finished with code -1.

### Versions & Configurations
* MSBuild 16.0
*   OS: Windows 11
* playwright 1.22.2

**Comment by rainersigwald** [comment]
This is an intentional design of the `Exec` task. You can set its parameter [`IgnoreStandardErrorWarningFormat`](https://docs.microsoft.com/visualstudio/msbuild/exec-task) to avoid the behavior, or set `CustomErrorRegularExpression` to be specific to your tool.
