### ISSUE TITLE
Message: Property "MSBildToolsVersion' is not defined

### ISSUE THREAD

**Issue by kelicto** [dotnet/msbuild#7691]
### Describe the bug
Opening the project file will show underline

### To Reproduce
1. Unload someone target project.
2. Open the csporj on visual studio.

### Screenshots
![image](https://user-images.githubusercontent.com/23723575/167529398-21bb3ee4-b5e0-4813-aaef-7d1ecba98f98.png)

**Comment by kelicto** [comment]
NET Framework traditional project documentation structure description file, not some new structure type of documentation. You can create a normal project type like console and I think you can see the problem.

**Comment by BenVillalobos** [comment]
Do you have any visual studio extensions installed?

**Comment by Nirmal4G** [comment]
No, I'm not seeing this in a clean install of VS or even in my own setup which has a bunch of MSBuild custom extensions.
