### ISSUE TITLE
Support disabling node reuse with an msbuild property

### ISSUE THREAD

**Issue by jeromelaban** [dotnet/msbuild#7693]
### Issue Description
When developing tasks and testing those in the same solution, msbuild reused nodes lock the output of file in the original task's project output location.

The only known way to avoid this is to have `/nr:false`, but doing so from visual studio does not seem possible.

Would it be possible to have an msbuild property to disable the node reuse for the "current" node (whatever it means for the msbuild runtime) so the files get unlocked at the end?

The issue is similar to https://github.com/dotnet/msbuild/issues/5385

### Versions & Configurations
17.3 Preview 1

**Comment by BenVillalobos** [comment]
I'm not sure of a way to do this from VS, but a temporary workaround could be to set `MSBUILDDISABLENODEREUSE` to 1.

From a developer command prompt:
`set MSBUILDDISABLENODEREUSE=1`
`devenv <your-project>`

**Comment by rainersigwald** [comment]
Team triage: we don't plan to do this, because we're planning to fix the underlying issue #6461. For now, setting that environment variable is probably your best bet.
