### ISSUE TITLE
Static graph respect only first ProjectReference for same project

### ISSUE THREAD

**Issue by iskiselev** [dotnet/msbuild#7694]
### Issue Description
Only first ProjectReference for same project respected by isolated build.

### Steps to Reproduce
I try to play with static graph and isolated build using example from https://github.com/dotnet/msbuild/blob/main/documentation/specs/static-graph.md#examples

`Referenced\Referenced.csproj`:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <UnusualOutput>Configuration\Unusual.txt</UnusualOutput>
  </PropertyGroup>

  <Target Name="UnusualThing" Returns="$(UnusualOutput)" />
</Project>
```

`Referencing\Referencing.csproj`:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Referenced\Referenced.csproj" />
  </ItemGroup>

  <Target Name="GetUnusualThing" BeforeTargets="BeforeBuild">
    <MSBuild Projects="..\Referenced\Referenced.csproj"
             Targets="UnusualThing">
      <Output TaskParameter="TargetOutputs"
              ItemName="Content" />
    </MSBuild>
  </Target>
</Project>
```

As example does not suggest steps to fix it to be compatible with isolated builds, let's do it. Let's suppose that `Referencing.csproj` need assembly reference to `Referenced.csproj` .

First we need add:
```
  <ItemGroup>
    <ProjectReferenceTargets Include="GetUnusualThing" Targets="UnusualThing"/>
  </ItemGroup>
```
We also need to duplicate ProjectReference, one will be used for reference output assembly, another one should provide dependency for static graph on UnusualThing:
```
    <ProjectReference Include="..\Referenced\Referenced.csproj" Targets="UnusualThing" ReferenceOutputAssembly="false" />
    <ProjectReference Include="..\Referenced\Referenced.csproj"  />
```

It will fail (`dotnet msbuild Referencing\Referencing.csproj -graph -isolate`). It is possible to fix if we express it in next form:
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Referenced\Referenced.csproj" Targets="Build;UnusualThing" ReferenceOutputAssembly="false" />
    <ProjectReference Include="..\Referenced\Referenced.csproj" Targets="Build"  />
    <ProjectReferenceTargets Include="GetUnusualThing" Targets="UnusualThing"/>
  </ItemGroup>

  <Target Name="GetUnusualThing" BeforeTargets="BeforeBuild">
    <MSBuild Projects="..\Referenced\Referenced.csproj"
             Targets="UnusualThing">
      <Output TaskParameter="TargetOutputs"
              ItemName="None" />
    </MSBuild>
  </Target>
</Project>
```
### Expected Behavior
Next should work:
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Referenced\Referenced.csproj" Targets="UnusualThing" ReferenceOutputAssembly="false" />
    <ProjectReference Include="..\Referenced\Referenced.csproj" />
    <ProjectReferenceTargets Include="GetUnusualThing" Targets="UnusualThing"/>
  </ItemGroup>

  <Target Name="GetUnusualThing" BeforeTargets="BeforeBuild">
    <MSBuild Projects="..\Referenced\Referenced.csproj"
             Targets="UnusualThing">
      <Output TaskParameter="TargetOutputs"
              ItemName="None" />
    </MSBuild>
  </Target>
</Project>
```

**Comment by BenVillalobos** [comment]
@dfederm when you have a chance could you take a look at this?

**Comment by dfederm** [comment]
Yup, I'll look at this.

**Comment by iskiselev** [comment]
@dfederm, my goal was to create target in Referencing.csproj that will call into some target of Referenced.csproj and will get access to the return value - so that `Configuration\Unusual.txt` value returned from `Referenced.csproj`  `UnusualThing` target` will be available in the build of `Referencing.csproj`. I don't want to call `UnusualThing` for all `ProjectReference` that `ProjectReferenceTargetsForBuild` will do.
I only try to understand how I can give graph build information, that `Referencing.csproj->GetUnusualThing` has dependency to `Referenced.csproj->UnusualThing`. I don't know yet if the fix solved it or not.
