### ISSUE TITLE
MSBuild no longer "just works" with solutions targeting `Any CPU`

### ISSUE THREAD

**Issue by tannergooding** [dotnet/msbuild#7711]
### Issue Description

Starting with .NET 7 Preview 5, attempting to run `dotnet build` for a solution that has a `Debug|Any CPU` configuration no longer works.

### Steps to Reproduce
1. Clone https://github.com/terrafx/terrafx.interop.windows
2. Run `dotnet build`

### Expected Behavior

The build completes succesfully.

### Actual Behavior

```
> dotnet build
MSBuild version 17.3.0-preview-22306-01+1c045cf58 for .NET
.\TerraFX.Interop.Windows.sln.metaproj : error MSB4126: The specified solution configuration "Debug|x64" is invalid. Please specify a valid solution configuration using the Configuration and Platform properties (e.g. MSBuild.exe Solution.sln /p:Configuration=Debug /p:Platform="Any CPU") or leave those properties blank to use the default solution configuration. [.\TerraFX.Interop.Windows.sln]
```

### Analysis

Possibly related to https://github.com/dotnet/msbuild/pull/7511

### Versions & Configurations

```
> dotnet --version
7.0.100-preview.5.22307.18
```

**Comment by BenVillalobos** [comment]
We initially thought this might have been related to SetPlatform, but that doesn't look to be the case since `EnableDynamicPlatformResolution` is not set anywhere in the repo. Unassigning myself for now

**Comment by BenVillalobos** [comment]
@v-codyguan Could you reproduce this error and provide binlogs of a working build and failing build (pre-preview 5 and preview 5). Thanks!

**Comment by tannergooding** [comment]
> Our biggest question about this is whether or not it's a regression.

This is, to me, a regression. Targeting "Any CPU" has been the default for solutions created by VS going back to .NET Framework and building those solutions using `dotnet build` has been possible since at least `.NET Core 2.0`.

A separate repro is the following, showing that `dotnet new sln` defaults to "Any CPU" and building such a solution is now broken by default:
```
mkdir tmp
cd tmp
dotnet new sln
dotnet new console
dotnet sln add .\tmp.csproj
dotnet build
```

**Comment by rainersigwald** [comment]
@tannergooding I don't repro. Can you share a binlog (offline via Teams is fine with me)?

```sh-session
❯ dotnet new sln
The template "Solution File" was created successfully.


S:\play\tmp
❯ dotnet new console
The template "Console App" was created successfully.

Processing post-creation actions...
Restoring S:\play\tmp\tmp.csproj:
  Determining projects to restore...
  Restored S:\play\tmp\tmp.csproj (in 90 ms).
Restore succeeded.



S:\play\tmp via .NET v7.0.100-preview.6.22352.1 🎯 net7.0
❯ dotnet sln add .\tmp.csproj
Project `tmp.csproj` added to the solution.

S:\play\tmp via .NET v7.0.100-preview.6.22352.1 🎯 net7.0
❯ dotnet build
MSBuild version 17.3.0-preview-22329-01+77c72dd0f for .NET
  Determining projects to restore...
  All projects are up-to-date for restore.
C:\Program Files\dotnet\sdk\7.0.100-preview.6.22352.1\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.RuntimeIdentifierInf
erence.targets(219,5): message NETSDK1057: You are using a preview version of .NET. See: https://aka.ms/dotnet-support-
policy [S:\play\tmp\tmp.csproj]
  tmp -> S:\play\tmp\bin\Debug\net7.0\tmp.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:02.82
```

**Comment by tannergooding** [comment]
*sigh*, this is because `vcvarsall.bat` is getting run on my machine since I frequently work with C++ as well. That sets `Platform = x64` as an environment variable and breaks MSBuild here -.-

I don't remember seeing this before recently and AFAIK haven't changed anything with regards to when `vcvarsall.bat` gets run, but that appears to be the issue. `InheritedEnvironmentStateBugs++`

**Comment by rainersigwald** [comment]
@Forgind looking through the log shared offline found a bug in the env-var-skipping change: we didn't log the `PLATFORM` env var even though it was used in evaluation of the solution metaproject. Can you add that case to tests?

**Comment by BenVillalobos** [comment]
Team Triage: This is part of the documented environment variable behavior, we'll figure out the logging to make it clear.
