### ISSUE TITLE
Build on s390x now fails with System.PlatformNotSupportedException

### ISSUE THREAD

**Issue by uweigand** [dotnet/msbuild#7729]
### Issue Description

As of .NET7 preview5, attempting to use msbuild on an linux-s390x host now fails with:
```
MSBuild version 17.3.0-preview-22306-01+1c045cf58 for .NET
MSBUILD : error MSB1025: An internal failure occurred while running MSBuild.
System.PlatformNotSupportedException: S390x is not a supported architecture.
   at Microsoft.Build.Shared.XMakeAttributes.GetCurrentMSBuildArchitecture()
   at Microsoft.Build.BackEnd.NodeProviderOutOfProc.CreateNodes(Int32 nextNodeId, INodePacketFactory factory, Func`2 configurationFactory, Int32 numberOfNodesToCreate)
   at Microsoft.Build.BackEnd.NodeManager.AttemptCreateNode(INodeProvider nodeProvider, NodeConfiguration nodeConfiguration, Int32 numberOfNodesToCreate)
   at Microsoft.Build.BackEnd.NodeManager.CreateNodes(NodeConfiguration configuration, NodeAffinity nodeAffinity, Int32 numberOfNodesToCreate)
   at Microsoft.Build.Execution.BuildManager.PerformSchedulingActions(IEnumerable`1 responses)
   at Microsoft.Build.Execution.BuildManager.HandleNewRequest(Int32 node, BuildRequestBlocker blocker)
   at Microsoft.Build.Execution.BuildManager.ProcessPacket(Int32 node, INodePacket packet)
   at Microsoft.Build.Execution.BuildManager.<>c__DisplayClass78_0.<Microsoft.Build.BackEnd.INodePacketHandler.PacketReceived>b__0()
   at Microsoft.Build.Execution.BuildManager.ProcessWorkQueue(Action action)
```

### Steps to Reproduce

To reproduce, you need a dotnet SDK hosted natively on linux-s390x.  While this is not a platform supported by Microsoft and there are no pre-built binaries, it is a community-supported platform in the runtime and other packages, and we are able to build a native SDK since .NET6; it is e.g. provided by Red Hat as part of RHEL8 on s390x.

Note that tiny "hello world" programs actually still build; but attempting to build a large project (like the runtime repository itself) shows the error.  I assume this is because the error only triggers in the code path where multiple build nodes are spawned, but I'm not completely certain about the specific triggers.

### Expected Behavior

Build completes successfully.

### Actual Behavior

`System.PlatformNotSupportedException: S390x is not a supported architecture.`

### Analysis

In the past, msbuild used to work fine on our platform even without having any platform-specific support code anywhere in the msbuild sources.  However, as of a recent commit, this is no longer true.  https://github.com/dotnet/msbuild/pull/7550  (@BenVillalobos @rainersigwald) added an explicit check in `GetCurrentMSBuildArchitecture` causing execution to abort if the current architecture is anything but Intel or ARM.

We really need to be able to continue using msbuild on s390x in order to offer continued support for .NET7 and later on our platform.  I'd be happy to work on a fix, but I'd appreciate guidance on the correct approach here.  Should we make msbuild explicitly aware of s390x as a platform throughout?   Or should msbuild just handle "unknown" architectures without aborting, as it used to?

FYI @janani66 @Sapana-Khemkar - this problem will also affect PowerPC as another community-supported platform.

FYI @directhex @steveisok @crummel

**Comment by uweigand** [comment]
> As of .NET7 preview5, attempting to use msbuild on an linux-s390x host now fails with:

Small update: I just noticed that the problem already appears with preview4 as well.  preview3 still works.

**Comment by rainersigwald** [comment]
> Should we make msbuild explicitly aware of s390x as a platform throughout? Or should msbuild just handle "unknown" architectures without aborting, as it used to?

I lean toward the latter on .NET Core at least for the case where we're just launching "another of the same". We can't have, for example, an x64 taskhost on S390x, but that's not likely to be relevant in most cases.

@BenVillalobos what do you think?

**Comment by BenVillalobos** [comment]
Created https://github.com/dotnet/msbuild/pull/7731 to fall back to the original logic.

**Comment by uweigand** [comment]
Thanks!   I've re-build my s390x dotnet SDK (.NET7 preview4) with the above patch included, and this does fix the problem for me.  The resulting msbuild is once again able to sucessfully complete a native build of the full dotnet runtime repo on s390x.
