### ISSUE TITLE
Release 17.3

### ISSUE THREAD

**Issue by Forgind** [dotnet/msbuild#7749]
- [x] When VS main snaps to `17.4`, create `vs17.3` branch
- [x] Create darc channel for `VS 17.4` if it doesn't already exist \
`darc add-channel --name "VS 17.4"`
- [x] Ping internal "First Responders" Teams channel to get the new channel made available as a promotion target
- [x] Associate the next release branch with the next release channel \
`darc add-default-channel  --channel "VS 17.4" --branch vs17.4 --repo https://github.com/dotnet/msbuild`
- [x] Remove the `main` to old release channel default channel \
`darc delete-default-channel --repo https://github.com/dotnet/msbuild --branch main --channel "VS 17.3"`
- [x] Associate the `main` branch with the next release channel \
`darc add-default-channel  --channel "VS 17.4" --branch main --repo https://github.com/dotnet/msbuild`
- [x] Check subscriptions for the current channel `VS 17.3` and update as necessary (for instance, SDK's `main` branch should usually be updated \
`darc get-subscriptions --exact --source-repo https://github.com/dotnet/msbuild --channel "VS 17.3"`\
Update channel `VS 17.3` to `VS 17.4` for the sdk main subscription\
`darc update-subscription --id 5480c5ca-4fa6-4d8a-1987-08d9d606f30d`
- [x] Ensure that the current release channel `VS 17.3` is associated with the correct release branch\
`darc get-default-channels --source-repo https://github.com/dotnet/msbuild --branch vs17.3`
- [x] Fast-forward merge the correct commit (the one that is currently inserted to VS main) to the `vs17.3` branch \
`git push upstream 797fd829a374a880f63fd4eea4ea6990404c48f4:refs/heads/vs17.3`
- [x] Fix OptProf data flow for the new vs17.3 branch
- [x] Update the [release-branch insertion release definition](https://dev.azure.com/devdiv/DevDiv/_releaseDefinition?definitionId=2153&_a=definition-variables) to have `InsertTargetBranch` `rel/d17.3`.
- [x] Prepare final branding PR for `vs17.3` but ⚠️ DO NOT MERGE IT YET ⚠️ #
- [x] Promote `unshipped` public API to `shipped` in `main` #7510 
      1. `Get-ChildItem -r src/PublicAPI.*.txt | Clear-Content`
      2. Open MSBuild.sln in Visual Studio, let it settle
      3. Find a green squiggle for the analyzer and fix all in solution
      4. `Get-ChildItem -r PublicAPI.Unshipped.txt | % { Move-Item -Force -Path $_ (Join-Path $_.Directory.FullName "PublicAPI.Shipped.txt") && New-Item $_ }`
- [x] Create 17.4 branding PR, including public API change #7501, #7510
- [x] Merge 17.4 branding PR
- [x] Prepare QB-mode bug for final branding insertion in internal VS repo
- [x] Update [internal "create VS PR for insertion"](https://dev.azure.com/devdiv/DevDiv/_releaseDefinition?definitionId=2153&_a=definition-variables) release to point to the new VS release branch by default
- [x] Merge final branding to `vs17.3` branch
- [x] Get QB approval
- [x] Merge to VS
- [x] ASAP after release, push packages to nuget.org (not currently automated, contact dnceng)
- [x] Update `main` subscriptions to the new channel (this can be done after release) \
`darc get-subscriptions --exact --target-repo https://github.com/dotnet/msbuild --target-branch main`
- [x] Create the 17.3 release (https://github.com/dotnet/msbuild/releases/tag/v17.3.1)

**Comment by admalledd** [comment]
Is there a timeline on the Nuget updates? If I am following correctly VS updated to 17.3 and netcore SDK 6.0.400 uses 17.3, however the packages are not yet on Nuget. I see release tag https://github.com/dotnet/msbuild/releases/tag/v17.3.0 but no https://www.nuget.org/packages/Microsoft.Build#versions-body-tab (and related packages)

**Comment by Forgind** [comment]
I think we can release 17.3 now? It's historically been a very manual process. I've been trying to automate it so we just hit one button, and it publishes to NuGet, but that isn't working yet. Sorry for the delay!
