### ISSUE TITLE
[REGRESSION] After upgrading to VS 17.2.5 the MSBuildDebugEngine environment variable is no longer respected.

### ISSUE THREAD

**Issue by MarkKharitonov** [dotnet/msbuild#7752]
## Visual Studio Version
17.2.5

## Summary
Setting MSBuildDebugEngine and MSBUILDDEBUGPATH does not produce the same effect as in VS 17.1.x, namely no binary logs no text files are produced at all.

## Steps to Reproduce

1. Set the aforementioned env variables
2. Open devenv from the console where the env is updated.
3. Build a project

## Expected Behavior
Binary logs and some text files are produced in the folder specified by MSBUILDDEBUGPATH 

## Actual Behavior
No files are produced.

## User Impact
Unable to troubleshoot VS build issues

**Comment by Forgind** [comment]
I can see what's happening here. I made a change to add fallbacks in case we couldn't write to the directory you specified, but it didn't make the directory if it wasn't there, and it didn't just write the logs. I'll make a PR soon.

**Comment by MarkKharitonov** [comment]
Much appreciated.
