### ISSUE TITLE
msbuild does not "recover" from slowdowns

### ISSUE THREAD

**Issue by kasperk81** [dotnet/msbuild#7757]
when i build runtime libraries, after quickly building 50 or so libraries, msbuild slows down and doesn't recover the speed it initially possessed for rest of the build.

reproduction steps:

```sh
# clone dotnet/runtime on linux

# first build native prerequisite
./build.sh clr+libs.native

# then build libs and notice how the build slows down after a first couple of
# libraries are built (and never recovers the speed)
./build.sh libs.src
```

**Comment by rainersigwald** [comment]
Can you please collect a trace of the build by installing [`dotnet-trace`](https://docs.microsoft.com/dotnet/core/diagnostics/dotnet-trace) and running your repro with

```
dotnet trace collect --providers Microsoft-Build -- ./build.sh libs.src
```

? That should collect perf information using [our events](https://github.com/dotnet/msbuild/blob/main/documentation/specs/event-source.md).

**Comment by kasperk81** [comment]
docs say:

> **Note**
>
>Using this option monitors the first .NET 5 process that communicates back to the tool, which means if your command launches multiple .NET applications, it will only collect the first app. Therefore, it is recommended you use this option on self-contained applications, or using the dotnet exec <app.dll> option.

since `./build.sh libs.src` invokes `dotnet` internally multiple, it doesn't work. i didn't find a "follow child" option, provided by similar tools; `strace -f` or gdb (all versions) and lldb (version 14 onward) `follow-fork-mode` option.

@hoyosjs

**Comment by hoyosjs** [comment]
That's good feedback, but sadly I don't think there's a provision for that. I opened https://github.com/dotnet/diagnostics/issues/3175 to discuss the issue. @rainersigwald, when a build shells out using the MSBuild task, is there a way to get an equivalent invocation from the binlog such that `dotnet exec msbuild` could reproduce the issues in a single instance?

**Comment by rainersigwald** [comment]
No, unfortunately MSBuild is multi-process by design and while you can build with `-m:1` to avoid that, it dramatically alters the perf characteristics of the build so it's probably not something that would be helpful here.

A binlog might have sufficient information to observe and possibly troubleshoot the slowdown, though.

**Comment by kasperk81** [comment]
@rainersigwald, here is `artifacts/log/Debug/Build.binlog` from `./build.sh clr+libs --binarylog`: https://github.com/kasperk81/runtime/releases/download/msbuild_binlogs/Build.binlog

weirdly enough, the total duration is smaller than core compile task alone:

![image](https://user-images.githubusercontent.com/83082615/178055683-a36bfb55-7d27-44b7-bd68-8d9cdec40292.png)

**Comment by kasperk81** [comment]
> nothing is jumping out at me

ok, in that case, we can close this. it just always feels like after quickly building couple of libraries, the build slows down then it continues on degraded speed. it is probably tied to project-to-project dependency graph; the leaf nodes build quicker than the others.
