### ISSUE TITLE
ngen failure in VS on MSBuildTaskHost.exe

### ISSUE THREAD

**Issue by rainersigwald** [dotnet/msbuild#7793]
Just happened to catch this in a scrollback:

```
Failed to load dependency Microsoft.NET.StringTools.net35 of assembly MSBuildTaskHost, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a because of the following error : The system cannot find the file specified. (Exception from HRESULT: 0x80070002)
```

I wonder if this line needs to specify that it should be in the context of `MSBuildTaskHost.exe.config` not `devenv.exe.config`?

https://github.com/dotnet/msbuild/blob/c1b61ebeaa0f77d1382c6a0734024557ecf255c3/src/Package/MSBuild.VSSetup/files.swr#L177

**Comment by MichalPavlik** [comment]
It seems setup sets `vsn.exe.config` as default config file. It's weird that config for the specified exe (when exists) is overridden by vsn unless someone explicitly configure it in `swr`.
