### ISSUE TITLE
eng/Packages.props has hardcoded package versions

### ISSUE THREAD

**Issue by lbussell** [dotnet/msbuild#7794]
.NET Source-Build relies on overriding package version properties to build projects with the latest versions of all dependencies. Using hardcoded package versions (e.g. `6.0.0` instead of `SystemCollectionsImmutableVersion`), we end up pulling prebuilts from the internet. The proper solution is to declare properties for package versions in `eng/Versions.props`, and reference those properties from `eng/Packages.props`. The proper format for the properties is the full package version name without periods followed by "Version", some of the dependencies in this file already follow that pattern.

https://github.com/dotnet/msbuild/blob/c1b61ebeaa0f77d1382c6a0734024557ecf255c3/eng/Packages.props#L13-L29

**Comment by rainersigwald** [comment]
Is this the kind of thing that should be caught in our source-build CI leg?

Does this mean we can't use Dependabot to keep references up to date as dnceng has advised us in the past?

For `eng/Packages.props` I have no problem with moving to versions but for the stuff that we want to keep updated I'd really like automation to keep that updated.

**Comment by lbussell** [comment]
Fixed with https://github.com/dotnet/msbuild/pull/7809
