### ISSUE TITLE
How soon the problem with nodes will be solved?

### ISSUE THREAD

**Issue by INTERNALINTERFERENCE** [dotnet/msbuild#7801]
https://github.com/dotnet/msbuild/pull/7387
The commit got into the master 10 days ago, but it doesn't seem to be in the dotnet master, because I still have to open visual studio with special parameters:
```
From a developer command prompt:
set MSBUILDDISABLENODE = 1
```

**Comment by rainersigwald** [comment]
That PR should ship with Visual Studio 17.3, starting in the next released preview, which will be released soon.
