### ISSUE TITLE
WriteCodeFragment can be modernized to use the value of ImplicitUsings for writing code fragments.

### ISSUE THREAD

**Issue by AraHaan** [dotnet/msbuild#7806]
Since the .NET 6 SDK's ``ImplicitUsings`` was added for global usings support for C# projects. I am filing this issue here for my work on an pull request to change that.

Note: The PR still needs some changes to msbuild files to make it all work since I made a new parameter (ironically it's named ``ImplicitUsings``) as required (might be a slight breaking change that can be reviewed to make it less breaking).

Due to the nature of how breaking this might be, It might not be possible to put it in any .NET 6 servicing releases (for now).

**Comment by AraHaan** [comment]
After thinking about it might, you might be right with this but it would have to only request this when targeting an .NET TargetFramework that allows implicit usings.

**Comment by Forgind** [comment]
Closing per https://github.com/dotnet/msbuild/pull/7807#issuecomment-1205480652
