### ISSUE TITLE
MSBuild task returned false but did not log an error

### ISSUE THREAD

**Issue by Forgind** [dotnet/msbuild#7862]
@jordi1215 showed me that the GenerateDepsFile task failed. It had presumably been invoked via an MSBuild task invocation, as it also logged two "MSBuild task returned false but did not log an error" errors. Before logging that error, we should ensure that no task invoked as a result of executing the current task logged an error.

**Comment by rainersigwald** [comment]
> task invoked as a result of executing the current task

Can you elaborate on this please?

**Comment by Forgind** [comment]
I didn't spend any time investigating, but at a glance, it looked like:
MSBuild task invoked, specifying some target -->
target includes GenerateDepsFile task, which fails and logs an error, then returns false -->
MSBuild task returns false but doesn't log an error.

I seem to remember we had some logic to prevent this from happening, but I'm wondering if that's broken in some way. I should've asked for logs; will do that later today if he still has it up.

**Comment by Forgind** [comment]
Sadly, he didn't. This probably isn't actually actionable.
