### ISSUE TITLE
Log helper methods should support a custom string interpolation handler

### ISSUE THREAD

**Issue by rainersigwald** [dotnet/msbuild#7875]
C# 10 supports [string interpolation handlers](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/tutorials/interpolated-string-handler) that enable efficient behavior with calls like (from their examples):

```c#
logger.LogMessage(LogLevel.Trace, $"Trace Level. CurrentTime: {time:t}. This won't be printed.");
```

This would be really nice to have in `Log.LogMessage` and related APIs.

**Comment by Forgind** [comment]
I'm unclear on what the goal is here. Many of our logging helper methods call into our localized resources, so we couldn't do anything as clean as the example you shared. What are you thinking?

**Comment by rainersigwald** [comment]
It's not about _our_ logging; it's about the logging API we provide to tasks.
