### ISSUE TITLE
Expose File IO API for tasks

### ISSUE THREAD

**Issue by stan-sz** [dotnet/msbuild#7876]
Writing custom MSBuild tasks that involve file IO operations involves calling `System.IO.File` directly or using `System.IO.Abstractions` for testable code. It would be handy for task authors to have the IO API exposed via either `Task`/`TaskExtension` base class or using the currently-inernal `FileSystems` static class as in:

https://github.com/dotnet/msbuild/blob/8b24a1bc3017ce78ecd6f21efb4e2c12395a74e7/src/Tasks/FileIO/VerifyFileHash.cs#L41

Some API is already available through https://docs.microsoft.com/en-us/dotnet/api/microsoft.build.filesystem.msbuildfilesystembase?view=msbuild-17-netcore

**Comment by BenVillalobos** [comment]
To be clear, what part of the API exactly are you asking for? Is it only `FileSystems`?

**Comment by stan-sz** [comment]
Yes, FileSystems

**Comment by Forgind** [comment]
FileSystems is exposed publicly through MSBuildFileSystemBase. Its methods are virtual, so you can override them if you wish; otherwise, it uses defaults from FileSystems.
