### ISSUE TITLE
Regression, .400 msbuild reports error on duplicate PackageVersions

### ISSUE THREAD

**Issue by erinlah-ms** [dotnet/msbuild#7886]
### Issue Description

After upgrading to 6.0.400 version of SDK, dotnet restore fails on all our project. We had (benign) duplicate entries. This worked fine on 6.0.302, but now on 6.0.400 this results in build failures.

### Steps to Reproduce

https://github.com/erinlah-ms/bug-repros/tree/main/repro-packageversiondup

1. install just 6.0.302 sdk
2. clone folder linked above
3. cd original
4. dotnet restore. Note no errors
5. install 6.0.400 sdk (don't uninstall .302)
6. dotnet restore. 
7. cd workaround
8. dotnet restore
9. open visual studio 17.3.0 (latest VS 2022 Enterprise)
10. build/restore the workaround.csproj from visual studio

### Expected Behavior

Error at step 6, building original.csproj, no errors at step 8 or 10 building workaround.csproj

### Actual Behavior

Step 10 fails to restore/build in visual studio, despite workaround.

### Analysis

It appears that release .400 introduced a new warning for duplicate PackageVersion entries. This broke our repo.

Normally we would just workaround the issue until such time as we could fix it. However, Visual Studio does not permit the user to downgrade to an older release of msbuild. Building the 'workaround.csproj' folder under visual studio still fails.

Visual Studio lacks an option to honor the msbuild/sdk version selected in the repo. It partially ignores global.json by using the version/build of msbuild that is shipped in box in visual studio, including using the targets/tasks defined in that version of msbuild.

### Versions & Configurations

Dotnetsdk 6.0.302 / dotnet msbuild 17.2.0+41abc5629
dotnetsdk 6.0.400 / dotnet msbuild  17.3.0+92e077650
Visual Studio 2022 Enterprise 17.3.0

**Comment by erinlah-ms** [comment]
@jaredpar Bug as requested.

**Comment by jeffkl** [comment]
This should probably be moved to NuGet, the functionality was added here: https://github.com/NuGet/NuGet.Client/pull/4484

/cc @nkolev92

**Comment by jaredpar** [comment]
Thanks for filing @erinlah-ms 

I can't transfer issues between organizations so I re-filed the issue in NuGet Client with the same information.

https://github.com/NuGet/Home/issues/12022

Closing as that will be the primary
