### ISSUE TITLE
Assembly manifest issues when building with OutputPath

### ISSUE THREAD

**Issue by ptsoccer** [dotnet/msbuild#7898]
### Issue Description
I have a solution that has a mix of EXEs and DLLs that I want to build to a single folder to deploy. I use the OutputPath property in msbuild to accomplish this. The issue I'm having is, when there different nuget packages referencing different versions of the same DLL, it likely ends up with one EXE ending up in a situation crashing at runtime because the assembly version doesn't match what it is expecting. Normally binding redirects are automatically added to fix this, but that only works when there is a versioning conflict in  the references of a single EXE. To illistrate, consider 3 files: EXE1, DLL A, and DLL B:

EXE1 references A v2.0.0
EXE1 references B v3.0.0 references A v3.0.0

EXE1 will end up with a binding redirect pointing to A v3.0.0 and all is fine. 

However introducing EXE2:

EXE2 references A v2.0.0
EXE1 references A v2.0.0
EXE1 references B v3.0.0 references A v3.0.0

EXE1 redirects to A v3.0.0, but EXE2 is still expecting A v2.0.0. Normally this is fine if the EXEs are built to separate folders, but combined into one folder, now there's an issue. If EXE1 is copied last, it will copy A v3.0.0, and EXE2 will crash because it was expecting A v2.0.0. A similar issue would happen if they are copied in reverse.

### Steps to Reproduce

[ProjectBuildOrderProblem.zip](https://github.com/dotnet/msbuild/files/9383520/ProjectBuildOrderProblem.zip)

The reproduction (attached) is pretty simple. I have 2 >NET Framework 4.6.2 EXEs
EXE ProjectBuildOrderProblem uses System.Runtime.CompilerServices.Unsafe, Version=4.0.4.1 because seemingly that's the default for 4.6.2
EXE ProjectBuildOrderProblem2 uses System.Runtime.CompilerServices.Unsafe, Version=6.0.0.0 because it references System.Collections.Immutable, Version=6.0.0.0 which references System.Runtime.CompilerServices.Unsafe, Version=6.0.0.0

To build:
msbuild /restore ProjectBuildOrderProblem.sln /p:OutDir="\<pathtoextractedzip\>\Output"
Note that \<pathtoextractedzip\> needs to be replaced with the path to where the zip is extracted.

After that, just run ProjectBuildOrderProblem.exe and it should crash.

### Expected Behavior
Ideally, a binding redirect would be inserted for ProjectBuildOrderProblem that points to System.Runtime.CompilerServices.Unsafe, Version=6.0.0.0. A compile error explaining the conflict would be acceptable. A runtime error isn't great because it will only be thrown when the reference is actually needed, so even simply opening the EXEs wouldn't be enough to detect the issue in a real project.

### Actual Behavior
The runtime error

```System.IO.FileLoadException: Could not load file or assembly 'System.Runtime.CompilerServices.Unsafe, Version=4.0.4.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)```

is raised.

### Versions & Configurations

MSBuild version
```Microsoft (R) Build Engine version 17.2.1+52cd2da31 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

17.2.1.25201
```

**Comment by BenVillalobos** [comment]
> Ideally, a binding redirect would be inserted for ProjectBuildOrderProblem that points to System.Runtime.CompilerServices.Unsafe, Version=6.0.0.0

Have you tried manually adding the binding redirect to your app.config?

Building multiple projects like this, with no relation between the two (eg `ProjectReference`) makes it difficult for our `ResolveAssemblyReference` task to figure this out for you.

**Comment by ptsoccer** [comment]
Yeah that works, but it's nearly impossible to tell that these bindings need to occur. I've ended up adding a new project that references every other project to create the bindings, then copy those bindings to every other project.

I guess my main confusion is it wasn't really that obvious that this msbuild parameter wasn't supported as well beyond .NET framework.

**Comment by BenVillalobos** [comment]
Team Triage: Unfortunately there's no "nice" way to handle this scenario.  

> Ideally, a binding redirect would be inserted for ProjectBuildOrderProblem that points to System.Runtime.CompilerServices.Unsafe, Version=6.0.0.0

Ultimately, there's a single `System.Runtime.CompilerServices.Unsafe.dll` **because everything points to the same folder**.

> A compile error explaining the conflict would be acceptable.

This is also tough because during each project's build everything is fine. Then the build outputs get copied and there's no way to know what will happen after that.

> A runtime error isn't great because it will only be thrown when the reference is actually needed, so even simply opening the EXEs wouldn't be enough to detect the issue in a real project.

Agreed 😕 None of this is ideal, but due to the nature of how things work in this build process there isn't much that can be done.

A possible path forward:
In theory you could have this particular dll output to specific folders within the output directory by modifying your build. Then you can modify each app.config to point to that specific folder within the output directory.

I don't think there's anything we can do to make this scenario better, unless there's another suggestion we haven't thought of. Closing this for now. Feel free to continue the conversation here and reopen though!

**Comment by ptsoccer** [comment]
I don't particularly want to reopen the issue, but just to ask: Is this effectively saying that compiling multiple EXEs to the same folder is not supported?
