### ISSUE TITLE
Consider renaming "up-for-grabs" label to "help wanted"

### ISSUE THREAD

**Issue by danmoseley** [dotnet/msbuild#7900]
It is specially recognized by Github. See context https://github.com/dotnet/runtime/issues/71496

You'll want to make sure you update upforgrabs.net if necessary, with a PR like https://github.com/up-for-grabs/up-for-grabs.net/pull/3320

cc @mairaw

**Comment by rainersigwald** [comment]
No objection here. @baronfel/@benvillalobos?

**Comment by baronfel** [comment]
None at all - I actually did this in the SDK over the weekend (since we had both sets of tags already, likely from an issue transfer).

**Comment by BenVillalobos** [comment]
I support this move. `help wanted` is much more intuitive.

**Comment by mairaw** [comment]
You can just rename the labels and check if you have any docs that point to the old label.

**Comment by BenVillalobos** [comment]
Will be fixed by https://github.com/up-for-grabs/up-for-grabs.net/pull/3373
