### ISSUE TITLE
Dependent project does not generate nuget package when multiple TFMs

### ISSUE THREAD

**Issue by odalet** [dotnet/msbuild#7911]
### Issue Description

Consider this scenario:

* Lib1.csproj multi-targets `net48` and `net6.0` and has `GeneratePackageOnBuild` set to `true`
* Lib2.csproj does the same
* Lib1.csproj references Lib2.csproj (both are part of the same solution)

Now, let's `dotnet build Lib1.csproj`:

* It generates Lib2 assemblies (one for each target),
* It genrates Lib1 assemblies (one for each target)
* It generates Lib1 `nupkg`
* **It does not generate Lib2 `nupkg` though**

> NB: this does not happen when building the solution in VS

### Steps to Reproduce
* See attached solution: [MultipleTfmsNugetRepro.zip](https://github.com/dotnet/msbuild/files/9423338/MultipleTfmsNugetRepro.zip)
* Then:

```sh
cd .....\Lib1
dotnet build
```

* `Lib1.nupkg` is created in `Lib1\bin\Debug`
* `Lib2.nupkg` is not `Lib2\bin\Debug`

I also attached the corresponding binlog (build in release configuration this time): [binlog.zip](https://github.com/dotnet/msbuild/files/9423334/binlog.zip)

### Expected Behavior

`Lib2.nupkg` should be generated

### Actual Behavior

`Lib2.nupkg` is not generated

### Analysis

I've skimmed through the binlog and I think it boils down to `IsInnerBuild = true`preventing Lib2's nuget package from being generated. Here is what I guess happens:

* Because Lib1 is a multi-targeting project, it is split into 2 pseudo-projects: one for each TFM 
* Thanks to the project reference, each one of these pseudo-projects transitively builds Lib2 (only for the TFM it is compatible with) in `IsInnerBuild = true` mode.
  * This gives us Lib2 assemblies both for `net48` and `net6.0` targets
  * And obviously Lib1 assemblies as well for both targets
* Back to Lib1, the root project goes on with building the nuget package and it is generated (and as expected references `Lib1.nupkg`)
* However, because Lib2 is never built with `IsInnerBuild = false`, its package is never generated.

### Versions & Configurations

* Visual Studio v17.2.2
* `dotnet --version`: 6.0.303

**Comment by BenVillalobos** [comment]
MSBuild Team Triage: This is by design. The workarounds here are to build each project individually or to build the solution itself.

**Comment by rainersigwald** [comment]
Including @aortiz-msft as FYI for the NuGet side.

> * However, because Lib2 is never built with `IsInnerBuild = false`, its package is never generated.

This is exactly the cause. When referenced by another project, we don't build the "outer build" of that project, because we may not need _all_ of the TargetFrameworks inside it. Instead, we build only what we need for a specific reference.

Building a solution/traversal project that invokes the "outer build" for both projects works because in multitargeted projects, pack happens in the outer build.

**Comment by odalet** [comment]
@rainersigwald : does your labeling means I should open a bug in the nuget repository? I clearly feel there's a functional hole here (as honestly the scenario I describe should just work as it does if I were to not multi-target) but maybe the MSBuild repo is not the good place for it?

**Comment by rainersigwald** [comment]
@odalet it's a problem with a multi-layered cause but since the overall scenario is owned by NuGet I think that's the best place to pursue it.
