### ISSUE TITLE
Unified Build control update

### ISSUE THREAD

**Issue by mmitche** [dotnet/msbuild#7925]
### Description

**This issue is dependent on https://github.com/dotnet/source-build/issues/2974 and is a placeholder for .NET 8 required work in product repositories.**

Instructions for implementation will be updated once https://github.com/dotnet/source-build/issues/2974 but will likely be a mechanical shift of properties in this repo. In a general sense, this is scaffolding work for expanding the set of source-built platforms beyond Linux.

**Comment by mmitche** [comment]
This is .NET 8 work

**Comment by mmitche** [comment]
Blocked on move to net9 arcade

**Comment by rainersigwald** [comment]
@mmitche what's the timeline y'all expect for us to move to Arcade 9? Sooner than "after the last 8.0.X00 release"?

**Comment by mmitche** [comment]
I think that's right? We're not trying to drive a specific schedule, other than before .NET 9 ships. When would you normally move?

**Comment by rainersigwald** [comment]
Historically we try to move as soon as possible after our main branch will no longer ship in a previous SDK major.

**Comment by mmitche** [comment]
Resolved
