### ISSUE TITLE
DotNet 6.0 MSBuild (amd64 dlls) gave this unhandled Exception when Building a DotNet 6.0-Windows Project from my code

### ISSUE THREAD

**Issue by garevaul** [dotnet/msbuild#7942]
I am building a Project from my code using all required .Net 6.0 MSBuild (amd64) dlls.  I am getting this error when I run the build project code.

Also, I do not know why in this error it is mentioning **\..\tools\net472\Microsoft.NET.Build.Tasks.dll** when I am not referencing Net472 at all.

Regards
Garry

-----------
Error Stack......
-----------
Project "GoodbyteOurDllsAndCoderMaster.csproj" (Rebuild target(s)):
	: ERROR C:\Program Files\dotnet\sdk\6.0.400\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.TargetFrameworkInference.targets(120,5): The "AllowEmptyTelemetry" task could not be instantiated from "C:\Program Files\dotnet\sdk\6.0.400\Sdks\Microsoft.NET.Sdk\targets\..\tools\net472\Microsoft.NET.Build.Tasks.dll". Method not found: 'Byte[] System.AppDomainSetup.GetConfigurationBytes()'.
	: ERROR C:\Program Files\dotnet\sdk\6.0.400\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.TargetFrameworkInference.targets(120,5): The "AllowEmptyTelemetry" task has been declared or used incorrectly, or failed during construction. Check the spelling of the task name and the assembly name.
	: ERROR (0,0): This is an unhandled exception in MSBuild -- PLEASE UPVOTE AN EXISTING ISSUE OR FILE A NEW ONE AT https://aka.ms/msbuild/unhandled.
    System.TypeLoadException: Could not load type 'System.Runtime.Remoting.RemotingServices' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
   at Microsoft.Build.BackEnd.TaskExecutionHost.Dispose(Boolean disposing)
   at Microsoft.Build.BackEnd.TaskExecutionHost.Dispose()
   at Microsoft.Build.BackEnd.TaskBuilder.ShutdownComponent()
   at Microsoft.Build.BackEnd.TargetBuilder.BuildTargets(ProjectLoggingContext loggingContext, BuildRequestEntry entry, IRequestBuilderCallback callback, String[] targetNames, Lookup baseLookup, CancellationToken cancellationToken)
   at Microsoft.Build.BackEnd.RequestBuilder.BuildProject()
   at Microsoft.Build.BackEnd.RequestBuilder.BuildAndReport()
Done building project "GoodbyteOurDllsAndCoderMaster.csproj" -- FAILED.

**Comment by rainersigwald** [comment]
How are you invoking the build? Are you using the MSBuild API? Are you using MSBuildLocator? What is your application's TargetFramework?

**Comment by garevaul** [comment]
Hi Rainer,

I am running my Build project code from a Net6.0-Windows project. I am referencing all the MSBuild dlls from the location 'C:\Program Files\Microsoft Visual Studio\2022\Professional\Msbuild\Current\Bin\amd64\...'

The Project I am Targeting/Building is also a Net6.0-Windows project which has references to various other 'Net6.0' and 'Net6.0-Windows' Dlls.

The Error when debugging is shown in this image >>
![image](https://user-images.githubusercontent.com/15125247/188321479-60f2744e-9a39-438f-a0df-d3b0ac574214.png)

The Code I am using to build the Project is this;

```
 var projectCollection = new ProjectCollection();
                var buildParameters = new BuildParameters(projectCollection);
                var globalProperty = new Dictionary<String, String>();
                globalProperty.Add("Configuration", "Debug");
                globalProperty.Add("Platform", "Any CPU");
                BuildManager.DefaultBuildManager.ResetCaches();
                var buildRequest = new BuildRequestData(projectOrSolutionFilePath, globalProperty, null, new String[] { "Rebuild" }, null);
                var buildResult = BuildManager.DefaultBuildManager.Build(buildParameters, buildRequest);
```

**Comment by garevaul** [comment]
Hi Rainer 

I am new to Github. I commented directly to the question at Github instead of replying to this notification. Hope you got the notification of that comment.

Regards
Bikramjeeth

**Comment by eriawan** [comment]
@garevaul 

I think it's quite obvious that you have reference to MSBuild that comes with Visual Studio, but your project is targeted against .NET 6.0 using TFM of `net6.0-windows`. The MSBuild that comes with Visual Studio requires .NET  Framework runtime, and this is totally different, therefore you should not mix your NET 6.0 projects with references that require .NET Framework.

I recommend you to use MSBuild references in the form of official MSBuild's nuget package: https://www.nuget.org/packages/Microsoft.Build
Why? Because this nuget of MSBuild supports both .NET Framework and NET 6.0:

![image](https://user-images.githubusercontent.com/8773147/188329219-67d1b406-c66f-4bcc-a570-1e945c87f86b.png)

And also don't forget to also add nuget package of Microsoft.Build.Framework, because Microsoft.Build requires it: https://www.nuget.org/packages/Microsoft.Build.Framework/

Note: if you add Microsoft.Build nuget package, the Microsoft.Build.Framework will be added as resolved nuget package as well when you restore nuget package of your project if you haven't added Microsoft.Build.Framework package.

@rainersigwald 
Feel free to correct me 🙂

**Comment by garevaul** [comment]
Hi @eriawan @rainersigwald,

I used the nuget MSBuild packages. It went through the previous error. But it is giving this error now. I tried looking for a nuget package by the name 'Microsoft.Common.props', but it is not there. 

**Please Note:** I have Installed the .Net 6.0 SDK using Winget/Choco. But they did not install in the **C:\Program Files\dotnet\sdk\** location. So I downloaded the dotnet-sdk-6.0.400-win-x64.zip file and unzipped it in this location. 

And I added a System Environment Variable **MSBuildSDKsPath** with value **C:\Program Files\dotnet\sdk\6.0.400\Sdks**

----------------------------------
Project "GoodbyteOurDllsAndCoderMaster.csproj" (Rebuild target(s)):
	: ERROR C:\Program Files\dotnet\sdk\6.0.400\Sdks\Microsoft.NET.Sdk\Sdk\Sdk.props(40,3): The imported project "D:\Goodbyte Projects OUR UTILITY\GoodbyteMaster\GoodbyteMaster\bin\Debug\net6.0-windows\Current\Microsoft.Common.props" was not found. Confirm that the expression in the Import declaration "D:\Goodbyte Projects OUR UTILITY\GoodbyteMaster\GoodbyteMaster\bin\Debug\net6.0-windows\**Current\Microsoft.Common.props**" is correct, and that the file exists on disk.
Done building project "GoodbyteOurDllsAndCoderMaster.csproj" -- FAILED.

**Comment by garevaul** [comment]
Hi @rainersigwald

Thanx. It works Excellent after using MSBuildLocator.

But I need to ask you that I guess the MSBuild Locator points to the Nugets Installed in the c:\users\<>\.nuget\packages\ in the PC, and MSBuild action in the Project uses those MSBuild Nuget packages.

Is it like that?

If so then, we have given  ExcludeAssets="runtime" to all the MSBuild packages entries in the csproj file (Except to the MSBuildLocator). So the MSBuild Packages are Not included in the Runtime, except the MSBuildLocator dll.

But the MSBuild packages are there on **MY computer** in c:\users\<>\.nuget\packages\

But if the same application is deployed on some other machine, then how will the application use those MSBuild packages because there you just have the MSBuildLocator dll, and the other MSBuild packages are not there on that other machine.

How does it work?

Regards
Bikramjeeth

**Comment by rainersigwald** [comment]
@garevaul MSBuildLocator finds a copy of MSBuild that is installed on the machine that's running the application, either through Visual Studio or through the .NET SDK. That way your application that uses MSBuild can build using the same logic that VS/`dotnet build` would use on that machine.

**Comment by garevaul** [comment]
Ok @rainersigwald thanx a zillion. It was kind of you to take up the issue and resolve it.

Special thanx to @eriawan for your on dot guidance.

Regards
@garevaul
