### ISSUE TITLE
MSBuild detects wrong processor count on Windows when debugging processor groups

### ISSUE THREAD

**Issue by dmex** [dotnet/msbuild#7943]
### Issue Description

MSBuild detects the wrong processor count on Windows when debugging processor groups and the bug was introduced with PR: https://github.com/dotnet/msbuild/pull/5625

### Analysis

The comments in PR 5625 mentioned various ongoing issues testing processor group support on Windows due to the lack of hardware:
> I don't have a machine with > 32 cores to actually test this.
> I'm trying to pull some strings internally to borrow a machine big enough to test it on

The lack of hardware should never have been an issue. Windows has special boot parameters to enable virtual processor groups specially designed for developers to write and debug processor group support on Windows without requiring physical hardware with >64 processors. 😋

The MSDN documentation is aimed at driver developers however the same steps are required for testing and debugging usermode applications: https://docs.microsoft.com/en-us/windows-hardware/drivers/devtest/boot-parameters-to-test-drivers-for-multiple-processor-group-support

For example:
`bcdedit.exe /set groupsize 2`

If you have 16 processors this will create 8 processor groups with 2 processors in each group and simulate a machine with > 64 processors. Usermode functions such as GetSystemInfo (and the .NET framework which is not group aware) will now only report 2 processors and this includes MSBuild because of two issues:

1) This check for `>= 32` is incompatible with the groupsize boot paramater and must be removed:
https://github.com/dotnet/msbuild/blob/65c50fb73faefec0ef2ce8256b802f50cc8236f0/src/Framework/NativeMethods.cs#L516

2) MSBuild is using a custom enumerator with GetLogicalProcessorInformationEx which is incorrect:
https://github.com/dotnet/msbuild/blob/65c50fb73faefec0ef2ce8256b802f50cc8236f0/src/Framework/NativeMethods.cs#L538-L575

Starting Windows 7 usermode applications are supposed to call [GetActiveProcessorCount](https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-getactiveprocessorcount) and kernel drivers [KeQueryActiveProcessorCountEx](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/wdm/nf-wdm-kequeryactiveprocessorcountex)

The `GetLogicalCoreCountOnWindows` function MSBuild is using should be removed and all the code be replaced with a single line: 
```csharp
int numberOfProcessors = GetActiveProcessorCount(ALL_PROCESSOR_GROUPS);
```
Typedefs:
```csharp
const ushort ALL_PROCESSOR_GROUPS = 0xFFFF;

[DllImport("kernel32.dll")]
public static extern int GetActiveProcessorCount(ushort GroupNumber);
```

### Steps to Reproduce
1) Open command prompt as Administrator
2) Execute `bcdedit.exe /set groupsize 2`
3) Reboot
4) MsBuild is now limited to 2 processors (on a 16 processor machine).

### Expected Behavior
MSBuild support for multiple processor groups.

### Actual Behavior
MSBuild is limited to 2 processors making testing/debugging applications significantly slower.

**Comment by elachlan** [comment]
Wow. Awesome write up! Are you going to put in a PR?

**Comment by dmex** [comment]
@elachlan I've created PR #7945

**Comment by dmex** [comment]
👍
