### ISSUE TITLE
"DotNet Clean" and "DotNet Build" are not working on THESE projects .Net 6 projects on the CSPROJ files or SLN file.

### ISSUE THREAD

**Issue by garevaul** [dotnet/msbuild#7958]
Hi,

"DotNet Clean" and "DotNet Build" are not working on these projects' CSPROJ files and the SLN file.

The Command I tried in Powershell is
`dotnet clean "I:\Goodbyte Net Framework DLL Projects\GoodbyteOurDllsAndCoderMaster\GoodbyteOurDllsAndCoderMaster.sln"`

`dotnet clean -c debug "I:\Goodbyte Net Framework DLL Projects\GoodbyteOurDllsAndCoderMaster\GoodbyteOurDllsAndCoderMaster.sln"`

`dotnet clean -c release "I:\Goodbyte Net Framework DLL Projects\GoodbyteOurDllsAndCoderMaster\GoodbyteOurDllsAndCoderMaster.sln"`

`dotnet build "I:\Goodbyte Net Framework DLL Projects\GoodbyteOurDllsAndCoderMaster\GoodbyteOurDllsAndCoderMaster.sln"`

The Projects Folders are here::
https://1drv.ms/u/s!AjNAB3KpbqsEkWos0AMsJbvDcAef?e=DqCvie

Just Copy the Entire Folder to let's says i-drive, like "I:\Goodbyte Net Framework DLL Projects" or to any Root of the Drive of your choice and Run the Powershell Command.

The Assemblies DO NOT get Cleaned or Build **(IN These Projects SITUATION)**

Regards

**Comment by rainersigwald** [comment]
Are you seeing errors? Things appear to work on my machine.

Build:

```
  GoodbyteOurDllsAndCoderMaster -> C:\repro2\Goodbyte Net Framework DLL Projects\GoodbyteOurDllsAndCoderMaster\bin\Debug\net6.0-windows10.0.19041.0\GoodbyteOurDllsAndCoderMaster.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:17.34
```

Clean:

```
     1>Done Building Project "C:\repro2\Goodbyte Net Framework DLL Projects\GoodbyteOurDllsAndCoderMaster\GoodbyteOurDllsAndCoderMaster.sln" (Clean target(s)).
...
Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:02.63
```

**Comment by garevaul** [comment]
No there are no errors. 

But the 'Clean' should remove all the files from the 'bin\net6.0' / 'bin\net6.0-windows' the relevant files in 'obj\net6.0' / 'obj\net6.0-windows' folders of all the projects, including the 'GoodbyteOurDllsAndCoderMaster' project.

Which is not happening.

Regards

**Comment by garevaul** [comment]
Hi @rainersigwald

It has been 12 days since my comment. Any updates on this issue. I guess it is a bug in 'DotNet' command utility, that maybe when the projects do not contain any code, then the cleanup does not take place. 

I think it is this, or maybe something else.

Regards
@garevaul

**Comment by BenVillalobos** [comment]
@garevaul What specific files aren't getting deleted? This doesn't repro on my machine.

Can you also [provide a binlog](https://aka.ms/msbuild/binlog)? Just add `/bl` to your command line and submit it as a feedback ticket at [Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html) to keep your information private. Then link that feedback ticket here.

**Comment by garevaul** [comment]
Hi @rainersigwald @BenVillalobos 

I think I have found the small bug, or maybe I do not know the whole story :) 

If you download my provided project folders and RUN the 'DotNet clean' **FIRST**, then the clean does NOT take place.

But if you give the 'DotNet build' command and then do 'DotNet clean', then the clean is done fine.

Please try and see.

Regards
@garevaul

**Comment by BenVillalobos** [comment]
This is expected. `dotnet clean` works by deleting specific files generated from the last build. These files are specified in `obj\<projectname>.FileAbsolute.txt`. 

The problem with this scenario is that the files built from a previous build are written as absolute paths, which won't be cleaned if the paths change at all.

Are you seeing this in a scenario where you're moving this project around (bin/obj included)?

**Comment by garevaul** [comment]
Hi @rainersigwald @BenVillalobos 

You are right. It is exactly that issue. The files/Folders were originally located in another location, so the paths in the FileAbsolute.txt was pointing to that old location.

Thanx 
@garevaul
