### ISSUE TITLE
Disable MSBuild Server for interactive builds

### ISSUE THREAD

**Issue by MichalPavlik** [dotnet/msbuild#7964]
There is a reported issue: https://github.com/dotnet/sdk/issues/27597

We should disable MSBuild Server behavior when we detect `interactive` switch.

**Comment by marcpopMSFT** [comment]
@MichalPavlik , this is needed for 7.0.1xx rc2. We'll be snapping that branch tomorrow so if you can get this merged by end of the week, that should be in time.  BTW, are there any other cases where server causes bad impact or is interactive unique enough to be the only one?
