### ISSUE TITLE
❗Help Make MSBuild Better! [4-min survey]

### ISSUE THREAD

**Issue by BenVillalobos** [dotnet/msbuild#7996]
If you've ever struggled with using MSBuild, we want to hear from YOU!

Prioritizing **over one-thousand** issues is a never-ending challenge. We're hoping this survey will give us a big picture look at what 
developers want and need from us.

Help us out by [**taking this 4 minute survey**](https://forms.office.com/r/Rghh3w3tnY).

Thanks ❤️

**Comment by rainersigwald** [comment]
Survey closed. Thanks, folks!
