### ISSUE TITLE
Could not copy the file "XXXX\apphost.exe" because it was not found

### ISSUE THREAD

**Issue by MichalStrehovsky** [dotnet/msbuild#8003]
### Issue Description

Running dotnet publish after deleting obj and bin directories fails until I taskkill the dotnet process.

### Steps to Reproduce

* Download the latest SDK installer build (I'm using 7.0.100-rtm.22470.23)
* Unzip it to e.g. C:\dotnet7 and then run the following exact steps:

```
cd c:\dotnet7
set path=%cd%;%path%
dotnet new console -o test
cd test
dotnet publish -r win-x64 -c Release
rmdir /S /Q obj
rmdir /S /Q bin
dotnet publish -r win-x64 -c Release
```

### Expected Behavior
The second publish succeeds, same as the first.

### Actual Behavior
```
C:\dotnet7\sdk\7.0.100-rtm.22470.23\Microsoft.Common.CurrentVersion.targets(5145,5): error MSB3030: Could not copy the
file "C:\dotnet7\test\obj\Release\net7.0\win-x64\apphost.exe" because it was not found. [C:\dotnet7\test\test.csproj]
```

### Analysis
Something with the dotnet.exe process that hangs around after the first publish. If I `taskkill /im dotnet.exe /f` before the second publish, it works. It took a while to figure that out.

Here's the binlog from the failed attempt: 
[msbuild.zip](https://github.com/dotnet/msbuild/files/9630415/msbuild.zip)

### Versions & Configurations
7.0.100-rtm.22470.23

**Comment by rainersigwald** [comment]
Hmm. I don't seem to repro with those steps.

```sh-session
❯ git clean -xdf
Removing bin/
Removing obj/

8003\test on main via .NET v7.0.100-rtm.22472.21 🎯 net7.0
❯ dotnet publish -r win-x64 -c Release -bl
MSBuild version 17.4.0-preview-22466-03+48ab5664b for .NET
C:\Users\raines\Downloads\dotnet-sdk-7.0.100-rtm.22472.21-win-x64\sdk\7.0.100-rtm.22472.21\MSBuild.dll --property:_IsPublishing=true -property:RuntimeIdentifier=win-x64 -property:_CommandLineDefinedRuntimeIdentifier=true -property:Configuration=Release -bl -distributedlogger:Microsoft.DotNet.Tools.MSBuild.MSBuildLogger,C:\Users\raines\Downloads\dotnet-sdk-7.0.100-rtm.22472.21-win-x64\sdk\7.0.100-rtm.22472.21\dotnet.dll*Microsoft.DotNet.Tools.MSBuild.MSBuildForwardingLogger,C:\Users\raines\Downloads\dotnet-sdk-7.0.100-rtm.22472.21-win-x64\sdk\7.0.100-rtm.22472.21\dotnet.dll -maxcpucount -restore -target:Publish -verbosity:m .\test.csproj
  Determining projects to restore...
  Restored S:\repro\dotnet\msbuild\issues\8003\test\test.csproj (in 13 ms).
C:\Users\raines\Downloads\dotnet-sdk-7.0.100-rtm.22472.21-win-x64\sdk\7.0.100-rtm.22472.21\Sdks\Microsoft.NET.Sdk\targe
ts\Microsoft.NET.RuntimeIdentifierInference.targets(257,5): message NETSDK1057: You are using a preview version of .NET
. See: https://aka.ms/dotnet-support-policy [S:\repro\dotnet\msbuild\issues\8003\test\test.csproj]
C:\Users\raines\Downloads\dotnet-sdk-7.0.100-rtm.22472.21-win-x64\sdk\7.0.100-rtm.22472.21\Sdks\Microsoft.NET.Sdk\targe
ts\Microsoft.NET.Sdk.targets(1136,5): warning NETSDK1179: One of '--self-contained' or '--no-self-contained' options ar
e required when '--runtime' is used. [S:\repro\dotnet\msbuild\issues\8003\test\test.csproj]
  test -> S:\repro\dotnet\msbuild\issues\8003\test\bin\Release\net7.0\win-x64\test.dll
  test -> S:\repro\dotnet\msbuild\issues\8003\test\bin\Release\net7.0\win-x64\publish\

8003\test on main via .NET v7.0.100-rtm.22472.21 🎯 net7.0
❯ .\msbuild.binlog

8003\test on main via .NET v7.0.100-rtm.22472.21 🎯 net7.0
❯ cmd /c rmdir /s /q obj bin

8003\test on main via .NET v7.0.100-rtm.22472.21 🎯 net7.0
❯ dotnet publish -r win-x64 -c Release -bl
MSBuild version 17.4.0-preview-22466-03+48ab5664b for .NET
C:\Users\raines\Downloads\dotnet-sdk-7.0.100-rtm.22472.21-win-x64\sdk\7.0.100-rtm.22472.21\MSBuild.dll --property:_IsPublishing=true -property:RuntimeIdentifier=win-x64 -property:_CommandLineDefinedRuntimeIdentifier=true -property:Configuration=Release -bl -distributedlogger:Microsoft.DotNet.Tools.MSBuild.MSBuildLogger,C:\Users\raines\Downloads\dotnet-sdk-7.0.100-rtm.22472.21-win-x64\sdk\7.0.100-rtm.22472.21\dotnet.dll*Microsoft.DotNet.Tools.MSBuild.MSBuildForwardingLogger,C:\Users\raines\Downloads\dotnet-sdk-7.0.100-rtm.22472.21-win-x64\sdk\7.0.100-rtm.22472.21\dotnet.dll -maxcpucount -restore -target:Publish -verbosity:m .\test.csproj
  Determining projects to restore...
  Restored S:\repro\dotnet\msbuild\issues\8003\test\test.csproj (in 3 ms).
C:\Users\raines\Downloads\dotnet-sdk-7.0.100-rtm.22472.21-win-x64\sdk\7.0.100-rtm.22472.21\Sdks\Microsoft.NET.Sdk\targe
ts\Microsoft.NET.RuntimeIdentifierInference.targets(257,5): message NETSDK1057: You are using a preview version of .NET
. See: https://aka.ms/dotnet-support-policy [S:\repro\dotnet\msbuild\issues\8003\test\test.csproj]
C:\Users\raines\Downloads\dotnet-sdk-7.0.100-rtm.22472.21-win-x64\sdk\7.0.100-rtm.22472.21\Sdks\Microsoft.NET.Sdk\targe
ts\Microsoft.NET.Sdk.targets(1136,5): warning NETSDK1179: One of '--self-contained' or '--no-self-contained' options ar
e required when '--runtime' is used. [S:\repro\dotnet\msbuild\issues\8003\test\test.csproj]
  test -> S:\repro\dotnet\msbuild\issues\8003\test\bin\Release\net7.0\win-x64\test.dll
  test -> S:\repro\dotnet\msbuild\issues\8003\test\bin\Release\net7.0\win-x64\publish\
```

Are you getting this reliably?

One thing I notice from your binlog is

```text
Skipping target "CoreCompile" because all output files are up-to-date with respect to the input files.
```

which seems to imply that the `rmdir` may not have been run or was somehow concurrent with the second build?

**Comment by MichalStrehovsky** [comment]
C:\Users\raines\Downloads\dotnet-sdk-7.0.100-rtm.22472.21-win-x64
S:\repro\dotnet\msbuild\issues\8003\test

Test needs to go under the extracted dotnet. Iirc that part was important for some reason.

**Comment by MichalStrehovsky** [comment]
> which seems to imply that the rmdir may not have been run or was somehow concurrent with the second build?

Those folders are definitely deleted. I was troubleshooting this for a while until I figured out killing all dotnet.exe instances resolves it. It's 100% repro for me and has been with various 7.0/8.0 SDK versions I tried lately.

Extracting the SDK and creating projects using the SDK into the **same directory** is my "scratch program" workflow. It can all be quickly cleaned up because I just delete the one folder.

**Comment by BenVillalobos** [comment]
@MichalStrehovsky Is this a regression?

> If I taskkill /im dotnet.exe /f before the second publish, it works. It took a while to figure that out.

cc @rokonec msbuild server related?

**Comment by MichalStrehovsky** [comment]
It is a regression. The workflow stopped working recently (not much more than ~2 months ago?). I brushed it off as some intermittent issue. It took a while until I realized the exact steps to repro it and the relationship with the msbuild server (the fact that taskkill makes it start working again). `dotnet` is starting to have too much "magic" for my taste.

Setting `DOTNET_CLI_DO_NOT_USE_MSBUILD_SERVER` to `1` makes it no longer repro.

**Comment by rokonec** [comment]
I have discussed it with Michal. The root cause is not MSBuild server but our updated immutable-files up to date check.
We simply add dotnet root `c:\dotnet7\` as immutable directory so c:\dotnet7\test which contains test projects is also considered immutable and removing bin and obj from it will break this immutability and cause msbuild node process believe files are still there.
If `c:\dotnet7\test` would have contained multiple projects it would be reproducible even without msbuild server (in nodes processes).
Workaround/recommendation is not put anything projects into dotnet-root directory and let dotnet-root directory be reserved only as target for dotnet installations.
@rainersigwald do we want to somehow address this issue? One solution would be to test if project directory is inside of known immutable directories and log error.

**Comment by rokonec** [comment]
@rainersigwald By looking at the code, we would have to inject test and disabling logic in:
- `LoggingService.LogProjectStarted`
- `Evaluator.Evaluate`

If would test if project file is considered immutable and if it was, if would turn immutable check off permanently.

We shall consider if this amount of code and complexity is worth to solve this, IMO, niche use case.
Please advise.

**Comment by rainersigwald** [comment]
@baronfel do you have an opinion here? I lean toward "do nothing until/unless we get more feedback on this" but it sure is a bad failure case if you do hit it.

One other possible option would be to try to detect whether dotnet-root is writeable (as a proxy for "is the SDK an unzipped one") and disable the immutable-files caching then?

**Comment by baronfel** [comment]
I'm inclined to agree. This is the first time I've heard of folks making projects inside an SDK directory (though of course such a thing is _possible_), and I don't want to over correct on a solution without a few more data points.

**Comment by srvitor1212** [comment]
Hello guys, i think i'm having the same error. Do you know how to fix it ?

https://answers.microsoft.com/pt-br/feedback/forum/fdbk_moderator/ide-visual-studio-2022-msb3030-erro-estoura-no/ec7fc30b-f988-4ee6-b58c-8708889d52d6

**Comment by qwerty7676mi** [comment]
I'm getting the "Could not copy the path\plugin.dll because it was not found" error for hundreds of dlls in all projects under the solution while publishing the project. I'm able to build the project and run it locally though. Is this the same issue?

**Comment by rainersigwald** [comment]
> I'm getting the "Could not copy the path\plugin.dll because it was not found" error for hundreds of dlls in all projects under the solution while publishing the project. I'm able to build the project and run it locally though. Is this the same issue?

@qwerty7676mi very unlikely to be this issue, please file a new one.
