### ISSUE TITLE
MSB1001: Unknown switch; Switch: --project

### ISSUE THREAD

**Issue by Denovocto** [dotnet/msbuild#8009]
### Describe the bug
When using the dotnet cli, using `dotnet run --project <project_name>` and `dotnet build --project Bioportal.API`,
 MSBuild Fails with error: 
`MSBUILD : error MSB1001: Unknown switch.`. Sometimes it runs flawlessly without error and other times it says build failed.
I've tried starting new shell sessions, new terminal sessions, restoring projects, none seem to fix the error.

### To Reproduce
Currently using `MSBuild version 17.4.0-preview-22428-01+14c24b2d3` and `.NET 7.0.100-rc.1.22431.12`. 
The full default commandline flags are: `-maxcpucount`, `verbosity:m`, `-restore`, `-consoleloggerparameters:Summary`.

Below that error, this information is shown: 
Switches appended by response files:
Switch: --project`
### Exceptions (if any)
MSB1001: Unknown switch

#### `dotnet --info`
```
.NET SDK:
 Version:   7.0.100-rc.1.22431.12
 Commit:    f1cf61e1c0

Runtime Environment:
 OS Name:     fedora
 OS Version:  36
 OS Platform: Linux
 RID:         fedora.36-x64
 Base Path:   /usr/share/dotnet/sdk/7.0.100-rc.1.22431.12/

Host:
  Version:      7.0.0-rc.1.22426.10
  Architecture: x64
  Commit:       06aceb7015

.NET SDKs installed:
  7.0.100-rc.1.22431.12 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 7.0.0-rc.1.22427.2 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 7.0.0-rc.1.22426.10 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```
#### IDE / Editor
Just using alacritty as terminal and zsh as shell. Error appears only in cli.

**Comment by rokonec** [comment]
@Denovocto It might be related to https://github.com/dotnet/msbuild/issues/8010 and is already being fixed by https://github.com/dotnet/msbuild/pull/8006.
Above bug would have surfaced if you attempted to cancel build, CTRL+C, some short time, max 15 minutes, before. Have you?

**Comment by Denovocto** [comment]
@rokonec At that time I don't think I did. Usually I don't quit or exit my builds. I see them through completion. Although, when I run projects `dotnet run` through cli, is when I `Ctrl-C` to stop their execution, but only after the build has completed and the project is already running. I don't know if it applies to run as well?

**Comment by rokonec** [comment]
Yes, it most like IS this issue. 
Thanks very much for reporting. The fix will be released in dotnet 7 RTM.
