### ISSUE TITLE
[Feature] Directory.Solution.props and Directory.Solution.targets support in Visual Studio

### ISSUE THREAD

**Issue by hknielsen** [dotnet/msbuild#8038]
Directory.Build.props/targets are awesome, but when you want to apply the setting to all csproj's thats in the Solution, and some csproj's are not rooted under the `.sln` directory, I need to copy the Directory.Build.props file, or even have to add my own SDK to handle this.

Having my own SDK to Import Solution wide props/targets files seem a bit excessive, and would be nice to have out of the box.

/SomeSln/SomeSln.sln
/SomeSln/SomeSln.Build.props
/Foo/Bar/Bar.csproj - Includes `Solution.Build.props` when `Solution` is build

**Comment by hknielsen** [comment]
@KalleOlaviNiemitalo 
>already documents Directory.Solution.props and Directory.Solution.targets
What SDK is that imported by? I dont see my `Directory.Solution.props` getting imported when opening the Solution

**Comment by hknielsen** [comment]
@KalleOlaviNiemitalo ah yeah I see. Hmm yeah then that would not work for my case.

I still think that it would be valuable to have a way to do Solution wide props/targets Imports. Directory.Build.props only work if you have all your csproj's rooted under the sln, I agree we cant change that, but would need something else, ie. `Solution.Build.props`
Just like global.json are Solution wide, it seem like there's some inconsistencies.

**Comment by rainersigwald** [comment]
You can do this manually today, by importing files based on `$(SolutionDir)` or `$(SolutionPath)`. However, you probably _don't_ want to do this. It introduces very confusing differences between builds:

1. In the context of solution A, the project builds one way.
2. In the context of solution B, the project builds another way.
3. When built on its own, the solution builds a third way.

This is _especially_ confusing when working on both solutions or going back and forth, and with incremental builds: if the project is up to date and was last built in context A, will a build (without clean) in context B produce correct outputs, or a weird combination where some configuration from A apply to some outputs and some configuration from B applies to others?

**Comment by rainersigwald** [comment]
> Just like global.json are Solution wide, it seem like there's some inconsistencies.

That's not quite correct, `global.json` applies to folders just like `Directory.Build.props` does; the difference is that if two projects in the same build are discovered to have different `global.json` the build fails.

**Comment by hknielsen** [comment]
Hi @rainersigwald thanks for taking your time to chime in :)

>That's not quite correct, global.json applies to folders just like Directory.Build.props does

global.json search paths is first in the SolutionFilePath for the global.json, if `global,json` is not there the resolver looks at the csproj directory
https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/Microsoft.Build.NuGetSdkResolver/GlobalJsonReader.cs#L93

So if you have SolutionA, and SolutionB, including the same csproj's (sln at different locations), they could be compiled with ie. different SDK versions, if one have that liking.

>However, you probably don't want to do this. It introduces very confusing differences between builds

I agree and maybe its not as easy as first anticipated from my side.
Im investigating how we can move from a custom Build/Compilation pipeline to MsBuild, using the custom logic we have today expressed in a MsBuild SDK.
For our users today, it is possible to have a project layout like:
```
Foo/Foo.sln
Foo/Bar/Bar.csproj
Baz/Baz.csproj
```
I would like to be able to include props and target files in `Baz/Baz.csproj`, if fx our SDK is not not used, but using elements that the SDK would deal with, I would like to give some helpful information to the user.
Without a solution wide Include, the best way I can see forward today is to generate a `Directory.Build.props` file in `Baz/` location, when Users does this

**Comment by hknielsen** [comment]
@rainersigwald - To come back to this. Why is it that `Directory.Solution.props` and `Directory.Solution.targets` is not picked up in Visual Studio? Seem like that would  solve all issues, and its already a supported feature by MsBuild.

**Comment by BenVillalobos** [comment]
Closing this since it isn't an MSBuild issue. You can file feedback at [Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html) so this can get routed to the VS team.
