### ISSUE TITLE
MSBuildStartupDirectory wrong values for .NET 7 dotnet build (blocker for Sonar analysis)

### ISSUE THREAD

**Issue by mary-georgiou-sonarsource** [dotnet/msbuild#8094]
### Issue Description

When analyzing a project using SonarScanner for .NET (integration tool for [SonarQube](https://marketplace.visualstudio.com/items?itemName=SonarSource.sonarqube)), and we use the .NET 7 runtime the analysis fails ([related issue](https://github.com/SonarSource/sonar-scanner-msbuild/issues/1333)).

After digging around we found that the problem lies with `MSBuildStartupDirectory` property that we use (see [here](https://github.com/SonarSource/sonar-scanner-msbuild/blob/5.8.0.52797/src/SonarScanner.MSBuild.Tasks/Targets/SonarQube.Integration.ImportBefore.targets#L12)) to get the absolute path from which `dotnet build` command or MSBuild is called. 

The issue can be summarized as follows:

If one builds two consecutive projects with .NET7, the value of `MSBuildStartupDirectory` keeps the value of the first project that was built.

### Steps to Reproduce

Clone https://github.com/mary-georgiou-sonarsource/net7Repro
```bash
cd Project1
dotnet build /target:DisplayMessages
cd ../Project2
dotnet build /target:DisplayMessages
```
### Expected Behavior
`MSBuildStartupDirectory` should have as a value the path of the root folder from which is invoked.

### Actual Behavior
After building `Project1` the output is:
```
  MSBuildStartupDirectory = Dir\Project1
  Project File Name = Project1.csproj
```

After building `Project2`:
```
  MSBuildStartupDirectory = Dir\Project1
  Project File Name = Project2.csproj
```
Notice that the `MSBuildStartupDirectory` is not updated to `Dir\Project2`. 

I did the same test, but with targetting `dotnet 6.0.305`, and the behavior, in that case, was correct - `MSBuildStartupDirectory` had the correct value.

### Versions & Configurations
* MSBuild version 17.4.0-preview-22470-08+6521b1591
* dotnet 7.0.100-rc.2.22477.23
* OS:  Microsoft Windows 10 Pro 10.0.19044 Build 19044

This is a blocker for the .NET project analysis with SonarQube.
It seems that a workaround is to use `msbuild /t:rebuild -v:d`.
Is there a workaround for the dotnet CLI?

Thanks a lot!

**Comment by rainersigwald** [comment]
Looks like a bug in MSBuild Server. @rokonec

@mary-georgiou-sonarsource, MSBuild server is off by default for .NET 7.0.100 GA (not yet released).

> Is there a workaround for the dotnet CLI?

There is, the environment variable `DOTNET_CLI_DO_NOT_USE_MSBUILD_SERVER=1`:

```sh-session
$ dotnet build /target:DisplayMessages
MSBuild version 17.4.0-preview-22470-08+6521b1591 for .NET
  Determining projects to restore...
  Restored /workspaces/net7Repro/Project2/Project2/Project2.csproj (in 3 ms).
  MSBuildStartupDirectory = /workspaces/net7Repro/Project1
  Project File Name = Project2.csproj

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:00.16
$ DOTNET_CLI_DO_NOT_USE_MSBUILD_SERVER=1 dotnet build /target:DisplayMessages
MSBuild version 17.4.0-preview-22470-08+6521b1591 for .NET
  Determining projects to restore...
  All projects are up-to-date for restore.
  MSBuildStartupDirectory = /workspaces/net7Repro/Project2
  Project File Name = Project2.csproj

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:00.86
```

The workaround will be harmless but unnecessary on SDKs after GA; we should fix this bug before attempting to reenable MSBuild Server.

**Comment by baronfel** [comment]
Yes - that's correct. The MSBuild Server feature has been changed into an opt-in for the GA release (with an associated grammar change to the environment variable override), so setting this environment variable will no longer change any behaviors.
