### ISSUE TITLE
ItemGroup with metadata inside Target produces duplicate items

### ISSUE THREAD

**Issue by dfields-msft** [dotnet/msbuild#8117]
### Issue Description
When an `ItemGroup` is used inside a `Target` and references item metadata like `%(Filename)`, each subsequent `ItemGroup` is redundantly evaluated once for each item enumerated by the previous `ItemGroup`, resulting in duplicate items in the final list. When the items are `Compile` items, this can lead to warning CS2002 which may cause pipeline builds to fail when `-warnaserror` is used.

### Steps to Reproduce
Here's an example target which demonstrates the issue; a min-repro solution is also attached.
```xml
<Target Name="EnumerateFiles">
  <ItemGroup>
    <MyFile Include="A/**/*.txt" Link="%(Filename)"/>
    <MyFile Include="B/**/*.txt" Link="%(Filename)"/>
    <MyFile Include="C/**/*.txt" Link="%(Filename)"/>
  </ItemGroup>
  <Error Condition="'@(MyFile)' != 'A\1.txt;A\2.txt;B\3.txt;C\4.txt'" Text="Duplicate files enumerated: @(MyFile)"/>
</Target>
```

[DuplicateItemMinRepro.zip](https://github.com/dotnet/msbuild/files/9924208/DuplicateItemMinRepro.zip)

### Expected Behavior
Each item matched by the wildcard is enumerated exactly once.

### Actual Behavior
Duplicate items are enumerated.

### Analysis
It seems like the implementation of `ItemGroup` may leave some state behind which isn't cleared when the next `ItemGroup` is evaluated.

### Versions & Configurations
MSBuild version 17.3.1+2badb37d1 for .NET Framework
17.3.1.41501

**Comment by rainersigwald** [comment]
The globbing is a bit off a red herring here; you can reproduce the behavior without:

```xml
<Project>

<Target Name="EnumerateFiles">
  <ItemGroup>
    <MyFile Include="A" Link="%(Filename)"/>
    <MyFile Include="B" Link="%(Filename)"/>
    <MyFile Include="C" Link="%(Filename)"/>
  </ItemGroup>
  <!-- <Error Condition="'@(MyFile)' != 'A\1.txt;A\2.txt;B\3.txt;C\4.txt'" Text="Duplicate files enumerated: @(MyFile)"/> -->

  <Message Importance="high" Text="MyFile: Identity= %(MyFile.Identity) Link= %(MyFile.Link)" />
</Target>

</Project>
```

```sh-session
❯ dotnet build .\foo.proj
MSBuild version 17.4.0-preview-22470-08+6521b1591 for .NET
  MyFile: Identity= A Link=
  MyFile: Identity= B Link= A
  MyFile: Identity= C Link= A
  MyFile: Identity= C Link= B
```

What is happening here is that the syntax you've posted, when inside a target, causes [batching](https://learn.microsoft.com/visualstudio/msbuild/msbuild-batching).

1. The first line executes, sees that there are no `@(MyFile)` items, and evaluates `%(Filename)` to the empty string.
2. The second line executes, sees that there is one item (in my example with no globs), and evaluates `%(Filename)` to its name, so you get `B` with metadata `A`
3. The third line sees that there are two items with distinct filenames, and runs in two batches, so you get `C` with metadata `A` and `C` with metadata `B`.

Outside a target, the `%()` syntax is interpreted differently and applies to the items being created by the `Include`'s expansion.

You may wish to try something like this:

```diff
diff --git a/DuplicateItemMinRepro.csproj b/DuplicateItemMinRepro.csproj
index 220ad4a..30bb7d8 100644
--- a/DuplicateItemMinRepro.csproj
+++ b/DuplicateItemMinRepro.csproj
@@ -8,10 +8,13 @@
 
   <Target Name="EnumerateFiles">
     <ItemGroup>
-      <MyFile Include="A/**/*.txt" Link="%(Filename)"/>
-      <MyFile Include="B/**/*.txt" Link="%(Filename)"/>
-      <MyFile Include="C/**/*.txt" Link="%(Filename)"/>
+      <MyFile Include="A/**/*.txt" />
+      <MyFile Include="B/**/*.txt" />
+      <MyFile Include="C/**/*.txt" />
+
+      <MyFile Link="%(MyFile.FileName)" />
     </ItemGroup>
+
     <Error Condition="'@(MyFile)' != 'A\1.txt;A\2.txt;B\3.txt;C\4.txt'" Text="Duplicate files enumerated: @(MyFile)"/>
   </Target>
 
```

**Comment by dfields-msft** [comment]
Aha, thank you for the clear explanation! I was aware of batching, but hadn't comprehended how it would manifest in this case and expected it to apply as it does outside the target. Effectively, each item declaration was doing a for-each over the current set of items and using *those* items to generate metadata for the new item(s), rather than using each new item to generate metadata for itself (as is done outside the task). Your alternative solution works well to apply the metadata separately from enumerating items inside the target (though I will note that if there were additional items already in the list prior to this `ItemGroup` I think the metadata will be applied to them as well; this could be worked around by enumerating a distinct list of items and then merging those into the pre-existing list).
