### ISSUE TITLE
Investigate SDK test failures and finalize "enable producing reference assemblies by default"

### ISSUE THREAD

**Issue by rokonec** [dotnet/msbuild#8133]
We have reverted https://github.com/dotnet/msbuild/pull/8111.
See https://github.com/dotnet/msbuild/pull/8131 for more details.
Related failing SDK insertion PR was https://github.com/dotnet/sdk/pull/28869

We shall either fix in msbuild or find out how to fix test in SDK.

**Comment by drewnoakes** [comment]
This has been fixed.

**Comment by rainersigwald** [comment]
Note that I've recieved a couple of offline reports of trouble from this that make me suspect we'll have to revert again, but we're not quite there yet.
