### ISSUE TITLE
.net 6.0 NativeReference does not build 

### ISSUE THREAD

**Issue by chrisbrasington** [dotnet/msbuild#8144]
In my csproj I have a native reference like...

```
  <ItemGroup>
    <NativeReference Include="NativeSimple">
      <Kind>Framework</Kind>
      <Frameworks>ExternalAccessory CoreLocation AVFoundation AudioToolbox CoreBluetooth</Frameworks>
      <ForceLoad>true</ForceLoad>
      <IsCxx>true</IsCxx>
      <SmartLink>false</SmartLink>
    </NativeReference>
  </ItemGroup>
```

But any attempt to build on mac errors..

> dotnet build

```
/usr/local/share/dotnet/sdk/6.0.402/Microsoft.Common.CurrentVersion.targets(2193,5): error MSB4062: The "Microsoft.Build.Tasks.ResolveNativeReference" task could not be loaded from the assembly Microsoft.Build.Tasks.Core, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b0
3f5f7f11d50a3a.  Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.
```

What's going on?

**Comment by rainersigwald** [comment]
The `ResolveNativeReferences` task is not supported on .NET Core MSBuild, but I suspect the problem is not just that--the `NativeReference` item you're using doesn't look like the one that's consumed by that task.

What type of project is this? MAUI? Xamarin? What SDK is mentioned in the Project element?

**Comment by karinerock** [comment]
I have the same question... has anybody found a work around or a solution ?

**Comment by devoxyz** [comment]
Same problem here. Anyone please ?

**Comment by rainersigwald** [comment]
@karinerock @devoxyz 

> What type of project is this? MAUI? Xamarin? What SDK is mentioned in the Project element?
