### ISSUE TITLE
"[MSBuild]::VersionGreaterThanOrEquals( 4.6.1, 4.0)" cannot be evaluated

### ISSUE THREAD

**Issue by zvilius** [dotnet/msbuild#8148]
### Issue Description
.NET 4.6.1 project fails to build with:
error MSB4184: The expression "[MSBuild]::VersionGreaterThanOrEquals( 4.6.1, 4.0)" cannot be evaluated. Version string was not in a correct format.

### Steps to Reproduce
I build this project from the command line using tools installed with VS2022, but using the 14.16 toolchain by running:
vcvarsall.bat x64 -vcvars_ver="14.16"

Project file is attached.
[ManagedPromptHandler.zip](https://github.com/dotnet/msbuild/files/9974208/ManagedPromptHandler.zip)

Command line:
msbuild ./Vision/Solutions/win64/vc15.0/VisionInterfaces.sln /property:Configuration="Unicode Debug" /property:Platform=x64 /target:build /maxcpucount /clp:verbosity=minimal;Summary /filelogger /flp:logfile=".\msbuild_log\debug\VisionInterfaces.log" /flp:verbosity=normal

Other projects in the solution build normally.

I probably haven't built this for a few months, but it did build with the VS2022 installation sometime in the fairly recent past. I noticed this failure today with VS2022 17.4, and then backed up to 17.3.6 (previous installed version) and got the same error.

### Actual Behavior
Complete error message:
C:\Program Files\Microsoft Visual Studio\2022\Professional\MSBuild\Current\Bin\amd64\Microsoft.NETFramework.C
urrentVersion.props(117,25): error MSB4184: The expression "[MSBuild]::VersionGreaterThanOrEquals( 4.6.1, 4.0
)" cannot be evaluated. Version string was not in a correct format. [C:\v6.3\Vision\ManagedPromptHandler\proj
ects\win64\vc15.0\ManagedPromptHandler.vcxproj]

### Versions & Configurations
MSBuild version 17.3.1+2badb37d1 for .NET Framework
17.3.1.41501

**Comment by zvilius** [comment]
I've done as you requested. In order to minimize the junk in the binlog I built only the project in question, so the command line that I used for generating the binlog was:

msbuild ./Vision/ManagedPromptHandler/projects/win64/vc15.0/ManagedPromptHandler.vcxproj /property:Configuration="Unicode Debug" /property:Platform=x64 /target:build /maxcpucount /clp:verbosity="minimal;Summary" /bl

The resulting error was the same as in the original report.

**Comment by BenVillalobos** [comment]
It looks like you have a space in front of `4.6.1` when you define `TargetFrameworkVersion` in your vcxproj. Do you still see the error when removing the space?

**Comment by zvilius** [comment]
Bingo! The error is resolved by removing the space.
Thanks ..
Mark Z.

**Comment by alicexudoosan** [comment]
I have a same issue, can't load projects. The error message is [MSBuild]::VersionGreaterThanOrEquals( 4.7.2, net 6.0)" cannot be evaluated. Version string was not in a correct format. C"\Program Files\Microsoft Visual Studio\2022\Professional|MSBuild\Current\Bin\amd64\Microsoft.NETFramwork.CurrentVersion.props.

**Comment by danmoseley** [comment]
@alicexudoosan Looks like you have a space in your project file also?

Btw I expect the team would take a PR that trims spaces in this code path.
