### ISSUE TITLE
Regression in Static Web Assets in newer MSBuild versions

### ISSUE THREAD

**Issue by javiercn** [dotnet/msbuild#8153]
### Issue Description

We think we found a regression in MSBuild on VS 17.5.0 Preview 2.0. Apparently a property is disappearing when an item is being added to a collection.

We call a task with some items. They go in and come out correctly (they have the BasePath property).
We add the outputs back to the item group.
When they are added, the BasePath property is missing.

![image](https://user-images.githubusercontent.com/6995051/201186542-f42a9605-286e-45ca-a68e-6433ff80ee8e.png)
![image](https://user-images.githubusercontent.com/6995051/201186848-f2e8659b-95d8-45b8-b682-012c086239ce.png)
![image](https://user-images.githubusercontent.com/6995051/201186879-43c70812-fd01-4f4e-9323-36cc6a8a53af.png)
![image](https://user-images.githubusercontent.com/6995051/201186897-bdd96bd8-5982-478a-a2f6-0b71fb915477.png)
 
### Steps to Reproduce
* File new project MVC with (individual auth)

### Expected Behavior
Metadata items are preserved

### Actual Behavior
The BasePath metadata item is lost

### Analysis

Analysis is above.

### Versions & Configurations
MSBuild version 17.5.0-preview-22558-04+15b127d24 for .NET Framework
17.5.0.55804

**Comment by rainersigwald** [comment]
Since it's about copying metadata, I suspect this is related to #8098. We should investigate and make sure we fix before 17.5-preview2.

**Comment by rainersigwald** [comment]
I haven't been able to truly minimize the repro but you can run _just_ `msbuild WebApplication1.csproj -t:UpdateExistingPackageStaticWebAssets -bl` to keep any other targets from running but still see the behavior.

**Comment by dougbu** [comment]
@rainersigwald I believe dotnet/aspnetcore#44925 is still blocked on this bug. Any headway on the fix❔

/cc @MackinnonBuck in case there's a new SDK containing a fix during his build ops rotation this week and early next.

**Comment by rainersigwald** [comment]
@dougbu @MackinnonBuck We haven't _fixed_ the issue but we reverted the change that caused it; you should not hit this in recent (last week+) SDKs.

**Comment by sebastienros** [comment]
@rainersigwald updated the version again today and still seeing the same error.

https://dev.azure.com/dnceng-public/public/_build/results?buildId=99424&view=logs&j=b72e85ab-3386-5aa9-6405-3837662d9688&t=42fe3a49-1549-510e-de90-ca27b36d7602

**Comment by marcin-krystianc** [comment]
> Confirmed that reverting #8098 seems to fix the issue, so I'm going to do that while we figure out more.
> 
> fyi @marcin-krystianc -- looks like something didn't have good test coverage and broke.

I've identified where the bug was -> https://github.com/dotnet/msbuild/pull/8098/files#r1038252057. I'm going to re-submit this PR with accompanying tests.

**Comment by brunolins16** [comment]
@marcin-krystianc @rainersigwald Is the fix or the reverting commit available already? I just updated with the latest SDK version (8.0.100-alpha.1.22602.10) and still reproduce the same error.

https://dev.azure.com/dnceng-public/public/_build/results?buildId=102145&view=logs&jobId=4a1f0fe1-d87a-57fd-c29d-71ea15e38f30&j=4a1f0fe1-d87a-57fd-c29d-71ea15e38f30&t=e34518a7-7ef2-58fc-776d-024f679b17d8

**Comment by Forgind** [comment]
Looking at your binlogs, it appears you're actually using an older version of MSBuild than we would have expected. It's two commits before the revert rainersigwald mentioned, but he verified that the correct version is now in installer:main, so hopefully it will work tomorrow.

**Comment by brunolins16** [comment]
> Looking at your binlogs, it appears you're actually using an older version of MSBuild than we would have expected. It's two commits before the revert rainersigwald mentioned, but he verified that the correct version is now in installer:main, so hopefully it will work tomorrow.

Thanks! We will try with tomorrow version and let you know.

**Comment by rainersigwald** [comment]
Regression was fixed and the change is planned to go back in with #8240.
