### ISSUE TITLE
T4 TextTemplating stopped working recently

### ISSUE THREAD

**Issue by sretz** [dotnet/msbuild#8162]
### Issue Description
First of all sorry if this is not the correct repository to report the bug, I was not able to find a better repository.
I don't know when the problem started happening but I believe it would have been after 5 months ago because that is the last time I did an update for https://github.com/innovoft/Innovoft.IO.SplitReaders https://www.nuget.org/packages/Innovoft.IO.SplitReaders . But at some point the T4 import stopped generating files. I only noticed because I started a new project that I need to follow the same basic setup, and it didn't work. I deleted the *.tt.cs files in Innovoft.IO.SplitReaders and the test project no longer worked, so the problem could be older than 5 months.

### Steps to Reproduce
1) download https://github.com/innovoft/Innovoft.IO.SplitReaders
2) build test (only building the library works because otherwise nothing is calling one of the generated methods such as ReadColumnsAdd)

Here is the sections from the csproj file related to T4 that has worked in the past. I don't know how to quote xml.
PropertyGroup
TransformOnBuild: true
OverwriteReadOnlyOutputFiles: true
TransformOutOfDateOnly: false

Import Project="$(VSToolsPath)\TextTemplating\Microsoft.TextTemplating.targets"

### Expected Behavior
T4 create *.tt.cs files that will compiled

### Actual Behavior
As far as I can tell nothing is happening with the T4s.

### Analysis
I think something changed with the T4 system.

### Versions & Configurations
MSBuild version 17.4.0+18d5aef85 for .NET Framework
17.4.0.51802
Windows 10 Pro x64

**Comment by rainersigwald** [comment]
Team Triage: We believe this is an issue with Visual Studio, not MSBuild. Can you [open a feedback ticket instead](https://docs.microsoft.com/visualstudio/ide/feedback-options)?

After it's created, that will open an internal bug which will be routed to the right team. If you post the link here we may be able to help that process go faster.

**Comment by sretz** [comment]
@rainersigwald https://developercommunity.visualstudio.com/t/T4-TextTemplating-stopped-working-recent/10200793?port=1025&fsid=76dbfc1d-aa0a-4ad6-95c4-ea63e345146f

**Comment by rainersigwald** [comment]
Great, it's routed to the T4 team. Thanks for the report!

**Comment by sretz** [comment]
@rainersigwald thanks for the help
