### ISSUE TITLE
Conditional imports including VSToolsPath will throw an exception even if the condition is false

### ISSUE THREAD

**Issue by Forgind** [dotnet/msbuild#8168]
### Issue Description
See title. This has hit multiple internal customers.

### Steps to Reproduce
```
<Project>
  <Import Project="$(VSToolsPath)\Foo.targets" Condition="Exists('$(VSToolsPath)\Foo.targets')" />
  <Target Name="Build" />
</Project>
```

### Expected Behavior
No error

### Actual Behavior
`MSB4226 The imported project "$(VSToolsPath)\Foo.targets" was not found. Also, tried to find "$(VSToolsPath)\Foo.targets" in the fallback search path(s) for $(VSToolsPath) - "C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v17.0" . Confirm that the path in the <Import> declaration is correct, and that the file exists on disk in one of the search paths.`

### Analysis
This error was added in #8095, but it should respect conditions.

**Comment by rainersigwald** [comment]
Workaround
==========

In `C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Current\Bin\MSBuild.exe.config` or your equivalent, comment out the line 

```xml
<property name="VSToolsPath" value="$(MSBuildProgramFiles32)\MSBuild\Microsoft\VisualStudio\v$(VisualStudioVersion)" />
```

**Comment by Forgind** [comment]
Alternate workaround:
Disable the 17.6 changewave

**Comment by AArnott** [comment]
This breaks graph-based restore and build too.

**Comment by AArnott** [comment]
@rainersigwald your workaround did not solve the problem in VS, where the build still fails.

**Comment by Forgind** [comment]
Did the changewave-based workaround work?

The revert should be in VS already, so you can also upgrade to the latest internal preview.

**Comment by AArnott** [comment]
> Disable the 17.6 changewave
> Did the changewave-based workaround work?

I've never heard of a changewave, nor do I know how to disable it.

**Comment by Forgind** [comment]
https://github.com/dotnet/msbuild/blob/main/documentation/wiki/ChangeWaves.md should help.

You can disable change waves for individual projects, but if you want to disable it for an entire solution, so set MSBUILDDISABLEFEATURESFROMVERSION to 17.6 in a command prompt then launch devenv.

**Comment by AArnott** [comment]
Thanks.

**Comment by sailro** [comment]
We first saw this issue in a preview of 17.5 (I'm working on Visual Studio Tools for Unity). And we are still reproducing it with 17.5 GA, 17.6p1 and 17.6 int p2. Disabling the 17.6 changewave works -thank you for the workaround-, but from what I'm reading above my understanding is that the fix should be already in the latest internal preview. Am I missing something ?

**Comment by Forgind** [comment]
Hi @sailro,

Can you first verify that you do have a false condition? Of note, the previous version of this didn't just not throw an error when the condition was false; it just didn't throw errors. That means that you can have an invalid Import with a true condition (or no condition) and have it not error until recently if it uses VSToolsPath.

If your condition is false, are you able to share a [binlog](http://aka.ms/msbuild/binlog)? If you can share one but don't want it publicly visible, you can create a VS feedback ticket and attach it. Then comment here with a link, and I can take a look.

Thanks!

**Comment by yaakov-h** [comment]
The merge in #8171 is tagged as being in VS 17.5 and above, but I'm still seeing this same error in VS17.5. and VS17.6.

The import that I have is:

```xml
<Import Project="$(VSToolsPath)\WebApplications\Microsoft.WebApplication.targets" Condition="'$(VSToolsPath)' != ''" />
```

However, with some debugging on the project, its quite clear that `VSToolsPath` is empty and therefore the condition is false.

Is there something special about a string equality import? I note that this isn't covered by the unit tests in #8171, only false-literal and `Exists(...)` checks.

**Comment by jhennessey** [comment]
I'm hitting the same issue as described in @yaakov-h's [comment](https://github.com/dotnet/msbuild/issues/8168#issuecomment-1621026072). I can work-around the issue by changing the value of `VSToolsPath` in `C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\amd64\MSBuild.exe.config` from

```xml
<property name="VSToolsPath" value="$(MSBuildProgramFiles32)\MSBuild\Microsoft\VisualStudio\v$(VisualStudioVersion)" />
``` 

to:

```xml
<property name="VSToolsPath" value="$(MSBuildExtensionsPath)\Microsoft\VisualStudio\v$(VisualStudioVersion)" />
```

This allows the import to actually succeed. 

Would it make sense to update this value as the current value doesn't seem right?

**Comment by thornch** [comment]
@jhennessey - I got the same issue, thanks for your workaround!

> Would it make sense to update this value as the current value doesn't seem right?

I have created a ticket and hope they will fix the wrong path situation: https://developercommunity.visualstudio.com/t/Wrong-path-configuration-for-VSToolPat/10448097
