### ISSUE TITLE
Issue on build projects on weak virtual hardware after upgrading to .NET 7

### ISSUE THREAD

**Issue by k3yz1** [dotnet/msbuild#8174]
### Issue Description

When I up my docker-compose file with **two or more** .net projects it stuck at build step.
At this time, all memory and CPU are occupied.
In log i see:
 => => # MSBuild version 17.4.0+18d5aef85 for .NET
 => => #   Determining projects to restore...
 => => #   All projects are up-to-date for restore.

at this point it stuck.

When i try up docker-compose file with **one** .net projects - everything works fine.

I have not been able to reproduce the problem on my local machine, but it was always reproduced on a virtual cloud machine.
We use DigitalOcean Droplet on the Basic tariff plan.
The configuration is:
- Shared CPU 1 cpu
- 1 GB Memory
- 25 GB Disk
- Ubuntu 22.04 x64

Previously we used .Net 6 and MSBuild version 17.3.2+561848881 for .NET. and there were no problems.

### Steps to Reproduce

To reproduce the problem, I created 2 test solutions in Visual Studio 2022.

First for .Net 6 and Second for .Net 7.

They contain 2 default "Worker Service" type projects.
With default docker files (as it create VS2022):

.NET 6:
>   FROM mcr.microsoft.com/dotnet/runtime:6.0 AS base
>   WORKDIR /app  
>   FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
>   WORKDIR /src
>   COPY ["WorkerService1/WorkerService1.csproj", "WorkerService1/"]
>   RUN dotnet restore "WorkerService1/WorkerService1.csproj"
>   COPY . .
>   WORKDIR "/src/WorkerService1"
>   RUN dotnet build "WorkerService1.csproj" -c Release -o /app/build  
>   FROM build AS publish
>   RUN dotnet publish "WorkerService1.csproj" -c Release -o /app/publish /p:UseAppHost=false  
>   FROM base AS final
>   WORKDIR /app
>   COPY --from=publish /app/publish .
>   ENTRYPOINT ["dotnet", "WorkerService1.dll"]

.NET 7:
> FROM mcr.microsoft.com/dotnet/runtime:7.0 AS base
> WORKDIR /app
> FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
> WORKDIR /src
> COPY ["WorkerService1/WorkerService1.csproj", "WorkerService1/"]
> RUN dotnet restore "WorkerService1/WorkerService1.csproj"
> COPY . .
> WORKDIR "/src/WorkerService1"
> RUN dotnet build "WorkerService1.csproj" -c Release -o /app/build
> FROM build AS publish
> RUN dotnet publish "WorkerService1.csproj" -c Release -o /app/publish /p:UseAppHost=false
> FROM base AS final
> WORKDIR /app
> COPY --from=publish /app/publish .
> ENTRYPOINT ["dotnet", "WorkerService1.dll"]

Second service is identical.

And default docker-compose file (same for both solutions):

> version: '3.4'
> 
> services:
>   workerservice1:
>     image: ${DOCKER_REGISTRY-}workerservice1
>     build:
>       context: .
>       dockerfile: WorkerService1/Dockerfile> 
>   workerservice2:
>     image: ${DOCKER_REGISTRY-}workerservice2
>     build:
>       context: .
>       dockerfile: WorkerService2/Dockerfile

The test solution for .NET 6 works fine when I start 
`
docker-compose up
`

Solution for .NET 7 stuck  just like my project.

**This is reproduced only on a weak virtual machine, which I wrote about above.**

**Comment by BenVillalobos** [comment]
Can you try running msbuild with a higher verbosity? Try adding `/v:d` to your msbuild calls.

**Comment by k3yz1** [comment]
thanks for the answer Ben, I'm attaching logs.

pay attention:

.NET 7 build:
#23 245.1 Time Elapsed 00:04:03.37

.NET 6 build:
#23 14.46 Time Elapsed 00:00:13.17

these are absolutely identical default projects.

my project also build, after 40 minutes of waiting.

[log for .NET6 build](https://1drv.ms/u/s!AqvlCiQ1270xhZxkmj3BhYVLC-FunQ?e=wJC4kt)
[log for .NET7 build](https://1drv.ms/u/s!AqvlCiQ1270xhZxlBw49tNMha_SdXQ?e=f8Q5KA)

**Comment by k3yz1** [comment]
The problem is solved by adding a swap file.

The question remains - why the build worked before switching to .NET 7?

**Comment by AR-May** [comment]
It could be related to the issue https://github.com/dotnet/runtime/issues/75049. Could you try again with the recent .NET SDK?
