### ISSUE TITLE
net7: Razor class library - Missing CSS bundle in published package when built using msbuild /maxCpuCount

### ISSUE THREAD

**Issue by hakenr** [dotnet/msbuild#8175]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Razor class library (Blazor) with CSS isolation.
Published as NuGet package using `<GeneratePackageOnBuild>true</GeneratePackageOnBuild>`.
Built using `"C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\amd64\msbuild.exe" /m`.
After upgrade to net7 and VS 17.4.0. the generated `.nupkg` does not include `/staticwebassets/Name.bundle.scp.css`. (all other static assets are present).

When the `/m` switch is removed from the `msbuild` call, the CSS file is present in the resulting `.nupkg`.
When the project is multi-targeted to `net6`+`net7`, the CSS file is present in the resulting `.nupkg`.
(Weird behavior observed with `/m:1` switch. On our build server, the CSS file is there. On my dev-box, it is not.)

### Expected Behavior

The generated `.nupkg` should contain the CSS bundle no matter which TargetFramework/maxCpuCount is used.

### Steps To Reproduce

Unfortunately, I was not successful in reproducing the issue with a minimal project setup.

I prepared a setup (branch) in our repo which reproduces the issue:
https://github.com/havit/Havit.Blazor/tree/net7-msbuild-repro

Call msbuild with `/m` from project root directory to reproduce the issue:
```
"C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\amd64\msbuild.exe" /m
```
Output files (without CSS bundle):
`.\Havit.Blazor.Components.Web\bin\Debug\Havit.Blazor.Components.Web.3.2.0.nupkg`
`.\Havit.Blazor.Components.Web.Bootstrap\bin\Debug\Havit.Blazor.Components.Web.Bootstrap.3.2.0.nupkg`

Call msbuild without any switches and the CSS file will be in the output:
```
"C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\amd64\msbuild.exe"
```

### .NET Version

7.0.100

### Anything else?

I was not sure in which repository should I file the issue. In the end I decided for `aspnetcore` as there is a good probability the issue is located in the `.target` files and/or build-tasks owned by the team?

**Comment by javiercn** [comment]
@hakenr I have moved this issue to the MSBuild repo. What I am observing is that in one case, the item "magically" disappears. So this might be related to a similar issue that we investigated recently.

From the binlog I can see that the item is correctly added as content:
![image](https://user-images.githubusercontent.com/6995051/202167862-f7c12e12-c649-4864-9d41-3eb74326b855.png)

When it gets here it is somehow ignored:
![image](https://user-images.githubusercontent.com/6995051/202167953-fca391e9-974a-4d7d-b725-d29b8c43ea81.png)

The relevant target is:
![image](https://user-images.githubusercontent.com/6995051/202167994-a5405156-1e03-4f14-8e90-0d9aea3ed338.png)

I might be missing something on my analysis, but if I am, I can't tell from the binlog where the item is being removed, and the definition is equivalent to the one for other files that are being included.

**Comment by maridematte** [comment]
Reopening so we can try to get a repro, and start tracking this once again.

**Comment by JaynieBai** [comment]
@maridematte Repro this issue with the following steps.
    1. Download  the project and change the TargetFramework to net9.0

> Smaller repo which currently reproduces the issue:
> [Havit.Bt.Blazor.zip](https://github.com/dotnet/aspnetcore/files/10017092/Havit.Bt.Blazor.zip)

   2. msbuild /p:DeployOnBuild=true /m /bl
  
**Actual Results:**  In the package staticwebassets, some assets are missing.

From the binlog, the assets are lost in the _PackageFiles items

[msbuild8175.binlog.txt](https://github.com/user-attachments/files/19845966/msbuild8175.binlog.txt)

![Image](https://github.com/user-attachments/assets/efb74d5e-cbbd-4522-9f93-61b4a13b6abe)

![Image](https://github.com/user-attachments/assets/57c2f5c7-f469-4177-b6cb-6fff42f3aa25)
