### ISSUE TITLE
MSBuild Version Comparison Intrinsic Functions Could Be More Robust

### ISSUE THREAD

**Issue by BenVillalobos** [dotnet/msbuild#8177]
It looks like you have a space in front of `4.6.1` when you define `TargetFrameworkVersion` in your vcxproj. Do you still see the error when removing the space?

_Originally posted by @BenVillalobos in https://github.com/dotnet/msbuild/issues/8148#issuecomment-1318998032_

**Comment by BenVillalobos** [comment]
We talked about trimming all incoming strings, or logging a warning whenever this occurs. Customers shouldn't have to deal with situations like this.

**Comment by BenVillalobos** [comment]
We have many Version comparison functions here:

https://github.com/dotnet/msbuild/blob/06231decdb6530a9e98d752f2a90661f66e7a229/src/Build/Evaluation/IntrinsicFunctions.cs#L497-L525

They all call SimpleVersion.Parse, which calls RemoveTrivia. looks like the Trim() should go in here:

https://github.com/dotnet/msbuild/blob/06231decdb6530a9e98d752f2a90661f66e7a229/src/Build/Utilities/SimpleVersion.cs#L128

It should ideally be a Trim or some special (read: efficient) Span logic to be more efficient

**Comment by zvilius** [comment]
I would like to provide a resolution for this, since it was my issue that prompted this one.
I would be a first time contributor.

**Comment by rainersigwald** [comment]
@zvilius awesome! I assigned the issue to you. Let us know if you have questions, or feel free to put up a PR or draft PR if it's easier to communicate that way.
