### ISSUE TITLE
Include Exclude doesn't seem to work Xplat when path separator is `/` (forward slash)

### ISSUE THREAD

**Issue by mikes-gh** [dotnet/msbuild#8188]
### Issue Description

Problem encountered in https://github.com/MudBlazor/MudBlazor/pull/5801
```
  <Target Name="IncludeGeneratedStaticFiles" DependsOnTargets="WebCompiler" BeforeTargets="BeforeBuild">
    <ItemGroup>
      <!--Include without duplication-->
      <_NewCompiledDocsCssFiles Include="wwwroot/MudBlazorDocs.min.css" Exclude="@(Content)" />
      <Content Include="@(_NewCompiledDocsCssFiles)" />
    </ItemGroup>
  </Target>
```
It seems `Include="wwwroot/MudBlazorDocs.min.css"` pattern with `Exclude=@(Content)` fails to remove duplicates on windows.  I need to use `\` (backslash) for path separator in order for it to work on Windows and Linux/mac

In all our project files we normally use `/ ` (forward slash) for path separators and the problem didn't show up on mac or build servers (Linux).

However windows users local builds started to fail.

In the following example `wwwroot/MudBlazorDocs.min.css` as the `Include` pattern fails on Windows platform with duplicate content files.

If I change it to  `wwwroot\MudBlazorDocs.min.css` the Content is correct and the build succeeds with no duplicate Content files

### Steps to Reproduce

Repo

Build https://github.com/MudBlazor/MudBlazor/pull/5801 on Windows (fails)
Build https://github.com/MudBlazor/MudBlazor/pull/5801 on OS with `/` path separator (succeeds)

Alternatively use HEAD of dev and change the following lines to a forward slash the build will fail on windows but succeed on Linux/mac

https://github.com/MudBlazor/MudBlazor/blob/2f65df6b8d39ddd7109bce58648ad60be606f177/src/MudBlazor/MudBlazor.csproj#L91
https://github.com/MudBlazor/MudBlazor/blob/2f65df6b8d39ddd7109bce58648ad60be606f177/src/MudBlazor/MudBlazor.csproj#L92
https://github.com/MudBlazor/MudBlazor/blob/2f65df6b8d39ddd7109bce58648ad60be606f177/src/MudBlazor.Docs/MudBlazor.Docs.csproj#L113

### Expected Behavior
To be able to use `/` everywhere as the path separator for Xplat builds

### Actual Behavior
The Include Exclude pair fails and duplicate files are passed to `Microsoft.NET.Sdk.Razor.StaticWebAssets`
`C:\Program Files\dotnet\sdk\7.0.100\Sdks\Microsoft.NET.Sdk.Razor\targets\Microsoft.NET.Sdk.Razor.StaticWebAssets.target
s(419,5): error : Two assets found targeting the same path with incompatible asset kinds: `

### Analysis

Something to do with path separators and string comparisons only when using forward slash as path separator
Seems similar to https://github.com/dotnet/msbuild/issues/724
However that looks like it had a fix

### Versions & Configurations
```
dotnet msbuild --version
MSBuild version 17.4.0+18d5aef85 for .NET
17.4.0.51802
```
* If applicable, include the version of the tool that invokes MSBuild (Visual Studio, dotnet CLI, etc):
```
dotnet --version
7.0.100
```

**Comment by JaynieBai** [comment]
@rainersigwald I'd like to have a look at issue

**Comment by JaynieBai** [comment]
[Uploading msbuild.txt…](It's msbuild binlog file)  Include="wwwroot/MudBlazorDocs.min.css" pattern with Exclude=@(Content) fails to remove duplicates on windows.

**Comment by mikes-gh** [comment]
@JaynieBai Thanks for looking into this.  This was my suspicions too.  Presumably the comparison should be path separator agnostic thought right?

**Comment by JaynieBai** [comment]
MSBuild the following project.  Not sure why the item outside of target works with excluding the specified file correctly. But in the target item exclude doesn't work. Is there any difference when parse  between them?  @rainersigwald 
`<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
	<ItemGroup>
		
		<_NewCompiledCssFiles Include="File/Program.cs" Exclude="File\Program.cs"  />
	</ItemGroup>
	<Target Name="Message">
		<ItemGroup>
			
			<_NewCompiledCssFiles Include="File/Program.cs" Exclude="File\Program.cs"  />
			<Content Include="@(_NewCompiledCssFiles)" />
		</ItemGroup>
		<Message Text="Current Content is @(_NewCompiledCssFiles)" Condition="'@(_NewCompiledCssFiles)' != '' "></Message>
	</Target>
</Project>`
![image](https://user-images.githubusercontent.com/26814373/207001290-1ca99b56-3666-457d-a11b-53c3f624e324.png)

**Comment by JaynieBai** [comment]
@JanKrivanek @rainersigwald   I changed the tests about item with include and exlude under the target and made a draft pr. 16 tests fails.

**Comment by JanKrivanek** [comment]
This is one of the differences in `Exclude` behavior of global vs traget local items instantiation (example of other difference: https://github.com/dotnet/msbuild/issues/2491). This is caused by the fact that both are handled by a different code (long running epic to address this: https://github.com/dotnet/msbuild/issues/1124).

In a scope of this issue only the paths normalization behavior was addressed.
