### ISSUE TITLE
Please do not clear $(ClickOncePublishDir) unconditionally 

### ISSUE THREAD

**Issue by anderslaub** [dotnet/msbuild#8196]
https://github.com/dotnet/msbuild/blob/d797c48da13aaa4dc7ae440ed7603c990cd44317/src/Tasks/Microsoft.Common.CurrentVersion.targets#L5718

Previously $(publishdir) was cleared _if_ it was the default value. Setting PublishDir to a solution specific path ensured that the folder was not cleared.

It's a major breaking change which is now breaking our local rebuilds that the `ClickOncePublishDir` folder is suddenly being removed completely on `Clean` target.  (`ClickOncePublishDir == PublishDir` by default.)

**Comment by andedani** [comment]
Yes, it broke my build too.

**Comment by rainersigwald** [comment]
We have been tracking this as https://developercommunity.visualstudio.com/t/msbuild-complation-failure-after-VS-2022/10202200, which offers this **workaround** until we can ship a fix:

In a [`Directory.Build.targets`](https://learn.microsoft.com/visualstudio/msbuild/customize-your-build#directorybuildprops-and-directorybuildtargets), add

```xml
<Project>
 <!-- override this target to its old behavior to work around https://developercommunity.visualstudio.com/t/msbuild-complation-failure-after-VS-2022/10202200
      Note that this might break any ClickOnce packaging you have. -->
  <Target Name="CleanPublishFolder">
    <RemoveDir
        Directories="$(ClickOncePublishDir)"
        Condition="'$(ClickOncePublishDir)'=='$(OutputPath)app.publish\' and Exists('$(ClickOncePublishDir)')"/>
  </Target>
</Project>
```

I'll leave this open since the fix will be in this repo.

**Comment by sujitnayak** [comment]
Please do not assume that overriding PublishDir would mean that it will not be cleaned during Clean. It is not a guaranteed behavior you should take a dependency on. If you want to change the behavior of the target, you can override it in your targets or project file with a custom target.

**Comment by sujitnayak** [comment]
The change has been undone until a correct fix is implemented that does not cause failures during Clean.
