### ISSUE TITLE
Conditional include of resources.resx not working

### ISSUE THREAD

**Issue by njannink** [dotnet/msbuild#8197]
### Issue Description
I try to update my directory.build.props file to conditionally include a resources.resx when its available, but that doesn't seem to work. I don't know if this is a bug or by design.

### Steps to Reproduce
Add the following section to your directory.build.props file

```
  <ItemGroup Condition="Exists('./Properties/Resources.resx')">
    <Compile Update="Properties\Resources.Designer.cs" DesignTime="True" AutoGen="True" DependentUpon="Resources.resx" />
    <EmbeddedResource Update="Properties\Resources.resx" Generator="ResXFileCodeGenerator" LastGenOutput="Resources.Designer.cs" />
  </ItemGroup>
```

### Expected Behavior
Resources.designer.cs file is updated when resource file changes

### Actual Behavior
Resource designer file doesn't change when resx file changes.

**Comment by JaynieBai** [comment]
I tested it locally,  this works in Directory.Build.targets.

**Comment by njannink** [comment]
Never though of this, but indeed putting it in the Directory.Build.targets file works
