### ISSUE TITLE
Replacing a property group with an import of a project which has the same property group changes behavior

### ISSUE THREAD

**Issue by axodox** [dotnet/msbuild#8200]
### Issue Description

We are using MSBuild with a Visual C++ project. We would like to set a property called LocalDebuggerCommand from an imported project (in Nuget packaged SDK, but this has nothing to do with Nuget, it happens without it too), this however does not work for us.

### Steps to Reproduce

Create a C++ dll library app. Create a property group in the vcxproj and set the LocalDebuggerCommand to some exe, observe that it works properly (this property defines the app to start on launch). Now replace the property group with an import, and add the property group in the imported project (directly, without a target), observe that now the property has no effect.

### Expected Behavior

Properties should work the same way when set by imported projects.

### Actual Behavior

Some properties (e.g. LocalDebuggerCommand) do not work when set by imported projects.

### Analysis

We suspect that either:
* Our assumption that the import tag for msbuild is like a import pragma in C++ is wrong. The import tag does not import the property where it is placed - according to MSDN it should
* Some properties are read directly from the msbuild project file by tools directly, and they do not check imported projects for these values - this would mean it is a limitation of visual studio

### Versions & Configurations

MSBuild version 17.4.0+18d5aef85 for .NET Framework
17.4.0.51802

Windows 11 22H2
VS 2022 17.4.1

**Comment by Forgind** [comment]
I tried this out with a generic property in a csproj, and it worked as expected—that is, adding something like `<Import Project="Import.props" />` and setting a property in it made that property available when I then tried to print that out. With that in mind, I suspect this is a CPS-specific issue. @lifengl, does that sound right to you?

**Comment by JaynieBai** [comment]
This C++ Project [Dll1.zip](https://github.com/dotnet/msbuild/files/11351709/Dll1.zip) set the property LocalDebuggerCommand in the imported project. it works as expected. 
@axodox  Could you have a look if there are any differences between your project and mine?

**Comment by danmoseley** [comment]
The /pp switch might help show ordering here.
