### ISSUE TITLE
Delete Microsoft.VisualStudioVersion.v*.Common.props files

### ISSUE THREAD

**Issue by Forgind** [dotnet/msbuild#8203]
It seems like we never import them; can we just remove them?

**Comment by Nirmal4G** [comment]
It is imported here...

https://github.com/dotnet/msbuild/blob/59c2ff861191e4af4a479d92efdb809812cabe01/src/Tasks/Microsoft.Common.props#L111

Is it really needed? When will `VisualStudioVersion` be empty? .NET SDK context?

**Comment by rainersigwald** [comment]
It's empty when you start a build that doesn't have it defined as an environment variable (the `Developer Command Prompt for VS 2022` sets it).

I don't know if it's "really" needed and it does feel like this could be simplified but I don't think it's worth much investigation time.
