### ISSUE TITLE
runtime build stuck when DOTNET_CLI_USE_MSBUILD_SERVER is set to 1

### ISSUE THREAD

**Issue by smasher164** [dotnet/msbuild#8232]
### Issue Description
On the latest (as of https://github.com/dotnet/runtime/commit/41ae1aebcce81dbe742bad16533b70d0f46ef7c8) commit of the runtime, the build gets stuck indefinitely. I tried building five times, pulling in latest changes, and clearing all artifacts. The build displays and gets stuck at `Microsoft.NETCore.App.Runtime ->` which is in the packing stage. It went up to one hour for one of the executions, before I killed it.

### Steps to Reproduce
0. Ensure that `DOTNET_CLI_USE_MSBUILD_SERVER` is set to `1`.
1. `.\build.cmd -allconfigurations`

Unable to attach binlog when building with `-bl` since the build was cancelled early.

### Expected Behavior
Build is successful.

### Actual Behavior
Build is stuck on `Microsoft.NETCore.App.Runtime ->`.

### Analysis
Steps taken to debug:
1. Attached a debugger to the host process, which seemed to just be stuck in `System.Threading` code.
2. Process tree just shows a bunch of MSBuild.dll invocations:
![process-tree](https://user-images.githubusercontent.com/12636891/206589980-bfc51be4-e81a-4932-95a8-0577348aba56.png)
3. Using `procexp`, I couldn't pinpoint a handle that referenced `Microsoft.NETCore.Runtime`.
4. @hoyosjs suggested rebuilding with `DOTNET_CLI_USE_MSBUILD_SERVER` set to `0`, and the build was successful.

Perhaps there's some deadlock in the msbuild server?

### Versions & Configurations
- On Windows 11 x86_64
- `dotnet msbuild --version` prints
```
MSBuild version 17.4.0+18d5aef85 for .NET
17.4.0.51802
```
- `dotnet --version` prints `7.0.100`

/cc @rokonec

**Comment by rokonec** [comment]
I tried it with dotnet SDK 7.0.101 and it worked on my computer. Tooked ~ 2hours though for clean build and 10 minutes for rerun.
@smasher164 Was it clean build? Any other hints on repro steps? Can you still repro it? Was this repro consistent?

**Comment by smasher164** [comment]
Closing because I can no longer repro this. Thank you!
