### ISSUE TITLE
Error When Using Dotnet Publish via Command Line

### ISSUE THREAD

**Issue by MatthewMartinPlanview** [dotnet/msbuild#8241]
### Issue Description

We are using a Github action on a self-hosted runner to publish a ClickOnce application to a network share from a profile. When calling `dotnet publish` via the command line on the host machine, we receive an error complaining about build tasks not being found in the common targets file.

### Steps to Reproduce

While we are using this in a self-hosted runner (Windows Server), this behavior happens locally as well. Running the following command via a Powershell window produces the error:

`dotnet publish "C:\Users\MatthewMartin\source\repos\e1-rendertest\src\PrmRenderTest.UI\PrmRenderTest.UI.csproj" "/p:PublishProfile=C:\Users\MatthewMartin\source\repos\e1-rendertest\src\PrmRenderTest.UI\Properties\PublishProfiles\ClickOnceProfile.pubxml"`

### Expected Behavior

Expected that publish succeeds normally.

### Actual Behavior

Error produced is: C:\Program Files\dotnet\sdk\7.0.100\Microsoft.Common.CurrentVersion.targets(4149,5): error MSB4062: The "Microsoft.Build.Tasks.RequiresFramework35SP1Assembly" task could not be loaded from the assembly Microsoft.Build.Tasks.Core, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a.  Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask. [C:\actions-runner\_work\e1-rendertest\e1-rendertest\src\PrmRenderTest.UI\PrmRenderTest.UI.csproj]

### Analysis

Editing the `build\.dotnet\sdk\7.0.100\Microsoft.Common.CurrentVersion.targets` file to remove the following prompts another error (of the same kind) related to the UpdateManifest task.

```
<RequiresFramework35SP1Assembly
      ReferencedAssemblies="@(Reference)"
        ErrorReportUrl="$(_DeploymentFormattedErrorReportUrl)"
        TargetFrameworkVersion="$(TargetFrameworkVersion)"
        CreateDesktopShortcut="$(CreateDesktopShortcut)"
        SigningManifests="$(SignManifests)"
        Assemblies="@(_DeploymentManifestDependencies)"
        DeploymentManifestEntryPoint="@(_DeploymentResolvedDeploymentManifestEntryPoint)"
        EntryPoint="@(_DeploymentResolvedManifestEntryPoint)"
        Files="@(_DeploymentManifestFiles)"
        SuiteName="$(SuiteName)" >
      <Output TaskParameter="RequiresMinimumFramework35SP1" PropertyName="_DeploymentRequiresMinimumFramework35SP1" />
    </RequiresFramework35SP1Assembly>
```

The .csproj file contains references to the latest versions of Microsoft.Build.Tasks.Core (17.4.1) and Microsoft.Build.Utilities.Core (17.4.1). Updating these references has no effect.

It seems that MSBuild is loading older assemblies (15.1.1) for the above mentioned libs.

### Versions & Configurations

Visual Studio 2022 Professional

Microsoft (R) Build Engine version 4.8.9037.0
[Microsoft .NET Framework, version 4.0.30319.42000]
Copyright (C) Microsoft Corporation. All rights reserved.

4.8.9037.0

### Publish Profile

```
<?xml version="1.0" encoding="utf-8"?>
<!--
https://go.microsoft.com/fwlink/?LinkID=208121.
-->
<Project>
  <PropertyGroup>
    <ApplicationRevision>5</ApplicationRevision>
    <ApplicationVersion>1.0.0.*</ApplicationVersion>
    <BootstrapperEnabled>False</BootstrapperEnabled>
    <Configuration>Release</Configuration>
    <CreateWebPageOnPublish>False</CreateWebPageOnPublish>
    <GenerateManifests>true</GenerateManifests>
    <Install>True</Install>
    <InstallFrom>Unc</InstallFrom>
    <InstallUrl>\\share\BrowserRenderTest\</InstallUrl>
    <IsRevisionIncremented>True</IsRevisionIncremented>
    <IsWebBootstrapper>False</IsWebBootstrapper>
    <MapFileExtensions>False</MapFileExtensions>
    <OpenBrowserOnPublish>False</OpenBrowserOnPublish>
    <Platform>Any CPU</Platform>
    <PublishDir>\\share\BrowserRenderTest\</PublishDir>
    <PublishUrl>\\share\BrowserRenderTest\</PublishUrl>
    <PublishProtocol>ClickOnce</PublishProtocol>
    <PublishReadyToRun>True</PublishReadyToRun>
    <PublishSingleFile>True</PublishSingleFile>
    <SelfContained>True</SelfContained>
    <SignatureAlgorithm>sha256RSA</SignatureAlgorithm>
    <SignManifests>False</SignManifests>
    <TargetFramework>net6.0-windows</TargetFramework>
    <UpdateEnabled>True</UpdateEnabled>
    <UpdateMode>Foreground</UpdateMode>
    <UpdateRequired>False</UpdateRequired>
    <WebPageFileName>Publish.html</WebPageFileName>
    <ManifestCertificateThumbprint>REDACTED</ManifestCertificateThumbprint>
    <ManifestKeyFile>PrmRenderTest.UI_TemporaryKey.pfx</ManifestKeyFile>
    <CreateDesktopShortcut>False</CreateDesktopShortcut>
    <ProductName>Browser Render Test</ProductName>
    <PublisherName>Planview</PublisherName>
    <ExcludeDeploymentUrl>False</ExcludeDeploymentUrl>
    <RuntimeIdentifier>win-x86</RuntimeIdentifier>
  </PropertyGroup>
  <ItemGroup>
    <BootstrapperPackage Include="Microsoft.NetCore.DesktopRuntime.6.0.x64">
      <Install>True</Install>
      <ProductName>.NET Desktop Runtime 6.0.8 (x64)</ProductName>
    </BootstrapperPackage>
  </ItemGroup>
</Project>
```

**Comment by John-Hart** [comment]
Dotnet publish does not support publishing ClickOnce applications.  You will need to use msbuild instead.  Here's a document that should help: https://learn.microsoft.com/en-us/visualstudio/deployment/building-clickonce-applications-from-the-command-line?view=vs-2022

**Comment by Forgind** [comment]
Closing per John-Hart's comment.

**Comment by HughWarrington** [comment]
OK but could we improve the behaviour of `dotnet publish` so that it outputs 'Publishing a ClickOnce profile is not supported with this tool' or something, instead of crashing with a cryptic error message? It's clear from the multiple tickets that the current behaviour has consumed many developer hours on investigation and Github activity.

**Comment by HughWarrington** [comment]
Huh, I see some commits on #29951, after it was marked as closed in favour of this ticket, which look like they might fix the issue after all?

**Comment by Forgind** [comment]
I don't know all of what would have to be changed to properly support this scenario via dotnet publish, but rainersigwald's commit mentioned the bad error message, so I'm guessing the plan is just around improving the error experience. May be wrong, though; I didn't look at this thoroughly.

**Comment by evan-boissonnot** [comment]
why the dotnet publish can't be a proxy to msbuild for this target ClickOnce ?

**Comment by Forgind** [comment]
dotnet publish _does_ use MSBuild, but I believe ClickOnce uses other parts of Visual Studio/Build Tools that aren't baked into MSBuild directly.
