### ISSUE TITLE
`maxcpucount` : Is there a similar option while building via GUI

### ISSUE THREAD

**Issue by lalith-mcw** [dotnet/msbuild#8272]
Is there a similar option for `--maxcpucount` while building via GUI

When I build multiple njsproj files that blocks and doesn't build in parallel via gui but vcxproj does build in parallel without any input or `/MP` config set in the project file
![image](https://user-images.githubusercontent.com/84698958/210067572-948e4f4b-0543-46fb-9379-27202763be11.png)

But while using GUI to build the solution file the njsproj files builds in a sequential way and restricts the compilation for only one project at a time but vcxproj is building in parallel 
![image](https://user-images.githubusercontent.com/84698958/210068136-44d2eeca-15ce-4b3d-8757-dd1c94238da2.png)

**Comment by danmoseley** [comment]
By GUI you mean Visual Studio?

There is a max number of parallel builds option in the Visual Studio options, what do you have it set to?

It may have changed, but my memory is that inside VS, MSBuild does not do parallelism, but instead builds each project when instructed, and VS handles parallelism.

**Comment by lalith-mcw** [comment]
> By GUI you mean Visual Studio?

Yeah 

> There is a max number of parallel builds option in the Visual Studio options, what do you have it set to?

By default its 32 right ?

> It may have changed, but my memory is that inside VS, MSBuild does not do parallelism, but instead builds each project when instructed, and VS handles parallelism.

https://learn.microsoft.com/en-us/visualstudio/ide/reference/options-dialog-box-projects-and-solutions-build-and-run?view=vs-2022

```
Maximum number of parallel project builds

Specifies the maximum number of C++ and C# projects that can build at the same time. To optimize the build process, the maximum number of parallel project builds is automatically set to the number of CPUs of your computer. The maximum is 32.
```
Its only restricted to c++ and c# project it seems in my case its node js project which doesn't work

**Comment by danmoseley** [comment]
I would open a VS feedback issue for that. They can either explain why or they can consider changing it. It may be that the Node project system didn't opt into it or there may be a good reason why it can't.

**Comment by rainersigwald** [comment]
Team Triage: We believe this is an issue with the Node integration in Visual Studio, not MSBuild. Can you [open a feedback ticket instead](https://docs.microsoft.com/visualstudio/ide/feedback-options)?

After it's created, that will open an internal bug which will be routed to the right team. If you post the link here we may be able to help that process go faster.
