### ISSUE TITLE
The task factory "RoslynCodeTaskFactory" could not be loaded when build from visual studio for mac

### ISSUE THREAD

**Issue by AkiSakurai** [dotnet/msbuild#8274]
When building a project with RoslynCodeTaskFactory from Visual Studio for Mac (Version 17.4.2), it report the following error.
The problem do not happens when build using dotnet build.
The problem only happens when build with .net 7 sdk

```
Error MSB4175: The task factory "RoslynCodeTaskFactory" could not be loaded from the assembly "/usr/local/share/dotnet/sdk/7.0.101/Microsoft.Build.Tasks.Core.dll". Could not load file or assembly 'System.CodeDom, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. Could not find or load a specific file. (0x80131621) (MSB4175) (RoslynTest)
```

``` csproj
<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    </PropertyGroup>
    <Target Name="Test" AfterTargets="Compile">
        <HelloWorld />
    </Target>
    <UsingTask
    TaskName="HelloWorld"
    TaskFactory="RoslynCodeTaskFactory"
    AssemblyFile="$(MSBuildToolsPath)\Microsoft.Build.Tasks.Core.dll" >
    <ParameterGroup />
    <Task>
        <Reference Include="System.Xml"/>
        <Using Namespace="System"/>
        <Using Namespace="System.IO"/>
        <Code Type="Fragment" Language="cs">
    <![CDATA[
    // Display "Hello, world!"
    Log.LogError("Hello, world!");
    ]]>
        </Code>
    </Task>
    </UsingTask>
</Project>

```

**Comment by jrdodds** [comment]
I tested to see if I received the same results. I saw some differences but the essential issue reported is the same.

I have "Visual Studio for Mac 17.4.2" and "Visual Studio for Mac 17.5 Preview" installed on the same machine. My machine has macOS Monterey v12.6.2 and has an Apple M1 Pro chip (ARM).

The example project file, as provided, failed with `dotnet build` for me with the error "error MSB3755: Could not find reference "System.Xml".  ...". I altered the project file to remove the line `<Reference Include="System.Xml"/>`. (The `UsingTask` is copied from the [documentation](https://learn.microsoft.com/en-us/visualstudio/msbuild/msbuild-roslyncodetaskfactory?view=vs-2022#hello-world).)

My revised file for testing was:

```XML
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <Target Name="Test" AfterTargets="Compile">
    <Message Text="in Test" />
    <HelloWorld />
  </Target>

  <UsingTask TaskName="HelloWorld" TaskFactory="RoslynCodeTaskFactory" AssemblyFile="$(MSBuildToolsPath)\Microsoft.Build.Tasks.Core.dll">
    <ParameterGroup />
    <Task>
      <Using Namespace="System"/>
      <Using Namespace="System.IO"/>
      <Code Type="Fragment" Language="cs">
        <![CDATA[
        // Display "Hello, world!"
        Log.LogError("Hello, world!");
        ]]>
      </Code>
    </Task>
  </UsingTask>

</Project>

```

This project 

- built with `dotnet build`, 
- built with Visual Studio for Mac 17.5 Preview, 
- and failed to build with Visual Studio for Mac 17.4.2.

The error description in Visual Studio for Mac 17.4.2 matches the issue report.

Changing the `TargetFramework` to `net6.0` made no difference.

**Comment by AkiSakurai** [comment]
Fixed

**Comment by jrdodds** [comment]
My own quick testing with VS for Mac 17.6.10 (build 428) seems to confirm the report from @phillippschmedt.

**Comment by phillippschmedt** [comment]
> My own quick testing with VS for Mac 17.6.10 (build 428) seems to confirm the report from @phillippschmedt.

I reported it also here https://github.com/dotnet/msbuild/issues/9878 (and mentioned a workaround). It seems like vs for mac is dead already.
