### ISSUE TITLE
MSBuild API get wrong outputPath on Linux + nodeJS

### ISSUE THREAD

**Issue by JaneySprings** [dotnet/msbuild#8291]
[**Example**](https://github.com/JaneySprings/PathBug)

### Issue Description
I am creating an VSCode extension that allow debug .NET MAUI apps. I use Microsoft.Build NuGet to get the path to output directory (OutputPath property). 
I noticed that on Linux, when running from NodeJS, msbuild outputs a path containing an incorrect directory separation char ' \\ '.
<img width="269" alt="image" src="https://user-images.githubusercontent.com/48021947/211402099-44c0ccf8-347b-4252-a04f-66ea61992a79.png">

### Steps to Reproduce
You can take my example above and execute run.sh (don't forget to change the path to MSBuild.dll in the netapp/Program.cs file on your)

### Versions & Configurations
dotnet 7.0.100
Ubuntu 22.04 (ARM64)
NodeJS latest

I'm not sure if this is an MSBuild or DotNet bug, but maybe you can help me understand what is the reason for this behavior

**Comment by baronfel** [comment]
The slashes are hard-coded - you can check the evaluation with an https://aka.ms/binlog, but here's what a lot of the default OutputPath-setting code looks like:

```xml
    <OutputPath Condition="'$(OutputPath)' == '' and '$(PlatformName)' == 'AnyCPU'">$(BaseOutputPath)$(Configuration)\</OutputPath>
    <OutputPath Condition="'$(OutputPath)' == '' and '$(PlatformName)' != 'AnyCPU'">$(BaseOutputPath)$(PlatformName)\$(Configuration)\</OutputPath>
    <OutputPath Condition="!HasTrailingSlash('$(OutputPath)')">$(OutputPath)\</OutputPath>
```

.NET File-manipulation APIs can handle slash-mismatches generally - I'd expect things like `File.Create` and `Path.GetFullPath` to handle any slash-mismatches well on any platform, so I would suggest that your test app use `Path.GetFullPath` as a workaround.

A larger question though is: _should we move MSBuild to use property functions like `Path.Combine` in more places_? Should we regard it as a 'smell' to manually construct paths? If we did start using `Path.Combine` in more places, would tools like the structured log viewer be able to understand the changes in paths across logs taken from different operating systems?

**Comment by rainersigwald** [comment]
> A larger question though is: _should we move MSBuild to use property functions like `Path.Combine` in more places_? Should we regard it as a 'smell' to manually construct paths?

I have been thinking on this and thinking "yes" but also "ew the syntax is so ugly", which holds me back from proposing it.

**Comment by JaneySprings** [comment]
it looks strange, because without exec (node js process launcher) if you run dll from terminal the path will be correct, without ' \\ '
<img width="677" alt="image" src="https://user-images.githubusercontent.com/48021947/211406284-f21c60a6-7a84-416a-9c02-586eb624315f.png">

**Comment by baronfel** [comment]
Oh, I missed that part of the issue. I'd be really interested in what a binlog said about your environment - consider adding the https://www.nuget.org/packages/MSBuild.StructuredLogger library and add that logger to your project's evaluation, so that you can dig into the differences.

**Comment by JaneySprings** [comment]
How to add binlog to Microsoft.Build.Evaluation.Project? I didn't find any ctors/properties to add a Logger
