### ISSUE TITLE
Using StringTools in net462 with a System.Memory reference fails to build

### ISSUE THREAD

**Issue by BrennanConroy** [dotnet/msbuild#8295]
### Issue Description

Having the following two package references in a net462 project and using the `AsSpan` method results in:
> Error	CS0121 The call is ambiguous between the following methods or properties: 'System.MemoryExtensions.AsSpan<T>(T[], int, int)' and 'System.MemoryExtensions.AsSpan<T>(T[], int, int)'	ConsoleApp9 (net462)

```
<PackageReference Include="System.Memory" Version="4.5.5" />
<PackageReference Include="Microsoft.NET.StringTools" Version="17.4.0" />
```

```csharp
using System;

ReadOnlySpan<byte> value = (new byte[100]).AsSpan(0, 10);
Console.WriteLine(value.Length);
```

### Steps to Reproduce

Console App targeting net462:
csproj
```
<PackageReference Include="System.Memory" Version="4.5.5" />
<PackageReference Include="Microsoft.NET.StringTools" Version="17.4.0" />
```

program.cs
```csharp
using System;

ReadOnlySpan<byte> value = (new byte[100]).AsSpan(0, 10);
Console.WriteLine(value.Length);
```

### Expected Behavior

Able to build the project.

### Actual Behavior

> Error	CS0121 The call is ambiguous between the following methods or properties: 'System.MemoryExtensions.AsSpan<T>(T[], int, int)' and 'System.MemoryExtensions.AsSpan<T>(T[], int, int)'	ConsoleApp9 (net462)

### Analysis

The issue is coming from https://github.com/dotnet/msbuild/blob/a02d563625bdc82a9ffc1b9dab4616e881a5899f/src/StringTools/InternableString.Simple.cs#L7-L23
where you've defined an overload in the System namespace that conflicts with the one provided by System.Memory.

**Comment by rainersigwald** [comment]
Ah, that's unfortunate. The net35 asset is getting selected for use in a net462 project, but isn't the right choice; in fact StringTools doesn't support anything in the range `(3.5, 4.7.2)`. I don't know if it's possible to express that in the package, though, since net35 assemblies are generally binary compatible with net40 . . .

**Comment by RussKie** [comment]
Would adding an explicit version for net46 that doesn't contain the offending public API solve the issue?

**Comment by rainersigwald** [comment]
Since we haven't gotten other complaints I'm going to won't-fix this, but we can reconsider if it becomes more prominent.
