### ISSUE TITLE
Different releases of Microsoft.Build.* assemblies have the same 15.1 version leading to issues

### ISSUE THREAD

**Issue by Firensis** [dotnet/msbuild#8303]
It seems like at some point assemblies Microsoft.Build, Microsoft.Build.Framework, etc. stopped changing their versions after updates, so the versions of actually different Microsoft.Build assemblies became the same (15.1).
If an application depends on one of these libs and the same version (but different release) is installed in global assemblies cache (GAC), the app uses the version from GAC rather than expected lib placed near the executable. This leads to issues with missing types, members etc.

Could you please provide any ideas about solving such issues?

**Comment by rainersigwald** [comment]
This is intentional, and allows API client applications to work with multiple versions of MSBuild.

Do not install MSBuild assemblies in the GAC. They are intended to be within a Visual Studio instance, not global to the machine. Visual Studio has a setup step that should remove any entries that are in place at installation or update time.

**Comment by Firensis** [comment]
Thank you for the answer! :) But that's sad. Our client has this Microsoft.Build.Framework in his GAS and our analyzer depends on that library. The assembly from GAS doesn't provide some required types.

Do you may be know the way to load an assembly explicitly from a specific file? 'Assembly.Load' methods load from GAS.

**Comment by rainersigwald** [comment]
I do not know of a way to bypass the GAC when loading an assembly on .NET Framework.

Ideally, your client should unGAC MSBuild assemblies. If that's harmful for them we would love to know exactly why (via Visual Studio Feedback or a bug here).

If they absolutely can't do that, they may be able to update the version that is GACed to be the one from the Visual Studio instance that you're trying to load, so it comes from the GAC but is the right version. That's not what we want, but might be a small change to unblock progress.

**Comment by Firensis** [comment]
Than you for the answers, I've sent the information to the client.
It is very nice you took your time to help me :).
