### ISSUE TITLE
NuGet Source Transformation (.pp) not working as expected

### ISSUE THREAD

**Issue by Aragas** [dotnet/msbuild#8322]
### Issue Description
As I understand, MSBuild 17.5 might have broken the transformation.
The `obj` folder that should contain the transformed source code (`.cs.pp`) of a nuget package is empty - it doesn't contain the final `.cs` files where things like `$rootnamespace$` are resolved.
As an example, I have a NuGet Source Package (`BUTR.DependencyInjection` version 2.0.0.43) that stopped working.
The workarounds I saw while browsing source codes were basically "get rid of the .pp ending", since `.pp` was just used to hide the additional files. But how to fix it when it was used for the actual transformations?

## Steps to Reproduce
1. Create an empty C# project
2. Add `BUTR.DependencyInjection` version 2.0.0.43

## Expected Behavior
`.pp` files should be correctly transformed into `.cs` files

## Actual Behavior
`.pp` files are not correctly transformed into `.cs` files

### Versions & Configurations
VS2022
MSBuild version 17.4.1+9a89d02ff for .NET Framework
17.4.1.60106

VS2022 Preview
MSBuild version 17.5.0-preview-23053-01+ac0911a00 for .NET Framework
17.5.0.5301

VS2019
Microsoft (R) Build Engine version 16.11.2+f32259642 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

Happens in VS2019/VS2022/VS2022 Preview.
Happens on Rider too when MSBuild is used.

The computer I'm using is a fresh install. It does work still on my older one, ~~but it's I guess because I didn't upgrade yet, it's version is 17.4+9a89d02ff~~

EDIT:
The version of MSBuild seems to be the same for the working one and the broken one when using VS2022, the MSBuild versions of VS2019 is 16.
After verifying this, I have no idea what is causing this.
Also, to add to the confusion, when Rider is switched to use MSBuild, the same issue happens there too.

**Comment by AR-May** [comment]
This issue was moved to NuGet/Home#12857
