### ISSUE TITLE
WriteLinesToFile should warn when WriteOnlyWhenDifferent is set but Overwrite isn't

### ISSUE THREAD

**Issue by stan-sz** [dotnet/msbuild#8363]
The property https://github.com/dotnet/msbuild/blob/5f95887e07c8173b1c24c26c791e3ade924a4e8d/src/Tasks/FileIO/WriteLinesToFile.cs#L49 is considered only when `Overwrite` is set. Issue a warning when `WriteOnlyWhenDifferent == true && Overwrite == false` to help callers achieve build incrementality they expect, but may unintentionally have missed it, as the docs don't say about this dependency.

**Comment by KirillOsenkov** [comment]
I'm not even sure when is it helpful to have Overwrite false, honestly.

**Comment by rainersigwald** [comment]
Not specifying overwrite means "append". So I agree in theory with a warning on the illogical combination "append" + "don't change if possible".

**Comment by KirillOsenkov** [comment]
Ouch! That's not super intuitive. Wouldn't have guessed that it appends. Too late now to change the design though!

**Comment by stan-sz** [comment]
But a warning message can help here.

**Comment by stan-sz** [comment]
Ideally this validation can be coded up in the schema in

https://github.com/dotnet/msbuild/blob/5f95887e07c8173b1c24c26c791e3ade924a4e8d/src/MSBuild/MSBuild/Microsoft.Build.CommonTypes.xsd#L3652
