### ISSUE TITLE
auto-scroll after scrolling after using live logger

### ISSUE THREAD

**Issue by marcpopMSFT** [dotnet/msbuild#8392]
Repro on windows 11 console window
- dotnet new console
- dotnet build -ll
- let the build finish
- scroll up with the mouse wheel
- up arrow
On that last step, my command window jumps scrolling back to where it ended the build. I'll see if I can record a gif.
![LLautoscrollbug](https://user-images.githubusercontent.com/12663534/216459836-0f2a3953-7e98-49c8-b33c-c22d97093f9f.gif)

**Comment by edvilme** [comment]
Not entirely sure, but I think this was due to a workaround that is now no longer there
https://github.com/dotnet/msbuild/blame/fc3ab4c5e2a486abb8fc66aede7ec8e3eb91fe08/src/MSBuild/LiveLogger/LiveLogger.cs#L260
