### ISSUE TITLE
Developers get improved inner loop UX via interactive access to NuGet package source

### ISSUE THREAD

**Issue by JanKrivanek** [dotnet/msbuild#8398]
# Background

Idea by @rainersigwald 
Bringing the experience of working with packages in .NET ecosystem closer to other ecosystems (Go, Rust) having a link between an imported reference and it's source repository/commit as a first class citizen in the system.

## Tasks
- [x] #8510
- [x] #8512
- [x] #8507
- [x] #8511
- [x] #8722 

# Justification
- Faster inner loop of test-running patches and changes in referenced packages
- Simplifying OSS contribution workflow

**Comment by JanKrivanek** [comment]
https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1753051

**Comment by JonDouglas** [comment]
On the NuGet side https://github.com/NuGet/Home/issues/8443 may be related

**Comment by JanKrivanek** [comment]
The net8.0 prototyping and information gathering part of this user story concluded. Brief summarization (and prototype) linked here: https://github.com/dotnet/msbuild/issues/8510#issuecomment-1531361724

The actual production work on sub-problems of `PackageReference` vs `ProjectReference` substitutability is left for next releases (net9 and beyond)

**Comment by JanKrivanek** [comment]
https://github.com/NuGet/Home/wiki/NuGetizer-Future-Features#reference-unification
