### ISSUE TITLE
Investigation and spec writing for Packages Sourcing

### ISSUE THREAD

**Issue by JanKrivanek** [dotnet/msbuild#8399]
## Motivation

#8398 needs investigation (and possible spike) discovering possible implementation and delivery strategies, defining the scope and dependencies

## Expected outputs
- Internal idea paper, defining the scope and dependencies
- Review and signoff by stakeholders (Eng, PM, teams identified as dependenices - possibly VS, Nuget, SDK ?)
- (optional) spike exploring the viability and limitations
- Tasks/Stories proposal

**Comment by JanKrivanek** [comment]
Done by https://github.com/dotnet/msbuild/pull/8475

**Comment by donJoseLuis** [comment]
Close 8.0 package sourcing user story with current findings, create a user story with remaining goals & set as candidate for 9.0. Also, add this topic to the vision.
