### ISSUE TITLE
Research for Evaluation JIT/transpile

### ISSUE THREAD

**Issue by rokonec** [dotnet/msbuild#8412]
# Background

Evaluation interpret XML project files. There is hypothesis that if this interpretation if JITed or transpilled it could significantly speed up Evaluation.

DOD:
- measurement of possible gain
- high level design

**Comment by ladipro** [comment]
@rokonec thank you for the analysis. To clarify, are you measuring evaluation as it happens in a command-line build, solution load, or some other benchmark? I think it would be good to define the scenarios we're aiming to improve.

- If our goal is to improve command line build, what is the time spent in evaluation relative to total build time? In other words, how much would we gain end-to-end if evaluation was instantaneous?
- Similar question for an IDE scenario such as solution load or configuration switch. How much can evaluation move the needle there? In IDE we typically operate with populated caches so for example `LoadDocument` should be largely irrelevant.

**Comment by rokonec** [comment]
@ladipro @rainersigwald Do we plan to look into this further, or shall we close this issue?

**Comment by rainersigwald** [comment]
I'm ok closing it since we don't have any planned action.

**Comment by ladipro** [comment]
Agree with Rainer that it's fine closing although I suspect we'll come back to this at some point in the future. Thank you!
