### ISSUE TITLE
Test in multiple terminal emulators

### ISSUE THREAD

**Issue by rainersigwald** [dotnet/msbuild#8413]
- [x] VS Code Windows
   - Opens file in VS as oppose to containing folder, but this seems to me as correct behavior... same as Linux below. But it might not work with relative file paths. ***Needs to be retested after implementation.***
- [x] VS Code Mac
   - Opens file in VS as oppose to containing folder, but this seems to me as correct behavior... same as Linux below.
- [x] VS Code Linux
  - Opens file in VS as oppose to containing folder, but this seems to me as correct behavior...
![image](https://user-images.githubusercontent.com/25249058/234043961-6010d90d-71fd-4fcf-a441-6fa2a24764ab.png)
- [x] macOS Terminal - can't interact with hyperlinks
- [x] macOS iTerm2
  - Can interact with hyperlinks, but shows error: 
![image](https://user-images.githubusercontent.com/67507805/234225116-bb5ca3e8-9c9f-4179-b71c-276913505d7a.png)
- [ ] macOS Warp
- [x] Linux
  - [x] Default ubuntu 22 term - fully working
  - [x] Konsole - can't interact with hyperlinks
  - [x] Tilda - can't interact with hyperlinks
  - [x] XTerm - can't interact with hyperlinks 
  - [x] Xfce - can't interact with hyperlinks
  - [x] Terminus - can't interact with hyperlinks
  - [x] Terminator - fully working
  - [x] MATE - can't interact with hyperlinks
  - [x] Manjaro default console (zsh Konsole) - can't interact with hyperlinks

**Comment by edvilme** [comment]
I can confirm it works well on macOS iTerm. 
Works well on macOS Terminal, but ansi sequences for hyperlinks are not supported (but we have our fallback ie showing the path)

**Comment by reflectronic** [comment]
Unfortunately, on Windows 10, the emoji show up as tofu in the legacy console host: 
<image src="https://user-images.githubusercontent.com/27514983/235316716-a98b40c6-4ce7-4471-b90a-51d71e697409.png" alt="LiveLogger build output, with tofu in place of emojis" width="600" />

In Windows 11, conhost supports font fallback, so they appear to work fine. (Simulated by downloading the latest version of the console host from the Terminal repo:)
<image src="https://user-images.githubusercontent.com/27514983/235317257-d0b0ffb2-85db-4b12-83a0-6c170bb1cc85.png" alt="LiveLogger build output, but with emoji displaying properly" width="600" />

**Comment by ladipro** [comment]
@reflectronic thank you! I've filed #8723 to track the Win10 bug.
