### ISSUE TITLE
Enumerate live logger test matrix

### ISSUE THREAD

**Issue by marcpopMSFT** [dotnet/msbuild#8418]
Potential scenario test matrix:

**Examples**

- Single project quick build
- Single project quick build with error/warningSingle project slow build
- Single project slow build with error/warning
- Medium number of projects
- Medium number of projects with error/warning (the error should be visible throughout the build)
- Medium number of projects with lots of the same error (can/should these be collapsed together)
- Medium number of project with lots of different errors
- Many projects with parallel builds
- Build various .net repos successfully
- Build various .net repos with failure(s)
- etc.

**Comment by marcpopMSFT** [comment]
This is for manual testing and analysis. Think about test cases we could hand off to our vendors. Additionally, there may be some testing we can do in an automated fashion but since this is a Ux heavy feature, that may be more difficult. Suggestions welcome.

**Comment by marcpopMSFT** [comment]
CC @baronfel

**Comment by rainersigwald** [comment]
Most of the testing so far has been "build the MSBuild repo":

```
.\scripts\Deploy-MSBuild.ps1 -destination .\.dotnet\sdk\7.0.101\
.\build -msbuildengine dotnet -ll
```

**Comment by AR-May** [comment]
I think it is too early now to write test matrix. It does not seem to me that set of features already set for live logger.

**Comment by rokonec** [comment]
Bellow test cases are designed to give us good enough coverage.

| Action | Single Console | Multi project with tests | Orchard | 
| - |:-:|:-:|:-:|
| rebuild | ✔️| ✔️| ✔️|
| rebuild w/ cancel | ✔️|  | ✔️|
| restore | ✔️| ✔️| ✔️|
| interactive restore | ✔️| ✔️| ✔️|
| rebuild w/ errors | ✔️| ✔️| ✔️|
| rebuild w/ lots of errors |  | ✔️| ✔️|
| restore w/ errors |  | ✔️|  |
| dotnet test |   | ✔️| ✔️|


I have added dotnet test intuitively, as I know it uses Console colors and Console.Write for test progress reporting.

As for "Multi project with tests" I would recommend sln with one console, three class libraries projects and one test xunit project.

By interactive restore I mean a restore which DeviceFlow prompt:
![image](https://user-images.githubusercontent.com/25249058/231745387-e2ef3cf6-e185-4bb3-8bd9-954c32409947.png)
Here are some simple steps how to prepare simple console app:

Running installcredprovider per [these instructions](https://microsoft.sharepoint.com/teams/netfx/CLR/ProjectK/_layouts/15/Doc.aspx?sourcedoc=%7B10065841-2fa5-4c26-b91a-7d4b66b69a3c%7D&action=edit&wd=target%28net-core-validation.one%7C640f23bd-16f2-3442-a65f-b5eaf735912b%2FPrivate%20feeds%20for%20.NET%20Core%20and%20.NET%20releases%7C27551197-6789-470c-bc74-c35d8501897a%2F%29&wdorigin=703)

If it was already installed we might need to delete cached credentials from: `$env:UserProfile\AppData\Local\MicrosoftCredentialProvider`

If it was built before delete .\bin and .\obj folder

```
> dotnet nuget add source https://pkgs.dev.azure.com/dnceng/internal/_packaging/7.0.100-rc.1.22429.3-shipping/nuget/v3/index.json
> dotnet new console
> dotnet build -r win-x64 --interactive --restore
```

**Comment by ladipro** [comment]
I understand these are manual tests and passing is defined as "looks reasonable and doesn't crash". Please correct me if I'm wrong.

Since the logger makes assumptions about the shape of the build in terms of target names, output messages, and maybe more, it would be interesting to also test custom projects not based on the .NET SDK. And because we have decided to also support the logger in MSBuild.exe, I wonder if we should test C++, non-SDK-style, and whatever else is commonly built on the VS command line.

**Comment by rokonec** [comment]
> we should test C++, non-SDK-style, and whatever else  is commonly built on the VS command line

Good point. In order to have test matrix manageable, I have added only non-SDK and C++ for some test cases.

**Comment by ladipro** [comment]
Filed #8724 to define a test plan using the data in this issue.
