### ISSUE TITLE
MSBuild arguments that duplicate Visual Studio Publish command

### ISSUE THREAD

**Issue by sam-wheat** [dotnet/msbuild#8420]
Dotnet core 6
Visual Studio 17.4.2

When I publish my ClickOnce app from Visual Studio menu using a named .pubxml file  I get the following in the root publish folder:

    Applicaation Files folder
    setup.exe  
    MyApp.application 

When I re-publish the app a version folder appears in the Application Files folder (User is prompted to update).

The preceding works great - now I want to reproduce it using the msbuild command line so I can run it from a script.

When I run `MSBuild myproject.csproj /target:publish /p:PublishProfile=ProfileName /p:PublishDir="\\sharename\folder\"` I get the following in the root publish folder:

    Application Files folder
    language folders for dotnet runtime
    All dotnet runtime and application .dlls
    Launcher.exe
    Setup.exe
    MyApp.application

When I re-publish the app a the target folder is cleared and same files are copied again (User is not prompted to update).

What arguments and/or additional commands do I need to use on the command line to achieve the exact same result that I get with Visual Studio when I click Publish?    I did look at the output window in VS after running a publish but I am unable to reproduce the same result.

Thanks.

	<Project>
	  <PropertyGroup>
		<ApplicationRevision>4</ApplicationRevision>
		<ApplicationVersion>1.0.0.*</ApplicationVersion>
		<BootstrapperEnabled>True</BootstrapperEnabled>
		<Configuration>Release</Configuration>
		<CreateWebPageOnPublish>False</CreateWebPageOnPublish>
		<GenerateManifests>True</GenerateManifests>
		<Install>True</Install>
		<InstallFrom>Unc</InstallFrom>
		<IsRevisionIncremented>True</IsRevisionIncremented>
		<IsWebBootstrapper>False</IsWebBootstrapper>
		<MapFileExtensions>True</MapFileExtensions>
		<OpenBrowserOnPublish>False</OpenBrowserOnPublish>
		<Platform>Any CPU</Platform>
		<PublishProtocol>ClickOnce</PublishProtocol>
		<PublishReadyToRun>False</PublishReadyToRun>
		<PublishSingleFile>False</PublishSingleFile>
		<RuntimeIdentifier>win-x64</RuntimeIdentifier>
		<SelfContained>True</SelfContained>
		<SignatureAlgorithm>(none)</SignatureAlgorithm>
		<SignManifests>False</SignManifests>
		<TargetFramework>net6.0-windows</TargetFramework>
		<UpdateEnabled>True</UpdateEnabled>
		<UpdateMode>Foreground</UpdateMode>
		<UpdateRequired>False</UpdateRequired>
		<WebPageFileName>Publish.html</WebPageFileName>
		<CreateDesktopShortcut>True</CreateDesktopShortcut>
		<ProductName>MyApp</ProductName>
		<PublisherName>Us</PublisherName>
		<History></History>
	  </PropertyGroup>

**Comment by sujitnayak** [comment]
The publishing step that performs the tasks that you mention run inside Visual Studio. When you publish with the msbuild CLI, these steps will not run. You would need to write your own script to do the filtering of the files that happens during publish invoked from Visual Studio.
Thanks.

**Comment by Brubning** [comment]
That's a shame, this behaviour is different now than in the past - publishing a .NET 4.8 WPF application from command line with MSBuild /target:publish generates only the files necessary for the publish/install (Exactly as described by @sam-wheat).

Publishing a .NET 6.0 WPF application generates a lot of superfluous files which appear to be copied to at least 3 different locations.

We are publishing ClickOnce through pipelines and being able to run a single MSBuild task to achieve this without having to write additional scripts is super useful.

This issue hasn't been closed, is it likely to be addressed?

**Comment by sujitnayak** [comment]
@Brubning 

To redirect the ClickOnce artifacts to a different folder from the msbuild command line, you can override the ClickOncePublishDir property. For e.g. to redirect it to a folder named 'publish':

_msbuild foo.csproj /t:publish /p:ClickOncePublishDir=publish\ /p:PublishProfile=<path_to_pubxml>_

There are 2 caveats when you do so:
1. It is mandatory to specify a trailing backslash to the value of the ClickOncePublishDir property.
2. When the ClickOncePublishDir property is overriden, it is not cleaned by msbuild. You would need to author your own target to clean it before the publishing target runs. 

Thanks.

**Comment by sujitnayak** [comment]
Closing the issue since a workaround has been provided.
