### ISSUE TITLE
[LiveLogger] Use correct opt-in state

### ISSUE THREAD

**Issue by donJoseLuis** [dotnet/msbuild#8431]
Ensure LiveLogger has the right opt-in state to get the most modern logging including when combined with -bl

**Comment by Forgind** [comment]
I don't follow. Users have to opt in if they want to see the live logger at all; what more are you proposing?

**Comment by rainersigwald** [comment]
This is specifically talking about things like calling [`IEventSource4.IncludeEvaluationPropertiesAndItems()`](https://github.com/dotnet/msbuild/blob/49c7a8cf6dc7425ae3205cbb4e5babe15b72c005/src/Framework/IEventSource4.cs#L13-L20) so that we don't regress binlogs when this is enabled.

**Comment by rainersigwald** [comment]
We do `IncludeEvaluationPropertiesAndItems` now, anything else we need we should treat as a bug.
