### ISSUE TITLE
Developers get MS Build useful and up-to-date documentation

### ISSUE THREAD

**Issue by vlada-shubina** [dotnet/msbuild#8447]
The aim of the issue is to improve documentation on MSBuild for various groups of users:
- entry-level users
- advanced users
- 3rd party developers (custom task implementation, etc)
- developers of MSBuild

Some of ideas are below:
- create landing page for MSBuild with links to existing materials, likely grouped by topic and advance level
- review existing materials and identify gaps
- review existing tutorials and identify gaps 
- do a user study, as example
   - find some volunteers, not knowledgeable in MSBuild but keen to learn
   - give an advance task to accomplish
   - assess the progress in 1-2 days, interview for what's good/what's not, to identify the gaps
- consider creating blog posts / podcasts about MSBuild

For next release, the effort should be likely time boxed.

Tasks:
- [ ] https://github.com/dotnet/msbuild/issues/7163
- [ ] https://github.com/dotnet/msbuild/issues/8748

**Comment by rainersigwald** [comment]
We should coordinate with @ghogen about any doc efforts.

**Comment by vlada-shubina** [comment]
We would like to hear from you :loudspeaker: 

Please let us know which resources are useful from you, which resources can be improved and how and what additional resources you'd like to see.

**Comment by donJoseLuis** [comment]
Does not meet the 8.0 adjustment cutline and is not very well developed as a user story overall. Please reopen once direct goals for it are identified.
