### ISSUE TITLE
Warn when using BinaryFormatter resources while targeting .NET 8+

### ISSUE THREAD

**Issue by rainersigwald** [dotnet/msbuild#8453]
.NET 8 will make `BinaryFormatter` functionality opt-in, and there's cross-team work to ensure that users have good alternatives and are guided to use them.

`GenerateResource` can pass BinaryFormatter-serialized resource objects from a source `.resx` file to `.resources` files embedded by the compiler:

https://github.com/dotnet/msbuild/blob/03de075bf00cadc8cf6e884f1719ea1d2da5b30e/src/Tasks/ResourceHandling/MSBuildResXReader.cs#L186-L192

We should add a warning when we hit that case, so users are aware that they have BinaryFormatter exposure.

By default the warning should fire only when the user targets .NET 8+. The easiest way to implement this is probably to add a new argument to `GenerateResource` along the lines of `WarnOnBinaryFormatterResources`, pass it in as a property in common.targets, and then set a default value for it in the .NET SDK.

The warning must be overridable, because even in the long term (after .NET 9's removal of BinaryFormatter from the BCL) we expect it to be possible for applications to explicitly opt into BinaryFormatter support, and resources are likely to be a particularly long-lived use case.

**Comment by danmoseley** [comment]
Linking to https://github.com/dotnet/runtime/issues/39287 
and specifically
https://github.com/dotnet/runtime/issues/39290
https://github.com/dotnet/runtime/issues/39292 (?)

https://github.com/dotnet/designs/pull/141
