### ISSUE TITLE
[LiveLogger] Garbled output in cmd.exe

### ISSUE THREAD

**Issue by ladipro** [dotnet/msbuild#8455]
### Issue Description

LiveLogger does not work in cmd.exe.

### Steps to Reproduce

`dotnet build /ll` in cmd.exe.

### Expected Behavior

Either LiveLogger errors out or MSBuild falls back to regular console logging.

### Actual Behavior

My first attempt to use LiveLogger resulted in this:

![image](https://user-images.githubusercontent.com/12206368/219328641-5daea853-97d2-4962-9912-3a660c1e6a1a.png)

### Analysis

If this console is not fancy-capable then the logger should not be allowed to run. Note that you still get this kind of console when running the VS Developer prompt as administrator so this would be a blocker for enabling LL by default.

**Comment by rainersigwald** [comment]
I would have expected the livelogger to not be enabled in this case

https://github.com/dotnet/msbuild/blob/dfd8f413a80cd0865f968b2c0ad9b09c0df8c430/src/MSBuild/XMake.cs#L3436-L3455

So that's likely the first thing to chase.

**Comment by baronfel** [comment]
@ladipro do you run cmd inside Windows Terminal? if so the WT_SESSION would be non-empty.

**Comment by ladipro** [comment]
@baronfel I use the "Developer Command Prompt for VS 2022" shortcut created by VS installer. It has `%comspec% /k "C:\Program Files\Microsoft Visual Studio\2022\Preview\Common7\Tools\VsDevCmd.bat"` as its target. It does not run cmd inside Windows Terminal, as far as I can tell. The `WT_SESSION` environment variable is not defined.

Ah, _not defined_! The fix is to check for null in addition to "" in the code @rainersigwald linked before.

**Comment by baronfel** [comment]
Oh, that makes sense too :+1: I did a check real quick and verified that `cmd` inside Windows Terminal _does_ render correctly (which I hoped since Windows Terminal was doing the rendering portion).
