### ISSUE TITLE
[LiveLogger] Don't render any yellow or red unless/until there is a warning/error

### ISSUE THREAD

**Issue by ladipro** [dotnet/msbuild#8456]
The cross mark ❌ character is usually rendered in red and it unnecessarily creates the impression that something is wrong even if the build is progressing just fine. Similar for the yellow exclamation point.

![image](https://user-images.githubusercontent.com/12206368/219334266-18000a62-bd2d-45dc-8760-8cd168bfa4e9.png)

Suggestion: Add the &lt;number&gt; ℹ️, &lt;number&gt; ⚠️, &lt;number&gt; ❌ output only when &lt;number&gt; is &gt;0 (for each of the three).

**Comment by rainersigwald** [comment]
Strong agree on the principle "don't draw red unless there's a problem".

I'm less sure I like this display model overall--if we achieve the "warnings and errors are basically always on screen after they occur" model, we may not care about counts in the live display at all.

**Comment by edvilme** [comment]
This could be removed entirely (and maybe replaced with "Finished without errors or warnings", or something lime that?)
