### ISSUE TITLE
[LiveLogger] Many exceptions are thrown from the logger

### ISSUE THREAD

**Issue by ladipro** [dotnet/msbuild#8458]
### Issue Description

Throwing and catching exceptions has perf implications and generally makes debugging harder.

### Steps to Reproduce

Run `msbuild /ll` under a debugger.

### Expected Behavior

No exceptions.

### Actual Behavior

Many occurrences of:

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Build.Logging.LiveLogger.ProjectNode.Log() in C:\src\msbuild\src\MSBuild\LiveLogger\ProjectNode.cs:line 156
```

With an occasional:

```
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at Microsoft.Build.Logging.LiveLogger.TerminalBuffer.Render() in C:\src\msbuild\src\MSBuild\LiveLogger\TerminalBuffer.cs:line 145
```

### Versions & Configurations

Commit dfd8f413a80cd0865f968b2c0ad9b09c0df8c430

**Comment by AR-May** [comment]
We need to check code for possible race conditions.
Found a race condition in line https://github.com/dotnet/msbuild/blob/dfd8f413a80cd0865f968b2c0ad9b09c0df8c430/src/MSBuild/LiveLogger/LiveLogger.cs#L78
The collection is modified in event handlers, for example 
https://github.com/dotnet/msbuild/blob/dfd8f413a80cd0865f968b2c0ad9b09c0df8c430/src/MSBuild/LiveLogger/LiveLogger.cs#L145
It is different from what @ladipro found, but it is probably for similar reasons.

**Comment by rainersigwald** [comment]
All of the data structures we update in the event handlers should be thread safe. We can probably just switch to `ConcurrentDictionary` for that particular case. For `Lines` in `TerminalBuffer` we probably need to lock (or a bigger refactor to avoid that concept).

> Many occurrences of:
> 
> ```
> System.NullReferenceException: Object reference not set to an instance of an object.
>    at Microsoft.Build.Logging.LiveLogger.ProjectNode.Log() in C:\src\msbuild\src\MSBuild\LiveLogger\ProjectNode.cs:line 156
> ```

looks like we have been overzealous with `!` . . .
