### ISSUE TITLE
[LiveLogger] Plug the logger into minimum message importance checks

### ISSUE THREAD

**Issue by ladipro** [dotnet/msbuild#8463]
As a perf optimization MSBuild can filter out verbose log output very early to speed up the build if no logger interested in low importance messages is enabled. LiveLogger is currently not recognized by this system, making it slower than the default console logger as configured in `dotnet build`.

It should be as simple as adding a case here:
https://github.com/dotnet/msbuild/blob/dfd8f413a80cd0865f968b2c0ad9b09c0df8c430/src/Build/BackEnd/Components/Logging/LoggingService.cs#L1630-L1644

Needless to say, LL must not actually consume any low importance messages for this to work.

**Comment by rainersigwald** [comment]
> Needless to say, LL must not actually consume any low importance messages for this to work.

I suspect this won't be possible, but if we can hold to it it'd be really nice.

**Comment by ladipro** [comment]
> > Needless to say, LL must not actually consume any low importance messages for this to work.
> 
> I suspect this won't be possible, but if we can hold to it it'd be really nice.

LiveLogger appears to be consuming only high importance messages at the moment.

https://github.com/dotnet/msbuild/blob/5476e4396fdcec6e3578ba595082f18f2130ca21/src/MSBuild/LiveLogger/ProjectNode.cs#L200-L203

Are you aware of normal- or low-importance messages that may be needed in the future?

**Comment by rainersigwald** [comment]
My concern that we might need low-pri messages is around extracting more-sophisticated context around certain events/circumstances. By parsing low-pri messages we can get lots of state that isn't exposed in a more structured way today. But I don't know of any concrete need for that on our to-do list right now, and would be happy to cross that bridge when we come to it (with the possibility of solving the problem by adding better-structured messages).

**Comment by AR-May** [comment]
> It should be as simple as adding a case here

Looked at it, the LiveLogger is in MSBuild assembly now, not in Microsoft.Build, so not that easy. We either need to think how properly do that or to make some hack there for LoveLogger.

**Comment by AR-May** [comment]
Marking size 3 because the question of proper location for LiveLogger is raised and now this issue depends on it.

**Comment by rainersigwald** [comment]
I think I would be comfortable with a string match on a fully-qualified type name in the code block in the OP.

**Comment by AR-May** [comment]
> I think I would be comfortable with a string match on a fully-qualified type name in the code block in the OP.

Not a big fan of it, but it is a good enough hack for me, i think. I still would like to put some thought into LiveLogger location.
