### ISSUE TITLE
`EmitCompilerGeneratedFiles` and `CompilerGeneratedFilesOutputPath` are not present in auto completion

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/msbuild#8471]
### Issue Description

`EmitCompilerGeneratedFiles` and `CompilerGeneratedFilesOutputPath` are not present in auto completion

They should be added similar to https://github.com/dotnet/msbuild/pull/5728

**Comment by Youssef1313** [comment]
@ryan-rozario I think yes. It's marked as "help wanted".

**Comment by rainersigwald** [comment]
@ryan-rozario all yours. Please let us know if you have any trouble.
