### ISSUE TITLE
`RepositoryTask`'s usage of `IBuildEngine4.GetRegisteredTaskObject` breaks under multiple `AssemblyLoadContext`s.

### ISSUE THREAD

**Issue by teo-tsirpanis** [dotnet/msbuild#8478]
I enabled Central Package Management in my repository and put `Microsoft.DotNet.ReproducibleBuilds` in a `GlobalPackageReference`, which means that all my projects have Sourcelink enabled. Now when I build one of these projects, I get this error [right here](https://github.com/dotnet/sourcelink/blob/c9199d81c03166e2fb0b4e4758c1ceb41b3c1e1f/src/Microsoft.Build.Tasks.Git/RepositoryTask.cs#L137) (also opened dotnet/runtime#80526 to track its unhelpfulness):

```
System.InvalidCastException:

[A]System.Runtime.CompilerServices.StrongBox`1[Microsoft.Build.Tasks.Git.GitRepository] cannot be cast to [B]System.Runtime.CompilerServices.StrongBox`1[Microsoft.Build.Tasks.Git.GitRepository].

Type A originates from 'System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e' in the context 'Default' at location 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.2\System.Private.CoreLib.dll'.
Type B originates from 'System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e' in the context 'Default' at location 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.2\System.Private.CoreLib.dll'.
```

This error message tells us that the two `GitRepository`ies are different. My guess is that MSBuild loads the task assembly once for each project, and they get the `GitRepository` from a previous invocation, which resides in a different ALC and fails to cast.

The approach of caching the repository information has to be revisited. For now I will limit SourceLink to just my library projects.

**Comment by rainersigwald** [comment]
Thanks for the repro. MSBuild Team: let's prioritize investigating this, since it appears to be a failure in a using-all-the-new-cool-stuff scenario.

**Comment by tmat** [comment]
@teo-tsirpanis So, yes, your build is misconfigured. You're loading two copies of Source Link - one from package cache in `C:\Users\teo\.nuget\packages` and the other from `C:\Users\teo\code\Farkle\tests\packages`. Don't do that :)

**Comment by tmat** [comment]
Fixed by https://github.com/dotnet/sourcelink/pull/1034

**Comment by teo-tsirpanis** [comment]
Thanks!
