### ISSUE TITLE
[LiveLogger] Unreliable check for ANSI-capable terminal on Windows

### ISSUE THREAD

**Issue by ladipro** [dotnet/msbuild#8481]
> The Internet seems to think that checking the result of `GetConsoleMode` for `ENABLE_VIRTUAL_TERMINAL_PROCESSING` may be a better way of detecting fancy-capable environments.

this snippet from pwsh looks relevant:

https://github.com/SteveL-MSFT/PowerShell/blob/4c01dcc5d5672f4b0ccbac87fe756de01f487887/src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHostUserInterface.cs#L64-L85

_Originally posted by @rainersigwald in https://github.com/dotnet/msbuild/issues/8467#issuecomment-1439185528_
            
---

We currently use the `WT_SESSION` environment variable, which does not work in all scenarios. See the discussion in #8467 for details.

**Comment by danmoseley** [comment]
Does this suggest something the Console class should abstract?

**Comment by ladipro** [comment]
> Does this suggest something the Console class should abstract?

Yes, it would make sense for this to be provided by base libraries. It's not a super forward-looking functionality, though, because on modern Windows even the classic `conhost.exe` supports ANSI codes, as far as I can tell.
