### ISSUE TITLE
Developers get modernized inner-loop and learning MS BUILD experiences 

### ISSUE THREAD

**Issue by donJoseLuis** [dotnet/msbuild#8490]
# Background
Container for modernization user stories

# User Stories
- [x] #8398 

# Justification
Features to bring next-generation functionality to MSBUILD use cases.

**Comment by baronfel** [comment]
Change milestone to align with themesof.net tracking

**Comment by JanKrivanek** [comment]
The net8.0 prototyping and information gathering part of this user story concluded. Brief summarization (and prototype) linked here: https://github.com/dotnet/msbuild/issues/8510#issuecomment-1531361724

The actual production work on sub-problems of PackageReference vs ProjectReference substitutability is left for next releases (net9 and beyond)
