### ISSUE TITLE
[Performance]: Build Regression 17.4.1 vs 17.5.0

### ISSUE THREAD

**Issue by indy-singh** [dotnet/msbuild#8496]
### Issue Description

I've posted over here; https://developercommunity.visualstudio.com/t/Performance-Build-Regression-1745-vs-1/10289641 but I think this is a problem specific to msbuild.

We are using:-

17.4.1+9a89d02ff (fast, rolled out everywhere)
17.5.0-preview-23061-01+040e2a90e (slow, rolled out on a few machines to test)

But I wanted to get some pointers on how to debug/diagnose this sooner rather than later.

> We are just rolling out 17.5.0 and we’ve noticed a pretty huge discrepancy in the performance of building.
>
> For testing we are using dotnet new console as test project.
>
> dotnet clean && dotnet build --force --no-incremental -bl:17.4.5.binlog on a machine with 17.4.5.
>
> dotnet clean && dotnet build --force --no-incremental -bl:17.5.0.binlog on a machine with 17.5.0.
>
> In the small example above the difference is only 200ms or so, but in real world production projects we are seeing 45 seconds -> 200+ seconds.
>
> Happy to provide any further information required.
>
> Cheers,
> Indy

I've attached the binlog files. But other than everything taking a tad longer, I'm not super sure where to begin.

Thanks,
Indy

### Steps to Reproduce

[17.4.5.zip](https://github.com/dotnet/msbuild/files/10818305/17.4.5.zip)
[17.5.0.zip](https://github.com/dotnet/msbuild/files/10818306/17.5.0.zip)

### Data

[17.4.5.zip](https://github.com/dotnet/msbuild/files/10818305/17.4.5.zip)
[17.5.0.zip](https://github.com/dotnet/msbuild/files/10818306/17.5.0.zip)

### Regression

- [X] yes
- [ ] no

**Comment by indy-singh** [comment]
I guess the first and most obvious differences between the machines is the CPU.

The one using `17.4.1+9a89d02ff` has https://www.cpubenchmark.net/cpu.php?cpu=Intel+Core+i5-11400+%40+2.60GHz&id=4233

The one using `17.5.0-preview-23061-01+040e2a90e` has https://www.cpubenchmark.net/cpu.php?cpu=Intel+Core+i5-8400+%40+2.80GHz&id=3097

Let me go and find another machine that as the same CPU as the "fast" machine so I can get a 1:1 buildlog out.

**Comment by indy-singh** [comment]
Sorry, this took me longer than I expected to do this. Using an identical machine spec wise and running VS 17.4.5 and VS 17.5.0 shows no build time/performance regression at all. Apologies for the false alarm. I've attached the binlogs to confirm for the record.

Next time I'll be sure to pick the candidate machine more carefully.

Cheers,
Indy

[17.5.0.zip](https://github.com/dotnet/msbuild/files/10826926/17.5.0.zip)
[17.4.5.zip](https://github.com/dotnet/msbuild/files/10826927/17.4.5.zip)

**Comment by rainersigwald** [comment]
Thanks for following up! Glad we weren't the problem (this time 😁).
