### ISSUE TITLE
Investigate and list ProjectReference and PackageReference behavioral divergences

### ISSUE THREAD

**Issue by JanKrivanek** [dotnet/msbuild#8507]
## Motivation

#8398 needs investigation of what we can support (and how) in converting between the two.
There might be possible inconsitencies between [`PackageReference`](https://learn.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files) and [`ProjectReference`](https://learn.microsoft.com/en-us/visualstudio/msbuild/common-msbuild-project-items?view=vs-2022#projectreference) items metadata (and even behavior with same metadata - e.g. `SetTargetFramework` has different behavior for the two: https://github.com/NuGet/Home/issues/12436, `PrivateAssets` as well: https://github.com/dotnet/msbuild/issues/4371#issuecomment-815793382, etc.).

## Expected outputs
- List of supported metadata for `PackageReference` and `ProjectReference` - stressing out the differences
- List of metadata that leads to different behavior for the two.
- The investigation would ideally create a repo or branch with minimal samples of the findings
- List of identified existing open workitems/bugs related to difference of behavior of the two

**Comment by nkolev92** [comment]
At some point I did some digging about issues that contain this type of information and creating an issue for a future investigation. I don't think my issue has anything you don't know, but figured I'd share it:

```
PackageReference has PrivateAssets/ExcludeAssets/Include assets capabilities and those are respected. 
Those also easily translate into the dependencies in the generated package. 

ProjectReferences *do not* have the same equivalent experience. Realistically only the ReferenceOutputAssembly and PrivateAssets=all metadata work. 

Basically, there's absolutely no way to express a "runtime only" ProjectReference, the same way you can express a PackageReference. This feature covers the rethinking of all this metadata. 
Should project ref support all this metadata the same way PackageReference does? Should it? Gotchas/caveats?

See Re: How to express a package dependency without the weight of a P2P ref?

Project/PackageReference story

https://github.com/NuGet/Home/issues?q=is%3Aissue+ReferenceOutputAssembly+is%3Aopen
https://github.com/dotnet/sdk/search?q=ReferenceOutputAssembly&type=Issues
https://github.com/microsoft/msbuild/search?q=ReferenceOutputAssembly&type=Issues
```

**Comment by nkolev92** [comment]
I forwarded the e-mail my write-up references :)

**Comment by JaynieBai** [comment]
# Differences between PackageReference and ProjectReference
Tag | PackageReference | ProjectReference | IsSame | Comments
-- | -- | -- | -- | -- |
Name | ☑️ | ☑️ | ✅||
Aliases | ☑️ | ☑️ | ✅||
Version | ☑️| ❌ | ||
NoWarn | ☑️|❌|| 1. NoWarn on a package reference does not apply transitively to its dependencies https://github.com/NuGet/Home/issues/5740 2. NoWarn Metadata is not applied in projectReference. https://github.com/NuGet/Home/issues/5999 |
GeneratePathProperty| ☑️ | ❌||
IncludeAssets | ☑️ | ☑️ | ❌| 1. In package reference, IncludeAssets works for transitive and direct references 2. In project reference, IncludeAssets  works for transitive references |
ExcludeAssets | ☑️ | ☑️| ❌| 1. In package reference, ExcludeAssets works for transitive and direct references 2. In project reference, ExcludeAssets works for transitive references |
PrivateAssets | ☑️| ☑️ | ✅||
GlobalPropertiesToRemove | ❌ | ☑️|||
Project| ❌ | ☑️|||
OutputItemType | ❌ | ☑️|||
ReferenceOutputAssembly| ❌ | ☑️|||
Private | ❌ | ☑️|||
SetConfiguration |❌ | ☑️||https://github.com/NuGet/Home/issues/7868#issuecomment-519277759|
SetPlatform | ❌ | ☑️||https://github.com/NuGet/Home/issues/7868#issuecomment-519277759|
SetTargetFramework | ❌ | ☑️||https://github.com/NuGet/Home/issues/7868#issuecomment-519277759|
SkipGetTargetFrameworkProperties | ❌ | ☑️||https://github.com/NuGet/Home/issues/7868#issuecomment-519277759|
PlatformLookupTable | ❌ | ☑️||https://github.com/NuGet/Home/issues/7868#issuecomment-519277759|
Targets| ❌ | ☑️|||

**Comment by nkolev92** [comment]
Hey @JaynieBai 

Excellent list!

I think the NoWarn part for ProjectReference might not be 100% correct. 
ProjectReference do support NoWarn too. The issue linked is closed as a dup for transitive packages. 

Are you seeing anything different in your tests?

**Comment by JaynieBai** [comment]
> Hey @JaynieBai
> 
> Excellent list!
> 
> I think the NoWarn part for ProjectReference might not be 100% correct. ProjectReference do support NoWarn too. The issue linked is closed as a dup for transitive packages.
> 
> Are you seeing anything different in your tests?

Thanks for pointing it out.  I didn't find any direct warnings about project reference currently. But it couldn't suppress transitive warning now. So mark it not supported temporarily.

**Comment by nkolev92** [comment]
Not sure what you mean by ` I didn't find any direct warnings about project reference currently`

I think NoWarn is equivalent for ProjectReference and PackageReference. 

The lack of transitive support is a big change and it applies to more than just NoWarn.

**Comment by JaynieBai** [comment]
Taks an example from https://github.com/JanKrivanek/msbuild/blob/doc/dependencies-behavior/documentation/wiki/Controlling-Dependencies-Behavior.md#access-to-transitive-project-references
Repository Project defination: 
```<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Domain\Domain.csproj" />
  </ItemGroup>

</Project>
```
```using Newtonsoft.Json;
namespace Repository
{
    public class Persona
    {
        private Domain.PersonTable _tbl;
    }
}
```
Build it and there will generate following warnings.  
![image](https://user-images.githubusercontent.com/26814373/228762857-77c9b4e6-9e27-4744-97fe-42393bdf0f95.png)

In Service Project definition.
```<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
	  <ProjectReference Include="..\Repository\Repository.csproj">
		  <NoWarn>NU1701;NU1602</NoWarn>
	  </ProjectReference>
  </ItemGroup>

</Project>
```
> Not sure what you mean by ` I didn't find any direct warnings about project reference currently`
NU1701;NU1602 is transitive reference warning.  I can't find a warning that is generated from projectReference. And in https://learn.microsoft.com/en-us/nuget/reference/errors-and-warnings. It specifies NoWarn scope as Project, PackageReference

**Comment by JaynieBai** [comment]
Attach some examples for ExcludeAssets IncludeAssets and PrivateAssets in excel
[InvestigationExamples.xlsx](https://github.com/dotnet/msbuild/files/11110401/InvestigationExamples.xlsx)

**Comment by nkolev92** [comment]
If you take a project that targets net5.0 and add a project reference to a project that targets net472, you'll get a NU1702 which should be suppressible. 

I've created an issue to fix the doc to make it clearer: https://github.com/NuGet/docs.microsoft.com-nuget/pull/3038.

**Comment by nkolev92** [comment]
OK, so the bug for ProjectReference NoWarn is https://github.com/NuGet/Home/issues/8093.

**Comment by JaynieBai** [comment]
Discussed offline with @JanKrivanek 

From @JaynieBai 
When project A has an assembly reference. And project B references project A. But assembly reference is not in the project B dependency lists, B can't reference the transitive assembly. But for package reference and project reference, B can reference the transitive references.  How to let projectB reference projectA assembly without setting the assembly in the project B again?

From @JanKrivanek 
    Hi Jenny - transitive project and package references were added within the .net sdk style project as a feature primarily for the compiler. It might be that it was never intended to be extended to Assembly References as well - we'll check with @rainersigwald  - as he likely has the background info.

**Comment by rainersigwald** [comment]
Assembly references in .NET are generally required to be transitive. At runtime, if you call code from B that uses a type from A, the .NET assembly loader will fail if A cannot be loaded.

At _build_ time, the compiler may or may not need the full transitive closure--it will definitely need to see A if the public API of B returns a type from A, but if the use of A is all internal implementation details of B, the compiler may be able to succeed without access to A. However, the contract of the compiler is that you _should_ pass the full closure, and if you don't and a new compiler requires more assemblies to do deeper analysis on the same code, that is not considered a breaking change in the compiler.

All of that has been the same for a very long time; there's no change introduced in .NET Core or the .NET SDK compared to (for example) a set of VS2010 projects.

Prior to SDK-enabled transitive project references, the closure was computed entirely within `ResolveAssemblyReferences` per-project. RAR will attempt to find the transitive closure of references unless instructed otherwise.

In a fully old-school project what would happen is:

1. A builds, and produces `A.dll` in a folder, say `A\bin\debug\A.dll`
2. B builds, referencing `A.dll` from that folder _and copying it to `B\bin\debug\A.dll`_
3. Something that references A builds
   a. ResolveProjectReferences returns the path to `B\bin\debug\B.dll`
   b. RAR looks at `B.dll` and sees that it has a reference to A
   c. RAR looks "next to" `B.dll` and finds `A.dll`
   d. MSBuild gives both `A.dll` and `B.dll` to the compiler
   e. this project then copies both to _its_ bin directory so they're available at runtime.

A big difference between this approach and the SDK's default transitive ProjectReferences is how `A.dll` is presented to RAR and whether it's marked as a direct reference.

**Comment by JanKrivanek** [comment]
@JaynieBai - do you plan any other work on this task? Or can this be closed? (Feels complete from my point of view. And thanks again for the help!)

**Comment by JaynieBai** [comment]
I don't have any plan for this work now. So, I think we can close that.
