### ISSUE TITLE
Silent Failure of GetTargetFrameworks when using platform negotiation

### ISSUE THREAD

**Issue by MIchaelRShea** [dotnet/msbuild#8515]
I am trying to implement project to project platform negotiation in my Repo but it relies on the GetTargetFrameworks  target. this target appears to be failing silently which doesnt allow platform negotiation to work properyl. is there a way to enable more verbose logging to get target frameworks?

**Comment by rainersigwald** [comment]
The binary log should be able to present a pretty good picture of the flow here. It generally looks something like this:

![image](https://user-images.githubusercontent.com/3347530/222271855-b5f958ed-3f74-4e9a-80e0-8112b3a01198.png)

**Comment by AR-May** [comment]
Was the comment above helpful? Is there anything else we can help with?
