### ISSUE TITLE
[Feature]: WriteCodeFragment creates relevant directory structure

### ISSUE THREAD

**Issue by Forgind** [dotnet/msbuild#8516]
### Issue Description

WriteCodeFragment pretty directly calls File.WriteAllText, which fails if you pass in a folder structure that does not exist. We should consider calling Directory.CreateDirectory first.

### Steps to Reproduce

Take any project and add a call to the WriteCodeFragment task, passing in `OutputDirectory=<path on computer that does not exist>`

### Expected Behavior

Creates folders as necessary

### Actual Behavior

Fails

**Comment by jrdodds** [comment]
I would like to work on this issue. Please assign it to me. Thanks

**Comment by rainersigwald** [comment]
Sounds good, @jrdodds! Feel free to put up a draft PR and/or ask here if you run into any trouble.
