### ISSUE TITLE
[Bug]: Multitargeting fails to include PackageReadmeFile

### ISSUE THREAD

**Issue by miloush** [dotnet/msbuild#8518]
### Issue Description

When multitargeting using `<TargetFrameworks>`, `<None Update` items are not included in the build, making the `PackTask` fail when trying to pack content such as a readme file.

@KirillOsenkov 

### Steps to Reproduce

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net8.0</TargetFrameworks>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>
  <ItemGroup>
    <None Update="README.md" Pack="true" PackagePath="\" />
  </ItemGroup>
</Project>
```
\+ something to compile and non-empty _README.md_

### Expected Behavior

Build succeeds.

### Actual Behavior

```
error NU5039: The readme file 'README.md' does not exist in the package.
```

Build succeeds when either `<TargetFramework>` singular is used instead of multitagerting, or, when `<None Include` is used rather than `<None Update`.

### Analysis

In the multitargeting scenario, the first evaluation of the project does not contain `<None>` items, so _\_GetPackageFiles_ target does not produce any items and as a result the readme file is not included in nuspec, hence the error.

### Versions & Configurations

MSBuild version 17.6.0-preview-23081-04+7bf511372
OS version 25300.1000.amd64fre.rs_prerelease.230210-1451
.NET SDK version 8.0.100-preview.1.23115.2

**Comment by rainersigwald** [comment]
This issue was moved to NuGet/Home#12485
