### ISSUE TITLE
[Bug]: Cannot merge folders with wildcards

### ISSUE THREAD

**Issue by mmarczell-graphisoft** [dotnet/msbuild#8527]
### Issue Description

Trying to use wildcards to merge the contents of two folders looks like it should be possible, but doesn't work due to bugs.

### Steps to Reproduce

I have a vcxproj and two folders of resource files that I want to merge in the output. The content of the folders might be generated so I can't enumerate them in the project file, I need to use wildcards. I know wildcards are not fully supported in vcxproj so I follow the advice of [the docs](https://learn.microsoft.com/en-us/cpp/build/reference/vcxproj-files-and-wildcards) and put them in a Target:

```
<Target Name="SomeTarget" BeforeTargets="ClCompile">
   <ItemGroup>
      <Content Include="files1\**" CopyToOutputDirectory="PreserveNewest" TargetPath="files\@(RecursiveDir)%(Filename)%(Extension)"/>
      <Content Include="files2\**" CopyToOutputDirectory="PreserveNewest" TargetPath="files\@(RecursiveDir)%(Filename)%(Extension)"/>
   </ItemGroup>
</Target>
```

My project zipped:

[CppSandbox.zip](https://github.com/dotnet/msbuild/files/10883572/CppSandbox.zip)

### Expected Behavior

The contents of the two folders should be merged at buildtime.

### Actual Behavior

The project fails to build with the following error:
> error MSB3024: Could not copy the file "D:\Dev\Sandbox\CppSandbox\files1\a.txt" to the destination file "D:\Dev\Sandbox\CppSandbox\Debug\files\", because the destination is a folder instead of a file. To copy the source file into a folder, consider using the DestinationFolder parameter instead of DestinationFiles.

Contrary to the docs, if I omit the Target and use a direct ItemGroup, it works. Another weird behaviour occurs if we consider one of the folders to be generated at buildtime, ergo not present at project evaluation time. So let's just put that in a Target:
```
<ItemGroup>
	<Content Include="files1\**" CopyToOutputDirectory="PreserveNewest" TargetPath="files\@(RecursiveDir)%(Filename)%(Extension)"/>			
</ItemGroup>
<Target Name="SomeTarget" BeforeTargets="ClCompile">
	<ItemGroup>
		<Content Include="files2\**" CopyToOutputDirectory="PreserveNewest" TargetPath="files\@(RecursiveDir)%(Filename)%(Extension)"/>
	</ItemGroup>
</Target>
```
Now MSBuild gets confused and starts overwriting the files with each other:
>  Copying file from "D:\Dev\Sandbox\CppSandbox\files1\c.txt" to "D:\Dev\Sandbox\CppSandbox\x64\Debug\files\c.txt".
  Copying file from "D:\Dev\Sandbox\CppSandbox\files1\a.txt" to "D:\Dev\Sandbox\CppSandbox\x64\Debug\files\a.txt".
  Copying file from "D:\Dev\Sandbox\CppSandbox\files1\b.txt" to "D:\Dev\Sandbox\CppSandbox\x64\Debug\files\b.txt".
  Copying file from "D:\Dev\Sandbox\CppSandbox\files2\d.txt" to "D:\Dev\Sandbox\CppSandbox\x64\Debug\files\b.txt".
  Copying file from "D:\Dev\Sandbox\CppSandbox\files2\d.txt" to "D:\Dev\Sandbox\CppSandbox\x64\Debug\files\c.txt".
  Copying file from "D:\Dev\Sandbox\CppSandbox\files2\d.txt" to "D:\Dev\Sandbox\CppSandbox\x64\Debug\files\a.txt".
  Copying file from "D:\Dev\Sandbox\CppSandbox\files2\e.txt" to "D:\Dev\Sandbox\CppSandbox\x64\Debug\files\b.txt".
  Copying file from "D:\Dev\Sandbox\CppSandbox\files2\e.txt" to "D:\Dev\Sandbox\CppSandbox\x64\Debug\files\c.txt".
  Copying file from "D:\Dev\Sandbox\CppSandbox\files2\e.txt" to "D:\Dev\Sandbox\CppSandbox\x64\Debug\files\a.txt".
  Copying file from "D:\Dev\Sandbox\CppSandbox\files2\f.txt" to "D:\Dev\Sandbox\CppSandbox\x64\Debug\files\b.txt".
  Copying file from "D:\Dev\Sandbox\CppSandbox\files2\f.txt" to "D:\Dev\Sandbox\CppSandbox\x64\Debug\files\c.txt".
  Copying file from "D:\Dev\Sandbox\CppSandbox\files2\f.txt" to "D:\Dev\Sandbox\CppSandbox\x64\Debug\files\a.txt". 

### Versions & Configurations

Microsoft (R) Build Engine version 16.11.2+f32259642 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.
16.11.2.50704

or

MSBuild version 17.5.0+6f08c67f3 for .NET Framework
17.5.0.10706

**Comment by JanKrivanek** [comment]
Once properly investigated and documented here - a good candidate to include in the documentation/learning effort: https://github.com/dotnet/msbuild/issues/8447

**Comment by JanKrivanek** [comment]
@KalleOlaviNiemitalo Great suggestion. We've discussed this idea yesterday (without details on how to detect possible missues - your suggestion is nicely expanding that thought).

I'd probably modify the point 3 above ('does not reference any qualified `%(itemtype.metadata)`' to disallow `%(itemtype.metadata)` reference of self as well) - adding the suggestion inline, as your list is a nice reference
