### ISSUE TITLE
[browser][Codespaces] Build does not pass on Codespaces

### ISSUE THREAD

**Issue by ilonatommy** [dotnet/msbuild#8531]
Building runtime on Codespaces, e.g. `./dotnet.sh build -os browser -c Debug` fails with:
![image](https://user-images.githubusercontent.com/32700855/222734081-13acbbdd-825d-4b63-a28f-37579ed38d51.png)

The manual fix is to go to set `UseHardlinksIfPossible=false` in the affected targets (`intellisense.targets`, `optimizationData.targets`), see: https://github.com/dotnet/runtime/issues/14537#issuecomment-1410161834.

**Comment by rainersigwald** [comment]
@JaynieBai please let us know if you won't be able to get to this and we'll reassign.

**Comment by ilonatommy** [comment]
> How can I reproduce this?

1) main branch, no changes
2) running build e.g. `./dotnet.sh build -os browser -c Debug`
