### ISSUE TITLE
DownloadFile errors may dump stack to the user

### ISSUE THREAD

**Issue by danmoseley** [dotnet/msbuild#8538]
### Issue Description

With https://github.com/dotnet/msbuild/pull/8440 MSBuild is now logging callstacks for scenarios in which neither MSBuild, nor a logger, nor a task has any bug.
Assertion: a callstack should indicate someone should make a bug report.

### Steps to Reproduce

See discussion here https://github.com/dotnet/msbuild/pull/8440#issuecomment-1437783713

### Actual Behavior

The info relevant to the user should all be in the exception messages. The code should instead concatenate (or equivalent) the exception message and that of any inner exceptions, and display that.

**Comment by AR-May** [comment]
MSBuild team triage: For this case let's log the `ex.ToString()` in the low-prio message, so it shows up in -diag log or binlog. And the recursively (concatenated) error in the error message.
