### ISSUE TITLE
[Feature Request]: Bitshift MSBuild Property Function

### ISSUE THREAD

**Issue by 333fred** [dotnet/msbuild#8551]
### Issue Description

For reasons being Android version codes (which must be a single number), I'd like to be able to bitshift various parts of my major/minor/patch numbers together to make a single applicationversion number. There's no msbuild property function for this today, though, so I need to resort to an inline task. We already have some bitwise ops (such as `and` and `or`), but not shifts.

### Steps to Reproduce

N/A

### Expected Behavior

N/A

### Actual Behavior

N/A

### Analysis

https://github.com/dotnet/msbuild/blob/main/src/Build/Evaluation/IntrinsicFunctions.cs will need to be updated.

**Comment by rainersigwald** [comment]
I have no objection to adding `$([MSBuild]::LeftShift())` and friends next to `$([MSBuild]::Add())` in `IntrinsicFunctions`.

> It seems the documentation is a bit incomplete as it does not say that the static method or property must be public.

https://github.com/MicrosoftDocs/visualstudio-docs/pull/9045

**Comment by 333fred** [comment]
> Could multiply or divide with powers of two instead.

I could, yes, but I feel that's more unmaintainable than a code task.

**Comment by jrdodds** [comment]
If this issue passes triage, I would be happy to have it assigned to me. Thanks.

I'm assuming the work would be to add three new methods in `IntrinsicFunctions`:

- LeftShift
- RightShift
- RightShiftUnsigned

**Comment by jrdodds** [comment]
The existing bit operator functions are int only.

Is there a use case for long?

The functions wouldn't be overloaded. They would need to have different names.

**Comment by AR-May** [comment]
Team triage: We would like to have it. We are assigning it to @jrdodds, thank you for volunteering!

@333fred, are 32-bit operators sufficient for you?

**Comment by 333fred** [comment]
32-bit operators would be sufficient, as Android version codes are a single 32-bit int.
