### ISSUE TITLE
[Bug]: UseTrustedSettings parameter for XslTransformation task is ignored when using dotnet build

### ISSUE THREAD

**Issue by edstegman** [dotnet/msbuild#8570]
### Issue Description
(edited to add zip file of demo solution)

When building in VS 2022 or using msbuild from the comand line my project compiles. When building using dotnet build my project fails to compile.

The failure is on the XslTransformation task in my .csproj. The error is _error MSB3703: Unable to execute transformation. An error occurred while loading document '{path to file elided}'. See InnerException for a complete description of the error. [TargetFramework=netstandard2.0]_

### Steps to Reproduce

1. Unzip and open the attached solution.
[UseTrustedSettingsBug.zip](https://github.com/dotnet/msbuild/files/11035915/UseTrustedSettingsBug.zip)

3. Build in Visual Studio. (It succeeds.)
4. Command line build: msbuild.exe "UseTrustedSettingsBug.sln" (It succeeds.)
5. To confirm, open UseTrustedSettingsBug\obj\Debug\netstandard2.0\documentation.xml 
6. Command line build: dotnet build "UseTrustedSettingsBug.sln" (It fails.)

### Expected Behavior

The project compiles without errors when using 'msbuild' or 'dotnet build' command.

### Actual Behavior

The project compiles when using the msbuild command, but fails to compile when using dotnet build command, due to an error executing the XslTransformation task.

### Analysis

It appears that the dotnet build engine is not passing the UseTrustedSettings argument of "true" to the XslTransformation task instance it is creating to run the task. 

(Sorry, I have no idea what to call this build engine. dotnet build --version returns "MsBuild" but it obviously not msbuild because invoking msbuild works without error. </sigh>)

Here are links to source code for XslTransformation and XsltSettings. 

https://github.com/dotnet/msbuild/blob/60ea2f733cfcc78da965ab43cf040fe5c58800fb/src/Tasks/XslTransformation.cs#L450
https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/libraries/System.Private.Xml/src/System/Xml/Xslt/XsltSettings.cs#L31

You can see in the LoadXslt method when the UseTrustedSettings property = true it is passing an XsltSettings.TrustedXslt to the XslCompiledTransform.LoadMethod. The XsltSettings.TrustedXslt returns a new instance of XsltSettings created with the ctor argument enableDocumentFunction = true;

If the UseTrustedSettings property was being set properly by dotnet build there would not be an error when encountering the xslt document function.

### Versions & Configurations

Microsoft Visual Studio Professional 2022 (64-bit) - Current
Version 17.5.1

❯ msbuild -version

MSBuild version 17.5.0+6f08c67f3 for .NET Framework
17.5.0.10706

❯ dotnet build -version
MSBuild version 17.5.0-preview-23061-01+040e2a90e for .NET
17.5.0.6101

**Comment by JaynieBai** [comment]
Hi @edstegman.  Did you forget to attach the repro solution?  :)

**Comment by edstegman** [comment]
I dragged and dropped it on the form before submitting. Most likely I made some kind of operator error. Here you go.
[UseTrustedSettingsBug.zip](https://github.com/dotnet/msbuild/files/11035903/UseTrustedSettingsBug.zip)

**Comment by JaynieBai** [comment]
Debug msbuild with dotnet ./artifacts/bin/bootstrap/net7.0/MSBuild/MSBuild.dll at the project file.  UseTrustedSettings is set as true, and settings = XsltSettings.TrustedXslt;  is hit.  

 Find the exception is throwed in https://github.com/dotnet/msbuild/blob/b84faa7d0dfb42daedca5c244f73f0b07e1135d7/src/Tasks/XslTransformation.cs#L168

The innerException is "Resolving of external URIs was prohibited. Attempted access to: {path to file elided}".  This maybe be a known compatible issue. NET Core does not allow resolving external URIs for XML by default  https://github.com/dotnet/runtime/issues/26969#issuecomment-408175222  @rainersigwald   What's your point how to deal with such issue?

**Comment by edstegman** [comment]
Sorry I couldn't identify the root cause. The inner exception is not output in the build log, even after cranking up the build verbosity to diagnostic.

There is room for improvement in this area in the build logging.

**Comment by rainersigwald** [comment]
> There is room for improvement in this area in the build logging.

Agreed. This is another case like the recently-fixed #8407 where we should not hide that inner exception.

**Comment by JanKrivanek** [comment]
Discussed offline - 2 separate PRs will be created (one needs security approval)

**Comment by edstegman** [comment]
I found another minor issue WRT UseTrustedSettings parameter that doesn't affect compilation behavior for MSBuild, but does affect intellisense/static analysis in the VS2022 IDE for the .csproj file when using the parameter.

The Microsoft.Build.Commontypes.xsd file is missing the UseTrustedSettings attribute for the XslTransformation element.
    <xs:element name="XslTransformation" substitutionGroup="msb:Task">
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="msb:TaskType">
                    <xs:attribute name="OutputPaths" use="required" />
                    <xs:attribute name="Parameters" />
                    <xs:attribute name="XmlContent" />
                    <xs:attribute name="XmlInputPaths" />
                    <xs:attribute name="XslCompiledDllPath" />
                    <xs:attribute name="XslContent" />
                    <xs:attribute name="XslInputPath" />
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>

 The issue also exists for earlier versions of Visual Studio, indicating it is not a new issue.

**Comment by rainersigwald** [comment]
@KalleOlaviNiemitalo nope, we forgot https://github.com/dotnet/msbuild/issues/8764. Thanks!

**Comment by JaynieBai** [comment]
> Re logging, the XslTransformation task calls TaskLoggingHelper.LogErrorWithCodeFromResources(string messageResourceName, params object[] messageArgs). There is also TaskLoggingHelper.LogErrorFromException(Exception exception, bool showStackTrace, bool showDetail, string file), which logs the inner exceptions if requested via the showDetail parameter or the "MSBUILDDIAGNOSTICS" environment variable, but this then does not log an error code. I feel there should a method that does both; that way, inner exceptions would be consistently formatted and this feature could be consistently enabled with the environment variable.

Should we reopen the issue or create a new one? My fix added the XmlResolver for the security setting.  But didn't resolve the log method that should log the inner exception and error code together.

**Comment by JanKrivanek** [comment]
@JaynieBai - for logging improvement I'd suggest opening a distinct item - as the current issue is resolved
