### ISSUE TITLE
[Bug]: Microsoft.Build 17.5.0: package doesn't include net6.0 target.

### ISSUE THREAD

**Issue by tmds** [dotnet/msbuild#8577]
### Issue Description

I have an app that targets .NET 6 and .NET 7 with a reference to the latest `Microsoft.Build` package (`17.5.0`).

When I restore my app, I get the following warning:

```
warning NU1701: Package 'Microsoft.Build 17.5.0' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8, .NETFramework,Version=v4.8.1' instead of the project target framework 'net6.0'.
```

### Steps to Reproduce

A project file:
```
...
    <TargetFrameworks>net6.0;net7.0</TargetFrameworks>
...
    <PackageReference Include="Microsoft.Build" Version="17.5.0" ExcludeAssets="runtime" />
```

### Expected Behavior

No warnings are printed.

### Actual Behavior

A warning is printed because the net6.0 is not provided by the package.

### Analysis

The warning occurs because `Microsoft.Build` doesn't target `net6.0`, and that causes the app to fall back to `net472` assets for the .NET 6 build.

In `17.3.0`, the package was targeting `net6.0`. In `17.4.0`, that target was removed and replaced by `net7.0`.

Because .NET 6 is still supported, the package should still provide a `net6.0` target.

**Comment by tmds** [comment]
cc @rainersigwald @Forgind

**Comment by rainersigwald** [comment]
I think the packages are correct, though the end-to-end behavior with the fallback is unfortunate. MSBuild 17.5.0 is usable only in the context of .NET SDK 7.0.200, which requires a .NET 7 runtime, so MSBuild 17.4+ also requires a .NET 7 runtime.

If you want a package that references MSBuild assemblies to work on the .NET 6 runtime, you should target a version of MSBuild that supports that, like 17.3.0.

> Because .NET 6 is still supported, the package should still provide a `net6.0` target.

We don't follow this policy because MSBuild is not usable as a standalone library.

**Comment by tmds** [comment]
ok, based on this, I've updated my references to:

```xml
<PackageReference Condition="'$(TargetFramework)'=='net6.0'" Include="Microsoft.Build" Version="17.3.0" ExcludeAssets="runtime" />
<PackageReference Condition="'$(TargetFramework)'=='net7.0'" Include="Microsoft.Build" Version="17.5.0" ExcludeAssets="runtime" />
```

You can close the issue unless you think there is something that can/should be improved.
