### ISSUE TITLE
how to know if is really publishing in a msbuild task?

### ISSUE THREAD

**Issue by liesauer** [dotnet/msbuild#8585]
### Issue Description

when using publish profile in visual studio, the publish doesn't behave like `dotnet publish`, it runs some kinds of `msbuild.exe` and `csc.exe`.

so i am unable to determine if is publishing in msbuild task.

```
  <UsingTask
    TaskName="_DetermineIsPublishing"
    TaskFactory="$(TaskFactory)"
    AssemblyFile="$(MSBuildToolsPath)/Microsoft.Build.Tasks.Core.dll" >
    <ParameterGroup>
      <Args ParameterType="System.String" Output="true" />
      <IsPublishing ParameterType="System.Boolean" Output="true" />
    </ParameterGroup>
    <Task>
      <Code Type="Fragment" Language="cs">
<![CDATA[
var CommandLineArgs = Environment.GetCommandLineArgs();
if (CommandLineArgs.Length < 2) {
  IsPublishing = false;
} else {
  IsPublishing = CommandLineArgs[1] == "publish";
}
Args = string.Join(" ", CommandLineArgs);
]]>
      </Code>
    </Task>
  </UsingTask>

  <Target Name="_IsPublishing" BeforeTargets="PrepareForBuild">
    <_DetermineIsPublishing>
      <Output TaskParameter="IsPublishing" PropertyName="_RunningIsPublishing" />
      <Output TaskParameter="Args" PropertyName="_RunningArgs" />
    </_DetermineIsPublishing>
  </Target>
```

### Steps to Reproduce

1. publish the project using publish profile in visual studio

### Expected Behavior

have a proper way to know if is building or publishing the project.

### Actual Behavior

can not know if is building or publishing the project when using publish profile in visual studio.

**Comment by vijayrkn** [comment]
@liesauer - When publishing from inside Visual Studio, Visual Studio passes an additional property to msbuild call `deployOnBuild` and the value is true. Can you check for the existence of this property with the given value to determine if it is in the publish part of the build from Visual Studio?

**Comment by liesauer** [comment]
> @liesauer - When publishing from inside Visual Studio, Visual Studio passes an additional property to msbuild call `deployOnBuild` and the value is `true`. Can you check for the existence of this property with the given value to determine if it is in the publish part of the build from Visual Studio?

i can't see the `deployOnBuild` property, but i found another property call `VisualStudioEdition` seems ok for me.

and thanks for responsing.
