### ISSUE TITLE
[Bug]: SDK style Net48 projects do not support transitive dependencies.

### ISSUE THREAD

**Issue by JKlessens** [dotnet/msbuild#8587]
### Issue Description

We are trying to convert a project with a legacy project file, with .Net framework 4.8 as target, to an SDK style project. I used the .Net upgrade assistent (command line) tool for this.

However (among several other problems) we ran into the issue that certain transitive dependencies are not working anymore. After some trial and error I could reproduce it in a new simple Visual Studio solution. And it became clear that it is the combination of .Net framework 4.8 in an sdk style project that is not supporting transitive dependencies.

### Steps to Reproduce

I set up a solution where project a directly depends on project b, which in turn directly depends on project c, and where project a references something in project c. And test it with some different configurations. I tested the following:

```
project a             => project b            => project c
netstandard2.0 SDK    => Net48 Legacy         => Net48 Legacy
netstandard2.0 SDK    => Net48 SDK            => Net48 SDK
netstandard2.0 SDK    => Net48 SDK            => Net48 Legacy
netstandard2.0 SDK    => Net48 SDK            => netstandard2.0 SDK
netstandard2.0 SDK    => netstandard2.0 SDK   => netstandard2.0 SDK
netstandard2.0 SDK    => netstandard2.0 SDK   => Net48 Legacy
```

[testSDKTransitives.zip](https://github.com/dotnet/msbuild/files/11041090/testSDKTransitives.zip)

### Expected Behavior

```
project a             => project b            => project c             || build successful
netstandard2.0 SDK    => Net48 Legacy         => Net48 Legacy          || Yes
netstandard2.0 SDK    => Net48 SDK            => Net48 SDK             || Yes
netstandard2.0 SDK    => Net48 SDK            => Net48 Legacy          || Yes
netstandard2.0 SDK    => Net48 SDK            => netstandard2.0 SDK    || Yes
netstandard2.0 SDK    => netstandard2.0 SDK   => netstandard2.0 SDK    || Yes
netstandard2.0 SDK    => netstandard2.0 SDK   => Net48 Legacy          || Yes
```

### Actual Behavior

```
project a             => project b            => project c             || build successful
netstandard2.0 SDK    => Net48 Legacy         => Net48 Legacy          || Yes
netstandard2.0 SDK    => Net48 SDK            => Net48 SDK             || No
netstandard2.0 SDK    => Net48 SDK            => Net48 Legacy          || No
netstandard2.0 SDK    => Net48 SDK            => netstandard2.0 SDK    || No
netstandard2.0 SDK    => netstandard2.0 SDK   => netstandard2.0 SDK    || Yes
netstandard2.0 SDK    => netstandard2.0 SDK   => Net48 Legacy          || Yes
```

### Analysis

Projects targeting .Net framework 4.8 and using the new SDK style projects do not pass on their transitive dependencies.

### Versions & Configurations

Microsoft (R) Build Engine version 17.1.0+ae57d105c for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

17.1.0.7609

Tool invoking the build in reproduction is Visual Studio 2022 17.1.0
Tool invoking the build in our real life situation is msbuild with version as shown above I think.

edit: fixed some outlining
edit2: changed .Net assistant to .Net upgrade assistant

**Comment by JaynieBai** [comment]
@JKlessens  Thanks for submitting issue.  This issue doesn't repro in latest version. Could you update VS to latest version (Version 17.5.3)?

**Comment by JKlessens** [comment]
Sadly I cannot just upgrade my VS in my work environment. In any case we will upgrade only to LTS versions, when we upgrade. (I think v17.4 will be the next version). Did you get it reproduced on my version?
If I have some time in the coming days/weeks I will install the newest VS on my home pc and try it there.

**Comment by JaynieBai** [comment]
> Sadly I cannot just upgrade my VS in my work environment. In any case we will upgrade only to LTS versions, when we upgrade. (I think v17.4 will be the next version). Did you get it reproduced on my version? If I have some time in the coming days/weeks I will install the newest VS on my home pc and try it there.

Yes. I repro in your version. But can't repro in new version. I think this issue has been fixed in new version. So please upgrade that to LTS version if it works.

**Comment by JKlessens** [comment]
Ok, thank you. We will upgrade as soon as possible, and use a work around until then.
