### ISSUE TITLE
Generated code is not included.

### ISSUE THREAD

**Issue by devsko** [dotnet/msbuild#8593]
### Issue Description

Target `GenerateCode` in `Client.csproj` generates `ServiceClient.cs` inside the project.
`ClientTest` references `Client` and calls `ServiceClient.Action()`

When built from the command line, the generated code is not included in the assembly. Interestingly a build in Visual Studio works as expected. (but fails again with `Condition="'$(DesignTimeBuild)' != 'true'"`)

### Steps to Reproduce

See complete solution here: https://github.com/devsko/DependentProjectBug

```
msbuild DependentProjectBug.sln -t:Clean
msbuild DependentProjectBug.sln -t:Restore -t:Build
```

### Expected Behavior

The generated code should be included in the `Client.dll` assembly.

### Actual Behavior

The generated code is not included. Calling the generated code results in a build failure.

### Analysis

I tried various other Before/AfterTarget's without effect.

### Versions & Configurations

MSBuild 17.6.0.12203
Windows 11 22H2 22624.1465 x64

**Comment by jrdodds** [comment]
MSBuild is smart enough to know that it can start building multiple projects concurrently. A `ProjectReference` is expected to bring in an assembly that is depended upon. MSBuild will have a given project perform its pre-build steps and then wait for an assembly from another project. But `CodeGenerator` doesn't produce an assembly, `Lib` doesn't actually have code references to `CodeGenerator`, and within the `CodeGenerator` project the `GenerateCode` target runs after the `Build`.

Because `CodeGenerator` doesn't produce an assembly and is writing into a different project folder, `CodeGenerator` looks like it is a pre-build step within the `Lib` project; not its own project.

**Comment by rainersigwald** [comment]
@devsko you may be interested in [tutorials about code generation in the docs](https://learn.microsoft.com/visualstudio/msbuild/tutorial-custom-task-code-generation).

**Comment by devsko** [comment]
Thanks for your responses.

@jrdodds I tried to let `CodeGenerator` produce an assembly (as in my real scenario) but the build still failed.

@rainersigwald That's exactly where I come from. I adapted the repo to even better match the documentation that describes almost exactly my scenario.
We have a ASP.NET Core web API and use `NSwag aspnet2csclient` to generate the code in `Client`. The only difference is that we use the service assembly as input and not a `.json` definition but I think that makes no difference.

Maybe I miss something, but I would say the documented example only works in Visual Studio. When built from command line the generated code is not compiled to the assembly. 
When you add `Condition="'$(DesignTimeBuild)' != 'true'"` to the `GenerateClient` target in `Client.csproj` it even fails in VS with `C:\repos\devsko\DependentProjectBug\ClientTest\Program.cs(4,1,4,14): error CS0103: The name 'ServiceClient' does not exist in the current context` A second build completes successfully.

At the moment we have to run the build step twice during CI to get it succeed. It would be great to find a better solution.

**Comment by devsko** [comment]
Okay, I found the solution. Following snippet is missing from target `GenerateClient` in `Client.csproj`
```
    <ItemGroup>
      <Compile Include="ServiceClient.cs" />
    </ItemGroup>
```
This part is also missing in the [documentation](https://learn.microsoft.com/en-us/visualstudio/msbuild/tutorial-rest-api-client-msbuild).

**Comment by jrdodds** [comment]
@devsko If you haven't already, can you open a documentation issue? On the [tutorial page](https://learn.microsoft.com/en-us/visualstudio/msbuild/tutorial-custom-task-code-generation?view=vs-2022) in "Feedback" at the bottom of the page, click "This page". You can cross-ref to this issue.
