### ISSUE TITLE
[Bug]: Wrong parameters in XslTransformation MSB3094 error when XmlInputPaths does not match OutputPaths

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [dotnet/msbuild#8641]
### Issue Description

When the XslTransformation task is called such that the XmlInputPaths and OutputPaths parameters do not have the same number of items, it fails with an MSB3094 error that incorrectly references the XmlContent parameter.

### Steps to Reproduce

Build this project:

```XML
<Project>
  <Target Name="Main">
    <XslTransformation XmlInputPaths="dummy.xml" XslInputPath="dummy.xslt" OutputPaths="" />
  </Target>
</Project>
```

(The dummy.xml and dummy.xslt files need not exist.)

### Expected Behavior

error MSB3094: "OutputPaths" refers to 0 item(s), and "XmlInputPaths" refers to 1 item(s).
They must have the same number of items.

### Actual Behavior

error MSB3094: "XmlContent" refers to 0 item(s), and "XmlInputPaths" refers to 1 item(s).
They must have the same number of items.

### Analysis

<https://github.com/dotnet/msbuild/blob/51df47643a8ee2715ac67fab8d652b25be070cd2/src/Tasks/XslTransformation.cs#L114-L119>

The bug has been there ever since the first public commit.

### Versions & Configurations

MSBuild 17.6.0-preview-23108-10+51df47643 from .NET SDK 8.0.100-preview.1.23115.2

**Comment by rainersigwald** [comment]
@KalleOlaviNiemitalo nice analysis! Would you be interested in submitting a PR? If not we'll mark this `help wanted`.
