### ISSUE TITLE
[Bug]: Wrong parameters in XslTransformation MSB3094 error when XmlContent does not match OutputPaths 

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [dotnet/msbuild#8642]
### Issue Description

When the XslTransformation task is called such that the XmlContent parameter is specified and OutputPaths does not have exactly one item, it fails with an MSB3094 error that shows the wrong number of items in each parameter.

### Steps to Reproduce

Build this project:

```XML
<Project>
  <Target Name="Main">
    <XslTransformation XmlContent="&lt;dummy/&gt;" XslInputPath="dummy.xslt" OutputPaths="out1;out2" />
  </Target>
</Project>
```

(The dummy.xslt file need not exist.)

### Expected Behavior

error MSB3094: "XmlContent" refers to 1 item(s), and "OutputPaths" refers to 2 item(s). They must have the same number of items.

or

error MSB3094: "XmlContent" is specified, and "OutputPaths" refers to 2 item(s). It must have exactly one item.

### Actual Behavior

error MSB3094: "XmlContent" refers to 2 item(s), and "OutputPaths" refers to 1 item(s). They must have the same number of items.

### Analysis

<https://github.com/dotnet/msbuild/blob/51df47643a8ee2715ac67fab8d652b25be070cd2/src/Tasks/XslTransformation.cs#L121-L126>

The bug has been there ever since the first public commit.

### Versions & Configurations

MSBuild 17.6.0-preview-23108-10+51df47643 from .NET SDK 8.0.100-preview.1.23115.2

**Comment by rainersigwald** [comment]
@KalleOlaviNiemitalo nice analysis! Would you be interested in submitting a PR? If not we'll mark this `help wanted`.
