### ISSUE TITLE
[Bug]: Long versions of intrinsic functions are unreachable

### ISSUE THREAD

**Issue by Forgind** [dotnet/msbuild#8698]
### Issue Description

Our arithmetic operations treat everything as a double, which means the 'long' version of our intrinsic functions are unavailable. This can induce floating point arithmetic errors, especially at large values where doubles are less precise. We should try to use long and only fall back to double if the input cannot be parsed as a long.

### Steps to Reproduce

Create a simple console app and add this target:

```XML
  <Target Name="BadSubtract">
    <Message Text="$([MSBuild]::Subtract(9223372036854775807, 9223372036854775806)) should be 1" Importance="High" />
  </Target>
```

Then make that target run.

### Expected Behavior

Outputs `1 should be 1`

### Actual Behavior

Outputs `0 should be 1`

**Comment by jrdodds** [comment]
If this issue moves forward from triage, please consider assigning it to me because I'm familiar with the issue from #8569.

**Comment by Forgind** [comment]
I don't see any problem with fixing this as long as it doesn't regress perf. Will assign 🙂 Appreciate all the help!
