### ISSUE TITLE
[LiveLogger] Broken emoji in the legacy console host on Windows 10

### ISSUE THREAD

**Issue by ladipro** [dotnet/msbuild#8723]
Unfortunately, on Windows 10, the emoji show up as tofu in the legacy console host: 
<image src="https://user-images.githubusercontent.com/27514983/235316716-a98b40c6-4ce7-4471-b90a-51d71e697409.png" alt="LiveLogger build output, with tofu in place of emojis" width="600" />

In Windows 11, conhost supports font fallback, so they appear to work fine. (Simulated by downloading the latest version of the console host from the Terminal repo:)
<image src="https://user-images.githubusercontent.com/27514983/235317257-d0b0ffb2-85db-4b12-83a0-6c170bb1cc85.png" alt="LiveLogger build output, but with emoji displaying properly" width="600" />

And you can work around it by setting `HKEY_CURRENT_USER\Console\UseDx` to 1 (use at your own risk and so on):
<image src="https://user-images.githubusercontent.com/27514983/235317526-f8fe0150-06e0-4528-b0e4-9e4a5a8117b7.png" alt="LiveLogger build output, but with emoji displaying properly, now in full color" width="600" />

_Originally posted by @reflectronic in https://github.com/dotnet/msbuild/issues/8413#issuecomment-1528841156_

**Comment by rainersigwald** [comment]
Closing since we dropped the emoji and haven't gotten much demand to get it back.
