### ISSUE TITLE
[Flaky test] - ToolTaskThatTimeoutAndRetry is randomly failing

### ISSUE THREAD

**Issue by JanKrivanek** [dotnet/msbuild#8750]
### Context
The [ToolTaskThatTimeoutAndRetry](https://github.com/dotnet/msbuild/blob/main/src/Utilities.UnitTests/ToolTask_Tests.cs#LL845C21-L845C48) test needs an external process to wait for the timeout. [PowerShell](https://github.com/dotnet/msbuild/blob/main/src/Utilities.UnitTests/ToolTask_Tests.cs#L902) sleep is used for windows - that however prooves to be a bit unstable in CI

### Evidence
https://github.com/dotnet/msbuild/pull/8659
https://github.com/dotnet/msbuild/pull/8749#issuecomment-1543749828

### Suggestions
* Use other host then PowerShell.exe (e.g. cmd.exe)
* Overload the ExecuteTool method of the ToolTask - so that no external process actually needs to be executed
* Write one-off sleep .exe (overkill)
* ?

**Comment by AR-May** [comment]
Somewhere in the tests there should be the sleep task or target which does not have the problem, so we would want to use it here instead of PowerShell sleep.
