### ISSUE TITLE
[Bug]: "MSBUILD : error MSB4166: Child node "5" exited prematurely. Shutting down. 

### ISSUE THREAD

**Issue by Anakinn** [dotnet/msbuild#8751]
### Issue Description

While attempting to publish a .NET solution with dotnet publish, the following error message is encountered:

"MSBUILD : error MSB4166: Child node "5" exited prematurely. Shutting down. Diagnostic information may be found in files in when doing dotnet publish sln". (sometimes it is "2" or "3" totally random). Resources looks good we are not out of resources.

This happens at random and no more information is provided what is wrong. On some build agents it is consistent. We even rebuild few of them but this issue persists. /nr:false does not have an effect on this. Also this is happening when doing dotnet test. It started recently without any change on build agents.

### Steps to Reproduce

Cannot provide logs from our build agents.

### Expected Behavior

Error message which will point to the real issue.

### Actual Behavior

Unclear error message.

### Analysis

We tried to resolve it for couple of days without luck.

### Versions & Configurations

17.5.0.10706

**Comment by danmoseley** [comment]
I'd expect the message `"MSBUILD : error MSB4166: Child node "5" exited prematurely. Shutting down. Diagnostic information may be found in files in` to continue with `"{1}" and will be named MSBuild_*.failure.txt. This location can be changed by setting the MSBUILDDEBUGPATH environment variable to a different directory.{2}`

**Comment by AR-May** [comment]
Team triage: Could you please set MSBUILDDEBUGPATH and then take a look if you have the mentioned `MSBuild_*.failure.txt` and if there is an error there. 

If this file is not producing useful information, please turn on a `diag` level text log and see if there is a specific project/target/task that runs on the process which is failing.

It may also produce a better diagnostics information if you run your build with `/m:1`. You would not want to have your build all the time this way, but it could catch the error.
