### ISSUE TITLE
[Bug]: Microsoft.Build V17.3.2 nuget package target net6.0 (LTS) has deprecated dependency System.Security.Principal.Windows

### ISSUE THREAD

**Issue by Bertk** [dotnet/msbuild#8757]
### Issue Description

The validation step of my Azure build pipeline fails because the nuget package **System.Security.Principal.Windows V5.0.0** was recently **deprecated**. 

The project arcade-light is targeting the LTS (net6.0) and current STS (net7.0). 

https://dev.azure.com/bertk0374/arcade-light/_build/results?buildId=712&view=logs&j=82714dea-b90c-59c3-0d7d-c3d466a091ea&t=f82296ba-669c-594c-03d0-04c98a1a806a&l=632

### Steps to Reproduce

see [build output ](https://dev.azure.com/bertk0374/arcade-light/_build/results?buildId=712&view=artifacts&pathAsName=false&type=publishedArtifacts)

### Expected Behavior

Microsoft.Build V17.3.2 nuget package has no dependency to deprecated nuget packages.

### Actual Behavior

MSBuild V17.3.2 uses deprecated System.Security.Principal.Windows V5.0.0 nuget package.

### Analysis

see actual beahvior

### Versions & Configurations

MSBuild version 17.6.3+07e294721 for .NET Framework
17.6.3.22601

Visual Studio  V17.6.0-pre.7.0

**Comment by rainersigwald** [comment]
This reference is removed for 17.7+ by https://github.com/dotnet/msbuild/pull/8714.

**Comment by Bertk** [comment]
Thank you for your fast response. Today the deprecated status for nuget package **System.Security.Principal.Windows** was removed.

PR #8714 still uses System.Security.Principal.Windows for ".NETStandard" ??? :wink:

https://github.com/dotnet/msbuild/pull/8714/files#:~:text=Windows%22%20/%3E-,%3CPackageReference%20Include%3D%22System.Security.Principal.Windows%22%20/%3E,-%3CPackageReference%20Include

Anyway, I hope the solution will be available for net6.0 (LTS) and net7.0 (STS).

**Comment by rainersigwald** [comment]
> PR #8714 still uses System.Security.Principal.Windows for ".NETStandard" ??? 😉

Yes, it must since the types aren't part of .NET Standard itself.

> Anyway, I hope the solution will be available for net6.0 (LTS) and net7.0 (STS).

I do not expect to service old versions of MSBuild to remove this redundant dependency.
