### ISSUE TITLE
Sizes of Emojis in Terminal Logger are not the same.

### ISSUE THREAD

**Issue by bsdayo** [dotnet/msbuild#8769]
![Error Emoji](https://github.com/dotnet/msbuild/assets/41754841/4453a934-766f-484e-87fd-a9d067f28fba)
![Warning Emoji](https://github.com/dotnet/msbuild/assets/41754841/14df5766-f6ad-4684-bbe6-c71f8b2983d0)

Environment: Windows 11, Windows Terminal.
Font: JetBrains Mono
Font Size: 11

Tried to switch to other fonts and size, but still performs.

_Originally posted by @bsdayo in https://github.com/dotnet/msbuild/discussions/8768#discussioncomment-5926868_

**Comment by rainersigwald** [comment]
What font are you using? There may be different fallback paths involved depending on that.

**Comment by bsdayo** [comment]
In the screenshot above I am using JetBrains Mono.

Switching to a different font does not work:

Cascadia Code:

![image](https://github.com/dotnet/msbuild/assets/41754841/fd20863b-9d33-4a55-9f34-fb5496ee0c2b)

Consolas:

![image](https://github.com/dotnet/msbuild/assets/41754841/7a24fe6c-f8fa-4272-ae5d-c5f56c45178d)

I have not modified the display fonts for Windows.

**Comment by baronfel** [comment]
We're aiming to remove the emoji entirely for preview6 in favor of more limited, accented coloration to sidestep this issue.

**Comment by ladipro** [comment]
@KalleOlaviNiemitalo, I don't believe we currently throttle the rewrites if the terminal connection is slow. It probably deserves a separate issue.

@bsdayo, #8719 attempted to fix the misalignment issue. Does it still reproduce in Preview 5 and later for you?

**Comment by bsdayo** [comment]
> @KalleOlaviNiemitalo, I don't believe we currently throttle the rewrites if the terminal connection is slow. It probably deserves a separate issue.
> 
> @bsdayo, #8719 attempted to fix the misalignment issue. Does it still reproduce in Preview 5 and later for you?

Still reproducible, but a bit different

<img width="817" alt="image" src="https://github.com/dotnet/msbuild/assets/41754841/6fb0d851-9cba-4c97-a61e-48d43bea4351">

<img width="49" alt="image" src="https://github.com/dotnet/msbuild/assets/41754841/f116904d-1ff2-492a-9a92-001cb45a538d">
<img width="42" alt="image" src="https://github.com/dotnet/msbuild/assets/41754841/3b7a9ca7-89a5-4d5f-bdd7-f7e7bd7702d6">

**Comment by bsdayo** [comment]
nvm, found that it is related to terminal font.

After changing to Cascadia Code:

<img width="121" alt="image" src="https://github.com/dotnet/msbuild/assets/41754841/574c848a-7109-4f71-9f8f-85bb81a168ac">

Thanks!
