### ISSUE TITLE
[Bug]: Terminal logger formatting issue when displaying running targets

### ISSUE THREAD

**Issue by vitek-karas** [dotnet/msbuild#8781]
### Issue Description

I tried to add `/tl` to the build in dotnet/runtime repo. For the most part it works great - I like this.
But in some cases the "active" targets (the lines which are updating with times) get mangled a little bit:
![image](https://github.com/dotnet/msbuild/assets/10670590/07a58888-e34c-49b7-8c57-6404bfdb10a7)

This is on Windows, running in Windows Terminal under powershell (.NET 7 pwsh).

### Steps to Reproduce

Run something like:
`.\build.cmd Clr+Libs /tl` in dotnet/runtime repo.

### Expected Behavior

Each target shows exactly one time.

### Actual Behavior

Some targets sometimes show the time twice (with only the second one updating)

**Comment by baronfel** [comment]
This _may_ already be solved with nightlies - we had a width-calculation issue that has been fixed. Can you try to reproduce with preview5 nightlies if you get a chance?

**Comment by vitek-karas** [comment]
Will see - I can't build the runtime with a preview SDK (well, I could but it's rather complicated)

One more question:
![image](https://github.com/dotnet/msbuild/assets/10670590/380fce54-3964-496d-b45e-c2199374ef9f)

Will we fix this to show humanly readable duration - as in `minutes:seconds`?

**Comment by baronfel** [comment]
I suppose we could - but if we leave it in seconds isn't that motivation for the runtime team to make their build faster? (I kid, of course :) )

**Comment by vitek-karas** [comment]
Do you want me to file a separate issue?

I would **love** to be able to build runtime in less than 60 seconds, maybe the new msbuild can make that happen ;-)

**Comment by baronfel** [comment]
I went ahead and created a new issue from your comment/request.

**Comment by rainersigwald** [comment]
I don't think this is solved yet--I believe I messed up truncation-to-fit-in-window when I colorized TF in #8715.

**Comment by rainersigwald** [comment]
Should be fixed by #8907.
