### ISSUE TITLE
[Bug]: "Assembly loaded during Evaluation" shown during build despite minimal output selected

### ISSUE THREAD

**Issue by DominikGrabiec** [dotnet/msbuild#8784]
### Issue Description

Updated to Visual Studio 2022 17.6 and now whenever I first build I get three lines of "Assembly loaded during Evaluation" for each project that I am building. My msbuild output verbosity setting within Visual Studio is set to "minimal" so I would not expect these messages to be shown.

This is shown just after `------ Build started: Project:` :
```
Assembly loaded during Evaluation: System.Collections.Immutable, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (location: C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\System.Collections.Immutable.dll, MVID: 5f9ff90f-0d16-4469-a104-76829d3705e2, AppDomain: [Default])
Assembly loaded during Evaluation: Microsoft.IO.Redist, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 (location: C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\Microsoft.IO.Redist.dll, MVID: d528d43e-4d35-4c28-8aa6-a5ce49a5eba7, AppDomain: [Default])
Assembly loaded during Evaluation: Microsoft.Build.Utilities.Core, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (location: C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\Microsoft.Build.Utilities.Core.dll, MVID: fbb0ad21-bf4f-4348-a20a-cfe351e23e51, AppDomain: [Default])
```

These messages bring no value to me and are distracting as usually the only messages that long are warnings and errors which need to be dealt with.

I'm not sure if this would qualify as a bug or a feature request, so I've made it a bug for simplicity's sake, and let the msbuild experts figure out an appropriate solution.

### Steps to Reproduce

Build a C++ project with Visual Studio 2022 17.6 just after starting Visual Studio and having no lingering msbuild instances. Additional builds while msbuild instances are resident do not emit these extra messages.

### Expected Behavior

```
2>------ Rebuild All started: Project: DataAPI, Configuration: Debug x64 ------
2>Building Custom Rule E:/Source/Libraries/DataAPI/CMakeLists.txt
2>Values.cpp
2>Generating Code...
2>DataAPI.vcxproj -> E:\Build\Libraries\DataAPI\Debug\DataAPI.lib
```

### Actual Behavior

```
2>------ Build started: Project: DataAPI, Configuration: Debug x64 ------
2>Assembly loaded during Evaluation: System.Collections.Immutable, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (location: C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\System.Collections.Immutable.dll, MVID: 5f9ff90f-0d16-4469-a104-76829d3705e2, AppDomain: [Default])
2>Assembly loaded during Evaluation: Microsoft.IO.Redist, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 (location: C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\Microsoft.IO.Redist.dll, MVID: d528d43e-4d35-4c28-8aa6-a5ce49a5eba7, AppDomain: [Default])
2>Assembly loaded during Evaluation: Microsoft.Build.Utilities.Core, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (location: C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\Microsoft.Build.Utilities.Core.dll, MVID: fbb0ad21-bf4f-4348-a20a-cfe351e23e51, AppDomain: [Default])
2>Values.cpp
2>DataAPI.vcxproj -> E:\Build\Libraries\DataAPI\Debug\DataAPI.lib
```

### Analysis

I believe the code was introduced in [this pull request](https://github.com/dotnet/msbuild/pull/8316), and I see two ways in which this could be mitigated, either:
* by removing them from the 'minimal' verbosity configuration
* or by adding a command line option or global environment setting to enable printing of them

### Versions & Configurations

```
MSBuild version 17.6.3+07e294721 for .NET Framework
17.6.3.22601
```

**Comment by JanKrivanek** [comment]
@DominikGrabiec can you confirm your Visual Studio MSBuild verbosity levels?

We had recently similar case where that turned out to be caused by `Diagnostic` verbosity:
https://developercommunity.visualstudio.com/t/Build-spamming-NET-assembly-load-messag/10365884#T-N10367400-N10369224

**Comment by DominikGrabiec** [comment]
My "MSBuild project build output verbosity:" is set to "Minimal", and my "MSBuild project build log file verbosity:" is set to "Normal". 

I did a little bit of experimenting and found out the following:
* When building after upgrade with unchanged settings from before the upgrade I ended up having those log messages displayed whenever a new MSBuild instance was started for the build.
* Having changed the "log" verbosity to "Minimal" I could not get the messages to appear in the output window.
* Changing the "log" verbosity back to "Normal" I could not get the messages to appear. (Even with MSBuild instances being force closed).
* Changing the "log" verbosity to "Diagnostic" made them reappear in the output window.
* Changing the "log" verbosity back to "Normal" hid those log messages from the output window.

Now I do have to question if this is the correct behaviour still, because changing the "log" verbosity within Visual Studio should change what gets put into the log file on disk, not what appears in the output window of Visual Studio. That should be controlled by the "output" verbosity setting.

There might also be an issue with a setting not getting correctly refreshed to the correct new value when upgrading Visual Studio versions, as the output kept happening to me on "Normal" logging when it shouldn't have.

**Comment by JanKrivanek** [comment]
Thank you @DominikGrabiec for the followup. It certainly looks quite unexpected.
It doesn't seem to be MSBuild related - I'm trying to check intenrnaly for possible cause in Visual Studio.

**Comment by JanKrivanek** [comment]
Hi @JaynieBai can you please try to quickly repro this - VS and SDK (`dotnet build --verbosity ...`), and CPS vs csproj vs cpp projects?

**Comment by JaynieBai** [comment]
> Hi @JaynieBai can you please try to quickly repro this - VS and SDK (`dotnet build --verbosity ...`), and CPS vs csproj vs cpp projects?

@JanKrivanek  I repro this issue with CPS vs csproj vs cpp projects in VS when the MSBuild project build log file verbosity is diag and detailed  
But SDK (dotnet build --verbosity:diag ...) doesn't show the same Assembly loaded during Evaluation with VS. It doesn't repro in SDK.

**Comment by jmecosta** [comment]
This is such a basic feature that I wonder why no one complains about it more. In fact, it can be an interesting feature when debugging loading DLLs for your own use. However, if you're actually trying to perform some real work, you would want it to be disabled. I'm currently trying to dig into build errors, and these log messages are just spamming all over the place.
