### ISSUE TITLE
Targets hooked BeforeTargets a conditioned target run after instead

### ISSUE THREAD

**Issue by rainersigwald** [dotnet/msbuild#8788]
```xml
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Target Name="Hooked" Condition="$(RunHooked)" />
  <Target Name="Before" BeforeTargets="Hooked" />
</Project>
```

```sh-session
❯ C:\Windows\Microsoft.NET\Framework\v4.0.30319\MSBuild.exe .\foo.proj /v:d /p:RunHooked=true
Microsoft (R) Build Engine version 4.8.9032.0
[Microsoft .NET Framework, version 4.0.30319.42000]
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 5/22/2023 12:51:33 PM.
Project "S:\msbuild\foo.proj" on node 1 (default targets).
Building with tools version "2.0".
Target "Before" in project "S:\msbuild\foo.proj" (target "Hooked" depends on it):
Done building target "Before" in project "foo.proj".
Target "Hooked" in project "S:\msbuild\foo.proj" (entry point):
Done building target "Hooked" in project "foo.proj".
Done Building Project "S:\msbuild\foo.proj" (default targets).


Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:00.10
```

Right, yes.

```sh-session
❯ C:\Windows\Microsoft.NET\Framework\v4.0.30319\MSBuild.exe .\foo.proj /v:d /p:RunHooked=false
Microsoft (R) Build Engine version 4.8.9032.0
[Microsoft .NET Framework, version 4.0.30319.42000]
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 5/22/2023 12:51:28 PM.
Project "S:\msbuild\foo.proj" on node 1 (default targets).
Building with tools version "2.0".
Target "Hooked" skipped, due to false condition; ($(RunHooked)) was evaluated as (false).
Target "Before" in project "S:\msbuild\foo.proj" (target "Hooked" depends on it):
Done building target "Before" in project "foo.proj".
Done Building Project "S:\msbuild\foo.proj" (default targets).


Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:00.10
```

The [docs on target ordering](https://learn.microsoft.com/visualstudio/msbuild/target-build-order?view=vs-2022#determine-the-target-build-order) say

> The `Condition` attribute of the target is evaluated. If the `Condition` attribute is present and evaluates to `false`, the target isn't executed and has no further effect on the build.
>
> Other targets that list the conditional target in `BeforeTargets` or `AfterTargets` still execute in the prescribed order.

But that's not happening here, the condition is determining whether `Before` runs before or after `Hooked`, somehow.

Still repros in 17.7, but longstanding.

**Comment by rainersigwald** [comment]
@AArnott asked about this with a more complicated repro (the condition on the hooked target depended on the target declaring `BeforeTargets` running to populate an item).

**Comment by rokonec** [comment]
Wen looking at code it seems to behave by default.
It is little confusing though because the skip-for-condition-false log event is logged at the time of condition evaluation which is and must be before "before" targets are executed.
1) target is processed for dependency graph purposes
2) condition is evaluated to know if "depends on" targets shall be scheduled - logged as skipped
3) "before" targets are scheduled
4) executing scheduled targets, i.e. only "before" targets

**Comment by rokonec** [comment]
By design
