### ISSUE TITLE
[Broken Build]: Want to generate all platform appxupload build

### ISSUE THREAD

**Issue by novemberi** [dotnet/msbuild#8797]
### Issue Description

I'm now using jenkins for automation generate `.appxupload`.

The first step is working good (I guess), cause the first ARM build output dir is no problem.
`build\bin\Master\ARM\GameAssembly.lib` - This is no problem.
But the next build for other architecture(in this case is x86)
I got error like this
```
(CreateWinMD target) -> 
  LINK : fatal error LNK1181: cannot open input file 'build\bin\ARM\Master\x64\My Project\GameAssembly.lib' [Project path\My Project\Club Vegas.vcxproj]
```

Why x64 directory is created inside ARM build?

### Steps to Reproduce

`msbuild "My Project.sln" -p:Configuration:"Master" -p:UapAppxPackageBuildMode="StoreUpload"`
This is my vcxproj property.
```
  <PropertyGroup>
    <OutDir>$(SolutionDir)build\bin\$(Platform)\$(Configuration)\</OutDir>
    <IntDir>$(SolutionDir)build\obj\$(MSBuildProjectName)\$(Platform)\$(Configuration)\</IntDir>
    <AppxBundle>Always</AppxBundle>
    <UseDotNetNativeToolchain>true</UseDotNetNativeToolchain>
    <GenerateAppInstallerFile>False</GenerateAppInstallerFile>
    <AppxPackageSigningTimestampDigestAlgorithm>SHA256</AppxPackageSigningTimestampDigestAlgorithm>
    <AppxAutoIncrementPackageRevision>True</AppxAutoIncrementPackageRevision>
    <GenerateTestArtifacts>True</GenerateTestArtifacts>
    <AppxBundlePlatforms>ARM|x86|x64</AppxBundlePlatforms>
    <HoursBetweenUpdateChecks>0</HoursBetweenUpdateChecks>
  </PropertyGroup>
```

### Expected Behavior

I want to get appxupload file like this.
App Name_version_x86_x64_arm_bundle_Master.appxupload

This appxupload I can generate inside Visual Studio - Create App Packages wizard.

### Actual Behavior

```
(CreateWinMD target) -> 
  LINK : fatal error LNK1181: cannot open input file 'build\bin\ARM\Master\x64\My Project\GameAssembly.lib' [Project path\My Project\Club Vegas.vcxproj]
```

**Comment by AR-May** [comment]
Team triage: @olgaark, can you please have a look if this is related to cpp build infra?

**Comment by olgaark** [comment]
I cannot say much without binlog, but "build\bin\ARM\Master\x64\My Project\GameAssembly.lib" contains "ARM" and "x64" which does not look right, especially for building x86 and indicates that OutDir was redefined somewhere in targets.

**Comment by novemberi** [comment]
OutDir is no problem in my vcxproj.
I found `-p:UseSubFolderForOutputDirDuringMultiPlatformBuild=false` param, and this helping for me in this case.
