### ISSUE TITLE
[Bug]: Input file "*.CoreCompileInputs.cache" is newer than output file "*.pdb"

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/msbuild#8807]
### Issue Description

binlog:

[build-4.8.0-feature.breaking-changes.549-netcoremobile-net7-UWP.zip](https://github.com/dotnet/msbuild/files/11584159/build-4.8.0-feature.breaking-changes.549-netcoremobile-net7-UWP.zip)

### Steps to Reproduce

Search for "is newer than output file" in the binlog. You can see for example the `net7.0-macos` build for Uno.UI.netcoremobile is done twice. The second Csc task execution says:

> Input file "obj\Uno.UI.netcoremobile\Release\net7.0-macos\Uno.UI.netcoremobile.csproj.CoreCompileInputs.cache" is newer than output file "obj\Uno.UI.netcoremobile\Release\net7.0-macos\Uno.UI.pdb".

### Expected Behavior

net7.0-macos should be done only once, ie, the second execution should be up to date and skipped.

### Actual Behavior

It's built twice.

**Comment by rainersigwald** [comment]
There is a race condition in your build, between

`Uno.UI.Build.csproj (BuildCIMobile) -> Uno.UI-netcoremobile-only.slnf (Restore;Build) -> Uno.UI.netcoremobile.csproj -> Uno.UI.netcoremobile.csproj net7.0-macos`

and

`Uno.UI.Build.csproj (BuildCIMobile) -> Uno.UI-netcoremobile-only.slnf (Restore;Build) -> SamplesApp.netcoremobile.csproj -> SamplesApp.netcoremobile.csproj net7.0-macos -> SamplesApp.netcoremobile.csproj net7.0-macos (_BuildRidSpecificAppBundle) -> Uno.UI.Foldable.netcoremobile.csproj net7.0-macos -> Uno.UI.netcoremobile.csproj net7.0-macos`

The latter carries some additional global properties, inherited from `_RunRidSpecificBuild` in `dotnet\packs\Microsoft.macOS.Sdk\13.0.2036\targets\Xamarin.Shared.Sdk.targets` https://github.com/xamarin/xamarin-macios/blob/1ca3c6ad8a27f76dc08903dbe0b1599027ee17cc/dotnet/targets/Xamarin.Shared.Sdk.targets#L338-L350

You should not rely on incremental build to resolve this build race condition and should instead work to eliminate the race. It's not clear to me from the log whether it's a bug in the macOS workload, or in your code. @rolfbjarne may have an opinion.

WRT the rebuild, it looks correct to me--when passed the additional global properties, there's an additional source file `C:\a\1\s\src\Uno.UI\Mixins\macOS\FrameworkElementMixins.g.cs` added to the compilation, so it should in fact build again.

**Comment by Youssef1313** [comment]
@rainersigwald I'm somewhat confused. I see `C:\a\1\s\src\Uno.UI\Mixins\macOS\FrameworkElementMixins.g.cs` is passed to both Csc invocations:

![image](https://github.com/dotnet/msbuild/assets/31348972/c540b8e1-adfd-4e16-97cd-b201159e8d58)

![image](https://github.com/dotnet/msbuild/assets/31348972/746d0dec-02d2-48f7-967a-d669a63a7cff)

**Comment by rainersigwald** [comment]
Ah, you're right--the problem there is that in one invocation it's added after `_GenerateCompileDependencyCache` looks at the compiler inputs. Try changing `MixinGeneration.targets`:

```diff
 <Target Name="GenerateMixins"
 		  Inputs="@(MixinInput)"
 		  Outputs="@(MixinOutput)"
-		  BeforeTargets="DispatchToInnerBuilds;Build;CoreCompile"
+		  BeforeTargets="DispatchToInnerBuilds;Build;BeforeCompile"
 		  Condition="'$(DesignTimeBuild)' != 'true'">
```

**Comment by rolfbjarne** [comment]
We build once for each RuntimeIdentifier, so if RuntimeIdentifiers=osx-arm64;osx-x64, we'll run the build twice (this is what `_RunRidSpecificBuild` does). Each of those builds should be separate, but it seems there are RID-agnostic generated files (the path does not include the RID):

```xml
<MixinOutput Include="$(MSBuildThisFileDirectory)Mixins\macOS\FrameworkElementMixins.g.cs" Condition="$(IsMacOS)" />
```

So I'm guessing these files get re-generated for each build, even though they don't need to be.

**Comment by Youssef1313** [comment]
@rainersigwald Some builds don't seem to run BeforeCompile at all, so this change causes GenerateMixins to not be run as well. Is it okay to include both `CoreCompile` and `BeforeCompile`?

**Comment by Youssef1313** [comment]
Or probably run before `CoreCompile;_GenerateCompileDependencyCache`?

**Comment by rainersigwald** [comment]
> Some builds don't seem to run BeforeCompile at all,

Do you happen to have an example? I find that a bit surprising.

> Is it okay to include both `CoreCompile` and `BeforeCompile`?

Yes; it'll run before whichever one runs first.

> Or probably run before `CoreCompile;_GenerateCompileDependencyCache`, which is a better guarantee?

This is more accurate, but the leading underscore indicates that `_GenerateCompileDependencyCache` is an internal implementation detail of common.targets, so I recommend hooking the public extension point `BeforeCompile`.

**Comment by Youssef1313** [comment]
@rainersigwald Sure.

[build-wasm-uitest-net6-4.9.0-PullRequest-12557-81804-12557.1737.zip](https://github.com/dotnet/msbuild/files/11668927/build-wasm-uitest-net6-4.9.0-PullRequest-12557-81804-12557.1737.zip)

**Comment by AR-May** [comment]
@rainersigwald could you take a look?

**Comment by rainersigwald** [comment]
@Youssef1313 Thanks!

It looks like `Uno.UI.Wasm.csproj` and `Uno.UI.Wasm.Tests.csproj` add an explicit dependency to `CoreCompile` to a property `<CompileTypeScriptDependsOn>CoreCompile;...`, which I think is causing `CoreCompile` to run earlier than it normally would.

You could try making that `Compile` instead, which should enforce `BeforeCompile` running . . . or you could stick with `_GenerateCompileDependencyCache`.
