### ISSUE TITLE
[Feature Request]: Opt-in mechanism for unique default names of binlogs

### ISSUE THREAD

**Issue by JanKrivanek** [dotnet/msbuild#8817]
### Summary

If explicit name for binlog is not specified `msbuild.binlog` is being used - which can lead to silent overwrites of pre-existing binlogs. This is especially painfull in more complicated workflows where msbuild is being invoked multipe times.

The cases where we heared about this could be useful:
* Failing to build C# project with fakes, due to attempts for concurrent writes to msbuild.binlog (https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1791139) FYI @ocallesp 
* Onboard binlogs in AzDO FYI @Json

### Proposed Feature

Add opt-in mechanism (probably commandline switch + environment variable), which would turn on generation of unique default names for binlogs

**Comment by rainersigwald** [comment]
Spitball proposed UX: specify `*` in the binlog file name and we'll expand it with a timestamp + possible disambiguator. So something like

```
msbuild -bl:Restore-*.binlog
```

Would produce `Restore-20230606090832.binlog`.

Downside to `*` is shell escaping it on non-Windows.

**Comment by baronfel** [comment]
Counter-proposal: the default name for a binlog should be `<entry project>.<timestamp in a lexically-sortable format>.binlog`. For example, `fsautocomplete.202311090108.binlog`. This would mean that binlogs for different projects from the same source directory wouldn't clobber. I'm also guessing that in most cases, folks are building the 'default' targets and so including target names in the default binlog file name would be less-than-useful.

**Comment by rainersigwald** [comment]
I like `entryproject.timestamp.binlog`.

**Comment by rainersigwald** [comment]
Maybe `-bl:*` as the gesture to opt into that pattern? That's easy-ish to type and doesn't change the existing behavior.

**Comment by rainersigwald** [comment]
Or should it be `entryproject{.targetifspecified}.timestamp.binlog`?

**Comment by baronfel** [comment]
I'm a little worried about `-bl:*` as a token because shells may expand `*`.

**Comment by f-alizada** [comment]
@rainersigwald @baronfel Another approach is to make feature available only using the environment variable let's say env: MSBUILDBinaryLogFilenameFormat, which could have templated value like "{timestamp}.{target}.binglog" which will result => "202311090108.build.binlog".
This will allow populate the template with different values with a feature request and the approach will not interact with already configured binlog switch parameter functinality. 

MSBUILDBinaryLogFilenameFormat = "*" => 202311090108.binlog
MSBUILDBinaryLogFilenameFormat = "{timestamp}.{target}.binglog" => "202311090108.build.binlog"
what do you think?

**Comment by rainersigwald** [comment]
Looping @KirillOsenkov in for awareness.

**Comment by KirillOsenkov** [comment]
I like most of these. I've always wanted for the entry project or solution name to be mentioned, part of me even regrets that <project>.binlog is not the default. A bit more cautious about allowing formatting, but something like -bl:* sounds great (and we may have several such options for a couple formats). Doubt we need a ton of flexibility here. And yes, probably need a different character than *.

**Comment by KirillOsenkov** [comment]
Heads up for everyone here, there's now a PR with the proposal: #10051
