### ISSUE TITLE
[BinFmt] Investigate the need of removal from deprecated code

### ISSUE THREAD

**Issue by JanKrivanek** [dotnet/msbuild#8822]
### Background 
 #6215
 This subitem is focused on code in `src/Deprecated/*`
 Currently 11 usages. Hopefuly this doesn't need to be touched, or at worst just conditioned, otherwise cost might be significant

### Expected output 
Find answers to below questions (and if any work is recommended to be done - create item for next sprint):
 * Are there any scenarios where code in `src/Deprecated/*` can be part of NET binaries (not FullFW)?
 * Is it find to ceompletely left out this code from BinaryFormatter deprecation effort? Or do we need put usages behind explicit opt-in?
 * Based on above findings - what is the suggested resolution for code in `src/Deprecated/*`?

**Comment by ladipro** [comment]
`Microsoft.Build.Engine` is FullFramework only, no need to worry about it for BF deprecation just yet. The longer-term plan is to remove it from main and stop shipping it altogether (#8826).
