### ISSUE TITLE
[BinFmt] Identify usages of GenerateResource task

### ISSUE THREAD

**Issue by JanKrivanek** [dotnet/msbuild#8827]
### Background 
 #6215
 This subitem is focused on [GenerateResource task](https://github.com/dotnet/msbuild/blob/310891fbe20859c29ff59506062ecd79e2ab987e/src/Tasks/GenerateResource.cs#L56)
 Here we dont need to know exact usages - just gain some idea about magnitude and patterns of usage
GenerateResouce Task uses BinaryFormatter for `application/x-microsoft.net.object.binary.base64` mime type - so we are mainly interested in that one

### Expected output
* List of internal repos that use `GenerateResource` task + some sample usages
* Examples of external GH repos (with recent activity) using `GenerateResource` task
* Count of external repos using `GenerateResource` task, idealy categorized by recent usage and # of commits, or some relativelu useful metric giving idea of how much/few it's being used (especialy for Core).

### TODO

what about resgen.exe?

**Comment by JanKrivanek** [comment]
FYI @Forgind - the search might be simplified via simply adding an implicit `GenerateResourceWarnOnBinaryFormatterUse` parameter with `true` value (somewhere into common targets? the FullFW version of MSBuild should be likely skipped)

**Comment by rainersigwald** [comment]
To a first approximation, the set of "repos that use GenerateResource" is the same as the set of "repos that use .NET". Search for `.resx` files or `EmbeddedResource` items to find most uses.

Few call `GenerateResource` directly; generally it's used through common.targets

https://github.com/dotnet/msbuild/blob/9604d20e7b556ca53a519a82680d131c2aa71bc6/src/Tasks/Microsoft.Common.CurrentVersion.targets#L3293-L3295

**Comment by JanKrivanek** [comment]
Based on offlien discussion with @rainersigwald - `GenerateResource` task targetting NET actually currently doesn't use `BinaryFormatter` at all (it just transfers the base64 encoded data, with de-/en-coding just the binary format, but performs no de/serialization of the actual data in the blobs - this happens only during generating .resx files and then during runtime when reading embedded resources - both outside of the scope of msbuild)

**Comment by ladipro** [comment]
Confirming the findings above. The one direct use of `BinaryFormatter` is basically an optimization to see if input resources should be read in another AppDomain. Then the task indirectly uses `BinaryFormatter` when it deserializes input resources and re-serializes them to its output. All of this is ifdefed out in .NET (Core) MSBuild so we're safe for now.

The resource story end-to-end is out of scope, the task is just a conversion tool.
