### ISSUE TITLE
[Bug]: Binlog doesn't contain input parameters anymore

### ISSUE THREAD

**Issue by rolfbjarne** [dotnet/msbuild#8845]
### Issue Description

It seems binlogs don't contain input parameters by default anymore.

### Steps to Reproduce

* Get a daily version of .NET (I'm using 8.0.100-preview.6.23305.2).
* Create a new project
* `dotnet build /bl`

```shell
$ dotnet new console
$ dotnet build /bl
```

Inspect the resulting binlog, noting that parameters are not there:

<img width="733" alt="Screenshot 2023-06-06 at 12 50 46" src="https://github.com/dotnet/msbuild/assets/249268/f0e265e4-0a16-4334-9a98-3a66a29893ac">

### Expected Behavior

Binlog should include every scrap of information it can.

### Actual Behavior

Missing information from the binlog.

### Analysis

This regressed somewhere between `8.0.100-preview.6.23279.5` and 
`8.0.100-preview.6.23305.2`.

The dotnet/msbuild diff for that is: https://github.com/dotnet/msbuild/compare/d077d294fa30f3ce8a8eda70f4630234a8f6c4c9...9604d20e7b556ca53a519a82680d131c2aa71bc6

Looking at the commit list, I found one suspect:

https://github.com/dotnet/msbuild/pull/8805

And then it occurred to me to tried to explicitly pass the verbosity:

```shell
$ dotnet build /bl:msbuild-diagnostic.binlog /v:diag
```

And now the extra information is in the new binlog:

```
$ ls -la *.binlog
-rw-r--r--  1 rolf  wheel  379046 Jun  6 12:47 msbuild-diagnostic.binlog
-rw-r--r--  1 rolf  wheel  353999 Jun  6 12:43 msbuild.binlog
```

Note how the size is different.

Both binlogs: [binlogs.zip](https://github.com/dotnet/msbuild/files/11663561/binlogs.zip)

### Versions & Configurations

```
$ 
dotnet --version
8.0.100-preview.6.23305.2
```

**Comment by rainersigwald** [comment]
Thanks for the report and analysis, @rolfbjarne. Should be fixed in next SDK flow.
