### ISSUE TITLE
[Broken Build]: how to build subproject of SLN using msbuild?

### ISSUE THREAD

**Issue by snikeguo** [dotnet/msbuild#8866]
### Issue Description

how to build subproject of SLN using msbuild?
This is my current compilation command:
```
devenv .\my.sln /Project "myproject" /build "Release|x86"
```
This compilation is very slow, so I want to use msbuild to compile the subproject.

The following command cannot be compiled,Because it involves some directory issues
```
msbuild  .\myfold\myproject /t:build .....
```
I expect msbuild to support similar commands:
```
msbuild  .\my.sln /p:project "myproject"    ......
```

### Steps to Reproduce

1

### Expected Behavior

1

### Actual Behavior

1

### Ask us questions

1

**Comment by jrdodds** [comment]
> I expect msbuild to support similar commands:
> 
> ```
> msbuild  .\my.sln /p:project "myproject"    ......
> ```

[MSBuild ](https://learn.microsoft.com/en-us/visualstudio/msbuild/msbuild-command-line-reference?view=vs-2022)does not follow the [`devenv` commands switches](https://learn.microsoft.com/en-us/visualstudio/ide/reference/devenv-command-line-switches?view=vs-2022). There is no `/Project` switch to MSBuild. The `/p` (or `/property`) switch defines a property and expects _name=value_. But there is no `$(project)` property.

The `devenv` command when given the [`/build` switch](https://learn.microsoft.com/en-us/visualstudio/ide/reference/build-devenv-exe?view=vs-2022), requires a solution file. The `/project` switch can be provided to specify a project within the solution. MSBuild doesn't work like that.

MSBuild can be given a solution file (in which case it synthesizes a meta project from the solution) or it can be given a project file. You cannot give MSBuild a solution file and a project within the solution file.

But you can give MSBuild a solution file and specify a target scoped to a project within the project file.

```
msbuild  .\my.sln /t:myproject:build ...
```

As @KalleOlaviNiemitalo stated see "[Build specific targets in solutions](https://learn.microsoft.com/en-us/visualstudio/msbuild/how-to-build-specific-targets-in-solutions-by-using-msbuild-exe?view=vs-2022)".

**Comment by snikeguo** [comment]
> Actually it's documented at https://learn.microsoft.com/en-us/visualstudio/msbuild/how-to-build-specific-targets-in-solutions-by-using-msbuild-exe?view=vs-2022

TKS,I solved the problem!
