### ISSUE TITLE
[Bug]: ResolveAssemblyReferences does not generate necessary binding redirect for PackageReference conflict

### ISSUE THREAD

**Issue by mvanhilst-msft** [dotnet/msbuild#8886]
### Issue Description

In a simple scenario where a project depends on two projects that, in turn, depend on conflicting versions of a NuGet package, no binding redirect is generated in the first project's output directory.

### Steps to Reproduce

https://github.com/mvanhilst-msft/ResolveAssemblyReferences-Bug

     Project C (Console App)
      |
      +-[ProjectReference]-> Project A (Class Library)
      |                       |
      |                       +-[PackageReference]-> Microsoft.Diagnostics.Tracing.EventSource 1.1.28
      |                       |                       |
      |                       |                       +-[dependency]-> Microsoft.Diagnostics.Tracing.EventSource.Redist 1.1.28
      |                       |                                                 /|\
      |                       |                                             [comes from]
      |                       |                                                  |
      |                       +-[code reference]-> Microsoft.Diagnostics.Tracing.EventSource.dll 1.1.28.0
      |
      +-[ProjectReference]-> Project B (Class Library)
                              |
                              +-[PackageReference]-> Microsoft.Diagnostics.Tracing.EventSource.Redist 2.2.0
                              |                                         /|\
                              |                                     [comes from]
                              |                                          |
                              +-[code reference]-> Microsoft.Diagnostics.Tracing.EventSource.dll 2.0.3.0
                              
Project A and B each have a simple Hello World example program using Microsoft.Diagnostics.Tracing.EventSource. Project C invokes the code from A and B.

### Expected Behavior

No runtime errors.

### Actual Behavior

    Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'Microsoft.Diagnostics.Tracing.EventSource, Version=1.1.28.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
       at ProjectA.ClassA.DoThing()
       at ProjectC.Program.Main(String[] args) in C:\repos\misc\ResolveAssemblyReferences-Bug\ResolveAssemblyReferencesBug\ProjectC\Program.cs:line 10

### Analysis

I checked the following things:

The NuGet package metadata appears correct for the packages involved.

ResolveAssemblyReferences does detect the conflict:

    There was a conflict between "Microsoft.Diagnostics.Tracing.EventSource, Version=2.0.3.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51" and "Microsoft.Diagnostics.Tracing.EventSource, Version=1.1.28.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a".

GenerateBindingRedirects says ResolveAssemblyReferences did not suggest any binding redirects:

    Task "GenerateBindingRedirects" (TaskId:87)
      Task Parameter:OutputAppConfigFile=obj\Debug\ProjectC.exe.config (TaskId:87)
      Task Parameter:AppConfigFile=App.config
                      OriginalItemSpec=App.config
                      TargetPath=ProjectC.exe.config (TaskId:87)
      Task Parameter:TargetName=ProjectC.exe.config (TaskId:87)
      No suggested binding redirects from ResolveAssemblyReferences. (TaskId:87)
    Done executing task "GenerateBindingRedirects". (TaskId:87)

The output directory of ProjectC contains `Microsoft.Diagnostics.Tracing.EventSource, Version=2.0.3.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51`.

### Versions & Configurations

Microsoft Visual Studio Enterprise 2022 (64-bit) - Current
Version 17.6.3

MSBuild version 17.6.3+07e294721 for .NET Framework
17.6.3.22601

**Comment by mvanhilst-msft** [comment]
Is it related that the `PublicKeyToken` is different between `1.1.28.0` and `2.0.3.0`?

**Comment by mvanhilst-msft** [comment]
Closing for now as it is by design and it appears there is no solution other than to avoid taking a dependency on 2.0.0+ of `Microsoft.Diagnostics.Tracing.EventSource`.

**Comment by rainersigwald** [comment]
Yeah, I'm afraid having different `PublicKeyToken`s means .NET Framework doesn't have any way to create binding redirects, so that kind of breaking change is quite difficult to deal with in a diamond dependency situation.

The only other option (beyond "avoid the conflict") is to move one version to a subfolder and have a custom [`AssemblyResolve`](https://learn.microsoft.com/dotnet/api/system.appdomain.assemblyresolve?view=netframework-4.8) handler that can locate it--and that can result in confusing conflicts because they will both be loaded in the same process.

cc @AR-May
