### ISSUE TITLE
[Bug]: TerminalLogger throws ArgumentOutOfRangeException when terminal size is indeterminate (guess)

### ISSUE THREAD

**Issue by TheArcaneBrony** [dotnet/msbuild#8913]
### Issue Description

TerminalLogger does not handle indeterminate terminal resolutions, eg. when running headless.

If I had to take a guess as to what's happening, terminal size probably returns <null>x<null>, which causes MSBuild to use `default(int)`, which is 0.

### Steps to Reproduce

NOTE: These build steps use JetBrains Rider as an example, this can probably be reproduced with other methods of having a terminal without width/height
- Set `MSBUILDLIVELOGGER` envvar to true, eg. `export MSBUILDLIVELOGGER=true` or `MSBUILDLIVELOGGER=true $command`
- Launch Rider
- Create or open project (any .net version)
- See all projects fail to load

### Expected Behavior

Handle terminal size at the standard terminal size of 80x24 when unable to determine terminal size (eg. headless), infinite width or fall back to legacy implementation.

### Actual Behavior

MSBuild version 17.7.0-preview-23281-03+4ce2ff1f8 for .NET
[?25l[1F
Unhandled exception. System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
   at Microsoft.Build.Logging.LiveLogger.LiveLogger.NodesFrame.Render(NodesFrame previousFrame)
   at Microsoft.Build.Logging.LiveLogger.LiveLogger.DisplayNodes()
   at Microsoft.Build.Logging.LiveLogger.LiveLogger.ThreadProc()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
[?25h

### Versions & Configurations

.NET SDK: 8.0.100-preview.5.23303.2 [/usr/share/dotnet/sdk]
OS: Arch Linux x86_64

**Comment by rainersigwald** [comment]
Thanks for the report! This should be fixed by #8733, but you can work around now by setting `MSBUILDLIVELOGGER=auto` instead of `true`--in that case we should fall back to the old logger when detecting output redirection.

**Comment by AR-May** [comment]
Team triage: closing this issue given that the fix is merged. Please feel free to reopen if you still see this issue.
