### ISSUE TITLE
[Bug]: Visual Studio keeps saying push to remote repo failed, even when it didn't

### ISSUE THREAD

**Issue by FelBenini** [dotnet/msbuild#8957]
### Issue Description

Well, the title says it all, when I commit and push to a remote repository it gives me an error message

![Error message](https://i.imgur.com/67dUSCU.png)

- first message: 'Commit created logically'
- second message: 'Failed to push to remote repository. See the exit window for more information'

## But in reality, the push was successful

![Commits on the repository](https://i.imgur.com/gbSaEUP.png)

### Steps to Reproduce

- Create a commit
- Push it to a private remote repository on GitHub using the git tab.

### Expected Behavior

Expected behavior was to give me a message that the push was successful.

### Actual Behavior

It succesfully push to the remote repository, but it says it wasn't successful

**Comment by rainersigwald** [comment]
Team Triage: We believe this is an issue with Visual Studio, not MSBuild. Can you [open a feedback ticket instead](https://docs.microsoft.com/visualstudio/ide/feedback-options)?

After it's created, that will open an internal bug which will be routed to the right team. If you post the link here we may be able to help that process go faster.

**Comment by FelBenini** [comment]
> Team Triage: We believe this is an issue with Visual Studio, not MSBuild. Can you [open a feedback ticket instead](https://docs.microsoft.com/visualstudio/ide/feedback-options)?
> 
> After it's created, that will open an internal bug which will be routed to the right team. If you post the link here we may be able to help that process go faster.

Just did that, @rainersigwald ! hope I done it right, here is the link
https://developercommunity.visualstudio.com/t/Visual-Studio-keeps-saying-push-to-remot/10400803

**Comment by rainersigwald** [comment]
Looks good to me; I'll let the version control folks take a look at it. Thanks.
