### ISSUE TITLE
[Feature Request]: Expose the getters of the `SolutionFile.FullName` and `SolutionFile.SolutionFileDirectory` properties

### ISSUE THREAD

**Issue by astrohart** [dotnet/msbuild#8963]
### Summary

In the `SolutionFile` class, the `FullName` and `SolutionFileDirectory` properties -- which I can see in ILDASM/ILSpy for the `Microsoft.Build` NuGet package -- are marked `internal`.  Nor are they documented on Microsoft Learn.  I do not think this is a good thing.

Typically, my experience has been in the past, that when you write a class that parses a file and then exposes the data model of the file, callers of the class should be able to have access to a property(ies) that reveal the fully-qualified pathname on the disk of the file that was parsed to give that object.

When I am working with the `SolutionFile` class, I would like to be able to read these properties as get-only -- obviously, it would not make sense to write to them. 

My point is, to make production-ready code, as I am passing a `SolutionFile` instance around, I want to ensure every so often that the `.sln` file still exists on the disk, since, in principle, to write bulletproof code, I cannot continue to make that assumption as I proceed with my program.

Thank you for your consideration.

### Background and Motivation

I am tasked with writing production-ready software.  A best practice is "never assume files on disk always exist in the same spot."  In my code, as I utilize the `SolutionFile` instance, I would like to be able to implement a check for the existence of the `.sln` or `.slnf` file that was parsed to yield the instance in the first place, to ensure that I am not working with the data of a file on the disk that no longer exists.

### Proposed Feature

Instead of

```C#
public sealed class SolutionFile
{
  /* ... */
  
  internal string FullPath
  {
    get
    {
      return _solutionFile;
    }
    set
    {
      ErrorUtilities.VerifyThrowInternalRooted(value);
      if (value.EndsWith(".slnf", StringComparison.OrdinalIgnoreCase))
      {
        ParseSolutionFilter(value);
        return;
      }
      _solutionFile = value;
      _solutionFilter = null;
      SolutionFileDirectory = Path.GetDirectoryName(_solutionFile);
    }
  }
  
  internal string SolutionFileDirectory { get; set; }

  /* ... */
}
```
Make the `FullName` and `SolutionFileDirectory` properties of the `SolutionFile` class `public`, with their setters made `internal`.
### Alternative Designs

Make the `FullName` and `SolutionFileDirectory` properties of the `SolutionFile` class `public`, with their setters made `internal`.

**Comment by astrohart** [comment]
10:59 06/27/2023

I have forked and cloned the repo and I am going to implement my proposed feature request and then submit a PR.

**Comment by rainersigwald** [comment]
The `SolutionFile` class is not intended for use outside of MSBuild. It is not a full-featured handler for the `.sln` file format and should not be used as such.

We need to document this more clearly--we didn't add sufficient caveats when it was made public.

**Comment by jrdodds** [comment]
Is there a full-featured parser for the .sln file format that is publicly available?

(It seems like `SolutionFile` is the closest thing to that (or maybe just the easiest to find), which leads to it being used when it isn't appropriate.)

**Comment by rainersigwald** [comment]
> Is there a full-featured parser for the .sln file format that is publicly available?

Not from the Visual Studio team. I know they've been asked for one before (because I've asked them several times) but I couldn't dig up a good tracking issue, so I'd recommend filing a request through VS Feedback.

**Comment by jrdodds** [comment]
I created a Visual Studio feedback issue: [Library for Solution (.sln) files](https://developercommunity.visualstudio.com/t/Library-for-Solution-sln-files/10401851).

**Comment by Forgind** [comment]
I voted for your issue 🙂

**Comment by jrdodds** [comment]
@danmoseley If there is an initiative to build out a common solution parser, I would be interested in contributing.

**Comment by astrohart** [comment]
> @danmoseley If there is an initiative to build out a common solution parser, I would be interested in contributing.

Heck yeah.  Just to use this one class, which I think of is a great solution parser, I have to bring the entire [Microsoft.Build NuGet package](https://www.nuget.org/packages/Microsoft.Build/) into my project.  I might not want all the other stuff.

I strongly suggest the creation of a `Microsoft.Build.Construction` NuGet package with just the `.sln`-parsing code.

**Comment by danmoseley** [comment]
> I have to bring the entire Microsoft.Build NuGet package into my project. I might not want all the other stuff.

You could of course paste in the relevant code or put it in its own git repo for others to use - it's liberally licensed and should be fairly easily extracted.

**Comment by astrohart** [comment]
@jrdodds I upvoted your feedback and left some comments on it

**Comment by astrohart** [comment]
@rainersigwald @danmoseley what about my original PR? #8965 I respectfully request it be merged.  As I have stated on its discussion thread, it is my assessment that it would add value to the `SolutionFile` class for those who consume it in their own projects.  A use case for which I have found it useful is opening up [LINQPad](https://www.linqpad.net) and using it to manipulate my really large software projects without havingto resort to always loading Visual Studio and waiting for umpteen projects to be loaded, but instead just writing a script.

**Comment by danmoseley** [comment]
What I believe would be ideal is someone takes this code and evolves it in its own repo/package as you suggest. If it maintained a slim read only version with essentially the same API as this one and was appropriately licensed, MSBuild could potentially take updates from it (likely copy paste). Meanwhile it makes sense to me to take limited changes like this PR that expose simple getters. This is mature code.

I don't speak for this project.

**Comment by astrohart** [comment]
I am still revisiting this and asking thatt my PR be merged.  I don't understand what the heck is behind the stiff resistance to including these seemingly innocuous changes and why we have to have a religious debate over it.  These are perfectly-reasonable changes.   People have said "oh well this class is not intended to be widely available."  Well, that doesn't matter --- it's out there, it's in a NuGet package and people can update its code and submit PRs, so I think it is out there and while we are at it, what's the hurt in exposing the `FileName` property as `public`?  None, IMHO.

**Comment by danmoseley** [comment]
> a) I don't want people to think I'm appropriating Microsoft's intellectual property, 

This repo is liberally licensed.

> (b) my own NuGet package would just merely be Yet Another Solution File Parser. Microsoft taking action on its side would make the new package more "official," IMHO.

The .NET ecosystem does sometimes tend to assume that Microsoft has to produce a library for it to be acceptable. Many times this comes up for parsers for some reason. That's limiting in a way that doesn't seem to happen in the Java ecosystem.

(The above being said, I do believe MSBuild should expose basic read only access, as I said above.)

@rainersigwald

**Comment by astrohart** [comment]
> Since it is not the solution parser that is used by the primary environment that uses solutions--Visual Studio--so is ours.
> Why choose it?

Because it was handy for a LINQPad script.

**Comment by astrohart** [comment]
I could not disagree more with the maintainers.  But what can you do?

**Comment by astrohart** [comment]
> > a) I don't want people to think I'm appropriating Microsoft's intellectual property,
> 
> This repo is liberally licensed.

That's not the point.  The point is, the `Microsoft.` in front of the package name, to my mind, means it came from the same people (Microsoft; i.e., the "brand") as who came up with the `.sln` file format itself.   This means I can trust it that it will properly parse the `.sln` file format, which is Microsoft-invented.

> 
> (The above being said, I do believe MSBuild should expose basic read only access, as I said above.)
> 
> @rainersigwald

I could not agree more @danmoseley.   I really have no idea WTH all this animosity is toward me and my tiny teeny weeny change suggestion!!!

> 
> > (b) my own NuGet package would just merely be Yet Another Solution File Parser. Microsoft taking action on its side would make the new package more "official," IMHO.
> 
> The .NET ecosystem does sometimes tend to assume that Microsoft has to produce a library for it to be acceptable. Many times this comes up for parsers for some reason. That's limiting in a way that doesn't seem to happen in the Java ecosystem.

Well, I just had the idea to break the Solution Parser piece only into a separate `Microsoft.Build.Construction` package so I can drop it in a LINQPad script I am using to go over the `.sln` files in my source code repos directories to do mass file operations on them according to rules about their contents --- without having to drag the entire `Microsoft.Build` ecosystem into my little LINQPad script.

**Comment by danmoseley** [comment]
> my own NuGet package would just merely be Yet Another Solution File Parser. Microsoft taking action on its side would make the new package more "official," IMHO.

One thought about this - of someone wanted to try to coalesce the community around a single solution parser and position it as more than an ad hoc project, they could consider nominating it to be in the .NET foundation, ie become dotnet/solutionparser or something. This costs nothing and can help broaden maintainers as well.
