### ISSUE TITLE
[Bug]: dotnet msbuild unable to build DSL project?

### ISSUE THREAD

**Issue by youn123** [dotnet/msbuild#8964]
### Issue Description

When trying to build a domain-specific language project with dotnet msbuild, I get the following error:

C:\Users\yobae\source\repos\Language1\Dsl\Dsl.csproj(4,3): error MSB4019: The imported project "C:\Program Files\dotnet\sdk\7.0.300-preview.23179.2\Microsoft\Visu
alStudio\v17.0\DSLTools\Microsoft.DslTools.settings.targets" was not found. Confirm that the expression in the Import declaration "C:\Program Files\dotnet\sdk\7.0
.300-preview.23179.2\\Microsoft\VisualStudio\v17.0\DSLTools\Microsoft.DslTools.settings.targets" is correct, and that the file exists on disk.

### Steps to Reproduce

1. Create a minimal DSL project using Visual Studio Domain-Specific Language Designer project template.
2. Open VS developer command prompt. Navigate to project directory and try to build:

```
dotnet msbuild /t:restore dsl.csproj
dotnet msbuild dsl.csproj
```

### Expected Behavior

The project should build successfully.

### Actual Behavior

Project build fails.

### Analysis

Seems like dotnet msbuild is missing DSL-related targets file.

**Comment by AR-May** [comment]
Team triage: The #8967 would track the issue better. Closing this issue.
