### ISSUE TITLE
[Feature Request]: Way to turn on server garbage collection without editing config file

### ISSUE THREAD

**Issue by youn123** [dotnet/msbuild#8966]
### Summary

Would like some way of turning on server GC without having to edit msbuild.exe.config under Program Files.

### Background and Motivation

For machines with a lot of memory, server GC seems to significantly improve processor utilization and reduce static graph load time (by at least half based on cursory analysis).

There is an environment variable `DOTNET_gcServer` that allows turning on server GC without editing app config files, but this only controls behavior of .NET Core. MSBuild on the VS developer command prompt is .NET Framework. Currently the only way to turn on server GC for MSBuild is editing its config file under Program Files, which we would like to avoid doing.

### Proposed Feature

Don't have specific suggestions. Maybe an MSBuild-specific environment variable? It may or may not be more apt to open an issue with .NET team. Starting here since we're really particularly interested in server GC for msbuild.

**Comment by youn123** [comment]
There is a `COMPLUS_gcServer`, but I believe this is also only recognized by .NET Core according to the docs here: https://learn.microsoft.com/en-us/dotnet/core/runtime-config/garbage-collector

**Comment by rainersigwald** [comment]
Yeah I don't think this configuration is possible within the runtime.

**Comment by AR-May** [comment]
Team triage: closing this issue.
