### ISSUE TITLE
[Performance]: Glob expansion inside targets is missing important Exclude optimization

### ISSUE THREAD

**Issue by ladipro** [dotnet/msbuild#8984]
### Issue Description

When glob expansion runs in a target via `ItemGroupIntrinsicTask`, it separately enumerates includes and excludes, then does the subtraction of their results. This may be prohibitively slow when excludes refer to large subdirectories.

### Steps to Reproduce

```xml
<Project>
  <Target Name="Build">
    <ItemGroup>
      <MyResources Include="**\*.png;**\*.jpg" Exclude="bin\**\*.*;obj\**\*.*" />
    </ItemGroup>
    <Message Text="MyResources.Count: @(MyResources->Count())" />
  </Target>
</Project>
```

When evaluating the glob, there is no need to recurse into `bin` or `obj` at all. MSBuild can simply skip these directories when it enumerates all `.png` and `.jpg` files.

### Data

An internal project is seeing >10 minutes spent running the `ItemGroupIntrinsicTask` due to this issue.

### Analysis

These are the problematic calls: https://github.com/dotnet/msbuild/blob/39e20dce0c00a572f1fbd20a0a520d4e941bbc33/src/Build/BackEnd/Components/RequestBuilder/IntrinsicTasks/ItemGroupIntrinsicTask.cs#L469-L481

### Regression

- [ ] yes
- [X] no

**Comment by AR-May** [comment]
>When evaluating the glob, there is no need to recurse into bin or obj at all.

Is that so? `Bin` folder - possibly, but I am unsure about `obj`. I wonder if this could be a breaking change.

**Comment by ladipro** [comment]
> > When evaluating the glob, there is no need to recurse into bin or obj at all.
> 
> Is that so? `Bin` folder - possibly, but I am unsure about `obj`. I wonder if this could be a breaking change.

The `bin` and `obj` here refers to the specific example in Steps to Reproduce. Fixing this perf issue is not expected to change anything functionally.
