### ISSUE TITLE
[Broken Build]: My CsProj file has errors when building in one Sln file, but not in another Sln file

### ISSUE THREAD

**Issue by EdLichtman** [dotnet/msbuild#8997]
### Issue Description

When I build in a master solution that contains every project in our platform, all of the CSProj files compile with some warnings.

When I build in an alternate, minimal Nant solution, I see tons of errors, suggesting that I haven't imported library references, that I clearly have. For instance, we have a logging library with ILogWriter, and it tells me that I haven't pulled in any library that contains ILogWriter.

Keep in mind, once again, when I build it in the Master Solution, it runs. So it's not that the Logging Library hasn't been built for the proper TargetFramework.

### Steps to Reproduce

I cannot publicly produce a minimal step, but if you look at my notes below, It explains my starting point question, and from there I can try to provide what I can.

### Expected Behavior

I expect my csproj file to build regardless of what Sln file I'm building.

### Actual Behavior

I cannot compile my environment because our nant solution specifically will not compile, due to a project that the nant solution is dependent upon that doesn't build only in the nant solution.

### Ask us questions

I've tracked it down though to the following:
In Master Solution, the MsBuildRuntimeType is "Full". In the Nant solution, the MsBuildRuntimeType is "Core".

the "Full" type uses:
MSBuildExtensionsPath = C:\Program Files\Microsoft Visual Studio\2022\Professional\MSBuild

The "Core" type uses: 
MSBuildExtensionsPath = C:\Program Files\dotnet\sdk\7.0.203

In many projects we use the following Attribute:
<Import Project="$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props" Condition="Exists('$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props')" />

However, in BOTH versions, it looks like MsBuildToolsVersion is no longer set. It seems to me that this attribute is obsolete, and "$(MsBuildToolsVersion)" can be replaced with "Current", however doing so does not fix it.

How does the Build system know whether to use Core or Full? Why is it using Full for a project in one solution, and Core for that same project in another solution? How do I begin fixing this?

**Comment by jrdodds** [comment]
Is the "master solution" a [Solution (.sln) file](https://learn.microsoft.com/en-us/visualstudio/extensibility/internals/solution-dot-sln-file?view=vs-2022)?

Is the "alternate, minimal Nant solution" also a [Solution (.sln) file](https://learn.microsoft.com/en-us/visualstudio/extensibility/internals/solution-dot-sln-file?view=vs-2022)? Or it is a [NAnt ](https://github.com/nant/nant)file?

In the project files (.csproj), what is `TargetFrameworkVersion` set to?

I'm guessing that the "Nant solution" is a NAnt XML file and that NAnt is finding and loading the wrong MSBuild.

Note that NAnt only supports .Net Framework up to v4.0 and the 'current' release of NAnt is from 2012.

**Comment by EdLichtman** [comment]
The nant solution is OurCompany.NantExtensions.csproj, so we build our own tasks for extending Nant. However, there was a problem loading it that seems to be a Nant issue, and I think I correlated it with a rider issue in which Rider was automatically choosing the dotnet sdk MSBuild instead of the Visual Studio MsBuild. I can close this since it was actually an issue in Rider.
