### ISSUE TITLE
[Broken Build]: MSBuild should be able to recognize older runtimes' existence doesn't preclude newer runtimes' existence

### ISSUE THREAD

**Issue by Forgind** [dotnet/msbuild#8998]
### Issue Description

I was working on an older branch, and as part of running build.cmd, it put the 7.0.5 runtime in my `.dotnet\shared\Microsoft.NETCore.App` folder. Then I updated to a newer version, and I got this:

![image](https://github.com/dotnet/msbuild/assets/12969783/2eb6cd01-6941-4d91-928c-3ed0795e280b)

In reality, I have both the 7.0.8 and and the 8.0 runtime installed. The problem here was just that it didn't realize that.

Deleting the .dotnet folder and running build.cmd again resolved the issue, and I could build successfully.

...but it would be good to not make me do that 🙂

### Steps to Reproduce

Clean repo. Build an old branch. Switch to main and build again.

### Expected Behavior

Success after it downloads/finds a new 7.0.7 runtime

### Actual Behavior

Failure (see picture above)

**Comment by AR-May** [comment]
Team triage: we think this does not meet the bar. If you would want to get tis fixed, engineering services could help with it.
