### ISSUE TITLE
[Bug]: Cannot stop recursive invocation of MSBuild with Ctrl-C.

### ISSUE THREAD

**Issue by teo-tsirpanis** [dotnet/msbuild#8999]
### Issue Description

We have a C++ codebase that uses CMake in a "superbuild" architecture, where an outer CMake project downloads our third-party dependencies, and the inner project contains our own code and is built afterwards.

The problem is that when I build the outer project, I cannot make it immediately stop via Ctrl-C and I have to kill it from the Task Manager. This hinders my development workflow.

### Steps to Reproduce

* Clone https://github.com/TileDB-Inc/TileDB and open a PowerShell into it.
* `mkdir build && cd build`
* Run `../bootstrap.ps1` (should not take long)
* Run `cmake --build . --config Release` and wait a couple of seconds before the next step.
* Try to cancel the build with Ctrl-C.

### Expected Behavior

The build stops.

### Actual Behavior

The build does not stop. Immediately after pressing Ctrl-C I get an `Attempting to cancel the build...` message.

After some time I getting a `C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(248,5): warning MSB4220: Waiting for the currently executing task "CustomBuild" to cancel. [C:\Users\teo\code\TileDB\build\ep_magic.vcxproj]`. The build will stop after the currently-building component of the outer project finishes (in this case it was a dependency, but in most cases when the main project gets built, the build is effectively uncancellable).

### Analysis

I don't think this is a problem of CMake because I can cancel the outer build on Unix with Makefiles. It seems that MSBuild struggles to kill the inner build.

Directly building the inner project can be cancelled without any problem.

### Versions & Configurations

MSBuild version 17.6.3.22601
CMake version 3.26.0-msvc3

**Comment by JanKrivanek** [comment]
Might be related? https://github.com/dotnet/sdk/issues/33417

**Comment by JaynieBai** [comment]
[msbuild.binlog.txt](https://github.com/dotnet/msbuild/files/12170513/msbuild.binlog.txt)
From the log, we can see cancelation is stuck in the task CostomBuild which is CppCommon task.  I think we need to ask cpp team if this task is cancelable task. 
![image](https://github.com/dotnet/msbuild/assets/26814373/e449ae11-7c4d-46c9-85e3-803ac18d250a)

**Comment by MichalPavlik** [comment]
@teo-tsirpanis, could you please create a VS community ticket for this issue? It could be then transferred to C++ team as they own this task. It may be solved by adding cancellation support in the task itself (MSBuild supports cancellable tasks). In the meantime, you can force stop the build immediately via Ctrl-Break combination. I'm closing this issue, but don't hesitate to reopen it in case you need more help.

**Comment by teo-tsirpanis** [comment]
Opened https://developercommunity.visualstudio.com/t/CustomBuild-MSBuild-task-has-trouble-can/10450821.
