### ISSUE TITLE
[Broken Build]: Manually copied DLL to output directory not copied to depdendent project

### ISSUE THREAD

**Issue by drauch** [dotnet/msbuild#9009]
### Issue Description

I manually copy a DLL from a NuGet package to the output directory in project A:

```
<Target Name="CopyNewestDllsToOutput" BeforeTargets="Build">
  <Copy SourceFiles="$(PkgMyPackage)\x64\My.dll" DestinationFolder="$(OutputPath)\Implementation" />
</Target>
```

Project B depends on project A, however, it does not receive this DLL as part of the output. How to fix  this?

Best regards,
D.R.

### Steps to Reproduce

-

### Expected Behavior

-

### Actual Behavior

-

### Ask us questions

-

**Comment by JanKrivanek** [comment]
@drauch Can you describe why expressing the dependency of A on the package via [`PackageReference`](https://learn.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files) isn't viable in your scenario?

**Comment by drauch** [comment]
Actually we _do_ reference it via PackageReference (which is why we have the PkgMyPackage variable available). It is, however, not a "real" NuGet package and we need some native DLL inside this "arbitrary Zip-Package in NuGet package disguise".

**Comment by JanKrivanek** [comment]
Do you own or have any power ower the build of the package? Ideally it'd add the native binary as a runtime specific asset: https://learn.microsoft.com/en-us/nuget/create-packages/supporting-multiple-target-frameworks#architecture-specific-folders

Alternatively add it as [`NativeReference`](https://learn.microsoft.com/en-us/visualstudio/msbuild/common-msbuild-project-items#nativereference) item or [`None`](https://learn.microsoft.com/en-us/visualstudio/msbuild/common-msbuild-project-items#none). e.g.: `<None Include="$(PkgMyPackage)\x64\My.dll" CopyToOutputDirectory="PreserveNewest">`

**Comment by drauch** [comment]
Thank you for your time.

If I add:
```
<ItemGroup>
    <None Include="$(PkgMyPackage)\x64\My.dll" CopyToOutputDirectory="PreserveNewest" />
</ItemGroup>
```
to project A it works in project A, however, when building project B it complains that:

> MSB3030	Could not copy the file "C:\x64\My.dll" because it was not found.

It looks like the None-element is somehow re-evaluated in the context of project B where the `PkgMyPackage` variable doesn't exist. Any ideas on this?

Best regards,
D.R.

**Comment by JanKrivanek** [comment]
Is the package in question public? If so - which one is it?
If not - are you/your company producing it? Then I'd first suggest making sure that it's build/packed properly - so that ordinary PackageReference can be used.

**Comment by drauch** [comment]
> Then I'd first suggest making sure that it's build/packed properly - so that ordinary PackageReference can be used.

Unfortunately, this is not going to happen :-/ I've worked around it by referencing the NuGet package in project A and project B (even though it should not be necessary in project B). Then the None-ItemGroup from above works as the `$(PkgMyPackage)` variable exists in both projects.

If anybody has a better solution I'll gladly accept it :-) For now: thanks @JanKrivanek for helping me out!

Best regards,
D.R.

**Comment by drauch** [comment]
I've found a better solution thanks to a colleague of mine:

```
  <Content Include="$(PkgMyPackage)\x64\My.dll" CopyToOutputDirectory="PreserveNewest" />
```

This makes it work in all dependent projects as well and does not require me to reference the NuGet package in all projects again.

Best regards,
D.R.
