### ISSUE TITLE
[Bug]: NullReferenceException in BuildManager.OnLoggingThreadException

### ISSUE THREAD

**Issue by GeertvanHorrik** [dotnet/msbuild#9014]
### Issue Description

Often after an update of Visual Studio, we get a lot of failed builds with this stack trace:

```
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Build.Execution.BuildManager.OnLoggingThreadException(Exception e)
   at Microsoft.Build.BackEnd.Logging.LoggingService.RaiseLoggingExceptionEvent(Exception ex)
   at Microsoft.Build.BackEnd.Logging.LoggingService.LoggingEventProcessor(Object loggingEvent)
   at Microsoft.Build.BackEnd.Logging.LoggingService.<StartLoggingEventProcessing>g__LoggingEventProc|135_0()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
An error occurred when executing task 'Build'.
Error: Unexpected end of file while parsing Name has occurred. Line 1, position 45.
```

For our convenience, we enable binary, file and xml logging during CI builds. Probably the combination of these steps causes the issue. I've deployed a fix to disable both binary and file logger (only keeping xml) and that seems to work. I am now running test builds where both binary and xml are enabled.

We use `dotnet msbuild`.

### Steps to Reproduce

Hard to repro, it does not happen all the time, but *mostly* after Patch Tuesday when Visual Studio gets updated. Sometimes repairing works, but sometimes it doesn't. Tried restarting the build agents, etc, nothing helped (this time).

### Expected Behavior

I would not expect a NullReferenceException in the BuildManager

### Actual Behavior

```
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Build.Execution.BuildManager.OnLoggingThreadException(Exception e)
   at Microsoft.Build.BackEnd.Logging.LoggingService.RaiseLoggingExceptionEvent(Exception ex)
   at Microsoft.Build.BackEnd.Logging.LoggingService.LoggingEventProcessor(Object loggingEvent)
   at Microsoft.Build.BackEnd.Logging.LoggingService.<StartLoggingEventProcessing>g__LoggingEventProc|135_0()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
An error occurred when executing task 'Build'.
Error: Unexpected end of file while parsing Name has occurred. Line 1, position 45.
```

### Analysis

Could it be related to having multiple build logging (binary, file and xml) enabled at the same time?

I did a quick analysis of the code, and technically the work queue could be null here:

https://github.com/dotnet/msbuild/blob/main/src/Build/BackEnd/BuildManager/BuildManager.cs#L2773

`InitializeLoggingService` is called (where event subscription takes place) *before* `_workQueue` gets assigned. (see https://github.com/dotnet/msbuild/blob/main/src/Build/BackEnd/BuildManager/BuildManager.cs#L564) 

### Versions & Configurations

msbuild --version:

MSBuild version 17.6.3+07e294721 for .NET Framework
17.6.3.22601

dotnet msbuild --version

MSBuild version 17.6.8+c70978d4d for .NET
17.6.8.32104

**Comment by GeertvanHorrik** [comment]
I use Cake to add this, here is the exact line:

https://github.com/GeertvanHorrik/RepositoryTemplate/blob/master/deployment/cake/lib-msbuild.cake#L236C1-L238C1

XmlLogger comes from MSBuild.ExtensionPack.Loggers (1.9.1).

**Comment by GangWang01** [comment]
It’s hard to repro.

[MSBuild.Extension.Pack 1.9.1](https://www.nuget.org/packages/MSBuild.Extension.Pack/1.9.1#supportedframeworks-body-tab) has only .NET Framework version. With dotnet msbuild using the this XML logger, the error below occurred.
```
MSBuild version 17.7.0-preview-23281-03+4ce2ff1f8 for .NET
MSBUILD : error MSB1021: Cannot create an instance of the logger. Could not load file or assembly 'Microsoft.Build.Utilities.v4.0, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
```

So I tried to reproduce with msbuild using Developer Command Prompt for VS 2022. Here are the detailed steps.
1. Install a lower version of VS.
2. Use Developer Command Prompt to build a ASP.NET Core Web App application. Restore the solution. Then build with multiple loggers `msbuild -bl:LogFromBinaryLogger.binlog -fl -flp:logfile=LogFromFileLogger.log;verbosity=diagnostic -logger:XmlFileLogger,C:\Users\<username>\.nuget\packages\msbuild.extension.pack\1.9.1\tools\net40\MSBuild.ExtensionPack.Loggers.dll;logfile=LogFromXMLLogger.xml;verbosity=Detailed;encoding=UTF-8`.
3. Update VS to latest.
4. Repeat step 2.

I tried many times. Unfortunately I couldn't reproduce this issue.

**Comment by GeertvanHorrik** [comment]
Thanks for putting in the effort to reproduce this (complex threading) issue. It is indeed very hard to reproduce this issue. I tried "playing" with the settings, and it *could* be related to the file logger. Once I disabled that one, it started working again (but again: it doesn't happen all the time, but mostly after a VS update).

I think there is an issue related to the field not being initialized. Maybe instead of having this `NullReferenceException`, you could use something like this:

```
var workQueue = _workQueue;
if (workQueue is null)
{
    // todo: log extended error or create a valid exception
}

workQueue.Post(...);
```

At least it could provide us with more information in the future that could eventually help solve this issue.

It could even be unit tested by manually calling OnThreadException without the queue being initialized (method should be made internal for this).

**Comment by GangWang01** [comment]
@GeertvanHorrik can you provide the binary log file(*.binlog) when this issue happened from CI build? The binary log has valuable information to help us understand this issue. In addition, the error at the last line `Error: Unexpected end of file while parsing Name has occurred. Line 1, position 45.` might be related.

**Comment by GeertvanHorrik** [comment]
I have not yet been able to reproduce this. I was "hoping" it would occur after last patch Tuesday. Will still put it here whenever it occurs again.

**Comment by GeertvanHorrik** [comment]
I have not yet been able to reproduce this. I was "hoping" it would occur after last patch Tuesday. Will still put it here whenever it occurs again.

**Comment by GangWang01** [comment]
Feel free to re-open when it happens again and provide the helpful binary log file(*.binlog) for investigation.

**Comment by GeertvanHorrik** [comment]
Today it happened again. So I immediately went to check if I could fetch the binlog. From the approx. 21 projects, 1 failed. All of the projects have .log (mostly empty, contains only warnings and errors), .xml and binlog.

The failed project unfortunately has:

1. Empty binlog file
2. Empty log file
3. Nearly empty xml file:

```
<?xml version="1.0" encoding="utf-8"?>
<build
```

Maybe this can give us some pointers about the cause?

**Comment by nicksuh** [comment]
Hi, This happens to our project also. any updates? Can't figure out how to fix it.
