### ISSUE TITLE
[BinFmt] Facilitate proper documentation of Custom BuildEventArgs deprecation and replacement

### ISSUE THREAD

**Issue by JanKrivanek** [dotnet/msbuild#9016]
https://github.com/dotnet/msbuild/pull/8917#discussion_r1258448613

### Background 
 #6215
 This subitem is focused on making sure that https://aka.ms/msbuild/eventargs / https://learn.microsoft.com/en-us/dotnet/api/microsoft.build.framework.custombuildeventargs contains information about `CustomBuildEventArgs` deprecation, reasoning, suggested replacements and possibly planned timelines (for Core and for FullFw)

### Suggested approach
Put together the required information (based on https://github.com/dotnet/msbuild/pull/8917), create documentation bug https://github.com/dotnet/docs/issues and cooperate with @ghogen on apropriate planning and execution or directly create proposal PR in the doc repo [internal] https://github.com/MicrosoftDocs/visualstudio-docs-pr

**Comment by JanKrivanek** [comment]
https://github.com/dotnet/docs/issues/36403

**Comment by JanKrivanek** [comment]
@KalleOlaviNiemitalo Forward compatibility will not be guaranteed here. Assemblies should be compiled against the oldest MSBuild they intend to support.
For Full Framework the build warnings are explicit opt-in - so it shouldn't cause unexpected degradations.
For Core we haven't detected any usage of concerns internaly or in the wild - so hopefully this should be 'just fine'. There still will be an option to override the warning/error/crashing behavior temporarily before facilitating the proper resolution (onboard onto the new custom events).

**Comment by slang25** [comment]
@KirillOsenkov does this effect [StructuredLogger](https://github.com/KirillOsenkov/MSBuildStructuredLog/blob/7d6b5c293368668e2ef20183c475c6a9f4552bec/src/StructuredLogger/AssemblyLoadBuildEventArgs2.cs#L20)?

**Comment by JanKrivanek** [comment]
@slang25 No events have been removed - so old logs will be still possible to open with new BinlogViewers without any issues
New events have been introduced - so version check needs to be employed and new version of BinlogViewer will need to be used - @rokonec - have you increased the [`FileFormat`](https://github.com/dotnet/msbuild/blob/main/src/Build/Logging/BinaryLogger/BinaryLogger.cs#L63) and facilitated the BinlogViewer change?

**Comment by rokonec** [comment]
There were no reason to increase FileFormat because file format has not been changed at all.
