### ISSUE TITLE
[Bug]: The SDK 'Microsoft.NET.Sdk' specified could not be found.

### ISSUE THREAD

**Issue by HoytRen** [dotnet/msbuild#9026]
### Issue Description

var rootElement = ProjectRootElement.Open(pathOfCsproj, ProjectCollection.GlobalProjectCollection, preserveFormatting: true);
var project = new Project(rootElement);

throw this exception.

### Steps to Reproduce

I installed .NET SDK by VS installer 2022 on Win11. Everything default.

I create 2 .NET 7.0 projects.

Form B project I reference Microsoft.Build by

`dotnet add package Microsoft.Build`

then call .csproj of A, and then get the error. There only these 2 lines of code in the program.cs. the rootElement is created successfully.

### Expected Behavior

A project object get created.

### Actual Behavior

Unhandled exception. Microsoft.Build.Exceptions.InvalidProjectFileException: The SDK 'Microsoft.NET.Sdk' specified could not be found.

### Versions & Configurations

Microsoft.Build --version 17.6.3

**Comment by HoytRen** [comment]
MSBuildLocator seems doesn't work well too. At first, it says I need to add 'ExcludeAssets="runtime"' property to Microsoft.Build package reference. but after I did that, my program can't start, and it says:

`Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Build, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.`

However, don't worry. I found a workaround to get needed information without instantiating a msbuild project.

**Comment by YuliiaKovalova** [comment]
HI @HoytRen,

I suspect you have missed `MSBuildLocator.RegisterDefaults();`

```
    using Microsoft.Build.Locator;

    namespace Generator
    {
        using Microsoft.CodeAnalysis.MSBuild;

        public static class Program
        {
            public static void Main(string[] args)
            {
                MSBuildLocator.RegisterDefaults();
                MSBuildWorkspace.Create();
            }
        }
    }

```

Feel free to reopen if you need more assistance here.

**Comment by HoytRen** [comment]
just let you know it's not the case, the program failed when loading assemble, no user code gets executed, it completely failed to run.

No matter, thanks for the example code.
