### ISSUE TITLE
[Bug]: TerminalLogger doesn't render some special characters

### ISSUE THREAD

**Issue by MichalPavlik** [dotnet/msbuild#9030]
### Issue Description

From windows Terminal:

![image](https://github.com/dotnet/msbuild/assets/12775388/89876846-3320-42a4-8d77-14d49c81cd20)

![image](https://github.com/dotnet/msbuild/assets/12775388/a0dad907-d058-474b-957e-03075349181d)

![image](https://github.com/dotnet/msbuild/assets/12775388/a2e3294e-e53e-4405-ae87-1717286dcbdf)

```
PS C:\GitRepos\OrchardCore> dotnet --info
.NET SDK:
 Version:   8.0.100-preview.6.23328.9
 Commit:    841df5ab90

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.100-preview.6.23328.9\
```

### Steps to Reproduce

Using .NET 8 P6 and Windows Terminal with PowerShell

### Expected Behavior

Special characters should be rendered correctly

### Actual Behavior

They are not :)

**Comment by rainersigwald** [comment]
I have bisected and 16e00e350a6523cc10131f5836569e4b5a09ff63 is to blame. Somehow.

**Comment by rainersigwald** [comment]
Workaround:

For cmd, `chcp 65001` to switch to the Unicode codepage.

For powershell, I couldn't figure out a nice way to do it -- but if you run `chcp 650001` in cmd _and then_ launch powershell it works.
