### ISSUE TITLE
[Bug]: Disable echoing input to terminal when Terminal Logger is enabled

### ISSUE THREAD

**Issue by ladipro** [dotnet/msbuild#9034]
### Issue Description

On certain platforms key presses are by default echo'ed to the terminal even when a program is running. I don't believe this is desirable with /tl as it can break the output in a random way.

### Steps to Reproduce

Build with /tl on Linux. Hit keys when the build is running.

### Expected Behavior

Except for special commands like Ctrl+C, key presses do nothing.

### Actual Behavior

Key presses are echoed to console, breaking and interleaving the output. For example when hitting Enter:

![image](https://github.com/dotnet/msbuild/assets/12206368/e429a6be-4793-4655-ad67-650062476d55)

### Versions & Configurations

Reproduces in current main (commit hash 4598629a2493ed6b366ab00d595ecd53a3164b60).

**Comment by rainersigwald** [comment]
`cargo` does _not_ do this. Not that that means _we_ shouldn't, necessarily.

**Comment by baronfel** [comment]
We may need two implementations here:
* Windows - `SetConsoleMode` with `ENABLE_ECHO_INPUT` disabled?
* non-Windows - we will likely need native code here. Consult [termios.h](https://pubs.opengroup.org/onlinepubs/7908799/xsh/termios.h.html) docs and we'll need to disable ECHO (to disable echoing to local stdout) and maybe ICANON (to disable 'canonical' mode)

References:
* https://stackoverflow.com/questions/358342/canonical-vs-non-canonical-terminal-input
* https://stackoverflow.com/questions/3305005/how-do-i-read-single-character-input-from-keyboard-using-nasm-assembly-under-u/3380413#3380413
