### ISSUE TITLE
[Bug]: SDK resolving (MSBuildLocator) on Mac with packages installed by Homebrew

### ISSUE THREAD

**Issue by YuliiaKovalova** [dotnet/msbuild#9038]
### Issue Description

Related tohttps://github.com/microsoft/vscode-dotnettools/issues/194

### Prerequisites
Mac OS with Homebrew installed.

### Steps To Reproduce
Install the C# Dev Kit
Open a folder with a .csproj file in it.
View error

![image](https://github.com/dotnet/msbuild/assets/95473390/fdba1381-2299-41e1-b7b8-dadae943f318)

### Expected Behavior

SDK is found.

### Actual Behavior

SDK is not found

**Comment by lifengl** [comment]
Hey, @YuliiaKovalova , @ladipro , based on the net core document https://learn.microsoft.com/en-us/dotnet/core/tutorials/netcore-hosting, the code should call get_hostfxr_path in nethost library to get the path of hostfxr dll, and then understand where to load hostfxr.  It looks like the current msbuildLocator has never use nethost, so it really depends on some earlier code path loads it into the memory to work. It might be not the case under certain conditions, and basically, the current implementation has always had a gap here.

and nethost.dll is in any of the NET Core runtime folder, so I assume it is in the searching path and I assume it can be loaded/bound correctly, so if we change the code to do that to resolve where to load hostfxr, it sounds to me the problem can be fixed.

@YuliiaKovalova : our GA date is earlier next month, can we get this quickly resolved to address various SDK resolving issue on Mac platform?

**Comment by YuliiaKovalova** [comment]
Primary sequence of dotnet_path resolution 
proposed changes:

for non-apphost apps, look for install locations via:
DOTNET_ROOT
dotnet binary that launched us
the known-good default paths
for apphost apps, look for install locations via
DOTNET_ROOT
the known-good default paths
PATH

**Comment by YuliiaKovalova** [comment]
The fix is published
https://www.nuget.org/packages/Microsoft.Build.Locator/1.5.6
