### ISSUE TITLE
Include error/warning count in -tl summaries

### ISSUE THREAD

**Issue by rainersigwald** [dotnet/msbuild#9049]
from @baronfel in chat offline:

> should we include a count of errors in relevant places? I'm specifically thinking of the individual project build report sections (`"<projectname> <tfm> failed with errors <time>"` => `"<projectname> <tfm> failed with <count> errors <time>"`) and the final summary `"Build failed with errors in <time>"` => `"Build failed with <total_count> errors in <time>"`)
> 
> I ask because that number is a quick visual check for a repeated-build scenario, and once you get past a certain number of reported errors (a screenful) counting yourself becomes untenable.

**Comment by baronfel** [comment]
I expect with TL enabled by default in .NET 9 previews we're going to start getting a lot of feedback related to this ticket. We should prioritize getting it in for preview 2.

**Comment by AraHaan** [comment]
I would love if TL could be enabled by default in a version of the .NET 8 SDK as well. I could also benefit from this too.

**Comment by baronfel** [comment]
@AraHaan for .NET 8 you can add an environment variable to your shell configuration to enable it by default for all applicable scenarios. Try setting `MSBUILDTERMINALLOGGER` to `auto` and see if that works for you.

**Comment by baronfel** [comment]
Also, we will almost certainly not be changing the default for .NET 8 - that would be a hugely breaking change for customers and we try to not do those without good reason.

**Comment by AraHaan** [comment]
Also as mentioned in the #msbuld channel on the DotNetEvolution Discord server. I would like it if it can also include both warnings and errors at same time as well for cases where a project simply has both. Feel free to check there as well too.
