### ISSUE TITLE
[BinFmt] Usage of  BinaryFormatter in tests

### ISSUE THREAD

**Issue by rokonec** [dotnet/msbuild#9051]
During migrating to new arcade using dotnet8 we have encounter few errors related to usage of deprecated `BinaryFormatter`,

It seems we are using BinFmt in some tests:

- `AssemblyNameEx_Tests` - we probably do no longer need binaryformatting of AssemblyNameEx
- https://github.com/dotnet/msbuild/blob/a9034a279cdb9f31166fa1212439822e6b2fbf56/src/Framework.UnitTests/EventArgs_Tests.cs#L56-L68 
whidbey seems to be VS2005 - I don't think we need it anymore, if VS still uses it they shall fix it soon - we don't need test for it
- https://github.com/dotnet/msbuild/blob/a9034a279cdb9f31166fa1212439822e6b2fbf56/src/Framework.UnitTests/LoggerException_Tests.cs#L49-L57
I thing this has been addressed in recent Jan changes in `SerializationContractInitializer` and we do no longer need to BinFmt LoggerException and whole `LoggerExceptionTests` class can be deleted

NOTE: @JanKrivanek FYI

**Comment by JanKrivanek** [comment]
Dupe of https://github.com/dotnet/msbuild/issues/8925
