### ISSUE TITLE
[Feature Request]: Allow packaging framework-dependent apps into an MSIX package

### ISSUE THREAD

**Issue by CanePlayz** [dotnet/msbuild#9077]
### Summary

Currently, it's not possible to package framework-dependent apps into an MSIX package. With a switch to set self-contained to be false, we could have MSIX packages with applications that are framework-dependent.

### Background and Motivation

I'm using a Bootstrapper which combines the advantages of self-contained and framework-dependent deployment (for context, see [here](https://github.com/Tyrrrz/DotnetRuntimeBootstrapper)). Currently, I cannot use that bootstrapper for applications that I package with MSIX.

### Proposed Feature

Add a switch to set self-contained to be false when packaging an app into an MSIX package.

**Comment by baronfel** [comment]
Hi @CanePlayz - how are you currently creating MSIX packages? Is this through something like a `wapproj` is Visual Studio, or some other means?

**Comment by CanePlayz** [comment]
Yep, completely forgot to mention, it's indeed through a `wapproj`.

**Comment by baronfel** [comment]
Thanks - `wapproj` is owned by a Visual Studio and isn't part of MSBuild itself. Can you open a feedback ticket in VS or in DevCommunity? That's the best way to get feedback to those teams about what you'd like them to work on. If you do so, you can copy the link here and I'll make sure they see it quickly.

**Comment by CanePlayz** [comment]
> Thanks - `wapproj` is owned by a Visual Studio component and isn't part of MSBuild itself. Can you open a feedback ticket in VS or in DevCommunity? That's the best way to get feedback to those teams about what you'd like them to work on. If you do so, you can copy the link here and I'll make sure they see it quickly.

Sure, thanks! It's here: https://developercommunity.visualstudio.com/t/Allow-packaging-framework-dependent-apps/10424115
