### ISSUE TITLE
[Broken Build]: After running `Deploy-MSBuild.ps1` for my local build, MSBuild cannot resolve a custom SDK

### ISSUE THREAD

**Issue by youn123** [dotnet/msbuild#9093]
### Issue Description

Ran `build.cmd` and `Deploy-MSBuild.ps1` on main to my VS installation. When I try to build a project, getting:

```
error : Could not resolve SDK "Microsoft.Build.Traversal". Exactly one of the probing messages below indicates why we could not resolve the SDK. Investigate and resolve that message to correctly specify the SDK.
C:\src\VS\src\vc\dirs.proj : error :   MSB4276: The default SDK resolver failed to resolve SDK "Microsoft.Build.Traversal" because directory "C:\Program Files\Microsoft Visual Studio\2022\Main\MSBuild\Sdks\Microsoft.Build.Traversal\Sdk" did not exist.
C:\src\VS\src\vc\dirs.proj : error MSB4236: The SDK 'Microsoft.Build.Traversal' specified could not be found.
```

`Microsoft.Build.Traversal` is a custom SDK that gets resolved from a Nuget package.

### Steps to Reproduce

Can reach out to me on internal teams for the project I'm trying to build.

### Expected Behavior

MSBuild should be able to resolve the SDK like it was able to before patch.

### Actual Behavior

MSBuild cannot resolve the SDK.

**Comment by AR-May** [comment]
Team triage: @GangWang01 let's try to repro this issue.

**Comment by GangWang01** [comment]
After syncing on internal teams, I tried the provided commit of msbuild and the project to be built. It was not reproduced. 
Close it as not repro. Feel free to re-open if it happens again.

**Comment by caspChristian** [comment]
Did this involve NuGet.config with private package source? https://github.com/dotnet/sdk/issues/36824
