### ISSUE TITLE
[Flaky test] TestEngineShutdownWhileActive

### ISSUE THREAD

**Issue by JanKrivanek** [dotnet/msbuild#9100]
**Microsoft.Build.UnitTests.BackEnd.BuildRequestEngine_Tests.TestEngineShutdownWhileActive**

### Incidence

I already saw it more than once, though in ADO history I cannot see other incidences. So probably let's just keep this item around for upvotes

### Details

https://dev.azure.com/dnceng-public/public/_build/results?buildId=361018&view=ms.vss-test-web.build-test-results-tab&runId=7619474&resultId=103618&paneView=debug

```
Assert.Equal() Failure\r\nExpected: Active\r\nActual:   Idle
```

```
at Microsoft.Build.UnitTests.BackEnd.BuildRequestEngine_Tests.VerifyEngineStatus(BuildRequestEngineStatus expectedStatus) in D:\a\1\s\src\Build.UnitTests\BackEnd\BuildRequestEngine_Tests.cs:line 523
at Microsoft.Build.UnitTests.BackEnd.BuildRequestEngine_Tests.TestEngineShutdownWhileActive() in D:\a\1\s\src\Build.UnitTests\BackEnd\BuildRequestEngine_Tests.cs:line 347
```

**Comment by JaynieBai** [comment]
Remove the https://github.com/dotnet/msbuild/blob/5f4646bee14c03f9637fd36a3001bc1ac23338d8/src/Build.UnitTests/BackEnd/BuildRequestEngine_Tests.cs#L346 will repro this issue locally verry often. 

Without enough sleep time, the following line couldn't make sure the engine status changed from idle to active.
https://github.com/dotnet/msbuild/blob/5f4646bee14c03f9637fd36a3001bc1ac23338d8/src/Build.UnitTests/BackEnd/BuildRequestEngine_Tests.cs#L521
