### ISSUE TITLE
[Bug]: The target “GetCopyToPublishDirectoryItems” does not exist in the project

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/msbuild#9109]
### Issue Description

The target “GetCopyToPublishDirectoryItems” does not exist in the project

### Steps to Reproduce

-

### Expected Behavior

No error.

### Actual Behavior

The target “GetCopyToPublishDirectoryItems” does not exist in the project

### Analysis

binlog:

[toolkit-build-packages (4).zip](https://github.com/dotnet/msbuild/files/12288027/toolkit-build-packages.4.zip)

My analysis is that `Uno.Toolkit.Samples.Mobile` invokes `GetCopyToPublishDirectoryItems` which then evaluates a ProjectReference but invokes `GetCopyToPublishDirectoryItems` on the multi targeting build rather than the build with the specific correct TargetFramework.

Shouldn't MSBuild pick the correct TFM?

**Comment by AR-May** [comment]
Team triage: @clairernovotny It seems like MSBuild.Sdk.Extras sdk is involved here.  Could you take a look if it could be related?
@Youssef1313 Does this issue reproduces with standard Microsoft sdk?
