### ISSUE TITLE
[Feature Request]: Expose the hash MSBuild uses to determine if a project should be built

### ISSUE THREAD

**Issue by Cjewett** [dotnet/msbuild#9122]
### Summary

During the MSBuild process expose a property which is the expected build output hash for a project so third parties can use it to make decisions in custom MSBuild tasks. 

### Background and Motivation

If the hash to determine if a project should be built or not is exposed then third parties could write custom tooling to implement distributed build caching. BeforeBuild we could check if the hash exists in the distributed cache and if it does download it. AfterBuild if the result doesn't already exist then we could push the results to the remote cache. The hope is to provide a C# and MSBuild native solution for distributed build caching. 

While there are higher level build systems that provide a version of distributed build caching in the C# ecosystem the correctness that an MSBuild generated hash would provide is key. As the ecosystem continues to evolve that hash would continue to be a source of truth whereas higher level build systems that aren't integrated with MSBuild provide incorrect results and run into bugs.

### Proposed Feature

I have no proposal. I feel like this may already be possible but could not find it, so I wanted to open an issue to start the discussion. Apologies if I should have created a different type of issue.

**Comment by rainersigwald** [comment]
Hey @Cjewett, I don't think I understand what you're asking for. Can you elaborate on what you think might be hashed, at what time?

> If the hash to determine if a project should be built or not

Specifically, this doesn't make sense to me. MSBuild _always_ builds projects. MSBuild's unit of incremental build is the Target (see the docs on [Incremental Builds](https://learn.microsoft.com/visualstudio/msbuild/incremental-builds)), and no hashing is involved--it's timestamp-based.

**Comment by Cjewett** [comment]
@rainersigwald @KalleOlaviNiemitalo Thanks for the responses and sorry for the confusion!

My assumption was that when MSBuild is determining if a project should or should not be built it is processing a set of inputs the project requires, performing calculations on those inputs and generating a hash, and then comparing that to a hash of the existing outputs. It sounds like no hash is calculated or maybe a combination of time and hash is used based on @KalleOlaviNiemitalo's response. I still need to go over the docs and code links to gain a better understanding. 

Really what I'm getting at is MSBuild is processing a set of inputs and making a decision on if the code needs to be compiled again or not. We want to understand if it's possible to piggyback off of that logic and introduce distributed build cache functionality with custom targets.

Hypothetical scenario: 
1. Target Inputs does not match Outputs locally.
2. Check distributed build cache if Inputs exists.
3a. [Remote Cache Hit] If yes then download Outputs from distributed build cache instead of executing the Target that would have generated the Outputs locally.
3b. [Remote Cache Miss] If no then execute the Target that would generate the Outputs locally. Upon completion upload the Inputs to map to the Outputs in the distributed build cache.

Does that clear the confusion? If not I'm happy to add more context and try to explain further.

**Comment by jrdodds** [comment]
@Cjewett You are trying to distribute the targets of a project? That will be impractical.

The `Inputs` and `Outputs` attributes on [`Target`](https://learn.microsoft.com/en-us/visualstudio/msbuild/target-element-msbuild?view=vs-2022) are optional and, when present, the values are dynamic. Most targets are logic and don't produce output files. Properties and items in the project are shared and are not scoped to targets.

**Comment by Cjewett** [comment]
@jrdodds Not necessarily all targets in a project but for some yes.

I guess I'm a bit confused and that is likely due to my lack of understanding of the MSBuild ecosystem. 

When you run a build, and more specifically when it is determining if a project should be compiled, is it looking at an Inputs? And doesn't that map to a deterministic Outputs? https://learn.microsoft.com/en-us/visualstudio/msbuild/incremental-builds?view=vs-2022#output-inference 

Just thinking out loud here but based on the code below
https://github.com/dotnet/msbuild/blob/8e4c5731440bf770f73447758ef51b4cae31a057/src/Tasks/Microsoft.Common.CurrentVersion.targets#L3395-L3425
@KalleOlaviNiemitalo's explanation, and I admit further explanation by ChatGPT :laughing: it looks like some cache is being generated to determine if a project should be built. Would it not be possible to take that file, hash it, and expose it in MSBuild? That way you can use the hash and some extended MSBuild functionality to determine if a remote cache contains the build output already, and if so download cached result to the csproj's build output directory. Then it can continue down its normal build flow.

**Comment by jrdodds** [comment]
@Cjewett ChatGPT has probably given you misinformation. But you are probably still better off than these [lawyers](https://arstechnica.com/tech-policy/2023/06/lawyers-have-real-bad-day-in-court-after-citing-fake-cases-made-up-by-chatgpt/). :smiley:

MSBuild doesn't pre-determine if a project needs to be built or not. MSBuild loads the project and follows the instructions in the project. Other tools that wrap MSBuild may have file tracking and/or caching. When you build a solution in Visual Studio and the build output reports some number of projects "skipped", that's Visual Studio and not MSBuild.

Target inputs and outputs are not deterministic.

Output inference is not determining target outputs. If a target has a task (or tasks) with an [`Output` element](https://learn.microsoft.com/en-us/visualstudio/msbuild/output-element-msbuild?view=vs-2022)  and the target is up to date, output inference will modify the property or item in the `Output` element as if the target had run.

@KalleOlaviNiemitalo's example is hashing the inputs to see if the inputs match the inputs seen in the last build. The `.CoreCompileInputs.cache` file is a generated artifact of the build. As the comment explains, this is an additional step to catch the cases where a file has been added or removed. The cache file alone is not sufficient to know if a target needs to be run.

**Comment by Cjewett** [comment]
@jrdodds Thanks again for further explanation! Wanted to acknowledge I've read this and intend to respond but need to pivot to another piece of work for a few work days.

**Comment by Cjewett** [comment]
@jrdodds Apologies for the delay. 

So I think an example of what [nx-dotnet](https://www.nx-dotnet.com/) is worth using because their solution does work.

What they do is they add a target:
```xml
<Project>
  <PropertyGroup>
    <MSBuildProjectDirRelativePath>$([MSBuild]::MakeRelative($(RepoRoot), $(MSBuildProjectDirectory)))</MSBuildProjectDirRelativePath>
    <NodeModulesRelativePath>$([MSBuild]::MakeRelative($(MSBuildProjectDirectory), $(RepoRoot)))</NodeModulesRelativePath>
  </PropertyGroup>
  <Target Name="CheckNxModuleBoundaries" BeforeTargets="Build">
    <Exec Command="node $(NodeModulesRelativePath)/node_modules/.pnpm/@nx-dotnet+core@1.22.0_@nrwl+workspace@16.8.1_nx@16.8.1_typescript@4.9.5/node_modules/@nx-dotnet/core/src/tasks/check-module-boundaries.js --project-root &quot;$(MSBuildProjectDirRelativePath)&quot;"/>
  </Target>
</Project>
```

That check-module-boundaries.js is checking if the contents of the MSBuildProjectDirRelativePath matches what exists in nx-cloud according to whatever logic nx is using. If it does then copy the contents to the machine. When the next steps occur within the MSBuild process it will not build because whatever check happens after doesn't think a build needs to occur. Is there anything with fundamentally wrong with the solution they've rolled out? 

There are certainly edge cases that are not caught such as changing repository level files (Directory.Packages.props), but as far as I can tell it does work.

**Comment by rainersigwald** [comment]
> Is there anything with fundamentally wrong with the solution they've rolled out?
> 
> There are certainly edge cases that are not caught such as changing repository level files (Directory.Packages.props),

Yes, exactly. There's also a lot of other tricks one could pull in build logic to make trouble here.

This is a fundamental problem with layering a new incrementality model on the existing one: it's pretty doable to get it _ok_, and almost impossible to get it _right_.

**Comment by jrdodds** [comment]
> That check-module-boundaries.js is checking if the contents of the MSBuildProjectDirRelativePath matches what exists in nx-cloud according to whatever logic nx is using.

Comparing nx-dotnet and MSBuild is helpful to understanding what you are asking for but it is an apple to an orange comparison.

> My hope is that a Microsoft solution could replace or provide a key for the logic they're using ...

MSBuild was designed to build and, as the build proceeds, skip steps that are already up-to-date. Your feature request seems to be that MSBuild should have a completely different "incrementality model" that supports project caching.

This may be off-topic but if this is an XY problem then maybe this gets at the X. Do you trigger your builds only when there is a source control change? Do you use an internal package server? I ask because the individual package can be focused, the package builds can be distributed, and the package is the cached build product.

**Comment by rainersigwald** [comment]
> I think those maintainers would agree that if Microsoft offered functionality to replace the `check-module-boundaries.js` piece it would be a happy day.

Well, some medium-good news for you: https://github.com/dotnet/msbuild/pull/9214 is a step in this direction. See also https://github.com/dotnet/msbuild/blob/main/documentation/specs/project-cache.md (which isn't updated for the new PR).

> My goal coming in was to see if this piece could be exposed.

The important thing to understand is "this piece" _doesn't exist_. It was not part of the design of MSBuild. That's a major limitation of MSBuild compared to more modern build systems. Microsoft is interested in adding it in, but it's quite difficult--the effort required to get [CloudBuild](https://www.microsoft.com/en-us/research/publication/cloudbuild-microsofts-distributed-and-caching-build-service/), the main internal-to-Microsoft distribution+caching system, working on a repo is so high

[BuildXL](https://github.com/microsoft/BuildXL) is another distribution and caching layer that can be applied on top of MSBuild. It provides its own understanding of the inputs/outputs based on interception and observation of the I/O syscalls made by MSBuild.exe and its launched processes.

**Comment by jrdodds** [comment]
> > as the build proceeds, skip steps that are already up-to-date
>
> My assumption was if the check to determine if something was already up-to-date is exposed ...

One problem is that you want the result of the check to be available and 'exposed' before MSBuild has performed the check.

**Comment by jrdodds** [comment]
> I assume with the internal packages what you're getting at is creating NuGet packages of the projects and referencing them from other projects via NuGet. We do have a NuGet server but in the case of this monorepository we are not leveraging it to distribute builds in the way that you described. There are a lot of fundamental changes that would need to happen and as you can imagine those type[s] of changes take time and philosophical shifts to move forward.

Oh, I'm very familiar with situations like those you describe. Good luck. :smiley:

And thanks for the conversation.

**Comment by Cjewett** [comment]
@jrdodds Likewise! Appreciate all of your responses, guidance, and teachings. 

@rainersigwald It looks like the functionality in https://github.com/dotnet/msbuild/pull/9214 would fill that void which is super exciting! Thanks for sending that. It looks like that functionality will roll out in 17.8 correct? Is there an expectation to update the docs to show an example or outline how to create one of these plugins or should we plan to dig into the source to understand what is going on?

Also, as this discussion is running its course I'm unsure how we want to approach the status of this ticket. I'm happy to close it if we're able to track the work related to the project-cache.md design doc and related work since it seems like that is the way forward and has been in the works for quite some time.

**Comment by rainersigwald** [comment]
> It looks like that functionality will roll out in 17.8 correct? 

Correct, though note that now that 17.9 is out there are fixes to improve the experience as https://github.com/microsoft/MSBuildCache matures.

> Is there an expectation to update the docs to show an example or outline how to create one of these plugins in a more tutorial-like manner or should we plan to dig into the source to understand what is going on?

@dfederm @AndyGerlicher This is a good question. I don't think we have plans to write detailed docs in the short term, right?

> Also, as this discussion is running its course I'm unsure how we want to approach the status of this issue.

I'm going to close for now but please let us know what questions you have!

**Comment by Cjewett** [comment]
@rainersigwald I'm okay closing this one. I have an e-mail chain open with @dfederm and have been keeping up to date with their improvements. We're doing the groundwork to have a pipeline which tests these changes internally as new updates roll out. Thanks everyone for the input here. Excited for this one!
