### ISSUE TITLE
[Bug]: NoWarn randomly get ignored in build

### ISSUE THREAD

**Issue by tarekgh** [dotnet/msbuild#9133]
### Issue Description

The runtime repo CI started randomly fail building projects which uses `NoWarn` and still the suppressed warning gets fired and breaks the build. The [runtime issue](https://github.com/dotnet/runtime/issues/90434) showing such failures. 

Here is an example suppressing [`NETSDK1206`](https://github.com/dotnet/runtime/blob/1b7263e63e3f793324b5a56fed949c7df1cab7cd/src/libraries/Microsoft.Extensions.Logging.Abstractions/tests/Microsoft.Extensions.Logging.Generators.Tests/Microsoft.Extensions.Logging.Generators.targets#L11) and compilation produces `error NETSDK1206: Found version-specific or distribution-specific runtime identifier(s): alpine-x64. Affected libraries: SQLitePCLRaw.lib.e_sqlite3`.

[binlog](https://1drv.ms/u/s!AhP2SwMuINnCjq01t_3ziraVD9mFMQ?e=dA8WQx)

### Steps to Reproduce

No specific steps as the CI randomly failing. 

### Expected Behavior

Projects suppressing the warning should build successfully without failing with the suppressed warning 

### Actual Behavior

The suppressed  `NETSDK1206` produces randomly the error:
`error NETSDK1206: Found version-specific or distribution-specific runtime identifier(s): alpine-x64. Affected libraries: SQLitePCLRaw.lib.e_sqlite3`

### Analysis

msbuild have a problem not suppressing the warning. 

### Versions & Configurations

The runtime repo CI runs is using `.NET 8 P7 SDK`.

**Comment by JanKrivanek** [comment]
Can this be an analogous case caused be a rootcause in a same code as https://github.com/dotnet/msbuild/issues/8814? @rokonec?

**Comment by JaynieBai** [comment]
> Does the binlog show NoWarn being translated to MSBuildWarningsAsMessages in the test project? Difficult to find when the log is so large.

From the correct build log, it's true to treat the warning as message.  But in the failed log it is treated as errors.
![image](https://github.com/dotnet/msbuild/assets/26814373/e250c03c-c199-4900-8a6f-c4387d2e8557)

**Comment by tarekgh** [comment]
@ViktorHofer may help with this as the failure is in [Microsoft.DotNet.HotReload.Utils.Generator.BuildTool](https://github.com/dotnet/hotreload-utils/tree/main/src/Microsoft.DotNet.HotReload.Utils.Generator.BuildTool)

**Comment by ViktorHofer** [comment]
@lambdageek @akoeplinger are the main contributors to hotreload-utils. Can you please take a look?

**Comment by akoeplinger** [comment]
Can you try removing the /p:CrossBuild=true ? It's not needed since you're building on arm64 for arm64

**Comment by JaynieBai** [comment]
> Can you try removing the /p:CrossBuild=true ? It's not needed since you're building on arm64 for arm64

Remove that, but the same errors are still there.

**Comment by JanKrivanek** [comment]
Info by @timmydo:


> [https://cloudbuild.microsoft.com/build/5c51aba5-6861-4aa5-90d5-d4f53de94008?bq=git_snrcode2_master_retail](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcloudbuild.microsoft.com%2Fbuild%2F5c51aba5-6861-4aa5-90d5-d4f53de94008%3Fbq%3Dgit_snrcode2_master_retail&data=05%7C01%7Cjan.krivanek%40microsoft.com%7C90299ba967424225702408dba332e39d%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638283211230487609%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=C%2BoLOudeueRa6yFiERJDsPpSCmMTY9W4NGS3I1DTNdM%3D&reserved=0)

> D:\data\Q\dotnet\9pwfkyv5X45xHLPhGvUGgg\sdk\8.0.100-preview.7.23376.3\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(267,5): warning NETSDK1206: Found version-specific or distribution-specific runtime identifier(s): osx.10.14-arm64, osx.10.14-x64. Affected libraries: Microsoft.ML.OnnxRuntime. In .NET 8.0 and higher, assets for version-specific and distribution-specific runtime identifiers will not be found by default. See https://aka.ms/dotnet/rid-usage for details. [D:\dbs\el\sn2\private\frontend\Answers\services\Flights\Test\Flights.Tests.csproj]

> binlog
> [https://cloudbuild.microsoft.com/stamp/MW_PS12/getfile?path=\CO1PPF547CF2B56\d:\dbs\sh\sn2\0822_092659_1\private\frontend\Answers\services\Flights\Test\Logs\Retail\AnyCPU\msbuild.binlog](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcloudbuild.microsoft.com%2Fstamp%2FMW_PS12%2Fgetfile%3Fpath%3D%255CCO1PPF547CF2B56%255Cd%3A%255Cdbs%255Csh%255Csn2%255C0822_092659_1%255Cprivate%255Cfrontend%255CAnswers%255Cservices%255CFlights%255CTest%255CLogs%255CRetail%255CAnyCPU%255Cmsbuild.binlog&data=05%7C01%7Cjan.krivanek%40microsoft.com%7C90299ba967424225702408dba332e39d%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638283211230487609%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=n22djPXONoNYWu74OUXAX3Jf31dkDi9HdoRW42Y6yIY%3D&reserved=0)

> text log 
> [https://cloudbuild.microsoft.com/stamp/MW_PS12/getfile?path=\CO1PPF547CF2B56\d:\dbs\sh\sn2\0822_092659_1\private\frontend\Answers\services\Flights\Test\Logs\Retail\AnyCPU\build.log](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcloudbuild.microsoft.com%2Fstamp%2FMW_PS12%2Fgetfile%3Fpath%3D%255CCO1PPF547CF2B56%255Cd%3A%255Cdbs%255Csh%255Csn2%255C0822_092659_1%255Cprivate%255Cfrontend%255CAnswers%255Cservices%255CFlights%255CTest%255CLogs%255CRetail%255CAnyCPU%255Cbuild.log&data=05%7C01%7Cjan.krivanek%40microsoft.com%7C90299ba967424225702408dba332e39d%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638283211230487609%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Aq09ZfS5F30Hkc7ZajzyP5pde31%2BlAI7qksEcWiqh7A%3D&reserved=0)

> we aren't building or running on OSX. I'm considering repackaging the onnxruntime nuget myself.

Btw. - the NETSDK1206 only shows as warning in that log:

![image](https://github.com/dotnet/msbuild/assets/3809076/f3f2eae1-5737-4cc1-a36b-8881ca0f23fc)
