### ISSUE TITLE
Analyzer: prefer explicit culture for `EmbeddedResource`

### ISSUE THREAD

**Issue by rainersigwald** [dotnet/msbuild#9154]
If you don't specify `WithCulture=false` or `Culture={culture identifier}` as metadata on an `EmbeddedResource`, the `AssignCulture` task will attempt to determine from the filename whether a file is neutral or belongs to a specific culture. But that can vary by what culture identifiers are known to .NET/the OS on the builder. It's more robust to explicitly specify.

related: https://github.com/MicrosoftDocs/visualstudio-docs/issues/9559

**Comment by JanKrivanek** [comment]
@ghogen - the visualstudio-docs repo doesn't seem to have issues (and hence the link above - https://github.com/MicrosoftDocs/visualstudio-docs/issues/9559 - is dead). Were those moved anywhere? I'd love to get the original context

**Comment by ghogen** [comment]
https://web.archive.org/web/20230824140802/https://github.com/MicrosoftDocs/visualstudio-docs/issues/9559

**Comment by ghogen** [comment]
I made changes to the AssignCulture task article to address this issue in August 2023 - https://learn.microsoft.com/en-us/visualstudio/msbuild/assignculture-task?view=vs-2022

https://github.com/MicrosoftDocs/visualstudio-docs/commit/33952289337ee72da9cc233ac2d34bdf5d9db38a

**Comment by JanKrivanek** [comment]
Duplicated by https://github.com/dotnet/msbuild/issues/9882
