### ISSUE TITLE
[Feature Request]: EnforceAssets attribute for PackageReference

### ISSUE THREAD

**Issue by EdLichtman** [dotnet/msbuild#9163]
### Summary

Sometimes a library may depend on another but not because you're using that library in the child.

This is to tell the parent that it needs to import a sibling.

### Background and Motivation

I'm packaging up distributable json manifest files that add themselves to a project in the form of AdditionalFiles.

I'm also packaging a single analyzer that finds all the manifest additional files and generates code from them.

The problem I'm having is, if the json packages have explicit dependencies on the analyzer, then the analyzer runs multiple times and clashes with itself. If I set PrivateAssets=none and IncludeAssets=none or ExcludeAssets=all, then the dependency graph in nuget doesn't list the analyzer as a dependency. 

An additional issue I can see this solving is, I would like a joint dependency, where the analyzer depends on the json being present and the json depends on the analyzer being present but neither of them are dependent upon each other and therefore don't cause a circular dependency. 

### Proposed Feature

I'm thinking EnforceAssets would be the reverse of PrivateAssets, but wouldn't interfere with include or exclude.

Therefore you can say:

EnforceAssets=build;buildTransitive;analyzers IncludeAssets=build

And the build would be the only thing the child uses but then tells the parent it must depend on those other assets. 

### Alternative Designs

I'm working on a snippet I found to add Pack=true called "AddPackDependencies"  I found to make it easier to communicate to a parent that a dependency is required. Problem is it also compiles the dll into it to avoid using the targetmoniker syntax. I am going to see if I can alter the function to include this, but it's been slow going, understanding the whole pipeline.

**Comment by rainersigwald** [comment]
This issue was moved to NuGet/Home#12842
