### ISSUE TITLE
System.Windows.Extensions.dll included in Linux SDK output

### ISSUE THREAD

**Issue by mthalman** [dotnet/msbuild#9213]
The Linux version of the SDK is including the System.Windows.Extensions.dll file in the following paths:

* ./sdk/x.y.z/FSharp/runtimes/win/lib/netx.y/System.Windows.Extensions.dll
* ./sdk/x.y.z/runtimes/win/lib/netx.y/System.Windows.Extensions.dll

~This is a regression as a result of the change in https://github.com/dotnet/msbuild/pull/9158. That change caused the live version of System.Security.Permissions to be used. That version has a dependency on System.Windows.Extensions, even when targeting Linux. So System.Windows.Extensions is being built and included in the output of the SDK.~ This is not a regression from https://github.com/dotnet/msbuild/pull/9158 because this change also exists in Microsoft-built SDK for Linux. The change from https://github.com/dotnet/msbuild/pull/9158 just made it visible in the source-build SDK diff tests.

There are other files existing in this `runtimes/win` path as well, which is a suspicious path when targeting Linux:

* System.Diagnostics.EventLog.dll
* System.Diagnostics.EventLog.Messages.dll
* System.Security.Cryptography.Pkcs.dll
* System.ServiceProcess.ServiceController.dll

**Comment by ViktorHofer** [comment]
Yes, I think this got resolved.
