### ISSUE TITLE
[Bug]: Content item marked with Pack="True" not included in NuGet package when using <TargetFrameworks> in csproj

### ISSUE THREAD

**Issue by bhaeussermann** [dotnet/msbuild#9230]
### Issue Description

In my solution I have an MSBuild targets file that looks as follows:

```
<Project>
    <Target Name="IncludeContentInPackage" AfterTargets="AfterCompile">
		<ItemGroup>
			<PackAsRuntimeFile Include="file-to-include.txt" PackagePath="content/file-to-include.txt" />
		</ItemGroup>

		<ItemGroup>
			<Content Include="@(PackAsRuntimeFile)" Pack="True" />
		</ItemGroup>
    </Target>
</Project>
```

When I package my project using the command
```
dotnet pack --configuration Release --output out
```
The resultant package file will include the specified file inside of a folder named "content".

However, when I change the project's `<TargetFramework>` element into a `<TargetFrameworks>`, the file will no longer be included in the package!

### Steps to Reproduce

A sample project that demonstrates the issue is attached.
Run the following command inside of the solution folder to create a package:
```
dotnet pack --configuration Release --output out
```
Rename the resultant _.nupkg_ file to a _.zip_ file in order to inspect its contents.

[MultipleTargetFrameworks.zip](https://github.com/dotnet/msbuild/files/12657361/MultipleTargetFrameworks.zip)

### Expected Behavior

The _.nupkg_ file contains the _file-to-include.txt_ file inside of a _content_ folder.

### Actual Behavior

The file to include is not in the package like when I use the `<TargetFramework>` tag on the project instead of `<TargetFrameworks>`.

### Versions & Configurations

dotnet --version: 7.0.401

MSBuild version 17.7.3+8ec440e68 for .NET
17.7.3.40206

**Comment by AR-May** [comment]
MSBuild team triage: moving this issue to the NuGet as it seems related to them.
