### ISSUE TITLE
[Bug]: DOTNET_CLI_UI_LANGUAGE ignored for English

### ISSUE THREAD

**Issue by splendid25** [dotnet/msbuild#9254]
### Issue Description

Hello,
I think the parameter DOTNET_CLI_UI_LANGUAGE doesn't work for some languages.

MsBuild runs in French by default, as my OS is in French.
When I try to set the language to English(en or en-US), nothing changes, the output is still in French.

But for instance, Spanish works as expected.

I don't know if I missed something in the config ?

Thank you

### Steps to Reproduce

```powershell
dotnet new console
$msbuild = "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\amd64\MSBuild.exe"
& $msbuild
```
```
Version MSBuild 17.7.2+d6990bcfa pour .NET Framework
La génération a démarré 22/09/2023 12:30:37.

Tentative d'annulation de la génération en cours...
```

```powershell
$env:DOTNET_CLI_UI_LANGUAGE="en"
& $msbuild
```
```
Version MSBuild 17.7.2+d6990bcfa pour .NET Framework
La génération a démarré 22/09/2023 12:31:09.

Tentative d'annulation de la génération en cours...
```

```powershell
$env:DOTNET_CLI_UI_LANGUAGE="es"
& $msbuild
```
```
Versión de MSBuild 17.7.2+d6990bcfa para .NET Framework
Compilación iniciada a las 22/09/2023 12:32:56.

Intentando cancelar la compilación...
```

### Expected Behavior

Output in English :
```
MSBuild version 17.7.2+d6990bcfa for .NET Framework
Build started 22/09/2023 14:01:39.

Attempting to cancel the build...
```

### Actual Behavior

Output in French :
```
Version MSBuild 17.7.2+d6990bcfa pour .NET Framework
La génération a démarré 22/09/2023 12:31:09.

Tentative d'annulation de la génération en cours...
```

### Analysis

The only way I could get it to work in English, is by setting the codepage.
Even then, it's half in english, half in french.
```powershell
chcp 437
& $msbuild
```
```
MSBuild version 17.7.2+d6990bcfa for .NET Framework
Build started 22/09/2023 12:31:58.

Tentative d'annulation de la génération en cours...
```

But I can't use this codepage for my build as I need some accents to display properly. I just want the MsBuild messages to be localized in english.

### Versions & Configurations

MSBuild version 17.7.2+d6990bcfa for .NET Framework
17.7.2.37605

**Comment by JanKrivanek** [comment]
FYI @nagilson
