### ISSUE TITLE
[Feature Request]: sln file annotation for a project that is not present

### ISSUE THREAD

**Issue by daveyostcom** [dotnet/msbuild#9259]
### Summary

Allow private nested solution folders.

### Background and Motivation

- I have a project `X`, which I use for a playground.
- I have to add `X` to `S` to be able to do useful things with `X`.
- No other projects in `S` depend on `X`.
- I don’t want to add `X` to the git repo for `S`.

The problem is that when someone clones my repo, they are admonished that project `X` is missing.  But they have no need to know anything about `X`.

### Proposed Feature

Given a solution `S` in folder/file `FolderS/S.sln`,
- A **private solution** `X` (`FolderX/X.sln`) is allowed to reference things within `S`
- `S` is not allowed to reference `X` or anything within `X`.
- `FolderX/X.sln` may be nested within `FolderS/`.
- Perhaps nesting of `FolderX` in `FolderS` must be required.

Thus `X` is unknown to `S` and can be left out of the `S` git repo without causing any problems in a clone of the `S` repo.

### Alternative Designs

It seems reasonable that this feature has to be implemented at the level of Solutions so that other files associated only with `X` can be in `FolderX`, such as IDE run configuration files.  But maybe there is another way.

It might be ok for a solution `FolderX/X.sln` not inside `FolderS` to be considered private.

The motivation of the above is to allow a private nested solution.  But more generally, it could be useful to have two solutions in separate folders, where one references the other, or where they are both partial solutions and reference each other.  That idea would lead to a case where a solution `G` may contain both `S` and `X` so that they are allowed to reference each other.

**Comment by rainersigwald** [comment]
Team Triage: The solution file format is controlled by Visual Studio, not MSBuild. Can you [open a feedback ticket instead](https://docs.microsoft.com/visualstudio/ide/feedback-options)?

After it's created, that will open an internal bug which will be routed to the right team. If you post the link here we may be able to help that process go faster.

**Comment by daveyostcom** [comment]
> Team Triage: The solution file format is controlled by Visual Studio, not MSBuild. Can you [open a feedback ticket instead](https://docs.microsoft.com/visualstudio/ide/feedback-options)?

Submitted.  Thanks.
