### ISSUE TITLE
Binlog - Add forward reading compatibility and quick raw reading capability

### ISSUE THREAD

**Issue by JanKrivanek** [dotnet/msbuild#9261]
### Context
Motivated/Driven by the Binlog Redacting topic. In order for faster processing of binlogs, we'd want to skip through events without need for deserialization - this could only be enabled if we explicitly store event sizes (breaking change). As a side effect this will allow to more gracefully process logs with unknown message types or unknown data within known message types.

**Comment by JanKrivanek** [comment]
Near completition. PR: https://github.com/dotnet/msbuild/pull/9307

**Comment by rokonec** [comment]
Almost done

**Comment by JanKrivanek** [comment]
Merged, plus updated tolling in partner repos

**Comment by rokonec** [comment]
[celebrate]     Roman Konecny reacted to your message:
________________________________
