### ISSUE TITLE
[Bug]: Localization comment is wrong and blocks translation.

### ISSUE THREAD

**Issue by crsuzukimsft** [dotnet/msbuild#9283]
### Issue Description

See the file /src/Tasks/Resources/Strings.resx at line 2788

 &lt;data name="Copy.RetryingOnAccessDenied" &gt;
     &lt;value>"MSB3895: Retrying on ERROR_ACCESS_DENIED because environment variable MSBUILDALWAYSRETRY = 1" &lt;/value &gt;
     &lt;comment>{StrBegin="MSB3895: "} LOCALIZATION: Do NOT translate MSBUILDALWAYSRETRY") &lt;/comment &gt;
   &lt;/data &gt;

The comment is wrong, since the string now has double quotes.
Current Dev rule: {StrBegin="MSB3895: "}
Suggested Dev rule: {StrBegin='"MSB3895: '}

### Steps to Reproduce

See text.

### Expected Behavior

The comment is fixed, unblocking translation.

### Actual Behavior

Current comment prevents localization.

**Comment by rainersigwald** [comment]
@crsuzukimsft do you need this for 17.8, or can we fix in `main`?

**Comment by crsuzukimsft** [comment]
both main and 17.8 as we localize both branches.
