### ISSUE TITLE
Enhance logging to enable correct tracking of task assemblies

### ISSUE THREAD

**Issue by ladipro** [dotnet/msbuild#9290]
Currently the `Using "{0}" task from assembly "{1}".` log message contains only the bare task name. Similarly, `TaskStartedEventArgs` carries only the task name, without additional parameters like architecture and runtime.  In cases where multiple tasks of the same name are loaded from different assemblies, it is impossible to reconstruct from logs information on which task was actually invoked.

Probably the most straightforward fix would be to include architecture & runtime (or `taskIdentityParameters` in general) in the message and event args, to allow log viewers to match them exactly.

**Comment by ladipro** [comment]
💡 `TaskStartedEventArgs` may as well just have the task assembly added to it.

**Comment by KirillOsenkov** [comment]
Wait, does MSBuild support two tasks with the same name? How does it even work? When you call a task from a target, which one gets called?

**Comment by rainersigwald** [comment]
Yes, you can wind up with the same task name from different assemblies and select between them with the `MSBuildArchitecture` and `MSBuildRuntime` [magic task parameters](https://learn.microsoft.com/visualstudio/msbuild/how-to-configure-targets-and-tasks?view=vs-2022#usingtask-attributes-and-task-parameters). This is super rare--but `GenerateResource` does it, so it's in a big chunk of builds.
