### ISSUE TITLE
[Bug]: Terminal logger crashes when building the SDK repo 

### ISSUE THREAD

**Issue by ladipro** [dotnet/msbuild#9323]
### Issue Description

Building the SDK on the command line results in a `KeyNotFoundException` in TL.

### Steps to Reproduce

1. Clone https://github.com/dotnet/sdk on Windows, checkout commit c0389b12154e290d7722d220e0e8928531c03e2d.
2. Set `MSBUILDLIVELOGGER=auto`.
3. Run `restore.cmd`.
4. Run `build.cmd`.

### Expected Behavior

Build runs to completion.

### Actual Behavior

Build hangs due to:

```
  C:\src\sdk\src\Tests\Microsoft.DotNet.PackageInstall.Tests\SampleGlobalTool\consoledemo.csproj Restore (7.0s)
  redist PublishNETAnalyzers (13.5s)
MSBUILD : error MSB4017: The build stopped unexpectedly because of an unexpected logger failure.
System.Collections.Generic.KeyNotFoundException: The given key 'ProjectContext { Id = 1906 }' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Microsoft.Build.Logging.LiveLogger.LiveLogger.ProjectStarted(Object sender, ProjectStartedEventArgs 337.7s)
   at Microsoft.Build.BackEnd.344.2s).EventSourceSink.RaiseProjectStartedEvent(Object sender, ProjectStartedEventArgs buildEvent)
```

### Versions & Configurations

8.0.100-preview.7.23376.3

**Comment by ladipro** [comment]
It appears to reproduce consistently on my machine. I should be able to dig deeper when I get some time.

**Comment by rainersigwald** [comment]
No repro on my machine (with one attempt). I might try to update to RC2 before investigating deeply, just in case.

**Comment by AR-May** [comment]
Team triage: @ladipro. could you check the latest MSBuild main as tell us if it reproes?

**Comment by ladipro** [comment]
@AR-May @rainersigwald it's likely timing sensitive and I cannot repro with the SDK repo anymore. However, it's not hard to guess what's happening. Our special handling of the `Restore` target contains assumptions which may not always be true, especially when building a non-conventional project.

Here's a minimal repro:

```xml
<Project>
  <Target Name="Restore">
    <MSBuild Projects="$(MSBuildThisFileFullPath)" Targets="Restore" Properties="Color=Red" />
  </Target>
</Project>
```

Run `dotnet restore` to reproduce the crash.

Not a P1 but we should make the code more defensive before enabling the logger by default.
