### ISSUE TITLE
ILMerge.Merge: ERROR!!: Duplicate type

### ISSUE THREAD

**Issue by wally96334** [dotnet/msbuild#9331]
### Issue Description

What I am trying to do is very straightforward (or it should be).

I am trying to merge all of my DLLs and associated resources into a single executable with Visual Studio 2017 Community using ILMerge. I get the following error:

Error       ILMerge.Merge: ERROR!!: Duplicate type 'XamlGeneratedNamespace.GeneratedInternalTypeHelper' found in assembly 'xxxx.WPF'. Do you want to use the /allowDup option? Primary_Calc_Console_01         

I see that an ILMerge.props file has been introduced after the installation. Presumably, this is a config file for ILMerge (?).

```
I see the following tag in the config file:
    <!-- added in Version 1.0.4, default=none -->
    <ILMergeAllowDuplicateType></ILMergeAllowDuplicateType>

```
Can someone tell me what value I should give it to allow duplicate types?

### Steps to Reproduce

I see the following tag in the config file:
```
    <!-- added in Version 1.0.4, default=none -->
    <ILMergeAllowDuplicateType></ILMergeAllowDuplicateType>

```
Can someone tell me what value I should give it to allow duplicate types?

### Expected Behavior

Ignore duplicate types

### Actual Behavior

none

**Comment by jrdodds** [comment]
Are you using the [MSBuild.ILMerge.Task](https://www.nuget.org/packages/MSBuild.ILMerge.Task/) NuGet package? That package has a ILMerge.props file with lines that match.

That package is from a third party and you need to contact the owners of the package.

**Comment by wally96334** [comment]
>>> That package is from a third party and you need to contact the owners of the package.

Done.

Thanks for the response.
