### ISSUE TITLE
Failed to build MSBuild: Binding redirect for System.ValueTuple 4.0.0.0 vs. 4.0.2.0

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/msbuild#9354]
I cloned MSBuild and built it with /p:CreateBootstrap=true

Build failed with

![image](https://github.com/dotnet/msbuild/assets/679326/e18c7b0f-fa05-4642-ad10-09f39ed9ec8f)

Let's fix this soon.

**Comment by KirillOsenkov** [comment]
also I think building with /bl should be the default for the msbuild repo (if I type build), surprised there was no binlog anywhere

**Comment by KirillOsenkov** [comment]
Binlog available upon request

![image](https://github.com/dotnet/msbuild/assets/679326/8781f7a4-e360-4eed-b36b-a9fc63dcfdad)

**Comment by KirillOsenkov** [comment]
Can we prioritize this please? @forgind I'm happy to help you investigate on my machine if you can't repro on yours.

**Comment by KirillOsenkov** [comment]
These are the System.ValueTuple.dlls on disk:

![image](https://github.com/dotnet/msbuild/assets/679326/834ce140-3cf9-4d48-9686-88a804e96a89)

**Comment by KirillOsenkov** [comment]
This is the redirect in `C:\msbuild\artifacts\obj\MSBuild\Debug\net472\MSBuild.exe.withSupportedRuntime.config`:
![image](https://github.com/dotnet/msbuild/assets/679326/34576895-6858-4773-9941-44ff47dc5787)

**Comment by KirillOsenkov** [comment]
So I understand what is happening but I don't know how to fix it. I think the code in here needs to be adjusted for 4.0.2.0:
https://github.com/dotnet/msbuild/blob/221fd2e8790a22ead513eb71630557efc02060e2/src/MSBuild/ValidateMSBuildPackageDependencyVersions.cs#L46

**Comment by KirillOsenkov** [comment]
I've worked around locally with:

![image](https://github.com/dotnet/msbuild/assets/679326/cb3992e4-739a-4c7b-81d3-5c7e6b92bf7f)

Not sure if it's the best fix. Looks like we expect 4.0.3.0 to be copied to output? Not sure why half of them are 4.0.2.0 and the other half 4.0.3.0 and what the expected behavior is.

**Comment by rainersigwald** [comment]
In the log what is the source of the copy in the MSBuild.exe process? Should be a NuGet package.

**Comment by KirillOsenkov** [comment]
Interesting, it copies from this weird location:
![image](https://github.com/dotnet/msbuild/assets/679326/cd2077fa-20a0-4956-8fa3-7810f9f4cb1f)

I'm guessing since I ran the build from a razzle-like environment it picked up the package from C:\.tools and not from the usual location. My environment must be dirty somehow.

**Comment by KirillOsenkov** [comment]
Ah, yes, I have an environment variable :(

`NUGET_PACKAGES=C:\.tools\.nuget\packages\`

I suppose PEBKAC, my bad.

**Comment by rainersigwald** [comment]
4.5.0 of that package should have 4.0.3.0 so it looks like you have a corrupt NuGet cache :-/

**Comment by KirillOsenkov** [comment]
Very likely, since this repo uses hardlinks!!

**Comment by KirillOsenkov** [comment]
You guys want to see real-life NuGet package cache corruption?

![image](https://github.com/dotnet/msbuild/assets/679326/02095f1f-962e-48cc-8e7b-06991d3865d4)


cc @inthemedium
