### ISSUE TITLE
Investigate System.Text.Json mismatches with C++ build tasks

### ISSUE THREAD

**Issue by rainersigwald** [dotnet/msbuild#9361]
This has caused some problems with C++, when the STJ delivered by MSBuild mismatches with the one in VS/targeted by the C++ build tasks.

**Comment by yuehuang010** [comment]
The specific issue user reported VS 17.7, System.Text.Json shipped by MSBuild is 7.0.0.0.  While Microsoft.Build.CPPTasks.Common uses STJ 7.0.0.3.
A simple workaround is to modify the `<bindingRedirect />` in msbuild.exe.config.

**Comment by rainersigwald** [comment]
In VS mode, can/should we offer an app-wide assembly load fallback to the VS CommonAssemblies folder? Would that solve this?

**Comment by yuehuang010** [comment]
The issue is running MSBuild from the console.  Microsoft.Build.CPPTasks.Common is built with VS version.  I guess as long as MSBuild's STJ is same or higher than it would should work.

**Comment by yuehuang010** [comment]
Even if you can, I don't think you should.  It would make MSBuild have stronger dependency to VS.

**Comment by AR-May** [comment]
Team triage: seems not applicable anymore.
