### ISSUE TITLE
[Bug]: Solution-based graph builds don't handle a quoted target list consistent with non-graph builds

### ISSUE THREAD

**Issue by dfederm** [dotnet/msbuild#9376]
### Issue Description

When using a quoted target list (eh `/t:"Clean;Build"`), the behavior is inconsistent with non-graph builds.

> error MSB4057: The target "Clean;Build" does not exist in the project.

MSBuild itself also behaves a bit inconsistently, the that's potentially a separate bug (@rainersigwald?).

Setup:
```
mkdir QuotedTargetRepro
cd QuotedTargetRepro
dotnet new classlib
dotnet new sln
dotnet sln add .
msbuild /t:restore
```

Non-graph
* `msbuild /v:m /graph:false /t:Clean;Build QuotedTargetRepro.sln` - WORKS
* `msbuild /v:m /graph:false /t:"Clean;Build" QuotedTargetRepro.sln` - WORKS
* `msbuild /v:m /graph:false /t:Clean;Build QuotedTargetRepro.csproj` - WORKS
* `msbuild /v:m /graph:false /t:"Clean;Build" QuotedTargetRepro.csproj` - FAIL

Graph:

* `msbuild /v:m /graph /t:Clean;Build QuotedTargetRepro.sln` - WORKS
* `msbuild /v:m /graph /t:"Clean;Build" QuotedTargetRepro.sln` - FAIL <--- This bug
* `msbuild /v:m /graph /t:Clean;Build QuotedTargetRepro.csproj` - WORKS
* `msbuild /v:m /graph /t:"Clean;Build" QuotedTargetRepro.csproj` - FAIL

### Steps to Reproduce

See above

### Expected Behavior

See above

### Actual Behavior

See above

**Comment by dfederm** [comment]
Looks like this works for slns at all because in `SolutionProjectGenerator.EvaluateAndAddProjects` it just adds targets exactly as they were requested (unsplit):

```cs
                // Add any other targets specified by the user that were not already added. A target's presence or absence must be determined at the last
                // minute because whether traversalInstance.Targets.ContainsKey(i) is true or not can change during the enumeration.
                foreach (string targetName in _targetNames.Where(i => !traversalInstance.Targets.ContainsKey(i)))
                {
                    AddTraversalTargetForProject(traversalInstance, project, projectConfiguration, targetName, null, canBuildDirectly);
                }
```

So this adds the target "Clean;Build" to the sln (actually "QuotedTargetRepro:Clean;Build" due to logic in `AddTraversalTargetForProject`) which simply calls the MSBuild task using the provided targets. Since the MSBuild task ends up splitting the targets, then this is where the split occurs.

This _feels_ a bit odd and possibly a happy accident that the splitting happens in the MSBuild task.

**Comment by dfederm** [comment]
Dug into the argument parsing and it seems intentional that a quoted value be treated as a single value and not multi-value. This explains why `/t:"Clean;Build"` on a project fails.

**Comment by dfederm** [comment]
To distill down the quirkiness of sln behavior (non-graph), consider:

```xml
<Project>
  <Target Name="Build">
    <Message Text="Build" Importance="High" />
  </Target>
  <Target Name="Clean">
    <Message Text="Clean" Importance="High" />
  </Target>
  <Target Name="Clean;Build">
    <Message Text="Clean;Build" Importance="High" />
  </Target>
</Project>
```

Then:
```
>msbuild /v:m /nologo /t:Clean;Build QuotedTargetRepro.csproj

  Clean
  Build

>msbuild /v:m /nologo /t:"Clean;Build" QuotedTargetRepro.csproj

  Clean;Build

>msbuild /v:m /nologo /t:Clean;Build QuotedTargetRepro.sln

  Clean
  Build

>msbuild /v:m /nologo /t:"Clean;Build" QuotedTargetRepro.sln

  Clean
  Build
```

That last command that "should" have executed the "Clean;Build" target.

This actually begs the question, how would one be able to specify a target name with a ';' in it when using the MSBuild task at all? Perhaps ';' shouldn't be allowed in target names.

**Comment by jeffkl** [comment]
As far as I know, you have to quote the whole thing:

```
msbuild "/target:Clean;Build"
```

**Comment by dfederm** [comment]
@jeffkl Yes, that's how one should invoke it, but this bug is mostly about how graph and non-graph builds handle the other (arguably incorrect) way of doing it. Surprisingly, it works when building a sln (it being `/t:"Clean;Build"`) because of how the `<MSBuild>` task works.

For a specific example, see microsoft/Terminal (https://github.com/microsoft/terminal/blob/0289cb043c3aac0f9199f667550d8811022e9bed/tools/bcz.cmd#L21C5-L21C20 and https://github.com/microsoft/terminal/blob/0289cb043c3aac0f9199f667550d8811022e9bed/tools/bcz.cmd#L80).

The issue is actually a little complicated (somewhat my fault for muddying the waters with my rambling), but to summarize:
1. Non-graph solution builds using `/t:"Clean;Build"` work, but graph builds don't. That's the hear of this bug and what I am fixing in #9390.
2. Non-graph solution builds using `/t:"Clean;Build"` work at all. In theory, they should be executing the "Clean;Build" target on the projects in the sln, but it ends up executing "Clean" and "Build" as separate targets. This is a quirk and arguably a bug. Also arguably is whether the bug is worth fixing though since it could break people, like Terminal (see above).
3. The `<MSBuild>` task has no way to invoke targets with ';' in them. Assuming there was some defined target named "Clean;Build", it would be impossible to invoke it except via the MSBuild command-line when directly building that specific project. Furthermore, other related MSBuild mechanisms like `BeforeTarget`, `AfterTargets`, etc. also have no way of specifying a target with that name. Based on that, it seems like ';' in a target name should be considered invalid.

The first issue is the one I'm mostly concerned with since it's related to graph behavior differing from "normal" builds. The other two I'll defer to the MSBuild team :)

**Comment by rainersigwald** [comment]
> Perhaps ';' shouldn't be allowed in target names.

I am completely surprised that this was not already the case 😱

**Comment by rainersigwald** [comment]
I agree, that seems like it should be perfectly fine to specify a command line that way.
