### ISSUE TITLE
[Bug]: PropertyReassignment logged as plain messages

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/msbuild#9385]
### Issue Description

I just discovered that Property reassignment events are logged as plain messages, and not as PropertyReassignmentEventArgs:

https://github.com/dotnet/msbuild/blob/31c4d335325e858a3c4dba66d921d0e31bdee5ff/src/Build/Evaluation/Evaluator.cs#L1351-L1357

I don't know how I've missed this previously. If we log the structured event, we don't need to materialize the long string message at all.

Here's where we log the real event args, but I suspect this code is not currently enabled:
https://github.com/dotnet/msbuild/blob/31c4d335325e858a3c4dba66d921d0e31bdee5ff/src/Build/Evaluation/PropertyTrackingEvaluatorDataWrapper.cs#L294-L300

**Comment by KirillOsenkov** [comment]
Oh wow, this is where it started:
https://github.com/dotnet/msbuild/commit/21eeb45852fd1fa695416da9306b15c175f3e0af

**Comment by baronfel** [comment]
Fixing this should make it much easier to track the property assignments in the UI - @KirillOsenkov would it be possible to link a property change to the position that the change occurred (meaning both in the specific file that caused the change as well as in the overall build graph?)

**Comment by KirillOsenkov** [comment]
Note that the viewer also deduplicates the messages because they are long strings and they repeat with the same text for every project being evaluated:
https://github.com/KirillOsenkov/MSBuildStructuredLog/blob/45ba130c7f3a1c311a7ece980b2a5d3f3ada0bc1/src/StructuredLogger/BinaryLogger/BuildEventArgsReader.Viewer.cs#L64-L99

So for a binlog with a thousand projects you get a thousand copies of each of these strings unless you deduplicate. But this is on the reader side, the writer (MSBuild) doesn't need to worry about that.
