### ISSUE TITLE
[Feature Request]: Can the transitive dependencies be reduced any?

### ISSUE THREAD

**Issue by masonwheeler** [dotnet/msbuild#9389]
### Summary

The `Microsoft.Build.Utilities.Core` NuGet package is surprisingly heavyweight, dragging dozens of transitive NuGet dependencies into the project, including bizarre things like `System.Drawing.Common` and a whole host of security/permissions related things, none of which feel like they have anything to do with running a simple build script.  Is there any way that this could be cut down a bit?

### Background and Motivation

I'm trying to use ANTLR in my project.  [The ANTLR code generator](https://github.com/kaby76/Antlr4BuildTasks) uses `Microsoft.Build.Utilities.Core`, which drags 30+ other packages along for the ride, significantly slowing down the CI build machine, because there are a lot of projects that depend on this project and so *all* of them get entire this transitive dependency set pulled in.  Why in the world should I need all of that baggage just to build a parser?

### Proposed Feature

Would it be possible to examine the dependencies and see if there are any outdated references that can be trimmed?  We all know how projects that have been around for a while tend to accumulate cruft, afterall...

**Comment by masonwheeler** [comment]
[Also asked the ANTLR code generator project if MSBuild is truly necessary for a code generator.](https://github.com/kaby76/Antlr4BuildTasks/issues/69)

**Comment by rainersigwald** [comment]
`System.Drawing.Common` has been removed for 17.8 by #9055.

> a whole host of security/permissions related things, none of which feel like they have anything to do with running a simple build script.

Unfortunately, many of them _do_ because build scripts are not reliably that simple. If you have any other specific ones to call out we can look at the nature of the dependency.

**Comment by rainersigwald** [comment]
> I'm trying to use ANTLR in my project. [The ANTLR code generator](https://github.com/kaby76/Antlr4BuildTasks) uses `Microsoft.Build.Utilities.Core`, which drags 30+ other packages along for the ride, significantly slowing down the CI build machine, because there are a lot of projects that depend on this project and so _all_ of them get entire this transitive dependency set pulled in.

I agree with @KalleOlaviNiemitalo that the Antlr4BuildTasks package appears to be overselling its dependencies. You can work around this in your projects by minimizing the reference though, like

```diff
- <PackageReference Include="Antlr4BuildTasks" Version="12.4.0" />
+ <PackageReference Include="Antlr4BuildTasks" Version="12.4.0" PrivateAssets="all" IncludeAssets="build" />
```

**Comment by rainersigwald** [comment]
@KalleOlaviNiemitalo 

> * [bundle dependencies into the package](https://learn.microsoft.com/en-us/visualstudio/msbuild/tutorial-custom-task-code-generation?view=vs-2022#bundle-dependencies-into-the-package) so that System.Buffers, System.Memory, and System.Text.Encoding.CodePages can be loaded at build time even if MSBuild does not depend on the same versions

I think we provide all of those on all platforms (though bundling them would be basically harmless).

**Comment by rainersigwald** [comment]
@KalleOlaviNiemitalo mind copying your (excellent) analysis over into https://github.com/kaby76/Antlr4BuildTasks/issues/69?

**Comment by rainersigwald** [comment]
> It would depend on the version of MSBuild, right? If a project referencing Antlr4BuildTasks is built in Visual Studio 2017, then the appdomain might have some version of System.Text.Encoding.CodePages loaded, but surely not version 7.0.0.0.

Good point, that's very true.

**Comment by masonwheeler** [comment]
> `System.Drawing.Common` has been removed for 17.8 by #9055.

Cool!  Any idea when we can expect to see it in NuGet?

> I agree with @KalleOlaviNiemitalo that the Antlr4BuildTasks package appears to be overselling its dependencies. You can work around this in your projects by minimizing the reference though, like
> 
> ```diff
> - <PackageReference Include="Antlr4BuildTasks" Version="12.4.0" />
> + <PackageReference Include="Antlr4BuildTasks" Version="12.4.0" PrivateAssets="all" IncludeAssets="build" />
> ```
> 
> Where `PrivateAssets` means "don't flow to projects that reference me" and `IncludeAssets="Build"` means "only use the build logic from this package, don't reference its library".

Thanks!  That looks very helpful.  I recall seeing something similar added to the csproj by Sam Harwell's old, outdated version of the ANTLR code generator, but I didn't know what it did.  This updated version doesn't put that in automatically, though.

**Comment by rainersigwald** [comment]
> Cool! Any idea when we can expect to see it in NuGet?

It will release with .NET 8.0 and Visual Studio 17.8 soon.

**Comment by masonwheeler** [comment]
All right, and adding those attributes fixes the issue of dragging all those dependencies into all the downstream projects, so I'm good for now.
