### ISSUE TITLE
[Bug]: Switching between branches with PackageReference and packages.config breaks build

### ISSUE THREAD

**Issue by labsin** [dotnet/msbuild#9397]
### Issue Description

I have a .net framework application targeting v4.7.2. I recently migrated from packages.config to PackageReferences and started targetting .net framework V4.8

I sometimes have to switch to an older branch to do customer hotfixes etc.

### Steps to Reproduce

[NugetMigrationTest.zip](https://github.com/dotnet/msbuild/files/13266864/NugetMigrationTest.zip)

```
git init .
git add -A
git commit -m "first commit"
REM Build before migration
MSBuild.exe .\NugetTest.sln /t:restore /p:RestorePackagesConfig=true
MSBuild.exe .\NugetTest.sln /t:build

REM Build after migration
git apply NugetMigrationTest_migration_patch.diff
MSBuild.exe .\NugetTest.sln /t:clean
MSBuild.exe .\NugetTest.sln /t:restore
MSBuild.exe .\NugetTest.sln /t:build

REM Build again before migration
git reset --hard
MSBuild.exe .\NugetTest.sln /t:clean
MSBuild.exe .\NugetTest.sln /t:restore /p:RestorePackagesConfig=true
MSBuild.exe .\NugetTest.sln /t:build
```

### Expected Behavior

Clean should all artifacts and correctly build for 4.7.2 with packages.config

### Actual Behavior

After migration builds correctly, but after resetting back, following error is thrown:

> C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\NuGet\17.0\Microsoft.NuGet.targets(198,5): error : Your project does not reference ".NETFramework,Version=v4.7.2" framework. Add a reference to ".N
> ETFramework,Version=v4.7.2" in the "TargetFrameworks" property of your project file and then re-run NuGet restore.

### Analysis

It seems to be related to obj\project.assets.json
If I remove that file, the error is no longer thrown.

### Versions & Configurations

MSBuild version 17.7.2+d6990bcfa for .NET Framework
17.7.2.37605

**Comment by rainersigwald** [comment]
This is by design on the NuGet side: https://github.com/NuGet/Home/issues/4476.
