### ISSUE TITLE
Add a reminder/nag feature to run VS Perf DDRITs when deployed assemblies change

### ISSUE THREAD

**Issue by rainersigwald** [dotnet/msbuild#9425]
It should be pretty easy to write automation to double-check that we run perf ddrits early when we change the assemblies we ship with (or the .swr in general).

**Comment by JanKrivanek** [comment]
As agreed on triage meeting - the 'resourceManagement policy' check should suffice here.

Similarly as we check PRs to release branches and post comment: https://github.com/dotnet/msbuild/blob/main/.github/policies/resourceManagement.yml#L119-L154

**Comment by JaynieBai** [comment]
@rainersigwald When should we run the perf ddrits as early as possible?  Is it in the msbuild PR when PR author updates the *.swr file?
Should we run all the tests or some specified tests from MSBuild-OpfProf?

**Comment by rainersigwald** [comment]
Ideally, any change to the `.swr` would require an `exp/` insertion before the PR was merged. It's hard to actually _require_ it but I think that should be the trigger for the reminder.
