### ISSUE TITLE
GetCopyToOutputDirectoryItems says it doesn't work for transitive P2P references

### ISSUE THREAD

**Issue by eerhardt** [dotnet/msbuild#943]
See the comment here:
https://github.com/Microsoft/msbuild/blob/f71174cc2a9d025ee3d78cad63dd4f9c8cef5116/src/XMakeTasks/Microsoft.Common.CurrentVersion.targets#L4010-L4023

The comment says

```
It would appear that this target computes full transitive closure of content items 
for all referenced projects; however that is not the case.
It only collects the content items from its immediate children and not children of children.
```

If this is true, we should fix this behavior so all transitive P2P references get their items copied.  If it isn't true, then we should update the comment to be correct.

/cc @brthor @rainersigwald

**Comment by japj** [comment]
@rainersigwald is #1845 a specific scenario where GetCopyToOutputDirectoryItems might not work correctly for P2P references?

I also see (wrong?) behaviour with "default" test projects (file new .netframework classlib):
- classlib1
- classlib2 ProjectReference to classlib1 (no actual code use of classlib1)
- classlib3 ProjectReference to classlib2

Actual output folder of classlib3 after building:
- contains classlib2.dll and classlib3.dll, but not classlib1.dll
- if I have "CopyToOutputDirectory Always" Content in the classlib1 project then that IS actually copied to classlib3 output folder (even though the classlib1.dll is not)

**Comment by BenVillalobos** [comment]
Adding this to the 17.0 milestone to update the description. As of 17.0 we're defaulting to copying content items transitively.
