### ISSUE TITLE
[Bug]: Building test project with only one framework causes NU1701 warning on different one

### ISSUE THREAD

**Issue by msmolka** [dotnet/msbuild#9432]
### Issue Description

I have simple test project: See attached file
it is multi target with one eol .dotnet version 5

```xml
<TargetFrameworks>net8.0;net462;net5.0</TargetFrameworks>
```

I've added package:

```xml
    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.TimeProvider.Testing" Version="8.0.0" />
    </ItemGroup>
```

now building project reports warning on ALL 3 target versions. If I remove .net5 - all is correct
if I add it reports warning

even running simple command with forcing build only for .net 8 produces nu1701 warning.

`
dotnet build --framework net8.0 --no-restore
`

[TestMultiTarget.zip](https://github.com/dotnet/msbuild/files/13388533/TestMultiTarget.zip)

### Steps to Reproduce

Run attached repo with framework 8

`
dotnet build --framework net8.0 --no-restore
`

### Expected Behavior

Warning only appears when building target framework 5 not any other supported ones.

### Actual Behavior

Warning is produced even for supported frameworks:

```
warning NU1701: Package 'Microsoft.Extensions.TimeProvider.Testing 8.0.0' was restored using '.NETF 
ramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8, .NETFramework,Version=v4.8.1' instead of the project tar 
get framework 'net5.0'. This package may not be fully compatible with your project. [TargetFramework=net8.0]

```

**Comment by GangWang01** [comment]
The frameworks supported by the package `Microsoft.Extensions.TimeProvider.Testing 8.0.0` are net6.0, net8.0 and net462. 

At the first time building `dotnet build --framework net8.0`, nuget restore task restores for all three target frameworks including net5.0 which is not supported by the package. Nuget restore task logs the warning NU1701 for net5.0 and adds this log message into obj\project.assets.json.
Then `ResolvePackageAssets` task(https://github.com/dotnet/sdk/blob/main/src/Tasks/Microsoft.NET.Build.Tasks/ResolvePackageAssets.cs) in the building creates obj\Debug\net8.0\TestMultiTarget.assets.cache from the info of obj\project.assets.json including the log message without filtering out matched target framework. It also reads the assets.cache file and outputs the log message even if building other supported frameworks without restore `dotnet build --framework net8.0 --no-restore`.

There are two problems.

1. Nuget restore task restores for all target frameworks specified in the project when build command points out the framework. I'm not sure if this is expected.
2. `ResolvePackageAssets` task writes assets.cache file without filtering out log messages matching the target framework. https://github.com/dotnet/sdk/blob/e80b07ab62f322e8adef5d32bae2026a2a2bd813/src/Tasks/Microsoft.NET.Build.Tasks/ResolvePackageAssets.cs#L1250 should filter out the log messages to resolve this problem.

**Comment by AR-May** [comment]
Team Triage: problem 1 seems to belong to NuGet. Problem 2 we do not think is relevant. We will transfer this issue to NuGet repository.

**Comment by AR-May** [comment]
This issue was moved to NuGet/Home#13048
