### ISSUE TITLE
[Broken Build]: Fresh checkout and attempting to debug ProjectCachePlugin functionality results in errors

### ISSUE THREAD

**Issue by Cjewett** [dotnet/msbuild#9441]
### Issue Description

Hi all,

Apologies if I missed documentation explaining this. I'm attempting to set up my local machine to be able to debug MSBuild better. I started with Building MSBuild with Visual Studio 2022 on Windows. That worked fine so I then followed the Using the repository binaries to perform builds instructions to step into the code. That is also working fine. I then created a new project called TestCachePlugin that includes the following ItemGroup: 
```
<ItemGroup>
  <ProjectCachePlugin Include="C:\Github\msbuild\artifacts\bin\Samples\ProjectCachePlugin\Debug\net8.0\ProjectCachePlugin.dll" />
</ItemGroup>
```

When using the net472 artifacts I wasn't seeing the log messages from the plugin being output. I assumed it might have been due to needing to use the net8.0 artifacts, so I started to follow the Building, Testing, and Debugging on .NET Core MSBuild. I run into a bunch of errors though. 

When I run `build.cmd -msbuildEngine dotnet` I get errors like the below:
`error MSB3245: Could not resolve this reference. Could not locate the assembly "mscorlib". Check to make sure the assembly exists on disk.`

Good news I do see the ProjectCachePlugin log messages I include TestCachePlugin in the solution though.

If I run `dotnet ./artifacts/bin/bootstrap/net8.0/MSBuild/MSBuild.dll ./src/Samples/TestCachePlugin/TestCachePlugin.csproj` I get `error NETSDK1127: The targeting pack Microsoft.NETCore.App is not installed. Please restore and try again. [C:\Github\msbuild\src\Samples\TestCachePlugin\TestCachePlugin.csproj]`

Anyone have guidance on how to resolve these issues?

I'm porting this over from an MSBuild comment so I did truncate the error logs. The version being used is the one set in global.json and at the time of testing it was `8.0.100-rc.1.23463.5`. 

### Steps to Reproduce

This is a pull request with the changes I've made. https://github.com/Cjewett/msbuild/pull/1/files
For the most part I didn't change anything about the repository and I've tested this while removing the example project from the solution as well just to confirm repository in its fresh state was working. 

### Expected Behavior

Running `build.cmd -msbuildEngine dotnet` should succeed and breakpoints should be hit. 
Running ``dotnet ./artifacts/bin/bootstrap/net8.0/MSBuild/MSBuild.dll ./src/Samples/TestCachePlugin/TestCachePlugin.csproj` should succeed and breakpoints should be hit. 

### Actual Behavior

Receive errors related to missing assemblies and targeting packs not being installed.

**Comment by dfederm** [comment]
@AR-May This doesn't appear to be related to project caching. I get the same thing if I do this in `main`:

```
dotnet ./artifacts/bin/bootstrap/net8.0/MSBuild/MSBuild.dll ./src/Samples/Dependency/Dependency.csproj
```

That being said @Cjewett , if you add `-restore` to your command you should see success.
