### ISSUE TITLE
Investigate and categorize existing MSBuild analyzing logic - Suggested rules

### ISSUE THREAD

**Issue by JanKrivanek** [dotnet/msbuild#9460]
### Input

* Suggested rules: [[Internal link] potential analyzer ideas](https://microsoft.sharepoint.com/:o:/t/DotNetTeam/EtSEoqLsusZNt0gLT0rGHS0BZ9ypO0Ad94TiqQLtnHEGNA?e=VzUqkM)

### Expected output

* List of categories of rules (with possible different dimensions of categorization - required input types; repo/project specific vs universal; phase of build when those can run (evaluation, build, postbuild); level of complexity of the rule; etc.)
* Notable examples of rules per category
* [optional] indication of candidates for intial spiking (rules that are universaly applicable, with low leve of complexity)

**Comment by JanKrivanek** [comment]
Split by half:
 - top till static graph rule - Yuliia
 - rest - Jan

**Comment by YuliiaKovalova** [comment]
What happens on evaluation sequentially:

1. Loading and Parsing
MSBuild loads and parses the project file( reads the XML & builds an internal representation of nodes)

2. Property and Item Evaluation
Properties are values that can be referenced throughout the project file, and items are sets of related items (files, references, etc.). 

3. Importing and Expanding Imports:
Processes <Import> elements, bringing in additional project files. 

4. Condition Evaluation:
Evaluates conditions associated with various elements in the project file, such as targets, tasks, properties, and items.

5. Target Graph Construction:
This graph represents the order in which targets should be executed. 

It looks like that we need to track the origin for some inputs for targets/tasks.
