### ISSUE TITLE
[Bug]: class MSBuildGlob should expose GlobRoot and FileSpec as public properties

### ISSUE THREAD

**Issue by adrianvmsft** [dotnet/msbuild#9463]
### Issue Description

The project system evaluation cache serializes glob information into the evaluation cache and reconstructs the globs when loading the data.
However, the GlobRoot and FileSpec properties are not available as public properties which prevents a proper reconstruction of the glob objects when loading the cache.

https://github.com/dotnet/msbuild/blob/main/src/Build/Globbing/MSBuildGlob.cs

They are currently exposed as 2 internal properties:
```CSharp
        internal string TestOnlyGlobRoot => _state.Value.GlobRoot;
        internal string TestOnlyFileSpec => _state.Value.FileSpec;
```
However that has a few issues:
- the 2 properties are internal instead of public
- The property name contains "Test"
- Calling the 2 properties would trigger the lazy calculation, which can be avoided because the 2 values are known from the beginning

The 2 properties should be exposed on the class itself and be removed from GlobState struct so that they don't require the Lazy calculation and also don't duplicate the data.

### Steps to Reproduce

This is API only

### Expected Behavior

```CSharp
        internal string GlobRoot { get; }
        internal string FileSpec { get; }
```

### Actual Behavior

```CSharp
        internal string TestOnlyGlobRoot => _state.Value.GlobRoot;
        internal string TestOnlyFileSpec => _state.Value.FileSpec;
```

**Comment by AR-May** [comment]
Team triage: @adrianvmsft are you interested in implementing this feature?
