### ISSUE TITLE
File in use by another application during build

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/msbuild#9465]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/File-in-use-by-another-application-durin/10516653)._

---
[severity:It's more difficult to complete my work]
Sometimes a Visual Studio build will fail because a file that it created is "in use by another application". The only remedy is to wait. I often have to wait 1 - 2 minutes before attempting another build. VS evidently holds onto files for a very long time past the end of the build process. Holding onto that file causes the VS build process to fail next time. VS will success in building if I wait 1 - 2 minutes.

---
#### Feedback Bot on 11/16/2023, 04:02 AM: 

(private comment, text removed)
#### Ray White on 11/22/2023, 04:25 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by AR-May** [comment]
Team triage: we need the error message to indicate which process exactly hold the lock for the file.

**Comment by rainersigwald** [comment]
The specific error seen in this case is `GenerateManifest.WriteOutputManifestFailed`

https://github.com/dotnet/msbuild/blob/5fcddc790f4eeaf953a3d283e39751dd0e1f2992/src/Tasks/GenerateManifestBase.cs#L622

That should be augmented to use something similar to the Copy task's "name the process that holds the lock" approach (probably by extracting that to a common location).

https://github.com/dotnet/msbuild/blob/5fcddc790f4eeaf953a3d283e39751dd0e1f2992/src/Tasks/Copy.cs#L926C31-L926C51

**Comment by dovkoy** [comment]
On 2/14/2024, OP shared his solution:
> I believe another process like Carbonite backup might be causing this. An external app may have locked these files, which cause builds to fail. I have no direct proof of this, but that’s my “gut feeling” on the matter. I have marked this as a “Solution” until I prove otherwise. Only time will tell.

I experienced the same issue and was able to fix it only by moving the project outside of my synced directory with Google Drive. Seems, in my case, Google Drive app (desktop) was the culprit.
