### ISSUE TITLE
[Bug]: Regression of issue 8274 in .net8

### ISSUE THREAD

**Issue by Larhei** [dotnet/msbuild#9471]
### Issue Description

Link in this [issue](https://github.com/dotnet/msbuild/issues/8274)

When building a project with RoslynCodeTaskFactory from Visual Studio for Mac (Version 17.6.7), it report the following error.
`Error MSB4175: The task factory "RoslynCodeTaskFactory" could not be loaded from the assembly "/usr/local/share/dotnet/sdk/8.0.100/Microsoft.Build.Tasks.Core.dll". Could not load file or assembly 'System.CodeDom, Version=7.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. Could not find or load a specific file. (0x80131621) (MSB4175)`

found it

![image](https://github.com/dotnet/msbuild/assets/47631685/45a74e84-eec9-4372-af24-f71af1ffe26e)

Why does .netssdk 8.0.100 ref .net7 assemblies? there is a version 8 of System.Codedome in my .net8.0.100 sdk folder?

### Steps to Reproduce

See issue 8274

### Expected Behavior

RoslynCodeTaskFactory references .net8 assemblies

### Actual Behavior

It is not referencing .net8 assemblies. It´s using .net 7 assemblies that are not in the sdk folder.

**Comment by Larhei** [comment]
Workaround for me

Copy System.CodeDom.dll from /usr/local/share/dotnet/sdk/7.0.401/ into /usr/local/share/dotnet/sdk/8.0.100

solved it for me

**Comment by AR-May** [comment]
Team triage: it seems like .net 8 is not supported in VS for Mac. You can file a [feedback issue](https://developercommunity.visualstudio.com/VisualStudioMac) for VS for Mac about that.

You might also try to use VS Code with C# dev kit for Visual Studio Code.

**Comment by Larhei** [comment]
This has nothing to do with VS Code or VS4mac.... It is SDK related. Dotnet SDK 8.0.100 is pointing to dlls from Dotnet SDK 7.x.

**Comment by rainersigwald** [comment]
@Larhei it is doing so in a way that works fine in the .NET (core) runtime environment, so this is a VSMac problem.

**Comment by awattar** [comment]
We are also facing this issue. @Larhei would you re/open this issue for VSMac?

**Comment by Larhei** [comment]
did it already. 

[here](https://developercommunity.visualstudio.com/t/Error-MSB4175:-The-task-factory-RoslynC/10534035)
