### ISSUE TITLE
[Bug]: -version message doesn't have a line ending

### ISSUE THREAD

**Issue by jrdodds** [dotnet/msbuild#9482]
### Issue Description

The -version switch displays the version number but doesn't include a line ending.

With Windows cmd and with PowerShell, this doesn't matter. The line is ended and the next prompt is shown on a new line.

But it shows up on macOS and Linux in a shell other than pwsh.

This is a bit of a nit but it is also a bit ugly and low effort to fix.

### Steps to Reproduce

On macOS or Linux in a standard shell run the following command:

```
dotnet msbuild --version -nologo
```

### Expected Behavior

Expected behavior is no artifacts and the next prompt is on a new line.

An example for the bash shell:

```
$ dotnet msbuild --version -nologo
17.8.3.51904
$
```

zsh should be the same, except the default zsh prompt is `%`.

### Actual Behavior

In bash on Ubuntu in WSL in Windows Terminal, the `$` command prompt for the next command is on the same line as the version output.

```
$ dotnet msbuild --version -nologo
17.8.3.51904$
```

![Screenshot Linux bash](https://github.com/dotnet/msbuild/assets/1728516/53f23fea-bea2-4b2f-8d50-c1e2c27f783c)

In zsh on macOS in Terminal, an inverse+bold `%` is displayed at the end of the version output (which is a zsh feature to show a partial line).

```
% dotnet msbuild --version -nologo
17.8.3.51904%
%
```

<img width="1135" alt="Screenshot macOS zsh" src="https://github.com/dotnet/msbuild/assets/1728516/aafc795c-ec08-4aa3-bb5a-1daadc8d030c">

### Analysis

In the `MSBuildApp` class, the -version switch is mapped to a call to the `ShowVersion()` method.

https://github.com/dotnet/msbuild/blob/d8283be045c16620c3e2ae3bfe33367257c3b4f3/src/MSBuild/XMake.cs#L2497-L2502

https://github.com/dotnet/msbuild/blob/d8283be045c16620c3e2ae3bfe33367257c3b4f3/src/MSBuild/XMake.cs#L4488-L4494

Currently this is the only usage of `ShowVersion()`. The `Write` could be changed to a `Writeln`.

**Comment by baronfel** [comment]
Thanks for the detailed analysis - that makes this one of the easiest "yes I agree, would you care to send a PR?" responses I have ever sent.

Having said that - yes, I agree, would you care to send a PR?

**Comment by jrdodds** [comment]
Yes. I will send a PR. :thumbsup:
Thanks

**Comment by baronfel** [comment]
Closing this as we merged the linked PR. Thanks again for your investigation and fix, @jrdodds!
