### ISSUE TITLE
Cases of broken links in Error Window

### ISSUE THREAD

**Issue by JanKrivanek** [dotnet/msbuild#9487]
### Context

VS Error Window creating the link based on our help keywoard seems to be broken in some cases:

<img width="355" alt="image" src="https://github.com/dotnet/msbuild/assets/3809076/fc59e6a3-1105-4ff4-8e33-2ef5beb5931d">

links:
 * https://learn.microsoft.com/en-us/visualstudio/ide/not-in-toc/default?view=vs-2022&f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(MSBuild.CannotModifyReservedProperty)%26rd%3Dtrue
 * https://learn.microsoft.com/en-us/visualstudio/ide/not-in-toc/default?view=vs-2022&f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(MSBuild.IncludeRemoveOrUpdate)%26rd%3Dtrue

Both leading to  `Oops! No F1 help match was found`

### Repro steps

Put a PropertyGroup inside ItemGroup and vice versa and build in VS

```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <ItemGroup />
  </PropertyGroup>

  <ItemGroup>
    <PropertyGroup />
  </ItemGroup>
</Project>
```

### Additional info

I'm not sure if this is a regression or if the links with 'help keyword' ever worked. However the errors have a good landing pages that would be nice to returned. We might need to get together with the team maintaining the links experience about what are the expectations on errors returned by us (as sdk or nuget errors that lead to proper landing page, have their errorcode inside the search term argument in the url)

**Comment by baronfel** [comment]
cc @ghogen here - I'm pretty sure that not all errors have help pages, right? And the point of the help links is to help track the usage of these links to prioritize creating and updating content?

If so, I don't think there's an all-up problem here - just a task list that we could help burn down.

**Comment by JanKrivanek** [comment]
Ah I see - that makes good sense
