### ISSUE TITLE
Upgrade to .NET 9 SDK 

### ISSUE THREAD

**Issue by mthalman** [dotnet/msbuild#9492]
This repo should be targeting the .NET 9 SDK from the global.json file. This is a requirement necessary for .NET source build in order to target the `net9.0` TFM.

Related to https://github.com/dotnet/source-build/issues/3770

**Comment by rainersigwald** [comment]
I do not think we can accept this requirement. We will ship in .NET 8 SDKs for almost a year before moving to .NET 9. It's certainly a surprise to me.

**Comment by mthalman** [comment]
> I do not think we can accept this requirement. We will ship in .NET 8 SDKs for almost a year before moving to .NET 9. It's certainly a surprise to me.

Ok. What is your intention on taking Arcade updates? I ask because https://github.com/dotnet/arcade/pull/14108 would break things if you don't have a new SDK. Would you just work around the `NetCurrent` update?

**Comment by rainersigwald** [comment]
I was planning to stay on Arcade 8 until the VS/MSBuild release that supports .NET 9.

**Comment by mthalman** [comment]
Ok, that works. I'll close this then.

**Comment by ViktorHofer** [comment]
Note that when building inside the VMR, we will likely require a common toolset version (SDK + Arcade.Sdk). That will mean that msbuild would use a .NET 9 SDK and a 9.0 Arcade.Sdk. I think that's already the case for source build today.

cc @mmitche @MichaelSimons
