### ISSUE TITLE
ProjectImportedEventArgs missing from most projects

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/msbuild#9501]
@tmat has sent me a binlog from "17.9.0-preview-23570-02+bf9d6d46d"
D:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Current\Bin\amd64\MSBuild.exe

It's missing ProjectImported events for all but a handful of projects:

Build.proj  id:51
Microsoft.CodeAnalysis.CSharp.Features.UnitTests.csproj net472 id:10601
Microsoft.CodeAnalysis.ExternalAccess.Copilot.csproj net472;net6.0 id:10501
Microsoft.CodeAnalysis.ExternalAccess.Copilot.csproj net472 id:10551
Roslyn.sln.metaproj v4.0 id:101
Roslyn.VisualStudio.Setup.csproj net472 id:2501

Ping me on teams and I can share the binlog internally.

**Comment by KirillOsenkov** [comment]
The binlog contains only about 1,200 import events, only for those 6 projects:

![image](https://github.com/dotnet/msbuild/assets/679326/c0260375-7999-453b-a1c5-4ddfb251e428)

Could it be that the ProjectImportedEventArgs are no longer sent across other node processes? Could this have regressed recently?

**Comment by JanKrivanek** [comment]
Might the `MSBUILDLOGIMPORTS` env var be fiddled with in your env @tmat?

**Comment by KirillOsenkov** [comment]
The binlog should contain it if so?

**Comment by KirillOsenkov** [comment]
and some imports were logged

**Comment by tmat** [comment]
> Might the `MSBUILDLOGIMPORTS` env var be fiddled with in your env @tmat?

Not that I am aware of.

**Comment by JanKrivanek** [comment]
It was just a wild quick quess.

For some reason calls emiting `ProjectImportedEventArgs` are conddition via few various conditions - just about half of those check the trait that wraps that env var - so flipping it would filter only some. But unless the env var would be accessed as property it would not be dumped into binlog.

Anyways - Alina is currently having few leads for next investigation steps, so please ignore my intervention here :-)

**Comment by KirillOsenkov** [comment]
No problem! I think we always log environment variables that start with MSBUILD, DOTNET and a third prefix that I don't remember.

Good idea, if the other nodes don't set the env then it might not happen there! I think it's a regression but I might be wrong (if it's always been broken then I'll be very surprised about how come we've missed this all this time)

**Comment by JanKrivanek** [comment]
Ah - didn't know about the logging of MSBUILD*,DOTNET* env vars - thanks for learning me something new today! :-)

Building with `$env:MSBUILDNOINPROCNODE=1` leads to no project imports being logged
Building with `/m:1` leads to all project imports being logged.

So I believe the [`Trait`](https://github.com/dotnet/msbuild/blob/abc2f4620f6749289cafeed7c9a9a80eaeb38e28/src/Framework/Traits.cs#L211) is the culprit here.

Regression or not - it's still worth fixing. I'd just like us to invest slightly more and introduce general way of communicating state (env, subscriptions, etc.) from main node to others - this way we wouldn't need to transmit (and ideally not even emit) events if there are no subscriber.

As a workaround - setting the trait globally (`SETX MSBUILDLOGIMPORTS "1"`) should do the trick (FYI @tmat)

**Comment by KirillOsenkov** [comment]
I'm not seeing ProjectImportedEventArgs in this list:
https://github.com/dotnet/msbuild/pull/8917/files#diff-49f60fe36c5743a0285e9d27ce7c6e981d8dc73de8bfa23405a9fdbd2cf69eddR75

Could it be that removing binary formatter impacted serialization of ProjectImportedEventArgs in node packet translator?

@rokonec

**Comment by KirillOsenkov** [comment]
As part of this issue let's verify that all node types mentioned here are being serialized properly:
https://github.com/dotnet/msbuild/blob/abc2f4620f6749289cafeed7c9a9a80eaeb38e28/src/Build/Logging/BinaryLogger/BuildEventArgsWriter.cs#L152C21-L152C21

**Comment by JanKrivanek** [comment]
> As part of this issue let's verify that all node types mentioned here are being serialized properly: https://github.com/dotnet/msbuild/blob/abc2f4620f6749289cafeed7c9a9a80eaeb38e28/src/Build/Logging/BinaryLogger/BuildEventArgsWriter.cs#L152C21-L152C21

Btw. to make sure there are no BuildEventArgs left of off the roundtrip test (even in future) - we can easily enumerate all BuildEventArgs inheritors from the Microsoft.Build assembly. Similarly as we test the BuildException types serialization here: https://github.com/dotnet/msbuild/blob/main/src/Build.UnitTests/BackEnd/BinaryTranslator_Tests.cs#L247-L258

**Comment by KirillOsenkov** [comment]
Hey folks, any progress on this issue? A bit worried that we have incomplete information in the binlogs and it could be misleading and make investigations harder.

**Comment by JanKrivanek** [comment]
@AR-May is on it - just currently OOF this week

**Comment by KirillOsenkov** [comment]
ah ok, no rush

**Comment by AR-May** [comment]
> Ah - didn't know about the logging of MSBUILD*,DOTNET* env vars - thanks for learning me something new today! :-)
> 
> Building with `/m:1` leads to all project imports being logged. Building with `$env:MSBUILDNOINPROCNODE=1` leads to no project imports being logged Ordinary cases of building are somewhere in between (depending if/how much evaluations occured on extra nodes)
> 
> <img alt="image" width="611" src="https://private-user-images.githubusercontent.com/3809076/291007166-68df11d6-8290-410e-b897-e215d3b083ae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzOTk1MjYsIm5iZiI6MTcwNTM5OTIyNiwicGF0aCI6Ii8zODA5MDc2LzI5MTAwNzE2Ni02OGRmMTFkNi04MjkwLTQxMGUtYjg5Ny1lMjE1ZDNiMDgzYWUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTZUMTAwMDI2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZmI5N2ZhZmEyMDQ5MTMxNTAyYzMzZDEyYjdmODM5NjllYjRhZjkxZWM5NGI1ODg5ZTI5YThhYTM1M2IwNjA0YSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.4YLbqs8QUh1uouMC0cyK2UaHA8hxrwwul3e9PASQV1c">
> vs
> 
> <img alt="image" width="608" src="https://private-user-images.githubusercontent.com/3809076/291007077-8ec18c45-4656-4e80-9e0d-013db9ee078d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzOTk1MjYsIm5iZiI6MTcwNTM5OTIyNiwicGF0aCI6Ii8zODA5MDc2LzI5MTAwNzA3Ny04ZWMxOGM0NS00NjU2LTRlODAtOWUwZC0wMTNkYjllZTA3OGQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTZUMTAwMDI2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmQ3Y2I4NjNiYzVlZGM5MDBhOThlNTAwZDIyN2E5M2IyMTUwZWE4NmU2OTMyOGMwZjhkOTc4NzcwNjIwNTg2YSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.0WjXmccI7aLyP3CDiRmryotelzr7uu5axh4QHEDl8Wc">
> So I believe the [`Trait`](https://github.com/dotnet/msbuild/blob/abc2f4620f6749289cafeed7c9a9a80eaeb38e28/src/Framework/Traits.cs#L211) is the culprit here.
> 
> Regression or not - it's still worth fixing. I'd just like us to invest slightly more and introduce general way of communicating state (env, subscriptions, etc.) from main node to others - this way we wouldn't need to transmit (and ideally not even emit) events if there are no subscriber.
> 
> As a workaround - setting the trait globally (`SETX MSBUILDLOGIMPORTS "1"`) should do the trick (FYI @tmat)

I agree, I managed to reproduce and debug the issue and I also believe the `Trait` class poses a problem, moreover, there should be a problem with any behavior that is controlled via environment variable that goes to `Trait` class (which is a lot). What happens is that the msbuild nodes get the `Trait` class created during the msbuild node creation and it is filled according to the env. variables on the initial build. So, when the new build reuses the old nodes, the main node sends the new configuration, including the environment variables, the old msbuild node sets these variables, but the values in the `Trait` class are not updated accordingly. 

In the case of this issue, the `MSBUILDLOGIMPORTS` variable gets the new value that is not propagated to Traits.
