### ISSUE TITLE
[Bug]: /graph builds succeed when there is not target in project file

### ISSUE THREAD

**Issue by maridematte** [dotnet/msbuild#9502]
### Issue Description

When the project file has no target and no type of build (no `sdk=...` or anything else) and you try to build it fails with `error MSB4040: There is no target in the project.` which is expected. If you try to build the same project but with the `/graph` argument the build succeeds.

This is true with `dotnet build` and with `MSBuild.exe` from VS 2022.

### Steps to Reproduce

1. Create a new console app (dotnet new console)
2. From the project file, delete the `sdk` definition in `<Project>`
3. Try to build the project with `/graph` option

### Expected Behavior

Build fails with `error MSB4040: There is no target in the project.`

### Actual Behavior

Builds says it succeeded when it did not.

**Comment by AR-May** [comment]
Team triage: @dfederm What do you think about the priority of this bug?

**Comment by dfederm** [comment]
I don't think the priority is that high.

I can look into it though.
