### ISSUE TITLE
[Bug]: ignoreProjectExtensions flag doesn't work when specified from an RSP file

### ISSUE THREAD

**Issue by AndyGerlicher** [dotnet/msbuild#9507]
### Issue Description

Looks like ignoreProjectExtensions is used before reading the rsp file, so it can only come from command line args.

https://github.com/dotnet/msbuild/blob/f914c9bfb613d32edb658b803c7fe046f9ee3c37/src/MSBuild/XMake.cs#L2918

### Steps to Reproduce

Create a `.sln` and `dirs.proj` in the same folder. Add `-ignoreProjectExtensions:.sln` to your `Directory.Build.rsp` file.

### Expected Behavior

```
F:\src\repo>msbuild.exe -ignoreProjectExtensions:.sln
MSBuild version 17.8.3+195e7f5a3 for .NET Framework
Restore complete (2.0s)
  F:\src\repo\dirs.proj Restore (2.0s)
...
```

### Actual Behavior

```
F:\src\repo>msbuild.exe
MSBuild version 17.8.3+195e7f5a3 for .NET Framework
MSBUILD : error MSB1011: Specify which project or solution file to use because this folder contains more than one project or solution file.
```

**Comment by f-alizada** [comment]
@AndyGerlicher thank you for reporting the bug and repro steps. We are going to work on the fix :)
