### ISSUE TITLE
[Bug]: MSBuild should not embed project extensions during restore

### ISSUE THREAD

**Issue by jeffkl** [dotnet/msbuild#9512]
### Issue Description

During restore, any generated file in `$(MSBuildProjectExtensionsPath)` is imported [here](https://github.com/dotnet/msbuild/blob/f914c9bfb613d32edb658b803c7fe046f9ee3c37/src/Tasks/Microsoft.Common.props#L66) and [here](https://github.com/dotnet/msbuild/blob/f914c9bfb613d32edb658b803c7fe046f9ee3c37/src/Tasks/Microsoft.Common.targets#L35).  Imports are automatically embedded in the binary log but in the case of these files, they are generated by the restore gesture.  

When a user specifies `/Target:Restore` or `/Restore`, MSBuild launches a build invocation of the Restore target with a special global property [MSBuildRestoreSessionId](https://github.com/dotnet/msbuild/blob/f914c9bfb613d32edb658b803c7fe046f9ee3c37/src/MSBuild/XMake.cs#L1773).  It should also set `ImportProjectExtensionProps` and `ImportProjectExtensionTargets` to false to skip the import of any project extension during restore.  This would only break users who are doing the following:

1. Invoke some custom build target that generates files in `$(MSBuildProjectExtensionsPath)`
2. Invoke restore and expect their generated props and targets to affect Restore

I am not aware of anyone doing this so I don't think it would be a breaking change.  At this time, since the files are embedded during evaluation, the ones that get embedded are not guaranteed to be correct if restore writes new versions. The functionality that executes restore (like NuGet) should [embed these files](https://github.com/NuGet/NuGet.Client/pull/5494) instead. 

I'd be more than happy to send the pull request.

### Steps to Reproduce

1. Restore a project with the binary logger (`/t:restore /bl`)
2. Modify a package reference
3. Restore again

### Expected Behavior

The binary log should have a the updated `.nuget.g.props`

### Actual Behavior

The embedded `.nuget.g.props` in the binary log is the one that existed on disk when the project was evaluated not the one that was generated during restore.

**Comment by JanKrivanek** [comment]
Team triage: versioning would be bettr solution - though more complicated. Restore filesmight possbily be of interest in some scenarios - so preventing them might be problematic as well.

**Comment by KirillOsenkov** [comment]
Note that the current behavior is plain wrong and incorrect. While versioning might be helpful in other scenarios, here it will only harm, by embedding irrelevant versions of these files, causing confusion, increasing binlog size and slowing the build down. What Jeff proposes is the best solution here.

**Comment by KirillOsenkov** [comment]
also by not importing these files during restore we make the build slightly faster and avoid non-determinism, where old content might feed into the evaluation in an unpredictable way.

**Comment by JanKrivanek** [comment]
@KirillOsenkov - Agreed. I as well missed the info about https://github.com/NuGet/NuGet.Client/pull/5494 that addresses concern of someone possibly wanting to see the files from restore time.

@jeffkl - you expressed the willingness to contribute a fixing PR - this would be very appreciated.

**Comment by rainersigwald** [comment]
Yeah, I also like 2; I would name it `MSBuildIsRestoring`. Though since we already have MSBuildRestoreSessionId, comparing it to nonempty seems pretty reasonable too.

How confident are we about other users of restoration not expecting the ProjectExtension stuff to be present at MSBuild-integrated restore time? I can imagine a system that would break under such a circumstance but I don't know if any exists. A changewave would probably be enough.

**Comment by jeffkl** [comment]
> How confident are we about other users of restoration not expecting the ProjectExtension stuff to be present at MSBuild-integrated restore time? I can imagine a system that would break under such a circumstance but I don't know if any exists. A changewave would probably be enough.

I think its extremely unlikely that anyone is doing this.  You would have to run some external process which generates the files and _then_ run restore, and finally build, while expecting the restore to take into account what you generated up front.  I highly doubt anyone has done this.
