### ISSUE TITLE
Include @dotnet/source-build-internal as code owners for SB files

### ISSUE THREAD

**Issue by ellahathaway** [dotnet/msbuild#9513]
### Summary

@dotnet/source-build-internal is not tagged as a code owner for [SourceBuildPrebuiltBaseline.xml](https://github.com/dotnet/arcade/blob/main/eng/SourceBuildPrebuiltBaseline.xml). It would be helpful to create a [CODEOWNERS file](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners?algolia-query=code%20owners) and include source-build-internal on SB files. For reference, Aspnet does this in their CODEOWNERS file: https://github.com/dotnet/aspnetcore/blob/36c976723fd0b55dad80f1ff32e665800ea4a021/.github/CODEOWNERS#L19

### Background and Motivation

Having a code owners file would also be generally useful when opening PRs in this repo, as it can sometimes be difficult and time consuming to determine who should be included as a reviewer.

### Proposed Feature

Create a CODEOWNERS file

**Comment by ellahathaway** [comment]
Can this issue be closed?

**Comment by rainersigwald** [comment]
It'll auto-close when https://github.com/dotnet/msbuild/pull/9532 brings the change to `main`.
