### ISSUE TITLE
[Bug]: Unable to open solution in MSbuild

### ISSUE THREAD

**Issue by Ann-1024** [dotnet/msbuild#9514]
### Issue Description

Unable to open WPF solution in MSbuild

### Steps to Reproduce

**Version Used**: 
net 6.0 Visual studio2022
"Microsoft.Build.Framework" Version="17.8.3" ExcludeAssets="runtime"
"Microsoft.Build.Locator" Version="1.6.10" 
"Microsoft.Build" Version="17.8.3" ExcludeAssets="runtime" 
"Microsoft.Build.Utilities.Core" Version="17.8.3" ExcludeAssets="runtime" 
"Microsoft.CodeAnalysis.Workspaces.MSBuild" Version="4.8.0" 

**Steps to Reproduce**:

1. clone a WPF repositories(such as https://github.com/HandyOrg/HandyControl or https://github.com/lepoco/wpfui)
2. use MSbuild to open the solution and throw error
  
```
using Microsoft.Build.Locator;
using Microsoft.CodeAnalysis.MSBuild;

//MSBuildLocator.RegisterDefaults(); can not use, throw error as can bot find msbuild
MSBuildLocator.RegisterMSBuildPath("C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\Msbuild\\Current\\Bin");
var msWorkspace = MSBuildWorkspace.Create();
var solution = msWorkspace.OpenSolutionAsync("HandyControl.sln").Result;
```

### Expected Behavior

open solution sucessfully

### Actual Behavior

throw error like that
System.TypeLoadException
  HResult=0x80131522
  Message=Could not load type 'System.Runtime.Remoting.RemotingServices' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
  Source=Microsoft.Build
  StackTrace:
   at Microsoft.Build.BackEnd.TaskExecutionHost.Dispose(Boolean disposing) in Microsoft.Build.BackEnd\TaskExecutionHost.cs:line 329
   at Microsoft.Build.BackEnd.TaskExecutionHost.Finalize() in Microsoft.Build.BackEnd\TaskExecutionHost.cs:line 103

**Comment by Ann-1024** [comment]
I attempt to use MSbuild in net6.0 app to open and analyze a solution on .Net farmework.

**Comment by Ann-1024** [comment]
You mean the MSbuild I installed is targeting on .NET Framework, I should not use them in .Net 6 APP? But I tried to use it in the WPF repositories and load itself and fail in the same way.

**Comment by Ann-1024** [comment]
I mean  I write the same code to use msbuild to open .sln  in the WPF repositories and load itself and fail in the same way.

**Comment by Ann-1024** [comment]
Yes, I want to use MSbuild to build and analyze WPF repositories in my app, but I fail to load the solution. To figure out the reason, I change the code in repository to make it load itself and fail again.

**Comment by AR-May** [comment]
MSBuild team triage: @Ann-1024 does @rainersigwald suggestion help with your issue?

**Comment by Ann-1024** [comment]
Yes, I try to target .NET Framework 4.7.2 and it works now.
