### ISSUE TITLE
[Bug]: Cross thread access to the static dictionary

### ISSUE THREAD

**Issue by f-alizada** [dotnet/msbuild#9550]
Updating properties of the static class could be accessed from different threads which could cause corruptions:
https://github.com/dotnet/msbuild/blob/b0e2b79230019c8f28ad7bedd82ecaa85a114761/src/Build/BackEnd/BuildManager/BuildManager.cs#L580

**Comment by JanKrivanek** [comment]
FYI @rokonec - related #8561?

**Comment by f-alizada** [comment]
Closing since the PR got merged already.
