### ISSUE TITLE
manage output path by using project properties

### ISSUE THREAD

**Issue by rainbowechoes** [dotnet/msbuild#9584]
### Issue Description

I want to manage outputpath by using project property. so I definition a property in csproj file, like this:
```xml
<MyProperty>true</MyProperty>
```

and I add a condition PropertyGroup in `Directory.Build.props` like this:
```xml
  <PropertyGroup Condition="'$(MyProperty)' == 'true'">
    <OutputPath>.\Bin\CustomeDirectory</OutputPath>
  </PropertyGroup>
```

but after I finished these operations, the dll file didn't output to the location that I wanted.

### Steps to Reproduce

1. add a custom property in csproj file, like `<MyProperty>true</MyProperty>`
2. use the property in `Directory.Build.props` file, like this:
```xml
  <PropertyGroup Condition="'$(MyProperty)' == 'true'">
    <OutputPath>.\Bin\CustomeDirectory</OutputPath>
  </PropertyGroup>
```

### Expected Behavior

the dll file should output to the `.\Bin\CustomDirectory` 

### Actual Behavior

the dll file output to the project default directory 

### Ask us questions

Can I use the property in props file? If I can, how to make it work correctly?

**Comment by baronfel** [comment]
This is an ordering issue - when MSBuild builds a project it first _evaluates_ that project, and evaluation ends up firing in this order:

* .NET SDK Props
* Directory.Build.props
* project file content
* .NET SDK Targets
* NuGet package props/targets
* Directory.Build.targets

(roughly, I've omitted some details).

This means that anything you set in the project _cannot_ influence the way that Directory.Build.props is evaluated. But even if it could, setting properties like OutputPath in the Project is not a good idea - by the time the project is evaluated several other .props files have been evaluated by the .NET SDK that depend on the value of OutputPath.

**Comment by rainbowechoes** [comment]
Thank you for your reply, baronfel.

Based on your explanation, does it mean that I can't use the properties defined in the csproj file within the props file? However, I've tried combining this property condition with Message Text, and the message in Text was successfully output during project build. This is quite strange.

Additionally, if I want to control the location of the Output path by implementing a property, what would be the recommended approach?

**Comment by jrdodds** [comment]
That's correct - you can't use properties in the `Directory.Build.props` file that are defined in the project file. The `Directory.Build.props` is evaluated early before the project file content. Properties that have their initial definition in the project file will be undefined when the `Directory.Build.props` is evaluated.

The `SDK.props` imports the `Directory.Build.props` (if one exists) and most of the content of the `SDK.props` is after the `Directory.Build.props` import. The point being that you can change the value of `OutputPath` in the `Directory.Build.props`.

It's common to chain a set of `Directory.Build.props` (and `Directory.Build.targets`) files. See "[Use case: multi-level merging](https://learn.microsoft.com/en-us/visualstudio/msbuild/customize-by-directory?view=vs-2022#use-case-multi-level-merging)".

In the project folder as a sibling of the .csproj file, you could add a `Directory.Build.props` file like:

```xml
<Project>
  <PropertyGroup>
    <MyProperty>true</MyProperty>
  </PropertyGroup>
  <Import Project="$([MSBuild]::GetPathOfFileAbove('$(MSBuildThisFile)', '$(MSBuildThisFileDirectory)../'))" />
</Project>
```

Higher in the directory tree where it will be shared across projects, you could have another `Directory.Build.props` file like:

```xml
<Project>
  <PropertyGroup Condition="'$(MyProperty)' == 'true'">
    <OutputPath>.\Bin\CustomeDirectory</OutputPath>
  </PropertyGroup>
</Project>
```

**Comment by rainbowechoes** [comment]
Understant it. Thank you all! Thanks for your patience and help.

**Comment by jrdodds** [comment]
> > you can't use properties in the Directory.Build.props file that are defined in the project file
> 
> You can't use those properties in _PropertyGroup_ in the Directory.Build.props file, but you can use them in _ItemGroup_ or _Target_ in that file, as those are evaluated later — see [Property and item evaluation order](https://learn.microsoft.com/en-us/visualstudio/msbuild/comparing-properties-and-items?view=vs-2022#property-and-item-evaluation-order).

I was answering in the context of the issue to be solved -- managing the `OutputPath` property -- but I didn't make that clear so it's good to note that my statement is not the general case.

The content of the Project is in the evaluation phase. Targets are in the execution phase. As noted, 

> ... setting properties like OutputPath in the Project is not a good idea ...

Just as setting `OutputPath` in the project is problematic, so is setting `OutputPath` in a target.
