### ISSUE TITLE
[Performance]: Loading SDK resolvers is slow on Windows

### ISSUE THREAD

**Issue by ladipro** [dotnet/msbuild#9591]
A recent experiment has shown that resolving in-box SDKs (e.g. `Microsoft.NET.Sdk`) directly in MSBuild without loading any of the configured resolvers has a significant perf impact.

PerfStar shows a ~5% improvement in build time, but strangely enough, only on Windows. The Linux numbers are unaffected.

Experimental change: https://github.com/dotnet/msbuild/compare/main...perf/sdk-resolution-shortcut3

PerfStar results:

![image](https://github.com/dotnet/msbuild/assets/12206368/0bfa9988-ec63-4ac8-b1d2-7ad541a844c1)

## Expected output

- Understand why this change affects only Windows. Is it the OS/runtime or is MSBuild/SDK doing something expensive?
- Find opportunities to make SDK resolution on Windows faster even in cases where we need to load resolvers.
- [non-goal] Productizing the experiment will be done as part of #9506, it is not a goal of this issue.

**Comment by ladipro** [comment]
_Too good to be true_ is the unfortunate outcome of this investigation. The baseline runs used by PerfStar for the **Avg 30 days** column all took place before December 5th 2023 and there is a significant difference between those results and what we're getting from recent experimental runs. The dashboard is not showing any main/baseline runs after 12/5. So this is not an apples-to-apples comparison.

The actual perf win, as calculated from two experimental runs, one with the changes and one without, is ~0.5%. This is more in line with expectations because what this essentially does is eliminate one or two assembly loads + some JITting from the evaluation code path.

@AR-May can you please check why PerfStar is not running on main and why the December runs were so different? For what it's worth, I see no difference when I manually compare a main build from 12/5 with current main.

cc @Forgind as I see that you recently submitted an experimental run. Please note that the relative results are invalid. Absolute numbers can still be compared with other experimental runs.

**Comment by Forgind** [comment]
I was looking at the results from PerfStar yesterday with rokonec, and the results looked fantastic, but they were much more than I'd expected. My interpretation was just that since my run was a 4.8% improvement, and your no-changes run was a 4.4% improvement, perhaps my change was a 0.4% improvement.

**Comment by AR-May** [comment]
Seems like I did not turn on the weekly runs when I cancelled the daily runs on the pipeline. Turning them on as I write this.
