### ISSUE TITLE
Support showing default MSBuild output when using CLI-based project evaluation

### ISSUE THREAD

**Issue by tmds** [dotnet/msbuild#9617]
### Is your feature request related to a problem? Please describe.

In a CI pipeline, I would like to use the CLI-based project evaluation to capture information to be passed to the next step while still have the default MSBuild output appear in the CI log.

Currently, when using CLI-based project evaluation, the default output MSBuild output becomes unavailable because standard output is used to print the evaluation result.

Also in other use-cases, it may be desired to still have the default MSBuild output shown while using project evaluation.

### Describe the solution you'd like

Allow the result of the project evaluation to be written to a file instead of writing it to standard output. Standard output can then be used for the usual MSBuild output.

### Additional information

https://github.com/dotnet/sdk/issues/36694 is a bug report that is also requesting for allowing the evaluation to be written to a file.

cc @baronfel

**Comment by baronfel** [comment]
I'm generally in favor of having some way of specifying this, because it's not really feasible or easy for any given command against the .NET CLI to be known to be free of errant output in the stdout stream at this time (due to things like the first-run output, workload updates, and arbitrary MSBuild tasks using Console.WriteLine).   If this proposed new `-evaluation-results-file` is used, then the normal stdout output for MSBuild could be freed up as suggested by @tmds.

**Comment by rokonec** [comment]
Is to possible to address it by `dotnet build /flp:output.txt ...; cat outout.txt`?

**Comment by Forgind** [comment]
> Is to possible to address it by `dotnet build /flp:logfile=output.txt ...; cat output.txt`?

This is clever, but without having tested it, I don't think it works, unfortunately. When using get*, we turn off the console logger and custom loggers. If you request a file logger, you can have it, but we also change the verbosity to quiet, and since SetParameterizedSwitch appends rather than prepends, and the verbosity switch looks at the last one set, your logs would always be quiet even if you requested something else.

Looking back at that, I'm not convinced that's really the right design, but that's a separate question.

**Comment by rokonec** [comment]
@Forgind  I have just tried `msbuild -getTargetResult:build "/flp:logfile=o.txt;v=n"` from powershell and it seems to be working.
I suppose /flp turns it back again, which is great.

**Comment by Forgind** [comment]
> @Forgind I have just tried `msbuild -getTargetResult:build "/flp:logfile=o.txt;v=n"` from powershell and it seems to be working. I suppose /flp turns it back again, which is great.

Great point! I'd forgotten you could set the file logger's verbosity separately from the rest of the build. I like that as a workaround.

**Comment by baronfel** [comment]
Using the existing file logger mechanism sounds like a perfect fix here - @tmds is that a viable resolution? I don't want to make a new feature unless the existing mechanism can't satisfy your need.

**Comment by tmds** [comment]
For my usage, I'd like the output to appear on terminal as before, that is: streaming as the build progresses.
That doesn't happen with the file logger.

Also, enabling this through `/flp:logfile=o.txt;v=n` is hard to remember (and requires quotes with bash), and it doesn't work with other flags like `--verbosity`.

The file logger is a workaround, but I'm hoping for something more first-class.
@Forgind made a PR for this: https://github.com/dotnet/msbuild/pull/9640.

**Comment by VAllens** [comment]
> @Forgind I have just tried `msbuild -getTargetResult:build "/flp:logfile=o.txt;v=n"` from powershell and it seems to be working. I suppose /flp turns it back again, which is great.

@rokonec 
On the Windows platform, it works normally.
On the Linux platform, it does not output log files, and the terminal does not have any output.

**Comment by tmds** [comment]
> On the Linux platform, it does not output log files, and the terminal does not have any output.

When I run `dotnet msbuild -getTargetResult:build "/flp:logfile=o.txt;v=n"` on Linux, it has the expected behavior of writing the evaluation output to the terminal, and the log output to the `o.txt` file.

note: it's important to include the `"` to avoid the shell interpreting the `;` as the end of the command.

**Comment by VAllens** [comment]
> > On the Linux platform, it does not output log files, and the terminal does not have any output.
> 
> When I run on Linux, it has the expected behavior of writing the evaluation output to the terminal, and the log output to the file.`dotnet msbuild -getTargetResult:build "/flp:logfile=o.txt;v=n"``o.txt`
> 
> note: it's important to include the to avoid the shell interpreting the as the end of the command.`"``;`

Oh, I'm sorry, I made a mistake.

I noticed a detail that I used dotnet build instead of dotnet msbuild.

Now, I am using Dotnet msbuild on the Linux platform and everything is going smoothly.

**Comment by tmds** [comment]
Fixed by https://github.com/dotnet/msbuild/pull/9640.
