### ISSUE TITLE
Analyzers prototyping - Representative analyzers set

### ISSUE THREAD

**Issue by JanKrivanek** [dotnet/msbuild#9630]
### Context
#9627

 * Let's go through ideas and build interesting initial set
 * Mark the analyzers in the set based on viability based on EventArgs ('Doable today', 'Doable with slight adjust of EventArgs with minimum implementation and perf cost', 'More complicated')
 * Let's choose few from the first 2 categories above, Expose OM for them and author them

The main part should be the last point

FYI @ladipro (this is based on your suggestion)

### References

 * [[Internal link] analyzer ideas](https://microsoft.sharepoint.com/teams/DotNetTeam/_layouts/15/Doc.aspx?sourcedoc={a2a284d4-baec-4dc6-b748-0b4f4ac61d2d}&action=edit&wd=target%28Potential%20Analyzers.one%7C8c8d15f9-d311-42f6-b5d0-9c9c8e185b78%2F%29&wdorigin=717)

**Comment by JanKrivanek** [comment]
Candidates:
- [ ] https://github.com/dotnet/msbuild/issues/9690

**Comment by ladipro** [comment]
Here's the list of analyzers we would like to ship, each with its own issue:

- #9879
- #9880 
- #9881 
- #9882 
- #9883 
- #9884 
- #9885 
- #9888 
- #9889 
- #9891
- #9892

I'll close this one and we'll continue in individual issues. Each proposed analyzer is a bit different and the devil is in the details, as they say.

**Comment by stan-sz** [comment]
This seems relevant to #1777
