### ISSUE TITLE
[Flaky test] Microsoft.Build.Tasks.UnitTests.SecurityUtil_Tests.SignFile_Success

### ISSUE THREAD

**Issue by surayya-MS** [dotnet/msbuild#9639]
While working on https://github.com/dotnet/msbuild/pull/9621 I came across this flaky test. It flakes quite often.

There are no error message or stack trace.

Sample failing build:
https://dev.azure.com/dnceng-public/public/_build/results?buildId=521905&view=ms.vss-test-web.build-test-results-tab&runId=12263180&resultId=104535&paneView=history

**Comment by JanKrivanek** [comment]
@surayya-MS pointed aother recently failing instance: https://dev.azure.com/dnceng-public/public/_build/results?buildId=535267&view=ms.vss-test-web.build-test-results-tab

Looking into artifacts, this is what is in the test artifacts (Microsoft.Build.Tasks.UnitTests_net472_x86.xml):

```
Shouldly.ShouldAssertException : `SignAction`\r\n    should not throw but threw\r\nSystem.ApplicationException\r\n    with message\r\n\"The parameter is incorrect.\r\n\"
   at Microsoft.Build.Tasks.UnitTests.SecurityUtil_Tests.SignFile_Success(String tfVersion, String tfIdentifier) in D:\a\1\s\src\Tasks.UnitTests\SecurityUtil_Tests.cs:line 48
```

**Comment by YuliiaKovalova** [comment]
Please check the recent runs: https://dev.azure.com/dnceng-public/public/_build?definitionId=75

**Comment by YuliiaKovalova** [comment]
It seems like the recent runs are green.
Can we close it?

**Comment by surayya-MS** [comment]
> It seems like the recent runs are green. Can we close it?

If that's the case, I think we should close it.
