### ISSUE TITLE
Support "quiet" verbosity in terminal logger

### ISSUE THREAD

**Issue by rainersigwald** [dotnet/msbuild#9654]
### Summary

Respect "quiet" verbosity in the terminal logger by minimizing or eliminating _persistent_ output lines (while preserving the "live" status display that is the point of TL).

### Background and Motivation

Today, `-tl` disregards verbosity settings (for example `-v:q`), because there are many existing "high" priority build messages that don't seem, in retrospect, to be very high-priority. However, that means that there's also no way to _reduce_ output from the terminal logger.

### Proposed Feature

When verbosity is set to quiet, do not emit messages like "restore finished", the "primary output of the project" message, or "build finished".

**Comment by baronfel** [comment]
Potential use cases:
* runtime script output?
* `dotnet test` without their new Terminal Logger support that's part of .NET 9 preview 2
