### ISSUE TITLE
[Bug]: .NET 9.0 Alpha build fails in Windows 1809 Docker containers with Terminal Logger error

### ISSUE THREAD

**Issue by lbussell** [dotnet/msbuild#9662]
### Issue Description

We're seeing this issue consistently with the latest .NET 9.0 alpha builds in our Windows Server Core 2019 and Nanoserver 1809 SDK images. The project is created with the `dotnet new web` command, and started failing with the SDK version 9.0.100-alpha.1.24058.1. The last known good SDK that we have is 9.0.100-alpha.1.24053.3.

```
 MSBUILD : error MSB4015: The build stopped unexpectedly because the "TerminalLog
 ger" logger failed unexpectedly during shutdown.\x1b[32X\x1b[32C
 System.IO.IOException: The parameter is incorrect.\x1b[30X\x1b[30C
    at System.ConsolePal.SetConsoleOutputEncoding(Encoding enc)\x1b[18X\x1b[18C
    at System.Console.set_OutputEncoding(Encoding value)\x1b[25X\x1b[25C
    at Microsoft.Build.Logging.TerminalLogger.TerminalLogger.Shutdown()\x1b[10X\x1b[10C
    at Microsoft.Build.BackEnd.Logging.LoggingService.ShutdownLogger(ILogger logger)
```

Please excuse the weird text formatting - I didn't want to cut anything off in case it's important.

(here's a link to failing pipeline run that was pulled from: https://dev.azure.com/dnceng-public/public/_build/results?buildId=531306&view=logs&j=993563f7-f5c3-53cf-2b69-c3a3c7bb299e&t=4e281778-b663-5be4-ed90-ae0bb7f6fb0d&l=336)

### Steps to Reproduce

I am unable to reproduce this issue on my local machine, but we are experiencing it consistently in our CI. If there are any additional diagnostic steps you want me to perform, let me know.

### Expected Behavior

The build completes successfully.

### Actual Behavior

```
 MSBUILD : error MSB4015: The build stopped unexpectedly because the "TerminalLog
 ger" logger failed unexpectedly during shutdown.\x1b[32X\x1b[32C
 System.IO.IOException: The parameter is incorrect.\x1b[30X\x1b[30C
    at System.ConsolePal.SetConsoleOutputEncoding(Encoding enc)\x1b[18X\x1b[18C
    at System.Console.set_OutputEncoding(Encoding value)\x1b[25X\x1b[25C
    at Microsoft.Build.Logging.TerminalLogger.TerminalLogger.Shutdown()\x1b[10X\x1b[10C
    at Microsoft.Build.BackEnd.Logging.LoggingService.ShutdownLogger(ILogger logger)
```

**Comment by rainersigwald** [comment]
Looks like there are two bugs here:

1. The crash
2. We aren't detecting redirection and are junking up that output with control codes, when we shouldn't be.

I would normally prioritize the crash but here that seems less bad than that we're using TL in this scenario at all.

**Comment by baronfel** [comment]
Agree with Rainer's assessment - we don't intend for TL to run in CI scenarios generally speaking (though it would be fine for it to run in a Docker context for example if the user ran a 'docker run -it SOME_SDK_IMAGE' command).

**Comment by lbussell** [comment]
Maybe you want to condition on `DOTNET_RUNNING_IN_CONTAINER`?

**Comment by baronfel** [comment]
> Maybe you want to condition on `DOTNET_RUNNING_IN_CONTAINER`?

This isn't general enough - we're trying to go for a capability-based detection approach. We check things like if a TTY is available, or if the StdOut has been redirected, or if the terminal that is present supports certain control codes. I want to figure out more about why the checks we have in place didn't work in this specific circumstance - it might be a category of detection that we've missed.

**Comment by AR-May** [comment]
@lbussell I am trying to repro or find more information about this bug. Unfortunately, the link to the CI build with repro in the description already expired. Do you have a more recent failed build?

**Comment by lbussell** [comment]
I tried to repro this today and wasn't able to - I'll re-enable our test and re-open this issue if I see it again.

**Comment by lbussell** [comment]
@AR-May I spoke too soon. The problem still exists. Here it is in our CI [MSFT internal link]: https://dev.azure.com/dnceng/internal/_build/results?buildId=2445932&view=logs&j=8fbd142f-3569-5a30-ef1a-e765423f275f&t=c48e8e47-6fa0-5956-a580-dcc0382d12b7&l=452

We are reading the logs out of a Docker container, so there seems to be some weirdness with the formatting. If there are any specific troubleshooting steps you'd like me to do in this scenario, I can do that.

**Comment by baronfel** [comment]
I wouldn't suggest that - many actual-editor scenarios would use TL while in the context of a Docker container. For example, the VSCode editor supports a concept called [devcontainers](https://code.visualstudio.com/docs/devcontainers/containers) - these are broadly used to ensure a reproducible environment for contributors to a project.  As a result, we _should not_ do any sort of Docker-based disablement of TL.

Since the build in question is 'driving' Docker-based builds and knows they don't want TL output, I'd suggest that for this specific use case @lbussell should use the parameters/knobs to disable TL for this one step - either the environment variable or the explicit parameter would do (though I expect the environment variable would be easier to pass).

**Comment by AR-May** [comment]
I agree, we will not want to disable it for all such scenarios. 
@lbussell You can find how to opt out of TL for you test case [on this page](https://learn.microsoft.com/en-us/dotnet/core/compatibility/sdk/9.0/terminal-logger#recommended-action).
