### ISSUE TITLE
Add a Console Logger Parameter to control the output encoding

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/msbuild#9694]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/msbuild-option-for-colsoleLoggerParamete/10376408)._

---
i need msbuild.exe option for -consoleLoggerParameters.
i made custom warning message for TODO and use it with Korean encoded with utf8.
however when i run compile, Korean warning message showed on output window is not readable as msbuild output console log as cp949(my Windows encoding).
so i hope you guys add encoding option for console logger like file logger parameter.

---
#### Feedback Bot on 5/29/2023, 09:01 AM: 

(private comment, text removed)

**Comment by AR-May** [comment]
@GangWang01, we want to check does it reproduce in VS Developer Command Prompt, or only for stand-alone msbuild.

**Comment by GangWang01** [comment]
It reproduced both with VS Developer Command Prompt and stand-alone msbuild, as well as `dotnet build` (dotnet 8.0.101). Here is a screenshot 
![standalone](https://github.com/dotnet/msbuild/assets/2950449/4007e190-ce66-4039-9646-05c5387669b3).

Adding encoding option to consolelogger parameters and setting it to `Console.OutputEncoding` could resolve it.

**Comment by AR-May** [comment]
@GangWang01, we discussed this issue and decided that creating a warning or error or message should work correctly with any language by default, without need to specify encoding in the parameters of console logger. Could you try to work in this direction?
