### ISSUE TITLE
[Bug]: PackageReference with Content fails to build rather than warn with NU1701

### ISSUE THREAD

**Issue by edmfgh** [dotnet/msbuild#9702]
### Issue Description

Given a consumer project, ProjectConsumer (with TargetFramework netstandard2.0) that PackageReferences a project with Content, ProjectWithContent, (with TargetFrameworks net48;net6.0) and another project without Content, ProjectWithoutContent, (also with TargetFrameworks net48;net6.0), ProjectConsumer fails to compile with "error CS0246: The type or namespace name 'ProjectWithContent' could not be found (are you missing a using directive or an assembly." On the other hand, ProjectWithoutContent compiles with warning NU1701.

Note that if ProjectWithContent and ProjectWithoutContent are ProjectReferenced rather than PackageReferenced, ProjectConsumer builds with warning. This leads me to suspect the issue could involve NuGet.

If there is a fundamental issue why a project with content cannot be PackageReferenced this way, it would be nice to have a more descriptive error message.

Thanks!

### Steps to Reproduce

Sample project to reproduce issue: https://github.com/edmfgh/PackageReferenceBug/tree/main

1. "dotnet pack" both ProjectWithContent and ProjectWithoutContent, e.g., "dotnet pack .\ProjectWithContent.csproj" -o <output folder>
2. Add <output folder> as a NuGet source
3. Ensure ProjectConsumer references ProjectWithContent and ProjectWithoutContent via PackageReference
4. Build ProjectConsumer

### Expected Behavior

ProjectConsumer builds with warnings that ProjectWithContent and ProjectWithoutContent may not fully be compatible with your project, ProjectConsumer.

### Actual Behavior

ProjectConsumer fails to compile with "error CS0246: The type or namespace name 'ProjectWithContent' could not be found (are you missing a using directive or an assembly reference?)"

### Versions & Configurations

SDK 8.0.101
MSBuild version 17.8.3+195e7f5a3 for .NET, 17.8.3.51904
IDE Agnostic

**Comment by AR-May** [comment]
This issue was moved to NuGet/Home#13221
