### ISSUE TITLE
Don't stomp on `CreateSatelliteAssembliesDependsOn` property in the common targets

### ISSUE THREAD

**Issue by baronfel** [dotnet/msbuild#9703]
We missed this one in #4922, currently the [`CreateSatelliteAssembliesDependsOn`](https://github.com/dotnet/msbuild/blob/9a0cef6f75bf13ffbbde956b8f7d7ad7d6e0d996/src/Tasks/Microsoft.Common.CurrentVersion.targets#L3889-L3906) definition isn't extendable by users in their project files, so they have to reach for mechanisms like Directory.Build.targets to ensure they can extend the process.

**Comment by JanKrivanek** [comment]
This actually seems to be much more widespread - e.g. the externally documented [`Commonly overridden DependsOn properties`](https://learn.microsoft.com/en-us/visualstudio/msbuild/how-to-extend-the-visual-studio-build-process?view=vs-2022#commonly-overridden-dependson-properties)
* `BuildDependsOn` : https://github.com/dotnet/msbuild/blob/23f77529a83531782dd498bf400381842c3d2d9e/src/Tasks/Microsoft.Common.CurrentVersion.targets#L891-L895
* `CleanDependsOn`: https://github.com/dotnet/msbuild/blob/23f77529a83531782dd498bf400381842c3d2d9e/src/Tasks/Microsoft.Common.CurrentVersion.targets#L5675-L5682
* `CompileDependsOn`: https://github.com/dotnet/msbuild/blob/23f77529a83531782dd498bf400381842c3d2d9e/src/Tasks/Microsoft.Common.CurrentVersion.targets#L3595-L3607

But there are others then seem as potentially usefull - CoreBuildDependsOn, RebuildDependsOn, RunDependsOn, PublishDependsOn etc. etc.


So the questions is - do we want to generally open this? Or any of them? Or do we want to keep them as-is semi-hidden, overridable only via explicit importing of sdk.targets?

cc @baronfel

**Comment by baronfel** [comment]
Oof. IMO we should open these as #4922 intended.

**Comment by JanKrivanek** [comment]
https://github.com/dotnet/msbuild/issues/9755
