### ISSUE TITLE
[Bug]: Help message does not contain some switches (-getProperty, -getTargetResult)

### ISSUE THREAD

**Issue by ladipro** [dotnet/msbuild#9710]
### Issue Description

Some of the supported command line switches are not mentioned in the help message. For example `-getProperty` and `-getTargetResult` but there may be more.

### Steps to Reproduce

`msbuild -h`

### Expected Behavior

Contains help for `-getProperty`.

### Actual Behavior

Does not contain help for `-getProperty`.

### Analysis

All switches should be cross-checked against the help message strings to see what else is missing. It may also be useful to introduce a lightweight mechanism for keeping help up-to-date, for example by having to list the relevant string resource ID in `s_parameterlessSwitchesMap` / `s_parameterizedSwitchesMap`.

**Comment by surayya-MS** [comment]
NOTE: Help message should contain new switches `-featureavailability` and `-fa` from https://github.com/dotnet/msbuild/pull/9665
