### ISSUE TITLE
[Bug]: FileNotFoundException System.Drawing.Common exception when referencing an assembly that references System.Drawing in an MSBuild task

### ISSUE THREAD

**Issue by ThomasGoulet73** [dotnet/msbuild#9711]
### Issue Description

I have an MSBuild task that references a .Net Framework assembly which references System.Drawing. This worked before and now it fails when using the .Net 8.0 SDK. The task also work when running using the MSBuild included with Visual Studio (Probably because the one included with Visual Studio runs with .Net Framework).

Here's the exception:
```
C:\MSBuildTaskError\ConsoleApp\ConsoleApp.csproj(11,5): error MSB4018: Échec inattendu de la tâche "TestTask".
C:\MSBuildTaskError\ConsoleApp\ConsoleApp.csproj(11,5): error MSB4018: System.IO.FileNotFoundException: Could not load file or assembly 'System.Drawing.Common, Version=0.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. Le fichier spécifié est introuvable.
C:\MSBuildTaskError\ConsoleApp\ConsoleApp.csproj(11,5): error MSB4018: File name: 'System.Drawing.Common, Version=0.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
C:\MSBuildTaskError\ConsoleApp\ConsoleApp.csproj(11,5): error MSB4018:    at LibraryTest.Class1..ctor()
C:\MSBuildTaskError\ConsoleApp\ConsoleApp.csproj(11,5): error MSB4018:    at MSBuildTaskTest.TestTask.Execute() in C:\MSBuildTaskError\MSBuildTaskTest\TestTask.cs:line 15
C:\MSBuildTaskError\ConsoleApp\ConsoleApp.csproj(11,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
C:\MSBuildTaskError\ConsoleApp\ConsoleApp.csproj(11,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask)
```

### Steps to Reproduce

Using this repro: [MSBuildTaskError.zip](https://github.com/dotnet/msbuild/files/14168171/MSBuildTaskError.zip)

1. Build LibraryTest.csproj using "dotnet build LibraryTest\LibraryTest.csproj -c Debug"
2. Build MSBuildTaskTest.csproj using "dotnet build MSBuildTaskTest\MSBuildTaskTest.csproj -c Debug"
3. Build ConsoleApp.csproj using "dotnet build ConsoleApp\ConsoleApp.csproj -c Debug".

### Expected Behavior

Step 3 should not return an exception.

### Actual Behavior

Step 3 returns an exception.

### Versions & Configurations

.NET SDK 8.0.101
MSBuild 17.9.0-preview-23618-08+82d381eb2

**Comment by rainersigwald** [comment]
This is a consequence of this .NET 8 breaking change: https://learn.microsoft.com/dotnet/core/compatibility/windows-forms/8.0/extensions-package-deps.

Tasks built against .NET Framework may work in the .NET (Core) SDK, but are not guaranteed to do so, and I don't think this is something we should fix.

**Comment by ThomasGoulet73** [comment]
I can't change the target framework of LibraryTest, it's a dll that I do not control in my real project. How can I fix my task without changing the target framework of LibraryTest ? Or is it even possible ?

**Comment by KirillOsenkov** [comment]
Is this the same issue as https://github.com/dotnet/msbuild/issues/5312? Or is it different?

**Comment by KirillOsenkov** [comment]
https://github.com/dotnet/sdk/issues/11489

**Comment by AR-May** [comment]
Team triage: seems like it should be fixed on your side, @ThomasGoulet73, as @rainersigwald suggested. Please feel free to ask if you get any questions.
