### ISSUE TITLE
Occasional extra characters in terminal logger output

### ISSUE THREAD

**Issue by jcmrva** [dotnet/msbuild#9715]
### Describe the bug

I quite like the terminal logger & I've used it consistently since I learned about it. Very rarely, extra characters will appear at the end of the line for some of the build artifacts.

> ...`.dll]8;;`
> ...`.dll\` 

The actual file name is not affected, just the display.

### To Reproduce
🤷 
### Further technical details
- Include the output of `dotnet --info`
  > .NET SDK:
 Version:           8.0.101
 Commit:            6eceda187b
 Workload version:  8.0.100-manifests.69afb982

  > Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19045
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.101\

  >.NET workloads installed:
 Workload version: 8.0.100-manifests.69afb982
There are no installed workloads to display.

  > Host:
  Version:      8.0.1
  Architecture: x64
  Commit:       bf5e279d92
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version: n/a - `dotnet build --tl`

**Comment by baronfel** [comment]
Is this happening locally, or in a CI/CD scenario? There's also a new version of .NET coming next week that will have fixes to Terminal Logger's output, so we may have inadvertently fixed this behavior already. It'd be worth checking again once that releases.

**Comment by jcmrva** [comment]
Locally; I haven't used it in CI yet.

It's not a big deal, wanted to bring this up just in case anything needed to be done.

**Comment by baronfel** [comment]
Thanks for the details! No worries, we can take a look and see if there's a reason for it. Thanks for logging issues about Terminal Logger 🫡

**Comment by YuliiaKovalova** [comment]
Hi @jcmrva,

May I ask you to provide additional information for the bug investigation:
1) Terminal & it's version where you run this request in (e.g. cmd, PowerShell, VS Dev Prompt...)
2) If it is possible, the name of the dll that is printed with` .dll]8;;` and check the path length for this artifact (if we cross any boundary)?

Thank you!

**Comment by jcmrva** [comment]
Hi @YuliiaKovalova 

I didn't keep the full output but the dll name is one of our projects that's being compiled. The path length is 50 chars or so.

PowerShell 7.4.1
Windows Terminal 1.18.10301.0

**Comment by rainersigwald** [comment]
Any non-ANSI characters in that path, especially "interesting" ones like GB-18030?

**Comment by jcmrva** [comment]
Nope, nothing unusual.

**Comment by YuliiaKovalova** [comment]
Thank you for the answers! I have found information that `.dll]8;;` can be displayed when the Terminal cannot correctly display color formatting, cursor movement, or other terminal control functions. Could you please check if all the colors are displayed correctly when you build, as shown in the attached screenshot?
![image](https://github.com/dotnet/msbuild/assets/95473390/946dae9f-ef92-4756-a73d-40691b8adcfd)

**Comment by rainersigwald** [comment]
That part is added only for a multitargeted project.

**Comment by jcmrva** [comment]
It only targets net8.0

**Comment by jcmrva** [comment]
This time it didn't put a newline between 2 projects (out of 30).

![image](https://github.com/dotnet/msbuild/assets/20140997/56b3b6ec-5bfb-4d7b-8c95-771144fd41bb)

**Comment by YuliiaKovalova** [comment]
Hi @jcmrva ,

Could you check the system set code page?
In order to do that please open PowerShell-> Properties -> Options -> Current code page.
![image](https://github.com/dotnet/msbuild/assets/95473390/c9059e40-4f7d-430c-898f-c9945fa8e3d7)

If it's not 65001, please change it using the next guideline: https://stackoverflow.com/questions/57131654/using-utf-8-encoding-chcp-65001-in-command-prompt-windows-powershell-window

**Comment by baronfel** [comment]
worth noting that it's not Windows Powershell being used here - it's Powershell Core 7.4+:

https://github.com/dotnet/msbuild/issues/9715#issuecomment-1942459139

**Comment by jcmrva** [comment]
I didn't make a note of what the old value was (IBM 432? 437? something like that) but I changed it to 65001 - all good so far.

**Comment by YuliiaKovalova** [comment]
> I changed it from 437 to 65001 - all good so far.

Thank you for checking it so promptly!
Let's give it a bit more time and if you don't notice any issues, I will close the ticket in 2 weeks.
