### ISSUE TITLE
[Kitten] Remove APICompat workaround once 8.0.2 or 9.xxx is consumed

### ISSUE THREAD

**Issue by JanKrivanek** [dotnet/msbuild#9720]
Not actionable now - logged not to forget about this.

### Background

A workaround for clashing version of Roslyn and APICompat checker needed to be introduced:
https://github.com/dotnet/msbuild/pull/9642/files#diff-50e91c82311ea26f2a73202525dfdf2b0a89c178ee666b2bf3ad4c84ac4c06dcR41

Once we update our build-time dotnet version (https://github.com/dotnet/msbuild/blob/main/global.json#L6) we should remove the workaround.

**Comment by f-alizada** [comment]
This is removed as part of the PR : https://github.com/dotnet/msbuild/pull/10484/files#diff-50e91c82311ea26f2a73202525dfdf2b0a89c178ee666b2bf3ad4c84ac4c06dc
