### ISSUE TITLE
`MsBuildSkipEagerWildCardEvaluationRegexes` not respected

### ISSUE THREAD

**Issue by rainersigwald** [dotnet/msbuild#9736]
NuGet (and some other systems) set `MSBuildSkipEagerWildCardEvaluationRegexes = [*?]+.*(?<!proj)$` to avoid spending time expanding globs for an evaluation that won't use them (for example, in NuGet static graph restore the evaluations don't need to expand `Compile` or `Content` globs since all NuGet cares about is package and project references).

This appears to be broken in `17.10.0-preview-24101-01+07fd5d51f`:

```
dotnet new blazor
$env:MSBUILDDISABLEFEATURESFROMVERSION="17.10"
dotnet restore -bl -p:RestoreUseStaticGraphEvaluation=true
# cancel out of debugger
# inspect nuget.binlog
```

This shows concrete items for Content and Compile that were pulled in via glob.

**Comment by jeffkl** [comment]
😢
