### ISSUE TITLE
Don't stomp on *DependsOn properties #2

### ISSUE THREAD

**Issue by JanKrivanek** [dotnet/msbuild#9755]
### Context

There are couple sdk ***DependsOn properties that allow injecting custom target as dependencies of sdk targets. However big portion of those properties are force set within sdk.targets - so users'd need to include sdk.targets explicitly to be able to set them (we even document a need for this workaround in the documentation mentioned below).

#4922 fixed couple, #9703 fixed one, but we have still dozens that we force overwrite.

e.g. the externally documented [`Commonly overridden DependsOn properties`](https://learn.microsoft.com/en-us/visualstudio/msbuild/how-to-extend-the-visual-studio-build-process?view=vs-2022#commonly-overridden-dependson-properties)
* `BuildDependsOn` : https://github.com/dotnet/msbuild/blob/23f77529a83531782dd498bf400381842c3d2d9e/src/Tasks/Microsoft.Common.CurrentVersion.targets#L891-L895
* `CleanDependsOn`: https://github.com/dotnet/msbuild/blob/23f77529a83531782dd498bf400381842c3d2d9e/src/Tasks/Microsoft.Common.CurrentVersion.targets#L5675-L5682
* `CompileDependsOn`: https://github.com/dotnet/msbuild/blob/23f77529a83531782dd498bf400381842c3d2d9e/src/Tasks/Microsoft.Common.CurrentVersion.targets#L3595-L3607

But there are others that seem as potentially usefull - CoreBuildDependsOn, RebuildDependsOn, RunDependsOn, PublishDependsOn etc. etc.

### Suggestion

Select a usefull subset (or probably all?) of the DependsOn properties in common target files ([search](https://github.com/search?q=repo%3Adotnet%2Fmsbuild+path%3A**%2F*.targets&type=code&p=2)) and redefine those with the additive pattern:

```xml
<SomeDependsOn>
   value1;
   value2
</SomeDependsOn>
```

--->

```xml
<SomeDependsOn>
   $(SomeDependsOn);
   value1;
   value2
</SomeDependsOn>
```

**Comment by baronfel** [comment]
Enforcing this rule could be an interesting BuildCheck

**Comment by JanKrivanek** [comment]
> Enforcing this rule could be an interesting BuildCheck

Would such properties by manualy configured by the author+user, or might there be any 'magic' how to detect properties that should actually behave as items?

**Comment by JanKrivanek** [comment]
Punting - no strong consensus
