### ISSUE TITLE
[Kitten] - Acquire OptProf build issue diagnostic data

### ISSUE THREAD

**Issue by JanKrivanek** [dotnet/msbuild#9761]
### Context

Our OptProf build tests have notrivial failure rate, that is caused by staling Solution Unload test step.
We need more diagnostic data (ETW, dump) so that Project System team can investigate further.

### Symptomps

Error message: Test 'OpenAndCloseProjectTestSolution' exceeded execution timeout period.

More details:

```
+ Close VS
Warning: (2:58.513) [Platform:TestLoggerDefault] Unable to retrieve an "IVsResourceManagerCacheControl".
+ Test Cleanup
+ TestCleanup
(19:59.204) [Platform:Testcase] ResultArchive: Copying C:\Windows\Microsoft.NET\Framework\v4.0.30319\ngen.log to C:\Test\Re\Archived Artifacts\NgenLogs\Framework\v4.0.30319
(19:59.209) [Platform:Testcase] ResultArchive: Copying C:\Windows\Microsoft.NET\Framework64\v4.0.30319\ngen.log to C:\Test\Re\Archived Artifacts\NgenLogs\Framework64\v4.0.30319
(20:04.230) [Platform:Testcase] ResultArchive: Copying C:\Test\Results\Deploy_*** 2024-01-13 11_02_42\Out\OmniLog.html to C:\Test\Re\Archived Artifacts
+ Final Test Result Verification
```

![image](https://github.com/dotnet/msbuild/assets/3809076/14fdf5b1-746d-4663-96ad-b2b1d0d22e04)

The VS instance seems to be stuck during closing.

This correlates with observations on screen capture from the test run - where unloading projects seem to be stuck:

![image](https://github.com/dotnet/msbuild/assets/3809076/f9edc9f9-bc16-48f0-a76c-585520df44a7)

### Steps to collect diagnostics

* In the pipeline [MSBuild-OptProf](https://devdiv.visualstudio.com/DevDiv/_build?definitionId=17389) in the top right corner click ‘Run pipeline’
* Set testMachineCleanUpStrategy to ‘stop’
![image](https://github.com/dotnet/msbuild/assets/3809076/fc0c1546-5ccc-408a-8b8a-c4d25ee55829)

* Click Run to deploy the test run.
* Once the run completes (which takes roughly 3 hours) the test machine should hang around for 3 days, and to get onto the test machine you can use the [DevDivLabConnector (wiki)](https://devdiv.visualstudio.com/DevDiv/_wiki/wikis/DevDiv.wiki/915/DevDivLabConnector) tool. You’ll need the machine name and in [Rerun OptProf on a Lab Machine (wiki)](https://devdiv.visualstudio.com/DevDiv/_wiki/wikis/DevDiv.wiki/2671/Rerun-OptProf-on-a-Lab-Machine?anchor=walkthrough) shows where to get the machine name and how to re-run test.
* Start the ETW collecting prior the repro run:
```
perfview collect /NoGui /Providers=*Microsoft-Build /BufferSize:8096 /CircularMB:8096 /NoNGenRundown /DataFile:<path-to-trace-file-that-will-be-created>
```
* If the issue reproduces (VS hangs in project unloading for several minutes), create 2 or 3 memory dumps (minidump should suffice) couple dozens of seconds appart. For dump creation, you can use e.g. ProcessExplorrer:
![image](https://github.com/dotnet/msbuild/assets/3809076/7db020fe-9ef4-4b0c-9c7d-9dee9242c2d1)

**Notes** 
* It's not clear if the issue is only by timing or by env as well - but it's probably best idea to try to repro on machines that experienced the issue during the initial run. 
* It might not be easy to reproduce - so possibly having more machines from the CI pool to run the repro might help to get it quicker.
* The machines are kept only for certain duration (I believe 48 or 72 hours) - and then it gets force recycled
* Copy out the collected data to some internal share or alternatively sharepoint

**Comment by drewnoakes** [comment]
> minidump should suffice

A minidump isn't going to contain the information we need. We need a full dump in order to see async task chains.

**Comment by YuliiaKovalova** [comment]
Current strategy: track the build state within a week. If no repro, we can close the ticket.

**Comment by JaynieBai** [comment]
It's not repro any more, close it.
