### ISSUE TITLE
[CI/CD]: Do not run full tests when only docs are updated

### ISSUE THREAD

**Issue by f-alizada** [dotnet/msbuild#9782]
### Summary

Currently workflow runs on every update in the PR and runs the full test on the PR with every update. 
However we do not need that when only non source code related changes are made, for instance documentations. 
Example of the PR: https://github.com/dotnet/msbuild/pull/9774

### Background and Motivation

No need to run test on unchanged code

### Proposed Feature

Skip the test runs  in case path changed only in https://github.com/dotnet/msbuild/tree/main/documentation

**Comment by rainersigwald** [comment]
Yeah, no objection here. AFAIK we don't have any dependencies into docs from tests or product code (we do depend on samples from some tests but that's not relevent).

**Comment by JaynieBai** [comment]
Should it build when only docs are updated?

**Comment by f-alizada** [comment]
> Should it build when only docs are updated?

We do no need to run test of MSBuild  when only docs are updated: Please see the example PR: https://github.com/dotnet/msbuild/pull/9774
However as part of this task it is better to verify that there is no any connection between the mentioned folder and the tests, so the coverage will be left the same, and leave pipelines/jobs run in case the connection exists.
