### ISSUE TITLE
Error CS9137 Occurred When Building a MAUI Project Targetting to Windows

### ISSUE THREAD

**Issue by SloneWang** [dotnet/msbuild#9785]
### Description

[Configuration Binding Source Generator](https://learn.microsoft.com/en-us/dotnet/core/whats-new/dotnet-8/runtime#configuration-binding-source-generator) is introduced by .NET8.0, and it works well in my web projects. I attempt to use this generator in my MAUI Blazor App by modifying the .csproj file like:
```
<Project Sdk="Microsoft.NET.Sdk.Razor">
    <PropertyGroup>
        ...
        <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
        <EnableConfigurationBindingGenerator>true</EnableConfigurationBindingGenerator>
        ...
    </PropertyGroup>
    ...
</Project>
```
It does function when targetting to net8.0-android, net8.0-ios, and net8.0-maccatalyst . However, a cs9137 error occurrs when set targetting to net8.0-windows10.0.19041.0. I followed the message and added `<InterceptorsPreviewNamespaces>$(InterceptorsPreviewNamespaces);Microsoft.Extensions.Configuration.Binder.SourceGeneration</InterceptorsPreviewNamespaces>` to project file, that error still occurrs.

### Reproduction Steps

Add codes below in PropertyGroup: 
```
<EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
<EnableConfigurationBindingGenerator>true</EnableConfigurationBindingGenerator>
<InterceptorsPreviewNamespaces>$(InterceptorsPreviewNamespaces);Microsoft.Extensions.Configuration.Binder.SourceGeneration</InterceptorsPreviewNamespaces>
```
Here is my test project [TestMauiBlazor.zip](https://github.com/dotnet/runtime/files/14392099/TestMauiBlazor.zip).

### Expected behavior

The Configuration Binding Source Generator will generate codes, and the compiler will compile the codes successfully.

### Actual behavior

The Configuration Binding Source Generator does generate codes. But the compiler throws a CS9137 error and messages &quot; The 'interceptors' experimental feature is not enabled. Add `<InterceptorsPreviewNamespaces>$(InterceptorsPreviewNamespaces);Microsoft.Extensions.Configuration.Binder.SourceGeneration</InterceptorsPreviewNamespaces>` to your project. &quot;

### Configuration

```
.NET SDK Version: 8.0.201
Operating System: Windows 10.0.22631 x64
maui-windows Version:  8.0.6/8.0.100
```

**Comment by rainersigwald** [comment]
@ericstj nailed it. And a nice workaround!

The full diff on that task invocation is now

```diff
diff --git a/src/Tasks/Microsoft.CSharp.CurrentVersion.targets b/src/Tasks/Microsoft.CSharp.CurrentVersion.targets
index 772d1bbcf8e..f2ff137f100 100644
--- a/src/Tasks/Microsoft.CSharp.CurrentVersion.targets
+++ b/src/Tasks/Microsoft.CSharp.CurrentVersion.targets
@@ -244,21 +244,29 @@ Copyright (C) Microsoft Corporation. All rights reserved.
          ApplicationConfiguration="$(AppConfigForCompiler)"
          BaseAddress="$(BaseAddress)"
          CheckForOverflowUnderflow="$(CheckForOverflowUnderflow)"
+         ChecksumAlgorithm="$(ChecksumAlgorithm)"
          CodeAnalysisRuleSet="$(ResolvedCodeAnalysisRuleSet)"
          CodePage="$(CodePage)"
          DebugType="$(DebugType)"
          DefineConstants="$(DefineConstants)"
          DelaySign="$(DelaySign)"
          DisabledWarnings="$(NoWarn)"
+         DisableSdkPath="$(DisableSdkPath)"
          DocumentationFile="@(DocFileItem)"
+         EmbedAllSources="$(EmbedAllSources)"
+         EmbeddedFiles="@(EmbeddedFiles)"
          EmitDebugInformation="$(DebugSymbols)"
          EnvironmentVariables="$(CscEnvironment)"
          ErrorEndLocation="$(ErrorEndLocation)"
          ErrorLog="$(ErrorLog)"
          ErrorReport="$(ErrorReport)"
+         Features="$(Features)"
+         InterceptorsPreviewNamespaces="$(InterceptorsPreviewNamespaces)"
          FileAlignment="$(FileAlignment)"
+         GeneratedFilesOutputPath="$(CompilerGeneratedFilesOutputPath)"
          GenerateFullPaths="$(GenerateFullPaths)"
          HighEntropyVA="$(HighEntropyVA)"
+         Instrument="$(Instrument)"
          KeyContainer="$(KeyContainerName)"
          KeyFile="$(KeyOriginatorFile)"
          LangVersion="$(LangVersion)"
@@ -271,19 +279,30 @@ Copyright (C) Microsoft Corporation. All rights reserved.
          NoWin32Manifest="$(NoWin32Manifest)"
          Nullable="$(Nullable)"
          Optimize="$(Optimize)"
-            OutputAssembly="@(XamlIntermediateAssembly)"
+         Deterministic="$(Deterministic)"
+         PublicSign="$(PublicSign)"
+         OutputAssembly="@(IntermediateAssembly)"
+         OutputRefAssembly="@(IntermediateRefAssembly)"
          PdbFile="$(PdbFile)"
          Platform="$(PlatformTarget)"
          Prefer32Bit="$(Prefer32Bit)"
          PreferredUILang="$(PreferredUILang)"
-            References="@(ReferencePath)"
+         ProjectName="$(MSBuildProjectName)"
+         ProvideCommandLineArgs="$(ProvideCommandLineArgs)"
+         References="@(ReferencePathWithRefAssemblies)"
+         RefOnly="$(ProduceOnlyReferenceAssembly)"
          ReportAnalyzer="$(ReportAnalyzer)"
+         ReportIVTs="$(ReportIVTs)"
          Resources="@(_CoreCompileResourceInputs);@(CompiledLicenseFile)"
          ResponseFiles="$(CompilerResponseFile)"
-            SkipAnalyzers="true"
+         RuntimeMetadataVersion="$(RuntimeMetadataVersion)"
+         SharedCompilationId="$(SharedCompilationId)"
+         SkipAnalyzers="$(_SkipAnalyzers)"
+         SkipCompilerExecution="$(SkipCompilerExecution)"
          Sources="@(Compile)"
          SubsystemVersion="$(SubsystemVersion)"
          TargetType="$(OutputType)"
+         TargetFramework="$(TargetFramework)"
          ToolExe="$(CscToolExe)"
          ToolPath="$(CscToolPath)"
          TreatWarningsAsErrors="$(TreatWarningsAsErrors)"
@@ -297,6 +316,8 @@ Copyright (C) Microsoft Corporation. All rights reserved.
          Win32Icon="$(ApplicationIcon)"
          Win32Manifest="$(Win32Manifest)"
          Win32Resource="$(Win32Resource)"
+         PathMap="$(PathMap)"
+         SourceLink="$(SourceLink)"
          />
 
 <!-- Only Applicable to the regular CoreCompile:
```

Some of those diffs are intentional (`SkipAnalyzers`) and some look right, but I'm not sure.

@jaredpar heads up I'm going to send a PR to sync these two targets again and will need compiler team review please.

**Comment by simonrozsival** [comment]
@rainersigwald We stared using interceptors in a new MAUI feature and we started hitting this issue because the `XamlPreCompile` task is not passing the `InterceptorsPreviewNamespaces` property to CSC. We can tell customers to use the workaround with a .rsp file, but it would be best to properly fix the issue. Do you think the fix will be ready in time for the .NET 9 release?

**Comment by rainersigwald** [comment]
@simonrozsival yeah, let me get #9786 up to date.

**Comment by rainersigwald** [comment]
@simonrozsival Are you able to test the experimental VS from (internal VS PR) https://dev.azure.com/devdiv/DevDiv/_git/VS/pullrequest/568127? I ran it on the project from the OP and it works (well, you have to disable `EmitCompilerGeneratedFiles` because of https://github.com/dotnet/roslyn/issues/73075). I think we're ready to go but having confirmation from y'all would be nice.

**Comment by simonrozsival** [comment]
@rainersigwald I'm currently on vacation so I won't be able to test it at least for the next two weeks

**Comment by rainersigwald** [comment]
Ok, when you get back it should be in VS int preview and SDK RC1 dailies.
