### ISSUE TITLE
MSB5029 (drive enumeration on wildcard) should be logged befor performing the enumeration

### ISSUE THREAD

**Issue by JanKrivanek** [dotnet/msbuild#9818]
Pointed out by @rainersigwald 

### Context

We currently log the warning only after the enumeration happens: https://github.com/dotnet/msbuild/blob/67f702b535a02be05a696376883bd9cd6d576e38/src/Tasks/CreateItem.cs#L146-L157

However we should log it as soon as the situation is uncovered instead: https://github.com/dotnet/msbuild/blob/67f702b535a02be05a696376883bd9cd6d576e38/src/Shared/FileMatcher.cs#L2109

Which we currently do only when the user explicitly opts-into this being an error.

### Goal
The warning is logged as early as possible - not to let user wondering on stuck build, while the warning still has the same rich info as today.

**Comment by baronfel** [comment]
This would be a good example of an ephemeral message in Terminal Logger - we'd want to show this ASAP in the display because it could mean the build takes way too long

**Comment by JaynieBai** [comment]
@JanKrivanek  From the following code, I can see the warning is logged after the situation bool logDriveEnumeratingWildcard = IsDriveEnumeratingWildcardPattern(fixedDirectoryPart, wildcardDirectoryPart); is uncovered instead.


https://github.com/dotnet/msbuild/blob/5089df85a739c170a6c3ab0493bd2c17b36d81d4/src/Build/Utilities/EngineFileUtilities.cs#L224-L311

**Comment by JanKrivanek** [comment]
Correct - the warning is logged after the files are alreadz enumerated. Though the problem is known before the enumertion happens. So we should log the warning before the enumeration (in FileMatcher).

If I have misunderstood your question, please ask again
