### ISSUE TITLE
Log TaskParameterEvent for scalar task parameters as well

### ISSUE THREAD

**Issue by ladipro** [dotnet/msbuild#9827]
`TaskParameterEvent` with `TaskParameterMessageKind.TaskInput` is currently used only for parameters that are lists. Parameters that are simple strings are logged as a specially formatted low-importance message.

```
Task Parameter: Name=Value
```
where the string `Task Parameter` is localized.

The binlog viewer contains logic to recognize this special message and recover the Name and Value to be rendered in the viewer UI. Since we will use this event for analyzers, it would be unfortunate to add one more place with this suboptimal processing. We should look into logging `TaskParameterEvent` for all parameters.

Preliminary measurements show binlogs getting ~1% bigger if we log both `TaskParameterEvent` and the textual message, and slightly smaller if we log only the structured event.

The tentative plan is to implement double-logging now, and make a note to remove the textual message after some time when we're comfortable breaking old viewers.

**Comment by ladipro** [comment]
@KirillOsenkov please let me know what you think.

**Comment by KirillOsenkov** [comment]
Seems like a good idea. I'd be surprised if anyone depended on the textual message.
