### ISSUE TITLE
[Bug]: PackageCertificatePassword argument does not support password protected certificate files

### ISSUE THREAD

**Issue by omghb** [dotnet/msbuild#9830]
### Issue Description

I have a password protected certificate file (PKCS12) for signing a MAUI (WinUI 3) app as packaged MSIX. So I try to use the `PackageCertificatePassword ` argument to pass the password. This results in:

```
C:\Users\user1\.nuget\packages\microsoft.windowsappsdk\1.3.230724000\buildTransitive\Microsoft.Build.Msix.Packaging.targets(515,5): 
error APPX0105: Cannot import the key file 'C:\Temp\Cert\example.p12'. The key file may be password protected. 
To correct this, try to import the certificate manually into the current user's personal certificate store.
```

The MS documentation writes that this is not supported: [link](https://learn.microsoft.com/en-us/windows/uwp/packaging/auto-build-package-uwp-apps)
> Note that a password is only supported for the private key; using a certificate file that is itself password-protected is not currently supported.

**Workaround**
Removing the password protection from the PKCS12 file enables the file to be used for signing. 

**Security considerations**
- Installing in the personal certificate store (as mentioned in the error) shouldn't be done as the build runs on shared build servers.
- I want to avoid working with unprotected files that contain private keys. The build infrastructure allows to keep those files "secret" but I still prefer to keep the password protection in place.

### Steps to Reproduce

-

### Expected Behavior

PackageCertificatePassword should work for a password protected certificate file (PKCS12).

### Actual Behavior

-

### Versions & Configurations

MSBuild version 17.8.3+195e7f5a3 for .NET

**Comment by rainersigwald** [comment]
Can you please file this at https://github.com/microsoft/windowsappsdk? That appears to be the repo that defines the build logic in question.

**Comment by omghb** [comment]
I added an issue about this here: https://github.com/microsoft/WindowsAppSDK/issues/4255
