### ISSUE TITLE
[Bug]: Target Inputs and Outputs are not working when press build button in .vcxproj

### ISSUE THREAD

**Issue by SilenceTiger** [dotnet/msbuild#9865]
### Issue Description

I want to generating some .h files from .txt files before build. if .txt files are changed or .h files are deleted, could regenerate .h files.

### Steps to Reproduce

1. create a empty c++ project in VS2022, for example generate test.vcxproj
2. create file a.txt, the content is "#define A 1";
3. add code before last </Project>, copy **a.txt** to **b.h**, and **use a.txt** as inputs, **b.h** as outputs.
![image](https://github.com/dotnet/msbuild/assets/13399719/a5065110-2626-4c2b-8a5a-3c2a76a2268d)
4. save the text.vcxproj.
5. use VS2022 to open text.vcxproj, and press **Build** for project.
6. first we can see that **b.h** has been generated, but when changed the content of **a.txt** to: "#define A 2", then press **Build** again, **b.h** will not generated the Task PreBuild will not excute any more unless press **Rebuild**.
7. you can also delete **b.h**, and press **Build** again, Task Prebuild will not excute anymore.

I want to know if there is a better way to write this: generating some .h files from .txt files before build and if .txt files are changed or .h files are deleted, could regenerate .h files.

### Expected Behavior

press **Build** Button will run PreBuild Task to regenerate **b.h** when **a.txt** is changed or **b.h** is missing.

### Actual Behavior

press **Build** Button will not run PreBuild Task to generate **b.h** when **a.txt** is changed or **b.h** is missing.

### Analysis

it seems that inputs and outputs attribute are not working in this case.

### Versions & Configurations

Visual Studio 2022.
msbuild version is 4.8.9032.0.

**Comment by AR-May** [comment]
Team Triage: We believe that this is an issue with Visual Studio, not MSBuild. The incremental build behavior of C++ project is controlled by C++ project system, which is part of VS. Can you [open a Visual Studio feedback ticket instead](https://docs.microsoft.com/visualstudio/ide/feedback-options)?

After it's created, that will open an internal bug which will be routed to the right team. If you post the link here we may be able to help that process go faster.
