### ISSUE TITLE
[Bug]: warning MSB8064 in Visual Studio 2022 Community using cmake's FetchContent_Declare

### ISSUE THREAD

**Issue by ghost** [dotnet/msbuild#9872]
### Issue Description

When I run my cmake project that uses cmake's FetchContent_Declare to download and configure boost libraries with Visual Studio 2019 everything works fine, but when trying to compile with Visual Studio Community 2022, I receive warning messages in random boost libraries from the script like so:

> C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(254,5): warning MSB8064: Custom build for item "D:\projects\...\boostassert-subbuild\CMakeFiles\fadc7e32d087e98c59c0cb2287341fc9\boostassert-populate-test.rule" succeeded, but specified dependency "d:\projects\...\boostassert-subbuild\boostassert-populate-prefix\src\boostassert-populate-stamp\debug\boostassert-populate-install" does not exist. This may cause incremental build to work incorrectly. [D:\projects\...\boostassert-subbuild\boostassert-populate.vcxproj]

And then cmake fails to find those libraries and shows messages like this one:

> CMake Error at build/_deps/boosttest-src/CMakeLists.txt:41 (target_link_libraries):
  Target "boost_prg_exec_monitor" links to:

>    Boost::io

> but the target was not found.  Possible reasons include:

>  * There is a typo in the target name.
>  * A find_package call is missing for an IMPORTED target.
>   * An ALIAS target is missing.

> Call Stack (most recent call first):
> build/_deps/boosttest-src/CMakeLists.txt:57 (boost_test_add_library)

I have to run the configuration step two or three more times to download the libraries properly.
> cmake -S . -B build

I strongly believe this is a MSBuild's bug

### Steps to Reproduce

Here is the script used: https://pastecode.io/s/0pb1021t
CMake version is 3.28.3

### Expected Behavior

Download the libraries at first run

### Actual Behavior

Described in the issue's description

**Comment by rainersigwald** [comment]
Team Triage: That error code is actually part of the VC++ targets and not this repo. Can you [open a Visual Studio feedback ticket instead](https://docs.microsoft.com/visualstudio/ide/feedback-options)?

After it's created, that will open an internal bug which will be routed to the right team. If you post the link here we may be able to help that process go faster.

**Comment by sreisjr** [comment]
Thanks for your feedback.
Here is the link for the ticket: https://developercommunity.visualstudio.com/t/warning-MSB8064-in-Visual-Studio-2022-Co/10617003?port=1026&fsid=e89dd2d1-f4a0-4b91-8029-db51ceced1a3

**Comment by sreisjr** [comment]
Just in case someone who's experiencing the same issues finds this. I was able to work around by using Ninja alongside VS2022 Community.
