### ISSUE TITLE
[Bug]: error MSB4175: The task factory "RoslynCodeTaskFactory" could not be loaded from the assembly "/usr/local/share/dotnet/sdk/8.0.203/Microsoft.Build.Tasks.Core.dll".

### ISSUE THREAD

**Issue by phillippschmedt** [dotnet/msbuild#9878]
### Issue Description

error MSB4175: The task factory "RoslynCodeTaskFactory" could not be loaded from the assembly "/usr/local/share/dotnet/sdk/8.0.203/Microsoft.Build.Tasks.Core.dll". Could not load file or assembly 'System.CodeDom, Version=7.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. Could not find or load a specific file. (0x80131621)

when trying to run a RoslynCodeTaskFactory task in .NET 8 and VS for Mac 17.6.10.

### Steps to Reproduce

Run a RoslynCodeTaskFactory task.

### Expected Behavior

Task runs fine.

### Actual Behavior

Throws error:
error MSB4175: The task factory "RoslynCodeTaskFactory" could not be loaded from the assembly "/usr/local/share/dotnet/sdk/8.0.203/Microsoft.Build.Tasks.Core.dll". Could not load file or assembly 'System.CodeDom, Version=7.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. Could not find or load a specific file. (0x80131621)

### Analysis

Was mentioned here:
https://github.com/dotnet/msbuild/issues/9471
and
https://github.com/dotnet/msbuild/issues/9732

### Versions & Configurations

dotNET SDK: 8.0.203
VS for Mac: 17.6.10

**Comment by rainersigwald** [comment]
Per https://learn.microsoft.com/visualstudio/mac/supported-versions-net, Visual Studio for Mac does not support .NET SDK 8.0.

**Comment by phillippschmedt** [comment]
@rainersigwald  Thanks for sharing the page with me, I was not even aware of that. 

Microsoft being microsoft once again. ¯\_(ツ)_/¯

**Comment by phillippschmedt** [comment]
In case anyone else runs into this problem, a workaround that seems to work is:

sudo cp /usr/local/share/dotnet/sdk/7.X.X.X/System.CodeDom.dll /usr/local/share/dotnet/sdk/8.X.X.X

Replace the 7.X.X.X with one of your 7.x versions installed and the 8.x.x.x with the one your vs for mac is using. Good luck.

**Comment by rainersigwald** [comment]
@jrdodds Can you share a log showing this happening using the .NET 6 or 7 SDK?

**Comment by jrdodds** [comment]
My test was bad. When I corrected my test, net6 and net7 work as expected and net8 fails because it is not supported.
