### ISSUE TITLE
[Built-in analyzer] Multiple projects share the same obj/bin

### ISSUE THREAD

**Issue by ladipro** [dotnet/msbuild#9879]
### Background

This issue tracks one of the BuildCheck analyzers we would like to ship in-box with MSBuild.

### Goal

Implement an analyzer with the following rule: No two projects should have the same `OutputPath` or `IntermediateOutputPath`.

### Notes

Using a shared directory for outputs or intermediates often leads to file access issues and non-deterministic builds.

**Comment by YuliiaKovalova** [comment]
It was implemented as a part of infra: https://github.com/dotnet/msbuild/pull/9735/files#diff-c0ff124955ad434ec4f985b7dc4366f5efa4d0794699cdb0260db5d84492129f

I am checking for the false positives reported...
