### ISSUE TITLE
[Built-in analyzer] TargetFramework and TargetFrameworks are both set

### ISSUE THREAD

**Issue by ladipro** [dotnet/msbuild#9880]
### Background

This issue tracks one of the BuildCheck analyzers we would like to ship in-box with MSBuild.

### Goal

Implement an analyzer with the following rule: The `TargetFramework` and `TargetFrameworks` properties should not be both set in outer builds.

### Notes

Setting both properties leads to unexpected SDK behavior. It is not uncommon for developers to define one of them in a project file and the other in an imported file such as `Directory.Build.props`.

**Comment by glen-84** [comment]
Similar to https://github.com/dotnet/msbuild/issues/9216#issuecomment-1725591503, although that's for a single project.
