### ISSUE TITLE
[Built-in analyzer] Build depends on an environment variable

### ISSUE THREAD

**Issue by ladipro** [dotnet/msbuild#9885]
### Background

This issue tracks one of the BuildCheck analyzers we would like to ship in-box with MSBuild.

### Goal

Implement an analyzer with the following rule: No implicit property derived from an environment variable is used during the build.

### Notes

Depending on the environment leads to build reproducibility problems. Properties should instead be passed to MSBuild explicitly on the command line with `/p`.

**Comment by sharwell** [comment]
Related to #2713
