### ISSUE TITLE
Sync Microsoft.Build version in analyzer template with Version.props during packing

### ISSUE THREAD

**Issue by GangWang01** [dotnet/msbuild#9923]
**Context**
https://github.com/dotnet/msbuild/pull/9789 added a template for custom analyzer. Microsoft.Build version specified in the template should be synced with Version.props during packing. See https://github.com/dotnet/msbuild/pull/9789/files#r1521218723 for more details.
This needs to be done after #9915.

**Goal**
For the future iteration, Microsoft.Build version in analyzer template should be in synced with Version.props.

**Comment by JaynieBai** [comment]
Currently, we can ref https://github.com/dotnet/msbuild/blob/main/documentation/release-checklist.md to update the version manually
