### ISSUE TITLE
[Bug]: Invalid property error does not appear

### ISSUE THREAD

**Issue by f-alizada** [dotnet/msbuild#9943]
### Issue Description

When building project and passing the not valid property name from command line, the build does not report the error.
Example of the invocation: 
dotnet msbuild .\projectfile.csproj /p:"property name"="property value"

### Expected Behavior

The error to be reported 100% of the time.
MSBUILD : error MSB4177: Invalid property. The name "property name" contains an invalid character " ".

### Actual Behavior

Some versions do not report the error. 
I was not able to repro it via latest main branch. 

Todo: 

- Understand the reason why the error not reporting in 17.9.x
- Check if it is fixed in latest main 
- Add tests to the scenario

**Comment by AR-May** [comment]
@Forgind We remember you have had some PR concerning this problem. Do you remember anything about this issue?

**Comment by Forgind** [comment]
I think you're thinking of https://github.com/dotnet/msbuild/pull/9570?

Without checking, that looks like 17.9 or 17.10, so if the problem reproduces in 17.10, we may have a problem.

**Comment by f-alizada** [comment]
@Forgind  Thank you! That is what I was trying to find :) 
It is not repro in main + 17.10. Closing the issue (duplicated)
