### ISSUE TITLE
Loss of Executable Bit When Extracting Archive with Unzip Task

### ISSUE THREAD

**Issue by pepone** [dotnet/msbuild#9949]
I encountered an issue while using the `Unzip` task in the .NET MSBuild repository. I attempted to extract an archive containing executables for macOS and Linux, intending to use these executables in a subsequent task. However, the execution failed due to the loss of the executable bit during the extraction process.

Upon extracting the archive using the `Unzip` task, I observed that the permissions of the extracted files were not preserved correctly. Comparing the permissions of the extracted files with those extracted using the `unzip -x` command revealed a discrepancy:

- Files extracted with `unzip -x` retained the executable bit (`-r-xr-xr-x` permissions).
- Files extracted with the `Unzip` MSBuild task had incorrect permissions (`-rw-r--r--`).

I conducted further testing using `.NET 8`, specifically `System.IO.Compression.ZipFile.ExtractToDirectory`, which correctly preserved the executable bit.

I found a related fix in the .NET repository that addresses this issue: [dotnet/runtime#55531](https://github.com/dotnet/runtime/pull/55531/files).

**Comment by AR-May** [comment]
Team triage: What version of the dotnet sdk are you using (you can use `dotnet --version` to see the version)?

**Comment by pepone** [comment]
I tested with 8.0.101

**Comment by AR-May** [comment]
@JaynieBai can you please take a look at this, try to repro/investigate this?
