### ISSUE TITLE
[Infra] Automate version bump on release branches updates

### ISSUE THREAD

**Issue by JanKrivanek** [dotnet/msbuild#9960]
### Context

`VersionPrefix` should be updated on each commit to our service branches (`vsXX.YY`)

https://github.com/dotnet/msbuild/blob/7ca3c98fad986066bbf2802c863236b4a0f4e34a/eng/Versions.props#L5

This is done to prevent clashes of the produced packages with same version that would cause issues later down the VS insertion pipeline.
There can be some subtle exceptions, but it's easiest just to apply the rule broadly.
Currently we use GH policies to inform us about this:

https://github.com/dotnet/msbuild/blob/7ca3c98fad986066bbf2802c863236b4a0f4e34a/.github/policies/resourceManagement.yml#L119-L154

It still requires user action and can be prone to errors.

### Goal

`VersionPrefix` is incremented on each commit to service branches or on each CI build of those.
It doesn't matter much if this is done asa commit/PR hook or AzDO build step

**Comment by GangWang01** [comment]
The ways to implement this have some obstacles.
- commit/git hook: it requires to configure server side, but it's difficult to do on Github repo.
- PR hook: Github repo can configure web hook, but it requires a website which has permission to edit the PR.
- Azure DevOps build step can make the change, but also requires permission to push the change back to source branch.

I think we can use Azure DevOps build step to easily check version bump on release branch. If the version is not bumped up, we fail PR check with a message in build step that tells the author to update the version.
