### ISSUE TITLE
[Bug]: GetType can still be called as property function, due to case-sensitive comparison

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [dotnet/msbuild#9967]
### Issue Description

<https://github.com/dotnet/msbuild/pull/6769> supposedly prevented calling GetType() as a property function, but it does not recognize the name if written with different letter case, e.g. `gettype`.

### Steps to Reproduce

demo.proj:

```XML
<Project>
  <PropertyGroup>
    <foo>aa</foo>
  </PropertyGroup>

  <Target Name="bb">
    <Message Importance="high" Text="$(foo.gettype().FullName)"/>
  </Target>
</Project>
```

dotnet msbuild demo.proj

### Expected Behavior

```
$ dotnet msbuild demo.proj
MSBuild version 17.9.6+a4ecab324 for .NET
demo.proj(7,32): error MSB4185: The function "GetType" on type "System.String" is not available for execution as an MSBuild property function.
```

### Actual Behavior

```
$ dotnet msbuild demo.proj
MSBuild version 17.9.6+a4ecab324 for .NET
  System.String
```

### Analysis

Perhaps a case-insensitive comparison here would fix it: <https://github.com/dotnet/msbuild/blob/a4ecab324c0586fe69b6bdcc062264b244dd8cd0/src/Build/Evaluation/Expander.cs#L5287>

Alternatively, compare the MemberInfo.Name string after the lookup, rather than the user-specified string.  That might be a larger change, though.

### Versions & Configurations

MSBuild version 17.9.6+a4ecab324 in .NET SDK 8.0.202

**Comment by rainersigwald** [comment]
Nice find! I can't believe that match is not case sensitive in the first place.

**Comment by rainersigwald** [comment]
I'm inclined to say no--because "we already updated the documentation to say you can't do that" but it's definitely a concern. @baronfel do you have thoughts?

**Comment by f-alizada** [comment]
If there is a possibility of low usage, shall we put the change under the changewave?

**Comment by f-alizada** [comment]
I see :) We have the MSBUILDENABLEALLPROPERTYFUNCTIONS, so the need of changewave is lowered. 
Had spent some time understanding why it is not reproducible in debug mode : 
https://github.com/dotnet/msbuild/blob/28f488a74ed75bf5f21ca93ac2463a8cb1586d79/src/Framework/LazyFormattedBuildEventArgs.cs#L183

**Comment by f-alizada** [comment]
@KalleOlaviNiemitalo it was exactly the case.

**Comment by f-alizada** [comment]
To be honest, I was thinking to leave it as it is, since it is in debug mode + the fix is prepared. 
I'm not 100% sure that this fix should be applicble only for `string`, however did not investigate details, there could be cases when ToString method overriden and returns the value == param.GetType().FullName, since the arguments is an array of object `object[] args`.
