### ISSUE TITLE
[Feature Request]: Expose `SolutionFile._solutionFilter` as a read-only

### ISSUE THREAD

**Issue by lsoft** [dotnet/msbuild#9981]
### Summary

If I open `slnf` via

```
            var slnfFile = Microsoft.Build.Construction.SolutionFile.Parse(
                slnfFilePath
                );
```

I will have no access to `slnf` projects, only to `sln` projects. Looks like, there is no problem to expose it:

```
        private HashSet<string> _solutionFilter;     // The project files to include in loading the solution.

       ///The project files to include in loading the solution.
       public IReadOnlySet<string> SolitionFilterProjects => _solutionFilter;
```

If this trivial approach will be approved, I hope I will be able to prepare a PR. :)

### Background and Motivation

I need to access what projects is in `slnf` file.

### Proposed Feature

Open already existing information to public space.

### Alternative Designs

Any design will be better, than nothing. I'm fine to accept any.

**Comment by rainersigwald** [comment]
The solution handling in MSBuild is not intended as a general-purpose library, so we don't expose all functionality like this. MSBuild doesn't need this to be public, so it's meeting our needs. Unfortunately you may need to look into alternate solution libraries.
